### ISSUE TITLE
Plugin capability to add "tabs" for model detail views

### ISSUE THREAD

**Issue by brobare** [nautobot/nautobot#1000]
### Environment
* Python version: 3.8
* Nautobot version: 1.1.4

### Proposed Functionality
Allow for plugins to add "tabs" to model detail pages. For example, ability to add plugin content to another "tab" on a device. The plugin would be able to add a tab and specify a location, say between "Interfaces" and "Power Ports".

<img width="862" alt="Screen Shot 2021-10-14 at 11 47 13 AM" src="https://user-images.githubusercontent.com/53182374/137377687-3d659662-6f4a-468e-937e-bddc02a59d97.png">

Other parts of the UI allow for custom content to be added, such as the NavBar:
https://nautobot.readthedocs.io/en/stable/plugins/development/#navigation-menu-items

### Use Case
As P.D. the plugin developer, I am creating a lot of content that needs to be rendered on model detail pages. For example, I am creating a plugin that tracks all "NMS" related data for a device. I would like to be able to create a new tab on a Device, then render data from the plugin for that device on that tab. Something like:
<img width="1677" alt="Screen Shot 2021-10-12 at 12 30 21 PM" src="https://user-images.githubusercontent.com/53182374/137380382-e1386c44-a560-429f-b5a1-1c7ccdf7fb44.png">
But it would be on the page for that device. 

Example:
<img width="434" alt="Screen Shot 2021-10-17 at 10 12 51 AM" src="https://user-images.githubusercontent.com/53182374/137637838-d4669200-8808-4dc0-92ad-1f22b34d3254.png">

### Database Changes
Dont think there would be any.

### External Dependencies
None

### Requirements

- [x] Provide ability for plugins to provide tabs and panes to particular model views
- [x] Needs Design Review: evaluate minimum amount of boilerplate code for plugins to define the content in the tab views
- [x] Document best-practices and example of plugin-provided tab view

### Needs Refinement

- [x] Can we adopt a simple pattern to "append to the end" or do we need to provide plugin's ability to insert tab into existing order

**Comment by lampwins** [comment]
For context, the tabs today are discrete views that require their own request cycle, which is why this use case was not covered when plugin template extensions were first implemented. That being said, in 1.2 we have the object detail Advanced tab coming which is not its own view and is just using strait bootstrap, so we do now seemingly have a pattern to support this.
