### ISSUE TITLE
Database changes for a failed job are not automatically rolled back

### ISSUE THREAD

**Issue by Johan-EU** [nautobot/nautobot#1005]
### Environment
* Python version: 3.8
* Nautobot version: 1.1.5-beta.1

### Steps to Reproduce
1. Run a job that makes changes to the database and calls `self.log_failure`
2.
3.

### Expected Behavior
Expected behavior is that the database transaction is rolled back. 
The documentation does not state the intended behavior for database changes of failed jobs so the above is my interpretation of expected behavior, failed jobs never change the database in the run method. Even if this is not the intended behavior there can be use cases with an expected failure condition (no program error) that require previous changes to the database to be rolled-back. Rolling back the existing transaction without marking the job as errored and logging a stack trace would be desirable. Using the Nautobot defined AbortTransaction results in a terminated job that remains in status running.

### Observed Behavior
The job status is failed but all changes to the database are persisted.

**Comment by bryanculver** [comment]
@nautobot/core when adopt #2726 and the changes implemented in #3085 will this go away as the atomic transaction happens within a Job author's handling (and they can capture any error done in `transaction.atomic`?

**Comment by bryanculver** [comment]
#2726 will leave it up to the author on how they would like to handle transactions, letting them wrap calls in `transaction.atomic`.
