### ISSUE TITLE
Various docs need to be updated for addition of NAUTOBOT_ROOT and removal of BASE_STORAGE_DIR

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#101]
### Environment
* Python version: n/a
* Nautobot version: 1.0.0b1

### Expected Behavior

- `NAUTOBOT_ROOT` should be documented in either `optional-settings.md` or `required-settings.md`, especially its required interaction with the `$NAUTOBOT_ROOT` environment variable.
- `BASE_STORAGE_DIR` should no longer be referenced in `optional-settings.md` or in `docs/configuration/index.md`

### Observed Behavior

- Neither of the settings documentation files mention `NAUTOBOT_ROOT`
- References to `BASE_STORAGE_DIR` were not removed in #74.

**Comment by chrismarget** [comment]
I'm trying to follow the installation instructions that were just committed today, find that the `nautobot-server init` step is writing the new configuration file to `/opt/nautobot/.nautobot/nautobot_config.py`. The `nautobot-server migrate` follow-up step expects to find the configuration at /opt/nautobot/nautobot_config.py`, isn't happy about the discrepancy.

Is there an environment variable I can set to work around this?

Thanks!

**Comment by glennmatthews** [comment]
Hi, can you confirm that you set the `$NAUTOBOT_ROOT` environment variable to `/opt/nautobot/` before running `nautobot-server init`?

**Comment by chrismarget** [comment]
`nautobot@ip-172-31-73-196:~$ printenv NAUTOBOT_ROOT
/opt/nautobot
nautobot@ip-172-31-73-196:~$ nautobot-server init
Configuration file created at '/opt/nautobot/.nautobot/nautobot_config.py'
nautobot@ip-172-31-73-196:~$`

**Comment by glennmatthews** [comment]
Oh, sorry! We haven't released v1.0.0b2 yet (aiming for today, but we'll see) so at the moment if you did a `pip install nautobot` you're still getting v1.0.0b1, which doesn't have the `NAUTOBOT_ROOT` changes made in #74. If you want the version that matches the docs (with the fixes therein) in the meantime you'll need to `pip3 install git+https://github.com/nautobot/nautobot@develop` to get the latest bleeding-edge version. Sorry for any confusion!

**Comment by chrismarget** [comment]
Excellent, thank you. I saw #74, figured it was related, didn't realize I had only half of the ingredients :)

**Comment by jathanism** [comment]
@chrismarget For the moment if you'd like to continue, please try to install Nautobot directly from the `develop` branch.

Instead of:
```
pip3 install nautobot
```

Run:
```
pip3 install git+https://github.com/nautobot/nautobot@develop
```
