### ISSUE TITLE
Tables include non-sortable columns as sortable columns

### ISSUE THREAD

**Issue by dsykes16** [nautobot/nautobot#1020]
### Environment
* Python version: 3.6.13
* Nautobot version: 1.1.4

### Steps to Reproduce
1. Navigate to https://[root]/extras/git-repositories/
2. Click on **Provides** to sort the list (i.e. GET https://[root]/extras/git-repositories/?sort=provides)

### Expected Behavior
List is sorted by `provided_contents` field

### Observed Behavior
```
<class 'django.core.exceptions.FieldError'>

Cannot resolve keyword 'provides' into field. Choices are: _custom_field_data, _token, backup_repository, branch, created, current_head, destination_for_associations, id, intended_repository, jinja_template, last_updated, name, provided_contents, remote_url, slug, source_for_associations, tagged_items, tags, username
```

### Suggested Fix
Bug appears to have been introduced in https://github.com/nautobot/nautobot/pull/577
https://github.com/nautobot/nautobot/blob/7c3c82dcd01a177227861a027f1531458fe5aa2e/netbox/extras/tables.py#L125

Immediate fix is to change `provides` to `provided_contents` at: https://github.com/nautobot/nautobot/blob/dc883b48826f7e3f40a110b7c1e6c247818349f3/nautobot/extras/tables.py#L200

The values *are* rendered correctly in the table as the template references the correct field:
https://github.com/nautobot/nautobot/blob/dc883b48826f7e3f40a110b7c1e6c247818349f3/nautobot/extras/tables.py#L49-L57

An identical issue occurs when clicking on the **Sync Status** header which attempts a sort on `last_sync_status` which is a non-existent field. I just tried the demo and have only had a few minutes to look at the codebase, so I'm not sure on a fix for this. If the object is being updated along with the git repo, which I assume it may be given the `current_head` field, then `last_updated` should provide the desired functionality; however, I need to dig into the codebase a bit to confirm that.

I'll get a PR up shortly that at least changes `provides` to `provided_contents` and add some tests to programmatically cross-check `Table` definitions against `Model` fields.

**Comment by lampwins** [comment]
@dsykes16 do you have any time to follow up on this? Otherwise core will likely take it on.

**Comment by bryanculver** [comment]
We are overhauling the UI in 2.0 so we should consider this for the new UI. For any potential fixes in 1.5, we should open up specific cases when this arises.

**Comment by dsykes16** [comment]
@lampwins yes, I've got capacity to see this through, I'd honestly forgotten about it. I've got a _significantly_ better understanding of Nautbot's testing framework now and I'm confident I can implement a universal test to find these issues and stick it on the base test class.

**Comment by dsykes16** [comment]
And I also just realized I'm a few months late responding... I previously had GitHub notifications turned off, which wasn't a great idea, but they're on now.
