### ISSUE TITLE
Update tests to ensure model instance are always valid

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot#1034]
### Proposed Changes

Update tests to always validate on save, as an example, the following is missing status being defined

https://github.com/nautobot/nautobot/blob/af9be7678b0ee402b36b7201e2d7a886e8835334/nautobot/dcim/tests/test_filters.py#L552-L590

### Justification

In using the `<model>.objects.create()` instead of `instance = <model>(); instance.validated_save()` will allow model instances to created that are not actually valid records, such as not providing a status where one is required. This leave the API and UI in a bad state in a production environment, and tests should better reflect an actual production environment.

**Comment by bryanculver** [comment]
Possibly consider fixtures or snapshot startup of valid data for test runs.

**Comment by glennmatthews** [comment]
See also #1999, #1334.

**Comment by glennmatthews** [comment]
Generally addressed by our ongoing migration to use data factories rather than hand-crafted data. The issue with omitting `status` fields in particular was due to a bug in our definition of the `StatusField` class (see #3785).
