### ISSUE TITLE
AttributeError when adding VM Component interfaces

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot#1043]
### Environment
* Python version: 3.6.3
* Nautobot version: v1.1.4

### Steps to Reproduce
1. Navigate to Virtualization -> Virtual Machines/
2. Click checkbox of device
3. Expand the "Add Components" button
4. Click "Interfaces"

![image](https://user-images.githubusercontent.com/9260483/139539065-67317d04-186b-494b-8c85-d6e100b91289.png)

![image](https://user-images.githubusercontent.com/9260483/139539095-4f250041-d3b2-46f0-87c7-5626922231eb.png)

### Expected Behavior

Ability to be able to bulk update interfaces to vm's

### Observed Behavior

Stacktrace

**Comment by jathanism** [comment]
Well this one is quite the metaprogramming pickle. Thanks for the report @itdependsnetworks!

Detailed meta traceback shows something funky getting passed into the the form:

![Cursor_and_AttributeError__type_object__VMInterface__has_no_attribute__get__-_networktocode-llc_-_nautobot](https://user-images.githubusercontent.com/138052/140197523-706a2bda-bd92-46df-b9fa-f57efceefc51.png)

**Comment by romanukes** [comment]
I'd like to work on this one
