### ISSUE TITLE
Spike on the Location model

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#1052]
### Proposed Changes

Per #774, we agree we want to implement a new `Location` model but how do we do it? We need to decide a path forward considering the implications of the existing `Site` and `Region` objects. Do we replace them? Augment them? Implement Location side-by-side?

### Justification

See: #774

### Requirements

- Location and LocationType Models Exist
- Device can have Location assigned to them

**Comment by darcynz** [comment]
Adding a location object model would be simpler in terms of users not having to rebuild their sites / regions...

**Comment by Thetacz** [comment]
I see `Region`s/`Site`s as organization units and `Location`s as actual physical ones. So adding new model makes more sense for me, each `Location` requiring a `Site`. The problem `Location`s should solve for us is "Where do I physically find a `Device`/`Rack`". There is a workaround for this using combination of `Rack Group` and `Rack` (described in [#774 comment](https://github.com/nautobot/nautobot/issues/774#issuecomment-988933493)), but it makes a bit of mess. Having `Location` for each floor, room or shelf would be much cleaner solution.

**Comment by pke11y** [comment]
It would also be good to be able to attach an image to a `Location` object.

**Comment by tbotnz** [comment]
@glennmatthews i c you are working on this PR. Itd be cool if there was support for a geojson polygon in a json field against the proposed location object to help with use cases for when  reverse geo coding / location matching is required

**Comment by glennmatthews** [comment]
Thanks @tbotnz for the suggestion! I like the idea but IMHO it makes sense as an additional feature request that can link back to #774 as the base feature - trying to avoid too much feature creep in the "1.0" version of this feature. :-)

**Comment by glennmatthews** [comment]
Implemented in #1891; remaining action items will be tracked under #774
