### ISSUE TITLE
Documentation bug - 404

### ISSUE THREAD

**Issue by edurguti** [nautobot/nautobot#1059]
### Environment
* Python version:3.8
* Nautobot version:1.1.4

### Steps to Reproduce
1. Open URL: https://nautobot.readthedocs.io/en/stable/installation/
2.Click on "Deploying Nautobot" Under Optional dependencies
3. Getting a non styled page (Github 404) https://nautobot.readthedocs.io/en/stable/installation/deploying-nautobot

show Deployment Documentation

404

**Comment by glennmatthews** [comment]
Thanks for the report! This was previously reported as #1023 and fixed in #1024, which will be included in the next release.
