### ISSUE TITLE
Feature Request: Contact

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#1066]
### Environment
* Python version: 3.9
* Nautobot version: 1.1.4

### Proposed Functionality

As part of the Nautobot Plugin Device Lifecycle Management plugin the model of a contact was introduced there. 

### Use Case

1. This is something that could be used in many other places as well. Such as assigning ownership of devices.
2. Ownership of sites
3. By moving into core then other plugins can leverage the model and have a single unified contact experience

### Database Changes

Create new data model, user

### External Dependencies

None

**Comment by jathanism** [comment]
How about we turn this into a discussion to cover how we might model this and how it would be associated with other objects?
