### ISSUE TITLE
Unable to distinguish VRF with the same name (for selection, import)

### ISSUE THREAD

**Issue by u1735067** [nautobot/nautobot#1067]
### Environment
* Python version: 3.9
* Nautobot version: 1.1.4

### Steps to Reproduce
1. Create 2+ VRFs with the same name in different tenants (or not), eg. `MGMT`

2.a. Use the `IP Address` import form and specify the created VRF : 
```
address,status,vrf
1.2.3.4/32,active,MGMT
```
2.b. Edit an IP address // or in the IP Address list, select one or more IP for mass edit

### Expected Behavior
a. The import works (allow better VRF selection in the form)
b. The VRFs are distinguishable

### Observed Behavior
a. The import fails with the error: `Row 1 vrf: "MGMT" is not a unique value for this field; multiple objects were found`
b. The desired VRF can't be selected knowingly

### Workaround

Rename the desired VRF to an unique name each time there's need to select it, and rename it back.

### Additional informations

Maybe covered by <https://github.com/nautobot/nautobot/issues/1032>?

**Comment by jathanism** [comment]
Ugh the lack of database-level uniqueness constraints strikes again! This duplicate names validation is only occurring in the CSV import form field.

We'll have to give this one a proper look to see how to address this. Thanks for the submission!

**Comment by jathanism** [comment]
This is unfortunately a problem we inherited from NetBox and there's no easy way to solve it without introducing backwards-incompatible database schema changes to more strictly enforce uniqueness. And this isn't the only issue of this kind. We will be doing a comprehensive data modeling review as a part of the v2.0 release roadmap. At this time we will not be able to provide a solution to this problem.

**Comment by lampwins** [comment]
This falls under https://github.com/nautobot/nautobot/issues/1574

**Comment by lampwins** [comment]
@glennmatthews I think we are good here? Thoughts?

**Comment by glennmatthews** [comment]
CSV import uniqueness is solved in 2.x, agreed.
