### ISSUE TITLE
Embed optional dependencies in the official Docker image (LDAP, SSO, storage, ..)

### ISSUE THREAD

**Issue by u1735067** [nautobot/nautobot#1068]
### User Story

As Isabella the Infrastructure Owner,

I want to have Docker images with optional dependencies preinstalled, to be ready for features such as LDAP, SSO or remote storage

So that I'm able to deploy Nautobot without rebuilding a custom Docker image, which is painful in closed network environment (`django-auth-ldap` requires `python-ldap` which requires some system dependencies, so you have to be able to access Pypi + the base distro repos in this case, or build the image on another internet connected host, or construct a dependency list to fetch the packages manually)

I will know this is done when:
* the Dockerfile is updated with the dependencies
* the Docker images embed the optional dependencies

 
### Database Changes (Optional)

None

### External Dependencies (Optional)

None not mentioned in the documentation.

### Additional informations

Found optional deps : 
* https://nautobot.readthedocs.io/en/stable/configuration/authentication/ldap/ : `django-auth-ldap`
* https://nautobot.readthedocs.io/en/stable/configuration/authentication/sso/: `social-auth-core[openidconnect]`, `social-auth-core[saml]`(, `social-auth-app-django`?)
* https://nautobot.readthedocs.io/en/stable/installation/nautobot/#remote-file-storage: `django-storages`
* https://github.com/nautobot/nautobot/blob/develop/examples/logging/advanced_requests.md: `django-request-logging`

I knew [Netbox Docker](https://github.com/netbox-community/netbox-docker) is providing LDAP out-of-the-box for a long time, so I was surprised to see that Nautobot is not when I tried to enable it 🙁

I already recreated a Nautobot image from Alpine to add this feature (225MB for Alpine, 379MB for Debian-slim), and adapted https://github.com/netbox-community/netbox-docker/blob/release/configuration/ldap/ldap_config.py for Nautobot with more options, if you're interested in this adapted file.

Maybe the configuration loader (`conf.d` like) could be ported too for easier integration?

**Comment by jathanism** [comment]
@u1735067 Thank you for the thoughtful submission. We'll need to review how to approach this.

@nniehoff I would love to have your feedback on this one. Would there be much overhead to just including these dependencies in our container image? Seems to me it wouldn't be too much?

**Comment by nniehoff** [comment]
I like this idea.  I did some initial research.  I already hate the size of our base container being 395MB to start with... However, adding these dependencies takes our final image to 406MB.  I think the size hit is very acceptable for the benefit.  I'll work on cleaning this up for a PR.
