### ISSUE TITLE
GraphiQL JS XSS Vulnerability

### ISSUE THREAD

**Issue by FragmentedPacket** [nautobot/nautobot#1077]
### Environment
* Python version: 3.6
* Nautobot version: 1.1.4

### Summary
We have a client that their Webinspect scanner has reported the XSS flaw within GraphiQL JS package that we're using.

https://github.com/graphql/graphiql/blob/main/docs/security/2021-introspection-schema-xss.md

Discussed internally and don't think we're actually affected by it, but it's showing up in scans due to advisories.

To remedy, we should upgrade GraphiQL to at least 1.4.7, but the latest is 1.5.1.

**Comment by glennmatthews** [comment]
Thanks for the report!
