### ISSUE TITLE
Custom Fields not filterable for Power Panels

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#1078]
### Environment
* Python version: 3.6
* Nautobot version: 1.1.5

Filtering by custom fields in power panels doesn't seem to work.

### Steps to Reproduce
1. Create a custom text field associated with the dcim power panel model
2. Create some power panels with various values for the custom field
3. In the power panels list view filter for one of the values entered for the custom field.
4. The list of power panels is not filtered

### Expected Behavior

Searching by the custom field value should filter the list of power panels

### Observed Behavior

Searching by the custom field value does not filter the list of power panels

**Comment by nniehoff** [comment]
I have confirmed the same behavior in Nautobot 1.2

<img width="1666" alt="Screen Shot 2021-11-16 at 6 01 32 AM" src="https://user-images.githubusercontent.com/14947575/141973791-a66ba072-beda-4568-b4ca-a86cb420202b.png">

**Comment by glennmatthews** [comment]
Thanks for the report! Looks like `PowerPanelFilterSet` (and a number of other device-component filtersets) is missing the necessary inheritance from `CustomFieldModelFilterSet` that would provide this logic.
