### ISSUE TITLE
Computed Fields: Returning template if variable doesn't exist.

### ISSUE THREAD

**Issue by FragmentedPacket** [nautobot/nautobot#1086]
### Environment
* Python version: 3.6
* Nautobot version: 1.1.5

### Steps to Reproduce
1. Create the following computed field
![image](https://user-images.githubusercontent.com/29315002/142428032-6e39fbfe-7c6c-4618-bf70-b488fedd0600.png)
2. Navigate to a device and check the computed field
![image](https://user-images.githubusercontent.com/29315002/142428099-d5fc3a1b-d054-471a-90c7-242cef11013e.png)

### Expected Behavior
For it to return the fallback value due to not being able to render

### Observed Behavior
The template is returned in the field instead

It appears https://github.com/nautobot/nautobot/blob/1ea660e02a7ab6e0487683a5c7bdbc37bf35bdf4/nautobot/extras/models/customfields.py#L87 returns the template back and no exception is raised. Not sure why the function is returning it, but that appears to be the culprit and thanks to @glennmatthews for pointing us in that direction.

**Comment by glennmatthews** [comment]
Needs investigation to understand the Jinja2 behavior being seen.

**Comment by jathanism** [comment]
I am unable to reproduce this in Nautobot v1.2.1. @FragmentedPacket Can you please double check and confirm? Thank you.
