### ISSUE TITLE
Separate Site Address information into distinct fields

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#1087]
### User Story

As Nick the Network Automation Engineer I wish to be able to get the state information in a simple programmatic fashion when possible from the Nautobot Site information. Today this cannot be done as the field is a whole address.

I will know this is done when I can poll an API endpoint to get the state field when filled in for a location.

 
### Database Changes (Optional)

Update to site

### External Dependencies (Optional)
None

**Comment by glennmatthews** [comment]
The challenge here (and the reason, I suspect, for the current design) is that different parts of the world have entirely different formats for addresses and their components. See for example https://www.mjt.me.uk/posts/falsehoods-programmers-believe-about-addresses/

**Comment by jvanderaa** [comment]
Agreed. And this we can solve for in the immediate with Custom Fields. The thought is that we have the data in one way, although that is a much easier to build when it is free form text. I'm good with a significant push out on this FR.

**Comment by jvanderaa** [comment]
Or a complete decline for now as well. It was just an idea as we look at using the SOT. We will probably go the custom fields route regardless.

**Comment by jathanism** [comment]
We agreed that this is not worth pursuing at this time.
