### ISSUE TITLE
Dockerfile Error building target: final with nautobot_config.append.py

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#1088]
### Environment
* Python version: 3.8.10
* Nautobot version:  1.1.5b1

### Steps to Reproduce
1. create a /opt/nautobot/nautobot_config.append.py
2. invoke -e buildx --target=final
3.

### Expected Behavior
Build succeeds and merged nautobot_config.py file is stored in container

### Observed Behavior

Error in step 34 [final 10/10] (see below)

```bash
#33 [final  9/10] WORKDIR /opt/nautobot
#33 DONE 0.1s

#34 [final 10/10] RUN nautobot-server init &&     cat /opt/nautobot/nautobot_config.append.py >> /opt/nautobot/nautobot_config.py &&     rm -f /opt/nautobot/nautobot_config.append.py
#34 0.849 A configuration already exists at /opt/nautobot/nautobot_config.py. Please backup and remove it or choose another path.**
#34 DONE 1.0s
```

**Comment by lampwins** [comment]
@jifox we are unable to reproduce this on v1.3.6, can you see if this is still any issue for you?

**Comment by lampwins** [comment]
@jifox any luck with this?

**Comment by jifox** [comment]
I don't have this issue anymore
