### ISSUE TITLE
404 error when creating a circuit termination for circuit

### ISSUE THREAD

**Issue by brobare** [nautobot/nautobot#1098]
### Environment
* Python version: 3.8.10
* Nautobot version: 1.2.0b1

### Steps to Reproduce
1. Go to a circuit.
2. Click on the "Add" button to terminate the circuit

### Expected Behavior
Ability to add the circuit termination. Has worked in previous versions, but seems to have broken in the 1.2.0 beta.

### Observed Behavior
404 error, see screenshot.
<img width="933" alt="Screen Shot 2021-11-23 at 9 11 51 AM" src="https://user-images.githubusercontent.com/53182374/143071949-1a86a775-ddeb-4f6e-bf1f-6a865b90e33f.png">

**Comment by glennmatthews** [comment]
Looks to have been broken by this change in ea0e921fe1044e60e44ed1de3eccdbab6ff7195d, which was making it possible to reference an existing object by fields other than `slug` and `pk` (such as custom fields, which are uniquely identified by `name`):

```diff
     def get_object(self, kwargs):
         # Look up an existing object by slug or PK, if provided.
-        if "slug" in kwargs:
-            return get_object_or_404(self.queryset, slug=kwargs["slug"])
-        elif "pk" in kwargs:
-            return get_object_or_404(self.queryset, pk=kwargs["pk"])
-        # Otherwise, return a new instance.
+        if kwargs:
+            return get_object_or_404(self.queryset, **kwargs)
         return self.queryset.model()
```

**Comment by jathanism** [comment]
> Looks to have been broken by this change in [ea0e921](https://github.com/nautobot/nautobot/commit/ea0e921fe1044e60e44ed1de3eccdbab6ff7195d), which was making it possible to reference an existing object by fields other than `slug` and `pk` (such as custom fields, which are uniquely identified by `name`):
> 
> ```diff
>      def get_object(self, kwargs):
>          # Look up an existing object by slug or PK, if provided.
> -        if "slug" in kwargs:
> -            return get_object_or_404(self.queryset, slug=kwargs["slug"])
> -        elif "pk" in kwargs:
> -            return get_object_or_404(self.queryset, pk=kwargs["pk"])
> -        # Otherwise, return a new instance.
> +        if kwargs:
> +            return get_object_or_404(self.queryset, **kwargs)
>          return self.queryset.model()
> ```

Compare our change to the custom `get_object()` to the Django core version:

https://github.com/django/django/blob/main/django/views/generic/detail.py#L20-L56

**Comment by glennmatthews** [comment]
> Compare our change to the custom `get_object()` to the Django core version:
> 
> https://github.com/django/django/blob/main/django/views/generic/detail.py#L20-L56

So that change was made to allow us to do `get_object(kwargs={"name": "foo"})` specifically for the case of custom field views (where the identifying key is `name` rather than `slug` due to https://github.com/nautobot/nautobot/issues/824). It might be that we could address that requirement without breaking the other uses of `get_object` by just adding a specific `elif "name" in kwargs:` or even something really hacky like `elif "name" in kwargs and self.queryset.model == CustomField`...

**Comment by glennmatthews** [comment]
> Could we add 'slug' to the custom field model?

See #824. The `name` field really is/should be the `slug`. We could add a separate `slug` field but it would be mostly redundant with the existing `name` field, and custom fields already have `name`, `label`, and `description` fields.
