### ISSUE TITLE
Add 'Primary' IP role

### ISSUE THREAD

**Issue by ggidofalvy-tc** [nautobot/nautobot#1099]
### Environment
* Python version: 3.9.7
* Nautobot version: latest stable version

### Proposed Functionality
I'd like to propose extending the current list of IP roles with a new role, the 'Primary' role.

### Use Case
The existence of the Secondary role, but not a Primary role seems to stem from the configuration logic of Cisco IOS, in which IP addresses *not marked* as secondary addresses are considered primary IP addresses.

In some NOSes, one can instead mark an IP address as the primary IP address of a (loopback) interface, which means that given IP address will be used as a source address in case a packet needs to originate from said interface (additionally, the address marked as the primary is frequently used in dynamic template generation login of the BNG/subscriber management of both Cisco and Juniper). Otherwise, all IP addresses on the interface are treated equal.

At the moment, it is not possible to model the 'primary' address of an interface easily in Nautobot. Setting all additional addresses on the interface as 'Secondary' is a possible work-around, but in that case, one needs to check for the existence of IP addresses of the same address family marked as 'Secondary' before one can determine that the IP without a role should indeed be marked specifically as the 'Primary' IP address of an interface.

This might introduce a bit of redundancy into Nautobot's data model, so I perfectly understand if this feature request cannot be accommodated for. 

### Database Changes
Likely not, just introducing a new value within IPAddressRoleChoices (might need a small migration in case the enum index needs to be update.)

### External Dependencies
n/a

**Comment by glennmatthews** [comment]
Thanks for the feature request! This might be more generally addressed in the long term by #1063, but may also be worth considering as a shorter-term interim feature.

**Comment by jcsicard** [comment]
While at it, I’d also suggest a “multicast” role as we currently have to abuse the anycast role to not trigger duplicate ip warnings

**Comment by jathanism** [comment]
> While at it, I’d also suggest a “multicast” role as we currently have to abuse the anycast role to not trigger duplicate ip warnings

This raises an important point that just adding an additional role isn't as simple as it sounds. There are logical considerations in the core tied to some of these individual role values. If we were to add "multicast", what other implications would there be? Would we also need to account for the ability to add duplicate objects?

The same goes for "primary". Does this introduce confusion with setting "primary IP" on an interface assignment or on a device object? We need tot think deliberately about these things. So, please let us know your thoughts!

**Comment by bryanculver** [comment]
Should this be a property on the through table of #2403?

**Comment by jathanism** [comment]
> Should this be a property on the through table of #2403?

Yes.

**Comment by lampwins** [comment]
This is now possible with the generic role model in 2.0
