### ISSUE TITLE
Provide health check for celery beat

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#1102]
### Environment
* Python version: 3.6
* Nautobot version: 1.2.0b1

We need to provide a healthcheck for Celery Beat.  In the docker-compose development file, we are using `nautobot-server health_check` for the Celery pods today.  Unfortunately, this health check doesn't check the health of the Celery worker or Celery beat.  The helm chart uses a slightly different approach for the celery worker which is:

```no-highlight
nautobot-server celery inspect ping --destination celery@$HOSTNAME
```

This works great for the Celery workers, but it doesn't work for Celery beat.  In some [quick research](https://thetldr.tech/how-to-perform-healthcheck-of-celery-beat/), we may need to implement a simple function to make this happen.  I wanted to get this open before we ship 1.2.

**Comment by gneville-ot** [comment]
@nniehoff - Is there any update to this?

I've spotted that the health check applied to celery-beat in the Helm charts is `nautobot-server celery inspect ping --destination celery@$HOSTNAME` but won't work

**Comment by Kircheneer** [comment]
Possibly something like this can help? https://github.com/celery/celery/issues/4079#issuecomment-1270085680

**Comment by glennmatthews** [comment]
That looks to be worker-specific to me, and what we're looking for in this issue is a healthcheck for beat rather than the workers. Thanks though!

**Comment by Kircheneer** [comment]
I thought that maybe there would be beat signals to cover the functionality, but it appears there is only [beat-init](https://docs.celeryq.dev/en/stable/userguide/signals.html#beat-init) and nothing after that.

**Comment by glennmatthews** [comment]
Backported in #5430.
