### ISSUE TITLE
Health check for celery workers causes significant performance impact

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#1106]
### Environment
* Python version: 3.6
* Nautobot version: 1.2.0b1

### Steps to Reproduce
1.  Run the docker compose with celery
2.  Watch the CPU Usage of that docker container

### Expected Behavior

Health checks should not cause a performance impact

### Observed Behavior

CPU spikes are fairly extreme

### Suggested fix

Move away from using the CLI `nautobot-server health_check`

**Comment by dgarros** [comment]
is this issue specific to docker compose ?

**Comment by nniehoff** [comment]
@dgarros no, it is applicable to k8s as well, however, in the helm charts for k8s we use a different health check, I thought we had gotten it back ported here as well but we have not.  The fix is in #1108 but we need to figure something out for #1102

**Comment by dgarros** [comment]
@nniehoff, thanks for the clarification. If it's not specific to docker-compose i think we should update the description of this issue because it's misleading, as you know, some users are using docker but neither docker-compose nor the helm-chart
