### ISSUE TITLE
Support getting changelog via GraphQL

### ISSUE THREAD

**Issue by jakubkrysl** [nautobot/nautobot#1110]
### Environment
* Python version: 3.6.8
* Nautobot version: 1.1.5

### Proposed Functionality
Please add support for getting object changes using GraphQL. 

### Use Case
There are quite a lot object changes in our Nautobot instance. Being able to get those through GraphQL would reduce stress on the server.

### Database Changes
None

### External Dependencies
None

**Comment by glennmatthews** [comment]
As a first pass, simply adding `@extras_features("graphql")` to the `ObjectChange` model may do the trick here.

**Comment by jvanderaa** [comment]
@glennmatthews assign to @josh5276 or myself.

**Comment by bryanculver** [comment]
Adding `changes = GenericRelation(to="extras.ObjectChange", content_type_field="changed_object_type", object_id_field="changed_object_id")` to `ChangeLoggedModel` should help simplify the accessor (also allowing for `instance.changes` to be a thing)

Then with the changes coming in #4163 we might be able to easily teach GraphQL the schema.

**Comment by lampwins** [comment]
Looks like this was added a while ago.
