### ISSUE TITLE
Circuit/cable trace broken when using single-termination circuits

### ISSUE THREAD

**Issue by ggidofalvy-tc** [nautobot/nautobot#1118]
### Environment
* Python version: 3.7.3
* Nautobot version: 1.1.5

### Steps to Reproduce
1. Create Device with at least one Interface
2. Create Circuit with a single Circuit Termination -- e.g. an Internet transit or an IX
3. Connect Interface to Circuit Termination with a Cable
4. Run the `trace` API function on the Interface

### Expected Behavior
I would get a one-item tuple back in the API response, containing the Device's Interface, followed by the Cable and finally the Circuit Termination of the Circuit.

### Observed Behavior
I received an error, see below:

```
{"error": "UUID('1739cb71-2173-5bff-91a6-adb03ce073c0')", "exception": "KeyError", "nautobot_version": "1.1.5", "python_version": "3.7.3"}
```

This breaks all Internet, Peering and IX circuits migrated from our NetBox. Since there's no equivalent of a (network) Provider in Nautobot yet, we're unable to model these circuits in a way that can be processed by our automation.

Additionally, in case of single-termination circuits, the `connected_endpoint` parameter just shows as `none` in the API response -- in NetBox, this was (correctly) shown as `circuits.circuittermination`.

**Comment by smk4664** [comment]
I can take a look at this, I did a little work with the changes for CircuitTermination.

**Comment by smk4664** [comment]
@ggidofalvy-tc I was unable to replicate the first part of your issue.  When trying the same steps you outlined, I got the following:

```
[
    [
        {
            "id": "e0173340-2fd3-45e5-820f-aa7f60c925fe",
            "url": "http://192.168.64.5/api/dcim/interfaces/e0173340-2fd3-45e5-820f-aa7f60c925fe/",
            "device": {
                "id": "382f62fc-eb55-4a3b-967a-f1c3302182af",
                "url": "http://192.168.64.5/api/dcim/devices/382f62fc-eb55-4a3b-967a-f1c3302182af/",
                "name": "sw01",
                "display": "sw01"
            },
            "name": "FastEthernet1/1",
            "cable": "b7f79b9a-fdf2-44c8-af3f-24fa23577ff7",
            "display": "FastEthernet1/1"
        },
        {
            "id": "b7f79b9a-fdf2-44c8-af3f-24fa23577ff7",
            "url": "http://192.168.64.5/api/dcim/cables/b7f79b9a-fdf2-44c8-af3f-24fa23577ff7/",
            "type": "",
            "status": {
                "value": "connected",
                "label": "Connected"
            },
            "label": "",
            "color": "",
            "length": null,
            "length_unit": ""
        },
        {
            "id": "c49ad841-b9a2-4d09-9d23-d11032f461c0",
            "url": "http://192.168.64.5/api/circuits/circuit-terminations/c49ad841-b9a2-4d09-9d23-d11032f461c0/",
            "circuit": {
                "id": "0e43a2fb-bf3c-4c44-aaba-a0828c53367f",
                "url": "http://192.168.64.5/api/circuits/circuits/0e43a2fb-bf3c-4c44-aaba-a0828c53367f/",
                "cid": "10001",
                "display": "10001"
            },
            "term_side": "A",
            "cable": "b7f79b9a-fdf2-44c8-af3f-24fa23577ff7",
            "display": "Side A"
        }
    ]
]
```

I also do not see the connected_endpoint parameter.

**Comment by ggidofalvy-tc** [comment]
After upgrading to 1.2.2, I no longer see this issue happening and the connected_endpoint parameter is properly populated yet again.
