### ISSUE TITLE
Truncate device names on overflow in equipment view(s)

### ISSUE THREAD

**Issue by bmagistro** [nautobot/nautobot#1119]
### Environment
* Python version: 3.6.8
* Nautobot version: 1.1.5
* OS: Cent 7.7

### Use Case + Proposed Functionality
When using fqdns for devices, such as `longhostname.part.net.thing.sub.domain.tld` this tends to be too long to fit in the rack/equipment view.  With the style being centered you loose the leading and trailing portions of the text.  In our case it has resulted in using only a portion of the fqdn  There is already alternate text when hovering over the clickable entry so truncating the value to a fixed size seems like it would be acceptable.

I believe this would just be UI changes only and should have not DB or external dependencies.  It may be possible to implement this with just CSS styling but some very quick testing did not work for me (Chrome) so not too hopeful (https://bugs.chromium.org/p/chromium/issues/detail?id=366550).  If open to the idea, would be willing to work on a possible patch.

**Comment by bmagistro** [comment]
I attempted to get this to work with `clip-path` but haven't been able to figure it out and likely need to defer to someone with more svg experience.  The alternative I had in mind is `foreignObject` and embedding html to be able to truncate using css however this is not supported in svgwrite (https://github.com/mozman/svgwrite/issues/70) at this time.

**Comment by Thetacz** [comment]
Thanks for reporting this. We're seeing the same in our instance, fixing this would be nice.
![image](https://user-images.githubusercontent.com/26114847/145540074-00f6ffee-5aad-4af9-8d66-19e706681108.png)
