### ISSUE TITLE
nautobot-server has no command 'start'

### ISSUE THREAD

**Issue by 991jo** [nautobot/nautobot#112]
### Environment
* Python version: 3.7.3
* Nautobot version: 1.0.0b1
* Debian 10, latest updates (2021-03-08)

### Steps to Reproduce
1. Follow the nautobot installation instructions (install dependencies, install database, install nautobot itself via pip, create the config file, add a user, run a test server...) - the testserver works.
2. create the uwsgi.conf and systemd files
3. start the nautobot.service systemd unit. (that executes the `nautobot start` commant)

### Expected Behavior
The server starts.

### Observed Behavior
nautobot-server does not know the command `start`

```
(nautobot) nautobot@nautobot:~$ nautobot-server start
Unknown command: 'start'. Did you mean startapp?
Type 'nautobot-server help' for usage.
```
Here is the help output:
```
(nautobot) nautobot@nautobot:~$ nautobot-server help

Type 'nautobot-server help <subcommand>' for help on a specific subcommand.

Available subcommands:

[auth]
    changepassword
    createsuperuser

[cacheops]
    cleanfilecache
    invalidate

[contenttypes]
    remove_stale_contenttypes

[core]
    generate_secret_key

[dcim]
    trace_paths

[debug_toolbar]
    debugsqlshell

[django]
    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    sendtestemail
    shell
    showmigrations
    sqlflush
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    test
    testserver

[django_rq]
    rqenqueue
    rqscheduler
    rqstats

[drf_yasg]
    generate_swagger

[extras]
    nbshell
    renaturalize
    rqworker
    runjob
    webhook_receiver

[graphene_django]
    graphql_schema

[rest_framework]
    generateschema

[sessions]
    clearsessions

[staticfiles]
    collectstatic
    findstatic
    runserver

[utilities]
    makemigrations
    migrate
```
It looks like there is no start command.

**Comment by glennmatthews** [comment]
Sorry for the confusion! The docs at https://nautobot.readthedocs.io/en/latest/ have already been updated to reflect the upcoming 1.0.0b2 release, which hasn't been published yet. In the short term, instead of `pip3 install nautobot`, please do `pip3 install git+https://github.com/nautobot/nautobot@develop` when following the online documentation.

**Comment by 991jo** [comment]
okay, thanks, that solves the problem.
