### ISSUE TITLE
UI - Buttons not visible if browser width is too narrow

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#1127]
### Environment
* Python version: 3.9
* Nautobot version: v1.2.0b2

### Steps to Reproduce
1. Open Nautobot in browser
2. Narrow the brwser width until the search field is on the 2nd line
3.

### Expected Behavior

Buttons should be visible

![image](https://user-images.githubusercontent.com/8406301/144742910-8b39055b-2293-4ed4-bf8b-0a958b1fbdac.png)

### Observed Behavior

Buttons are barely visible

![image](https://user-images.githubusercontent.com/8406301/144742811-96be33e2-162e-453c-84b5-36c36c831b69.png)

**Comment by glennmatthews** [comment]
Appears to be a CSS bug - as the browser window narrows, the menu items eventually collapse as intended into a single "hamburger" button, but before reaching that point, the search box and eventually the user dropdown both get shoved down to a new line instead of collapsing.
