### ISSUE TITLE
AUTH_LDAP_FIND_GROUP_PERMS does not work

### ISSUE THREAD

**Issue by UnicodeTreason** [nautobot/nautobot#1128]
### Environment
* Python version: 3.6
* Nautobot version: v1.2.0b1

Note I am using the Docker container.

### Steps to Reproduce
1. Configure LDAP [(As per docs)](https://nautobot.readthedocs.io/en/stable/configuration/authentication/ldap/#user-groups-for-permissions) including the option AUTH_LDAP_FIND_GROUP_PERMS
2. Create Group in Nautobot that matches AD Group name
2. Login with a user

### Expected Behavior
I expect the user to get automatically assigned to the group, so that new users automatically get permissions based on their LDAP group membership. This expectation comes from the wording of the setting and the comment provided with it "# For more granular permissions, we can map LDAP groups to Django groups."

### Observed Behavior
User does not get assigned to the group.

**Comment by bryanculver** [comment]
@UnicodeTreason Can you provide some additional details to reproduce this bug?

- AD group name
- Group name created in Nautobot
- All Nautobot related LDAP config details

We suspect this to be a gap in documentation.

**Comment by UnicodeTreason** [comment]
Hey mate,

I no longer have the exact configuration I was using at the time (Using a hacky MIRROR_GROUPS solution for now to get the app going), but here is what I recall I had configured.

- AD Group: "NautobotAdmin"
- Nautobot Group: "NautobotAdmin"

```python
# This search matches users with the sAMAccountName equal to the provided username. This is required if the user's
# username is not in their DN (Active Directory).
AUTH_LDAP_USER_SEARCH = LDAPSearchUnion(
    LDAPSearch("OU=NautobotAdminAccounts,OU=AdminAccounts,OU=Users,DC=contoso,DC=com", ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)"),
    LDAPSearch("OU=NautobotUserAccounts,OU=AdminAccounts,OU=Users,DC=contoso,DC=com", ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)")
)

# For more granular permissions, we can map LDAP groups to Django groups.
AUTH_LDAP_FIND_GROUP_PERMS = True

# Cache groups for one hour to reduce LDAP traffic
AUTH_LDAP_CACHE_TIMEOUT = 3600

# You can map user attributes to Django attributes as so.
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn"
}

# This search ought to return all groups to which the user belongs.
# django_auth_ldap uses this to determine group hierarchy.
AUTH_LDAP_GROUP_SEARCH = LDAPSearch("OU=AdminTeams,OU=Users,DC=contoso,DC=com", ldap.SCOPE_SUBTREE, "(objectClass=group)")
AUTH_LDAP_GROUP_TYPE = NestedGroupOfNamesType()

# Define special user types using groups.
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_active": LDAPGroupQuery("CN=NautobotAdmin,OU=AdminTeams,OU=Users,DC=contoso,DC=com")
                | LDAPGroupQuery("CN=NautobotUser,OU=AdminTeams,OU=Users,DC=contoso,DC=com"),
    "is_staff": LDAPGroupQuery("CN=NautobotAdmin,OU=AdminTeams,OU=Users,DC=contoso,DC=com")
                | LDAPGroupQuery("CN=NautobotUser,OU=AdminTeams,OU=Users,DC=contoso,DC=com"),
    "is_superuser": LDAPGroupQuery("CN=NautobotAdmin,OU=AdminTeams,OU=Users,DC=contoso,DC=com")
                    | LDAPGroupQuery("CN=NautobotUser,OU=AdminTeams,OU=Users,DC=contoso,DC=com")
}
```

Based on the doco I expected to be able to define a group in AD, and within Nautobot. And Django would automatically add users to that group.

As a somewhat hacky workaround, I just get Django to MIRROR the groups in at the moment. Its annoying as the first user to login from a new group has no permissions till they let me know theyve logged in and then I set the permissions on the now created group.

```python
# Mirror LDAP group assignments into Django
# Will create any that don't exist
AUTH_LDAP_MIRROR_GROUPS = ["NautobotAdmin", "NautobotUser"]
```

**Comment by gsnider2195** [comment]
Comment if this is still an issue and we can reopen
