### ISSUE TITLE
GraphQL: ip_addresses does not provide family

### ISSUE THREAD

**Issue by FragmentedPacket** [nautobot/nautobot#1131]
### Environment
* Python version: 3.6
* Nautobot version: 1.1.4+

### Steps to Reproduce
1. Create an IP address
2. Attempt to grab the family from the ip_addresses.
```
{
  ip_addresses {
    address
    family
  }
}
```
3.

### Expected Behavior
Be able to grab the family of an IPAddress

### Observed Behavior
```
{
  "errors": [
    {
      "message": "Cannot query field \"family\" on type \"IPAddressType\".",
      "locations": [
        {
          "line": 35,
          "column": 5
        }
      ]
    }
  ]
}
```

We're able to filter via family at the top level, but cannot retrieve the family. The RestAPI returns the family so expecting that GraphQL would as well.

I assume it is probably because family is a computed field and not automatically generated as a GraphQL schema.

**Comment by glennmatthews** [comment]
Should be as simple as adding a `family` field to the `IPAddressType` class and a corresponding `resolve_family` method.
