### ISSUE TITLE
Asset Tag required to be unique between tenants

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#1134]
### Environment
* Python version:  3.6
* Nautobot version:  1.1.5

If you create 2 tenants and respective sites in Nautobot I would expect the possibility of having duplicate asset tags across tenants but not within the same tenant.  Today I can't create 2 devices with the same asset tag but belonging to 2 different tenants.

### Steps to Reproduce
1.  Create Tenant A
2. Create Site A belonging to Tenant A
3.  Create Tenant B
4. Create Site B belonging to Tenant B
5. Create device with asset tag 'abc123' belonging to site A Tenant A
6. Create device with asset tag 'abc123' belonging to site B Tenant B

### Expected Behavior

Both devices created

### Observed Behavior

Unable to create the second device as the asset tag is already in use

**Comment by bryanculver** [comment]
This falls under a group several issues around uniqueness constraints.

Currently this is working as expect under the existing definition of the Tenant model. We will work to clarifying the documentation to call out some of these limitations while also revisiting the operating model of Tenant.

**Comment by lampwins** [comment]
This is an opinion that can be enforced through a custom validator.
