### ISSUE TITLE
Add REST API and GraphQL for JobLogEntry

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#1152]
### User Story

(Sequels to #1030)

As Cora the Coder, I want to be able to retrieve JobLogEntry records via the REST API so that I can dynamically render the results of a running Job as described in #650. I will know this is done when I can read all relevant attributes of all JobLogEntry records for a running Job via the REST API.

As Tammy the Tools Integrator, I want to be able to query job logs as structured data, whether by REST or by GraphQL, so that I can programmatically inspect the results of running any given Job in order to power my tools integrations. I will know this is done when I can retrieve all JobResults associated with a given Job execution via both REST and GraphQL.

### Database Changes

Already performed as part of #1030.

### External Dependencies

None.

**Comment by jathanism** [comment]
Fixed in #1196
