### ISSUE TITLE
Add gte/lte functionality to job-results created and completed timestamps. 

### ISSUE THREAD

**Issue by josh-silvas** [nautobot/nautobot#1164]
### Environment
* Python version: 3.7
* Nautobot version: v1.0.3

### Proposed Functionality
Implement lookup expressions for greater-than and less-than for the `created` and `completed` fields in the JobResultFilterSet. 
Something similar to the implementation that was done on [CreatedUpdatedFilterSet](https://github.com/nautobot/nautobot/blob/develop/nautobot/extras/filters.py#L83)

### Use Case
As Albert the API user, I would like to be able to query job results for the last x number of days or hours. 

I would know this is complete when I can query something similar to `/extras/job-results?created__gte=2021-10-29`

### Database Changes
None

### External Dependencies
None

**Comment by glennmatthews** [comment]
Looking at the code more closely, it may be that changing the filter definition to use `MultiValueDateTimeFilter` instead of `DateTimeFilter` for these fields may make this "just work". See `BaseFilterSet` in `nautobot/utilities/filters.py`.

**Comment by lampwins** [comment]
This was implemented some time ago.
