### ISSUE TITLE
UX Creating object permissions is horrible

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#1171]
### Environment
* Python version: 3.6
* Nautobot version: 1.2.0

With the new admin UI when trying to create or edit an object permission the list of object types is painfully useless, it shows a list of 4 objects to scroll through a long list.  Can we simply make the list taller to list more objects at 1 time?

![Screen Shot 2021-12-16 at 11 21 15 AM](https://user-images.githubusercontent.com/14947575/146427439-cb77b92f-5530-41ba-91cf-0ffb41d819de.png)

**Comment by dgarros** [comment]
Dup of #1140
