### ISSUE TITLE
Official Docker Image: v1.2.0 Tagged Images fail to load with ImportError: libxml2.so.2

### ISSUE THREAD

**Issue by UnicodeTreason** [nautobot/nautobot#1173]
### Environment
* Python version: 3.6/3.9
* Nautobot version: 1.2.0

### Steps to Reproduce
1. Pull down newly released images
```shell
podman pull networktocode/nautobot:1.2.0-py3.6
podman pull networktocode/nautobot:1.2.0-py3.9
```
2. Run aforementioned images
```shell
podman run --replace --pids-limit 0 --name nautobot_dev -p 8443:8443/tcp -v /home/user/git/nautobot/environment_configuration:/opt/nautobot docker.io/networktocode/nautobot:1.2.0-py3.6
podman run --replace --pids-limit 0 --name nautobot_dev -p 8443:8443/tcp -v /home/user/git/nautobot/environment_configuration:/opt/nautobot docker.io/networktocode/nautobot:1.2.0-py3.9
```

### Expected Behavior
Container loads up and runs successfully.

### Observed Behavior
Stacktrace occurs just before uwsgi loads

```shell
  File "/usr/local/lib/python3.6/site-packages/nautobot/core/management/commands/start.py", line 1, in <module>
    from django_webserver.management.commands.pyuwsgi import Command as uWSGICommand
  File "/usr/local/lib/python3.6/site-packages/django_webserver/management/commands/pyuwsgi.py", line 3, in <module>
    import pyuwsgi
ImportError: libxml2.so.2: cannot open shared object file: No such file or directory
```

### Notes
Running the beta image from the other week works fine still: 1.2.0-beta.1-py3.6

**Comment by glennmatthews** [comment]
Thanks for the report! Investigating now; likely an impact from the changes made in #1073 though I don't know yet why this wouldn't have been caught in testing.

**Comment by nniehoff** [comment]
@UnicodeTreason thanks for reporting this, I have confirmed I can reproduce the bug using docker as well.  I'll work on getting a fix in for this.  @glennmatthews agreed, especially how we got it into all of the sandbox environments.  @glennmatthews feel free to assign this to me

**Comment by glennmatthews** [comment]
Thanks @nniehoff! I can reproduce this issue locally as well, let me know if there's any way I can assist.
