### ISSUE TITLE
JobResult page may fail to list JobLogEntries in chronological order

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#1193]
### Environment
* Python version: 3.6
* Nautobot version: 1.2.1

### Steps to Reproduce
Unsure at this time

### Expected Behavior

JobLogEntries to be listed in chronological order.

### Observed Behavior

![image](https://user-images.githubusercontent.com/5603551/146831919-5afa877d-f07c-4bf6-838b-3c8c56c1c064.png)

Looking at the code, either the `JobLogEntry` class should define a `Meta.ordering` property, or else the `GitRepositoryResultView` and `JobResultView` view should add an `order_by()` to their `JobLogEntry` querysets.

**Comment by glennmatthews** [comment]
Also, using `settings.SHORT_DATETIME_FORMAT` for this column is probably not ideal as it only gives minute-level precision. For most jobs, a `HH:MM:SS.mmm` display would probably be more useful.

**Comment by jathanism** [comment]
Fixed in #1196 and #1199
