### ISSUE TITLE
Allow plugins to create top-level dropdowns in navbar

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#12]
### Proposed Functionality
It should be possible to add specific plugins, or groups of plugins, as a top-level item.

### Use Case
As a developer, I want to make it easy for users to find a given functionality that is implemented within a plugin.  If I’m developing a solution-centric plugin, I should be able to make that a top-level item on the navigation bar.  

### Database Changes
None.

### Plugin API Changes
Will need to extend the current PluginMenuItem API to allow the user to specify a target menu grouping.

### External Dependencies
None.

**Comment by jedelman8** [comment]
This was addressed in #485

**Comment by glennmatthews** [comment]
Plugin support for this feature was added in #572.
