### ISSUE TITLE
Not permitted to have two webhooks with same URL and exact same action set, even if content-types differ

### ISSUE THREAD

**Issue by itheodoridis** [nautobot/nautobot#1225]
### Environment
* Python version: 3.9
* Nautobot version: 1.2.1 (on docker with ldap and on ubuntu 20.04 as well)

### Steps to Reproduce
1. Create a webhook about a device or ip address being created or  updated or deleted (all three actions)
2. Save the webhook
3. Edit/modify it by removing an action
4. Try to save the webhook

### Expected Behavior
The webhoot should be updated

### Observed Behavior
An error occurs with message : "Webhook with this URL, Type create, Type update and Type delete already exists". The webhook is not updated and one is forced to cancel to get out of the edit mode.

**Comment by lampwins** [comment]
I am unable to reproduce this on v1.2.2. Can you confirm if you have any other webhooks already created? The error you are seeing is a uniqueness constraint on content type + URL + action to prevent duplicates.

**Comment by itheodoridis** [comment]
I suppose I should update to 1.2.2. In the mean time please follow me on this one.
Suppose you have a CRUD webhook for :
-  dcim \| device
-  dcim \| interface
-  ipam \| IP address
-  ipam \| prefix
-  ipam \| VLAN
and want to create a different one for 
- circuits \| circuit
- circuits \| provider
but both point to the same URL which is essentially the same teams room (why would it be different??)
So only the source items and the text is practically different.
(It would make no difference if I had only two create webhooks that pointed to the same URL)
I can never create the second one. If I remove an action from the CRUD combination, I can.
So I am saying something is off with the check. Maybe on purpose but still it feels wrong.
Sometimes the same check doesn't allow me to modify an existing webhook about the actions combination. 
Suppose I have two webhooks and I want to exchange their roles. I am practically frozen in place unless I delete them as I can't modify either without the check firing.
Is that clearer?
I will try and update to 1.2.2 but as I am on leave right now I don't know how soon I can make it.

**Comment by glennmatthews** [comment]
Thanks for the additional details! I can confirm that it's not permitted to have two different webhooks pointing to the same URL with the same set of actions but for different content-types, and I agree that there is a use case for this.

**Comment by glennmatthews** [comment]
Additionally it seems wrong that the current check only checks for exactly identical action sets - i.e. the following is permitted:

- Webhook 1: dcim.device, Create/Update/Delete, http://example.com
- Webhook 2: dcim.device, Create/Delete, http://example.com

but the following is blocked:

- Webhook 1: dcim.device, Create/Update/Delete, http://example.com
- Webhook 2: dcim.device, Create/Update/Delete, http://example.com

**Comment by itheodoridis** [comment]
Thank you Glen, yes that seems accurate.

**Comment by bryanculver** [comment]
To clarify:

**Expected to be permitted:**

- Webhook 1: dcim.device, Create/Update/Delete, http://example.com/
- Webhook 2: dcim.interface, Create/Delete, http://example.com/

**Not expected to be permitted:**

- Webhook 1: dcim.device, Create/Update/Delete, http://example.com/
- Webhook 2: dcim.device, Create/Delete, http://example.com/

Or

- Webhook 1: dcim.device, Create/Update/Delete, http://example.com/
- Webhook 2: dcim.device, Create/Update/Delete, http://example.com/
