### ISSUE TITLE
Scheduler: Enable cron style interval settings

### ISSUE THREAD

**Issue by sirtux** [nautobot/nautobot#1226]
### Environment
* Python version: n/a
* Nautobot version: 1.3?

### Proposed Functionality

As Tom, the network operator, I would like to have more complex intervals in the scheduler.

### Use Case

I have some jobs which need to be run at different intervals (e.g. 5min) then currently possible.

Scheduling use-cases to cover:

- UI
- API
- Plugin (via ORM)

### Database Changes
Possibly enhancing the model with the cron style fields.

### Implementation

Celery supports already crontab style schedules: https://docs.celeryproject.org/en/stable/userguide/periodic-tasks.html#crontab-schedules,
so I guess just having an "advanced" interval, which has free text fields for minute, hour, day_of_week, day_of_month and month_of_year could be enough, and of course support in the backend for this.

Thanks,
Tom

**Comment by bryanculver** [comment]
Thanks for submitting this feature request @sirtux!

Feature sounds pretty straightforward and can potentially be implemented without being a breaking change on the interval handling execution.

It is now working its way into prioritization.
