### ISSUE TITLE
API and UI Button to refresh Cable Paths.

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot#123]
### Environment
* Python version: 3.7.9
* Nautobot version: 1.0.0b2

### Proposed Functionality
API endpoint to update cable_paths. This could take an input to select specific Cable_paths based on an CableTermination, or update all cable paths. 

UI button to update the specific CablePath, perhaps on the Interface options next to tracing, or in the cable trace itself.

### Use Case
As a User, I need an easy way to update cable paths when changing Front/Rear ports or Circuit Terminations.  

### Database Changes
Unknown

### External Dependencies
None

**Comment by smk4664** [comment]
See my note in #104.  Since Circuit Ports are also Endpoints, if a Circuit was created with only an A end, and later changed to add a Z end, the paths for Cable connected to A end would need updated.  There was also a request for this in NetDev/#netbox. 

That said, I don't necessarily disagree with your statement.

**Comment by steffann** [comment]
Nothing a trigger attached to circuit termination saves shouldn't be able to fix ;)  I was just reading #104 and added a comment there as well. Will test!

**Comment by glennmatthews** [comment]
Is this still needed with the latest updates to #104?

**Comment by smk4664** [comment]
Obsoleted by #104. A Cable Path update should happen automatically, any need to manually run would likely be due to a bug that will need to be addressed.
