### ISSUE TITLE
Job list view is missing "last results" from latest job run

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#1237]
### Environment
* Python version:
* Nautobot version: 1.2.2

### Steps to Reproduce
1. Add a job to Nautobot and execute it at least once
2. Navigate to `/extras/jobs/`
3. Inspect the "Last Results" column

### Expected Behavior

The column should contain four colored labels showing the number of Success, Info, Warning, and Failure messages logged by this job:

![image](https://user-images.githubusercontent.com/5603551/148416576-21c27731-9af9-45fa-bfd4-a1d97dcb05b6.png)

### Observed Behavior

The column is blank:

![image](https://user-images.githubusercontent.com/5603551/148416343-6c1f6fab-cff8-4fc9-99b5-b2e336589fba.png)

**Comment by glennmatthews** [comment]
This appears to be due to the logging changes from #1030, as the page template is still attempting to render these values based on information in `JobResult.data["total"]`, which is no longer present. Probably both the template and the JobListView code need to be updated.

**Comment by briddo** [comment]
Resolved in #1411 by removing that column entirely
