### ISSUE TITLE
Docker Images: Add A major/minor Docker image that rolls up the patch versions into it

### ISSUE THREAD

**Issue by FragmentedPacket** [nautobot/nautobot#1242]
### Proposed Functionality
I'm going to try and explain this the best I can.

Currently, we're publishing Docker containers for the exact specific version, e.g. 1.2.2. In addition to those, I would like to see a 1.X tag that incorporates the latest patch version into it on each release of a patch. For instance, when 1.2.3 is release, a new image is also pushed up to 1.2 that now incorporates the latest patch version.

This can be extended to major versions down the road as well and hopefully it's pretty simple to tag and push up within our current process. Tagging @nniehoff though for his expert opinion

### Use Case
This functionality will help CI/CD pipelines for our Nautobot plugins where we can specify the minor versions to test against rather than list out a ton of patch version or not have to update pipeline files to test against the latest versions.

Our Nautobot plugin CI/CD matrix would only have to be: `[1.1, 1.2]` with this new change.

Example #1: https://github.com/nautobot/nautobot-plugin-chatops-grafana/blob/develop/.github/workflows/ci.yml#L150
- If we wanted to incorporate major tags as well, this would just have to be set to `1`.
Example #2: https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/blob/develop/.github/workflows/ci.yml#L150
- Same as above and will only require minimal maintenance rather than pinning patch level docker images within CI/CD

### External Dependencies
Docker publishing pipeline

**Comment by nniehoff** [comment]
The more appropriate place would be in the release.yml provided by #1218.  This should be as simple as adding tags to the docker/metadata-actions.  I'll work on this once we get #1218 done.
