### ISSUE TITLE
IP Address API Endpoints Could Provide Parent Prefixes

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#1245]
### Environment
* Python version: 3.9
* Nautobot version: 1.2.2

### Proposed Functionality

When grabbing an IP address via REST or GraphQL API, support providing a list of parent prefixes and aggregrates.

### Use Case

Provide ease of gathering parent prefix information.

### Database Changes

None

### External Dependencies

None

**Comment by glennmatthews** [comment]
Thank you! In some ways this is the converse of #842. #1032 is also very relevant.

**Comment by bryanculver** [comment]
Completed via #1032: https://next.demo.nautobot.com/api/ipam/ip-addresses/5afd9cae-5257-48cb-a611-c2fdba80359b/

![image.png](https://images.zenhubusercontent.com/64b03f5fbfa6195289288f36/0c89b1ad-f768-4bd1-ad40-723be14bea2d)
