### ISSUE TITLE
ORM ChangeLog Requests

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#1246]
### Environment
* Python version: 3.8
* Nautobot version: 1.2.2

### Proposed Functionality

Would like to have an ORM method to save with user information that would create a changelog entry

### Use Case

When someone makes an edit to a database object, the change shows up on the next UI edit, within the changelog the person that made the last UI edit gets attributed to the database object update.

### Database Changes

New function? Unsure if there are database changes needed for this

### External Dependencies

None

**Comment by bryanculver** [comment]
This should be achievable today with already available features, however documentation can be updated to include an example as to how one would do this.

**Comment by dgarros** [comment]
Maybe this could be integrated into `validated_save()`

**Comment by gsnider2195** [comment]
There is some documentation on this here
https://nautobot.readthedocs.io/en/stable/administration/nautobot-shell/#change-logging-and-webhooks

**Comment by lampwins** [comment]
We support this via the documented context manager. https://docs.nautobot.com/projects/core/en/stable/user-guide/administration/tools/nautobot-shell/?h=change+logging#change-logging-and-webhooks
