### ISSUE TITLE
Add support to pull GraphQL queries from a Git repository

### ISSUE THREAD

**Issue by dgarros** [nautobot/nautobot#1247]
### Environment
* Python version:3.9
* Nautobot version: 1.2.2

### Proposed Functionality
Add a new content type for Git that would allow the users to maintain and sync a library of GraphQL queries in a Git repository.
The idea is to extend what we are currently doing for Jobs and Confix context to Saved GraphQL query.

### Use Case
I think there are multiple use cases 
- Allow better peer review and traceability for GraphQL Queries
- Allow to manage GraphQL queries along side other resources in Git, like Jinja2 templates

### Database Changes
No

### External Dependencies
No

**Comment by lampwins** [comment]
We should think about the developer's experience in defining new data source types. Adding things like this is a recurring theme.
