### ISSUE TITLE
Git Repository Corrupted

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot#1259]
### Environment
* Python version: 3.8
* Nautobot version: 1.2.2

### Steps to Reproduce
1. Setup Git repo in Nautobot.
2. Click sync button for repo.

### Expected Behavior
I expect to see the Git repo updated with the latest commit for the specified branch.

### Observed Behavior
Receive error about `Error while refreshing <repo name>`. When you look in the repo folder notice that the .git folder is missing.

**Comment by bryanculver** [comment]
Without any further information it's hard to debug or find the source of this issue.

For future reference, the error message should include additional information around the exception which would be helpful to carry this further.

**Comment by jdrew82** [comment]
Unfortunately, I've been unable to reproduce this. I'm assuming it was maybe just a glitch that's not happened since. We can close this out.
