### ISSUE TITLE
Add BGP Support to Nautobot

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#1269]
### Environment
* Python version: 3.7
* Nautobot version: 1.2.3

### Proposed Functionality

I would like to model my BGP deployment in Nautobot.  This should include ASNs as well as peering relationships at a minimum.

### Use Case

As Nelly, a network engineer, I need to be able to model BGP configuration of my network in my source of truth to be able to completely automate the deployment of my network configuration.

### Database Changes

Definitely, probably at least ASNs perhaps more.  It's possible some of this may be better represented in a plugin.

### External Dependencies

None

**Comment by dutchshark** [comment]
Perhaps use [Peering Manager](https://github.com/peering-manager) to prevent reinventing the wheel?

**Comment by lampwins** [comment]
Closing with https://github.com/nautobot/nautobot-plugin-bgp-models
