### ISSUE TITLE
Add documentation about debuging jobs running in celery-worker

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#1273]
### Environment
* Python version: 3.8
* Nautobot version: 1.2.4

### Proposed Functionality
Provide a section in documentation that shows how to debug celery-worker jobs within the IDE.

### Use Case
As "P.D. Plugin Developer I want to debug jobs in my IDE (vscode). I havent found a description  in documentation of how jobs, that are started by a celery worker, can be debugged in my development IDE (vscode).

### Database Changes
None

### External Dependencies
None

**Comment by jathanism** [comment]
@jifox This is documented in the Celery project's [Debugging](https://docs.celeryproject.org/en/stable/userguide/debugging.html#debugging-tasks-remotely-using-pdb) section. Is this sufficient for you?

**Comment by jifox** [comment]
@jathanism Yes, that will be sufficient. I also found this information:
https://miaoz2001.medium.com/debug-celery-in-a-docker-compose-container-with-vs-code-2b1d7d5eef99
