### ISSUE TITLE
Upgrade to Django 3.2

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#1277]
### Proposed Changes

Upgrade Django dependency to 3.2.

### Justification

Django 3.1 is EOES as of December, which means we will not get data loss or security fixes going forward. 3.2 is the current LTS which extends EOES to April 2024.

**Comment by glennmatthews** [comment]
This may require migrations of some of our dependencies due to the addition of [default_auto_field](https://docs.djangoproject.com/en/4.0/releases/3.2/#customizing-type-of-auto-created-primary-keys).

**Comment by glennmatthews** [comment]
Specifically, it looks like `django-constance`, `social-auth-app-django`, and `django-taggit` 1.x (fixed in 2.x) do not yet have releases that account for that 3.2 feature.

**Comment by bryanculver** [comment]
Closed with #1461
