### ISSUE TITLE
Add more filter lookup expressions to custom fields

### ISSUE THREAD

**Issue by joewesch** [nautobot/nautobot#1288]
### Environment
* Python version: 3.7.12
* Nautobot version: 1.2.2

### Proposed Functionality
When adding a custom text field onto a model, the default filter expression seems to be the `icontains`. It would be nice if we also got access to all of the additional lookup expressions as the rest of the model fields such as `istartswith` and `iendswith` as well as the negate/exclude versions.

### Use Case
My current use case is for a customer to be able to create custom fields on a model and then be able to use an exclude filter on that field.

### Database Changes
None.

### External Dependencies
None.

**Comment by glennmatthews** [comment]
https://github.com/netbox-community/netbox/pull/7678 may be useful as a reference.

**Comment by lampwins** [comment]
@nautobot/core is there anything specific we need to address here with custom fields at this point, given all the work with filtersets?

**Comment by glennmatthews** [comment]
I think so? [CustomFieldFilter](https://github.com/nautobot/nautobot/blob/develop/nautobot/extras/filters.py#L315) still only generates `exact`, `icontains`, or `contains` filters for custom fields. We should probably have it instead pull in the `FILTER_*_LOOKUP_MAP` constants from `nautobot.utilities.constants` and make use of those.

**Comment by gsnider2195** [comment]
We're handling `date` fields in #1498. We can track filter updates for `text` and `integer` custom field types in this issue. Should the text filters also apply to `url`, `select` and `multiselect`?

**Comment by gsnider2195** [comment]
Possibly resolved by #2126. That PR added the following custom field filters:

  - `text`, `url` and `select`
    - `n` (exact)
    - `ic` (icontains)
    - `nic` (icontains)
    - `iew` (iendswith)
    - `niew` (iendswith)
    - `isw` (istartswith)
    - `nisw` (istartswith)
    - `ie` (iexact)
    - `nie` (iexact)
    - `re` (regex)
    - `nre` (regex)
    - `ire` (iregex)
    - `nire` (iregex)
  - `integer` and `date`
    - `n` (exact)
    - `lte` (lte)
    - `lt` (lt)
    - `gte` (gte)
    - `gt` (gt)

**Comment by joewesch** [comment]
Thanks @gsnider2195, I have confirmed that many filters that were not present before are now functioning as expected!
