### ISSUE TITLE
Jobs result live pagination resets to page 1

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#1289]
### Environment
* Python version: 3.8.6
* Nautobot version: 1.2.4

### Steps to Reproduce
1. Have a job that produces a lot of continuous logs and runs for several minutes
2. Run the job
3. In the results page, wait for more than 10 pages of log results to populate
4. Click on page 8

### Expected Behavior
The result set should remain on the user-selected log results page.

### Observed Behavior
On the next log poll cycle, the user is redirected back to page 1 of the log results.

**Comment by bryanculver** [comment]
Include the query string when auto refreshing the page.
