### ISSUE TITLE
Register “extras” features such as CFs, webhooks, export templates, links, relationships from plugins

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#13]

**Comment by glennmatthews** [comment]
A plugin might prefer/expect/require certain extensibility features to be defined/enabled as a consequence of installing and enabling the plugin. For example:

- Automatically adding certain custom fields or specific custom links to a Nautobot model(s)
- Automatically defining an export template(s) for a Nautobot model(s)
- Automatically creating certain Relationships between Nautobot models (and/or additional models provided by the plugin itself)

This can actually be implemented today via subclassing the PluginConfig `ready()` method but we lack documentation and official support for this option. See also #16 as a related issue.

Separate, but closely related, is the idea that plugins should be able to **use** all of these extensibility features with their own data models, such as change logging of plugin models (#15), webhooks triggered by updates to plugin models (#11), user-defined custom fields and custom links on plugin models (#???), relationships between plugin models (#???)

**Comment by glennmatthews** [comment]
Addressed in `next` by #820.
