### ISSUE TITLE
Extend permissions to enable delegation/CRUD of addresses and prefixes based on parent prefix tenancy

### ISSUE THREAD

**Issue by jcsicard** [nautobot/nautobot#130]
### Environment
* Python version: n/a
* Nautobot version: 1.0.0

### Proposed Functionality

Enable delegation of parts of the IPAM address plan to restricted users by extending permissions constraints matching so that the CRUD of a IPAM address or prefix object can be inherited or evaluated based on the properties of the parent prefix object.

### Use Case

A potential workflow with minimal changes could look like this:

The network group wants another group of admins (server group for example) to be able to self-manage (CRUD) ip addresses in the IPAM but only under prefixes that are specifically assigned to them.  

To enable this a network admin would 

- create the prefix to be delegated
- set the tenant on that prefix to "server-group"
- create a permissions group "server-admins"
- create and assign a permission with parameters:
- - actions: view, add, change, delete 
- - object type: ipam > ip address
- - assignment group: "server-admins" 
- - constraints (_proposed change_):  _{ "parent_prefix__tenant_slug": "server-group" }  or perhaps {"inherited_tenant_slug": "server-group"}_

### Database Changes
Unknown. Could probably be implemented minimally as code only without schema change.

### External Dependencies
Unknown/none

**Comment by jathanism** [comment]
This is is an interesting use-case. Thanks for submitting this!

**Comment by ggiesen** [comment]
Would a better model be to delegate based on tenant? I'd like to see permissions for everything (devices, racks, prefixes, etc) being able to be delegated, and I think tenant is ideal.

**Comment by jathanism** [comment]
@ggiesen Great question. The underlying challenge is how we relate objects to each other, and then consider all of the edge cases as it relates to the permissions-checking backend code. 

It seems simple at first, but unfortunately it isn't. We need to consider the common cases, and not just doing one-off implementations for mapping "grouped" object permissions from the parent to its descendants. As I see it, we have to consider implementing some kind of uniform "tree" language for parent/child relationships of objects before we do this, to lay the groundwork for having that granularity. 

For example: If a `Tenant` is a parent of all objects in that tenancy, having a uniform way to identify that streamlines the ability to do those descendant permission checks (from the tenant to descendants), or ancestral permission checks (from the descendants up to the tenant). Say, for example, any device that has a `tenant` field, rolling up to the parent as `children`. 

There is currently such a concept from `TenantGroup` as a parent (and other `*Group` style objects for that matter and their respective core objects, `RackGroup` -> `Rack`, et al.) to `Tenant` objects as children, but there isn't for any other objects that are assigned to that tenant.

**Comment by jedelman8** [comment]
@jathanism Would you mind creating the issue we had discussed and which you described here that is blocking this?

**Comment by itdependsnetworks** [comment]
@jcsicard does #1007 meet all of the requirements? If not, can you explain in more details?

**Comment by jcsicard** [comment]
So with #1007, we should now be (as we are currently in netbox) able to limit users to CRUDing ip addresses only under specific prefixes that we want to « delegate » to by building permission with constraint filters lists that explicitly match all delegated prefixes ([{address__net_host_contained: “delegatedprefix1”}, {address__net_host_contained: “delegatedprefix2”} … ]

This works but us cumbersome to manage.
What would be better would be to be able to use a “parentprefix” queryset filter on ipaddress (or even other prefix) objects, like such:

{address__parentprefix__tenant:”tenant1”}

this would make it so that the permission constraint is simple and only needs to be written once, rather than having to be adjusted everytime a new prefix is created/delegated to a “tenant user”.  This way we would only have to set the correct tenant value on the parent prefix to manage the RBAC/delegation.

This would then be analogous to giving CRUD permissions on interface objects based on it’s parent device’s tenant value like
{interface__device__tenant:”mytenant”}

As far as I understand, this is currently not possible because there is no ORM relationship between the child address and it’s containing parent prefix (#1032).

PS: thanks alot for #1007! It will enable us to finaly migrate to nautobot!

**Comment by lampwins** [comment]
Because of the explicit parent/child relationships that now exist in the IPAM data model in v2, this is now mostly possible in the current permissions feature set. Any additional enhancements, we will track as new requirements.
