### ISSUE TITLE
Interfaces / Console ports count incremented without connections

### ISSUE THREAD

**Issue by jn-ier** [nautobot/nautobot#1304]
### Environment
* Python version: 3.8.8
* Nautobot version: 1.2.4

### Steps to Reproduce
1. Add device with interfaces / console ports and dont connect any interfaces / console ports to other devices

### Expected Behavior
Previously before 1.2.4, the count of interfaces on the main page only increased the total number of interfaces / console ports that has a cable to other devices and showing wether or not these interfaces has end-to-end connectivity.

### Observed Behavior
In 1.2.4, the count of interfaces / console ports increases without connecting cables.

**Comment by bryanculver** [comment]
@jn-ier What version of Nautobot were you on before upgrading to 1.2.4?

**Comment by bryanculver** [comment]
This appears to have been broken with #716.
