### ISSUE TITLE
Cannot mass edit device types to 0U

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#1311]
### Environment
* Python version: 3.6.15
* Nautobot version: 1.2.4

0U is valid height when creating or editing a device type, but mass editing does not allow this.

### Steps to Reproduce
1. Create 2 device types
2. Mass edit them to set `U height` to 0U

### Expected Behavior
Set to 0U

### Observed Behavior
`Please select a value that is no less than 1.`

**Comment by bryanculver** [comment]
Confirmed. Thanks for reporting this @Thetacz.

**Comment by bryanculver** [comment]
Closed in #1611
