### ISSUE TITLE
Filtering prefixes returns all instead of empty

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#1312]
### Environment
* Python version: 3.6.15
* Nautobot version: 1.2.4

When I filter prefixes and the filter is too strict resulting in 0 prefixes found, I get all prefixes instead.

Example from [demo.nautobot.com](https://demo.nautobot.com):
Filter all prefixes from site `PEK02` with `mgmt` role in tenant `Nautobot Airports` ([link](https://demo.nautobot.com/ipam/prefixes/?mask_length__lte=&q=&within_include=&family=&mask_length=&present_in_vrf_id=&site=pek02&role=mgmt&tenant=nautobot-airports&is_pool=))
![image](https://user-images.githubusercontent.com/26114847/151367629-ca037cff-6c2b-4e09-b69a-fea532612625.png)
Now since no prefix is `deprecated`, add this to filter ([link](https://demo.nautobot.com/ipam/prefixes/?mask_length__lte=&q=&within_include=&family=&mask_length=&present_in_vrf_id=&status=deprecated&site=pek02&role=mgmt&tenant=nautobot-airports&is_pool=))
The result should be no prefixes, but returns all instead
![image](https://user-images.githubusercontent.com/26114847/151367833-92e9d30f-3968-449a-bd95-30d1d87a1d31.png)

### Steps to Reproduce
1. Open prefix list in UI
2. Set filtering to combination no prefix has

### Expected Behavior
No prefixes returned

### Observed Behavior
All prefixes returned

**Comment by jvanderaa** [comment]
There may be something related on #1149 that has caused this to become impacted. When adding some debugging commands, it looks like the queryset is being called multiple times, and at some point gets overwritten, maybe on permissions.

**Comment by jvanderaa** [comment]
In testing, if the `@property` is removed from the queryset option and added as a method instead, we are able to have the issue resolved.
