### ISSUE TITLE
GraphQL Query of primary_ip4_for in Interface IP_Address - Errors

### ISSUE THREAD

**Issue by jrpell** [nautobot/nautobot#1313]
### Environment
* Python version:  Python 3.8.11
* Nautobot version:  nautobot==1.2.3

### Steps to Reproduce
1.  Open GraphiQL within Nautobot
2.  Fill in the query like this:
```
query ($device_id: ID!) {
  device(id: $device_id) {
    interfaces {
      ip_addresses {
        address
        primary_ip4_for{
          id
        }
        tags {
          id
        }
      }
    }
  }
}
```
3. Fill in the Query variables with a proper device id in the Query Variables box:
```
{
  "device_id": "<valid device id from Nautobot instance>"
}
``` 
4. Run the Query

### Expected Behavior
I would expect to see all interfaces listed with details about them including ip address assignment and if that IP is the primary IP for the interface.  The Documentation Explorer on the right side shows the "primary_ip4_for" is a valid attribute for an IP Address as a part of an Interface.  Plus, this worked before upgrading to version 1.2.3 of Nautobot.  I believe I was on 1.2.1 before the upgrade.

### Observed Behavior
Every interface shows like this if it is not the primary interface for that device:
```
{
  "errors": [
    {
      "message": "IPAddress has no primary_ip4_for.",
      "locations": [
        {
          "line": 37,
          "column": 9
        }
      ],
      "path": [
        "device",
        "interfaces",
        16,
        "ip_addresses",
        0,
        "primary_ip4_for"
      ]
    },
```

For the interface that actually is the primary interface, it shows this:
```
{
      "message": "'Device' object has no attribute 'all'",
      "locations": [
        {
          "line": 37,
          "column": 9
        }
      ],
      "path": [
        "device",
        "interfaces",
        28,
        "ip_addresses",
        0,
        "primary_ip4_for"
      ]
    }
```

**Comment by glennmatthews** [comment]
Looks like the following line of code may be the culprit:

```python
resolved_obj = filterset_class(kwargs, getattr(self, field_name).all())
```

This code is meant to handle ManyToOneRel reverse-relations, but it turns out that OneToOneRel (`primary_ip4_for` is a reverse relation on OneToOneField) is a subclass of ManyToOneRel, so it's getting pulled in here too. We probably need some code to handle OneToOneRel differently from ManyToOneRel.
