### ISSUE TITLE
Error loading jobs in git-repo

### ISSUE THREAD

**Issue by joakimnyden** [nautobot/nautobot#1333]
### Environment
* Python version: 3.6.8
* Nautobot version: 1.2.5

### Steps to Reproduce
1. when working with jobs in Git-repo there are some problem loading modules in a subfolder.
2. if i update a file in the subfolder of jobs i need to reload nautobot and nautobot-worker.
3. then i have to wait pretty long for it to load the jobs.
4. when i then tries to run the job it failes cause it cant find the file. but the secound or third time i try to run the job it works.
5. when i edit a jobs-file directly under the jobs folder it's updated immediately and works the first time i try to rerun.
6. it works but takes long time when trying to debug a job that does not work and i have to trubbleshoot.
7. is there a better way to debug test jobs whithin jobs ? vs-code have great debugging tools but i realy dont know how to debug a nautobot-job with it.

### Observed Behavior
Devistating to debug jobs when i have to reload all the time. But it could be me not using the correct tools.

**Comment by glennmatthews** [comment]
Thanks for the report! Agreed that the current job authoring workflow could do with some improvements. This relates to #85, #138, #449, #1273 as well as the broader revamp discussed in #765.

I think the current simplest workflow when developing a job, as you alluded to, is to start a local instance of Nautobot and develop the job directly in `JOBS_ROOT` (e.g. `/opt/nautobot/jobs/` if running in Docker) so as to not need to deal with the added complexity of Git repos and/or plugin development - once the job is completed to your satisfaction you can then move it into a Git repo. 

That said, I'd be curious specifically around points 1 and 4 in your list above - would you mind providing more details as to the specific problems you've seen in these cases and how to reproduce them?

**Comment by joakimnyden** [comment]
great, i have to trie those methods wile developing. and to describe the issue in point 1 and 4.
the from default dir `opt/nautobot/git/jobs/jobs`  i have all my jobs defined. and that works fine. I have the added a subfolder `/opt/nautobot/git/jobs/jobs/plays` with a `__init__.py` file and added some python files to abstract the functions from the main files. but there seems to be some issue resolving those modules. they are not refreshed when i do a resync in the gui. I have seen that if i do some changes in the modules under the plays folder they are not refreshed when i rerun a job that imports that module. I have notised that when i reload the worker the module in the subfolder is refreshed.  from the logs i can see there errors: `ERROR   nautobot.jobs: Unable to load job Intergration_reports: No module named 'plays'`

**Comment by glennmatthews** [comment]
As currently implemented, jobs installed in $JOBS_ROOT or provided by Git repositories don't really support inter-module dependencies among different files - if you want to have a "library" of shared functions as a separate file, it really needs to be something properly installed as a Python package or a Nautobot plugin so that the Python module loader can correctly locate it as needed. We could probably do to document this limitation more explicitly in our docs.

**Comment by lampwins** [comment]
We will focus the resolution of this issue on documentation only.

**Comment by glennmatthews** [comment]
This should *generally* be solved by the changes in #5586, #5825, #5828, etc.
