### ISSUE TITLE
Consider using a factory library to generate model instances for testing purposes

### ISSUE THREAD

**Issue by briddo** [nautobot/nautobot#1334]
### Proposed Changes
We should consider using something like https://factoryboy.readthedocs.io/en/stable/orms.html to create model instances for testing purposes.

### Justification
This would:
1.  Speed up test development and abstract away all the trivial stuff into the factory classes. 
2. Make tests clearer and more succinct.
3. Make it easier to cope with schema changes

**Comment by glennmatthews** [comment]
See also #1999, #1034.

**Comment by bryanculver** [comment]
We have a lot of low-level factories today. Factories for things like Devices will be much more complex. As we introduce new models we add factories if feasible. The spirit of this is complete and will evolve. Including using DB snapshots for other performance considerations.
