### ISSUE TITLE
Server forgets main IPv4 (ipv6 not tested)

### ISSUE THREAD

**Issue by Mocem1** [nautobot/nautobot#1344]
### Environment
* Python version: 3.7.3
* Nautobot version: 1.2.4

Hi, 

First of all I would like to thank you for the nice tool. The issue I ran into is that when I change an IP address which is assigned to an interface to another interface of the same server it removes the main IP. This only happens to an IP address which is not the main IP. 

Changing the main IP from a interface to another works as designed. 

### Steps to Reproduce
1. Add server with 3 or more interfaces
2. Assign IP address to 2 different interface. Make 1 address the main IP 
3. Move the non main IP to another interface of the same server.
4. Check if the main IP is still there.

**Comment by glennmatthews** [comment]
Probably a duplicate of #1523, in which case this is fixed by #1558. Need to confirm.

**Comment by Mocem1** [comment]
Hi Glenn,

I can confirm this issue is fixed as well. 

Thanks
