### ISSUE TITLE
nautobot-scheduler needs a restart to see new scheduled jobs

### ISSUE THREAD

**Issue by sirtux** [nautobot/nautobot#1347]
### Environment
* Python version: 3.9
* Nautobot version: 1.2.5

### Steps to Reproduce
1. Schedule a job to run every hour
2.
3.

### Expected Behavior
The job is run every hour

### Observed Behavior
The job is not started at all, but a restart of nautobot-scheduler.service fixes this behaviour.

### To Do:

- [ ] Reproduce the issue

**Comment by bryanculver** [comment]
Thanks for the report @sirtux. To help us get this fixed, can you let us know how you are deploying Nautobot (as a service? container? etc)

**Comment by bryanculver** [comment]
@sirtux This has been unreproducible on our side. Can you potentially provide more information?

Pending closure.

**Comment by bryanculver** [comment]
Closing. Cannot reproduce.
