### ISSUE TITLE
CircuitTermination Missing Methods

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot#1350]
### Environment
* Python version: 3.7
* Nautobot version: 1.2.4

### Steps to Reproduce
1. Go to extensibility -> Custom Field -> Add
2. Attempt to change content type to "Circuit | Termination"
3. Note that is not there

### Expected Behavior

The ability to add to that content type

Use cases included:
* Adding custom field for local LEC
* Adding custom field for local contact information. 

### Observed Behavior
Content type not available.

**Comment by itdependsnetworks** [comment]
There are additionally missing methods for export_templates, webhooks, and statuses. They may not all be required, but not sure what constitutes not having them.

**Comment by smk4664** [comment]
I will be taking on this ticket.

**Comment by bryanculver** [comment]
Merged into `next`.
