### ISSUE TITLE
Delete Images from Device Type (Add a delete button)

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#1353]
### Environment
* Python version: 3.9
* Nautobot version:  a7a425060fec (v1.2.5)

### Proposed Functionality

Add delete buttons or delete checkboxes to the upload fields

![image](https://user-images.githubusercontent.com/8406301/153144623-5b5f6b47-26fd-4d96-b8bf-c72e12cf2627.png)

Maybe delete checkboxes are the better choice because this can be handled during saving the changes.

### Use Case

As Nelly the Network engineer I want to have the ability to remove an image (front view, rear view) when editing the device type.

Currently if no image is selected, the existing one is preserved. Adding just one image when updating will also preserve the other image. So there is no way to get rid of one of the images

![image](https://user-images.githubusercontent.com/8406301/153143462-f35995a7-9188-41e8-a5b8-194bb15f7774.png)

### Database Changes

None

**Comment by glennmatthews** [comment]
Thanks for the report! Based on some brief investigation, this may be as simple as making the below change:

```diff
diff --git a/nautobot/dcim/forms.py b/nautobot/dcim/forms.py
index 00d059030..1349347f4 100644
--- a/nautobot/dcim/forms.py
+++ b/nautobot/dcim/forms.py
@@ -879,8 +879,8 @@ class DeviceTypeForm(BootstrapMixin, CustomFieldModelForm, RelationshipModelForm
         widgets = {
             "subdevice_role": StaticSelect2(),
             # Exclude SVG images (unsupported by PIL)
-            "front_image": forms.FileInput(attrs={"accept": "image/bmp,image/gif,image/jpeg,image/png,image/tiff"}),
-            "rear_image": forms.FileInput(attrs={"accept": "image/bmp,image/gif,image/jpeg,image/png,image/tiff"}),
+            "front_image": forms.ClearableFileInput(attrs={"accept": "image/bmp,image/gif,image/jpeg,image/png,image/tiff"}),
+            "rear_image": forms.ClearableFileInput(attrs={"accept": "image/bmp,image/gif,image/jpeg,image/png,image/tiff"}),
         }
```

![image](https://user-images.githubusercontent.com/5603551/153222486-dd6f482d-9cd5-447c-b028-cf712462eb4d.png)
