### ISSUE TITLE
Virtual Chassis master device interface list is confusing

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#1356]
### Environment
* Python version: 3.7
* Nautobot version: 1.2.4 & 1.2.5

When viewing a virtual chassis master member ALL interfaces from the virtual chassis are listed.  First this is visually confusing on the interface list view if you have 2 devices of the same type which have 2 interfaces with the same name there are 2 "Eth1" interfaces listed but no indication as to which "Eth1" we are looking at.  Second, and more importantly if you select an interface from a non-master virtual chassis member and connect a cable to an interface on the master device the interface list on the cable creation view lists ALL of the interfaces in the virtual chassis.  In this case "Eth1" is listed 2 times, it is possible then to select the same interface from which you are trying to connect the cable.

![Screen Shot 2022-02-09 at 9 53 45 AM](https://user-images.githubusercontent.com/14947575/153249834-544a233e-4acc-4145-8009-7941b88585d4.png)

### Steps to Reproduce
1.  Create 2 devices of the same type
2.  Create a virtual chassis including the 2 devices
3.  Select 1 of the devices as the master device 
4. Check the interface list of the master device, notice ALL interfaces from the virtual chassis are included
5. Select an interface from the non-master device and connect a cable to another interface
6. On the cable connection view choose the master device to connect a cable to
7. In the interface list notice ALL interfaces from the virtual chassis are listed
8. Choose the second interface with the same name you are connecting from
9. You should receive the error `Cannot connect dcim | interface to itself`

### Expected Behavior

The interface list view is confusing on the master device, if this is a master in a virtual chassis we should include a device name here or perhaps make a interface list for the virtual chassis itself to include the device name as well.

On the cable creation view I shouldn't be able to connect an interface to itself.  Not sure if it really makes sense to include ALL interfaces in the master device interface list here or if you should have to choose the virtual chassis itself for such a list.  In any case in the case of listing ALL interfaces in a virtual chassis it should be clear as to which device the interface belongs to.

### Observed Behavior

The same interface (by name only) is listed multiple times in various interface list views for a virtual chassis master device.

**Comment by glennmatthews** [comment]
Similar class of UI issues as #629.

**Comment by jifox** [comment]
Hi, Also the Virtual Chassis List itself is confusing because it lists duplicate entries.

For every member of a virtual chassis a line is generated that displays the virtual_chassis.name and virtual_chassis.master device. Thats of course always the same for all the devices in the list.

e.g.:
http://localhost:8080/dcim/virtual-chassis/?q=ATKP

![image](https://user-images.githubusercontent.com/8406301/165229206-4e6af33e-7388-41f2-a620-fcba8e5281a9.png)

**Comment by lampwins** [comment]
> The interface list view is confusing on the master device, if this is a master in a virtual chassis we should include a device name here or perhaps make a interface list for the virtual chassis itself to include the device name as well.

While I don't disagree, the intended use is to rename the member interfaces to how they appear within the VC. I.e., in the original example with two Eth1 interfaces, do these actually both show up as Eth1 in within the VC if you do the equivalent of `show interfaces`? On most platforms, the interfaces take on new, indexed names based on the member's role within the VC.

**Comment by lampwins** [comment]
Non-master members show only their interfaces in the device interface table, where you can rename them in bulk by selecting the desired set of interfaces (usually all of them in this case) then scroll to the bottom left of the table and clicking rename. You can then use a regex-powered find and replace function.

Additionally, if desired, you can temporarily deselect the master from the VC which would allow you to see only that device's interface list in its interface table.

Generally, though, it has been a best practice to rename interfaces before adding devices as members of a VC, although I hope this shows it is perfectly fine to rename them after the fact.

**Comment by lampwins** [comment]
> Hi, Also the Virtual Chassis List itself is confusing because it lists duplicate entries.

@jifox thanks, I have opened #1749

**Comment by nniehoff** [comment]
> On most platforms, the interfaces take on new, indexed names based on the member's role within the VC.

@lampwins I think the keyword here is "most" there are also a number of platforms like the Cisco Nexus platforms which allow you to create a [virtual port channel](https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/nx-os-software/217274-understand-virtual-port-channel-vpc-en.html).  Each switch maintains it's own control plane and does not rename the interfaces.  It looks like this was at least once a [feature request in NetBox](https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/nx-os-software/217274-understand-virtual-port-channel-vpc-en.html) as well.  Is there a better way to model these multi-chassis LAGs recommended by Nautobot?

**Comment by jifox** [comment]
Also Checkpoint's do not rename their interfaces but there are Cluster IPs. That's why I use virtual-chassis to group it
