### ISSUE TITLE
Support Custom Field Name Changes

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot#137]
### Environment
* Python version: 3.7
* Nautobot version: v1.0.0b2

### Steps to Reproduce
1. Create a custom field in nautobot, e.g. `color` on the dcim.device model
2. Update data for a device, e.g. set to `red`
3. Updated name of custom field to `colour`
4. View the data in in the UI (notice it is missing)
5. Return custom field to `color`
6. See data return

### Expected Behavior

Either custom fields should not be editable or when edited, the data should migrate as well.

### Observed Behavior

The data seems to "disappear" on the UI. When the custom field name is returned, the data "reappears".

#### Screenshots

![image](https://user-images.githubusercontent.com/9260483/110879661-632f6100-82ab-11eb-8ad5-f19adf3ed815.png)

![image](https://user-images.githubusercontent.com/9260483/110879705-6f1b2300-82ab-11eb-983d-cd5fcd4cbb18.png)

![image](https://user-images.githubusercontent.com/9260483/110879743-7b9f7b80-82ab-11eb-8616-58e240dfbeea.png)

![image](https://user-images.githubusercontent.com/9260483/110879627-54e14500-82ab-11eb-91c9-d5ccd6e4966e.png)

**Comment by jathanism** [comment]
Yeah I would definitely lean towards a custom field not being able to be renamed once it is created. That would go a long way to avoiding an issue like this entirely that results in apparent data loss. Other concrete model fields cannot be renamed, so I think this asserts that consistency and prevents us from having to come up with an over-engineered solution.

**Comment by smk4664** [comment]
What about adding `label`. This way the name(label) presented to the End Users could change, but not change the internal field.

**Comment by glennmatthews** [comment]
> What about adding `label`. This way the name(label) presented to the End Users could change, but not change the internal field. Though, this could change its usability in scripts and jobs.

Custom fields actually *do* already have a `label` field, which can be freely changed. :-)

**Comment by jedelman8** [comment]
@itdependsnetworks can you test again using labels?  Does that help?  If so, this could be added to the docs in the short term.

**Comment by itdependsnetworks** [comment]
It does not, label changes what is in green, and I am referring to what is in orange. 

![image](https://user-images.githubusercontent.com/9260483/112414767-05facd00-8cf9-11eb-8e69-bd1e01b70881.png)

**Comment by itdependsnetworks** [comment]
actually, I am incorrect, I was referring to #135 yes, I think documentation for now is the course of action, with a longer term solution.

**Comment by lampwins** [comment]
For now, we will not allow the name or type to be changed once created.
