### ISSUE TITLE
Job Result Source Tab Has Inconsistent Behavior

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#1372]
### Environment
* Python version: 3.7
* Nautobot version: 1.2.5

### Steps to Reproduce
1. Install Example Plugin
2. Run a job
3. Modify plugin code and restart Nautobot
4. Run a job with new code
5. View previous job run

### Expected Behavior

The "Source" tab of a past job run shows the code of the job that was run to produce the output.

### Observed Behavior

The "Source" tab of a past job rub shows the _latest_ code of the job, which may not be the same code that was run to produce the output.

### Screenshots

_**Original Job Run (5:35pm)**_
<img width="1410" alt="Screen Shot 2022-02-14 at 12 36 09" src="https://user-images.githubusercontent.com/31187/153919238-e0e50e6d-6780-4d18-a37a-e5c6f2f98f03.png">

---

_**Source of Original Job Run**_
<img width="783" alt="Screen Shot 2022-02-14 at 12 35 54" src="https://user-images.githubusercontent.com/31187/153919311-57793da7-8536-46b6-91ee-0ebcdea7b484.png">

---

_**Newer Job Run w/ Updated Code (5:42pm)**_
<img width="1407" alt="Screen Shot 2022-02-14 at 12 42 34" src="https://user-images.githubusercontent.com/31187/153919390-3e77730c-5e22-4e51-b073-d6ea463e7969.png">

---

_**Source of Newer Job Run**_
<img width="1407" alt="Screen Shot 2022-02-14 at 12 42 47" src="https://user-images.githubusercontent.com/31187/153919428-9cc23207-229c-45a0-a122-c4a4cbf242bd.png">

---

_**Source of Previous Job Run (5:35pm) Showing Updated Code**_
<img width="1407" alt="Screen Shot 2022-02-14 at 12 44 24" src="https://user-images.githubusercontent.com/31187/153919535-6be40307-6a3e-4981-aa41-59c05252c489.png">

**Comment by jathanism** [comment]
The only way to solve this would be to snapshot the code that was run at execution time and we have no intentions to do this. Therefore this is expected behavior and we will likely solve the sin the future by removing the job source tab altogether as it tends to lead to more confusion than helpfulness.
