### ISSUE TITLE
API provision tokens for user

### ISSUE THREAD

**Issue by imranh2** [nautobot/nautobot#1374]
### Environment
* Python version: n/a
* Nautobot version: n/a

### Proposed Functionality
Netbox 3.0 added a feature where you can generate a token using the API if pass along a user/pass - https://github.com/netbox-community/netbox/commit/b038b1f613becb0298d276fa453fe844ba9e6f1e

Nautobot could enhance this feature by allowing the token generation to be more customisable (set the name and the permissions). But just having what Netbox has is a good base I think.

### Use Case
Would like to be able to generate tokens instead of saving people's passwords somewhere.

### Database Changes
None.

### External Dependencies
None.

**Comment by bryanculver** [comment]
Closed with #1551
