### ISSUE TITLE
Add API calls for VLAN groups available-vlans functionality

### ISSUE THREAD

**Issue by jasonjuenger** [nautobot/nautobot#1378]
### Environment
* Python version: 3.8.8
* Nautobot version: 1.2.5

### Proposed Functionality
The VLAN Groups page show the available VLANs within a specific VLAN group. 
Clicking on the "# VLANs available" link brings the user to a new page to
reserve the next available VLAN from that range. This functionality should be
exposed via API to allow for automated VLAN assignment.

This functionality has been implemented in Netbox [#2658](https://github.com/netbox-community/netbox/issues/2658) with an additional
enhancement to add scoping for min/max VLAN IDs in [#8168](https://github.com/netbox-community/netbox/issues/8168).

### Use Case
As a Nautobot user, I would like to programmatically assign VLANs to new
tenant buildouts using a single API call so that I can avoid race conditions 
querying then reserving VLANs when multiple workflows are reserving 
VLANs at the same time.

### Database Changes
New method is required in VLANGroup model to get available VLANs. To implement
the min/max VLAN ID scoping two new fields are required in the VLANGroup model,
min_vid and max_vid.

### External Dependencies
None

**Comment by jathanism** [comment]
Thanks for the submission. The [NetBox feature](https://github.com/netbox-community/netbox/commit/e0cfd5e49bda860353702affd435f62bf9322dd4) solves the problem, however we would likely do it in a slightly different way by implementing the nested endpoint as a viewset method (e.g. `VLANGroupViewSet.available_vlans`) so that we can reduce code duplication.

**Comment by joaopsys** [comment]
This would be a great feature to have, a min/max VLAN ID, so we can programmatically get the next available VLAN ID

**Comment by foxx** [comment]
Is this on the roadmap for any upcoming releases? Would love to see this feature, I'd happily pay a bounty if that would help?

**Comment by Senetus** [comment]
I would also love this feature to be able to automate vlan assignments!

**Comment by martijn-gr** [comment]
The company I work for could use this feature very much. It is one of the points of debate about choosing Nautobot VS Netbox.
Being able to limit the available vlans in a group without actually reserving all vlans would be useful.

In our case we have several vlan groups within a layer 2 domain. All groups together on a "site" form all vlans in the l2 domain (if that makes sense). (in our case that is, a site equals a routing edge for us.)

**Comment by glennmatthews** [comment]
FYI @mzbroch

**Comment by mzbroch** [comment]
@jasonjuenger @joaopsys @foxx @Senetus @martijn-gr 

This has been implemented under #6273 and released in Nautobot 2.3.6 https://github.com/nautobot/nautobot/releases/tag/v2.3.6

**Comment by martijn-gr** [comment]
> @jasonjuenger @joaopsys @foxx @Senetus @martijn-gr 
> 
> This has been implemented under #6273 and released in Nautobot 2.3.6 https://github.com/nautobot/nautobot/releases/tag/v2.3.6
> 
> You can check out our Docs at https://docs.nautobot.com/projects/core/en/stable/user-guide/core-data-model/ipam/vlangroup/?h=vlangroup

Will check this out next week.
