### ISSUE TITLE
Signal error to the GUI if a syntactically incorrect job is loaded from a git repository

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot#138]
### Environment
Using [nautobot-lab](https://github.com/nautobot/nautobot-lab) at 1.0.0b1
* Python version: 3.8.5
* Nautobot version: 1385ef2621ef (v1.0.0b2)

### Proposed Functionality

If there is a syntactical error in a job file in a git repository there should be a warning or an error message in the sync job logs that indicates this.

### Use Case

If someone was to write a job in a git repository and for example miss an import they wouldn't know if the error lies
- in the communication between the repository and the Nautobot instance
- in the job file itself
- in the layout of the repository
- some other place

### Database Changes

None

### External Dependencies

None

**Comment by jathanism** [comment]
Hello @Kircheneer, thanks for the submission.

What is the current behavior you're experiencing? It sounds like if a job is attempting to be loaded, it is failing silently or in a non-obvious way? Can you please add some context on your experience? Thanks in advance!

**Comment by Kircheneer** [comment]
I just did the following things:
1. Reset the lab container
2. Copy the example job (the new branch one) from the documentation in a git repository into a `jobs` folder under the repository root (that folder also contains an `__init__.py` file
3. Run the job (working as expected)
4. Change the `description` field in the `Meta` class to `descriptio`
5. Refresh the data source in Nautobot
6. Watch as the job silently disappears without an error message
7. Change it back to `description`
8. Refresh the data soruce in Nautobot
9. The job is still not visible

Is there maybe some caching at play here which I am missing?

**Comment by jathanism** [comment]
@glennmatthews Can you please help me confirm this one? :)

**Comment by jathanism** [comment]
I am unable to reproduce this on Nautobot v1.0.0b2. The job appears to still load but the `description` field disappears. 

Can you please [build and install `nautobot-lab` from GitHub ](https://github.com/nautobot/nautobot-lab#building-the-container)which will build b2 and see if this issue persists? 

Thanks!

**Comment by jedelman8** [comment]
Tagging @Kircheneer to see @jathanism's last comment!

**Comment by jathanism** [comment]
@Kircheneer That's progress! It does look like the `NewBranch job you linked was based off the [sample job of the same name](https://nautobot.readthedocs.io/en/latest/additional-features/jobs/#creating-objects-for-a-planned-site).

In any case your issue is on line 41:

https://github.com/Kircheneer/nautobot_data/blob/master/jobs/example.py#L41

You want that to be an instance of a `Status` object now and not a choice enum. So you need these changes

```python
# at the top
from nautobot.extras.models import Status

# one line 41
                status=Status.objects.get(slug="planned"),
```

Can you please see if updating your job fixes your issue?

**Comment by glennmatthews** [comment]
I can verify the reported behavior using the "master" branch of the linked repo - the job fails (from the user's perspective) silently to load when accessing the Jobs UI, although the error *is* logged to the console at least:

```
21:00:27.643 ERROR   nautobot.jobs        jobs.py                               get_jobs() :
  Unable to load job example: f-string: expecting '}' (example.py, line 40)
```

It would be reasonable for us to add some handling logic to report errors as a banner on the Jobs page, along the lines of "The following job files could not be loaded...". Thanks for the report!

**Comment by bryanculver** [comment]
Needs to be retested for 1.3/1.4 as symptoms may have changed with concrete Job model.
