### ISSUE TITLE
MarkdownLint should be run on our docs

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot#1385]
### Proposed Changes
Enable MarkdownLint on our code scanning.

### Justification
There was an error in the Markdown that caused the sidebar to not work properly on ReadtheDocs. This could/should have been caught by MarkdownLint.

**Comment by smk4664** [comment]
I wouldn't mind picking up this issue.

**Comment by smk4664** [comment]
I haven't forgotten about this issue, just have to update a lot of docs in order to make this change.

**Comment by glennmatthews** [comment]
#1557 did a bunch of cleanup to get our docs passing markdownlint at a snapshot in time; next thing that'll be needed is to add `markdownlint` to `invoke tests` and to the CI action(s) so that we don't regress in this area.

**Comment by glennmatthews** [comment]
Added in `next` (1.3.0) by #1635.
