### ISSUE TITLE
SVG files not working as image attachment

### ISSUE THREAD

**Issue by waydh** [nautobot/nautobot#1396]
### Environment
* Python version: 3.6.8
* Nautobot version: 1.2.5

### Steps to Reproduce
1. Open a device
2. Click "Attach an image"
3. Select an SVG file
4. Error "Upload a valid image. The file you uploaded was either not an image or a corrupted image."

### Expected Behavior
SVG files attach like JPEGs and GIFs

### Observed Behavior
On trying to attach an SVG file, receive error 

"Upload a valid image. The file you uploaded was either not an image or a corrupted image."

**Comment by smk4664** [comment]
To add some details here, Nautobot uses Django's ImageField to store the Image file location in the backend. ImageField does not support SVG files. https://code.djangoproject.com/ticket/14092

**Comment by waydh** [comment]
Thank you for the details. It seems there won't be any changes happening with Django's handling of images.

I see SVG to JPG/GIF conversion in my future :D
