### ISSUE TITLE
RegEx Search Capabilities for Text Fields

### ISSUE THREAD

**Issue by FragmentedPacket** [nautobot/nautobot#1400]
### User Story

As Nelly, the Network Engineer,

I want to use RegEx within text fields to be able to filter large data sets in a more flexible way.

So that when I want to find all devices that are a pair represented by two digits and either an A or B after, I'm able to use something such as `\d{2}A|B" to search for those devices. This can be extended to other text fields as well (Django already provides this, but must be set for the lookup expression and cannot be toggled.

I will know this is done when:
- Default search boxes within the filter forms support RegEx for core models
- Provides a way for plugin author's to consume the "core" way of providing this
- Potentially any text field supports RegEx

I came up with some crude code to show what I was thinking so it can be toggled with a "flag".

```python
    def search(self, queryset, name, value):
        if not value.strip():
            return queryset
        lookup_expr = "regex" if value.startswith("~") else "icontains"
        value = value.strip("~")
        return queryset.filter(
            Q(**{f"name__{lookup_expr}": value})
            | Q(**{f"serial__{lookup_expr}": value.strip()})
            | Q(**{f"inventoryitems__serial__{lookup_expr}": value.strip()})
            | Q(**{f"asset_tag__{lookup_expr}": value.strip()})
            | Q(**{f"comments__{lookup_expr}": value})
        ).distinct()
```

This is on the `DeviceFilterForm` and I was thinking we'd look for some beginning "flag" (in this case `~`) to know that we want to parse using RegEx. This can hopefully be generalized with a helper function that these methods can re-use.

We may want to add this functionality for any `django_filters.CharFilter` although they can already use the RegEx lookup expression or we can make an explicit `RegExCharFilter` that will look for the "flag" as well. But this is all tied to using a flag to determine if a RegEx search is wanted by a user.

### Pertains To (Optional)

- UI/UX

### Database Changes (Optional)

- I don't believe there are any DB changes, but filter changes.

### External Dependencies (Optional)

- None

### TODO

- [x] #1525
- [x] #1605
- [ ] Awaiting results of #1608 and follow-up implementation story which will provide the functionality in the UI

Let's explore a drop down for fields that allows the selection of a lookup expression for the field.

**Comment by jathanism** [comment]
We think this is a great idea in spirit, however we do not want to introduce "magic" characters for *only* the search field because it would set a precedent or perhaps even an expectation that this would be the case for ALL text input fields. So this solution will require some more thought and design. Thank you for the submission!

**Comment by bryanculver** [comment]
This is effectively done with the work brought in through the direct issues as well as the Dynamic Filter Form
