### ISSUE TITLE
export import inconsistency in custom fields

### ISSUE THREAD

**Issue by martin-networker** [nautobot/nautobot#1407]
### Environment
* Python version:  3.6.8
* Nautobot version: 1.2.5

Issue description:
    If we export for example VLANs from Nautobot the custom field column names has different name compared to what is expected during import. 
   my colleagues from time to time need to import several VLANs so they firstly export one VLAN, open the spreadsheet, write data of new VLANs and try to import this. This attempt fails because custom fields are without "cf_" in the export but requires prefix "cf_" during the import.
Example: in the export there is column named "owner" but for import we have to rename it to  "cf_owner".

Second problem during this export/import is inconsistency in status. In export the status starts with capital letter but import expect lowercase letter.
Active -> active
Reserved -> reserved

### Steps to Reproduce
1. Export one VLAN with some custom fields
2. Change the VLAN vid and name
3. Try to import VLAN from this spreadsheet

**Comment by glennmatthews** [comment]
Thanks for the report! Same general class of issue as described in #254.

**Comment by lampwins** [comment]
Related to #824.

**Comment by martin-networker** [comment]
I have discovered other export/import inconsistencies (see below). Please let me know if these can be handled within this issue or if I should open a new one:
  - field "rack_number" in export has to be "rack" in import
  - field "rack_face" in export has to be "face" in import
  - field "rack_face" has value "Front" in export but in import it has to be "front"
