### ISSUE TITLE
Blank margin around footer on Device pages

### ISSUE THREAD

**Issue by u1735067** [nautobot/nautobot#1408]
### Environment
* Python version: 3.10
* Nautobot version: 1.2.7

### Steps to Reproduce
1. Navigate to Device, Device tab or Advanced tab, like https://demo.nautobot.com/dcim/devices/a2d59253-d911-4f54-bc3e-b387adc44fd2/
2. Scroll to bottom

### Expected Behavior
There's no space between the footer and the browser border

### Observed Behavior
There's no space between the footer and the browser border

### Additional informations

The footer is included in the `.wrapper` div in those pages, instead of being in the `body` tag; maybe something in https://github.com/nautobot/nautobot/blob/v1.2.7/nautobot/dcim/templates/dcim/device.html ?

**Comment by glennmatthews** [comment]
Thanks for the report!
