### ISSUE TITLE
GraphQL query for prefix family returns error

### ISSUE THREAD

**Issue by mundruid** [nautobot/nautobot#1412]
### Environment
* Python version: 3.9.2
* Nautobot version: 1.2.4

### Steps to Reproduce
1. This requires the existence at least one of the following objects: `prefixes`
2. Go to GraphiQL dashboard
3. Paste the following query:
```
query {
      prefixes {
        role {
          id
          name
        }
        prefix_length
        family
      }
}
```

### Expected Behavior
I was expecting the following result based on the data in my Nautobot instance:
```
{
  "data": {
    "prefixes": [
      {
        "role": {
          "id": "cd59e59e-f51e-4353-b9a4-c57acb84c8f4",
          "name": "data_lan"
        },
        "prefix_length": 24
        "family": 4
      }
    ]
  }
}
```

### Observed Behavior
Instead I got the following error:
```
{
  "errors": [
    {
      "message": "Cannot query field \"family\" on type \"PrefixType\".",
      "locations": [
        {
          "line": 8,
          "column": 9
        }
      ]
    }
  ]
}
```

**Comment by glennmatthews** [comment]
Thanks for the report! A very similar issue to #1131, probably needs a fix similar to #1159.
