### ISSUE TITLE
Search sites by physical address in sites page

### ISSUE THREAD

**Issue by vladanmilosevic73** [nautobot/nautobot#1416]
### User Story

As Nelly the network engineer,

I want to be able to search sites in sites page by physical address in free form and supporting regex i.e. anything from that text field,

So that I can get faster responses than using generic search over all fields (top right corner)

I will know this is done:
- when I see a Physical Address input form on https://nautobot.abcdcom/dcim/sites/
- when that search supports regexp

### Pertains To (Optional)

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [x] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [x] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes (Optional)

- ?

### External Dependencies (Optional)

- ?

**Comment by glennmatthews** [comment]
Thanks for the request! The requirement for regex searching relates to #1400.

**Comment by bryanculver** [comment]
Might be related to #1052

**Comment by bryanculver** [comment]
While Sites no longer exist in 2.0, searching by multiple fields, including via Regex or contains, was introduced via several features: Dynamic Filter Form, Regex Filtering.

Demo: https://next.demo.nautobot.com/dcim/locations/?physical_address__ic=6301%20Silver
