### ISSUE TITLE
Narrow the scope of CI on push to non-integration branches

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#1417]
### Proposed Changes

Currently a push to any branch triggers the full CI suite including the full matrix of Python versions and Postgres/MySQL tests. Propose changing things so that while pushes to integration branches (`main`, `develop`, `next`) will continue to run the full CI suite, pushes to any other branch should run a much smaller set of tests, possibly just linters + 1 unittest suite.

### Justification

CI shouldn't be used as a substitute for running tests locally, and the current setup results in a lot of load on GitHub Actions when multiple developers are pushing commits for multiple feature branches.

Additionally, once a PR is open for a given branch, the current setup results in the full CI suite being run twice on each push (once for the push, once for the PR update), which is excessive and redundant.

**Comment by bryanculver** [comment]
Let's also see how much of https://github.com/nautobot/nautobot/pull/1184 addresses our issues as well.

**Comment by bryanculver** [comment]
Closed by #1628
