### ISSUE TITLE
Update all objectchange-capable models to inherit from ChangeLoggedModel

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#1424]
### Proposed Changes

There are a number of models (`CircuitTerminationModel`, `ComponentModel`, `ComponentTemplateModel`, `VMInterface`, possibly others) that implement a `to_objectchange` method but do not inherit from `ChangeLoggedModel`. It would be good to make them into ChangeLoggedModel subclasses (or more generally, they may be able to convert into `OrganizationalModel` or even `PrimaryModel` subclasses.)

### Justification

1. Reduction of code duplication - these models could then call `super().to_objectchange()` instead of implementing their own construction of `ObjectChange` instances
2. Consistent functionality - these models would then have `created` and `last_updated` fields like most other models do. If they become `PrimaryModel` subclasses, they would also add support for Tags which may also be desirable.

**Comment by bryanculver** [comment]
In `next`:

- `CircuitTermination` is now a `PrimaryModel`
- `ComponentModel` is now a `PrimaryModel`
- `ComponentTemplateModel` inherits from `ChangeLoggedModel`
- `CustomFieldChoice` inherits from `ChangeLoggedModel`
- `VMInterface` inherits from `PrimaryModel`

No other models implement their own `to_objectchange`. All above call super when they overload.
