### ISSUE TITLE
Failed Nautobot job does not revert database changes.

### ISSUE THREAD

**Issue by theandrelima** [nautobot/nautobot#1429]
### Environment
* Python version: 3.8
* Nautobot version: 1.1.6

### Steps to Reproduce
1. Start a Network Importer Job that will perform changes to Nautobot assets.
2. Make sure an exception condition happens to make the job fail.

### Expected Behavior
All changes performed before the exception is thrown should be reverted after the job fails.

### Observed Behavior
**OBS:** _Although the following involves quite a bit of NTC's network-importer, I'm afraid the root cause might be on Nautobot's side. Bare with me as I try to explain what I'm seeing:_

- We extend Network-Importer's NautobotInterface model with our own custom model to make sure certain tags are added to certain interfaces (that is, when those tags don't already exist)
- We also extend Network-Importer's NautobotCable model to make sure we throw an exception when a Cable is seen in Nautobot, but It doesn't exist in the Network. 
- Nautobot's Job class calls the job.run method under an atomic transaction: https://github.com/nautobot/nautobot/blob/v1.1.6/nautobot/extras/jobs.py#L1092. Meaning if anything goes wrong with the job, it must revert any changes made during its execution.
- BEFORE invoking the network-importer in Nautobot, I made sure there was no tags assigned to a particular interface that I absolutely knew would be tagged by our custom network-importer code (the Interface model I described above). I also made sure to create a cable connection that doesn't exist in the actual network, so the job would definitely fail. 
- What I expected to see was the Network Importer job successfully tagging the interface, and this happens as expected. I also expected to see the job failing with the cabling exception and message _"Database changes have been reverted due to error."_ (from the link above). This also happens and the message saying the changes were reverted is logged. 
- Finally, I expected to see my interface still untagged, but it remains tagged after the job fails.  Meaning reverting the atomic operation DOES NOT happen.

I have attached 2 prints:
One showing the interface being updated with the desired tag (about 1 second before the job fails), and another showing that the job  indeed failed and the _"Database changes have been reverted due to error."_ was printed.

![network_importer_job_interface_tagged](https://user-images.githubusercontent.com/39955130/155986973-e95a0f20-02fe-429f-921f-43d3bcf2d9c9.png)
![network_importer_job_cabling_exception](https://user-images.githubusercontent.com/39955130/155986971-64556720-1688-4849-87ae-26112e0bbb9e.png)

**Comment by smk4664** [comment]
So, network-importer uses the API (through pynautobot) not the ORM to make changes to the database. When calling through the API, it is making these changes outside the atomic transaction.  I don't know if it is possible to make API calls using atomic transactions. You might move the tag creation to happen after the cable connection.

**Comment by bryanculver** [comment]
@theandrelima 

Are you able to share a sanitized copy of your code?

**Comment by bryanculver** [comment]
At the moment API changes are not done in a way to support atomic transactions.
