### ISSUE TITLE
Print - Jobs Log is empty

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#1430]
### Environment
* Python version: 3.8.10
* Nautobot version: v1.2.8b1

### Steps to Reproduce
1. Execute a job
2. Print the job result page 
3.

### Expected Behavior

The log entries should be printed

### Observed Behavior

**Job Result Output**
![image](https://user-images.githubusercontent.com/8406301/156049351-60b9c402-937c-4178-8e8f-37dad7bb2994.png)

**Print Preview**
![image](https://user-images.githubusercontent.com/8406301/156049080-529c4627-2b7f-4501-9698-3707fd97bcdb.png)

**Comment by bryanculver** [comment]
This seems to be the case with a lot of views, as in many places we specify `noprint`: https://github.com/nautobot/nautobot/blob/develop/nautobot/extras/templates/extras/jobresult.html#L10

Need to review if this has unintended side effects if removed.
