### ISSUE TITLE
[1.3] Document webhook/changelog enhancements in 1.3 Release Overview

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#1441]
### Proposed Changes

Add a section under "Release Overview" in the 1.3 release notes summarizing the enhancements that have been made to change logging and webhooks as a part of #1389.

### Justification

This is a significant new feature.

### Acceptance Criteria

- "Release Overview" section includes notes about changelog
- Existing changelog and webhooks documentation should include updates where relevant

**Comment by bryanculver** [comment]
Closed with #1560
