### ISSUE TITLE
Support Ansible Connection Type in Platform

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#145]
### Environment
* Python version: 3.6+
* Nautobot version: 1.0.0b2

### Proposed Functionality

In moving to Ansible 2.10+ (I believe becoming required in Ansible 2.11 Core), the devices will now require a FQCN (Fully Qualified Collection Name). To help facilitate inventory for the Ansible platform, would like to have a way to get this via API and in the UI.

### Use Case

Ansible Inventory source moving forward past Ansible 2.10 base/core

### Database Changes

- One additional migration to support an additional field, `ansible_connection`.

**Comment by smk4664** [comment]
Could we not make this more generic? I am sure this could be used by more than just Ansible.

**Comment by itdependsnetworks** [comment]
@smk4664 i stated similar on #146, I think that #4 may be a solution

**Comment by smk4664** [comment]
> @smk4664 i stated similar on #146, I think that #4 may be a solution 

I saw that. Thanks!

**Comment by jedelman8** [comment]
@jvanderaa given the direction of using custom computed fields as the solution, are you okay if we close this out? If that happens to not suffice, we can re-open?

**Comment by jvanderaa** [comment]
Sure thing. I can leave the PR open as well for the discussion as we see the result of #4.
