### ISSUE TITLE
Implement Physical Interfaces Parenting Virtual Interfaces

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#1455]
Prototype an implementation similar to the PRs called out here: https://github.com/nautobot/nautobot/issues/929#issuecomment-1027017237 to evaluate if it addresses #929.

This should be able to identify if we run into backwards incompatibility issues with adopting this existing implementation (note we do have API versioning available now).

**Comment by glennmatthews** [comment]
Implemented in #1651 for 1.4.
