### ISSUE TITLE
Getting parent device via GraphQL

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#1460]
### Environment
* Python version: 3.6.15
* Nautobot version: v1.2.7

It is impossible to get parent of a device in device_bay via GraphQL. using the query from reproducer returns error either way (device in bay or standalone).

**A big note here:** GraphQL is behaving differently from REST API, where I can access directly `parent_device` instead of only being able to ask for the `device_bay` the device is in and than using another query to find the parent device this bay is in.
REST API:
![image](https://user-images.githubusercontent.com/26114847/157237004-4f6c73f8-b7bf-4cd1-a249-e3d85a6966e4.png)
So when fixing this, can you please make GraphQL behave the same way which for my usage is more convenient? (I don't care about the bay, I need the parent device. Bu I can still see the bay in nested serializer if I need to.)

### Steps to Reproduce
1. use following query in GraphQL
```
{
  devices {
    name
    parent_bay {
      name
    }
  }
}
```

### Expected Behavior
`parent_bay: None` / `parent_bay: name`

### Observed Behavior
![image](https://user-images.githubusercontent.com/26114847/157236354-0448dee5-75bb-4404-b131-01390411bd57.png)

**Comment by glennmatthews** [comment]
Need to re-test - possibly fixed incidentally by #1313?
