### ISSUE TITLE
Option to hide job source

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#1462]
### As ...

Patti - Platform Admin

### I want ...

A configuration option to entirely disable the Job `Source` tab from the Job execution and Job results pages.

### So that ...

Potentially sensitive code is not exposed to end users of Jobs, and users are not confused by potentially inconsistent Job source based on historical Job results (see #1372)

### I know this is done when...

- I have a global configuration setting (boolean) that controls whether the Job source tab is shown in the UI or not.
- The global configuration settings can be set in the UI (Constance config)
- The setting defaults to `True` for existing installs.

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [X] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by bryanculver** [comment]
@lampwins Please confirm but this should be completely gone in 1.3.

**Comment by glennmatthews** [comment]
I don't believe we removed this in 1.3 - still present in my local dev instance at least:

![image](https://user-images.githubusercontent.com/5603551/164232877-11b8bf9d-a1da-4d8b-8c5d-43dc19559c2b.png)

**Comment by lampwins** [comment]
I think we talked about introducing a setting (which I'm fine doing in a patch release) and then removing entirely in the next minor.

**Comment by lampwins** [comment]
Just rip it out. We can add it back if anyone actually complains.
