### ISSUE TITLE
View and edit relationship associations in API ModelViewSets

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#1463]
### As ...

Austin - Network Automation Engineer

### I want ...

To be able to retrieve and update relationship associations in the same API endpoints as the actual objects I am trying to use with relationships

### So that ...

I have a similar experience in the API with relationships as I do with custom fields, instead of having to deal with relationship associations in an entirely separate set of endpoints.

### I know this is done when...

- [x] #1887
- [x] #1888

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Requirements

- `"relationships"` should be an opt-in field to maintain performance on the default query (particularly GET)
- PATCH, PUT should work as expected

**Comment by glennmatthews** [comment]
Is there any remaining work for this epic now that #2092 is merged?

**Comment by glennmatthews** [comment]
@bryanculver @lampwins Can we close this epic as completed?
