### ISSUE TITLE
Investigate and decide on REST API versioning approach

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#1465]
### As ...

Austin - Network Automation Engineer

### I want ...

- To understand how Nautobot will handle significant (especially breaking) changes to its REST API
- To have a clearly documented mechanism for interacting with specific (non-latest) versions of a given REST API
- To have a plan for supporting this mechanism in pynautobot

### So that ...

- I can write tools and scripts that interact with the Nautobot REST API without worrying that an upgrade to Nautobot will break my REST API integration.
- I can migrate my tools to newer versions of the Nautobot REST API in a controlled, managed fashion, independent of the Nautobot release cycle.
- I can make use of the existing Jobs REST API for the immediate future but can switch my tools over to the revised Jobs REST API introduced in Nautobot 1.3 with a minimum of disruption or code changes required on my end

### I know this is done when...

- The Nautobot team has agreed upon and documented Nautobot's approach for REST API versioning
- A GitHub issue is opened for updating the Jobs REST API prior to the Nautobot 1.3 release so that it complies with the documented REST API versioning approach
- A GitHub issue is opened against pynautobot to request that it be enhanced to support REST API versioning.

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [X] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

N/A

### External Dependencies

Django REST Framework supports a variety of [approaches](https://www.django-rest-framework.org/api-guide/versioning/) for API versioning. Hopefully we will settle on one of those rather than rolling our own.

**Comment by glennmatthews** [comment]
As was pointed out to me, we currently claim to use DRF's `AcceptHeaderVersioning` (i.e. `"accept: application/json; version=1.3"`) where the default (if unspecified in the request headers) and only supported version for any given Nautobot version is the Nautobot version itself (so Nautobot 1.2.x defaults to API version 1.2 and doesn’t support any other; Nautobot 1.3.x defaults to API version 1.3 and doesn’t support any other, etc.).

There are of course a million-and-one opinions out there about the "best" way to provide REST API versioning, but there's something to be said for sticking with what we've already been doing, even if only minimally. My proposal is as follows:

- Continue to use AcceptHeaderVersioning.
- Henceforth declare support for *and default to* version 1.2 of the REST API, meaning "the REST API as it exists in Nautobot 1.2"
  - This means that existing clients that do not explicitly specify a requested version must receive the "version 1.2" API, with the following important distinctions.
- Non-breaking additions to the REST API (e.g. additional fields returned from GET requests, additional *optional* fields supported in POST/PATCH/PUT requests) do *not* require a new API version
  - For example, it is explicitly permitted and expected that a GET request for "version 1.2" of the REST API for a given endpoint might actually return a "version 1.3" JSON data, so long as all expectations of version 1.2 are still satisfied by the version 1.3 data format. The client does *not* have to explicitly request "version 1.3" to receive the updated data.
  - For example, a client sending a POST that requests "version 1.2" *may* include additional (optional) data that is only actually understood by a Nautobot instance running version 1.3 - this is permissible because the REST API simply ignores any fields that it does not understand. The client does *not* have to explicitly request "version 1.3" for the additional fields to be understood.
- Entirely new REST API endpoints (e.g. new `api/extras/jobs/<pk>/` endpoints introduced in Nautobot 1.3) *may* be made accessible to clients requesting an older REST API version
  - For example, a client may request "version 1.2" of the REST API and still be able to see and make use of the new API endpoints added in "version 1.3"
- For **non-compatible** API changes (e.g. the significant change in the `api/extras/jobs/` list endpoint between Nautobot 1.2 and 1.3), a client requesting no particular API revision (recall that this defaults to 1.2 if unspecified) or any version prior to the major.minor version where the change was introduced *must* continue to receive the 1.2 version of the API. Only a client *explicitly requesting* the introduced version or any later version (e.g. 1.3, 1.4, etc.) should receive the updated (backwards-incompatible) version of this API endpoint

A table presentation of some examples:
| API endpoint | Client requested API version | Response from Nautobot 1.2 | Response from Nautobot 1.3 |
| --- | --- | --- | --- |
| `/circuits/providers/<pk>/` | Unspecified | 1.2 API version | 1.3 API version (all changes are backward-compatible with 1.2) |
| `/circuits/providers/<pk>/` | 1.2 | 1.2 API version | 1.3 API version (backward-compatible with 1.2) |
| `/circuits/providers/<pk>/` | 1.3 | Rejected as unsupported | 1.3 API version (backward-compatible with 1.2) |
| |  |  |  |
| `/extras/jobs/` | Unspecified | 1.2 API version (class-based listing) | 1.2 API version (class-based listing) |
| `/extras/jobs/` | 1.2 | 1.2 API version (class-based listing) | 1.2 API version (class-based listing) |
| `/extras/jobs/` | 1.3 | Rejected as unsupported | *1.3 API version (model-based listing, backwards-incompatible)* |
| |  |  |  |
| `/extras/jobs/<pk>/` | Unspecified | 404 not found | 1.3 API version (first version supporting this endpoint) |
| `/extras/jobs/<pk>/` | 1.2 | 404 not found | 1.3 API version (first version supporting this endpoint) |
| `/extras/jobs/<pk>/` | 1.3 | 404 or unsupported | 1.3 API version (first version supporting this endpoint) |
| |  |  |  |
| `/extras/jobs/<class_path>/` | Unspecified | 1.2 API version | 1.2 API version (no changes were made in 1.3) |
| `/extras/jobs/<class_path>/` | 1.2 | 1.2 API version | 1.2 API version (no changes were made in 1.3) |
| `/extras/jobs/<class_path>/` | 1.3 | Rejected as unsuported | 1.2 API version (no changes were made in 1.3) |

**Comment by bryanculver** [comment]
I think the above approach is good @glennmatthews.

Some things I think we should thoroughly document before going with that approach:

**Split Versioning**
I think we should however spell out what users should expect when say they want to upgrade one portion of the API to leverage new functionality but maybe haven't updated their entire integration to use the new versions.

EX:

Lets say we introduce two backwards incompatible changes to 1.4, say `/virtualization/clusters/` and `/dcim/devices/`. If they set the `AcceptHeaderVersioning` globally, but are only interested in consuming breaking changes of `/dcim/devices/` they can have unintended consequences against `/virtualization/clusters/`.

**Breaking Changes, Removing Old Versions**
Detailing how we plan to remove prior API version support (keep X versions for N releases). As well when we move `1.2` code paths, do users specifying that version get an error response or moved up to the oldest supported version? Can we apply a header in the response of the newest version available?

At what point do we move "unspecified" to use the backwards incompatible change? In your example above would that only be after we remove `1.2` code paths? Or do we permit a rolling migration where the first version is conditionally upgrade, second version changes the default but still permitting a "legacy" request, then the third version dropping support for the older version?

**Comment by glennmatthews** [comment]
> **Split Versioning** I think we should however spell out what users should expect when say they want to upgrade one portion of the API to leverage new functionality but maybe haven't updated their entire integration to use the new versions.
> 
> EX:
> 
> Lets say we introduce two backwards incompatible changes to 1.4, say `/virtualization/clusters/` and `/dcim/devices/`. If they set the `AcceptHeaderVersioning` globally, but are only interested in consuming breaking changes of `/dcim/devices/` they can have unintended consequences against `/virtualization/clusters/`.

Yes, certainly - the correct thing for the client to do here would be to *not* set the header globally, but only set it specifically for calls to the particular API endpoint(s) that they want to migrate; all other APIs they call would remain at the existing version. We should document that as a best practice, and make sure `pynautobot` makes it easy to do that.

> **Breaking Changes, Removing Old Versions** Detailing how we plan to remove prior API version support (keep X versions for N releases). 

Certainly this needs to be documented. I know we've had other discussions about when it will be appropriate to remove deprecated features; this would be a part of that discussion. IMHO our API changes in breaking ways so infrequently that it *shouldn't* be a tremendous burden to support the legacy version indefinitely.

> As well when we (remove?) `1.2` code paths, do users specifying that version get an error response or moved up to the oldest supported version? Can we apply a header in the response of the newest version available?

Looks like the default DRF behavior here is to just reply `{"detail":"Invalid version in \"Accept\" header."}`, but we could certainly override that. I don't think automatically moving to a newer version is desirable - if the client requests something that we've dropped support for, an error response is appropriate, because returning a newer (non-backward-compatible) data format in the response will just confuse the client.

The *newest* version available is always the same as the Nautobot major.minor version, and it's returned in any successful API request (including the basic `/api/` endpoint) as an `API-Version` header.

> At what point do we move "unspecified" to use the backwards incompatible change?

Only at a major version boundary, if even at then, since it *is* a breaking API change and will potentially impact every API client.

> In your example above would that only be after we remove `1.2` code paths? Or do we permit a rolling migration where the first version is conditionally upgrade, second version changes the default but still permitting a "legacy" request, then the third version dropping support for the older version?

If we do decide at all that it's appropriate/necessary to remove legacy REST APIs, I think that would be the most desirable approach, yes:

Nautobot 1.x: default to "1.2" API version if unspecified, support non-backwards-compatible 1.3., 1.4, etc. versions as they are added

Nautobot 2.x: default to "2.0" version if unspecified (which in many/most cases may actually be identical to the 1.2 version still, as our API doesn't change in breaking ways all that often, but in general corresponds to the final 1.x version where possible - we may also introduce entirely new 2.0 APIs at this point), all 1.x versions are still available and can still be requested explicitly if desired but are considered deprecated.

Nautobot 3.x: default to "3.0" version if unspecified; explicit requests for 1.x versions are rejected as unsupported; 2.x versions are still available and can be requested explicitly but are considered deprecated.

**Comment by jathanism** [comment]
> Certainly this needs to be documented. I know we've had other discussions about when it will be appropriate to remove deprecated features; this would be a part of that discussion. IMHO our API changes in breaking ways so infrequently that it _shouldn't_ be a tremendous burden to support the legacy version indefinitely.

This right here falls under our yet-to-be-decided deprecation policy that we should absolutely model after that of [Django's official deprecation policy](https://docs.djangoproject.com/en/dev/internals/release-process/#internal-release-deprecation-policy).

I think we should be cautious about being TOO granular with versioning the API and introducing a matrix of breaking or backwards-incompatible changes. I think "for now" in 1.x since we did inherit the current API versioning scheme from NetBox that we should continue to support it. I do think that for version 2 and beyond, we might want to think about how deliberate this will be.

I am saying this because from a holistic perspective, everything discussed here is great! However, what has not yet been covered is how--exactly--we solve this within the code itself. If we have to end up doing feature branching the API with every new version, managing versioned serializers for different features across every new minor point release (1.3, 1.4, 2.0, 2.1, 2.2, etc.) is going to get complicated very quickly.

We would be wise to also do some competitive analysis on some existing community solutions out there. Here are two:

- https://github.com/sentyaev/drf-versioning - Has examples of two different methods for maintaining branched versions in the core
- https://github.com/mrhwick/django-rest-framework-version-transforms - No longer maintained, but still a very good implementation using version transform mappings that are similar in spirit to how database migrations work. Can also support per-endpoint versioning.

**Comment by glennmatthews** [comment]
> I think we should be cautious about being TOO granular with versioning the API and introducing a matrix of breaking or backwards-incompatible changes. I think "for now" in 1.x since we did inherit the current API versioning scheme from NetBox that we should continue to support it. I do think that for version 2 and beyond, we might want to think about how deliberate this will be.

IMHO now is the right time to do that thinking, rather than waiting for version 2. Do you have an alternate API versioning approach in mind?

**Comment by jathanism** [comment]
> IMHO now is the right time to do that thinking, rather than waiting for version 2. Do you have an alternate API versioning approach in mind?

I'm not sure yet. I think we should marry the holistic approach of how it would be communicated balanced with the technical approach of how it would be managed and implemented. So I think we need to review some of the technical solutions for how we'll manage the versioned serializers/views/endpoints, etc. and how for example, we would roll forward with features that are support or not in newer iterations that come with each minor release.

Personally I am of the mind that perhaps it may not need to be that complicated at all, and we might defer to how other major services out there do API versioning, which is that new features can always be added to an API and keep the version the same, but never changed or taken away without incrementing the version.

You mostly captured this in your initial writeup above, but I still think what is missing is the clarification of what it means for point releases. 

- Are we going to continue to maintain versioned serializers for example for v2.0, 2.1, 2.2, etc.?
- Or do we just roll forward until we start on the v3 horizon? I think that question might be a good one to answer for v1.2 vs v1.3.
- Should the new Jobs model API endpoints instead be v2 endpoints?
- Or is it too soon for us to start implementing v2 API endpoints as we haven't yet arrived at a cohesive plan or design for the v2 API?

**Comment by glennmatthews** [comment]
> I'm not sure yet. I think we could marry the holistic approach of how it would be communicated balanced with the technical approach of how it would be managed and implemented. So I think we need to review some of the technical solutions for how we'll manage the versioned serializers/views/endpoints, etc. and how for example, we would roll forward with features that are supported or not in newer iterations that come with each minor release.
> 
> Personally I am of the mind that perhaps it may not need to be that complicated at all, and we might defer to how other major services out there do API versioning, which is that new features can always be added to an API and keep the version the same, but never changed or taken away without incrementing the version.

That's what I'm proposing, more or less. Again, for the vast majority of API endpoints, "v1.2" will be forward-compatible with "v1.3" will be forward-compatible with "2.0", and so all three "API versions" will be served by exactly the same serializer/viewset code without any need to branch conditionally based on requested API version.

I'm just trying to avoid the need to create a global "API v2" just because of a breaking change to a single API endpoint. Tying the API version directly to the Nautobot version means that we don't need a separate versioning scheme for the API. 

> 
> You mostly captured this in your initial writeup above, but I still think what is missing is the clarification of what it means for point releases.
> 
>     * Are we going to continue to maintain versioned serializers for example for v2.0, 2.1, 2.2, etc.?

All depends on what you mean by versioned serializers? I am proposing that we establish a pattern here and stick to it, yes.

> 
>     * Or do we just roll forward until we start on the v3 horizon? I think that question might be a good one to answer for v1.2 vs v1.3 as it relates to the v2 API.

I'm not clear what you're asking here, apologies.

> 
>     * For example, should the new Jobs model API endpoints instead be v2 endpoints?

This is what I'm trying to avoid by tying the API version to the Nautobot version -- I don't want us to be on API version 10 by Nautobot 2.2 just because there were 10 individual breaking changes and each one necessitated bumping the global API version to the next whole number. 

> 
>     * Or is it too soon for us to start implementing v2 API endpoints as we haven't yet arrived at a cohesive plan or design for the v2 API?

Maybe this is the disconnect here. **Are** we thinking of making globally breaking changes to the API at some point to create an entirely new "v2 API"? I'd assumed not. If so, do we have open issues spelling out the kinds of changes we want to make that would necessitate this?

**Comment by bryanculver** [comment]
Based on the feedback above, I think it's really easy to think of this as:

> I am interested in consuming this API (say Jobs, `/dcim/devices/`, whatever) as it was in version X.Y of Nautobot.


**Hypothetical:**
Let's say we don't introduce anything non-backwards compatible to `/dcim/devices/` until `v2.4`. If we go by Glenn's [suggested theme here](https://github.com/nautobot/nautobot/issues/1465#issuecomment-1068154123), which I would agree with, this would be the deprecation path:

- v1.X-v2.3: No new functionality
- v2.4: New functionality introduced, behind `AcceptHeaderVersioning` flag
- v2.5+: Same as above, behind flag
- v3.X: Default behavior of `/dcim/devices/` becomes what was introduced in v2.4, previous functionality is behind `AcceptHeaderVersioning` flag (considered deprecated)
- v4.X: Deprecated functionality removed

What is the proper `AcceptHeaderVersioning` version the user would send to retrieve the deprecated functionality in `v3.X`? The last time the new functionality didn't exist, aka `v2.3`? The first time the expected functionality was introduced, aka `v1.2` (assuming we align on that being the genesis to all API versions)? Are all versions in-between `v1.2`-`v2.3` valid? Technically the last time `/dcim/devices/` returned the expected payload was all through `v2.X` since we don't change the default until `v3.X`, just new functionality was introduced in `v2.4`.

**Comment by glennmatthews** [comment]
Implemented for 1.3 by #1521.
