### ISSUE TITLE
Nav bar expands vertically when too many top level nav items present

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#1467]
### Environment
* Python version: 3.8
* Nautobot version: 1.2.7

### Steps to Reproduce
1. Have a plugin register enough top level nav items that all horizontal space in the nav bar is consumed
2.
3.

### Expected Behavior
The nav bar should be responsive to the available horizontal space and alter the navigation without compromising the vertical space the nav bar consumes. This is likely a requirement to be met by a UI overhaul. For now, we just need to ensure page elements are not hidden by the nav bar when it vertically expands.

### Observed Behavior
The nav bar search is pushed down which doubles the vertical size of the nav bar resulting in the nav bar covering critical UI elements like buttons and text.

TODO:
- [x] The NavBar items should continue to wrap onto new lines but the page should dynamically pad to ensure the navbar does not float over and hid elements on the page.

**Comment by glennmatthews** [comment]
Currently the wrapping/collapsing of the nav bar is based on hard-coded pixel widths (see for example #1217). We need to rework this so that it's dynamic based on what menus are actually present.
