### ISSUE TITLE
Relationships as list view table columns

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#1468]
### As ...

Austin - Network Automation Engineer

### I want ...

To be able to show relationships as columns in the list view, just as I am able to for custom fields today.

### So that ...

My relationships are visible and sortable as if they were first-class model fields.

### I know this is done when...

I am able to add relationships as columns in an object's list view table.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [X] Other (not directly a platform feature)

### External Dependencies

We likely need to look at performance considerations for relationships, especially when multiple relationships are in play for a given object type.

### Requirements

- Individual column for each relationship that exists for the displayed model
- Column values for many-to-one or one-to-one relationships (where the resulting set is unary) render a detail link and string representation of that object, otherwise show the count of related objects and link to the filtered list view

### Out of Scope

- Sorting (disable sortable action on column heading)
- Filtering (being addressed by #1316)

**Comment by HanlinMiao** [comment]
Completed by #2298
