### ISSUE TITLE
Login failed when BASE_PATH is set

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#147]
### Environment
* Python version: 3.8.5
* Nautobot version: 1.0.0b2

### Steps to Reproduce

I have installed: PLUGINS = ["nautobot_plugin_nornir", "nautobot_golden_config"]

1. set `BUILD_PATH="nautobot/"` in `nautobot_config.py`
2. invoke build --python-ver=3.8.5
3. invoke debug --python-ver=3.8.5
4. Open http://localhost:8000/nautobot/   _(shows up as expected)_
5. Klick on Login Button

### Expected Behavior
Login page should open http://localhost:8000/nautobot/login/?next=/nautobot/

When open manually it works.

### Observed Behavior

```
Page not found (404)
Request Method:	GET
Request URL:	http://localhost:8000/login/?next=/nautobot/
```
```
Using the URLconf defined in nautobot.core.urls, Django tried these URL patterns, in this order:

nautobot/
The current path, login/, didn't match any of these.

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

```

**Comment by jathanism** [comment]
Hmm... I it appears that the problem is that the `LOGIN_URL` value is being computed in `nautobot.core.settings` based on the default value of `BASE_PATH`, but then when you're overloading `BASE_PATH` in your `nautobot_config.py` that computation has already occurred.

Can you please try explicitly setting `LOGIN_URL="/nautobot/login/"` in your `nautobot_config.py` to match the expected path and see if that fixes the issue for you?

**Comment by jifox** [comment]
@jathanism Yo're right, adding the LOGIN_URL fixed the problem

```
BASE_PATH = os.environ.get("BASE_PATH", "nautobot/")
LOGIN_URL=f"/{BASE_PATH}login/"
```

**Comment by jathanism** [comment]
Awesome! Thanks for confirming! I will use this to improve the error-checking/handling around these configuration states. 

For example if `BASE_PATH` is non-default to trigger an error/warning if `LOGIN_URL` is still default. Something like that?

**Comment by jathanism** [comment]
I have determined by way of trying to fix this that the implementation needs to be replaced. I'm going to be removing `BASE_PATH` and instead direct people to use HTTP server configuration to accomplish subdirectory hosting.
