### ISSUE TITLE
Revise all documentation referencing objects with status fields

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#150]
### Proposed Changes

There are numerous places across the model documentation that are referencing the "status" field and the default values. We need to revise these to reference and link to the custom status documentation.

### Justification

We changed the way statuses work in Nautobot when we forked from NetBox. The documentation that references status fields needs to reflect this.

**Comment by scetron** [comment]
I can help with this.

**Comment by jathanism** [comment]
> I can help with this.

It's all yours!

**Comment by jedelman8** [comment]
@scetron are you able to work on this over the next few days? Targeting this for 1.0.0.

**Comment by scetron** [comment]
> @scetron are you able to work on this over the next few days? Targeting this for 1.0.0.

Should be able to have the first draft by tomorrow, so let me say Saturday to be safe.
