### ISSUE TITLE
Enforce IP uniqueness among different VRFs based on the Aggregate.

### ISSUE THREAD

**Issue by ChrisDeh** [nautobot/nautobot#1508]
### As ...

Nelly - Network Engineer

### I want ...

to be able to enforce uniqueness of IP-Addresses and Prefixes among different VRFs based on the Aggregate they belong to.
One way of implementation could be the "Private" Option of a RIR. If a RIR is private, IP-Space/Prefixes can be double used. If a RIR is non-private, IP-Addresses and Prefixes have to be unique within one Aggregate (of course except for Roles like VRRP, etc.).

### So that ...

i can properly track my different vrfs in my infrastructure for automation, even if they all represent the global routing table in the end.
For example I have one Part of your Network where the Global Routing Table is within a VRF called "inet" and in another Part of your Network, your global Routing Table is inside VRF "internet". There is some Point, where they are routed together, but for generating configuration based on documentation, I'd like to track these VRFs in your documentation.

### I know this is done when...

- I try to create a prefix in VRF "red" that already exists in VRF "blue", but both are from the same aggregate, that is not assigned by a RIR that is marked Private and i receive an error message.
- I try to assign a IP Address in VRF "red" that is already assigned in VRF "blue" but is from the same aggregate and it fails and i receive a error message.

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [X] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [X] Documentation
- [ ] Other (not directly a platform feature)

**Comment by glennmatthews** [comment]
Thanks for the request! Until/unless this gets implemented in Nautobot core, this *should* be implementable via a plugin providing a [custom validator](https://nautobot.readthedocs.io/en/stable/plugins/development/#implementing-custom-validators) function for the Prefix model.

**Comment by bryanculver** [comment]
We need to know what the exceptions to this enforcement would be.

It would be great to get an example dataset for different permutations of networks that would be valid and invalid for this enforcement.

**Comment by bryanculver** [comment]
This is enforced via Namespaces now, VRFs are not a uniqueness constraint for Prefixes. @ChrisDeh please check out: https://next.demo.nautobot.com to see if this will do what you desire.

**Comment by bryanculver** [comment]
> This is enforced via Namespaces now, VRFs are not a uniqueness constraint for Prefixes. @ChrisDeh please check out: https://next.demo.nautobot.com to see if this will do what you desire.

@nautobot/core Do we fill Namespaces sufficiently support this request: A prefix can exist in multiple VRFs but must be unique within a Namespace.
