### ISSUE TITLE
Misleading "poetry" reference in plugin documentation

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#151]
### Environment
* Python version: n/a
* Nautobot version: 1.0.0b2

Probably this counts as a special case of #62 but I wanted to make sure it didn't get overlooked.

### Steps to Reproduce
1. `nautobot/docs/plugins/index.md` contains several references to the `poetry` command, which is not an included command in our current installation workflow. 
2.
3.

### Expected Behavior

Documentation should accurately reflect how to install plugins in a Nautobot installation.

**Comment by jathanism** [comment]
Thanks. I'm working on the developer docs soonish, so this will get looped in. :)
