### ISSUE TITLE
Copy button on hover for more fields

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#1519]
### As ...

Ozzie - Operator

### I want ...

to be able to copy data with single click when viewing device detail

### So that ...

- I always copy the whole part and nothing extra
- the whole copy process is easier in general

### I know this is done when...

- I am able to click copy button when hovering over device attribute

Our original internal request is only for device type and asset number, but it does not make sense to limit to only these 2 attributes. It would be nice for this to be a general rule - whichever attribute I hover over, I can get the copy button there.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

None

### External Dependencies

None

**Comment by Thetacz** [comment]
This is probably as easy as adding `<span class="hover_copy">` over each attribute, but probably would be nice to do this somehow automatically.

**Comment by christhant** [comment]
Fields that need to display copy button when hover.
1. https://demo.nautobot.com/ipam/prefixes/2e8dd8c7-4ec2-4415-b64d-ce34cf5b2b09/?tab=main
- IPAM=> pre fix => ip address title needs to display copy button
- IP Address columns
2. https://demo.nautobot.com/ipam/vlans/52a457f4-e5d7-4efb-845d-abdde337e560/?tab=main
- IPAM=> vlan => prefix column needs to display copy button
3. https://demo.nautobot.com/dcim/devices/e71d056c-1b24-40f7-b4ec-276dfa3ebbad/?tab=main
asset tag needs to display copy button
4. https://demo.nautobot.com/circuits/circuits/8f361c7c-b477-48cc-9624-38e217f7e967?tab=main
circuit Id title need to display copy button
circuit table => Circuit ID need to display copy button
