### ISSUE TITLE
Editing an existing user token shows "create" buttons instead of "update"

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#153]
### Environment
* Python version:
* Nautobot version:

### Steps to Reproduce
1. Navigate to user "Profile"
2. Navigate to "API Tokens"
3. Click "Add token"
4. Click "Create"
5. From the token list view, click "Edit" on the token you just created

### Expected Behavior

There should be an "Update" button.

### Observed Behavior

There are "Create" and "Create and Add Another" buttons. 

![Cursor_and_Notification_Center](https://user-images.githubusercontent.com/138052/111223484-7176c900-859a-11eb-95c0-289b9361b01a.png)

**Comment by glennmatthews** [comment]
For whatever reason, it appears that `TokenEditView` is a subclass of the generic `ObjectEditView`, and therefore it's not automatically setting the `editing` flag in the context when calling `render()`. A simple fix would be to just add this flag; a better fix might involve investigating whether it would be possible to subclass `ObjectEditView` here instead.
