### ISSUE TITLE
UI: Device Type Import form title is incorrectly aligned

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot#1538]
### Environment
* Python version:  3.9.6
* Nautobot version: 1.2.9

### Steps to Reproduce
1. Go to Devices --> Device Type Import page

### Expected Behavior
The page title on the Device Type import page should be properly aligned, similar to all other import forms.

### Observed Behavior
The page title "Device Type Import" is not aligned properly.  It is aligned with the leftmost side of the page.

**Comment by glennmatthews** [comment]
![image](https://user-images.githubusercontent.com/5603551/161604718-6f16aa0a-a7e5-4e15-84a4-40f8202cb906.png)
