### ISSUE TITLE
NAPALM driver will not be displayed in Platforms page

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#155]
### Environment
* Python version: 3.8.5
* Nautobot version: 3.1.7

### Steps to Reproduce
1. Add platfom data
2. save

### Observed Behavior

The string 'ios' isn't displayed even it is stored

![Screenshot_missing_napalm_data](https://user-images.githubusercontent.com/8406301/111269021-5786c600-862e-11eb-87dc-bac1a52b5211.jpg)

Edit platform data shows its stored:

![Screenshot_defined_napalm_data](https://user-images.githubusercontent.com/8406301/111269179-8d2baf00-862e-11eb-9c24-85348290819f.jpg)

**Comment by jvanderaa** [comment]
I'll grab this one @jathanism @glennmatthews. I have the fix in that other PR that I need to take out.

**Comment by glennmatthews** [comment]
Would you mind also fixing the typo in "NAPALM argurments" while you're there? :-)

**Comment by jvanderaa** [comment]
Completely agree. I got the argument update in there as well.
