### ISSUE TITLE
/extras/git-repositories/ doesn't allow for nautobot_golden_config provided contents 

### ISSUE THREAD

**Issue by grahamneville** [nautobot/nautobot#1552]
### Environment
* Python version: 3.9
* Nautobot version: 1.2.8

### Steps to Reproduce
1. Attempt to POST to /extras/git-repositories and have a provider_contents of 'nautobot_golden_config.jinjatemplate'

### Expected Behavior

The API accepts it as it is a valid provider-contents if using the golden config plugin.
If you've configured manually and perform a GET on the same endpoint you'll see it appears in the list.

### Observed Behavior

The API rejects it as it only accepts 4 values. These can been seen via the Swagger API.

**Comment by glennmatthews** [comment]
This should be fixed by #1588.
