### ISSUE TITLE
Documentation cleanup

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot#1556]
### As ...

Ozzie - Operator

### I want ...

Documentation with less grammatical errors, typos, and adheres better to markdown formatting and linting requirements.

### So that ...

I can understand it better when I read it.

### I know this is done when...

The documentation has less grammatical errors and typos in it than it did previously.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [X] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

n/a

### External Dependencies

n/a

**Comment by bryanculver** [comment]
Closed with #1557
