### ISSUE TITLE
Epic: UX Research

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#1565]
### As ...

Cora - Coder

### I want ...

I want to research various aspects of User Experience (UX) paradigms and patterns and how they related to the types of user interactions that are most common in Nautobot

### So that ...

I have a better appreciation for the current state-of-the-art practices and can begin to apply them to an overhauled Nautobot web UI.

### I know this is done when...

All stories linked to this epic are completed.

### Optional - Feature groups this request pertains to.

- UI/UX

### Stories/Considerations

- [ ] #1537
- [x] #1064
- [x] #1851
- [ ] #2516
- [x] #2518
- [ ] #2525
- [ ] #2529 
- [ ] #2534
- [ ] #2796
- [ ] #2516
- [x] #2511
- [ ] #2975 
- [x] #3212
- [x] #3235
- [x] #1020

### Ideas

- When no objects exist in list view link to model documentation to explain what this model is and can be used for
- Being able to bulk/single-row edit items without leaving list view
- Being able to preview object on list view via fly-out from right hand side pane
- Context-specific dashboards
    - In addition to the global dashboard, clicking on the top-level contexts should load their own dashboards for a "one-level-deeper" overview of data

**Comment by jifox** [comment]
Hello,

I would like to see a multi-selection of checkboxes by selecting a range of checkboxes with the mouse.

The rectangle in this graphic is the selected range (Mouse move with left mouse-button down). 

![image](https://user-images.githubusercontent.com/8406301/205851584-282e7159-ccb4-4978-a4d1-fa8028549f1c.png)

After   releasing the left mouse button all checkboxes within the rectangle should be selected.

Also maybe take the `<Ctrl>` key into account to extend the current selection.
