### ISSUE TITLE
Epic: UI technology research & prototyping

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#1566]
## Direction

Currently Nautobot uses Bootstrap 3 & jQuery 3.6. We would like to overhaul the UI of Nautobot and we have a couple different approaches:

- Client-side (see #910, think NodeJS ala React, Angular, Vue.JS, etc)
- "Modern Web" (think HTMX, Alpine.js)
- Classic Web (HTML, CSS, JS)

Only the first option provides us a clearer way to get out of Django templating and using component/object-oriented front-end development.

To consider these approaches, each has their caveats of tools dependency, plugin ease-of-installation, maintainability, advanced capability. To that end we've identified five different approaches which may or may not need a bit of a bakeoff to consider fairly for the desired UI overhaul of Nautobot:

- [x] #2894
    - This is largely complete with the work done by #2319
    - #2272
    - #2952
    - **Needs Dan's Newer Prototypes Linked**
- [x] #2889
    - #2950
- [x] #2890
    - Comprised in #2950 
- [x] #2891
    - #2933
- [x] #2892
    - #2953

Some of the evaluation criteria we will consider with these approaches is:

- Dependency Management/Ease of Installation
    - Easy-mode Nautobot is a `pip install`, including with plugins. How much more difficult is any one of these approaches?
- Development Complexity
    - Rolling your own advanced functionality vs library built-ins
- Code Weight for the Common Case
    - How many lines does it take to create and view a new model
- Potential Code Reduction
    - Can we eliminate duplicate business logic and go all-API

To Implement in All Solutions:

- Location List View
- Location Create/Edit View
- Location Detail View
- Advanced Workflow: Create a Location Type from a Location Create/Edit View
- Integration: Have a plugin provide it's own model to be viewed (list,edit,detail) in the UI

Prototypes can either have some assumed solved problems or at least explain away and caveats to peak score on the criteria

> *Example:* While React was chosen for the prototypes for Client-side frontends, it's assumed Angular or VueJS should have relatively similar technical challenges they are seeking to address.

> *Example:* "Modern Web" prototype may still have jQuery in the DOM because they overhaul portions of the UI, its implementation doesn't use it directly and its saving time building out a whole new UI from scratch. Copy🍝! 

### Stories/Considerations

- [ ] #910
- [x] #1158
- [x] #3026 

#### Note
#2796 `BulkEditForms` on certain models are getting long just like the `FilterSetForms` on `ObjectListViews` were before. Just leaving a footnote here to remind us that we might want to consider changing that.

**Comment by bryanculver** [comment]
We will be posting a detailed scorecard for the competing prototypes from above based on criteria such as:

- User Responsiveness
- Complex UX Flows
- Core Maintenance
- App/Plugin Maintenance (Code & Environment)
- Production Deployment & Environment
- Core Provided Components - Effort
- App/Plugin “Coloring Outside the Lines/Ejecting” - Effort
- Tech Ecosystem & Longevity
- Migration
- Developer Learning Curve

**Comment by itdependsnetworks** [comment]
Without going to crazy, I think it would be good to consider the next level of detail:

- Ease of creating modals
- Ease of creating nested modals (think creating a device, device-type modal#1, manufacturer modal#2)
- Ease of creating table
    -  Accessor, link, action buttons
- Ease of creating a form
- Ease of inline editing
- Ease of copy text capability
- The ability to provide IPAM nesting (load on click)
