### ISSUE TITLE
Epic: Foundational UI components

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#1567]
- [ ] https://github.com/nautobot/nautobot/issues/1858
- [ ] #2586

**Comment by Kircheneer** [comment]
Following up a conversation with @glennmatthews I have two suggestions/requests here:

## Related-objects table

The `Provider` model has a table at the bottom of the detail view that shows all `Circuit` instances that belong to it. I am currently using the same pattern in a `VPN` -> `Tunnel` relationship and I can imagine it being useful in a multitude of scenarios.

![Screenshot 2022-11-03 at 14 12 37](https://user-images.githubusercontent.com/12400533/199729780-3228ab6a-2b3e-491b-bf94-decee7e0472c.png)

## Endpoint view

The `Circuit` has two panels on its detail view that either allow for the creation of or show the related circuit endpoints. In my plugin development case this could be useful for two `TunnelEndpoint` instances of a `Tunnel`, but I could reasonably see usage of this as a future addition to the `Cable` detail view as an example.

![Screenshot 2022-11-03 at 14 14 34](https://user-images.githubusercontent.com/12400533/199730208-4f784dde-a4a6-45a7-a9af-97d35700e58e.png)

**Comment by Kircheneer** [comment]
Adding another use case tot he endpoint view, its also re-implemented in the [BGP App](https://github.com/nautobot/nautobot-plugin-bgp-models/)
