### ISSUE TITLE
Epic: Developer Documentation Overhaul

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#1570]
## TODO

- [ ] #2981
     - Mostly based on the current `docs/plugins/development.md`, but removing the parts that are about setting up a development environment and such.
- [ ] #5217
     - How best to author models, etc.
     - Cross-reference: https://blog.networktocode.com/post/developing-nautobot-plugins-1/
- [ ] Model auto-docs
     - Probably get this for free with Django admin model docs
- [x] #2800 
- [x] #2982
    - Job Author
- [ ] #2983
    - Not Nautobot itself, but setting up your environment for success for Jobs or App

**Comment by glennmatthews** [comment]
Taking inspiration from the blog series starting at https://blog.networktocode.com/post/developing-nautobot-plugins-1/ would be an excellent idea.

**Comment by itdependsnetworks** [comment]
Please consider and/or at least be aware of the "classy" views. There is django classy https://ccbv.co.uk/ and drf-classy 
https://www.cdrf.co/. It helps provide the MRO of classes as well as make it easier to navigate the Class objects and show where the code originates from. The code used to generate classy views for django and drf could be used to do the same for Nautobot as well.


![image](https://user-images.githubusercontent.com/9260483/216630516-0bb8b437-ea30-488a-914b-2ba0e5fd128a.png)

**Comment by bryanculver** [comment]
Proposing changes to top-level sections:

- Overview
- User Guide (How to use Nautobot)
- Administrator Guide (How to deploy, admin Nautobot)
- Developer Guide (Jobs, Apps, etc, _maybe_ shove Maintainers guide in here)
- Release Notes (fix Overview page)
- Nautobot Apps
    - Future work could show links to the docs for the apps you have installed, as well as listing out all of the other ones

**Comment by bryanculver** [comment]
- Improve cross-linking between different sections of the documentation
    - Potentially investigate a plugin to help do this for us
- The target audience is mainly directed towards internal development, and very light on user guides, medium on feature guide
    - Feature Guide: "How to use `Namespaces`"
    - User Guide: "How to manage IPs in Nautobot"
        - Our current user guides are more so model/feature documentation
- Look at other excellent documentation as examples
    - Zero-to-hero

**Comment by bryanculver** [comment]
# Overview

- Move app stack to administrator guide
   - Should also be accessible from the developer guide
- A very basic "try it out" for getting started then segway into the full install
   - Link to demo
   - Link to docker compose
   - link to nautobot lab
- Bring Overview and README into close alignment but NOT the same file
- Summarize our Overview, Key Use case
- Ditch design philosophy (maybe some fragments go into the maintainers guide

**Comment by lampwins** [comment]
Also want to break out of the app/plugin API into individual pages, instead of one consolidated section/page.

**Comment by bryanculver** [comment]
- User Guide (How to use Nautobot)
      - User Guides (_Become Feature Guides_):
		      - **Re-order for grouping, and introductory to advanced** 
          - Creating Devices: "user-guides/getting-started/creating-devices.md"
          - Custom Fields: "user-guides/custom-fields.md"
          - Getting Started In the Web UI: "user-guides/getting-started/index.md"
          - Git as a Data Source: "user-guides/git-data-source.md"
          - GraphQL: "user-guides/graphql.md"
          - Interfaces: "user-guides/getting-started/interfaces.md"
          - IP Address Management: "user-guides/getting-started/ipam.md"
          - Platforms: "user-guides/getting-started/platforms.md"
          - Regions: "user-guides/getting-started/regions.md"
          - Tenants: "user-guides/getting-started/tenants.md"
          - The Search Bar: "user-guides/getting-started/search-bar.md"
          - Git as a Data Source: "user-guides/git-data-source.md"
          - GraphQL: "user-guides/graphql.md"
          - Relationships: "user-guides/relationships.md"
          - Django Storages with S3: "user-guides/s3-django-storage.md" **Move to Admin Guide**
          - VLANS and VLAN Groups: "user-guides/getting-started/vlans-and-vlan-groups.md"
  - Core Functionality:
	      - **Just a collection of the model documentation and could probably just go away**
      - Circuits: "core-functionality/circuits.md"
      - Devices and Cabling: "core-functionality/devices.md"
      - Device Types: "core-functionality/device-types.md"
      - IP Address Management: "core-functionality/ipam.md"
      - Power Tracking: "core-functionality/power.md"
      - Secrets: "core-functionality/secrets.md"
      - Service Mapping: "core-functionality/services.md"
      - Sites, Locations, and Racks: "core-functionality/sites-and-racks.md"
      - Tenancy: "core-functionality/tenancy.md"
      - Virtualization: "core-functionality/virtualization.md"
      - VLAN Management: "core-functionality/vlans.md"
  - Model Details (Becomes **Model Documentation**):
      - Circuits:
          - Circuit: "models/circuits/circuit.md"
          - Circuit Termination: "models/circuits/circuittermination.md"
          - Circuit Type: "models/circuits/circuittype.md"
          - Circuit Provider: "models/circuits/provider.md"
          - Circuit Provider Network: "models/circuits/providernetwork.md"
      - DCIM:
          - Cable: "models/dcim/cable.md"
          - Console Port: "models/dcim/consoleport.md"
          - Console Port Template: "models/dcim/consoleporttemplate.md"
          - Console Server Port: "models/dcim/consoleserverport.md"
          - Console Server Port Template: "models/dcim/consoleserverporttemplate.md"
          - Device: "models/dcim/device.md"
          - Device Bay: "models/dcim/devicebay.md"
          - Device Bay Template: "models/dcim/devicebaytemplate.md"
          - Device Redundancy Group: "models/dcim/deviceredundancygroup.md"
          - Device Role: "models/dcim/devicerole.md"
          - Device Type: "models/dcim/devicetype.md"
          - Front Port: "models/dcim/frontport.md"
          - Front Port Template: "models/dcim/frontporttemplate.md"
          - Interface: "models/dcim/interface.md"
          - Interface Template: "models/dcim/interfacetemplate.md"
          - Inventory Item: "models/dcim/inventoryitem.md"
          - Location: "models/dcim/location.md"
          - Location Type: "models/dcim/locationtype.md"
          - Manufacturer: "models/dcim/manufacturer.md"
          - Platform: "models/dcim/platform.md"
          - Power Feed: "models/dcim/powerfeed.md"
          - Power Outlet: "models/dcim/poweroutlet.md"
          - Power Outlet Template: "models/dcim/poweroutlettemplate.md"
          - Power Panel : "models/dcim/powerpanel.md"
          - Power Port: "models/dcim/powerport.md"
          - Power Port Template: "models/dcim/powerporttemplate.md"
          - Rack: "models/dcim/rack.md"
          - Rack Group: "models/dcim/rackgroup.md"
          - Rack Reservation: "models/dcim/rackreservation.md"
          - Rack Role: "models/dcim/rackrole.md"
          - Rear Port: "models/dcim/rearport.md"
          - Rear Port Template: "models/dcim/rearporttemplate.md"
          - Region: "models/dcim/region.md"
          - Site: "models/dcim/site.md"
          - Virtual Chassis: "models/dcim/virtualchassis.md"
      - Extras:
          - Config Context: "models/extras/configcontext.md"
          - Config Context Schema: "models/extras/configcontextschema.md"
          - GraphQL Query: "models/extras/graphqlquery.md"
          - Image Attachment: "models/extras/imageattachment.md"
          - Job: "models/extras/job.md"
          - Job Log Entry: "models/extras/joblogentry.md"
          - Job Result: "models/extras/jobresult.md"
          - Secret: "models/extras/secret.md"
          - Secrets group: "models/extras/secretsgroup.md"
      - IPAM:
        - Aggregate: "models/ipam/aggregate.md"
        - IP Address: "models/ipam/ipaddress.md"
        - Prefix: "models/ipam/prefix.md"
        - Rir: "models/ipam/rir.md"
        - Role: "models/ipam/role.md"
        - Route Target: "models/ipam/routetarget.md"
        - Service: "models/ipam/service.md"
        - VLAN: "models/ipam/vlan.md"
        - VLAN Group: "models/ipam/vlangroup.md"
        - VRF: "models/ipam/vrf.md"
      - Tenancy:
        - Tenant: "models/tenancy/tenant.md"
        - Tenant Group: "models/tenancy/tenantgroup.md"
      - Users:
        - Object Permission: "models/users/objectpermission.md"
        - Token: "models/users/token.md"
      - Virtualization:
        - Cluster: "models/virtualization/cluster.md"
        - Cluster Group: "models/virtualization/clustergroup.md"
        - Cluster Type: "models/virtualization/clustertype.md"
        - Virtual Machine: "models/virtualization/virtualmachine.md"
        - VM Interface: "models/virtualization/vminterface.md"
- Additional Features:
	    - **Split between model docs and feature docs** 
      - Caching: "additional-features/caching.md"
          - **Feature Guide**
      - Change Logging: "additional-features/change-logging.md"
          - **Feature Guide, need model docs**
      - Computed Fields: "models/extras/computedfield.md"
          - **Have model docs, need feature guide**
      - Context Data: "additional-features/config-contexts.md"
      - Custom Fields: "models/extras/customfield.md"
      - Custom Links: "models/extras/customlink.md"
      - Dynamic Groups: "models/extras/dynamicgroup.md"
      - Export Templates: "models/extras/exporttemplate.md"
      - Git Repositories: "models/extras/gitrepository.md"
      - Jobs: "additional-features/jobs.md"
		      - **Split between User, Administrator, and Developer**
      - Job Buttons: "models/extras/jobbutton.md"
		      - **Split between User, Administrator, and Developer**
      - Job Hooks: "models/extras/jobhook.md"
		      - **Split between User, Administrator, and Developer**
      - Job Scheduling and Approvals: "additional-features/job-scheduling-and-approvals.md"
          - **Split to Administrator, Feature Guide, need model docs**
      - NAPALM: "additional-features/napalm.md"
          - **Feature Guide, some admin relating to permissions**
      - Notes: "models/extras/note.md"
      - Relationships: "models/extras/relationship.md"
      - Statuses: "models/extras/status.md"
      - Tags: "models/extras/tag.md"
      - Template Filters: "additional-features/template-filters.md"
      - Webhooks: "models/extras/webhook.md"
  - REST API:
      - **Feature Guide**
      - Overview: "rest-api/overview.md"
          - **Break up into different pages like Filtering and Authentication**
      - Filtering: "rest-api/filtering.md"
      - Authentication: "rest-api/authentication.md"
  - GraphQL API:
      - **Feature Guide**
      - Overview: "additional-features/graphql.md"
          - **May need to be broken up into different pages**
--- 

- Administrator Guide (How to deploy, admin Nautobot)
	- Installation:
      - Installing Prerequisites: "installation/index.md"
      - Installing Nautobot: "installation/nautobot.md"
      - Deploying Nautobot Services: "installation/services.md"
      - Configuring an HTTP Server: "installation/http-server.md"
      - External Authentication (Optional): "installation/external-authentication.md"
      - Nautobot Docker Images: "docker/index.md"
	- Migration:
      - Migrating from NetBox: "installation/migrating-from-netbox.md"
      - Upgrading Nautobot: "installation/upgrading.md"
      - Migrating from PostgreSQL to MySQL: "installation/migrating-from-postgresql.md"
  - Configuration:
      - Configuring Nautobot: "configuration/index.md"
      - Required Settings: "configuration/required-settings.md"
      - Optional Settings: "configuration/optional-settings.md"
  - External Authentication:
      - LDAP: "configuration/authentication/ldap.md"
      - SSO: "configuration/authentication/sso.md"
      - Remote Header: "configuration/authentication/remote.md"
  - Administration:
      - Nautobot Server: "administration/nautobot-server.md"
      - Nautobot Shell: "administration/nautobot-shell.md"
      - Permissions: "administration/permissions.md"
      - Replicating Nautobot: "administration/replicating-nautobot.md"
      - Task Queues: "administration/celery-queues.md"
  - Installing and Using Plugins: "plugins/index.md"
  - Health Check: "additional-features/healthcheck.md"
      - **Administrator Guide**
  - Prometheus Metrics: "additional-features/prometheus-metrics.md"
      - **Administrator Guide**

---

- Developer Guide (Jobs, Apps, etc, _maybe_ shove Maintainers guide in here)
	- Developing Apps: "plugins/development.md"
			- **The top level needs to be split out into sections, WAY TOO BIG**
      - Porting NetBox Plugins to Nautobot: "plugins/porting-from-netbox.md" **Consider removing**
      - Code Reference (Autodocs):
          - nautobot.apps: "code-reference/nautobot/apps/__init__.md"
          - nautobot.apps.admin: "code-reference/nautobot/apps/admin.md"
          - nautobot.apps.api: "code-reference/nautobot/apps/api.md"
          - nautobot.apps.choices: "code-reference/nautobot/apps/choices.md"
          - nautobot.apps.datasources: "code-reference/nautobot/apps/datasources.md"
          - nautobot.apps.filters: "code-reference/nautobot/apps/filters.md"
          - nautobot.apps.forms: "code-reference/nautobot/apps/forms.md"
          - nautobot.apps.models: "code-reference/nautobot/apps/models.md"
          - nautobot.apps.secrets: "code-reference/nautobot/apps/secrets.md"
          - nautobot.apps.tables: "code-reference/nautobot/apps/tables.md"
          - nautobot.apps.testing: "code-reference/nautobot/apps/testing.md"
          - nautobot.apps.ui: "code-reference/nautobot/apps/ui.md"
          - nautobot.apps.urls: "code-reference/nautobot/apps/urls.md"
          - nautobot.apps.views: "code-reference/nautobot/apps/views.md"
  - Autodocs for all other code (models, filtersets, serializers, etc) can/should be published in the developer docs to but is a different audience than the app API autodocs
 - Core Developer Guide (split):
	 - **Maintainer & App developer guide**
      - Best Practices: "development/best-practices.md"
      - Style Guide: "development/style-guide.md"
      - Extending Models: "development/extending-models.md"
	      - Cross-reference to develop apps
      - Generic Views: "development/generic-views.md"
      - Page Templates: "development/templates.md"
      - Navigation Menu: "development/navigation-menu.md"
      - Home Page Panels: "development/homepage.md"
      - User Preferences: "development/user-preferences.md"
      - Testing: "development/testing.md"
		- **Maintainer-specific guide**
      - Introduction: "development/index.md"
      - Getting Started: "development/getting-started.md"
      - Advanced Docker Compose Usage: "development/docker-compose-advanced-use-cases.md"
      - Application Registry: "development/application-registry.md"
      - Release Checklist: "development/release-checklist.md"

---
