### ISSUE TITLE
Epic: Apps Refactor

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#1575]
## Purpose

Nautobot as a platform is broken up across many apps (`Core`, `Extras`, `Utilities`) which at this point provides little to no value for separation and in fact, causes more problems when it comes to imports and discovery.

The "Core" features of Nautobot are contained across the apps above.

## Plan

Collapse `Extra` and `Utilities` Apps into `Core`. Further, to help with discovery we will expose a "Plugin-App" "API" to aid Nautobot App (also/formerly known as a plugin) developer in knowing what models, functions, views, etc are safe to import from. Think: `nautobot.applib.models.dcim` (no that is not a final convention).

## TODO
- [x] #2721
- [x] #2723
- [ ] #3165 

## Related

- #204 (Utilities is completed, extras not being done for this milestone)
   - Not required to complete epic
- ~#2722~
   - Canceled

**Comment by bryanculver** [comment]
After #3035 and #2826 we probably need to consider #2721 and #2722 to be done in one large body of work to get around circular import issues.

**Comment by bryanculver** [comment]
Breaking changes completed. #3165 is not a 2.0-breaking change, more-so migration readiness.
