### ISSUE TITLE
Removing custom field does not clean up choices from objects

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#1582]
### Environment
* Python version: 3.6.15
* Nautobot version: 1.2.10

I deleted a custom field of type Selection, the assigned values remained in database. I could get them in ORM (`obj.cf["custom_field_name"]`), but not API. I was not able to remove or edit any object that had value of this custom field set. I had to write quick ORM script to do it for me, including changelog creation for this deletion, because the next user who would change the object would appear to change `custom_fields` too.

Note: When fixing this, please make sure changelog is created for any object having a choice of this Selection cf assigned.

### Steps to Reproduce
1. create new custom field with type Selection, assign to a model
2. create a choice for this custom field
3. create new object of the chosen model, set value for this custom field to the choice
5. delete the custom field
6. edit/delete the object

### Expected Behavior
object edited/deleted

### Observed Behavior
`Unknown field name `CUSTOM_FIELD_NAME` in custom field data.
![image](https://user-images.githubusercontent.com/26114847/160878194-132ba3f1-f212-4c63-aba3-e845d5b92a5e.png)

**Comment by nniehoff** [comment]
I have confirmed this is a bug in 1.2.10 and the current develop branch

**Comment by briddo** [comment]
Follow-up issue created to add change logging #1631

**Comment by glennmatthews** [comment]
Implemented in `next` by #1626.
