### ISSUE TITLE
Update documentation for external authentication SSO Backend to get a proper install

### ISSUE THREAD

**Issue by syyna** [nautobot/nautobot#159]
### Environment
* Python version: 3.8.5
* Nautobot version: 1.02b

### Steps to Reproduce
1. Follow steps to install SAML SSO backend in https://nautobot.readthedocs.io/en/latest/configuration/authentication/sso/
2. Run into several issues due to incomplete documentation of dependencies to install
3.

### Expected Behavior
Following the doc should get me to the intended next step

### Observed Behavior
Following the doc led me to an error

### Fix
These are the proper steps for SAML dependencies for external authentication:
Using sudo outside the venv

1.  sudo apt install -y libxml2-dev libxmlsec1-dev libxmlsec1-openssl pkg-config

Switching to user nautobot and installing within the venv.
2. sudo -iu nautobot
3. source bin/activate
4. pip install testresources
5. pip install --upgrade pip setuptools wheel
6. pip install python3-saml

This is tested on ubuntu 20.04 with the base nautobot install using the nautobot install docs.

**Comment by jathanism** [comment]
Thanks @syyna for the report! 👀

**Comment by dgjustice** [comment]
This is related to issue #149
