### ISSUE TITLE
Don't import jobs as top-level modules

### ISSUE THREAD

**Issue by u1735067** [nautobot/nautobot#1598]
### As ...

Austin - Network Automation Engineer

### I want ...

Nautobot to load jobs in a dedicated per-source namespace

### So that ...

it provides a safe way to load Jobs, preventing an eventual misnaming mistakes (file named `sys.py` for example), prevent collisions (2 sources with `my_jobs.py` for example), allow to unload all jobs safely (`del sys.modules[i] for i in sys.modules if i.startswith('nautobot.jobs.')` or to refresh per-project jobs (`del sys.modules[i] for i in sys.modules if i.startswith('nautobot.jobs.my_source')`.

### I know this is done when...

I can load 2 job sources with the same filename

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [X] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

None in the 1.2.x branch?

### External Dependencies

None?

**Comment by u1735067** [comment]
In the same idea, all code written by devs are running in a `Job(BaseJob)` instance, where many variable are already set, so it may be possible the dev accidentally overwrite job variables ; for example (dummy job):
```py
class MyJob(Job):
  parts = ('part1', 'part2')
  def run(self, data: dict, commit: bool):
    self.failed = False
    for part in self.parts:
      getattr(self, part)()
      if self.failed:
        return

  def part1(self):
    self.failed = True

  def part1(self):
    self.failed = False
```

A possible evolution could be to "sandbox" dev class like this, still giving access to the job instance in a variable:
```py
class JobExecNS:
  def __init__(self, job: Job):
    self.job = job

class MyJob(JobExecNS):
  def run(self, data: dict, commit: bool):
    self.job.log_info('Hello world!')
    self.failed = False
    self.job.log_info(f'failed={self.failed}, job.failed={self.job.failed}')
```

**Comment by bryanculver** [comment]
@gsnider2195 @jathanism I believe with the jobs overhaul this has been addressed, correct?

**Comment by jathanism** [comment]
> @gsnider2195 @jathanism I believe with the jobs overhaul this has been addressed, correct?

That is correct!

**Comment by bryanculver** [comment]
Closed via #765

**Comment by glennmatthews** [comment]
Sorry to nitpick, but this isn't fully addressed, at least not in the way requested by the submitter. 

- Manually installed jobs are *not* namespaced (`JOBS_ROOT/myjob.py` gets imported as module `myjob`, not as something like `nautobot.jobs.myjob`).
- We do have code in place now to reject loading jobs that conflict with existing modules.packages (`sys.py` will not be imported and will not clobber the stdlib `sys.py`) at least
- Git repo jobs are now namespaced by the repo slug (`GIT_ROOT/mygitrepo/myjob.py` --> `mygitrepo.myjob` module)

This is *most* of the way there IMO. Just wanted to be clear.

**Comment by bryanculver** [comment]
> Sorry to nitpick, but this isn't fully addressed, at least not in the way requested by the submitter.
> 
> * Manually installed jobs are _not_ namespaced (`JOBS_ROOT/myjob.py` gets imported as module `myjob`, not as something like `nautobot.jobs.myjob`).
> * We do have code in place now to reject loading jobs that conflict with existing modules.packages (`sys.py` will not be imported and will not clobber the stdlib `sys.py`) at least
> * Git repo jobs are now namespaced by the repo slug (`GIT_ROOT/mygitrepo/myjob.py` --> `mygitrepo.myjob` module)
> 
> This is _most_ of the way there IMO. Just wanted to be clear.

To @u1735067 original "I know when this is done when"

> I can load 2 job sources with the same filename

Can this be done?

**Comment by u1735067** [comment]
Sorry for not making the US as precise as required, @glennmatthews got my point right in https://github.com/nautobot/nautobot/issues/1598#issuecomment-1674689308, the title of this story is not satisfied, the idea was really to have a common Nautobot specific namespace, then namespace per source (so local should be in `.local.` maybe?).

Also https://github.com/nautobot/nautobot/issues/1598#issuecomment-1265124529 is probably another whole US, but I don't know if you're interested in that (but as someone who see people not that much experimented in development, usually network people, developing jobs, I think this would be useful).

**Comment by bryanculver** [comment]
> Sorry for not making the US as precise as required, @glennmatthews got my point right in [#1598 (comment)](https://github.com/nautobot/nautobot/issues/1598#issuecomment-1674689308), the title of this story is not satisfied, the idea was really to have a common Nautobot specific namespace, then namespace per source (so local should be in `.local.` maybe?).
> 
> Also [#1598 (comment)](https://github.com/nautobot/nautobot/issues/1598#issuecomment-1265124529) is probably another whole US, but I don't know if you're interested in that (but as someone who see people not that much experimented in development, usually network people, developing jobs, I think this would be useful).

Are you writing jobs exclusively locally or Git repo? I suspect with your comment you aren't developing with Apps/Plugins in mind.

**Comment by u1735067** [comment]
> Are you writing jobs exclusively locally or Git repo?
Using git repo exclusively

> I suspect with your comment you aren't developing with Apps/Plugins in mind.
True ^^

**Comment by bryanculver** [comment]
So as far as the clobbering is concerned (and @glennmatthews keep me honest):

Two network engineers wouldn't be able to write two jobs with the same name in the same file without it being an obvious collision.

Say: 
```py
# JOBS_ROOT/engineer_a.py 

class MyJob(BaseJob):
#...
```

```py
# JOBS_ROOT/engineer_b.py 

class MyJob(BaseJob):
#...
```

Those would be namespace/classpath as `engineer_a.MyJob` and `engineer_b.MyJob` respectively.


GitRepo would be similar; If it's the same repo they'd have their own files. If it's different repos it would be:

```py
GitRepository(name="Engineer A's Jobs", slug="engineer_a_git")
GitRepository(name="Engineer B's Jobs", slug="engineer_b_git")
```

`engineer_a_git.jobs.MyJob` and `engineer_b_git.jobs.MyJob`

Maybe there's an edge-case for a local file matching the slug of a GitRepo? I think there is some tiebreaking there?

**Comment by glennmatthews** [comment]
> Maybe there's an edge-case for a local file matching the slug of a GitRepo? I think there is some tiebreaking there?

Probably yes - I'm not sure which one would win in the case of this collision without testing it, but in any case only one or the other would be loaded, never both.
