### ISSUE TITLE
Spike: Create design spec for FilterSet (don't shadow, when to not use magic fields, etc)

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#1606]

**Comment by jathanism** [comment]
First draft: https://gist.github.com/jathanism/a61d3a3cbd2ee7721bf40c6ac0ef294e

**Comment by bryanculver** [comment]
> First draft: https://gist.github.com/jathanism/a61d3a3cbd2ee7721bf40c6ac0ef294e

Will this live here? https://github.com/nautobot/nautobot/tree/develop/nautobot/docs/development

**Comment by jathanism** [comment]
> > First draft: https://gist.github.com/jathanism/a61d3a3cbd2ee7721bf40c6ac0ef294e
> 
> Will this live here? https://github.com/nautobot/nautobot/tree/develop/nautobot/docs/development

Yeah to me it seems like it would fit perfectly as part of the style guide. After we codify this, I think it would be wise to follow up with introducing linter checks to enforce these.

**Comment by bryanculver** [comment]
Additional feedback provided on Gist.
