### ISSUE TITLE
Spike: Inventory gaps of FilterSet fields to models (and delta between design above and current FilterSets)

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#1607]

**Comment by jathanism** [comment]
Check out this super secret Google Doc with the contents I provided so it's easier to comment on it:

https://docs.google.com/document/d/1NBgjAhhuev0BnzB4_nArsg9gB8eObi8Z1lI6d7CsXB4/edit#heading=h.6irw5dcblzqj

And just for transparency here is the compiled document for anyone in the community who is curious:

https://gist.github.com/jathanism/7c585954da4cb1a54997be31991cdaac
