### ISSUE TITLE
Spike: Design UX for using/customizing a FilterForm

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#1608]
### Requirements
- Not display all permutations of fields and lookup expressions simultaneously (by default)
- Provide the user an ability to select any field and lookup expression combination supported by the FitlerSet to filter the table by
- Provide the user with an ability to edit, view current filter arguments
- Provide the user the ability to specify an arbitrary number of filters

### Non-requirements
- Filtering arbitrary by nested lookup

**Comment by timizuoebideri1** [comment]
# FilterForm - UI Design

### Changes Made:

- (1) Filtered elements appear as labels just below the page title . (2) FilterForm moved from the right sidebar to a modal, 
  <img width="1543" alt="Screenshot 2022-06-27 at 11 04 56 PM" src="https://user-images.githubusercontent.com/94907097/176044705-63dd535b-695c-4fb4-83c5-c81a51a65137.png">
  <img width="1543" alt="Screenshot 2022-06-27 at 11 06 28 PM" src="https://user-images.githubusercontent.com/94907097/176044957-041b690a-2ae5-44f5-af3a-cc62a8f313f1.png">

### Features

1. All fields and their related lookup expressions are available on the FilterForm, which means any filtering combination performed on the API FilterSet can now be performed on the FilterForm.

**Figure 1**: List of all available model fields
<img width="1543" alt="Screenshot 2022-06-27 at 11 06 46 PM" src="https://user-images.githubusercontent.com/94907097/176046426-8ee6aa4e-056b-4c76-9a35-7f13e793232f.png">

**Figure 2**: List of related lookup expression
<img width="1543" alt="Screenshot 2022-06-27 at 11 06 52 PM" src="https://user-images.githubusercontent.com/94907097/176046654-eeec8526-0ece-437b-951e-389790d4decb.png">
_**Note**: Only lookup expr related to that field would show-up in the `Lookup type` field_

**Figure 3**: `Value` would either be a dropdown or an input field depending on `Field` and `Lookup Type` selected choices
<img width="1543" alt="Screenshot 2022-06-27 at 11 07 43 PM" src="https://user-images.githubusercontent.com/94907097/176047197-0a4f6b34-2ab0-47f6-aaa1-e9e41201cead.png">

<img width="1543" alt="Screenshot 2022-06-27 at 11 07 51 PM" src="https://user-images.githubusercontent.com/94907097/176047228-9caed2a6-f373-4a9b-b6aa-32c8eaeb9855.png">

If the `Field` choice is not a Relational field(Foreign Key, ManyToMany, OneToOne e.t.c) then the `Value` field would be an input field, while if the `Field` choice is a Relational field and the `Lookup Type` choice is `n - exact`, the `Value` field would be a dropdown populated by appropriate data

**Figure 4**: Add more Filter Fields
<img width="1543" alt="Screenshot 2022-06-27 at 11 42 40 PM" src="https://user-images.githubusercontent.com/94907097/176048623-c2672766-833c-43ab-aa22-1b8afba509f4.png">
By clicking on the` Add another field` button you can add as much filter field as desired

**Comment by bryanculver** [comment]
Closing as prototype in branch (see #1972) and screenshots above.
