### ISSUE TITLE
Job Log Output Containing URL Links

### ISSUE THREAD

**Issue by lgilroy-ibkr** [nautobot/nautobot#1613]
### As ...

Cora - Coder

### I want ...

The ability to allow Log output in jobs to show a URL link for the client to click on.  I tried to add mark_safe and format_html to the self.log_info(message=...) but it only displays the string I want the ability to allow it to be a href whihc would be clickable.

### So that ...

The user has the ability to view additional ouptut of the Job Running that I cannot display in the log message output for the job.

### I know this is done when...

An option is available for additional fields in the jobs to be shown or I have the ability to add a farmetatted HTML Href in the log output.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

Not Sure

**Comment by glennmatthews** [comment]
Hi @lgilroy-ibkr,

The message logs support Markdown formatting, so you should be able to do something like `self.log_info(message="[Click here](http://example.com)")` if you want a hyperlink in the logs. Does this meet your needs?

**Comment by lgilroy-ibkr** [comment]
Hi @glennmatthews ,

Thank you for the quick feedback this is great, thank you I didn't realize Mark Down was supported and then I reread the documentation and it says it there.    Sorry, thanks for this.

I will close it.

~Lloyd
