### ISSUE TITLE
GraphQL crashes with AssertionError on custom fields with "." in the slug

### ISSUE THREAD

**Issue by frdaigne** [nautobot/nautobot#1618]
* Python version: 3.9.10
* Nautobot version:1.2.8

### Steps to Reproduce
1. Create a custom field with a dot "." in the slug (e.g. "Misc.") and bind it to an object (e.g. ipam.ipaddress)
2. Populate the field value on a object (e.g. a ip-address, with value "Misc.= loopback")
3. Navigate to /graphql

### Expected Behavior
dot "." should not be allowed into a slug if GraphQL does not like it

### Observed Behavior
<class 'AssertionError'>

Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "cf_misc." does not.

**Comment by glennmatthews** [comment]
Fixed for 2.0 by #3426; users can no longer create custom fields with non-permissible `key` strings.
