### ISSUE TITLE
Bulk Operation Schema Views are Incorrect

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#1619]
### Environment
* Python version: 3.6+
* Nautobot version: 1.2+ (confirmed in `next` as well)

### Steps to Reproduce
1. View https://demo.nautobot.com/api/docs/#operations-ipam-ipam_ip-addresses_bulk_partial_update
2.
3.

### Expected Behavior

Schema for bulk update should be a list of the models.

### Observed Behavior

Schema shows as a single object for the bulk update methods.

**Comment by glennmatthews** [comment]
This appears to still be an issue after #1544.
