### ISSUE TITLE
Add database backup/restore to invoke tasks

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#162]
### Environment
* Python version: 3.8.5
* Nautobot version: 1.0.0-beta.2

### Proposed Functionality

Add a functionality to backup and restore the nautobot database.

if possible:
   invoke backup filename 
   invoke restore filename 

### Use Case

To allow easy script triggered database backups it wolud be nice to have a invoke command to start the backup process.

### Database Changes

None

### External Dependencies

None

**Comment by jedelman8** [comment]
Going to tentatively add into 1.1.
