### ISSUE TITLE
Remove monkey-mixin for `TaggableManager`

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#1633]
### Proposed Changes

For v2, per [this PR comment](https://github.com/nautobot/nautobot/pull/1505/files/fdfd0df621f195b45f19ee922e7b5d7c9bf2bd05) 

- [ ] Remove the `monkey_mix` from `nautobot.core.apps.CoreConfig.ready()`
- [ ] Convert `nautobot.extras.models.mixins.TaggableManagerMonkeyMixin` into a subclass of `taggit.managers.TaggableManager`  instead of a mixin and move it to `nautobot.extras.models.managers.TaggableManager` (assuming this stays in `extras`)
- [ ] Replace all `from taggit.managers import TaggableManager` references to `from nautobot.extras.models.managers import TaggableManager`
- [ ] Generate database migrations to account for the underlying model code changes (no schema changes required)

### Justification

This should be removed in v2 since we will no longer care about backwards-incompatibility and we can assert forward migration to move away from the need to monkey-mix `taggit.managers.TaggableManager`.

**Comment by glennmatthews** [comment]
Implemented in #3641.
