### ISSUE TITLE
Spike: Identify opportunities to introduce proper indexing on model fields

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#1639]
### Proposed Changes

We should inventory the core data models for opportunities to introduce field-level (using [`db_index=True`](https://docs.djangoproject.com/en/4.0/ref/models/fields/#db-index)) and compound indexes (using [`index_together`](https://docs.djangoproject.com/en/4.0/ref/models/options/#index-together)).

As a result of this effort we should both add the appropriate indexing, and also update our development guidelines to always gate on indexing and performance impact of related model changes.

### Justification

Most of the data models in the core are not making proper use of field-level indexes or compound indexes for commonly-queried field sets. This is one of the quickest and easiest ways to get notable performance increases that will result in huge usability improvements.

### Requirements

- Review all internal QuerySet filters, lookups and identify better opportunities for indexing
- Ensure we don't overly index tables, incurring update/create penalties
- Create housekeeping backlog to further groom each app's models as commonly filtered by end-user (to be done over sprints)

**Comment by jathanism** [comment]
As an example: #1638 is a exponentially scaling performance issue directly related to a lack of proper indexing.

**Comment by bryanculver** [comment]
Closed via #1793. #1615 updated.
