### ISSUE TITLE
Uses of json.dumps and yaml.dump should render UTF-8 characters correctly

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#1652]
Thank you to @sirtux for reporting this!

### Environment
* Python version:
* Nautobot version: 1.3

### Steps to Reproduce

1. Create a custom field of type JSON
2. Populate an individual custom field entry with JSON containing non-ASCII characters, for example: `{ "Hello World": "I am UTF-8! 💩" }`
3. View the object detail page containing this populated custom field.

### Expected Behavior

Non-ASCII characters to render correctly

### Observed Behavior

Non-ASCII characters are escaped:

![image](https://user-images.githubusercontent.com/5603551/163824756-b1a107e9-7a2c-45bc-a15b-c7b9c0eda511.png)

This appears to be because [`json.dumps` defaults to `ensure_ascii=True`](https://docs.python.org/3/library/json.html#character-encodings); adding an explicit `ensure_ascii=False` to `nautobot.utilities.templatetags.helpers.render_json()` results in the expected Unicode rendering.

We should scan through our code for any other instances of `json.dumps` that may warrant a similar change as well.

**Comment by bryanculver** [comment]
Changing `json.dumps` in the method called out above does work but there are several other places that use `render_json()` and those should be evaluated if they need `ensure_ascii` set to True.

Was investigating getting this out with 1.3.1 but due to the above figured it needed further review and #1662 was urgent.

**Comment by glennmatthews** [comment]
Need to check whether our YAML rendering has a similar issue.
