### ISSUE TITLE
contrib directory is missing (including the apache.conf)

### ISSUE THREAD

**Issue by htam-net** [nautobot/nautobot#166]
### Environment
* Python version: 3.6
* Nautobot version: 1.0.0b2

### Steps to Reproduce
1. Follow the steps for the Apache installation
2.
3.

### Expected Behavior
the contrib directory is present

### Observed Behavior
The contrib directory isn't included.

**Comment by htam-net** [comment]
Also, the apache installation guideline is described for Debian/ubuntu and not RHEL/CentOS. Also, it would be great to consider that the "default" Apache is quite old and you may require to use the SCL repo which change the path (of dependencies).

**Comment by glennmatthews** [comment]
Thanks for the information! Just wanted to note that #165 was just opened today and is proposing to remove the Apache configuration altogether. I'd appreciate your feedback on that proposal -- in particular, do you require Apache for your environment or would the alternative NGINX approach work just as well for you?

**Comment by htam-net** [comment]
NGINX would be fine ... but I never have an occasion to start learning it... so for the next time, I will try with NGINX.

By the way, I don't for the nginx installation, but with Apache, there is permission to correct to that httpd can access the /static directory.

**Comment by jathanism** [comment]
I'll be honest, seeing as we've been discussing ditching Apache altogether we have yet to revise these instructions. So great catch tho. Thanks for the submission.
