### ISSUE TITLE
Job (model) changelog are displayed without page header

### ISSUE THREAD

**Issue by u1735067** [nautobot/nautobot#1660]
### Environment
* Python version: 3.10
* Nautobot version: 1.3.0

### Steps to Reproduce
1. Install an instance and install jobs
2. Navigate to the Job model page
3. Click "Changelog"

### Expected Behavior
Job model header and navbar is still displayed

### Observed Behavior
Bare changelog is displayed

**Comment by bryanculver** [comment]
Thanks for the report @u1735067. Confirmed.

**Comment by u1735067** [comment]
I can't test right now, but a fix might be:

* https://github.com/nautobot/nautobot/blob/v1.3.5/nautobot/extras/views.py : 
```py
from nautobot.extras.views import ObjectChangeLogView

class JobChangeLogView(ObjectChangeLogView):
    base_template = "base.html"
```

* https://github.com/nautobot/nautobot/blob/v1.3.5/nautobot/extras/urls.py#L378:
```py
    path(
        "jobs/<slug:slug>/changelog/",
        views.JobChangeLogView.as_view(),
        name="job_changelog",
        kwargs={"model": Job},
    )
```

To force the generic template, because the `job.html` template is very specific.
