### ISSUE TITLE
Access dynamic groups from assigned objects in graphql

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot#1690]
### As ...

Austin - Network Automation Engineer

### I want ...

I want the ability to access dynamic groups assigned to an object at call time via a graphql query. 

### So that ...

So I can access other data that may be associated with the dynamic group

### I know this is done when...

I can query the dynamic groups associated to an object (example device) via graphql

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

Should be none

### External Dependencies

None

**Comment by glennmatthews** [comment]
This is possible following #5472:

![image](https://github.com/user-attachments/assets/eddecf6a-c343-4c65-b136-4e72a61e3e83)
