### ISSUE TITLE
Incorrect tag search - illusory duplicates returned

### ISSUE THREAD

**Issue by david-kn** [nautobot/nautobot#1692]
* Python version: 3.10
* Nautobot version: 1.3.2

### Steps to Reproduce
1. Search for an existing tag (in my case substring, e.g. `exclude`):
  - either in `Organization`-> `Tags` page or
  - when adding tag for any other object (see attached images)

### Expected Behavior
Only existing (unique) tag(s) should be returned.

### Observed Behavior
There are too many returned tags (not unique) that are duplicate (as for each model would exist individual tag with the same name). The number of returned duplicate tags correspond with a number of attached models to a given tag (in my case 35)

![image](https://user-images.githubusercontent.com/14314517/165064369-f0ba179f-e7a6-48d9-a6df-c31a8fefdd78.png)
![image](https://user-images.githubusercontent.com/14314517/165064376-9d2b880f-9149-4860-939a-d786a1c53f28.png)

btw. So far, I noticed this only for `Tags` but not for `Statuses` which can also be connected with multiple models.

**Comment by glennmatthews** [comment]
I can confirm this issue. It does *not* happen in the base Tags list (un-searched), but does appear when a search is issued.

**Comment by glennmatthews** [comment]
The below diff appears to fix the issue:

```diff
diff --git a/nautobot/extras/filters.py b/nautobot/extras/filters.py
index 48a0a4550..338a858a9 100644
--- a/nautobot/extras/filters.py
+++ b/nautobot/extras/filters.py
@@ -977,7 +977,7 @@ class TagFilterSet(NautobotFilterSet):
             return queryset
         return queryset.filter(
             Q(name__icontains=value) | Q(slug__icontains=value) | Q(content_types__model__icontains=value)
-        )
+        ).distinct()
 
 
 #
```

**Comment by david-kn** [comment]
Thanks Glen for confirmation :-) To filter and show only _distinct_ values was my inner guess as well.
