### ISSUE TITLE
Mass edit is not working for some IP addresses due to `assigned_object` validation

### ISSUE THREAD

**Issue by david-kn** [nautobot/nautobot#1693]
* Python version: 3.10
* Nautobot version: 1.3.2 (tested & failed also with 1.2.11)

### Steps to Reproduce
1. Select at least two IP addresses (don't know how to more properly identify "problematic" addresses from GUI because for some it works without error)
2. Choose "Edit selected" in order to mass edit multiple objects
3. Modify objects (probably anyhow) (I tried to add a tag or add a comment)

### Expected Behavior
Objects should be updated without any errors.

### Observed Behavior
Saving failed with an error related to `assigned_object_type` and `assigned_object_id`. **But when I edit the very same objects individually the save is successful without any issues!** This is a strange difference between validation happening upon saving a single address vs bulk save of multiple addresses.
![image](https://user-images.githubusercontent.com/14314517/165080682-44b527f2-c994-4a7e-b47d-59723b6f1221.png)

Maybe the issue could be also related to this PR: https://github.com/nautobot/nautobot/pull/1592 ? (I tried just a simple & quick search based on keywords from error message) 

btw. [Your demo nautobot](https://demo.nautobot.com/) instance is not working (can't login either with demo credentials) so I couldn't test it and provide links from your environment.

**Comment by bryanculver** [comment]
@david-kn Our demo rig is back up and running and I am not able to reproduce this bug. The IPs that throw errors, are they assigned to an object?
<img width="1169" alt="Screen Shot 2022-04-25 at 12 44 04" src="https://user-images.githubusercontent.com/31187/165135626-ae17eea9-c972-451a-9856-f30e661efdca.png">
<img width="1508" alt="Screen Shot 2022-04-25 at 12 44 23" src="https://user-images.githubusercontent.com/31187/165135635-171227d2-d6f6-438d-9898-e235e693c000.png">

<img width="1512" alt="Screen Shot 2022-04-25 at 12 47 13" src="https://user-images.githubusercontent.com/31187/165135645-359b2dd6-df19-417a-8810-870dfe10f200.png">

**Comment by snaselj** [comment]
Hello,

as we were debugging mass edit of 2 IP Address, we got this log from `self.__dict__` on the following line: https://github.com/nautobot/nautobot/blob/v1.3.2/nautobot/ipam/models.py#L863

```
WARNING:root:DICT {'_state': <django.db.models.base.ModelState object at 0x7f0361c91330>, 'id': UUID('89ea21c2-1360-5e27-bccd-93a568643a1e'), 'created': datetime.date(2019, 11, 20), 'last_updated': datetime.datetime(2022, 3, 4, 16, 42, 47, 227270, tzinfo=<UTC>), '_custom_field_data': {'asw_owner': 'NET', 'application_owner': None, 'asw_reverse_hostname': None, 'asw_comment': 'brekeek'}, 'status_id': UUID('c96a5993-f215-41f0-b1fc-9e0aadb6d6bf'), 'host': '5.62.25.2', 'broadcast': '5.62.25.127', 'prefix_length': 25, 'vrf_id': None, 'tenant_id': None, 'role': 'vip', 'assigned_object_type_id': 37, 'assigned_object_id': None, 'nat_inside_id': None, 'dns_name': '', 'description': 'Reserved for BBC/NET', '_django_version': '3.2.13', '_prefetched_objects_cache': {}, 'add_tags': <TagQuerySet []>, 'remove_tags': <TagQuerySet []>}
```

There is `'assigned_object_type_id': 37, 'assigned_object_id': None` that causes error raising on line:
https://github.com/nautobot/nautobot/blob/v1.3.2/nautobot/ipam/models.py#L866

The strange thing is that `object_type: 37` == `dcim.interface`

**Comment by sirtux** [comment]
I've seen similar thing happening - if you delete the assigned_object_id by API or anything else, that is accepted even if the object_type stays. 

This definetely is #1592, which fixes that for new changes, but not for existing issues. 

To solve that, you need to run through all ip adresses, check if assigned_object_id is None and if so, also set assigned_object_type_id to None, should be a simple 10 liner for nbshell, or so.

**Comment by ubajze** [comment]
I am able to reproduce this if I manually change the `assigned_object_id` to None.

```
>>> ip.assigned_object_id = None
>>> ip.save()
>>> ip.assigned_object_id
>>> ip.assigned_object_type_id
25
```

![Screenshot 2022-04-26 at 11 47 09](https://user-images.githubusercontent.com/6861762/165272705-f584efcb-489e-4a32-9402-10442fc57eb9.png)

I am not sure how to get to this state from UI.

**Comment by ubajze** [comment]
This is sample code that can be executed in nbshell:
```
>>> for ip in IPAddress.objects.all():
...  if ip.assigned_object_id is None:
...   ip.assigned_object_type_id = None
...   ip.save()
```

**Comment by snaselj** [comment]
@ubajze Thanks for the hint, however data are consistent when viewing through API:

http://localhost:9843/api/ipam/ip-addresses/5bef067e-b35e-59d9-9752-328f427a74a3/
```
{
    "id": "5bef067e-b35e-59d9-9752-328f427a74a3",
    ...
    "assigned_object_type": null,
    "assigned_object_id": null,
    "assigned_object": null,
    ...
}
```

After "single" editing this IP address, mass edit starts to work.

**Comment by ubajze** [comment]
@snaselj yeah API returns `null` for all the above objects (similar to what you can see in UI). But values are not null for all objects if you check nbshell.

API:
```
  "assigned_object_type": null,
  "assigned_object_id": null,
  "assigned_object": null,
```

nbshell:
```
>>> ip.assigned_object_type
<ContentType: dcim | interface>
>>> ip.assigned_object_id
>>> ip.assigned_object
```

**Comment by snaselj** [comment]
Thanks @ubajze , you are right, we have DB inconsistencies, I can see it directly using:
```
nautobot=> SELECT id, assigned_object_id, assigned_object_type_id FROM ipam_ipaddress WHERE assigned_object_id IS NULL and assigned_object_type_id IS NOT NULL;

                  id                  | assigned_object_id | assigned_object_type_id
--------------------------------------+--------------------+-------------------------
 9f9565b3-2b03-574b-b920-8c99d7c3f9b4 |                    |                      37
 bce4b481-9c7c-5df4-9212-023a76d747f2 |                    |                      37
 d4913b0e-29cc-5b3c-99b8-e1269e1e0fc9 |                    |                      37
...
```

I think issue can be closed now.

**Comment by ubajze** [comment]
@snaselj Do you have any idea how did you get to this state?

**Comment by bryanculver** [comment]
#1592 didn’t include any migration to clean up old data that may have not met what was necessary for the updated clean method.

Before that it was probably very likely that API changes (or at the very least ORM changes) could have created an invalid state.

While I won’t recommend frequent migrations of data it might be worth looking into edge case error handling.

**Comment by snaselj** [comment]
@ubajze 
After some digging we found that DB inconsistencies was created during our migration from Netbox to Nautobot.

This issue can be closed now, thanks for support :+1:

**Comment by david-kn** [comment]
Closing as resolved. Found the root case and a way how to fix it. 
Thanks for the support :-)
