### ISSUE TITLE
Investigate Warning "MySQL may not allow unique CharFields to have a max_length > 255"

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#1695]
### Proposed Changes

Investigate system check message for MySQL:
```
extras.Job.slug: (mysql.W003) MySQL may not allow unique CharFields to have a max_length > 255.
[22](https://github.com/nautobot/nautobot/runs/6119082771?check_suite_focus=true#step:7:22)
	HINT: See: https://docs.djangoproject.com/en/3.2/ref/databases/#mysql-character-fields
```

### Justification

Could result in unique job slug collisions.

**Comment by jathanism** [comment]
It's because `nautobot.extras.constants.JOB_MAX_SLUG_LENGTH` is `320`.

We'll need to adjust the max lengths for the the 4-tuple of `(source, GitRepository.name, module_name, job_class_name)` to add up to 255: 

https://github.com/nautobot/nautobot/blob/7ebe64d5bd0fbc36557c2dfb962751eee1700ad0/nautobot/extras/constants.py#L34-L38

**Comment by bryanculver** [comment]
I believe one thing @glennmatthews and I had discovered was around the "may not" portion of the warning.

Related here: https://dev.mysql.com/doc/refman/8.0/en/create-index.html#create-index-column-prefixes

It seems heavily engine backend dependent. Our thoughts were around evaluating the impact to the loss of characters and documenting it appropriately.

**Comment by gsnider2195** [comment]
Document the specific MySQL configuration where this could be encountered.  Maybe disable this warning completely?

**Comment by bryanculver** [comment]
@nautobot/core If we ditch slugs (#2611) will this warning go away?

**Comment by glennmatthews** [comment]
Sure, this warning is specific to a `slug` field so if we get rid of slugs (or rework the slug here to a max length of < 255 characters) then it will go away.
