### ISSUE TITLE
GraphQL: Filter devices by status

### ISSUE THREAD

**Issue by sirtux** [nautobot/nautobot#170]
### Environment
* Python version: 3.8.5
* Nautobot version: v1.0.0b2

### Steps to Reproduce
Run the following GraphQL-Query:
`{
  devices(status: "Active") {
    name
    status {
      name
    }
  }
}`

### Expected Behavior
I get a result set containing only the device with status "Active" or nothing because "Active" might be a nonexisting status.

### Observed Behavior
I get a result set containing all devices

**Comment by dgarros** [comment]
This issue is similar to #58, it's a known issue we need to fix

Also it would work as expected if you change "active" to "Active" (slug vs Name)

**Comment by sirtux** [comment]
Yes, that seems to be the same issue, after some analysis it seems to "fail open" if a filter value is not existing.
I tried that just with a tag: If I search for a tag "foo", and it's not existing -> All devices are returned. If that tag exists, but is not assigned to any device-> empty result.

Seems to be a very easy to make error on the user side and a very unexpected behaviour.

**Comment by jathanism** [comment]
Thanks for the report @sirtux and I tend to agree that this is unexpected behavior. I'd rather filters fail closed and not open, and we also need to try to make the filtering on field values a little more intuitive if we can.

**Comment by glennmatthews** [comment]
Fixed by #209.
