### ISSUE TITLE
Exclusion/negate filter on API

### ISSUE THREAD

**Issue by david-kn** [nautobot/nautobot#1718]
### As ...

Austin - Network Automation Engineer

### I want ...

To support exclusion (negation) filtering on the API, e.g.: `/?status!=1`

- Candidate to this epic? https://github.com/nautobot/nautobot/issues/1615
- This is a nice and very useful pre-work for a potential UI component already requested (https://github.com/nautobot/nautobot/issues/1711)

btw. Found an issue/PR for Netbox here (already solved and implemented): https://github.com/netbox-community/netbox/issues/3482

### So that ...

Actually anyone (not necessarily an automation engineer) can easily filter through data. Teams around me (e.g. finance, DCM or managers) could use this for various cases such summaries & reports. 

### I know this is done when...

- REST API query containing exclude symbol is correctly interpreted and data is returned.
- Query `https://demo.nautobot.com/dcim/devices/?region=europe&region!=netherlands` returns all Europe devices except those in the Netherlands.

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by glennmatthews** [comment]
Happy to tell you that the REST API already supports this! Try https://demo.nautobot.com/dcim/devices/?region=europe&region__n=netherlands :-)

**Comment by glennmatthews** [comment]
See also https://nautobot.readthedocs.io/en/stable/rest-api/filtering/#string-fields

**Comment by david-kn** [comment]
Ha - thanks for the link. My bad and sorry :-) 

Somehow I missed this and tried only those, for me, more common ways of negation with `~ `and `!` symbols.
