### ISSUE TITLE
MAX_PAGE_SIZE is been ignored in UI

### ISSUE THREAD

**Issue by divedo** [nautobot/nautobot#1739]
### Environment
* Python version: 3.10.4
* Nautobot version: 1.3.3

### Steps to Reproduce
1. Set MAX_PAGE_SIZE to 1000 (Can be via config file o admin view)
2. Go to devices (or other view with more than 1000 entries)
3. Change URL adding at the end: *?per_page=2500*

### Expected Behavior
An error or message that this request is not allowed.

### Observed Behavior
Backend is ignoring limit and processing request.
The API enforces MAX_PAGE_SIZE but it doesn’t look like the *get_paginate_count* function used for the UI does.

**Comment by bryanculver** [comment]
Thanks for the report @divedo!
