### ISSUE TITLE
Virtual Chassis list view filtering duplicates

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#1749]
### Environment
* Python version: 3.9
* Nautobot version: 1.3.2

### Steps to Reproduce
1. Create 1 virtual chassis with 2 members
2. Navigate to the VC list view (note 1 entry)
3. Search for the 1 VC record using the `q` filter

### Expected Behavior
The resultset to contain one entry (the one VC that was created)

### Observed Behavior
Two, duplicate entries are observed because of the presence of two members in the VC. This is a consequence of the fields that are searched and the lack of a `distinct()` clause on the queryset.

**Comment by timizuoebideri1** [comment]
Closing as unreproducible
