### ISSUE TITLE
Paginated list views not displaying correctly for "select all"

### ISSUE THREAD

**Issue by abates** [nautobot/nautobot#1755]
### Environment
* Python version: all
* Nautobot version: at least 1.3.2 and 1.3.3

### Steps to Reproduce
1. Go to any list view that implements paging (devices for example)
2. Click the top left checkbox in the table to select all
3. Observe the table moves outside the original <div>

### Expected Behavior
The list of objects should remain in place and not move.

### Observed Behavior
The list of objects moves after the original enclosing div

**Comment by glennmatthews** [comment]
![image](https://user-images.githubusercontent.com/5603551/166959504-ee036933-c694-4078-9386-35ef02647e2c.png)

**Comment by abates** [comment]
Possibly related to line 14 in forms.js:

https://github.com/nautobot/nautobot/blob/3018f68c8e23a79ce61f01913d630b61a06c8956/nautobot/project-static/js/forms.js#L8-L18

Commenting out that line seems to prevent the problem from happening
