### ISSUE TITLE
Saved Views

### ISSUE THREAD

**Issue by jakubkrysl** [nautobot/nautobot#1758]
### As ...

Nelly - Network Engineer

### I want ...

to be able to save multiple list view configurations

### So that ...

I can quickly switch between multiple workflows, where each workflow requires different columns in list view.

### I know this is done when...

- I can save several configuration of columns in list view
- I can name them for easier orientation
- I can quickly load any saved configuration from list view

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

None, it could be done with current implementation of user config
But some if cleaner solution would be implemented

**Comment by lampwins** [comment]
#3774

**Comment by lampwins** [comment]
AC:

- On any list view, a user can manipulate the view as they can today (applying filters, table column config, pagination, etc)
- User then have the ability to save (or update an existing) view that tracks all of the above
- Users give the view a name and select whether the view should be shared with other users
- On the list view, the user can quickly see the current active list view and change the saved view to another which is available

**Comment by HanlinMiao** [comment]
The owner and the view name should be unique together.
Save the table config, pagination, and filter params (sort order).
Url query parameters should be something similar to <user>:<view_name>.

**Comment by HanlinMiao** [comment]
- Implement the feature in the `user` app.
- Combine the filter and the table config modals (filter is on the left side and table config on the right; apply (no save one-off), save (updating an existing saved view), save as (creating a new saved view), and clear buttons)
- Navigation links should be grouped under the `user` dropdown
- ListView that the saved view is applied to has to be a model CharField.
- Save the user's default view (uniqueness constraint user -> list view)
- Save Views button should trigger a modal to save the current view
- Toggle between saved views should be a dropdown
- Something like this #4784 for the Table config form
- Table config should be a JSONArray field and the pagination field should be an integer field (max_page_size should win out if the pagination field stores a value larger than max_page_size)
