### ISSUE TITLE
Missing menu 'General / Installed Plugins' in navbar if HIDE RESTRICTED UI is activated

### ISSUE THREAD

**Issue by divedo** [nautobot/nautobot#1769]
### Environment
* Python version: 3.10
* Nautobot version: 1.3.3

### Steps to Reproduce
1. Activate _HIDE RESTRICTED UI_ (via web UI or config file)
2. Go to _Plugins_ menu in nav bar
3. _General / Installed Plugins_ is missing.

### Expected Behavior
Installed Plugins menu should be displayed to all users, with proper permissions.

### Observed Behavior
Menu is not been displayed to any user, (even superusers) if you activate _HIDE RESTRICTED UI_ option.
Instead of that, you can access this view pointing directly to urI: https://<YOUR_NAUTOBOT_URL>/plugins/installed-plugins/

**Comment by bryanculver** [comment]
Need to decide if the behavior should be to still hide the UI but allow superusers to see the list even with HIDE RESTRICTED UI enabled.

**Comment by bryanculver** [comment]
- Change so that all users (except for is_staff, superuser) cannot access the installed plugins page, nor see the menu item (regardless of HIDE RESTRICTED UI state)
- Fix so that HIDE RESTRICTED UI doesn't hide the menu item for users who do have access to it
