### ISSUE TITLE
Update Docs to Include "Added in", "Changed in", "Removed in" for Features

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#1778]
### Proposed Changes
Like https://github.com/nautobot/nautobot/pull/1745, but everywhere.

### Justification

More likely to go do RTD docs which may not be the same version as installed for a lot of users and may not be obvious to load the right docs version in footer.

**Comment by glennmatthews** [comment]
Substantially addressed in #2400. May be closeable?

**Comment by bryanculver** [comment]
Closed via #2400. We've been using a pretty nifty plugin from a pretty nifty maintainer. ;)
