### ISSUE TITLE
'HTTP_PROXIES' not working for Git repository sync

### ISSUE THREAD

**Issue by TheRealBecks** [nautobot/nautobot#1796]
### Environment
* Python version: 3.8.10
* Nautobot version: 1.3.4
* OS: Ubuntu 20.04
* 'HTTP_PROXIES' for usage of proxy server configured

### Steps to Reproduce
Follow the standard installation process for an Ubuntu 20.04 server:
1. https://nautobot.readthedocs.io/en/stable/installation/ubuntu/
2. https://nautobot.readthedocs.io/en/stable/installation/nautobot/
3. https://nautobot.readthedocs.io/en/stable/installation/services/
4. https://nautobot.readthedocs.io/en/stable/installation/http-server/
5. Open the browser and check that Nautobot is working --> Yes, works!
6. Install the 'nautobot-welcome-wizard' --> Has been loaded
7. Click 'Plugins' --> 'Welcome Wizard' --> Action 'Import' for 'Device Types' --> Site loaded correctly, but after refreshing the 'Import Device Types' table is still empty
8. Click 'Extensibility' --> 'Git Repositories' --> 'Devicetype-library' --> 'Synchronization Status'
9. After some time I will get the following two (timeout) errors. I did manual line breaks for easier reading:

```
Cmd('git') failed due to: exit code(128)
cmdline: git clone -v https://github.com/netbox-community/devicetype-library.git /opt/nautobot/git/devicetype_library
stderr: 'Cloning into '/opt/nautobot/git/devicetype_library'...
fatal: unable to access 'https://github.com/netbox-community/devicetype-library.git/':
Failed to connect to github.com port 443: Connection timed out '
```

```
Error while refreshing Devicetype-library:
Cmd('git') failed due to: exit code(128)
cmdline: git clone -v https://github.com/netbox-community/devicetype-library.git /opt/nautobot/git/devicetype_library
stderr: 'Cloning into '/opt/nautobot/git/devicetype_library'...
fatal: unable to access 'https://github.com/netbox-community/devicetype-library.git/':
Failed to connect to github.com port 443: Connection timed out '
```

### Configuration
I configured my HTTP proxy in the file `nautobot_config.py` as follows, but replaced the real IP addresses:
```
# HTTP proxies Nautobot should use when sending outbound HTTP requests (e.g. for webhooks).
HTTP_PROXIES = {
     'http': 'http://192.0.2.1:3128',
     'https': 'http://192.0.2.1:3128',
}
```

### Expected Behavior
I can see traffic flowing over the proxy server.

### Observed Behavior
I used TCP dump on the proxy server and there we're no packets incoming from the Nautobot server. I also checked with tcpdump on the Nautobot server and can say, that it's sending it's HTTP(S) traffic to the default gateway, so no proxy has been used.

I also checked directly on the Linux console and I can clone repositories from Github. I also saw the traffic on the proxy server. --> Proy configuration in Linux is working

**Comment by glennmatthews** [comment]
Git operations use the `GitPython` library, which is a fairly thin wrapper around Git. You might try logging in to Linux as the `nautobot` user account and doing a `git config --global https.proxy http://192.0.2.1:3128` command and see if that helps?

**Comment by smk4664** [comment]
@glennmatthews beat me to it, but I came to the same conclusion.

**Comment by TheRealBecks** [comment]
Thanks a lot, it's working now! :) Run these commands as user `nautobot`:
```
git config --global http.proxy http://192.0.2.1:3128
git config --global https.proxy http://192.0.2.1:3128
```

It would be good if the git proxy configuration for Nautobot gets documented. That's the current [HTTP_PROXIES](https://nautobot.readthedocs.io/en/latest/configuration/optional-settings/#http_proxies) documentation, but no word about the git commands. Do you think it's a good idea to do that?

**Comment by glennmatthews** [comment]
Absolutely that would be good to add to the documentation. Would you like to make a pull request?

**Comment by TheRealBecks** [comment]
@glennmatthews I created a pull request :smiley:

**Comment by TheRealBecks** [comment]
@glennmatthews Do I need to do anything to get that PR merged? Or will you guys do the job? :)

**Comment by glennmatthews** [comment]
We'll merge it shortly. Thank you! :-)
