### ISSUE TITLE
Unify REMOTE/SOCIAL_AUTH_* settings into central authentication settings

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#18]
Currently `REMOTE/SOCIAL_AUTH_*` settings are spread across the Remote Auth, SSO docs, and smattered also in the Permissions and Optional Settings docs. Let's get them all into one place (IMO: a dedicated security/auth/permissions section in optional settings).

**Comment by jedelman8** [comment]
@jathanism was your plan to add more than this https://nautobot.readthedocs.io/en/latest/configuration/authentication/sso/  ?

Want to see if there is more expected for 1.0.0 here?

**Comment by jathanism** [comment]
> @jathanism was your plan to add more than this https://nautobot.readthedocs.io/en/latest/configuration/authentication/sso/ ?
> 
> Want to see if there is more expected for 1.0.0 here?

Yes. @dgjustice was helping but we kind of hit an impasse with the somewhat split-brained nature of the way they are. Still in the works, tho.

**Comment by jathanism** [comment]
Duplicated by #149
