### ISSUE TITLE
Nautobot Status and other persisted objects should use uuid.uuid5 to generate ids

### ISSUE THREAD

**Issue by retnuh** [nautobot/nautobot#1809]
### Environment
* Python version: N/A
* Nautobot version:  All 1.x

### Steps to Reproduce
1.  Use `nautobot-server dumpdata` to create a fixture
2.  Watch your fixture explode on already existing `Status` objects!

### Expected Behaviour
It would be great if `Status` and other pre-populated objects in Nautobot used `uud.uuid5` to generate the IDs in a deterministic way.  It would be double nice if there were a migration to update existing DBs to the new UUID but maintain existing relationships.

Here's a small example of what `uuid.uuid5` might look like:

```
>>> import uuid
>>> uuid.uuid5(uuid.NAMESPACE_URL, "urn:x-nautobot-uuid:Status:Active")
UUID('aedc8cd9-d0d2-5ad7-8fc3-11615d39402e')
```

Obviously the specifics of the name and namespace used are up to you guys.  I don't think you'd have to go to the trouble of registering a urn namespace or anything, what's important is avoiding clashes with other applications.

The advantage of this would be that dump'd db's for test fixtures would be consistent without having to jump through hoops (for example, we delete the existing pre-populated objects in an override of `setUpClass` in test classes).

cc @jvanderaa @PhillSimonds

**Comment by glennmatthews** [comment]
Thanks for the request!

An alternate approach we've discussed in the past would be to add support for `natural_key` and `get_by_natural_key` to Status and various other classes - with this added we could probably use `dumpdata --natural-foreign --natural-primary` to avoid the UUID issue altogether.
