### ISSUE TITLE
Theme button in footer incorrectly italicized

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot#1815]
### Environment
* Python version: 3.9.6
* Nautobot version: 1.4.0-alpha

### Steps to Reproduce
1. The "Theme" button in the footer is italicized, whereas all other buttons in the footer are not.  This was a mistake on my end from a previously submitted PR (that has already been closed).

### Expected Behavior
The button should not be italicized.

### Observed Behavior
The button is italicized.

**Comment by bryanculver** [comment]
Closed by #1816
