### ISSUE TITLE
Help Button directs to inactive wiki

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot#182]
### Environment
* Python version: 3.8.5
* Nautobot version: 1.0.0.b2

### Steps to Reproduce
1. Scroll to bottom of page
2. Click on the Help link next to the lifebouy

### Expected Behavior
Load page that directs where to get help

### Observed Behavior
Loads root of the Nautobot/Nautobot repo.  

Perhaps this should point to the Discussions page, or perhaps the Wiki could be updated?

**Comment by jathanism** [comment]
How's this? https://github.com/nautobot/nautobot/wiki

**Comment by smk4664** [comment]
Better, maybe add a link to the discussions?

**Comment by jvanderaa** [comment]
Looks like this one is already fixed in develop? @smk4664 @jathanism ?

**Comment by smk4664** [comment]
Sure, since we added a wiki.  Although, I don't think a help button should go to a page that doesn't provide help.

**Comment by jathanism** [comment]
I think having the wiki satisfies this., but let's make a point to get some stuff added to the wiki. :)
