### ISSUE TITLE
Decorate Additional Models for Dynamic Groups Support

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#1822]
_Blocked by: https://github.com/nautobot/nautobot/issues/1483 (mainly #1737)_

**Comment by bryanculver** [comment]
Models of interest:
> * Circuits
> * Interfaces
> * Locations
> * Aggregate / Whatever IPAM considerations based on design changes.

_From @itdependsnetworks via: https://github.com/nautobot/nautobot/issues/3268#issuecomment-1425056844_

**Comment by glennmatthews** [comment]
Done through #5473 and related work.
