### ISSUE TITLE
Show values in changelog UI instead of UUID

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#1830]
### As ...

Isabella - Infrastructure Owner

### I want ...

to be able to easily see the value of field that was changed in changelog instead of UUID

### So that ...

I can easily work with changed values

### I know this is done when...

- changelog UI diff shows values instead of UUID

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [X] Documentation
- [ ] Other (not directly a platform feature)

**Comment by bryanculver** [comment]
@nautobot/core was this resolved with 1.3, 1.4, and https://github.com/nautobot/nautobot/issues/2795?

**Comment by glennmatthews** [comment]
Looks resolved now, I think #2056 was actually what addressed this (#2795/#2861 was a bug fix after #2056).
