### ISSUE TITLE
1.4: Interface API version 1.4 is missing parent_interface and bridge fields

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#1831]
### Environment
* Python version:
* Nautobot version: `next` after #1651

### Steps to Reproduce

Compare output of `/api/dcim/interfaces/` and `/api/dcim/interfaces/?api_version=1.4` - the latter is missing `parent_interface` and `bridge` keys on the interfaces. This appears to have been an oversight due to the interaction between #1651 and #1753.

### Expected Behavior

All supported fields to be present in the newest API serializer.

**Comment by bryanculver** [comment]
Closed via #1834
