### ISSUE TITLE
Provide a way to define and reuse URL data source integrations

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot#1835]
### As ...

Mike - Network Engineer

### I want ...

to have a consistent way to define and use external URL data source integrations with other systems, with some extra data such as secrets, or parameters to customize its behavior. This should be consistent for multiple URL data sources, that could be used for sending or receiving data.
I would like to do this in run time, so I don't need to restart my Nautobot service to add or update an endpoint.

### So that ...

I could have only one consistent way to define URL data sources, that I could use for multiple applications. For instance, for a chatops and a SSoT application, with application XYZ, I would have only one URL endpoint and use it independently.
Also, I would like that these applications would dynamically update the new added URL data sources without Nautobot restart.
In general, as a user, I would like to have a consistent experience with data sources, and specially with all the URL based ones, that share mostly the same pattern: name to identify, URL, secrets, timeout

### I know this is done when...

- When I can  configure external data sources (defined with an URL) that provide integration with Secrets and other attributes to define the integration, without restarting Nautobot.
- When from Nautobot Jobs or Plugins, can take the available data sources and reuse them as targets.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [x] Misc (including Data Sources)
- [ ] Organization
- [x] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- Depends on the implementation, maybe a new model or simple configuration extension

**Comment by chadell** [comment]
This feature could help to implement other open issues:
https://github.com/nautobot/nautobot-plugin-chatops/issues/122
https://github.com/nautobot/nautobot-plugin-ssot-ipfabric/issues/88

**Comment by smk4664** [comment]
In discussing this with some core maintainers, this would be good to initially start as a plugin. I will work on getting this into a repo.

**Comment by bryanculver** [comment]
Related? https://github.com/nautobot/nautobot/issues/3111 #4171

**Comment by chadell** [comment]
> Related? #3111 #4171

Yes, I think that `controllers` is a good implementation

**Comment by glennmatthews** [comment]
@chadell Is there more needed here or do the `Controller` and `ExternalIntegration` models fully address this use case?

**Comment by chadell** [comment]
yes, thanks
