### ISSUE TITLE
Default value of a Custom Field applied by default as a filter criteria on Devices view

### ISSUE THREAD

**Issue by HadriCarrera** [nautobot/nautobot#1836]
### Environment
* Python version: 3.10
* Nautobot version: 1.3.4

### Steps to Reproduce
1. Create custom field, and set a default value.
2. Go to Devices view and a filter criteria with the default value is checked, not applied in the current list of devices.
3. Set another filter and search.
4. The new list has your filter criteria applied and the default value of the custom field created before that can not be unchecked.

### Expected Behavior
The default value of a custom field should not be applied as a filter criteria on devices view.

### Observed Behavior
If you create a custom field and set a default value, this value is checked by default as well in the devices view as a filter criteria.
The first time you enter on devices view, it's not applied (all devices are shown) but if you set another filter criteria then it's applied. And can not be unchecked.
For example if you create a boolean field, True as default, now all your searches will be True as default, or False if you change it. If you try to remove this filter, will be True again on the next iteration.

**Comment by Manawyrm** [comment]
Yup, and this is a regression that was recently introduced. This used to work correctly in the past.

**Comment by glennmatthews** [comment]
Thanks for the report!
