### ISSUE TITLE
Last run and Last status fields aren't updating to most recently ran job.

### ISSUE THREAD

**Issue by Copter64** [nautobot/nautobot#1838]
### Environment
* Python version: 3.8.10
* Nautobot version: 1.3.5
* GC Plugin - 1.0.2
* Nautbot Plugin for Nornir - 1.0.0
* NB SSoT - 1.1.2

### Steps to Reproduce
1. After updating to 1.3.4 and still in 1.3.5 the Last ran statues in the /extra/jobs page are not showing the most recent job.

### Expected Behavior
Show the latest job that ran after completetion

### Observed Behavior
It looks to be displaying an older job that ran before, possibly the first job.

**Comment by mamullen13316** [comment]
I was hitting the same issue and searched issues here to see if it was known.  Check line 295 in `jobs.py`,  this works better for me:  `self._latest_result = self.results.latest()`.   There may be an underlying problem in that the first() and last() methods seem to be reversed,  or maybe that is expected? 
```
>>> j.results.latest().completed
datetime.datetime(2022, 6, 3, 12, 52, 26, 734830, tzinfo=<UTC>)
>>> j.results.first().completed
datetime.datetime(2022, 6, 3, 12, 52, 26, 734830, tzinfo=<UTC>)
>>> j.results.last().completed
datetime.datetime(2022, 6, 2, 22, 56, 23, 31883, tzinfo=<UTC>)
```

**Comment by Copter64** [comment]
> I was hitting the same issue and searched issues here to see if it was known. Check line 295 in `nautobot/extras/jobs.py`, this works better for me: `self._latest_result = self.results.latest()`. There may be an underlying problem in that the first() and last() methods seem to be reversed, or maybe that is expected?
> 
> ```
> >>> j.results.latest().completed
> datetime.datetime(2022, 6, 3, 12, 52, 26, 734830, tzinfo=<UTC>)
> >>> j.results.first().completed
> datetime.datetime(2022, 6, 3, 12, 52, 26, 734830, tzinfo=<UTC>)
> >>> j.results.last().completed
> datetime.datetime(2022, 6, 2, 22, 56, 23, 31883, tzinfo=<UTC>)
> ```

Interesting, so the "first" is actually showing the latest?  Almost like they are taking the most recent as the first entry into the DB.
