### ISSUE TITLE
Staff users with group permissions unable to view groups in admin UI

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#1839]
### Environment
* Python version: 3.7.13
* Nautobot version: v1.3.5

### Steps to Reproduce
1. Create a user with `is_staff` and `auth.view_group` permissions
2. Login with this user
3. Navigate to the Admin UI

### Expected Behavior

User can see link to `Users > Groups`

### Observed Behavior

User cannot see link to `Users > Groups` and `/admin/users/admingroup/` shows Access Denied

**Comment by jathanism** [comment]
This appears to be a bug in `ObjectPermissionsBackend` perhaps related to `ObjectPermissionsBackend.has_module_permussions()` (which is inherited from the base)  and module-level permission checks are failing in most cases. Need to track down why.

Most importantly, The Django admin scans app_labels to determine "module perms". Django stock auth backend `get_all_permissions` returns a `set` whereas our implementation returns a `dict`, but not quite sure if that's exactly right just yet.

Likely overloading `ObjectPermissionsBackend.has_module_permussions()` with something that works for the custom object-permissions backend is the right path.
