### ISSUE TITLE
Add Markdown enabled Comment-Field in Config Context

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#1847]
### As ...

Austin - Network Automation Engineer

### I want ...

to have a Markdown enabled comment-field to *Config Context* describe the Variables available for commands.

E.g.:

For the following Context the comment-field would be something like this:

**Available variables for commands:**

- **INTERFACE** - Full interface name e.g. "GigabitEthernet1/0/15"
- **INTERFACE_NAME** - Name part of the interface e.g. "GigabitEthernet"
- **INTERFACE_NUMBER** - Only the interface number e.g. "1/0/15"

```
{
    "livedata_plugin_commands": {
        "SAVE_CONFIG_COMMAND": "write memory",
        "SHOW_DEV_TRACK_INTF": "show device-tracking database interface {INTERFACE}",
        "SHOW_INTF": "show interface {INTERFACE}",
        "SHOW_INTF_STATS": "show interface {INTERFACE} stats",
        "SHOW_INTF_STATUS": "show interface {INTERFACE} status",
        "SHOW_LOG_INTF": "show logging | i {INTERFACE_NUMBER}",
        "SHOW_MAC_ADDR_INTF": "show mac address-table interface {INTERFACE}",
        "SHOW_RUN_COMMAND": "show running-config",
        "SHOW_RUN_INTF": "show running-config interface {INTERFACE}"
    }
}
```

### So that ...

It is documented in place and I must not lookup in other document

### I know this is done when...

I define Config Contexts

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- Yes:  Add Comment-field to Config Context (Markdown enabled)

### External Dependencies

None

**Comment by glennmatthews** [comment]
The ConfigContext model supports the `Notes` feature:

![image](https://github.com/user-attachments/assets/c14f97bc-4b7d-42b2-a90e-6b9e531dc0b8)
