### ISSUE TITLE
Possible infinite loop in cable tracing algorithm

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#185]
### Environment
* Python version: 3.7
* Nautobot version: develop @ d604c7595713cc21ac6c3b537896a393f7d887f5

### Steps to Reproduce
1. Create a circuit and add A and Z terminations
2. In the detail view for this circuit, select "Connect -> Circuit Termination" for either termination, and select the other termination of this same circuit as the other end of the cable.
3. The browser spins indefinitely waiting for a response from Nautobot.

![image](https://user-images.githubusercontent.com/5603551/112204859-8b438c00-8bea-11eb-9ace-a2207a4ddf1e.png)

### Expected Behavior

Either constructing such a loop should be forbidden outright (similar to how Nautobot rejects an attempt to cable a device's rear port to its own front port that maps to that rear port) or the loop should be detected and handled gracefully.

### Observed Behavior

The cable never gets constructed, but no error message is reported either.

**Comment by dgjustice** [comment]
It looks like `node` can be assigned back to itself, and there is no visited nodes structure, hence the loop will never terminate.  I'm going to write some tests to break this, then work back from that.  https://github.com/nautobot/nautobot/blob/dbb34c07166fd8bc044fd971daab6e06d74f3a9f/nautobot/dcim/models/cables.py#L414
