### ISSUE TITLE
UI - Unable to scroll through top-level menu in low resolution desktop screens

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot#1851]
### Environment
* Python version: unknown
* Nautobot version: 1.3.5

### Steps to Reproduce
1. Log in to Nautobot (e.g. demo.nautobot.com)
2. Make your web browser window smaller, both height and width wise (e.g. half window height/width on a laptop screen)
3. Open the hamburger icon for the menu items
 

### Expected Behavior
You should be able to scroll through the menu and see all options and select them.

### Observed Behavior
If the window is short enough height-wise, and you open a menu item with many choices (Like Extensibility), you are unable to see all of the options or scroll through them.

If the window is even shorter height-wise, you are unable to even see all of the menu options.  They appear to go off-screen, and are not rendered properly.

This issue does appear across web browsers (tested across Safari, Firefox, Chrome).
This issue does not appear on mobile platforms (tested on IOS Safari).

**Comment by glennmatthews** [comment]
Example (note that the "Services" menu item is still off the bottom of the window despite scrolling to the end of the menu):

![image](https://user-images.githubusercontent.com/5603551/172472035-4fc9029e-deab-4b1e-b740-25ce20f7bd09.png)

**Comment by gsnider2195** [comment]
Related to #1565
