### ISSUE TITLE
Add ability to schedule Nautobot jobs more frequently

### ISSUE THREAD

**Issue by jtdub** [nautobot/nautobot#1871]
### As ...

Austin - Network Automation Engineer

### I want ...

the ability to schedule Nautobot jobs at a minimum of 15 minute increments.

### So that ...

my plugin has the ability to schedule jobs as frequently as required.

### I know this is done when...

- When I have the ability to schedule jobs at a minimum of 15 minute increments.

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [X] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- unsure

### External Dependencies

- celery
- django-celery-beat

**Comment by glennmatthews** [comment]
See also #1226.

**Comment by bryanculver** [comment]
We will close this in favor of #1226 to any more granular time intervals (we already resolve the selection down to a crontab but exposing this to both the end-user and plugins would be ideal).
