### ISSUE TITLE
Create JobHookReceiver class that takes as input the object change instance via an ObjField

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#1877]
This is intended to be a callable Job that takes in a Object Change model change instance (instead of defined arguments that the existing Job class defines)

### Things to Consider
- Need to enhance the JobModel to store which class the Job inherits from which is not user editable
- Default filter out in Job list view any Job inheriting from JobHookReceiver

**Comment by bryanculver** [comment]
Closed with #2056
