### ISSUE TITLE
Device Cluster/HA Modeling

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#1892]
### As ...

Nelly - Network Engineer

### I want ...

To model various network device clustering and high availability topologies & configuration

### So that ...

I can easily track cluster peers, clustering type, and other high availability constraints for network devices like firewalls and router pairs.

### I know this is done when...

- I can create device clusters depicting Active/Passive with 2 or more nodes
- I can create device clusters depicting Active/Active with 2 or more nodes
- The concept of the cluster is its own model which supports extensibility features like custom fields

### Optional - Feature groups this request pertains to.

- DCIM

### Database Changes

- A new model for clusters (will need to consider naming here with virtualization.cluster)

### External Dependencies

None

### Specific User Stories

> As a user I would like to store/retrieve in Nautobot information to be able to deploy a Palo Alto firewall cluster. I will need to know what devices are in the cluster, the cluster's redundancy strategy, the order of which devices will be used (priority/weight).

> As a user I would like to be able to constrain a cluster type to a specific set of device types.

> As a user I would like to be prevented from changing attributes of the cluster type that would cause the current data to be invalid (example removing support for a particular device type while an existing cluster included one).

### TODO:

- [x] #2275
- To be defined based upon outcome of spike
- Name: RedundancyGroup
- Failover strategy on RedundancyGroup model (ENUM, "Active/Active", "Active/Passive")
- FK relationship from Device to RedundancyGroup
- Device holds priority attribute in RedundancyGroup

**Comment by lampwins** [comment]
Also of note, virtual chassis are meant to model multiple devices that share a common control plane. What I am after here are cases where the control plane is separate, but also cases where an engineer simply wants to designate that Device A is the "primary" and Device B is the "backup" even though the two devices may not even know about each other in the network design.

**Comment by itdependsnetworks** [comment]
I think we need to document where each would be handled, it is quickly getting confusing, at least to this Nautobot enthusiast.  Feel free to add to the list, but just off the top of my head. 

Example | virtual chassis | Device Cluster
-------- | --------------- | --------------
Cisco Stackwise |  <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>
Cisco VSS |  <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>
Nexus VPC |  <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>
Nexus VPC Fex's |  <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>
Palo Alto HA (active/active) |  <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>
Palo Alto HA (active/passive) |  <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>
Palo Alto HA (active/passive) |  <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>
Spine/Leaf pair |  <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>

**Comment by jathanism** [comment]
Are we talking baseline abstraction or are we also thinking of considering actual standby protocols like HSRP, VRRP, GSLB, etc.?  For clarity is this explicitly for chassis-based standby or are we thinking of modeling "high availability" solutions that could be used to define a cluster of devices?

Personally, I would prefer the former, where we are considering an abstraction of the most common types of active/standby/failover patterns. I would like to see `Cluster` become more of a general purpose object here once we do in fact merge `Device` and `VirtualMachine`, especially since we'll be doing so in a backwards-incompatible nature. I would hate to see us sprawl `Cluster` to only be used for `Device(virtual=True)` and some entire other solution for physical hardware.

**Comment by lampwins** [comment]
Thanks @itdependsnetworks I have updated the table to reflect my thinking, but I remain open-minded.

@jathanism I see this as providing baseline abstraction to cover a broad set of HA clustering primitives, but not getting into specific protocols or topologies. I think this will open those doors, but for now, I just want to start by being able to identify clusters of devices participating in some form of high-level HA technology. I also understand your thoughts on the existing virtualization `Cluster` model and this is certainly something we will need to consider during a refactor, but I do feel there is a distinction to be made between a cluster of VM hosts and a cluster of switches/routers/firewalls, in a longer-term vision in which we do support specific protocols. Perhaps some of that comes down to naming, which admittedly, I am bad at.

**Comment by jathanism** [comment]
> I also understand your thoughts on the existing virtualization `Cluster` model and this is certainly something we will need to consider during a refactor, but I do feel there is a distinction to be made between a cluster of VM hosts and a cluster of switches/routers/firewalls, in a longer-term vision in which we do support specific protocols. Perhaps some of that comes down to naming, which admittedly, I am bad at.

Seems to me that if we are thorough we could extend `Cluster` and `ClusterType` relationships to behave similarly to yet distinctly from the [work we're doing currently in prototyping the new `Location` and `LocationType` models](https://github.com/nautobot/nautobot/pull/1891).

Just to spitball for the sake of illustration (borrowing a bit from @itdependsnetworks table):

- Virtual "machine" devices can be in a `Cluster` that are of `ClusterType("Availability Zone")`
- Physical devices (like Cisco Nexus 9000s) could be in a `Cluster` of `ClusterType("Nexus VPC" )`
- Physical devices like top-of-rack or spine/leaf switches could be in a `ClusterType("VRRP" )`
- Similarly how the prototype for `Location/LocationType` does this with `ContentType` associations, perhaps `ClusterType` could define `DeviceType`s that can be associated with Clusters of this type (e.g. `DeviceType("Cisco Nexus")` can only be associated with `ClusterType("Nexus VPC" )`, etc.

**Comment by mzbroch** [comment]
@jathanism Aren't we just discussing "Static Groups" now ? What is going to make a Cluster object different than a pure group of devices (objects) ?

**Comment by lampwins** [comment]
@erjac77 not currently, but that will be a natural next step for us.

**Comment by bryanculver** [comment]
@lampwins We could use some help with additional requirements here.

Do we need to supply a weight to the cluster membership? Is the Active/Passive definition an attribute of the Cluster itself?

**Comment by jathanism** [comment]
> @jathanism Aren't we discussing "Static Groups" now ? What is going to make a Cluster object different than a pure group of devices (objects) ?

I mean we could use dynamic groups to define clusters, could we not?

**Comment by mzbroch** [comment]
> > @jathanism Aren't we discussing "Static Groups" now ? What is going to make a Cluster object different than a pure group of devices (objects) ?
> 
> By that logic we could use dynamic groups to define clusters, could we not? I don't think that is what is desired here.

To me, a cluster model itself could be represented as a generic `StaticGroup`, having its own `StaticGroupType` and `StaticGroupMember` assigned statically.

With that being said:
- a `StaticGroup` object itself should have its own attributes with the attribute schema defined in `StaticGroupType`
- a `StaticGroup` should be a type of `StaticGroupType`, where the `ContentType` and an attribute schema is defined (ie. `StaticGroupType` instance for `Firewall-HA` will enforce different set of attributes than group `Switch-Stack` instance)
- each `StaticGroupMember` (`dcim.Device`) might have a specific attributes that are defined per member (ie. priority, weight, role etc.)

**Comment by whitej6** [comment]
Adding to the list is Aireos WLC Failover. A/A & A/S should follow similar patterns to other network devices but WLCs have AP failover without clustering.

In a past life I managed 21 WLCs at a single site with thousands of APs. Each quadrant of the site had 4-6 WLC. The WLCs were not configured in Active/Active or Active/Standby, they however had primary secondary and tertiary set for the AP configuration.

**Comment by bryanculver** [comment]
@mzbroch @whitej6 Can we get more end-user specific stories?

(I may have this wrong @whitej6, as I have never configured AireOS devices, so please reply with a concrete example)
> As Nelly the Network Engineer I would like to deploy AireOS Wireless LAN Controllers (WLC) and APs. My WLCs can be configured to have sets of APs in either a primary, secondary, or tertiary role. WLCs do not have any specific failover strategy defined, as they are determined by the roles of the particular APs. etc...

**Comment by lampwins** [comment]
> Do we need to supply a weight to the cluster membership? Is the Active/Passive definition an attribute of the Cluster itself?

Yes to both.

As for the WLC use case, I would think you can model that as an Active/Active cluster with weight. Otherwise, this feature set might not be appropriate. It is important we do not boil the ocean here and in an effort to deliver agile software, we must draw some lines. We can look at enhancements later with targeted feedback.

**Comment by pke11y** [comment]
Use Case: OS upgrades

It would be really useful to be able to identify HA peers using the source of truth, when upgrading a network device.

For example:

- Spine: If the target device being upgraded is a spine device in a leaf and spine architecture - it would be good to know the list of other peer spine devices in the cluster to ensure theses peers are **active** and available to route traffic, before the target device will be upgraded and taken offline.
- MC-LAG: If the target device being upgraded is part of a MC-LAG group, it would be good to know other MC-LAG peers to ensure the status of the other peers is **active**, before the target device will be upgraded and taken offline.
