### ISSUE TITLE
Failed to build image

### ISSUE THREAD

**Issue by FloLaco** [nautobot/nautobot#1897]
### Environment
* Python version: 3.6.12
* Nautobot version: 1.3.5

### Steps to Reproduce
1. run `invoke build`

### Observed Behavior
```
Step 39/46 : FROM dependencies-dev-platform-$TARGETARCH as dependencies-dev
Service 'nautobot' failed to build: invalid reference format
```

I've never seen variable in reference, is it normal ?
If yes, where this variable is defined

**Comment by glennmatthews** [comment]
I believe this issue is seen if you're running docker-compose v1. The development environment requires docker-compose v2. We probably need to document this more explicitly.

**Comment by FloLaco** [comment]
You're right : 
```
(nautobot-dev2) florian@dsrauto-dev1:~/nautobot-carrefour-2$ docker-compose --version
docker-compose version 1.24.1, build 4667896b
```

**Comment by lampwins** [comment]
Is this still needed in 2024?

**Comment by glennmatthews** [comment]
If we implement #2207, I think this probably can be closed.

**Comment by lampwins** [comment]
Closing in favor of #2207
