### ISSUE TITLE
CustomField default value populated in filterform

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot#1903]
### Environment
* Python version: 3.8
* Nautobot version: 1.3.2

### Steps to Reproduce
1. Create CustomField with a default value (quick testing with site object)
2. Load target object's list/table view
3. FilterForm on right side is pre-populated with default value and not set to an empty value.

### Expected Behavior
Filterforms should not be pre-populated on initial load when query params are not passed in

### Observed Behavior
Default value is pre-populated but not applied as a filter to the page.

**Comment by glennmatthews** [comment]
I believe this is the same issue as #1836?

**Comment by whitej6** [comment]
That is correct. Linked PR should fix both
