### ISSUE TITLE
GraphiQL - Buttons are not displayed when browser window is too narrow

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#1942]
### Environment
* Python version: 3.9
* Nautobot version: nautobot-f48c46cf9-5bw74 (v1.3.5)

### Steps to Reproduce
1. Open GraphiQL page
2. Zoom in until the search field in the main menu do not fit in 1st line
3.

### Expected Behavior

Buttons stay visible

### Observed Behavior

Buttons are not displayed

Zoom 67%:
![image](https://user-images.githubusercontent.com/8406301/175205553-4989d1e6-fee2-4dea-a4a9-137e33733ec3.png)

Zoom 75%:
![image](https://user-images.githubusercontent.com/8406301/175205673-5755b84f-0f51-415e-a100-b098dbe8a05d.png)

**Comment by HanlinMiao** [comment]
This issue is fixed in Nautobot v1.4.1, closed by #2186.
