### ISSUE TITLE
Transaction TestCase does not have the helper functions found in TestCase

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot#1949]
### Environment
* Python version: 3.8
* Nautobot version: 1.3.4

### Steps to Reproduce
1. Create a test that uses TransactionTestCase
2. Try to call self.add_permissions("dcim.add_manufacturer") in that test.

### Expected Behavior
The Test will add the permission that was requested to be used during testing.

### Observed Behavior
TransactionTestCase does not contain the method `add_permissions`.

**Comment by bryanculver** [comment]
Closed in #1954
