### ISSUE TITLE
Add default preference for all users for table columns

### ISSUE THREAD

**Issue by dnewood** [nautobot/nautobot#1970]
### As ...

Patti - Platform Admin

### I want ...

To be able to set a default table configuration for all users. 

![Screen Shot 2022-06-28 at 10 02 52 AM](https://user-images.githubusercontent.com/67761754/176198486-f5e178fe-846e-4c16-9e60-ce11136cbea8.png)

### So that ...

Nautobot admins have the ability to set a default table view for all users by default. For example, if an admin determines that the Utilization column within `/prefixes` should not be display by default.

### I know this is done when...

- When a Nautobot admin has the ability to set a default table preference for all users from the admin panel or possibly a configuration option in `nautobot_config.py`

![Screen Shot 2022-06-28 at 10 38 07 AM](https://user-images.githubusercontent.com/67761754/176207026-0360b496-bbbc-4ec4-b64b-1a7328980b90.png)

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [X] Circuits
- [X] DCIM
- [X] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

would not require changes

### External Dependencies

No external dependencies required

**Comment by glennmatthews** [comment]
Doable now with saved views, #3774 etc.
