### ISSUE TITLE
Spike: Evaluate Strategy for graphene-django Dead Project Notice

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#1973]
### Proposed Changes
- [Strawberry](https://github.com/strawberry-graphql/strawberry)?
    - [strawberry-graphql-django](https://github.com/strawberry-graphql/strawberry-graphql-django)
- [graph_wrap](https://github.com/PaulGilmartin/graph_wrap)?
    - Need to discuss with maintainer as it has a dependency on graphene-django
    - Previous spike: https://github.com/nautobot/nautobot/issues/784
- Contribute/fork/vendor?

### Justification
- https://github.com/graphql-python/graphene-django/issues/1324

### Things to Consider
- Alignment with REST API
- Maintainability
- Plugin, integrator ecosystem impact (forcing plugin maintainers to define GraphQL schemas instead of getting it for free)
- Performance (we've pulled in optimizer, but will we regress going to say Strawberry)

### Outcome

- A table summarizing the choices & considerations above (like: https://github.com/nautobot/nautobot/issues/510#issuecomment-1147654215)
- A housekeeping ticket is opened that describes the plan to proceed

**Comment by lampwins** [comment]
@glennmatthews do we need this issue?

**Comment by glennmatthews** [comment]
graphene-django eems to still be alive (last release 12/20/23, last commit 3 days ago as of this writing) so I think we can close this for now.
