### ISSUE TITLE
Spike: Investigate Upgrade `django-taggit` to v3+

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#1983]
### Proposed Changes

Upgrade `django-taggit` to `~3.0.0`, however v2 has been observed to have breaking API changes: https://github.com/nautobot/nautobot/blob/develop/pyproject.toml#L76-L77

### Considerations

- What changes come in with v3+, and if those API changes impact plugins
- Can we adapt breaking changes to be minimal/non-impacting to core, plugins

### Outcome

- A housekeeping ticket is opened that describes the plan to proceed

**Comment by glennmatthews** [comment]
The only "breaking" change in django-taggit v3 is a change to default slug generation for newly created non-ASCII (Unicode) tags, which should be harmless for us.

The v2 API change (from `object.tags.set("Tag 1", "Tag 2")` to `object.tags.set(["Tag 1", "Tag 2"])` is pretty trivial to account for in core (I only found four instances of `tags.set()` to update), but it would be a breaking change to any plugins that are doing a `tags.set()` call (though based on a quick code search, this *looks* pretty uncommon; plugins are much more commonly doing `tags.add()` or `tags.remove()`, the APIs for which have not changed).

**Comment by glennmatthews** [comment]
Implemented in `next` for 1.5.
