### ISSUE TITLE
Jobs sometimes fail with `Can't decode message body: DecodeError(InterfaceError('connection already closed'))`

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot#1985]
### Environment
* Python version: 3.8.13
* Nautobot version: 1.3.3

### Steps to Reproduce

Unfortunately I don't have clear reproducable steps to follow to replicate this behavior on a clean environment. The following is the scenario:

There are two virtual machines each running Docker where 8 workers and 2 nautobot containers are running. The postgres database is running externally of this stack. The scheduler container runs on the first of the two virtual machines (because otherwise scheduled jobs are run twice). There is a (somewhat long-running, up to 30 minutes) job scheduled to run at 1am each night. The scheduler container shows the following logs each night:

```
[2022-06-29 01:00:00,001: INFO/MainProcess] Scheduler: Sending due task ${redacted}: daily_20557cab-df5a-4e30-a3cb-0591e7c56f68 (nautobot.extras.jobs.scheduled_job_handler)
[2022-06-30 01:00:00,000: INFO/MainProcess] Scheduler: Sending due task ${redacted}: daily_20557cab-df5a-4e30-a3cb-0591e7c56f68 (nautobot.extras.jobs.scheduled_job_handler)
```

The logs for the workers that pick up these jobs can be found here: https://gist.github.com/Kircheneer/726c285479f90d09a3dff48cac843763

### Expected Behavior

The job runs normally and terminates as if ran manually.

### Observed Behavior

The job doesn't run. Either the `JobResult` doesn't show up at all in the GUI table or it still shows as pending the next morning.

**Comment by Kircheneer** [comment]
Now we are running into issues where normal jobs fail with the same error, so this appears to not be connected to scheduling of jobs. Here is an example worker output for a non-scheduled failing job. Note that the error message is the same (`Can't decode message body: DecodeError(InterfaceError('connection already closed'))`):

```
[2022-07-01 10:59:21,393: CRITICAL/MainProcess] Can't decode message body: DecodeError(InterfaceError('connection already closed')) [type:'application/x-nautobot-json' encoding:'utf-8' headers:{'lang': 'py', 'task': 'nautobot.extras.jobs.run_job', 'id': 'd6045105-389b-4ad9-bd04-a6a49fda5d97', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [300.0, 150.0], 'root_id': 'd6045105-389b-4ad9-bd04-a6a49fda5d97', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': "{'data': {'site': ['7fa931cd-cc74-48e3-8d73-1ecacbded6e1'], 'region': [], 'tenant_group': [], 'status': [], 'access_class': []}, 'request': <nautobot.utilities.utils.NautobotFakeRequest object at 0x7d03172e9a30>, 'commit': True, 'job_result_pk': UUID('0ed517c7-ecbc-4dd0-820e-65294dd41916')}", 'origin': 'gen119@76629778e13d', 'ignore_result': False, 'elasticapm': {'trace_parent_string': '00-6d2085b97f70af305bf7a53abd1abdde-f8c6a59f72290b4d-01'}}]
body: b'[[], {"data": {"site": ["7fa931cd-cc74-48e3-8d73-1ecacbded6e1"], "region": [], "tenant_group": [], "status": [], "access_class": []}, "request": {"__nautobot_type__": "nautobot.utilities.utils.NautobotFakeRequest", "META": {"CONTENT_LENGTH": "128", "CONTENT_TYPE": "application/json", "HTTP_ACCEPT": "*/*", "HTTP_ACCEPT_ENCODING": "gzip, deflate", "HTTP_HOST": "${redacted}", "HTTP_USER_AGENT": "python-requests/2.27.1", "QUERY_STRING": "", "REMOTE_ADDR": "{redacted}", "REQUEST_METHOD": "POST", "SERVER_NAME": "76629778e13d", "SERVER_PORT": "8080"}, "POST": {}, "GET": {}, "user": "54aa3f34-b593-414c-9728-be28ed2295fe", "path": "{redacted}"", "id": "0e40ab71-9d37-47a8-84c3-878462142bc3"}, "commit": true, "job_result_pk": "0ed517c7-ecbc-4dd0-820e-65294dd41916"}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (912b)
```

**Comment by Kircheneer** [comment]
I have two matters here:
- What can I do to resolve the immediate issue?
- Can we improve the UX in this case so that this error shows up in the jobs logs rather than the jobs getting stuck in the pending status?

**Comment by glennmatthews** [comment]
Noting elasticapm in the stack trace - possibly relevant? https://github.com/elastic/apm-agent-python/issues/1559

**Comment by bryanculver** [comment]
@Kircheneer Can you provide a sanitized copy of your config along with the setup of your databases (single instance, HA via ...)?

**Comment by gsnider2195** [comment]
Are you able to find out which worker(s) these jobs are failing on to see if there's a pattern?

**Comment by Kircheneer** [comment]
@bryanculver here is the configuration: https://gist.github.com/Kircheneer/27da3d9c8878a1836a543cbfff62af45

The database backend is this as HA configuration: https://severalnines.com/clustercontrol/databases/postgresql/

**Comment by Kircheneer** [comment]
@glennmatthews that looks very promising, I will work a downgrade of `elasticapm` into our next release

**Comment by Kircheneer** [comment]
@gsnider2195 unfortunately there doesn't appear to be a pattern to this, it happens to workers of seemingly random numbers on both of the hosts.

**Comment by Kircheneer** [comment]
Just to give a quick update - we have deloyed the `elasticapm` downgrade last Friday and so far everything is looking good. I will give another update in a week or so but I think that that was indeed the culprit.

**Comment by gsnider2195** [comment]
The DecodeError just happens to be what's re-raising the actual error here which is coming from postgres psycopg2 exceptions: 
```
InterfaceError('connection already closed')

Exception raised for errors that are related to the database interface rather than the database itself.
```
```
OperationalError('SSL SYSCALL error: EOF detected\n')

Exception raised for errors that are related to the database’s operation and not necessarily under the control of the programmer, e.g. an unexpected disconnect occurs, the data source name is not found, a transaction could not be processed, a memory allocation error occurred during processing, etc.
```

Is it possible since this is running and failing at exactly 1am that the database is running another task that's locking the tables or using up a lot of system resources causing these errors?

**Comment by jathanism** [comment]
Sorry just seeing this now. This is a known issue with SSL and persistent connections. 

Please see the original issue: https://github.com/nautobot/nautobot/issues/127

And the documentation: https://nautobot.readthedocs.io/en/stable/installation/services/#ssl-error

Quick fix: Disable persistent connections:

```python
DATABASES = {
    "default": {
        # Other settings...
        "CONN_MAX_AGE": 0,
    }
}
```

Or just remove this key from your `DATABASES` setting entirely.

**Comment by jathanism** [comment]
@Kircheneer Last looks if you could please confirm that this is suitable for you. Otherwise I'll be closing this! Thanks.
