### ISSUE TITLE
Make atomicity optional when running jobs

### ISSUE THREAD

**Issue by tbotnz** [nautobot/nautobot#1991]
### As ...

P.D. - Plugin Developer

### I want ...

To make DB atomicity in jobs an optional feature

### So that ...

When i have jobs which are long running and make several DB changes i can reflect the DB changes in the DB as they happen instead of at the end of the job.

( e.g Reserve an inventory resource then deploy it in a single job )

### I know this is done when...

I can set a property on the Job which disables the default atomic behavior

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### To Consider

- Migrating away from "magicalness" of current jobs to make running jobs atomic more explicit
    - Dry-run would be up to author to implement
    - Commit flag would go away
- Wrapper/backwards compatibility for pre-existing jobs to maintain existing functionality

**Comment by tbotnz** [comment]
![image](https://user-images.githubusercontent.com/23552972/176800127-69d01e8c-64a5-44cf-afd7-0d235bc6501e.png)

**Comment by glennmatthews** [comment]
Will need to think about how this interacts with job scheduling and approvals - if the job run is no longer atomic, then there will be no ready way for an approver to "dry-run" the job to preview its effects on the database, unless the job itself implements a custom "dry-run" parameter.

This may be desirable though as the current "dry run" functionality is potentially misleading, as if the job is capable of making any changes to external systems, it is up to the job author to ensure that it doesn't do so when run with `commit=False` at present.

**Comment by jifox** [comment]
In my opinion it would be a great feature if a job-result could be forwarded to the approval jobs queue.

This would allow users that can execute a job without having the "Commit" permission. To forward the job with a reference to the job-results to a user taht can commit the change.

**Comment by bryanculver** [comment]
Good morning @tbotnz!

We recently planned out v2.0 of Nautobot and have decided to rip out the automatic atomic behavior of jobs as a breaking change.

As you saw it was essentially just wrapping everything in `with transaction.atomic():` this is something that can be easy to move down to the job author level. We may or may not provide simple handles based on inheritance to restore this magic but having two separate inheritances vs wrapping your code in a single function call is a bit even on complexity change.

We'll be documenting this as well as providing examples of how a job author can maintain atomic transactions.

If this changes during prototyping->implementation we will re-open this issue.

As always, thank you for your contributions!
