### ISSUE TITLE
Filter form UI revamp

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#1998]
### As ...

Nelly - Network Engineer

### I want ...

An extensible and easy-to-use filter form UI in all object list views

### So that ...

I have a better experience when trying to filter results which allows me to use all possible filtering options

### Requirements
- Not display all permutations of fields and lookup expressions simultaneously (by default)
- Provide the user an ability to select any field and lookup expression combination supported by the FitlerSet to filter the table by
- Provide the user with an ability to edit, view current filter arguments
- Provide the user the ability to specify an arbitrary number of filters

### Out of scope
- Filtering arbitrary by nested lookup

### Optional - Feature groups this request pertains to.

- UI/UX

### Database Changes

None

### External Dependencies

None?

See #1608

**Comment by glennmatthews** [comment]
Is "saving" a set of filters, or setting them as per-user defaults for a particular object-list, in scope?

**Comment by lampwins** [comment]
> Is "saving" a set of filters, or setting them as per-user defaults for a particular object-list, in scope?

No

**Comment by bryanculver** [comment]
Let's see if we can also get an answer to #2162 before this.

**Comment by bryanculver** [comment]
Closed with #2348.

Great work @timizuoebideri1!
