### ISSUE TITLE
Allow Jobs to be marked as read-only

### ISSUE THREAD

**Issue by progala** [nautobot/nautobot#200]
### Environment
* Python version: Python 3.8.5
* Nautobot version: 1.0.0b2

### Proposed Functionality

It would be helpful to be able to mark a Job as being read-only, i.e. not modifying the database. This would then remove "Commit message" checkbox from the Job form, and would stop "Database changes..." log messages from showing up in the Job results.

### Use Case

As an end user running Jobs that are read-only (formerly known as Reports) I might not understand why I'm seeing the "Commit changes" checkbox and why "Database changes..." logs show up in Job results.

As a programmer writing a Job I want to be able to specify that given Job will not modify database objects.

### Database Changes

None.

### External Dependencies

None.

**Comment by jathanism** [comment]
Thanks @progala for submitting this. :)
