### ISSUE TITLE
Remove rqworker container from default docker development environment

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#2002]
### Proposed Changes

Nothing in Nautobot core requires rqworker at this point in time, and hasn't since 1.1. But our default docker-compose.yml still includes a container running rqworker. We should consider removing this container for efficiency.

### Justification

Reduced overhead of dev environment.

The only risk I can think of is if:
1) We make some change that breaks the rqworker and don't detect it because of this removal
2) A user is running latest Nautobot but still has a custom plugin that's using the rqworker rather than Celery
then we might have an issue.

**Comment by bryanculver** [comment]
Closed in #2024
