### ISSUE TITLE
VLAN-Deployment-Groups

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#2044]
### As ...

Nelly - Network Engineer

### I want ...

an easy and secure way to deploy VLANs to switches and interfaces (Trunks).

### So that ...

- I can select which VLANs to include in the Deployment-Group out of the VLANs defined in parent group
- I can modify VLAN names by just editing the parent groups data (DRY) without touching the deployment group
- I can securely remove VLANs from parent VLAN-Group and all deployment groups will be updated automatically.
- I can assign more than one deployment groups to single device. So I can define e.g. tagged vlans for Accesspoints, Additional VLANs on site-to-site layer 2 connection that are only used in datacenter (HA Sync), VLANs on edge switches, ...

### I know this is done when...

- I define a new VLAN-Deployment-Group by adding a unique group-name and a constant reference to an existing VLAN-Group. (The parent VLAN group is not changeable after creation).
- I select the VLANs to include in Deployment-Group from the list of VLANs defined in VLAN-Group. All vlans in one deployment-group are unique.
- I add Deployment-Groups (0..n) to a virtual-chassis's, devices or interfaces (allowed vlans). Only Deployment-Groups having the same parent are allowed to add to an object.
    - Adding Deployment-Groups should work like assigning Tags.
- I add a device to a virtual-chassis that has deployment-groups assigned.
    - If the device has also deployment-groups assigned, the parent VLAN-Group needs to be identical in order to allow insertion.
    - If the device has no deployment-groups assigned, it will be added to the virtual-chassis and inherits the virtual-chassis groups as a reference. So changes to the assigned groups of the virtual-chassis will always be reflected at the device level. The device will inherit all DISTINCT vlans of all Deployment-Groups assigned to the virtual chassis (get_deployed_vlans())
- I add a device to a virtual-chassis that has no Deployment group assigned.
    - The virtual chassis takes over the Deployment-Groups from the device. 
    - The device inherits the Deployment-Groups from the virtual-chassis.
- I remove a device from a virtual chassis.
    - All the current Deployment-Groups from the virtual-chassis will be added to the device. This ensures that no configuration change will happen on the device and its interfaces.
- I select the deployed vlans in GraphQL
- I use the API to define and query Deployment Group specific data

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [X] DCIM
- [X] IPAM
- [ ] Misc (including Data Sources)
- [X] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- New model VLAN-Deployment-Group

    ```
    parent_vlan_group:   foreigen key reference parent VlanGroup
    name: str
    slug: str
    description: text
    ref_selected_vlans:  foreigen key reference to vlans in parent_vlan_group
    ```

- References to assigned Deployment-Groups for 
    - VirtualChassis
    - Device
    - Interface

**Comment by gsnider2195** [comment]
This appears to be a good use case for dynamic groups however vlans and vlan groups aren't supported in dynamic groups yet. We're going to need to determine if dynamic groups, custom relationships and possibly custom validators would satisfy all of the requirements above.

**Comment by jifox** [comment]
@bryanculver Is there a time horizon for adding VLANs to Dynamic groups?

**Comment by bryanculver** [comment]
> @bryanculver Is there a time horizon for adding VLANs to Dynamic groups?

Dynamic Groups should come to more models in 2.X with the work in #1483. We can prioritize models but we're working on fixing the filter sets which is the blocker for adding it to more models.

**Comment by glennmatthews** [comment]
VLANs can be assigned to dynamic groups now.
