### ISSUE TITLE
API call to sync all Git repositories

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot#2047]
### As ...

Austin - Network Automation Engineer

### I want ...

I would like to have a single API call in Nautobot that triggers a sync of all Git repositories.  Currently a separate API call must be made for each individual repository.

### So that ...

When I write automation for config deployments using the Golden Config plugin and Ansible, I can refresh all relevant repositories in a single API call.  For example, I currently refresh 4 repositories, requiring 4 separate API calls:
- running-config backups repo
- intended config state files repo
- structured data repo
- jinja2 template repo

### I know this is done when...

I can make a single POST API call to refresh all Git repositories currently configured.

Maybe it can look something like:
`http://nautobot-url/api/extras/git-repositories/sync`

The current one for syncing one repo at a time is
`http://nautobot-url/api/extras/git-repositories/{id}/sync`

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

n/a

### External Dependencies

n/a

**Comment by lampwins** [comment]
@matt852 @itdependsnetworks this _feels_ like a feature that is specific to a need in golden config? Does there really exist a need to sync _every_ repo across every repo I may have defined? I think it makes sense to sync all those related to golden config in one go, but maybe I don't want to sync all my data source repos for other things at the same time.
