### ISSUE TITLE
Relationships do not have Change Log View.

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot#2051]
### Environment
* Python version: 3.8
* Nautobot version: 1.3.5

### Steps to Reproduce
1. Create a relationship
2. On relationship detail view there is no Change Log Tab.

### Expected Behavior
Change Log view is displayed for the Relationship.

### Observed Behavior
Cannot access Relationship Change Log.

**Comment by smk4664** [comment]
Relationships use the ChangeLoggedModel but do not have a URL endpoint for their changelog.

**Comment by glennmatthews** [comment]
Good catch. We missed this in #1894.

**Comment by smk4664** [comment]
I was going to fix this in develop, but noticed that between develop and next that relationships changed from using uuid to using a slug. Should I fix it in both develop and next?

**Comment by glennmatthews** [comment]
But`develop` doesn't even *have* a detail view for relationships?

**Comment by bryanculver** [comment]
Closed in #2055.
