### ISSUE TITLE
Dynamic Group Set Theory Names

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot#2069]
### As ...

Ozzie - Operator

### I want ...

To fully understand how to construct my Dynamic groups, despite my limited knowledge on set theory, using common terms I may understand better. 

### So that ...

I can quickly create dynamic groups as well as train coworkers to develop dynamic groups using language that is simple and easy to understand. 

### I know this is done when...

When there is reasonable naming within the dynamic group set theory instructions. 

Specifically, that the choiceset defined here: https://github.com/nautobot/nautobot/blob/bc5fafa681604b6e141814c5281dc528627618de/nautobot/extras/choices.py#L97-L106 

If we observe other usage of this, such as Ansible: https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html#common-patterns They use:
* Multiple groups (OR)
* Intersection of groups (AND)
* Excluding groups (NOT)

Salt Include/Exclude https://docs.saltproject.io/en/latest/ref/states/include.html
Sumo Logic Include/Exclude https://help.sumologic.com/Manage/Collection/Processing-Rules/Include-and-Exclude-Rules

These do not align directly with set theory, but are more human readable. 

In line with the same practices, can we consider some alternative names:
* OR -- Include 
* AND -- Common/Overlap
* NOT -- Exclude

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [X] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

N/A

### External Dependencies

N/A

**Comment by lampwins** [comment]
I think we want to maintain the `OR`, `AND`, & `NOT` terminology in parenthesis. My vote for names would be:

- Include (OR)
- Include (AND)
- Exclude (NOT)

**Comment by jathanism** [comment]
> I think we want to maintain the `OR`, `AND`, & `NOT` terminology in parenthesis. My vote for names would be:
> 
> * Include (OR)
> * Include (AND)
> * Exclude (NOT)

Deciding to go with "Restrict (AND)" vs. having Include in there twice. 

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/138052/180074370-3bbd3930-fd08-4032-b807-08df2ac7e327.png">

**Comment by bryanculver** [comment]
Closed with #2079
