### ISSUE TITLE
Darkmode is not consistent, page flashes in default mode during page load

### ISSUE THREAD

**Issue by sirtux** [nautobot/nautobot#2075]
### Environment
* Python version: 3.9
* Nautobot version: v1.4.0a2

### Steps to Reproduce
1. Enable dark mode
2. Go to any other page then the current one

### Expected Behavior
Dark mode is permanent active

### Observed Behavior
During load, I can see the light mode pop up for less then a second before it switches to dark mode.
This breaks the user experience and also hurts in the eye.

**Comment by lampwins** [comment]
Actually just confirmed this on https://next.demo.nautobot.com/dcim/devices/?per_page=1000

Seems this is because we load the theme JS after content (which is a general JS best practice), but that is biting us here.

**Comment by gsnider2195** [comment]
Could we switch this to on dom ready instead of page load complete?
