### ISSUE TITLE
JobResult logs can be exported as CSV

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot#2086]
### As ...

Ozzie - Operator

### I want ...

to have an easy option to export the JobResult logs into a CSV file

### So that ...

I could take this output into other systems

### I know this is done when...

- In the JobResult page there is a button to "Export to CSV" the generates and downloads the CSV file

### Optional - Feature groups this request pertains to.

- [x] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

Nothing

**Comment by glennmatthews** [comment]
What data in particular are you looking to include in the export? Is just job/timestamp/user/status sufficient or would you be looking to somehow include the logs as well?

**Comment by chadell** [comment]
yes, I would like the logs:  job/user/timestamp/grouping/level/object/message

**Comment by glennmatthews** [comment]
OK, so this is more about exporting the logs for a single JobResult than it is for exporting the overall JobResults table, correct?

**Comment by chadell** [comment]
Yes, will try to refine the description to explain it better
