### ISSUE TITLE
Facing Static Media Failure error after fresh installation

### ISSUE THREAD

**Issue by sajaltiwari** [nautobot/nautobot#210]
### Environment
* Python version: 3.6.8
* Nautobot version: 1.0.0b2

### Steps to Reproduce
1. Followed all the steps from the document
2. After nginx getting Static Media error
3. Disabled selinux but still not working

### Expected Behavior
Should get page of Nautobot

### Observed Behavior
Getting Static Media Failure error page

**Comment by jathanism** [comment]
Can you please provide context on what system you're running on? Is it CentOS? If so, which version?

Can you please also provide the static media error output you'r receiving and anything else that might help us to reproduce the issue? Thanks!

**Comment by sajaltiwari** [comment]
Centos version: 
CentOS Linux release 8.2.2004 (Core) 

Below is the error I am getting while accessing the web app.

![image](https://user-images.githubusercontent.com/30925310/112967795-40d18a80-9169-11eb-9c05-b08b53e187bf.png)

**Comment by sajaltiwari** [comment]
@jathanism  Can you please check the above message and help in fixing the issue. I have already disabled SELinux and check the configuration files.

**Comment by jathanism** [comment]
> Centos version:
> CentOS Linux release 8.2.2004 (Core)
> I am using Nginx for HTTP and default WSGI

Let's double check the basics. 

Can you please share your NGINX config? Or confirm that the location mapping for `/static/` in your NGINX config matches the path where the static files are (e.g. `/opt/nautobot/static/`)? For example:

```
    location /static/ {
        alias /opt/nautobot/static/;
    }
```

Confirm directory path is world-readable, for example:
```
$ ls -ld /opt/nautobot/static
drwxr-xr-x 2 nautobot nautobot 4096 Mar 30 20:56 /opt/nautobot/static
```

If those are accurate, what happens when you navigate directly to `/static/materialdesignicons-5.4.55/css/materialdesignicons.min.css`. Do you get a 404?

**Comment by sajaltiwari** [comment]
Thanks @jathanism . Below are the requested logs.

1) Nginx config

`server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;

    server_name _;

    ssl_certificate /etc/pki/tls/certs/nautobot.crt;
    ssl_certificate_key /etc/pki/tls/private/nautobot.key;

    client_max_body_size 25m;

    location /static/ {
        alias /opt/nautobot/static/;
    }

    # For subdirectory hosting, you'll want to toggle this (e.g. `/nautobot/`).
    # Don't forget to set `FORCE_SCRIPT_NAME` in your `nautobot_config.py` to match.
    # location /nautobot/ {
    location / {
        include uwsgi_params;
        uwsgi_pass  127.0.0.1:8001;
        uwsgi_param Host $host;
        uwsgi_param X-Real-IP $remote_addr;
        uwsgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
        uwsgi_param X-Forwarded-Proto $http_x_forwarded_proto;

        # If you want subdirectory hosting, uncomment this. The path must match
        # the path of this location block (e.g. `/nautobot`). For NGINX the path
        # MUST NOT end with a trailing "/".
        # uwsgi_param SCRIPT_NAME /nautobot;
    }

}

server {
    # Redirect HTTP traffic to HTTPS
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}`

2) Folder permissions
`
[root@server ~]# ls -ld /opt/nautobot/static                               
drwxrwxr-x. 19 nautobot nautobot 4096 Mar 29 12:30 /opt/nautobot/static
`
3) I get a 403 error if I directly navigate to `/static/materialdesignicons-5.4.55/css/materialdesignicons.min.css`.
I did run `nauto-server collectstatic` command as shown in the history of nautobot user

`
[nautobot@contosoipam ~]$ history
    1  python3 -m venv /opt/nautobot
    2  echo "export NAUTOBOT_ROOT=/opt/nautobot" >> ~/.bashrc
    3  source ~/.bashrc
    4  echo $NAUTOBOT_ROOT
    5  echo $PATH
    6  which pip3
    7  pip3 install --upgrade pip wheel
    8  pip3 install nautobot
    9  nautobot-server --version
   10  nautobot-server init
   11  vi $NAUTOBOT_ROOT/nautobot_config.py
   12  echo napalm >> $NAUTOBOT_ROOT/local_requirements.txt
   13  echo django-storages >> $NAUTOBOT_ROOT/local_requirements.txt
   14  nautobot-server migrate
   15  nautobot-server createsuperuser
   **16  nautobot-server collectstatic**
   17  pip3 install -r $NAUTOBOT_ROOT/local_requirements.txt
   18  nautobot-server check
   19  nautobot-server runserver 0.0.0.0:8000 --insecure
   20  vi $NAUTOBOT_ROOT/uwsgi.ini
   21  exit
 `

![image](https://user-images.githubusercontent.com/30925310/113192091-fbea4880-927b-11eb-97b2-1b4afe89ac70.png)

**Comment by jathanism** [comment]
Hmm... Okay thanks for the info. That 403 error is suspicious. Some kind of permissions error affecting the static files.

Can you make sure that `/opt/nautobot` is also world readable (`ls -ld /opt/nautobot`)?

I know you said you _disabled_ SELinux, but can you please confirm how you did that? 

And just in case, did you see the [SELinux Troubleshooting ](https://nautobot.readthedocs.io/en/latest/installation/selinux-troubleshooting/)guide?

Sorry to be pedantic but I just want to isolate that we haven't missed something before I try to reproduce this issue myself.

**Comment by jtdub** [comment]
Can you execute "sestatus" and provide the output?

**Comment by sajaltiwari** [comment]
Thanks found the issue. The `/opt/nautobot` folder didn't had proper permission seems i created it with nautobot user.
I have fixed the permission and it's working now.

Thanks for your help.

**Comment by jathanism** [comment]
> Thanks found the issue. The `/opt/nautobot` folder didn't had proper permission seems i created it with nautobot user.
> I have fixed the permission and it's working now.
> 
> Thanks for your help.

Thanks for the report all the same! We can use this to flesh out our troubleshooting docs.
