### ISSUE TITLE
Model Chassis Switches (Module support)

### ISSUE THREAD

**Issue by FragmentedPacket** [nautobot/nautobot#2101]
### As ...

Nelly - Network Engineer

### I want ...

- To be able to model my chassis switches such as Cisco 9407, Cisco 9410, Cisco Nexus 7/9k, etc.
- To be able to define a module or slot type similar to device type that defines a specific hardware module that can be re-used
- To be able to add the modules to devices and track module related information such as serial number, etc.
- Devices to be able to inherit the interfaces and components from the module so I don't have to define in two places or have them disparate

Related PR from NetBox: https://github.com/netbox-community/netbox/pull/8105

### So that ...

I can properly model my chassis switches and not have to redefine interfaces and components

### I know this is done when...

- When I can create a module type to base modules from that have device components such as interfaces, power supplies, etc.
- When I can create a module and assign it to a device and assign module specific data such as serial number, etc.
- When I can add number of modules are supported in a device type to enforce device type specific constraints
- When I can view a device and all device components (interfaces, etc.) are visible via the normal means (UI/API/GraphQL)
- When I can view all the modules related to a device from UI/API/GraphQL

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [X] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- New models and updates to existing Device model

### External Dependencies

N/A

**Comment by alextremblay** [comment]
I would LOVE to have this feature!

I'm currently using device bays and child devices to model this behaviour, and it's... not fun

plus, implementing a Module model similar to netbox would allow nautobot users to leverage https://github.com/netbox-community/devicetype-library, which would be an absolute killer feature for getting new users up and runnign quickly with Nautobot :)

**Comment by aanghel123** [comment]
is this targeted for version 2.X?

**Comment by jvanderaa** [comment]
@FragmentedPacket how would this be different than using Inventory and Inventory Items?

**Comment by qduk** [comment]
@jvanderaa I discussed this briefly with @chadell. While inventory items do provide some of the functionality of a module, the biggest difference I see missing is adding components. Inventory items don't allow that. Something also to think about is how we'd model these in a rack. I don't believe inventory items are represented in a rack.

**Comment by qduk** [comment]
@jvanderaa I would think we'd still keep inventory items solely based on the viewpoint Glenn pointed out [here](https://github.com/nautobot/nautobot-plugin-netbox-importer/issues/92#issuecomment-1718150685)

**Comment by jvanderaa** [comment]
Hmm, so that is saying that we would need to make some migrations to it. I still really don't see a difference in the real world of the difference, except maybe we are saying that InventoryItems are not nestable, in that a SIP / SPA / Device such as the Cisco ASRs world there is.

**Comment by bradh1977** [comment]
has this feature been targeted for any upcoming release?  I was trying to determine an efficient way to associate line cards with my Arista chassis switches.  Some way of identifying the module and all its associated fixed interfaces to a "device bay."  Inventory item does not accomplish this, rather it just appears to set a name to the slot... Then you have to add the interfaces later.

**Comment by lampwins** [comment]
We are planning this for 2.3, in June of 2024.

**Comment by gsnider2195** [comment]
# Design meeting notes

- Create new `ComponentModel` for `ModuleBay` and `ComponentTemplateModel` for `ModuleBayTemplate` for placing modules on devices. Both models contain a `CharField` for `position`
- Create `ModuleType` for modules which will be similar to `DeviceType`. `ModuleType` will be able to have its own component templates that get instantiated on new module creation
  - The names of the components created from a module's component templates can be templated according to the module identifier (`Ethernet1/<module.modulebay.position>/1`)
- Create `PrimaryModel` for `Module` which will have FKs to the `Device`, `ModuleBay`, `ModuleType` and `CharFields` for `serial` and `asset_tag` (and other miscellaneous device-ish fields)
- Create a child model of `ComponentModel` called `ModularComponentModel` (or something else) that will have a new nullable FK to `Module`. Will need to update the `Interfaces`, `Console ports`, `Console server ports`, `Power ports`, `Power Outlets`, `Front pass-through ports`, `Rear pass-through ports`, and any other `ComponentModel` that can be placed within a module to be a `ModularComponentModel`.


What do these checkboxes on the "add module" view do:

![image](https://github.com/nautobot/nautobot/assets/75227981/63a52e91-d9f9-4543-81be-2af7c881008d)

![image](https://github.com/nautobot/nautobot/assets/75227981/a0e49451-e2a5-42f1-ac62-e78f5abe2962)

**Comment by gsnider2195** [comment]
- Lets also consider the case where Nautobot is used as an inventory for modules that may not yet be installed. So I may want to instantiate a bunch of Modules that aren't installed in ModuleBays/Devices but are associated to the location where they're stored (an inventory of spare modules)
- We'll want to look at a way to migrate InventoryItems to Modules, maybe similar to the way we are migrating Location.contact_* to the Contact and Team models in #5034
- We may also have a use case for Modules that contain ModuleBays themselves
- What is the UX of physically moving a module with connected cables? We could probably just keep the cables connected and let the user use the bulk disconnect feature of the interfaces table if they would like to disconnect them. Would need to document this behavior
