### ISSUE TITLE
Allow Plugins to use utilities/templatetags/buttons.py

### ISSUE THREAD

**Issue by FragmentedPacket** [nautobot/nautobot#212]
### Environment
* Python version: 3.8.8
* Nautobot version: 1.0.0b2

### Proposed Functionality
Allow plugin authors to use the builtin [buttons](https://github.com/nautobot/nautobot/blob/develop/nautobot/utilities/templatetags/buttons.py#L27).

I spoke with @jathanism on this and he agreed with adding a `plugin` field to these buttons that would prepend on the `_get_viewname` function.

An example:

```python
def _get_viewname(instance, action, plugin=False):
    """
    Return the appropriate viewname for adding, editing, or deleting an instance.
    """

    # Validate action
    assert action in ("add", "edit", "delete")
    viewname = "{}:{}_{}".format(instance._meta.app_label, instance._meta.model_name, action)
    if plugin:
        viewname = f"plugins:{viewname}"

    return viewname

@register.inclusion_tag("buttons/clone.html")
def clone_button(instance, plugin=False):
    url = reverse(_get_viewname(instance, "add", plugin=plugin))

    # Populate cloned field values
    param_string = prepare_cloned_fields(instance)
    if param_string:
        url = f"{url}?{param_string}"

    return {
        "url": url,
    }
```
This would allow plugin authors to reuse this code within HTML templates for views.

Also what may help is the following template snippet:

```
    <div class="pull-right">
        <div class="pull-right noprint">
            {% plugin_buttons object %}
            {% if perms.extras.add_status %}
                {% clone_button object plugin= True %}
            {% endif %}
            {% if perms.extras.change_status %}
                {% edit_button object plugin=True %}
            {% endif %}
            {% if perms.extras.delete_status %}
                {% delete_button object plugin=True %}
            {% endif %}
        </div>
    </div>
```

If this is accepted by the other maintainers, I can do the work to submit a PR to get this feature implemented.

### Use Case
Developing a plugin and attempting to re-use as much code provided by Nautobot.

**Comment by glennmatthews** [comment]
I'm in favor of this feature, but I'd recommend that instead of adding a separate `plugin` parameter to the API, we instead check whether the provided `instance`'s `app_label` is a native app or a plugin app, and automatically derive the correct reversed viewname accordingly - see #293 for an example fix to a similar issue.

**Comment by FragmentedPacket** [comment]
@glennmatthews Thanks for the suggestion. Implemented that and this helped me get rid of custom HTML for the list view and just use everything builtin.
