### ISSUE TITLE
SyntaxWarning Nautobot-server migrate

### ISSUE THREAD

**Issue by Jpickle779** [nautobot/nautobot#2139]
### Environment
*Ubuntu Server 22.04 (Jammy)
*postgreSQL 14.4
* Python version: 3.10.4
* Nautobot version: 1.3.9

### Steps to Reproduce
1. Install dependencies
2. Run installation up until Nautobot-server migrate
3.

### Observed Behavior
![C443FAC9-7AE0-4A63-8AD7-1FA6B0777B45](https://user-images.githubusercontent.com/96391015/182729213-83d4891a-5974-4d0b-8830-4412fef05ce2.png)

**Comment by bryanculver** [comment]
@Jpickle779 This seems to be throwing an error around the configuration. Can you provide a sanitized config?

**Comment by bryanculver** [comment]
Unable to reproduce.
