### ISSUE TITLE
Dynamic Group - UI Issues with Filters/Stacking

### ISSUE THREAD

**Issue by mzbroch** [nautobot/nautobot#2141]
### Environment
* Python version:
* Nautobot version: 1.4.0-beta1 (4th August - next)

### Steps to Reproduce
1. Create a dynamic group with a filter assigned
2. Assign sub-groups (nested) to a group with an existing filter 
3.

### Expected Behavior
Nautobot should prevent groups from having both children groups and filters assigned to them.

### Observed Behavior
Nautobot allows for the group to have both children and filters on a parent group.

**Comment by bryanculver** [comment]
Closed with #2144
