### ISSUE TITLE
When using SSO (okta) logs only show when a user logs out but not in

### ISSUE THREAD

**Issue by gneville-ot** [nautobot/nautobot#2146]
### Environment
* Python version: 3.10
* Nautobot version: 1.3.8

### Steps to Reproduce
1. Setup nautobot with SSO against OKTA
2. Attempt to login using SSO with a valid user
3. Attempt to logout

### Expected Behavior
You will see both a login and logout message printed to stdout for the user

### Observed Behavior
You only see a logout message printed to stdout for the user

### Extra Info
As a temporary solution I changed the code in https://github.com/nautobot/nautobot/blob/develop/examples/okta/group_sync.py and added the following so I can get a log for when a user using OKTA logs in:

```
<--snip-->
loggerauth = logging.getLogger("nautobot.auth.login")
<--snip-->

def group_sync(uid, user=None, response=None, *args, **kwargs):
<--snip-->
    loggerauth.info(f"User {uid} successfully authenticated")
<--snip-->
```

**Comment by lampwins** [comment]
Django should have a signal that it uses to update the `last_login` timestamp for user. Hooking into that signal is likely the best way to solve this.
