### ISSUE TITLE
Extend Core models listviews from plugins

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot#2147]
### As ...

P.D. - Plugin Developer

### I want ...

to get the option to add fields in Nautobot Core model list views (tables) from Plugins, to add reference to new models added by the plugins.
Also, to customize the display and order of the columns in this view, to make it more relevant to the content added by the plugin 

### So that ...

My plugin can enrich the core model information directly in the core views.

### I know this is done when...

I have an option to extend the tables used by the listview, creating new fields, and manipulating the default display and order.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [X] Circuits
- [X] DCIM
- [X] IPAM
- [X] Misc (including Data Sources)
- [X] Organization
- [X] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

Don't think so.

**Comment by minitriga** [comment]
Hey, 

Was talking to Jason last night about this at a meet up and I have tested the implementation of this with Netbox many months ago as it was a requirement I had from a previous project. I was able to achieve adding columns to any tables within the platform by creating a new column and then registering that column to a Netbox table. 

```python
import django_tables2 as tables

InterfaceCount = tables.TemplateColumn(
    template_code = """{{record.interfaces_count}}""",
    verbose_name="Interface Count"
)

class site_journal_entries_count(tables.Column):
    def render(self, value):
        return value.count()

    def value(self, value):
        return value.count()

columns = [
    # Table to Add to, Name of Coumn, Column
    ('DeviceTable', 'interface_count', InterfaceCount),
    ('DeviceTable', 'site_journal_count', site_journal_entries_count(
        verbose_name='Site Journal Entries', 
        accessor='site.journal_entries'
        )
    )
]
```

Here is my example plugin: https://github.com/minitriga/netbox_table_plugin/tree/main/netbox_table_plugin
These are my commits to a fork of Netbox to test functionality:

- https://github.com/minitriga/netbox/commit/b03f76f7ef301b6a1f18fd67f7764496b3beec23
- https://github.com/minitriga/netbox/commit/f21f1de3f0d307541814d94b6cdc8de7dd073389

**Comment by bryanculver** [comment]
Related?  #1957

**Comment by chadell** [comment]
Yes, I think that #1957 solves it (even before I created the issue).
@minitriga do you agree?

**Comment by lampwins** [comment]
We will cover this in #4899
