### ISSUE TITLE
Homepage cards can be customized

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot#2149]
### As ...

Austin - Network Automation Engineer

### I want ...

to have the option to choose which family cards are showed in the Nautobot homepage, to provide a more relevant view of Nautobot status.

> Eventually, it would be great to also be able to add new cards from a plugin (it would go to a different issue if this makes sense) 

### So that ...

the Nautobot homepage would show only relevant information

### I know this is done when...

I have an option to customize the homepage via settings, ideally per user, but it could also work defining it globally in the nautobot_config.py

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

don't think so

**Comment by glennmatthews** [comment]
Plugins can already add new homepage content (https://nautobot.readthedocs.io/en/stable/development/homepage/) and you can use the `HIDE_RESTRICTED_UI` config setting if you want content that a user doesn't have access to to be removed from the home page.

Is the request here to be able to remove/hide homepage content that core provides, and that the user has permissions to access?

**Comment by chadell** [comment]
> Is the request here to be able to remove/hide homepage content that core provides, and that the user has permissions to access?

Yes, the request is to remove/hide content not limited to the permissions to access

**Comment by glennmatthews** [comment]
Initial implementation in #4908. We can refine further in future.
