### ISSUE TITLE
Swagger documentation lists incorrect authorization header

### ISSUE THREAD

**Issue by achard** [nautobot/nautobot#2154]
### Environment
* Python version: 3.10
* Nautobot version: 1.39

### Steps to Reproduce
1. Open the swagger API interface 
2. Attempt to use the included curl commands to execute API calls

### Expected Behavior
The listed authorzation header value should be 
Authorization: Token <VALUE>

### Observed Behavior
THe header value is instead
Authorzation <VALUE>

![image](https://user-images.githubusercontent.com/776287/183323157-1359a238-3fde-4d08-89f7-8389b5ad9b00.png)

**Comment by smk4664** [comment]
@achard and I looked into this a little. This issue occurs when you use Authorize on the tokenAuth with just the token and no `Token` prefix. Perhaps this should be renamed to Swagger Docs Token Authorization without `Token` prefix.
