### ISSUE TITLE
MultiValueCharFilter for non-related model fields needs to be addressed

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#2162]
### Proposed Changes

This filter needs to be adapted since there are cases where `CharField` filters (such as `DeviceFilterSet.name`) do not make any sense as what gets rendered as a `DynamicMultipleChoiceField in` many forms. The dynamically generated `MultiValueCharField` that gets generated doesn't necessarily map to non-choice-backed fields (e.g. `Device.name` or `Device.asset_tag`).

- As currently generated, it inherits from `MultipleChoiceFilter`, but this should only be the case if it is eligible to have choices provided at filter definition time (such as if it is a slug-related field or the new `NaturalKeyorPKMultipleChoiceFilter`).
- A raw char field (like `Device.name`) does not inherently have any choices to from which to choose, so using `MultiVarCharFilter` is incorrect to make it a choice filter unless choices are also provided.
- A pattern similar to what we had to do with `ContentTypeFilter` (inherits from `CharFilter`) and `ContentTypeChoiceFilter` (inherits from `ChoiceFilter`) with a common mixin (`ContentTypeFilterMixin`) shared between them should be considered here.

### Justification

This is an important consideration for generating UI fields automatically from filtersets as we assert consistency in newer features like Dynamic Groups. Consider `Device` objects where the principle of least astonishment is violated when working with this feature via the API on the `name`, `serial`, and `asset_tag` fields, since almost every filter field is a multi-value filter, except for these.

**Comment by bryanculver** [comment]
This might be sufficient: https://select2.org/tagging#tagging-with-multi-value-select-boxes

In their demo I could easily search for arbitrary text including spaces and commas and creating the "value" by pressing enter. Might be worth exploring.

**Comment by bryanculver** [comment]
Closed via #2413
