### ISSUE TITLE
Eliminate `NullableCharFieldFilter`, and review `CharField` where `null=True`

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#2163]
### Proposed Changes

`NullableCharFieldFilter` (and `nautobot.NullableCharField` itself) needs to go away in v2. It is not even used.

Guidance here:
- Remove `nautobot.utilities.filters.NullableCharFieldFilter` and `nautobot.utilities.fields.NullableCharField`
- Establish style enforcement that any model `CharField` must never have `null=True` and `blank=True` set UNLESS `unique=True`
- Where not explicitly required, any `CharField` with `null=True` should be removed.

### Justification

It is bad data design to have `CharField` with `null=True` because this introduces two ways such a field can be considered "empty" (both an empty string or `None`).

From the Django docs on [`null`](https://docs.djangoproject.com/en/4.0/ref/models/fields/#null):

> Avoid using [`null`](https://docs.djangoproject.com/en/4.0/ref/models/fields/#django.db.models.Field.null) on string-based fields such as [`CharField`](https://docs.djangoproject.com/en/4.0/ref/models/fields/#django.db.models.CharField) and [`TextField`](https://docs.djangoproject.com/en/4.0/ref/models/fields/#django.db.models.TextField). If a string-based field has `null=True`, that means it has two possible values for “no data”: `NULL`, and the empty string. In most cases, it’s redundant to have two possible values for “no data;” the Django convention is to use the empty string, not `NUL`L. One exception is when a [`CharField`](https://docs.djangoproject.com/en/4.0/ref/models/fields/#django.db.models.CharField) has both `unique=True` and `blank=True` set. In this situation, `null=True` is required to avoid unique constraint violations when saving multiple objects with blank values.

**Comment by glennmatthews** [comment]
Review of existing cases:

- `BaseInterface.mac_address` has `null=True` but is not required to be unique. Should be made non-nullable.
- `JobLogEntry.log_object` and `JobLogEntry.absolute_url` have `null=True` but probably should be changed.
- `ScheduledJob.queue` has `null=True` and may have logic around  this, but should be changed to use blank instead.
- `WebHook.ca_file_path` has `null=True`, change it.

- `InventoryItem.asset_tag` has `null=True` but also `unique=True`, leave as is.
- `Device.name` has `null=True` and `db_index=True`, and is part of a `unique_together` constraint, leave as is for now.
- `Device.asset_tag` has `null=True` but also `unique=True`, leave as is.
- `Rack.facility_id` has `null=true, is not required to be unique, but is part of a `unique_together` constraint. Leave as is.
- `Rack.asset_tag` has `null=True` but also `unique=True`, leave as is.
- `VRF.rd` has `null=True` but also `unique=True`, leave as is.

**Comment by itdependsnetworks** [comment]
Should any of these be use cases in #2257? I don't fully get it, but this one seems like it should never be

> BaseInterface.mac_address has null=True but is not required to be unique. Should be made non-nullable.

**Comment by glennmatthews** [comment]
Would be nice to cover in #2257 but may be tricky to automate - the logic would be something like:

if isinstance(field, (CharField, TextField)) and field.null and not (field.unique or exists(unique_together constraint containing field)) then raise a warning

**Comment by glennmatthews** [comment]
Resolved in #3046 for 2.0.
