### ISSUE TITLE
Jobresults - Info field on Table

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#2171]
### As ...

Nelly - Network Engineer

### I want ...

I want to easily see, which Data was  modified by a particular job.

### So that ...

I can identify the jobresult to select when viewing the job-results table.

e.g.: The Job "Update Device Interface" pushes the current configuration to the device. At present there is no way to identify the jobresult that had updated a particular interface.

An additional column, to displays info  that's created during job execution would be fine.

### I know this is done when...

- I execute a job.
- The job exectutes `self.log_remark(f"Info to Display in Job-Results-Table")`
- I configure this infomation to be a visible column in jobresults table

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [X] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- ?? Maybe just select the log entry with type "remark"

### External Dependencies

None

**Comment by jathanism** [comment]
Are you thinking of something that just allows storing a reference to the modified object? Or just something free-form? The former is remarkably difficult to do unless we perhaps consider leveraging the `Notes` feature for something like that to store a "remark" as a note for an instance.

**Comment by jifox** [comment]
In my opinion the free form would be best. The objects are available in job-log lines. But for selection of a particular job one can prepare a string that allows the search for the needed criteria.

**Comment by lampwins** [comment]
This would be covered in #1727
