### ISSUE TITLE
Is there any option for Supplier management/ Vendor assessment through Nautobot

### ISSUE THREAD

**Issue by arunqa** [nautobot/nautobot#2177]
As we are using the Nautobot tool.

We have a requirement for Vendor risk assessment questionnaires / Vendor management. Is there any option available in Nautobot to achieve this requirement?

**Comment by bryanculver** [comment]
Good morning @arunqa!

I see a related discussion opened around vendor management: https://github.com/nautobot/nautobot/discussions/1974

At this time there is no planned feature in core to support this information but this could be a great candidate for a plugin.
