### ISSUE TITLE
[1.4] Jobs Result Filter - Error when Search field "Status" is empty

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#2178]
### Environment
* Python version: 3.9
* Nautobot version: e02bb08e6c2a (v1.4.0rc1)

### Steps to Reproduce
1. Open Job Results Page
2. Filter a "Job"
3. Klick "Apply"

### Expected Behavior
The Job Results table should be populated with selected entries

### Observed Behavior

Error message:
> Invalid filters were specified:
>     * status
>           * Select a valid choice. is not one of the available choices.

When selecting for e.g. "Completed" for the status, it's working fine

**Comment by glennmatthews** [comment]
Thanks for the report! This appears to be a pre-existing issue that is uncovered by the addition of `STRICT_FILTERING` as a default setting in 1.4.
