### ISSUE TITLE
Make Nautobot a general-purpose framework

### ISSUE THREAD

**Issue by vpogrebi** [nautobot/nautobot#2181]
### As ...

P.D. - Plugin Developer

### I want ...

Nautobot to be implemented as a "general-purpose" Python framework

### So that ...

I can develop non-network infrastructure projects that do not include Network Infrastructure components ('dcim', 'ipam', 'virtualization', etc.).

### I know this is done when...

Nautobot can be used as a general-purpose Python framework to develop ANY projects, including projects that do not include network components.

### ADDITIONAL DETAILS

At the moment, few network components ('dcim', 'circuits', 'ipam', 'virtualization', etc.) are tightly "built-in" Nautobot framework, automatically making these components being part of any project that uses Nautobot. Separating these components "out" of the core framework (making them non-required "plugins" so to speak) - will allow Nautobot to become a "general-purpose" framework that can be used for any project implementation including non-network related projects.

This will significantly increase support and use of this framework - making it much more popular by attracting non-network Python development community.

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [X] Organization
- [X] Plugins (and other Extensibility)
- [X] Security (Secrets, etc)
- [X] Image Management
- [X] UI/UX
- [X] Documentation
- [X] Other (not directly a platform feature)

### Database Changes

Everything is already in place. All that's needed - is to make network components "pluggable", non-required components.

**Comment by bryanculver** [comment]
Thanks for the submission @vpogrebi. Do you have any example projects or use cases where you'd like to see Nautobot expand into as a more generic SoT platform?

**Comment by vpogrebi** [comment]
Absolutely, @bryanculver !

My Nautobot experience started when I was part of NIDM (Network Infrastructure Domain Model) project team at BoFA (that contains few Network to Code developers) led by John Anderson - and I've come to love Nautobot. My contract at BoFA ended, and I got job at Paramount (its CBS Interactive part) - in a team that manages Paramount's Content Distribution Network (CDNs) and everything related to it. This is fully cloud-based infrastructure, so there is no internal network infrastructure to carry out content distribution.

I am trying to convince this team to rewrite its existing implementation (non-Django based, no UI, etc.) using Nautobot (which can perfectly be used for this - if not for built-in network components). My thought is that Nautobot in general can be used for ANY project implementation - where Django can be used.

BTW... There was Brian Culver at BoFA (we had some little interaction) - are you him by chance?

**Comment by vpogrebi** [comment]
Please let me know if this can be done, and how son one can expect it to be implemented.

I would not want to use this framework for our team's CDN implementation - unless we can have home HTML and main menu void of network infrastructure related items (which we are not going to use).

On the other hand, if this is done and I succeed in convincing the team to use this framework - we may be able to contribute CDN (Content Distribution Network) plugin implementation.
