### ISSUE TITLE
Return `is_superuser` and `last_login` fields for User API endpoints

### ISSUE THREAD

**Issue by joewesch** [nautobot/nautobot#2208]
### As ...

Austin - Network Automation Engineer

### I want ...

To be able to get the `is_superuser` and `last_login` fields for my User models via API.

### So that ...

I can create a report that will show which of our users are superusers in order to find new superusers that may have been created by other superusers without our knowledge. In addition, to be able to determine when a superuser hasn't logged in for a while and their permissions could be pruned.

### I know this is done when...

- I can call the User API endpoint and get back the values for the `is_superuser` and `last_login` fields.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [X] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

I don't believe so as these fields already exist on the Django User model.

### External Dependencies

N/A

**Comment by jrlee16** [comment]
additionally it would be nice to be able to enable/disable superuser status for user(s) via api to enable automation to enforce superuser access to a specified list of users only.

**Comment by glennmatthews** [comment]
Resolved for 2.0 by #3500.
