### ISSUE TITLE
Housekeeping: replace admin footer block with an `{% include 'inc/footer.html' %}`

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2210]
Would it be possible/sensible to replace this block with an `{% include 'inc/footer.html' %}` similar to what was done in `nautobot/core/templates/base.html` below? I *think* this footer is identical, but would be good to confirm.

_Originally posted by @glennmatthews in https://github.com/nautobot/nautobot/pull/2046#discussion_r920128907_

**Comment by glennmatthews** [comment]
Done in #5423.
