### ISSUE TITLE
Migration to 1.4.0 may fail if default statuses have been modified.

### ISSUE THREAD

**Issue by Rel-iez** [nautobot/nautobot#2215]
### Environment
* Python version: 3.9
* Nautobot version: 1.4.0

Upgrading Nautobot from 1.3.6 to 1.4.0 using the instructions provided in the documentation introduced a conflict with the status 
'Retired' if the existing environment already have this status implemented.

The error occurs during migration when running:
> nautobot-server post_upgrade

Applying dcim.0014_location_status_data_migration...Unexpected error while running data migration to populate status for dcim.location: duplicate key value violates unique constraint "extras_status_name_key"
DETAIL:  Key (name)=(Retired) already exists.

Temporarily solved by renaming the 'Retired' status.

### Steps to Reproduce
1. Have a status called 'Retired' in existing environment.
2. Upgrade to 1.4.0 from 1.3.x with the same steps as [documentation](https://nautobot.readthedocs.io/en/latest/installation/upgrading/).
3. Data migration during the post upgrade process will run into a duplicate key value.

### Expected Behavior
Successful data migration

### Observed Behavior
Unexpected error during post upgrade due to duplicate keys, status name 'Retired'.

**Comment by glennmatthews** [comment]
Thanks for the report! I haven't encountered this in my own environment, but from code inspection it looks likely that this is going to be the case if any of the pre-populated status's slug, description, or color has been changed from the default values defined in `nautobot/extras/management/__init__.py` and `nautobot/dcim/choices.py`.
