### ISSUE TITLE
Swagger API Docs Appears to Have Lost Sectional Headings

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#2222]
### Environment
* Python version: 3.9
* Nautobot version: 1.4.0

### Steps to Reproduce
1. Install Nautobot
2. Navigate to https://test.nautobot.com/api/docs/#/ page
3. Expect to see headers for circuits, dcim, ipam, etc...

### Expected Behavior

Expect to see headers for circuits, dcim, ipam, etc...

### Observed Behavior

See only section headers of `API` and `Circuits`

**Comment by glennmatthews** [comment]
Possibly same root cause as #2232
