### ISSUE TITLE
Performance Testing Harness: Identify Current Baseline Performance with Multiple Datasets

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2228]
Snapshot current performance of tests run from completing #2227 with average and very-large datasets.

@lampwins and @bryanculver responsible for retrieving or defining the scale of both datasets.

This is aimed at providing CI heuristic for PRs/releases that significantly impact performance, as well as identifying workflows for improvement when it comes to performance instead of just user reports, suspicions.

**Comment by lampwins** [comment]
This is underway in another backlog
