### ISSUE TITLE
Swagger UI broken (extra `/api` in URLs)

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#2232]
### Environment
* Python version:
* Nautobot version: 1.4.0

### Steps to Reproduce
1. Navigate to /api/docs/
2. Attempt any "Try it out" operation

### Expected Behavior

Valid API request, e.g. to `http://localhost:8080/api/circuits/circuit-terminations/`

### Observed Behavior

Invalid API request due to an extra `/api` in the URL, e.g. `http://localhost:8080/api/api/circuits/circuit-terminations/'`

Additionally, there's an extra `/circuits` section at the end of the listed endpoints:

![image](https://user-images.githubusercontent.com/5603551/185177652-5f3fa71d-9796-4463-a941-a57badde3792.png)

This appears to have been broken by #1902.

**Comment by jvanderaa** [comment]
I did some testing with pynautobot to test against what the impact may be on this. Pynautobot did handle API requests just fine for many of the items including creating devices, sites, and IPAM.

**Comment by glennmatthews** [comment]
Yeah, pynautobot *should* be using the REST API directly, not going through Swagger, so I'd expect it to be unaffected - thanks for checking though!

**Comment by jvanderaa** [comment]
Agreed, didn't know if there was a challenge with the URL all together.
