### ISSUE TITLE
Location Names Don't Provide Enough Context in Dropdown

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2235]
### Discussed in https://github.com/nautobot/nautobot/discussions/2233

<div type='discussions-op-text'>

<sup>Originally posted by **Phill93** August 17, 2022</sup>
Hi,

can someone give me a tip how to best create my location structure in 1.4.0?

I have several buildings that are designated with numbers (e.g. 101,102...) in these the rooms are again designated with numbers (e.g. 001, 101, 201).

I have now created the following location structure in my Nautobot instance: Building -> Floor -> Room (102 -> G -> 101)

If I now have the room 101 in several buildings, Nautobot lists me the 101 several times in the location field without differentiation.

<img width="905" alt="Bildschirmfoto 2022-08-17 um 17 40 31" src="https://user-images.githubusercontent.com/1454797/185182721-a7192cfa-f74b-4952-b1aa-ebdc9c3954f5.png">

Greetings

Daniel

Translated with www.DeepL.com/Translator (free version)

</div>

**Comment by christhant** [comment]
After looking into the content setup and code,  
1. it appears that location types are not allowed to setup with the same name. i.e. all the location type names must be unique.
2. location type dropdown is using Python generic DynamicModelChoiceField. It probably needs to be created with custom model that can take different set of parameters and display hierarchical data structure in the dropdown. 


![Image](https://user-images.githubusercontent.com/110844839/187217204-80d58bbb-1aad-4848-86b9-4a2e64459ca0.png)

**Comment by bryanculver** [comment]
> After looking into the content setup and code,
> 
> 1. it appears that location types are not allowed to setup with the same name. i.e. all the location type names must be unique.
> 2. location type dropdown is using Python generic DynamicModelChoiceField. It probably needs to be created with custom model that can take different set of parameters and display hierarchical data structure in the dropdown.

Take a look at the API response for the Locations endpoint. The Select2 widget should grab a `display_name` field if present in the response. Clicking this dropdown calls said API:

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/31187/187224763-45a78ab4-0f66-4a53-88f0-471a9042ce7c.png">
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/31187/187224879-87001300-d747-4191-889b-bc5b26aab151.png">
