### ISSUE TITLE
Implement best practice for using `get_route_for_model()` for fetching URL routes

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#2243]
### Proposed Changes

As a part of the work for Dynamic Groups a new utility function was introduced at `nautobot.utilities.utils.get_route_for_model()` which given a model and an action will construct a URL route for you. Using this function should be established as a best practice for Nautobot developers. 

### Justification

There are "micro" anti-patterns all over the code base where this logic is manually constructed. While currently working, it's effectively propagating an established pattern by way of copy and paste, which is undesirable longer term.

For example: 

https://github.com/nautobot/nautobot/blob/6d7065dbbeec91ca88783a79406bbe91dd6649a3/nautobot/extras/models/change_logging.py#L51-L53

A similar pattern also exists for API routes:

https://github.com/nautobot/nautobot/blob/6d7065dbbeec91ca88783a79406bbe91dd6649a3/nautobot/utilities/testing/api.py#L63-L67

We should unify these all under a single code path, remove the duplication, and document this as a best practice. Longer term we should enforce it with linters.

**Comment by bryanculver** [comment]
Other than having to make changes in dozens of places (say if we want to refactor our URI/reverse signatures), are there performance improvements with moving this all into a defined util function (can we cache the call more for potentially cutting down DB lookups or expensive `if` checks)?

**Comment by jathanism** [comment]
Fixed by #2223
