### ISSUE TITLE
Server error Unknown column 'dcim_region.lft'

### ISSUE THREAD

**Issue by tcjn** [nautobot/nautobot#2251]
### Environment
Python version: 3.8.10
Nautobot version: 1.3.10

### Steps to Reproduce
1. Install fresh nautobot instance on Ubuntu with MySQL backend

### Expected Behavior

No Server error

### Observed Behavior

 Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'django.db.utils.OperationalError'>

(1054, "Unknown column 'dcim_region.lft' in 'where clause'")

**Comment by tcjn** [comment]
Looks like issue is related to https://github.com/nautobot/nautobot/issues/1724

**Comment by glennmatthews** [comment]
Can you confirm whether you're using MySQL or MariaDB? #1724 *should* only apply to MariaDB but not to MySQL.

**Comment by glennmatthews** [comment]
Also can you please confirm what version of MySQL you are running?

**Comment by tcjn** [comment]
I have reinstalled MySQL to MariaDB and issue is solved now. Sorry for a late response.
