### ISSUE TITLE
Nautobot silently discards interface's tagged vlans if mode is wrong

### ISSUE THREAD

**Issue by retnuh** [nautobot/nautobot#2253]
### Environment
* Python version:   N/A
* Nautobot version:  1.3.8

### Steps to Reproduce
1.  Add a vlan to an interfaces tagged vlans, but don't set the mode to `MODE_TAGGED`
2.  call `save` or `validated_save` on the interface
3.  vlan is no longer in tagged_vlans

### Expected Behavior

I think this should be a validation error, rather than a silent discard - or at least _add_ a validation error, so it will be caught in `validated_save`

Here is the code:

```
    def clean(self):
        # Remove untagged VLAN assignment for non-802.1Q interfaces
        if not self.mode and self.untagged_vlan is not None:
            raise ValidationError({"untagged_vlan": "Mode must be set when specifying untagged_vlan"})

    def save(self, *args, **kwargs):

        # Only "tagged" interfaces may have tagged VLANs assigned. ("tagged all" implies all VLANs are assigned.)
        if self.present_in_database and self.mode != InterfaceModeChoices.MODE_TAGGED:
            self.tagged_vlans.clear()

        return super().save(*args, **kwargs)
```

### Observed Behavior

A validation error or other error so that when doing things programmatically, these things don't happen silently.

**Comment by glennmatthews** [comment]
Sounds related to #895
