### ISSUE TITLE
Site latitude or longitude doesn't work with float

### ISSUE THREAD

**Issue by joewesch** [nautobot/nautobot#2256]
### Environment
* Python version: 3.7.13
* Nautobot version: 1.4.0

### Steps to Reproduce
```
>>> from nautobot.dcim.models import Site
>>> site = Site.objects.first()
>>> site.longitude = 33.33
>>> site.longitude
33.33
>>> site.validated_save()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/nautobot/core/models/__init__.py", line 51, in validated_save
    self.full_clean()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 1251, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'longitude': ['Ensure that there are no more than 6 decimal places.']}
>>>
```

### Expected Behavior
I expected the longitude to be accepted since it is less than 6 decimal places

### Observed Behavior
It threw a Validation error that there were more than 6 decimal places.

### Analysis
It seems that since the field is a Decimal field it only accepts strings:
```
>>> site.longitude = "33.33"
>>> site.longitude
'33.33'
>>> site.validated_save()
>>> site.longitude
Decimal('33.33')
>>>
```

### TODO

- In validate/clean, help user by converting Floats inputted into a Decimal. No need to throw error for loss of precision, 6th decimal place precision gets us down to 10cm.

**Comment by jathanism** [comment]
While this is a user experience surprise, the root cause here is actually because a `float` and `Decimal` are not as precise:

```
In [3]: import decimal

In [4]: decimal.Decimal(33.33)
Out[4]: Decimal('33.3299999999999982946974341757595539093017578125')

In [5]: decimal.Decimal("33.33")
Out[5]: Decimal('33.33')
```

The former is why this error about decimal places occurs.
