### ISSUE TITLE
Add UI filterform fields for filtering Devices based on Asset Tag and Serial Number

### ISSUE THREAD

**Issue by martin-networker** [nautobot/nautobot#2258]
### As ...

Ozzie - Operator

### I want ...

Be able to filter devices based on Asset Tags and Serial Number.

### So that ...

Team responsible for HW installation is able to filter devices based on Asset Tag and Serial number.

### I know this is done when...

The team responsible for HW installation identifies devices based on Asset Tag and Serial number.
Currently there is no Asset Tag or Serial number field in Device filters even though both are native Nautobot Device parameters. 
This field should allow filter on multiple values so we will be able to enter "asset_tag_123, asset_tag_456, asset_tag_789" which will filter three devices (if these Asset Tags exists).

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [X] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by glennmatthews** [comment]
Thanks for the request! FYI the filterset and REST API do already support filtering on these fields:

![image](https://user-images.githubusercontent.com/5603551/185637325-fc975b00-c8f1-4e9a-bf93-f8814133613a.png)

and correspondingly you can filter the UI by constructing a URL manually:

![image](https://user-images.githubusercontent.com/5603551/185637603-cd6651ef-accf-4b6b-8c56-493479874d45.png)

so all that's really missing is the UI form field for directly entering a filter value(s). This should be coming in 1.5 as part of:

- #1998 
- #2162

**Comment by martin-networker** [comment]
Thanks @glennmatthews 
The use case is that our HW installation team needs to change for example site for 50 devices based on Asset Tag. The ways you have proposed above are not really suitable for such amount of devices.

**Comment by itdependsnetworks** [comment]
Why doesn't https://nautobot.readthedocs.io/en/latest/plugins/development/#extending-filters work?

**Comment by bryanculver** [comment]
Looks like the filter itself on the Filter Set isn't supporting multiple values (this might change existing behavior).

In order to support this in the UI we will likely need #2162.

**Comment by bryanculver** [comment]
> Looks like the filter itself on the Filter Set isn't supporting multiple values (this might change existing behavior).
> 
> In order to support this in the UI we will likely need #2162.

After reviewing this further:
- `asset_tag` will support multiple filters at present (can be validated in demo environment, `/dcim/devices/?asset_tag=taco&asset_tag=burrito`)
- `serial` is the proper filter name for Serial Number, however this isn't currently implemented with support for multiple values. Needs evaluation if can be fixed in a non-breaking change or if must wait for #1737

As discussed here https://github.com/nautobot/nautobot/issues/2258#issuecomment-1220731123, the improvements for UX are forthcoming.

**Comment by lampwins** [comment]
@nautobot/core can we validate this one?

**Comment by glennmatthews** [comment]
`asset_tag` and `serial` filters both support multi-value filtering in 2.0 and are selectable via the "Advanced" filter form.

![image](https://github.com/nautobot/nautobot/assets/5603551/1f66a763-0ee3-4cf1-82cf-6a4313702d1e)

So I think this can be closed as completed.
