### ISSUE TITLE
Documentation - Development

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#226]
### Environment
* Python version: N.A
* Nautobot version: N.A

### Proposed Functionality

I stumbled over the following message on slack channel and have not found any reference in DEVELOPMENT section of the manual. Add this, please.

> jathanism  17:02 Uhr
Heads up for those of you brave souls building from the develop branch, please get into the habit of running **nautobot-server post_upgrade** which performs a bunch of common operations (such as nautobot-server migrate).

### Use Case

Better development process

### Database Changes

None

### External Dependencies

None

**Comment by jathanism** [comment]
Thanks for the suggestion. This is a new command that hasn't really been weaved into the docs yet other than in the `nautobot-server` reference: https://nautobot.readthedocs.io/en/latest/administration/nautobot-server/#post_upgrade
