### ISSUE TITLE
GraphiQL View - Controls disappearing on resizing window

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot#2265]
### Environment
* Python version: 3.7
* Nautobot version: 1.3.10

### Steps to Reproduce
1. Load GraphiQL UI View
2. Resize window
3. As soon as nav menus hit the right side BUT before transitioning to expanding menu the div of navbar overflows one line and covers up the GraphiQL controls that reside in the topBar div inside the editor

### Expected Behavior
The navbar div expands and pushes the controls further down the view

### Observed Behavior
navbar div covers controls in the topBar div

**Comment by whitej6** [comment]
Normal sizing
![image](https://user-images.githubusercontent.com/26559188/185667634-fafd0746-0d61-4395-aaa3-5cbe7d925ae4.png)

Broken sizing
![image](https://user-images.githubusercontent.com/26559188/185667767-b3494af5-44e1-4078-89ca-66d44aa0553a.png)

Working mobile sizing
![image](https://user-images.githubusercontent.com/26559188/185667912-0072e947-f35a-4f69-85e3-f90c2e9f1556.png)

**Comment by whitej6** [comment]
This can be replicated at `https://demo.nautobot.com/graphql/`

**Comment by glennmatthews** [comment]
Is this a duplicate of #1942?

**Comment by whitej6** [comment]
Yes it is, just verified local instance against develop. Closing
