### ISSUE TITLE
Navigation/Menu bar covers scroll bar

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#2266]
### Environment
* Python version: 3.7.13
* Nautobot version: 1.4.0

### Steps to Reproduce
1. navigate to API documentation http://nautobot/api/docs/
2. try to grab the scrollbar on the right side of the screen
3. scroll down a few pages so that the scroll bar moves below the navigation menu

### Expected Behavior

Scroll bar should be accessible immediately on page load

### Observed Behavior

Scroll bar covered by nav menu until scrolling down

**Comment by glennmatthews** [comment]
Is this specific to the Swagger UI? I think a similar behavior can be seen on any list view if `per_page` is set to 1000 and there are enough items in the list.

**Comment by gsnider2195** [comment]
> Is this specific to the Swagger UI? I think a similar behavior can be seen on any list view if `per_page` is set to 1000 and there are enough items in the list.

I am seeing this on other pages now that you mention it. It's more obvious on the API page because the scrollbar gets so small that it disappears completely behind the menu.
