### ISSUE TITLE
GraphQL query detail view doesn't display default information properly.

### ISSUE THREAD

**Issue by bile0026** [nautobot/nautobot#2269]
### Environment
* Python version: 3.8
* Nautobot version: 1.4.0 (e4112c63d4f6)

### Steps to Reproduce
1. Open a GraphQL query object

### Expected Behavior
Page by default should display the "GraphQL" tab with the query details. 
![image](https://user-images.githubusercontent.com/5022496/185925365-81ded581-1df2-42fb-8389-2c6a13a8511b.png)

### Observed Behavior
Page looks blank with the tabs along the top. Have to click one of the tabs to get information to show. 
![image](https://user-images.githubusercontent.com/5022496/185924959-f3950e17-631b-4fc0-8c32-3b7fec984763.png)

**Comment by glennmatthews** [comment]
Thanks for the report. I can confirm this bug.
