### ISSUE TITLE
Plugin drop-down not visible without staff/superuser status

### ISSUE THREAD

**Issue by naga293tach** [nautobot/nautobot#2270]
### Environment
* Python version: 3.6
* Nautobot version:3.9

### Steps to reproduce
* Install plugins whose menu items do not require any permissions. 
*  Hide restricted UI enabled or disabled did not have any effect

### Expected Behavior
* User must be able to access plugins from the plugin drop-down displayed on the nav bar without superuser/staff status. 

### Observed Behavior
 * The plugin drop down is not displayed for users who do not have either staff or superuser status.

**Comment by glennmatthews** [comment]
This is probably a change resulting from #1844.

**Comment by glennmatthews** [comment]
Menus and menu items that have empty permissions (i.e. no restrictions) should always be rendered regardless of user permissions.

**Comment by glennmatthews** [comment]
Looks like #2279 fixes this as well.
