### ISSUE TITLE
Add docs linting rule to disallow relative directory links

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#2273]
### Proposed Changes

Per https://github.com/mkdocs/mkdocs/issues/1854, `mkdocs` only validates file-relative links (`../installation/index.md`) and by design does *not* validate directory-relative links (`../installation/`). I'm working on a PR to fix our existing documentation links to follow the validated standard. But it would be very useful to add a docs linting rule to detect and disallow directory-relative links so that they don't creep back in inadvertently.

### Justification

Let's use tooling to enforce that our documentation follows best practices and avoid broken links in our docs.

**Comment by smk4664** [comment]
I am finishing up a markdownlint Custom Rule to flag these, would you mind assigning this to me?
