### ISSUE TITLE
Import/Export: Identify Solution for Generic Import/Export (Spike)

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2276]
### TODO

- Research 3rd-party libraries that could be leveraged to support this
    - Actively maintained, compatible licensing
    - _Or_ should we implement our own because it will be lighter weight/more maintainable
    - EX: https://github.com/django-import-export/django-import-export
- Supports generic foreign keys
- Round-trippable (as long as the export is complete you should be able to import without modification)
- Currently CSV is supported and should be maintained, YAML (because of device type import)
- Bulk updating (should be called out but does need to be implemented at present, let's not make it harder on ourselves)

### Outcome

- Library (internal or 3rd party) is chosen (internal does not have to be implemented and can be created as a blocking requirement for #851)

**Comment by jathanism** [comment]
Notes and findings here: https://github.com/nautobot/nautobot/discussions/2502

**Comment by jathanism** [comment]
- We will use DRF parser/renderers so that the same serializers can be used for import/export
- Bulk import will be supported by way of a different content-type (parser)
- Formats
  - [CSV](https://github.com/mjumbewu/django-rest-framework-csv)
  - [YAML](https://github.com/jpadilla/django-rest-framework-yaml)
- Care needs to be taken that paginated outputs and nested representations are flattened

**Comment by jathanism** [comment]
## Implementation

- We will use `[djangorestframework-csv](https://github.com/mjumbewu/django-rest-framework-csv)`
- The renderer `rest_framework_csv.renderers.PaginatedCSVRenderer` must be used 
    - This returns the current page of results without the `next`, `previous`, `count`

## Nested object representations

- By default these are flattened and indexed with dotted notation
    - (e.g. `Status.content_types` gets exploded into `content_types.0`, `content_types.1`, 
    - This is not desirable. We want flat representations as a comma-separated string e.g.
        - `[``"``dcim.device``"``,` `"``dcim.interface``"``]` becomes…
        - `"``dcim.device,dcim.interface``"` in a CSV field
- Bulk import done using `bulk_create` (or `bulk_update`) existing API endpoints and should “just work” but this needs to be asserte4d.
    - This is done using the `rest_framework_csv.parsers.CSVParser` 
- Custom fields (being a nested representation) need to be accounted for
    - Current implementation is 1 header per e.g. `cf_{custom_field.slug}`

## Models

- Remove `csv_headers` attribute
- Remove `to_csv()` method

## Views

- Remove `queryset_to_csv()` method
- The correct API call needs to be accounted for to export ALL objects via CSV in keeping with current UI behaviors.

**Comment by jathanism** [comment]
Created issue https://github.com/nautobot/nautobot/issues/2569 to track.
