### ISSUE TITLE
Test Fixtures: Region, Site, Location, Rack, Device Type, Manufacturer, Platform, Role

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2282]

**Comment by gsnider2195** [comment]
I collapsed a lot of test setup data from the tests in `dcim.tests.test_filters` so you may be able to leverage that data for this issue. Take a look at [common_test_data](https://github.com/nautobot/nautobot/blob/825bd1f62a5906dceb8c09ac386f12b8f625a49f/nautobot/dcim/tests/test_filters.py#L106)

**Comment by bryanculver** [comment]
`Device` and `Interface` will require a lot more legwork to implement. Moving to future backlog.

Majority implemented via #2540, #2594.
