### ISSUE TITLE
No requests possible with OpenAPI Documentation in Nautobot 1.4

### ISSUE THREAD

**Issue by netgitdom** [nautobot/nautobot#2289]
### Environment
* Python version: 3.7.13
* Nautobot version: v1.4.1b1
* Docker version: v4.10.1

### Steps to Reproduce
1. invoke start (to start Nautobot with docker)
2. Open API Documentation in Browser (Chrome)
3. Navigate to some API Call, e.g. http://localhost:8080/api/docs/#/api/api_ipam_vrfs_list
4. Use "Try This Out" to get VRFs via API Call

### Expected Behavior
Successful API Call with List of VRFs

### Observed Behavior
I´ll get a 404 Error.

It seems to me, that die "Request URL" is wrong:
Under the "Responses" bar I see the URL with 2 x "api" in the path.
http://localhost:8080/api/api/ipam/vrfs/

<img width="426" alt="image" src="https://user-images.githubusercontent.com/25263529/186190014-528962bd-aa7b-45e1-bbdf-7f50b0679ed4.png">

Maybe this is the reason for the failed request. 

Regards

**Comment by glennmatthews** [comment]
Duplicate of #2232, fixed in 1.4.1.

**Comment by bryanculver** [comment]
@netgitdom Your Nautobot version listed is `v1.4.1b1` but as @glennmatthews pointed out this does appear to be a duplicate of #2232 which should have been fixed in 1.4.1.

Which Docker tag of Nautobot are you using?

**Comment by netgitdom** [comment]
I followed the guide from the documentation ( http://localhost:8080/static/docs/development/getting-started.html ) I cloned the GitHub repo and started it via "invoke start".
I changed nothing on the configuration and honestly, I don't find any tag on which version to use for docker. Can you guide me to the file where I can find it ?

**Comment by sirtux** [comment]
I tried it on 1.4.1 in a "normal install" and not docker and can confirm it works here.

**Comment by netgitdom** [comment]
So it is something in my environment.
Tanks for the feedback, I´ll close this issue :)
