### ISSUE TITLE
Plugins Allow To Append to Core Menu Items

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#2301]
### As ...

P.D. - Plugin Developer

### I want ...

With the explosion of menu items across the board, it may be good to allow plugin authors to add their Plugin menu to a core model. Such as the Circuit Maintenance plugin it would be terrific to be able to publish all of the menu items underneath Circuit which has plenty of space available.

### So that ...

The menu can be cleaned up some and allow for plugins that pertain to a specific area such as Circuits.

### I know this is done when...

- When I can put plugin menu items underneath existing menu items such as Circuits.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [X] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- ?

**Comment by glennmatthews** [comment]
This should be possible already?

**Comment by glennmatthews** [comment]
https://nautobot.readthedocs.io/en/stable/development/navigation-menu/#modifying-existing-menu
