### ISSUE TITLE
Include hint to worker logs whenever a job exits due to an Exception

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot#2305]
### As ...

Austin - Network Automation Engineer

### I want ...

it to be evident that the full stack trace for job exceptions can be found in the worker logs (see https://github.com/nautobot/nautobot-plugin-golden-config/issues/337 for an issue where this caused extraneous troubleshooting steps).

### So that ...

I don't spend more time troubleshooting than needed.

### I know this is done when...

an unforeseen exception in a job causes a failure log message that tells the user to look into the worker logs.

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [X] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

None

### External Dependencies

None

**Comment by glennmatthews** [comment]
relates to #765

**Comment by bryanculver** [comment]
@gsnider2195 @jathanism was this addressed in #765?

**Comment by jathanism** [comment]
> @gsnider2195 @jathanism was this addressed in #765?

That is correct!

**Comment by bryanculver** [comment]
Closed via #765
