### ISSUE TITLE
Change custom field results in error when you attempt to update an object

### ISSUE THREAD

**Issue by schreyack** [nautobot/nautobot#231]
### Environment
* Python version: Sandbox
* Nautobot version: Sandbox

### Steps to Reproduce
1. Add a custom field 
2. Update an object and put some data in the custom field
3. Go back and now *change* the name of the custom field
4. Now go and try to update the object you will get this error:
5. Unknown field name 'test' in custom field data.

### Expected Behavior
When I changed the name of the custom field, I should have gotten a screen similar to deleting a custom field that warned me and/or updated the existing fields.

### Observed Behavior
Updating the custom field worked with no warnings or errors, but then when you go to edit the object using that custom field you get the error.

**Comment by glennmatthews** [comment]
Thanks for the report! Can you confirm whether this is the same issue described in #137? It will most likely be addressed by PR #208 in any case. :-)

**Comment by schreyack** [comment]
Oh, basically the same.  This just extends the notion that if you try to update that object, it will fail.

**Comment by lampwins** [comment]
Yes, I see this as the same behavior as #137. We have decided for now that changing the name (or type) of a custom field will not be allowed. This is something we may revisit later.
