### ISSUE TITLE
Drop Python 3.7 Support

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2316]
### Proposed Changes
Drop Python 3.7 support.

### Justification
3.7 stops receiving security fixes in July 2023. Dependent libraries may drop support earlier but commonly not soon after.

### TODO

- [x] Remove publish of package & container support
- [x] Switch default container image to newer version (doesn't have to be 3.8)

**Comment by itdependsnetworks** [comment]
Perhaps as an alternate to this, let's just define the process and put this conversation to bed. Something *like* this could be good.

* In the immediate release after Python security will no longer be maintained, Nautobot support will be removed
* The removal will be in semver Minor versions
* They will be announced in the release notes

**Comment by glennmatthews** [comment]
Done in #3554.
