### ISSUE TITLE
Reference to Deleted Jobs

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot#2324]
### Environment
* Nautobot version (Docker tag too if applicable): 1.3.10
* Python version: 3.7
* Database platform, version: postgres
* Middleware(s):

### Steps to Reproduce
1. Run a job
2. Delete the job (not the job run instance, but actual job)
3. Go to front page
4. Click on job run instance, and observe a 404

### Expected Behavior

A 2XX page instead of a 4/5XX page

### Observed Behavior

<img width="832" alt="image" src="https://user-images.githubusercontent.com/9260483/187045280-3d81fa20-4932-4272-b29e-50077e58f525.png">

**Comment by glennmatthews** [comment]
Appears to be a cacheops issue. The `JobResult.job_model` is automatically set to `None` after deleting the Job, but cacheops is making Django think that it is still set. Running `cacheops.invalidate_all()` makes the error go away.
