### ISSUE TITLE
Circuit Termination with A and Z Swap broken with 1.3.x

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot#2326]
### Environment
* Nautobot version (Docker tag too if applicable): 1.3.1
* Python version: 3.8
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Create a Circuit with two terminations
2. Click the Swap termination button.

### Expected Behavior
The terminations will swap sides.

### Observed Behavior
![image](https://user-images.githubusercontent.com/17092348/187055955-42838f02-f42a-46a3-952b-a03c5be5d6a8.png)
Server Error: Circuit has no field named 'termination__'

**Comment by smk4664** [comment]
Notice the `termination__` is two underscores. In order to avoid a Unique Constraint issue when performing the swap, we set the term_side to `_`, but  when we call save, it is getting picked up by signals.py where the circuit gets filtered by `termination__`:

```
    fields = {
        "last_updated": timezone.now(),
        f"termination_{instance.term_side.lower()}": instance.pk,
    }
    Circuit.objects.filter(pk=instance.circuit_id).update(**fields)
```

**Comment by smk4664** [comment]
Also, unfortunately there are no tests for the `CircuitSwapTerminations`, so this did not get caught by tests.

**Comment by glennmatthews** [comment]
Looks to have been introduced by #1144. Appears that a similar regression was fixed in NetBox by https://github.com/netbox-community/netbox/commit/a4955b420a4b3b06f9caf14ff71d9f8329c13c3b.
