### ISSUE TITLE
Change Log tab missing in device component detail views

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#2330]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.2b1
* Python version:
* Database platform, version: MySQL
* Middleware(s): n/a

### Steps to Reproduce
1. Create a device with components (interfaces, power ports, console ports, etc - all components appear to be affected)
2. Navigate to the device detail view, then to the appropriate device component list view (interfaces, power ports, etc.), then click on an individual component (interface, power port, etc.) in the table, e.g. http://localhost:8080/dcim/console-ports/8b5d0e98-8ed9-4d93-8451-68202fc8253a/

![image](https://user-images.githubusercontent.com/5603551/187236121-4259316a-3410-495c-bb61-82a8ed6f44be.png)

### Expected Behavior

"Change Log" tab to be included in the page.

### Observed Behavior

"Change Log" tab is missing, however the changelog view does exist as you can manually enter the URL such as http://localhost:8080/dcim/console-ports/8b5d0e98-8ed9-4d93-8451-68202fc8253a/changelog/ in order to view it.

This is probably because the various device component models do not actually inherit from the base `ChangeLoggedModel` mixin class at present, and so are lacking an `instance.get_changelog_url` method.

**Comment by glennmatthews** [comment]
May be a regression resulting from #2049. See also #1424.

**Comment by lampwins** [comment]
Let's bite the bullet and turn these into proper change-logged models. For the migrations to do that, let's set the timestamps of the component's device timestamp. In this context, it is less confusing than using the timestamp of when the migration is run.
