### ISSUE TITLE
Secrets pulled from text file may include leading/trailing whitespace, including newlines

### ISSUE THREAD

**Issue by morp86** [nautobot/nautobot#2338]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.1
* Python version: 3.2.0
* Database platform, version: Postgress 14.5
* Middleware(s):

### Expected Behavior

Authentication to GIT repo working as expected. Cloning repo.

### Observed Behavior

Authentication failure.
Cmd('git') failed due to: exit code(128) cmdline: git fetch -v origin stderr: 'fatal: credential url cannot be parsed:

Update:
This issue was caused by creating the txt files using VI. As recommended by Glenn M, create the files using echo -n "My Secret String" > my_text_file.txt.

**Comment by glennmatthews** [comment]
Thanks for the report. We've talked about modifying/enhancing this feature to automatically strip leading/trailing whitespace from the raw string read from the text file, so as to avoid exactly this sort of issue. I think the number of cases where a valid Secret **does** want to retain such whitespace will be vanishingly small.
