### ISSUE TITLE
Possible regression with IPAddress

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#234]
### Environment
* Python version: 3.7.9
* Nautobot version: 1.0.0b2 (develop branch)

### Steps to Reproduce
1. In a nautobot shell `nautobot-server nbshell` try:

```python
from nautobot.ipam.models import IPAddress
from netaddr import IPAddress as NetAddrIPAddress
netaddr_ipaddress = NetAddrIPAddress('192.168.1.1')
IPAddress.objects.create(address=netaddr_ipaddress)
```

### Expected Behavior

An IPAddress object is created.  In previous versions of Nautobot (1.0.0b1) this worked, I also confirmed this works in NetBox:

```python
from ipam.models import IPAddress
from netaddr import IPAddress as NetAddrIPAddress
netaddr_ipaddress = NetAddrIPAddress('192.168.1.1')
IPAddress.objects.create(address=netaddr_ipaddress)
```

### Observed Behavior

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 445, in create
    obj = self.model(**kwargs)
  File "/opt/nautobot/nautobot/ipam/models.py", line 822, in __init__
    self._deconstruct_address(address)
  File "/opt/nautobot/nautobot/ipam/models.py", line 833, in _deconstruct_address
    broadcast = address.broadcast if address.broadcast else address.network
AttributeError: 'IPAddress' object has no attribute 'broadcast'
```

**Comment by jathanism** [comment]
You have to use `netaddr.IPNetwork` objects. In b3 they are all the same underlying field types and `netddr.IPAddress` objects are no longer used . 

This was not the case before b3. 

You can also just use a string. Can you please confirm using a string works? If so, assuming we have docs that refer to these, let's revise them.

**Comment by nniehoff** [comment]
Good to know.  String does work, doesn't look like this is in the docs, but it's in some code we use internally.  We do something similar to:

```python
subnet = netaddr.IPNetwork('192.168.2.0/30')
IPAddress.objects.create(address=subnet[0])
```

Looking at the code this would make sense, but looking deeper at the code indexing a `netaddr.IPNetwork` object (i.e. `subnet[0]`) returns an `netaddr.IPAddress` type.  So the above code becomes:

```python
subnet = netaddr.IPNetwork('192.168.2.0/30')
IPAddress.objects.create(address=netaddr.IPNetwork(subnet[0]))
```

or you just use string... Anyway, as long as this is intended I'm good if you want to close this issue.

**Comment by jathanism** [comment]
> Good to know. String does work, doesn't look like this is in the docs, but it's in some code we use internally. We do something similar to:
> 
> ```python
> subnet = netaddr.IPNetwork('192.168.2.0/30')
> IPAddress.objects.create(address=subnet[0])
> ```
> 
> Looking at the code this would make sense, but looking deeper at the code indexing a `netaddr.IPNetwork` object (i.e. `subnet[0]`) returns an `netaddr.IPAddress` type. So the above code becomes:
> 
> ```python
> subnet = netaddr.IPNetwork('192.168.2.0/30')
> IPAddress.objects.create(address=netaddr.IPNetwork(subnet[0]))
> ```
> 
> or you just use string... Anyway, as long as this is intended I'm good if you want to close this issue.

With all due respect, this internal code is a heavy anti-pattern. We shouldn't be using indexing on `IPNetwork` objects.

Either of these works:
```
subnet = netaddr.IPNetwork('192.168.2.0/32')
IPAddress.objects.create(address=subnet)
```

This is preferred, because it's just strings:

```
IPAddress.objects.create(address='192.168.2.0/32')
```

So yeah, just use strings. :)
