### ISSUE TITLE
Docs link in the footer of Nautobot UI returns 404

### ISSUE THREAD

**Issue by jlixfeld** [nautobot/nautobot#2341]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.1
* Python version: 3.10.5
* Database platform, version: Postgres
* Middleware(s): 

### Steps to Reproduce
1. `nautobot-server runserver`
2. browser to nautobot homepage, ie: `http://127.0.0.1:8000`
3. click "Docs" link on right side of footer

### Expected Behavior
Redirect to the intended documentation page.

### Observed Behavior
404
'docs/index.html' could not be found
request URL: http://127.0.0.1:8000/static/docs/index.html

**Comment by smk4664** [comment]
@jlixfeld Static files are not served by Django runserver by default, as this should be handled by your webserver (apache, nginx, etc.). You will either need to run with `DEBUG = True` or `nautobot-server runserver --insecure`.  This is only used for testing though, in Production you will want to follow the Nautobot install instructions.

**Comment by sirtux** [comment]
@smk4664 Even that this issue persists, just tested on 1.3.10 and 1.4.1, the docs are not part of the files collect-static writes, as it seems.

**Comment by smk4664** [comment]
@sirtux Is this when installing Nautobot through pip or downloading the repo?  The docs are not included in the static within the repo. You can run `invoke build-and-check-docs` in order to build them locally.

**Comment by smk4664** [comment]
I was going to comment that they should be in the package already, but I don't see them, so perhaps something is broken.

**Comment by glennmatthews** [comment]
Confirmed that the files are missing from the package.
