### ISSUE TITLE
Read the docs - Link returns 404

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot#2344]
### Environment
RTD https://nautobot.readthedocs.io/en/stable/administration/nautobot-server/#dumpdata 

### Steps to Reproduce
1. https://nautobot.readthedocs.io/en/stable/administration/nautobot-server/#dumpdata
2. <img width="925" alt="image" src="https://user-images.githubusercontent.com/26559188/187544185-f22eb604-b2d5-4712-84ec-30d08606b8b7.png">
3. url returned https://nautobot.readthedocs.io/en/stable/latest/installation/migrating-from-postgresql/#export-data-from-postgresql

### Expected Behavior
200 response & proper link

### Observed Behavior
404 and dead link

**Comment by smk4664** [comment]
This was resolved in #2303.

**Comment by glennmatthews** [comment]
Confirmed, this was fixed in #2303.
