### ISSUE TITLE
Multi select custom field gets cleared on bulk edit of different field

### ISSUE THREAD

**Issue by slappey-ibkr** [nautobot/nautobot#2353]
While bulk editing multiple device records I noticed my multi select custom field list was being emptied even though I did not make any changes to it in the bulk edit form.  The multi select form field is essentially evaluating as changed when no values are selected in the bulk edit form which then overrides the db field with an empty list.  I fixed this in my lab by changing line 1014 in core/views/generic.py from `not in (None, "")` to `not in (None, "", [])`.

https://github.com/nautobot/nautobot/blob/develop/nautobot/core/views/generic.py#L1014

### Environment
* Nautobot version (Docker tag too if applicable): 1.2.9
* Python version: 3.6.8
* Database platform, version: postrges
* Middleware(s): 

### Steps to Reproduce
1.  Create a multi select custom field, assign it to dcim | device content type, populate it with data.
2.  Bulk edit multiple device records. Do not change the multi select field, change a different field.  Click save.
3.  View the change log.

### Expected Behavior

The field I changed in the bulk edit form should be changed on the device record, not the multi select field which I did not change.  The multi select custom field list should not be emptied when you make no changes to the bulk edit form.

### Observed Behavior

Both the field I changed and the multi select field were changed.  The multi select field list was emptied. 

<img width="890" alt="nautobot-bug-step-1" src="https://user-images.githubusercontent.com/84326667/187958339-dddaf830-b92f-4ec5-8b57-91cf37611f20.PNG">

<img width="888" alt="nautobot-bug-step-2" src="https://user-images.githubusercontent.com/84326667/187958368-23cb0b0a-555e-47b6-a33b-fc0f90cd576f.PNG">

### Fix

Inside BulkEditView in core/views/generic.py:

*Change from:*

```
                            # Update custom fields
                            for field_name in form_custom_fields:
                                # 2.0 TODO: #824 when we use slug in obj.cf we can just do obj.cf[field_name[3:]]
                                if field_name in form.nullable_fields and field_name in nullified_fields:
                                    obj.cf[form_cf_to_key[field_name]] = None
                                elif form.cleaned_data.get(field_name) not in (None, ""):
                                    obj.cf[form_cf_to_key[field_name]] = form.cleaned_data[field_name]
```

*Change to:*

```
                            # Update custom fields
                            for field_name in form_custom_fields:
                                # 2.0 TODO: #824 when we use slug in obj.cf we can just do obj.cf[field_name[3:]]
                                if field_name in form.nullable_fields and field_name in nullified_fields:
                                    obj.cf[form_cf_to_key[field_name]] = None
                                elif form.cleaned_data.get(field_name) not in (None, "", []):
                                    obj.cf[form_cf_to_key[field_name]] = form.cleaned_data[field_name]
```

**Comment by glennmatthews** [comment]
Thanks for the report, and for the proposed fix!
