### ISSUE TITLE
Add support to Napalm vars for env var retrieval

### ISSUE THREAD

**Issue by susanhooks** [nautobot/nautobot#2354]
### Proposed Changes
I would see if we can add to the Napalm variables in settings.py to allow them to be retrieved as environment variables. 

### Justification
This would be useful for Golden Config/nautobot-nornir which offer environment variables as an option for Napalm secrets to retrieve config.

**Comment by bryanculver** [comment]
@susanhooks Are you thinking that a setting set in `settings.py` is exposed to plugins/the app as an environment variable?

**Comment by susanhooks** [comment]
@bryanculver I got some further clarification in slack, I misunderstood how it was working. Closing the issue.
