### ISSUE TITLE
Include contract number/code along with devices, both for procurement but also for support.

### ISSUE THREAD

**Issue by itheodoridis** [nautobot/nautobot#2368]
### As ...

Mary - Manager

### I want ...

to include contract number/code along with devices, both for procurement but also for support.

### So that ...

Network teams can lookup and verify which devices are covered by which contract.

### I know this is done when...

I can supply contact number/code for procurement and support for devices and search devices based on the contract numbers as criteria for the search.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [X] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [X] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [X] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

Additional fields should be created per device.
Contracts may be modeled as well and be supplied in the form of a drop down list to choose from per device.

**Comment by Kircheneer** [comment]
I believe that the [Device Lifecycle Management Plugin](https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt) might be what you are looking for?

**Comment by itheodoridis** [comment]
I wasn't after an entire plugin, but an integration of an additional data model. I will look into it but for the moment I am sticking with this. Thank you for the reference!

**Comment by nkallergis** [comment]
Not to push your finger or anything but this specific plugin:
a) does exactly what you need, it just adds a couple of additional data models (EoX, contracts, etc)
b) has minimal maintenance overhead (literally two lines of "code")

As @Kircheneer already suggested, I also encourage you to try it and see for yourself!

**Comment by itheodoridis** [comment]
Well if you know me (which you do), since @Kircheneer 's suggestion I have already communicated internally (where the request came from, interesting don't you think? They are making requests ;) ) that such a plugin exists and have already announced and program my intention to test it in a lab instance (my lab instance which means a full docker-compose setup with access to the real network).
So yes I will test it but the fact remains that this means also integrating a plugin with other functionalities that not everyone agrees are needed (Software Lifecycle and CVE tracking which are already covered elsewhere) and adding on a few dependencies that could probably be avoided. So getting a lot more than what you bargained for in every direction. 
Like I said, I will test it anyway and get back to you. Getting more than we bargained for, happens a lot strangely.. ;)
So was that a no? :)
I 'll have news soon.

**Comment by itheodoridis** [comment]
I am integrating the plugin in a lab environment as I described above. However I get warnings in the log that I never got before, I am guessing it's coming from plugin functions. Those are issued both by nautobot and the celery worker.
Here is an example below:
```
nautobot-docker-nautobot-1         | 09:38:27.138 WARNING nautobot.utilities.deprecation :
nautobot-docker-nautobot-1         |   Class CustomFieldModelForm is deprecated, and will be removed in a future Nautobot release. Instead of deriving HardwareLCMForm from CustomFieldModelForm, please migrate your code to inherit from class CustomFieldModelFormMixin instead.
```

**Comment by Kircheneer** [comment]
This is only indirectly related to Nautobot itself and is an issue that should go onto the repository for the plugin instead. In short: Some Nautobot internals were deprecated and any uses of those need to be switched over to a new pattern. You, as a user, can safely ignore these warnings, functionality is not impacted in any way.

**Comment by itheodoridis** [comment]
Thank you Leo I realize that, I was making an indirect point.
My initial feature request is to have a contract number as a model integrated in nautobot. I got a suggestion to use another plugin.
I have responded that a use of an entire plugin for a model or field creates a lot of overhead such as compatibility issues or having to rely on the maintenance of that plugin. I believe this warning just made my point.
I will create an issue on that repo as well.
About this issue here, I will conclude my evaluation of the proposal you and Nikos made to use the plugin and respond in a few hours time max.

**Comment by itheodoridis** [comment]
It turns out they know: https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/issues/101.
That takes care of that, I will get back to you soon.

**Comment by itheodoridis** [comment]
We have concluded testing, the plugin was accepted as a solution so I am going to integrate it in our systems. I would have preferred a more minimal approach as I mentioned but .. that's how it is. So moving on. Closing this one.
Thank you for your help.
