### ISSUE TITLE
Allow API tokens to have object level permissions

### ISSUE THREAD

**Issue by grahamneville** [nautobot/nautobot#2373]
### As ...

Austin - Network Automation Engineer

### I want ...

To allow object level permissions on each API token so they can be restricted in there use.

### So that ...

A token doesn't automatically inherit the users permissions but is more locked down.

### I know this is done when...

I can create a token and assign the token permissions in the same way users and groups are given permissions.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [X] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by grahamneville** [comment]
When creating the token the permissions to choose from when applying to an API tokeb should only been shown to the same has what the user has been given.

**Comment by lampwins** [comment]
Unfortunately, this would take too much effort than we are currently willing because so much of our permission enforcement and related feature sets is directly tied to users.
