### ISSUE TITLE
Job Execution -> Job Result Page Not the default any more

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#2378]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.2
* Python version: 3.9
* Database platform, version: Postgres, 13
* Middleware(s): None

### Steps to Reproduce
1. Upgrade Nautobot instance
2. Install Example Plugin
3. Navigate to Jobs and enable Example Logging Job
4. Execute the Example Logging Job
5. Get redirected to page, with no parameters

### Expected Behavior

Expected to be sent to the tab of JobResults page `?tab=main`

### Observed Behavior

Seeing just the url without the tab

**Comment by jvanderaa** [comment]
When trying to navigate to the JobResult URL, it automatically adds the `?tab=main`, but does not automatically go there when clicking execute.

**Comment by jathanism** [comment]
Confirmed. Thanks @jvanderaa

**Comment by jathanism** [comment]
There's definitely a difference between 

`/extras/job-results/:uuid/` (works as expected)

And 

`/extras/jobs/results/:uuid/` (shows nothing unless you click one of the nav tabs)
