### ISSUE TITLE
Nautobot Version Management Command

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot#2386]
### As ...

Patti - Platform Admin

### I want ...

A simple django management command to retrieve the Nautobot version from environment.

### So that ...

I can quickly confirm the expected version in a python environment 

### I know this is done when...

- I created a management command that will send the version to STDOUT

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [X] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

None

### External Dependencies

None

**Comment by smk4664** [comment]
Does `nautobot-server --version` achieve this already?

**Comment by whitej6** [comment]
I felt like I tried it but may have only done version. Can close

**Comment by smk4664** [comment]
It looks like `nautobot-server --version` is only documented in the installation docs and not on the Nautobot-Server docs.

https://nautobot.readthedocs.io/en/stable/installation/nautobot/#verify-your-nautobot-installation

**Comment by smk4664** [comment]
So, `nautobot-server version` will only show the django version. This is a built-in django manage.py command.
