### ISSUE TITLE
core getter does not honor NAPALM_TIMEOUT value

### ISSUE THREAD

**Issue by eneiford** [nautobot/nautobot#2393]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.2
* Python version: 3.9.13
* Database platform, version: postgres 12.8
* Middleware(s):

### Steps to Reproduce
1. set NAPALM_TIMEOUT `NAPALM_TIMEOUT = int(os.getenv("NAUTOBOT_NAPALM_TIMEOUT", 120))`
2. click on device configuration tab 
3. blank screen returns with no errors and no config after 30 seconds
4. set "conn_timeout" in platform NAPALM arguments resulting in no change in behavior

### Expected Behavior
configuration to appear (or an error)

### Observed Behavior
no configuration or error

---
**_NOTE_** 
LLDP Neighbors getter does populate (which returns data in less than 30 seconds)
I had to modify nautobot_plugin_nornir to increase timeout for device so nautobot_golden_config backup would succeed on device - it certainly will not return data within the default 30 seconds
neighboring devices with smaller configurations all populate properly as long as they return before the timeout
older version of nautobot (built in same infra) retrieves configuration after about 50 seconds of clicking the device configuration tab
---
<img width="736" alt="image" src="https://user-images.githubusercontent.com/19722607/189265684-fdbd359b-c062-4dec-bec8-9d67457eb60b.png">

**Comment by bryanculver** [comment]
Thanks for the submission @eneiford. This is being passed into the derived NAPALM driver relevant to the specified platform.

Can you let us know which device platform you're connecting to? Also, can you find out if your browser console is receiving any errors as well?

**Comment by eneiford** [comment]
driver is nxos_ssh.  I will review the browser console when I am able.  I am not getting any logs at all in the container.

**Comment by eneiford** [comment]
i am not getting any browser console notifications when the configuration
fails to return.  I can flip to the LLDP Neighbors tab and the return
values will populate, but the configuration will not.  Calls to the
endpoint /api/dcim/devices/{mydev.id}/napalm/?method=get_config return the
following error:

{
"get_config": {
"error": "Method get_config failed: \nPattern not detected:
'{router-name}#' in output.\n\nThings you might try to fix this:\n1.
Explicitly set your pattern using the expect_string argument.\n2. Increase
the read_timeout to a larger value.\n\nYou can also look at the Netmiko
session_log or debug log for more information.\n\n"
}
}

**Comment by bryanculver** [comment]
@eneiford #2574 made related changes to this, which was released in 1.4.6. Have you checked out a recent release of Nautobot to see if this has been addressed?
