### ISSUE TITLE
Circuits: wrong display of A-Z termination site

### ISSUE THREAD

**Issue by david-kn** [nautobot/nautobot#2404]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.1
* Python version: 3.7.13
(tested also on demo instance)

### Steps to Reproduce
In Nautobot GUI to to Circuits:
1. Create a circuit
2. Add a termination side A (from any site, e,g. AMS01)
3. Add a termination side Z (from any other site, e.g. SIN01)

### Expected Behavior
To see both sites in a overview table of circuits ("/circuits/circuits/`) .

### Observed Behavior
Only A termination site is shown (see attached image) (btw. "old" circuits are displayed properly)

If only one termination (either A or Z) is set, then the overview table displays the one site correctly.

![image](https://user-images.githubusercontent.com/14314517/189615613-60eda1ce-9bcb-4c81-a53b-4c8dc76751de.png)

**Comment by glennmatthews** [comment]
Looks like yet another cacheops issue. If I filter the table (changing the queryset being used) the new termination shows up just fine. I suspect that running `nautobot-server invalidate all` will also fix the issue though I haven't tested this. Tagging #1721.
