### ISSUE TITLE
Copy button - not working for ip address

### ISSUE THREAD

**Issue by david-kn** [nautobot/nautobot#2406]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.1
* Python version: 3.7.13
(tested also on demo nautobot)

### Steps to Reproduce
1. Open any device object with IP address assigned in Nautobot GUI
2. Click on a "copy" button next to `Primary IP` address when hovering with mouse 

### Expected Behavior
The IP value should have been copied in clipboard.

### Observed Behavior
Nothing is copied (if a clipboard contained something before, it stays there without any change).

Probably the issues is due to fact that the IP address HTML element is missing the ID `ipv4` that is supposed to be used for element selection (see image) because the "copy" button works for device name though (in title) where element ID is properly defined.

btw. I didn't want to create two seperated issues for this topic / for another (un)expected behavior but are you aware that when the copy buton is used for a device name it copies tha device name + it adds a whitespace in front of and behind the name itself? The clipboard is NOT just the name itself (e.g. `ams01-dist-01`)

I would be nice to fix this and also extend in the future with already existing request: https://github.com/nautobot/nautobot/issues/1519 (just saying :-) )
![image](https://user-images.githubusercontent.com/14314517/189653292-f1d6fd1a-b266-46f7-9a5d-accd541a89c6.png)

### TODO
- Revert:
- https://github.com/nautobot/nautobot/pull/1833/files#diff-f0afa17f447ab2c1d36a0f264153145754fa67028968d3d9ff6ea103198b03beL161-R143
- https://github.com/nautobot/nautobot/pull/1833/files#diff-f0afa17f447ab2c1d36a0f264153145754fa67028968d3d9ff6ea103198b03beL182-R164

**Comment by glennmatthews** [comment]
Thanks for the report! Looks like this was broken by #1833.
