### ISSUE TITLE
Create Slimmed Dockerfile, ready for clustered deployment

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#242]
### Environment
* Python version: N/A
* Nautobot version: 1.0.0b3

### Proposed Functionality

Update Dockerfile to be ready for production like deployment onto services such as Docker-compose, Kubernetes, Nomad, Openshift, etc.

### Use Case

Build container base image for deployment onto clusters, and development system, ready for a production environment.

### Database Changes

None

### External Dependencies

Docker

**Comment by jvanderaa** [comment]
Should be assigned to @nniehoff

**Comment by jathanism** [comment]
Can you please add some more context about the why here?

**Comment by glennmatthews** [comment]
Is this different than #195?

**Comment by jvanderaa** [comment]
It is the issue for 195.
