### ISSUE TITLE
Add unit tests for ObjectDynamicGroupsView

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#2450]
### Proposed Changes

Add unit tests for ObjectDynamicGroupsView similar to [GetObjectChangelogViewTestCase](https://github.com/nautobot/nautobot/blob/954cdcf308459dae1f59b9232bfe5d9d52cec82d/nautobot/utilities/testing/views.py#L228)

### Justification

More test coverage for this new view

**Comment by glennmatthews** [comment]
No longer relevant after the recent enhancements to dynamic group caching and views.
