### ISSUE TITLE
Enhance `hyperlinked_object` Filter to Accept Display Text Property Name

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2454]
Enhance `hyperlinked_object` to let you specify the display text, something like `{{ record|hyperlinked_object("name") }}` would be pretty convenient.

_Originally posted by @glennmatthews in https://github.com/nautobot/nautobot/pull/2359#discussion_r975316651_

**Comment by glennmatthews** [comment]
Implemented by #2616
