### ISSUE TITLE
New filter form search box

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#2460]
### As ...

Nelly - Network Engineer

### I want ...

An always present search box in list views

### So that ...

I can always quickly type in a string value for a search that utilizes the `q` filter, without having to click the advanced filtering form and add an explicit filter.

### I know this is done when...

A search text field is always present in list views, next to the filter form button.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

None

### External Dependencies

None

**Comment by lampwins** [comment]
A part of #1998

**Comment by bryanculver** [comment]
@lampwins Just to confirm that this search box would be combined with the filters applied via the dynamic filter form.

**Comment by lampwins** [comment]
@bryanculver correct.
