### ISSUE TITLE
Importing Regions Successfully but shows odd parent/child region in success screen

### ISSUE THREAD

**Issue by scetron** [nautobot/nautobot#2463]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.2
* Python version: 3.8
* Database platform, version: postgres 13
* Middleware(s):

### Steps to Reproduce
1. Use CSV field to bulk import some regions
2. View success screen, but parent child relationship is incorrect
3.

### Expected Behavior

Correct Parent child relationships in the success screen

### Observed Behavior

![Screen Shot 2022-09-21 at 15 50 59](https://user-images.githubusercontent.com/10200477/191597509-6225cf16-3d40-4472-ba25-f3f4a310171d.png)

The parent child relationships of the regions that were import are shown in an odd order, this makes you think that the CSV import was malformed or otherwise incorrect, however checking the Regions page shows that the regions were correctly imported.

This is mostly cosmetic as the regions appear to be imported correctly.

**Comment by glennmatthews** [comment]
Region is going away in 2.0; it would be good though to check this with CSV import of `Location` records to see whether the different implementation there shows the same issue or not.

**Comment by glennmatthews** [comment]
Possibly related to #2516.
