### ISSUE TITLE
Jobs: misleading "sensitive variables or requiring approval" error message

### ISSUE THREAD

**Issue by u1735067** [nautobot/nautobot#2466]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.3
* Python version: 3.10
* Database platform, version: pgsql
* Middleware(s):

### Steps to Reproduce
1. Create a job having `has_sensitive_variables = True` (the default) but not `approval_required`
2. Navigate to the job to run it (▶)

### Expected Behavior
No alerts

### Observed Behavior
An alert:
``` This job is flagged as possibly having sensitive variables but is also flagged as requiring approval. One of these two flags must be removed before this job can be run.```

### Additional informations

https://github.com/nautobot/nautobot/blob/v1.4.3/nautobot/extras/templates/extras/job.html#L38-L44 : the test doesn't match the error message

**Comment by gsnider2195** [comment]
[extras/templates/extras/job.html](https://github.com/nautobot/nautobot/blob/825bd1f62a5906dceb8c09ac386f12b8f625a49f/nautobot/extras/templates/extras/job.html#L38) 

`if job_model.has_sensitive_variables or job_model.approval_required` 

should be 

`if job_model.has_sensitive_variables and job_model.approval_required`
