### ISSUE TITLE
GraphQL : Add custom fields as filter arguments

### ISSUE THREAD

**Issue by dgarros** [nautobot/nautobot#247]
### Environment
* Python version: 3.7
* Nautobot version: 1.0.0b2

### Proposed Functionality
Add support for custom fields in filter argument for all graphql types
Currently it's possible to define some arguments when querying a model, at the top level, but it's not possible to query by custom fields. 

if there is a custom field `type` defined under `Site`  model, it should be possible to search for cf_type
```graphql
{
  sites(cf_type: "ams") {
	id
        name
}
```
### Use Case
Similar to the API, it would be good to be able to search by custom fields with `cf_<custom_field_name>`

### Database Changes
No

### External Dependencies
No

**Comment by jathanism** [comment]
Fixed in #246
