### ISSUE TITLE
Child location's slug is autogenerated using parent's UUID rather than slug

### ISSUE THREAD

**Issue by alhogan** [nautobot/nautobot#2470]
### Environment
* Nautobot version (Docker tag too if applicable): v1.4.2
* Python version: 3.8
* Database platform, version: PostgreSQL v13

### Steps to Reproduce
1. Create root location type
2. Create child location type of the root location type
3. Create root location
4. Create child location of the root location

### Expected Behavior
Child Location's slug auto generated using the parent location's slug

![Screen Shot 2022-09-22 at 10 25 28 AM](https://user-images.githubusercontent.com/98360253/191788181-eb8eb14e-ceaa-468b-9cf7-672811287a57.png)

### Observed Behavior
Child Location's slug auto generated using the parent location's UUID

![Screen Shot 2022-09-22 at 10 28 18 AM](https://user-images.githubusercontent.com/98360253/191788941-9923a1e2-be37-42ba-8ff1-e32e84d4ac1d.png)

**Comment by glennmatthews** [comment]
Appears to have been introduced by #2322. Any fix needs to be careful to not re-introduce #2311.
