### ISSUE TITLE
nautobot:1.3.10-py3.9 ---> ff1962d125a0 (v1.4.3) in GUI 

### ISSUE THREAD

**Issue by telescope40** [nautobot/nautobot#2471]
### Environment
* Nautobot version (Docker tag too if applicable): 1.3.10  Tag 1.3.10-py3.9
* Python version:py3.9
* Database platform, version: postgres PG_VERSION=14.5-1.pgdg110+1"
* Middleware(s):

### Steps to Reproduce
1. docker pull networktocode/nautobot:1.3.10-py3.9
2. Update docker-compose files to reflect new image 
3. docker-compose build / up 

### Expected Behavior
Nautobot version 1.3.10 not 1.4.3

**Comment by bryanculver** [comment]
Thanks for the report @telescope40. We've run across this before. Are you installing any plugins in your Docker compose files?

**Comment by telescope40** [comment]
Yes I am . These pre-existed prior to the issue.  The upgrade was in an effort to onboard the BGP & Firewall plugins both of which seemed to result in the image being unstable. The have been removed entirely from the plugin requirements  and config 

`nautobot_netbox_importer
nautobot_device_onboarding
nautobot_golden_config
nautobot-ssot
nautobot-chatops
nautobot_device_lifecycle_mgmt
nautobot_circuit_maintenance
nautobot_data_validation_engine
nautobot-plugin-chatops-panorama
`

**Comment by bryanculver** [comment]
Can you share your plugin requirements file?

I assume you're using: https://github.com/nautobot/nautobot-docker-compose

**Comment by jvanderaa** [comment]
@bryanculver you can assign me on this.

**Comment by jvanderaa** [comment]
Stems from the Nautobot Golden Config plugin, that needs to be pinned to a version that does not require >1.4.0 of Nautobot. 

https://github.com/nautobot/nautobot-plugin-golden-config/blob/develop/pyproject.toml#L37

**Comment by jvanderaa** [comment]
The latest version of Golden Config has requirements to use features introduced in 1.4 for a particular feature. 

To pin back to the previous release, change the requirements file (`plugin_requirements.txt`) to having:

```
nautobot-golden-config==1.1.3
```

**Comment by bryanculver** [comment]
If we can confirm this is using https://github.com/nautobot/nautobot-docker-compose then this should be addressed via https://github.com/nautobot/nautobot-docker-compose/issues/50

**Comment by telescope40** [comment]
Yes , I am using the Docker-Compose and replacing with nautobot-golden-config=1.1.3 does bring the build back down to 1.2.8. I am curious however , I did read the docker-compose will build the latest stable build but the image that is running 1.3.10. Anyway thanks for the quick help !

**Comment by telescope40** [comment]
An interesting follow up. When I reviewing one of the objects I am prompted with . I have reverted back to 1.2.8

`A database programming error was detected while processing this request. Common causes include the following:

 Database migrations missing - When upgrading to a new Nautobot release, the upgrade script must be run to apply any new database migrations. You can run migrations manually by executing nautobot-server migrate from the command line.

 Unsupported PostgreSQL version - Ensure that PostgreSQL version 9.6 or higher is in use. You can check this by connecting to the database using Nautobot's credentials and issuing a query for SELECT VERSION().`

**Comment by bryanculver** [comment]
@telescope40 This may have been due to migrations being applied when the container upgraded to 1.4.3.

Can you perform `nautobot-server showmigrations` or show the entries in the `django_migrations` DB table?

**Comment by telescope40** [comment]
See the nautobot-server migrations below , how would I check the django_migrations ? Should I just upgrade to the db to 9.6? 

`nautobot@790d156f72c2:~$ nautobot-server showmigrations
admin
 [X] 0001_initial
 [X] 0002_logentry_remove_auto_add
 [X] 0003_logentry_add_action_flag_choices
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
 [X] 0009_alter_user_last_name_max_length
 [X] 0010_alter_group_name_max_length
 [X] 0011_update_proxy_permissions
 [X] 0012_alter_user_first_name_max_length
circuits
 [X] 0001_initial_part_1
 [X] 0002_initial_part_2
 [X] 0003_auto_slug
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
database
 [X] 0001_initial
 [X] 0002_auto_20190129_2304
dcim
 [X] 0001_initial_part_1
 [X] 0002_initial_part_2
 [X] 0003_initial_part_3
 [X] 0004_initial_part_4
 [X] 0005_device_local_context_schema
 [X] 0006_auto_slug
 [X] 0007_device_secrets_group
django_celery_beat
 [X] 0001_initial
 [X] 0002_auto_20161118_0346
 [X] 0003_auto_20161209_0049
 [X] 0004_auto_20170221_0000
 [X] 0005_add_solarschedule_events_choices
 [X] 0006_auto_20180322_0932
 [X] 0007_auto_20180521_0826
 [X] 0008_auto_20180914_1922
 [X] 0006_auto_20180210_1226
 [X] 0006_periodictask_priority
 [X] 0009_periodictask_headers
 [X] 0010_auto_20190429_0326
 [X] 0011_auto_20190508_0153
 [X] 0012_periodictask_expire_seconds
 [X] 0013_auto_20200609_0727
 [X] 0014_remove_clockedschedule_enabled
 [X] 0015_edit_solarschedule_events_choices
extras
 [X] 0001_initial_part_1
 [X] 0002_initial_part_2
 [X] 0003_initial_part_3
 [X] 0004_populate_default_status_records
 [X] 0005_configcontext_device_types
 [X] 0006_graphqlquery
 [X] 0007_configcontextschema
 [X] 0008_jobresult__custom_field_data
 [X] 0009_computedfield
 [X] 0010_change_cf_validation_max_min_field_to_bigint
 [X] 0011_fileattachment_fileproxy
 [X] 0012_healthchecktestmodel
 [X] 0013_default_fallback_value_computedfield
 [X] 0014_auto_slug
 [X] 0015_scheduled_job
 [X] 0016_secret
 [X] 0017_joblogentry
 [X] 0018_joblog_data_migration
 [X] 0019_joblogentry__meta_options__related_name
 [X] 0020_customfield_changelog
 [X] 0021_customfield_changelog_data
ipam
 [X] 0001_initial_part_1
 [X] 0002_initial_part_2
 [X] 0003_remove_max_length
 [X] 0004_fixup_p2p_broadcast
 [X] 0005_auto_slug
nautobot_chatops
 [X] 0001_initial
 [X] 0002_commandlog_params1
 [X] 0003_params_to_params1
 [X] 0004_remove_params_rename_params1
nautobot_circuit_maintenance
 [X] 0001_initial
 [X] 0002_notification_secrets_out_of_db
 [X] 0003_improve_rawnotification
 [X] 0004_raw_md5
 [X] 0005_notificationsource__token
 [X] 0006_fake_migration_to_update_custom_fields
 [X] 0007_notificationsource_attach_all_providers
 [X] 0008_raw_binary
 [X] 0009_auto_20210916_1519
 [X] 0010_rawnotification_stamp
 [X] 0011_mysql
nautobot_data_validation_engine
 [X] 0001_initial
nautobot_device_lifecycle_mgmt
 [X] 0001_hardwarelcm
 [X] 0002_softwarelcm
 [X] 0003_service_contracts
 [X] 0004_validated_software_m2m
 [X] 0005_software_reporting
 [X] 0006_cvelcm_vulnerabilitylcm
 [X] 0007_softwareimagelcm
 [X] 0008_software_image_data_migration
 [X] 0009_software_remove_image_fields
nautobot_device_onboarding
 [X] 0001_initial
 [X] 0002_create_onboardingdevice
 [X] 0003_onboardingtask_label
nautobot_golden_config
 [X] 0001_initial
 [X] 0002_custom_data
 [X] 0003_auto_20210510_2356
 [X] 0004_auto_20210616_2234
 [X] 0005_json_compliance_rule
 [X] 0006_multi_repo_support_temp_field
 [X] 0007_multi_repo_support_convert_many
 [X] 0008_multi_repo_support_final
 [X] 0009_multiple_gc_settings_part_1
 [X] 0010_multiple_gc_settings_part_2
 [X] 0011_multiple_gc_settings_part_3
 [X] 0012_multiple_gc_settings_part_4
 [X] 0013_multiple_gc_settings_part_5
 [X] 0014_convert_sotagg_queries_part1
 [X] 0015_convert_sotagg_queries_part2
 [X] 0016_convert_sotagg_queries_part3
 [X] 0017_convert_sotagg_queries_part4
 [X] 0018_convert_sotagg_queries_part5
nautobot_plugin_chatops_panorama
 (no migrations)
nautobot_ssot
 [X] 0001_initial
 [X] 0002_performance_metrics
sessions
 [X] 0001_initial
social_django
 [X] 0001_initial (2 squashed migrations)
 [X] 0002_add_related_name (2 squashed migrations)
 [X] 0003_alter_email_max_length (2 squashed migrations)
 [X] 0004_auto_20160423_0400 (2 squashed migrations)
 [X] 0005_auto_20160727_2333 (1 squashed migrations)
 [X] 0006_partial
 [X] 0007_code_timestamp
 [X] 0008_partial_timestamp
 [X] 0009_auto_20191118_0520
 [X] 0010_uid_db_index
taggit
 [X] 0001_initial
 [X] 0002_auto_20150616_2121
 [X] 0003_taggeditem_add_unique_index
tenancy
 [X] 0001_initial
 [X] 0002_auto_slug
users
 [X] 0001_initial
virtualization
 [X] 0001_initial
 [X] 0002_virtualmachine_local_context_schema
 [X] 0003_vminterface_verbose_name
 [X] 0004_auto_slug`

**Comment by telescope40** [comment]
Thank you for taking the time to help me with these issues.

**Comment by telescope40** [comment]
@bryanculver 
`nautobot=# SELECT * FROM django_migrations;
 id  |               app               |                                       name                                        |            applied   
         
-----+---------------------------------+-----------------------------------------------------------------------------------+----------------------
---------
   1 | contenttypes                    | 0001_initial                                                                      | 2022-06-21 03:34:03.8
69831+00
   2 | contenttypes                    | 0002_remove_content_type_name                                                     | 2022-06-21 03:34:03.8
78191+00
   3 | auth                            | 0001_initial                                                                      | 2022-06-21 03:34:03.8
98486+00
   4 | auth                            | 0002_alter_permission_name_max_length                                             | 2022-06-21 03:34:03.9
14968+00
   5 | auth                            | 0003_alter_user_email_max_length                                                  | 2022-06-21 03:34:03.9
20896+00
   6 | auth                            | 0004_alter_user_username_opts                                                     | 2022-06-21 03:34:03.9
26668+00
   7 | auth                            | 0005_alter_user_last_login_null                                                   | 2022-06-21 03:34:03.9
32405+00
   8 | auth                            | 0006_require_contenttypes_0002                                                    | 2022-06-21 03:34:03.9
34137+00
   9 | auth                            | 0007_alter_validators_add_error_messages                                          | 2022-06-21 03:34:03.9
39866+00
  10 | auth                            | 0008_alter_user_username_max_length                                               | 2022-06-21 03:34:03.9
4554+00
  11 | auth                            | 0009_alter_user_last_name_max_length                                              | 2022-06-21 03:34:03.9
52475+00
  12 | auth                            | 0010_alter_group_name_max_length                                                  | 2022-06-21 03:34:03.9
59482+00
  13 | auth                            | 0011_update_proxy_permissions                                                     | 2022-06-21 03:34:03.9
65494+00
  14 | auth                            | 0012_alter_user_first_name_max_length                                             | 2022-06-21 03:34:03.9
72039+00
  15 | users                           | 0001_initial                                                                      | 2022-06-21 03:34:04.0
26983+00
  16 | admin                           | 0001_initial                                                                      | 2022-06-21 03:34:04.0
80861+00
  17 | admin                           | 0002_logentry_remove_auto_add                                                     | 2022-06-21 03:34:04.0
96902+00
  18 | admin                           | 0003_logentry_add_action_flag_choices                                             | 2022-06-21 03:34:04.1
0947+00
  19 | extras                          | 0001_initial_part_1                                                               | 2022-06-21 03:34:04.3
03683+00
  20 | tenancy                         | 0001_initial                                                                      | 2022-06-21 03:34:04.3
90989+00
  21 | dcim                            | 0001_initial_part_1                                                               | 2022-06-21 03:34:04.6
50475+00
  22 | circuits                        | 0001_initial_part_1                                                               | 2022-06-21 03:34:04.7
15107+00
  23 | circuits                        | 0002_initial_part_2                                                               | 2022-06-21 03:34:05.2
38886+00
  24 | circuits                        | 0003_auto_slug                                                                    | 2022-06-21 03:34:05.2
65411+00
  25 | database                        | 0001_initial                                                                      | 2022-06-21 03:34:05.2
74695+00
  26 | database                        | 0002_auto_20190129_2304                                                           | 2022-06-21 03:34:05.2
81651+00
  27 | dcim                            | 0002_initial_part_2                                                               | 2022-06-21 03:34:05.6
50907+00
  28 | ipam                            | 0001_initial_part_1                                                               | 2022-06-21 03:34:05.9
04301+00
  29 | extras                          | 0002_initial_part_2                                                               | 2022-06-21 03:34:06.5
9786+00
  30 | dcim                            | 0003_initial_part_3                                                               | 2022-06-21 03:34:10.5
81879+00
  31 | virtualization                  | 0001_initial                                                                      | 2022-06-21 03:34:11.4
49459+00
  32 | dcim                            | 0004_initial_part_4                                                               | 2022-06-21 03:34:16.3
53655+00
  33 | extras                          | 0003_initial_part_3                                                               | 2022-06-21 03:34:18.0
88974+00
  34 | extras                          | 0004_populate_default_status_records                                              | 2022-06-21 03:34:18.6
2017+00
  35 | extras                          | 0005_configcontext_device_types                                                   | 2022-06-21 03:34:18.7
45746+00
  36 | extras                          | 0006_graphqlquery                                                                 | 2022-06-21 03:34:18.7
63825+00
  37 | extras                          | 0007_configcontextschema                                                          | 2022-06-21 03:34:18.9
51752+00
  38 | extras                          | 0008_jobresult__custom_field_data                                                 | 2022-06-21 03:34:19.0
10554+00
  39 | extras                          | 0009_computedfield                                                                | 2022-06-21 03:34:19.1
22449+00
  40 | extras                          | 0010_change_cf_validation_max_min_field_to_bigint                                 | 2022-06-21 03:34:19.5
63838+00
  41 | extras                          | 0011_fileattachment_fileproxy                                                     | 2022-06-21 03:34:19.6
29641+00
  42 | extras                          | 0012_healthchecktestmodel                                                         | 2022-06-21 03:34:19.6
38027+00
  43 | extras                          | 0013_default_fallback_value_computedfield                                         | 2022-06-21 03:34:19.6
87689+00
  44 | extras                          | 0014_auto_slug                                                                    | 2022-06-21 03:34:19.9
36761+00
  45 | extras                          | 0015_scheduled_job                                                                | 2022-06-21 03:34:20.1
32604+00
  46 | extras                          | 0016_secret                                                                       | 2022-06-21 03:34:20.7
86063+00
  47 | dcim                            | 0005_device_local_context_schema                                                  | 2022-06-21 03:34:20.9
04754+00
  48 | dcim                            | 0006_auto_slug                                                                    | 2022-06-21 03:34:21.7
08209+00
  49 | dcim                            | 0007_device_secrets_group                                                         | 2022-06-21 03:34:21.8
11634+00
  50 | django_celery_beat              | 0001_initial                                                                      | 2022-06-21 03:34:21.8
53063+00
  51 | django_celery_beat              | 0002_auto_20161118_0346                                                           | 2022-06-21 03:34:21.8
79583+00
  52 | django_celery_beat              | 0003_auto_20161209_0049                                                           | 2022-06-21 03:34:21.8
98478+00
  53 | django_celery_beat              | 0004_auto_20170221_0000                                                           | 2022-06-21 03:34:21.9
07829+00
  54 | django_celery_beat              | 0005_add_solarschedule_events_choices                                             | 2022-06-21 03:34:21.9
16993+00
  55 | django_celery_beat              | 0006_auto_20180322_0932                                                           | 2022-06-21 03:34:21.9
56168+00
  56 | django_celery_beat              | 0007_auto_20180521_0826                                                           | 2022-06-21 03:34:21.9
7522+00
  57 | django_celery_beat              | 0008_auto_20180914_1922                                                           | 2022-06-21 03:34:22.0
14082+00
  58 | django_celery_beat              | 0006_auto_20180210_1226                                                           | 2022-06-21 03:34:22.0
40085+00
  59 | django_celery_beat              | 0006_periodictask_priority                                                        | 2022-06-21 03:34:22.0
50621+00
  60 | django_celery_beat              | 0009_periodictask_headers                                                         | 2022-06-21 03:34:22.0
61066+00
  61 | django_celery_beat              | 0010_auto_20190429_0326                                                           | 2022-06-21 03:34:22.3
15492+00
  62 | django_celery_beat              | 0011_auto_20190508_0153                                                           | 2022-06-21 03:34:22.3
32474+00
  63 | django_celery_beat              | 0012_periodictask_expire_seconds                                                  | 2022-06-21 03:34:22.3
45004+00
  64 | django_celery_beat              | 0013_auto_20200609_0727                                                           | 2022-06-21 03:34:22.3
54525+00
  65 | django_celery_beat              | 0014_remove_clockedschedule_enabled                                               | 2022-06-21 03:34:22.3
62733+00
  66 | django_celery_beat              | 0015_edit_solarschedule_events_choices                                            | 2022-06-21 03:34:22.3
71307+00
  67 | extras                          | 0017_joblogentry                                                                  | 2022-06-21 03:34:22.4
75836+00
  68 | extras                          | 0018_joblog_data_migration                                                        | 2022-06-21 03:34:22.5
8042+00
  69 | extras                          | 0019_joblogentry__meta_options__related_name                                      | 2022-06-21 03:34:22.6
87693+00
  70 | extras                          | 0020_customfield_changelog                                                        | 2022-06-21 03:34:23.0
41676+00
  71 | extras                          | 0021_customfield_changelog_data                                                   | 2022-06-21 03:34:23.1
46411+00
  72 | ipam                            | 0002_initial_part_2                                                               | 2022-06-21 03:34:25.5
38509+00
  73 | ipam                            | 0003_remove_max_length                                                            | 2022-06-21 03:34:26.2
2466+00
  74 | ipam                            | 0004_fixup_p2p_broadcast                                                          | 2022-06-21 03:34:26.3
32298+00
  75 | ipam                            | 0005_auto_slug                                                                    | 2022-06-21 03:34:26.3
81617+00
  76 | nautobot_chatops                | 0001_initial                                                                      | 2022-06-21 03:34:26.4
12036+00
  77 | nautobot_chatops                | 0002_commandlog_params1                                                           | 2022-06-21 03:34:26.4
20749+00
  78 | nautobot_chatops                | 0003_params_to_params1                                                            | 2022-06-21 03:34:26.5
23227+00
  79 | nautobot_chatops                | 0004_remove_params_rename_params1                                                 | 2022-06-21 03:34:26.5
37862+00
  80 | nautobot_circuit_maintenance    | 0001_initial                                                                      | 2022-06-21 03:34:27.4
58074+00
  81 | nautobot_circuit_maintenance    | 0002_notification_secrets_out_of_db                                               | 2022-06-21 03:34:27.5
68522+00
  82 | nautobot_circuit_maintenance    | 0003_improve_rawnotification                                                      | 2022-06-21 03:34:28.0
56987+00
  83 | nautobot_circuit_maintenance    | 0004_raw_md5                                                                      | 2022-06-21 03:34:28.2
07928+00
  84 | nautobot_circuit_maintenance    | 0005_notificationsource__token                                                    | 2022-06-21 03:34:28.2
20231+00
  85 | nautobot_circuit_maintenance    | 0006_fake_migration_to_update_custom_fields                                       | 2022-06-21 03:34:28.2
22454+00
  86 | nautobot_circuit_maintenance    | 0007_notificationsource_attach_all_providers                                      | 2022-06-21 03:34:28.2
33991+00
  87 | nautobot_circuit_maintenance    | 0008_raw_binary                                                                   | 2022-06-21 03:34:28.3
8695+00
  88 | nautobot_circuit_maintenance    | 0009_auto_20210916_1519                                                           | 2022-06-21 03:34:28.4
12517+00
  89 | nautobot_circuit_maintenance    | 0010_rawnotification_stamp                                                        | 2022-06-21 03:34:28.6
1716+00
  90 | nautobot_circuit_maintenance    | 0011_mysql                                                                        | 2022-06-21 03:34:28.6
51698+00
  91 | nautobot_data_validation_engine | 0001_initial                                                                      | 2022-06-21 03:34:28.9
0345+00
  92 | nautobot_device_lifecycle_mgmt  | 0001_hardwarelcm                                                                  | 2022-06-21 03:34:29.5
97491+00
  93 | nautobot_device_lifecycle_mgmt  | 0002_softwarelcm                                                                  | 2022-06-21 03:34:29.8
29146+00
  94 | nautobot_device_lifecycle_mgmt  | 0003_service_contracts                                                            | 2022-06-21 03:34:30.3
37902+00
  95 | nautobot_device_lifecycle_mgmt  | 0004_validated_software_m2m                                                       | 2022-06-21 03:34:31.5
72934+00
  96 | nautobot_device_lifecycle_mgmt  | 0005_software_reporting                                                           | 2022-06-21 03:34:31.8
50618+00
  97 | nautobot_device_lifecycle_mgmt  | 0006_cvelcm_vulnerabilitylcm                                                      | 2022-06-21 03:34:32.3
66605+00
  98 | nautobot_device_lifecycle_mgmt  | 0007_softwareimagelcm                                                             | 2022-06-21 03:34:32.5
21179+00
  99 | nautobot_device_lifecycle_mgmt  | 0008_software_image_data_migration                                                | 2022-06-21 03:34:32.6
69701+00
 100 | nautobot_device_lifecycle_mgmt  | 0009_software_remove_image_fields                                                 | 2022-06-21 03:34:32.8
84166+00
 101 | nautobot_device_onboarding      | 0001_initial                                                                      | 2022-06-21 03:34:33.3
79038+00
 102 | nautobot_device_onboarding      | 0002_create_onboardingdevice                                                      | 2022-06-21 03:34:33.5
22836+00
 103 | nautobot_device_onboarding      | 0003_onboardingtask_label                                                         | 2022-06-21 03:34:33.7
14081+00
 104 | nautobot_golden_config          | 0001_initial                                                                      | 2022-06-21 03:34:34.9
16377+00
 105 | nautobot_golden_config          | 0002_custom_data                                                                  | 2022-06-21 03:34:35.3
39142+00
 106 | nautobot_golden_config          | 0003_auto_20210510_2356                                                           | 2022-06-21 03:34:35.7
34489+00
 107 | nautobot_golden_config          | 0004_auto_20210616_2234                                                           | 2022-06-21 03:34:36.3
82643+00
 108 | nautobot_golden_config          | 0005_json_compliance_rule                                                         | 2022-06-21 03:34:37.2
08736+00
 109 | nautobot_golden_config          | 0006_multi_repo_support_temp_field                                                | 2022-06-21 03:34:37.6
24431+00
 110 | nautobot_golden_config          | 0007_multi_repo_support_convert_many                                              | 2022-06-21 03:34:38.7
41304+00
 111 | nautobot_golden_config          | 0008_multi_repo_support_final                                                     | 2022-06-21 03:34:39.3
45613+00
 112 | nautobot_golden_config          | 0009_multiple_gc_settings_part_1                                                  | 2022-06-21 03:34:40.4
44513+00
 113 | nautobot_golden_config          | 0010_multiple_gc_settings_part_2                                                  | 2022-06-21 03:34:40.5
95794+00
 114 | nautobot_golden_config          | 0011_multiple_gc_settings_part_3                                                  | 2022-06-21 03:34:41.3
93352+00
 115 | nautobot_golden_config          | 0012_multiple_gc_settings_part_4                                                  | 2022-06-21 03:34:41.5
31343+00
 116 | nautobot_golden_config          | 0013_multiple_gc_settings_part_5                                                  | 2022-06-21 03:34:41.7
98065+00
 117 | nautobot_golden_config          | 0014_convert_sotagg_queries_part1                                                 | 2022-06-21 03:34:42.1
39159+00
 118 | nautobot_golden_config          | 0015_convert_sotagg_queries_part2                                                 | 2022-06-21 03:34:42.2
907+00
 119 | nautobot_golden_config          | 0016_convert_sotagg_queries_part3                                                 | 2022-06-21 03:34:42.5
04762+00
 120 | nautobot_golden_config          | 0017_convert_sotagg_queries_part4                                                 | 2022-06-21 03:34:42.6
41941+00
 121 | nautobot_golden_config          | 0018_convert_sotagg_queries_part5                                                 | 2022-06-21 03:34:42.7
23256+00
 122 | nautobot_ssot                   | 0001_initial                                                                      | 2022-06-21 03:34:43.2
5668+00
 123 | nautobot_ssot                   | 0002_performance_metrics                                                          | 2022-06-21 03:34:43.4
17448+00
 124 | sessions                        | 0001_initial                                                                      | 2022-06-21 03:34:43.4
28361+00
 125 | default                         | 0001_initial                                                                      | 2022-06-21 03:34:43.6
22178+00
 126 | social_auth                     | 0001_initial                                                                      | 2022-06-21 03:34:43.6
2385+00
 127 | default                         | 0002_add_related_name                                                             | 2022-06-21 03:34:43.7
63829+00
 128 | social_auth                     | 0002_add_related_name                                                             | 2022-06-21 03:34:43.7
65488+00
 129 | default                         | 0003_alter_email_max_length                                                       | 2022-06-21 03:34:43.7
7881+00
 130 | social_auth                     | 0003_alter_email_max_length                                                       | 2022-06-21 03:34:43.7
80369+00
 131 | default                         | 0004_auto_20160423_0400                                                           | 2022-06-21 03:34:43.8
0108+00
 132 | social_auth                     | 0004_auto_20160423_0400                                                           | 2022-06-21 03:34:43.8
02976+00
 133 | social_auth                     | 0005_auto_20160727_2333                                                           | 2022-06-21 03:34:43.8
141+00
 134 | social_django                   | 0006_partial                                                                      | 2022-06-21 03:34:43.8
24979+00
 135 | social_django                   | 0007_code_timestamp                                                               | 2022-06-21 03:34:43.8
3919+00
 136 | social_django                   | 0008_partial_timestamp                                                            | 2022-06-21 03:34:43.8
4974+00
 137 | social_django                   | 0009_auto_20191118_0520                                                           | 2022-06-21 03:34:43.8
93176+00
 138 | social_django                   | 0010_uid_db_index                                                                 | 2022-06-21 03:34:43.9
20112+00
 139 | taggit                          | 0001_initial                                                                      | 2022-06-21 03:34:44.0
6908+00
 140 | taggit                          | 0002_auto_20150616_2121                                                           | 2022-06-21 03:34:44.4
52037+00
 141 | taggit                          | 0003_taggeditem_add_unique_index                                                  | 2022-06-21 03:34:44.5
10758+00
 142 | tenancy                         | 0002_auto_slug                                                                    | 2022-06-21 03:34:44.7
7794+00
 143 | virtualization                  | 0002_virtualmachine_local_context_schema                                          | 2022-06-21 03:34:44.9
1945+00
 144 | virtualization                  | 0003_vminterface_verbose_name                                                     | 2022-06-21 03:34:45.0
07127+00
 145 | virtualization                  | 0004_auto_slug                                                                    | 2022-06-21 03:34:45.3
87657+00
 146 | social_django                   | 0002_add_related_name                                                             | 2022-06-21 03:34:45.3
93073+00
 147 | social_django                   | 0001_initial                                                                      | 2022-06-21 03:34:45.3
9502+00
 148 | social_django                   | 0004_auto_20160423_0400                                                           | 2022-06-21 03:34:45.3
96841+00
 149 | social_django                   | 0005_auto_20160727_2333                                                           | 2022-06-21 03:34:45.3
98564+00
 150 | social_django                   | 0003_alter_email_max_length                                                       | 2022-06-21 03:34:45.4
00299+00
 151 | extras                          | 0022_objectchange_object_datav2                                                   | 2022-09-20 11:17:14.9
73346+00
 152 | extras                          | 0023_job_model                                                                    | 2022-09-20 11:17:16.5
68845+00
 153 | extras                          | 0024_job_data_migration                                                           | 2022-09-20 11:17:17.4
17609+00
 154 | extras                          | 0025_add_advanced_ui_boolean_to_customfield_conputedfield_and_relationship        | 2022-09-20 11:17:17.6
95133+00
 155 | extras                          | 0026_job_add_gitrepository_fk                                                     | 2022-09-20 11:17:18.5
74236+00
 156 | extras                          | 0027_job_gitrepository_data_migration                                             | 2022-09-20 11:17:18.7
90575+00
 157 | extras                          | 0028_job_reduce_source                                                            | 2022-09-20 11:17:19.1
6009+00
 158 | extras                          | 0029_dynamicgroup                                                                 | 2022-09-20 11:17:19.4
46947+00
 159 | extras                          | 0030_webhook_alter_unique_together                                                | 2022-09-20 11:17:19.5
36837+00
 160 | extras                          | 0031_tag_content_types                                                            | 2022-09-20 11:17:19.8
19373+00
 161 | extras                          | 0032_tag_content_types_data_migration                                             | 2022-09-20 11:17:20.0
18321+00
 162 | extras                          | 0033_add__optimized_indexing                                                      | 2022-09-20 11:17:22.6
88303+00
 163 | extras                          | 0034_alter_fileattachment_mimetype                                                | 2022-09-20 11:17:22.7
30302+00
 164 | extras                          | 0035_scheduledjob_crontab                                                         | 2022-09-20 11:17:22.7
66409+00
 165 | extras                          | 0036_job_add_has_sensitive_variables                                              | 2022-09-20 11:17:23.2
43105+00
 166 | extras                          | 0037_configcontextschema__remove_name_unique__create_constraint_unique_name_owner | 2022-09-20 11:17:23.3
84785+00
 167 | dcim                            | 0008_increase_all_serial_lengths                                                  | 2022-09-20 11:17:23.8
12839+00
 168 | dcim                            | 0009_add_natural_indexing                                                         | 2022-09-20 11:17:29.0
02469+00
 169 | dcim                            | 0010_interface_status                                                             | 2022-09-20 11:17:29.1
78189+00
 170 | dcim                            | 0011_interface_status_data_migration                                              | 2022-09-20 11:17:40.0
92+00
 171 | dcim                            | 0012_interface_parent_bridge                                                      | 2022-09-20 11:17:40.4
88733+00
 172 | dcim                            | 0013_location_location_type                                                       | 2022-09-20 11:17:41.9
28378+00
 173 | circuits                        | 0004_increase_provider_account_length                                             | 2022-09-20 11:17:42.0
91079+00
 174 | circuits                        | 0005_providernetwork                                                              | 2022-09-20 11:17:43.3
82403+00
 175 | circuits                        | 0006_cache_circuit_terminations                                                   | 2022-09-20 11:17:43.5
30121+00
 176 | circuits                        | 0007_circuitterminations_primary_model                                            | 2022-09-20 11:17:43.8
83055+00
 177 | circuits                        | 0008_add_natural_indexing                                                         | 2022-09-20 11:17:44.0
10487+00
 178 | circuits                        | 0009_circuittermination_location                                                  | 2022-09-20 11:17:44.1
88821+00
 179 | dcim                            | 0014_location_status_data_migration                                               | 2022-09-20 11:17:44.3
45248+00
 180 | django_rq                       | 0001_initial                                                                      | 2022-09-20 11:17:44.3
59865+00
 181 | extras                          | 0038_configcontext_locations                                                      | 2022-09-20 11:17:44.5
843+00
 182 | extras                          | 0039_objectchange__add_change_context                                             | 2022-09-20 11:17:45.2
92266+00
 183 | extras                          | 0040_dynamicgroup__dynamicgroupmembership                                         | 2022-09-20 11:17:45.6
14465+00
 184 | extras                          | 0041_jobresult_job_kwargs                                                         | 2022-09-20 11:17:45.6
90225+00
 185 | extras                          | 0042_job__add_is_job_hook_receiver                                                | 2022-09-20 11:17:45.7
73242+00
 186 | extras                          | 0043_note                                                                         | 2022-09-20 11:17:45.9
85871+00
 187 | extras                          | 0044_add_job_hook                                                                 | 2022-09-20 11:17:46.1
85475+00
 188 | extras                          | 0045_add_custom_field_slug                                                        | 2022-09-20 11:17:46.2
53915+00
 189 | extras                          | 0046_populate_custom_field_slug_label                                             | 2022-09-20 11:17:46.4
39853+00
 190 | extras                          | 0047_enforce_custom_field_slug                                                    | 2022-09-20 11:17:46.9
61046+00
 191 | ipam                            | 0006_ipaddress_nat_outside_list                                                   | 2022-09-20 11:17:47.3
69842+00
 192 | ipam                            | 0007_add_natural_indexing                                                         | 2022-09-20 11:17:48.3
36369+00
 193 | ipam                            | 0008_prefix_vlan_vlangroup_location                                               | 2022-09-20 11:17:49.2
839+00
 194 | nautobot_bgp_models             | 0001_initial                                                                      | 2022-09-20 11:17:51.1
82092+00
 195 | nautobot_firewall_models        | 0001_initial                                                                      | 2022-09-20 11:18:05.3
97423+00
 196 | nautobot_firewall_models        | 0002_custom_status                                                                | 2022-09-20 11:18:05.8
44987+00
 197 | nautobot_firewall_models        | 0003_default_status                                                               | 2022-09-20 11:18:08.7
1097+00
 198 | nautobot_firewall_models        | 0004_add_description                                                              | 2022-09-20 11:18:08.9
29123+00
 199 | nautobot_firewall_models        | 0005_capircapolicy                                                                | 2022-09-20 11:18:09.1
09198+00
 200 | nautobot_firewall_models        | 0006_renaming_part1                                                               | 2022-09-20 11:18:13.5
30048+00
 201 | nautobot_firewall_models        | 0007_renaming_part2                                                               | 2022-09-20 11:18:13.7
00753+00
 202 | nautobot_firewall_models        | 0008_renaming_part3                                                               | 2022-09-20 11:18:14.4
09341+00
 203 | nautobot_golden_config          | 0019_convert_dynamicgroup_part_1                                                  | 2022-09-20 11:18:14.5
94973+00
 204 | nautobot_golden_config          | 0020_convert_dynamicgroup_part_2                                                  | 2022-09-20 11:18:14.8
28742+00
 205 | nautobot_golden_config          | 0021_convert_dynamicgroup_part_3                                                  | 2022-09-20 11:18:15.1
57401+00
 206 | users                           | 0002_token_ordering_by_created                                                    | 2022-09-20 11:18:15.1
92876+00
 207 | virtualization                  | 0005_add_natural_indexing                                                         | 2022-09-20 11:18:16.0
72442+00
 208 | virtualization                  | 0006_vminterface_status                                                           | 2022-09-20 11:18:16.2
66617+00
 209 | virtualization                  | 0007_vminterface_status_data_migration                                            | 2022-09-20 11:18:16.4
8862+00
 210 | virtualization                  | 0008_vminterface_parent                                                           | 2022-09-20 11:18:16.8
57444+00
 211 | virtualization                  | 0009_cluster_location                                                             | 2022-09-20 11:18:17.0
36401+00
(211 rows)
`

**Comment by bryanculver** [comment]
@telescope40 Looking at that output there are many migrations that were applied when you started up Nautobot with 1.4. Quick way to tell is the dates but starting at `0022_objectchange_object_datav2` and onward were migrations that came in with 1.4. So either you need to revert your database or roll back the migrations which may not work.

**Comment by glennmatthews** [comment]
Related: #2653
