### ISSUE TITLE
Docs: readthedocs sphinx breadcrumb links broken

### ISSUE THREAD

**Issue by joewesch** [nautobot/nautobot#249]
### Environment
* Python version: N/A
* Nautobot version: N/A

### Steps to Reproduce
1. Go to any page on https://nautobot.readthedocs.io/
2. Click on the Edit on Github link at the top right of the page

### Expected Behavior
It should bring up a github page that either allows for quick edit (user has proper permissions) or asks the user to fork the repo to provide an edit.

### Observed Behavior
404 error

**Comment by jathanism** [comment]
Huh, looks like it's linking to `master` by default, which doesn't exist. Must be some kind of setting to tweak in either our templates or RTD.

**Comment by jathanism** [comment]
Yep! https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/configuration.md#edit_uri
