### ISSUE TITLE
Document TownCrier

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot#2490]
### Proposed Changes

Update the `PULL_REQUEST_TEMPLATE.md` to include information about towncrier and how it is used.

### Justification

It was not clear to me:

* Clarity on that it is required
* Between changed and fix, when I am "fixing an issue" as an example
* Clarity when there is not an existing issues, what should the number be

In general I am not sure community members will understand the process without documentation on the template.

**Comment by itdependsnetworks** [comment]
If periods are required on the fragements: https://github.com/nautobot/nautobot/pull/2614/files#r995141707 would be good to add a test for it as well.

**Comment by bryanculver** [comment]
https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments
https://github.com/nautobot/nautobot/blob/develop/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L27
