### ISSUE TITLE
Need a UI pattern for filtering tree models by parent

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#2518]
https://github.com/nautobot/nautobot/issues/774#issuecomment-1172594812:

> Implement a pattern for filtering Locations by base_site (which is a derived attribute, not a database field) so that for example when selecting a related Site while editing an object, the Location selection menu can filter to only display Locations that exist within that Site.

The specifics there may be irrelevant due to #2517, but the basic concept remains relevant, for example:

- Give me a dropdown of Locations of type "Campus" filtered to only those within parent Location "North Carolina"
- Give me a dropdown of Prefixes filtered to only those within parent Aggregate "10.0.0.0/8"
Etc.

Relates to #1032, #977, #629, etc.

**Comment by amtypaldos** [comment]
This would be a big help for us!

**Comment by jathanism** [comment]
Related to #2513 (and related fix #2665) since we're not getting nested results from reversible queries for Dynamic Groups.

**Comment by glennmatthews** [comment]
Implemented for 1.5 by #2672
