### ISSUE TITLE
Epic: Fix up all FKs and related names to follow a self-consistent pattern

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#2520]
### Proposed Changes

We don't have a single consistent pattern for foreign key names and (especially) related names on the corresponding reverse relations, for example:

- `Site.powerpanel_set` versus `Site.rack_groups` (pluralization, underscores)
- `PowerFeed.power_panel` versus `PowerPanel.powerfeeds` (underscores)
- `Tenant.rackreservations` versus `Tenant.route_targets` (underscores)

etc.

Fixing this will be a breaking change for the ORM and possibly also for the REST API and/or GraphQL as well, but it's the right thing to do long-term.

### Justification

Tech debt reduction, improved self-consistency and ease of use.

### TODO

- [x] #2960
- [x] #3066
- [ ] #3067
- [x] #3068
- [x] #3069
- [x] #3351 
- [ ] Add a lint check for this (not blocking epic)

**Comment by gsnider2195** [comment]
As part of this can we standardize on parent/child relation names for tree objects? django-tree-queries doesn't give you an option to choose those so anything that's a django-tree-queries treenode is already using `parent` and `children` but we have inconsistencies on MPTTModels. For example InventoryItem uses `parent`/`child_items` and Region uses `parent`/`children`.

**Comment by jathanism** [comment]
My proposal as we had discussed before is to use the `Meta.verbose_name_plural` for the related model and normalize spaces to underscores. For example:

```python
In [1]: ConsolePort._meta.verbose_name_plural
Out[1]: 'console ports'

In [2]: from nautobot.utilities.utils import slugify_dashes_to_underscores

In [3]: slugify_dashes_to_underscores(ConsolePort._meta.verbose_name_plural)
Out[3]: 'console_ports'
```

**Comment by gsnider2195** [comment]
Should a `ForeignKey` field from `Rack` to `RackGroup` be called `rack_group` or just `group`? Currently it's called `group` but this doesn't match `RackGroup`'s `_meta.verbose_name`

**Comment by glennmatthews** [comment]
IMHO explicit is better than implicit. Especially now that we have things like DynamicGroup and DeviceRedundancyGroup, `group` is ambiguous, `rack_group` is not.

**Comment by bryanculver** [comment]
Down to a single story #3067 which is in the milestone. Closing.
