### ISSUE TITLE
X-Frame-Options is set to DENY

### ISSUE THREAD

**Issue by baldy2811** [nautobot/nautobot#2548]
### Environment
* Nautobot version (Docker tag too if applicable): latest docker Version (1.4)
* Python version: 3.9

### Steps to Reproduce
1. Install nautobot-ui-plugin
2. add nautobot-ui-plugin to plugin_requirements.txt
3. add nautobot_ui_plugin to config
4. rebuild docker container
5. View Topology

### Expected Behavior
I would see the network Topology were all servers/cables/routers are connected to.

### Observed Behavior
I got an error that the frame is not displayed:
X-Frame-Options is set to DENY

**Comment by jcrystall** [comment]
Yes, this was an error in the plugin. It's fixed now in 0.10.3.
https://gitlab-ce.gwdg.de/gwdg-netz/nautobot-plugins/nautobot-ui-plugin/-/issues/4

**Comment by glennmatthews** [comment]
Terrific, thank you for letting us know!
