### ISSUE TITLE
collapsing of Job groupings is broken in next

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#2555]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.0a0

### Steps to Reproduce
1. Go to https://next.demo.nautobot.com/extras/jobs/
2. Click the "Data Quality" heading

### Expected Behavior

All five jobs under "Data Quality" to be hidden

### Observed Behavior

Only the first job is hidden, the other four remain visible.

This appears to be a regression due to changes to the job_table.html template in #2317.

**Comment by jathanism** [comment]
I confirmed that reverting `job_table.html` to the previous version from commit d80a3cf94928f988a16a5d99d7fdc4ade025782f fixes this issue. 

It's not clear to me why this template needed to change for the custom field grouping feature. If it's not, we should just be able to revert the changes to this file to fix this bug.
