### ISSUE TITLE
Many settings as defined in settings.py do not respect the documented environment variables

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#2578]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.5
* Python version: any
* Database platform, version: any
* Middleware(s): n/a

### Steps to Reproduce
1. Use a minimal, stripped-down `nautobot_config.py`, rather than one containing all optional settings like the `nautobot/core/templates/nautobot_config.py.j2` template does.
2. Attempt to influence various optional settings by setting environment variables for the Nautobot process, e.g. `NAUTOBOT_DEBUG=True`

### Expected Behavior

Environment variables should be respected as documented.

### Observed Behavior

Many environment variables are not respected by the defaults defined in `settings.py`, only the overrides for these settings in `nautobot_config.py.j2` respect environment variables. Related: #2574. The below list may not be comprehensive:

- CACHEOPS_DEFAULTS / NAUTOBOT_CACHEOPS_DEFAULTS
- CACHEOPS_ENABLED / NAUTOBOT_CACHEOPS_ENABLED
- CACHEOPS_REDIS / NAUTOBOT_CACHEOPS_REDIS
- CORS_ALLOW_ALL_ORIGINS / NAUTOBOT_CORS_ALLOW_ALL_ORIGINS
- DEBUG / NAUTOBOT_DEBUG
- DISABLE_PREFIX_LIST_HIERARCHY / NAUTOBOT_DISABLE_PREFIX_LIST_HIERARCHY (making this inherit from a variable by default would possibly break our Constance config though)
- ENFORCE_GLOBAL_UNIQUE / NAUTOBOT_ENFORCE_GLOBAL_UNIQUE
- MAINTENANCE_MODE / NAUTOBOT_MAINTENANCE_MODE
- METRICS_ENABLED / NAUTOBOT_METRICS_ENABLED
- SESSION_COOKIE_AGE / NAUTOBOT_SESSION_COOKIE_AGE
- SESSION_FILE_PATH / NAUTOBOT_SESSION_FILE_PATH
- STRICT_FILTERING / NAUTOBOT_STRICT_FILTERING
- TIME_ZONE / NAUTOBOT_TIME_ZONE, as well as all of the related time/date format variables

Solution should *probably* be to just strip down `nautobot_config.py.j2` and move the environment variable checks directly into `settings.py`.

This also relates to #1150.

**Comment by jathanism** [comment]
> * METRICS_ENABLED / NAUTOBOT_METRICS_ENABLED

This one can't easily be set as an environment variable because it's a "magic" setting that is interpreted. 

The magic variable is processed inside of `nautobot.core.cli._configure_settings`, so if an environment variable were to be read, it would have to be done so in this code block:

```python
    # If metrics are enabled and postgres is the backend, set the driver to the
    # one provided by django-prometheus.
    if settings.METRICS_ENABLED and "postgres" in settings.DATABASES["default"]["ENGINE"]:
        settings.DATABASES["default"]["ENGINE"] = "django_prometheus.db.backends.postgresql"
```

I would rather us eliminate this setting entirely in exchange for just having users explicitly set the metrics backend by just setting this in `nautobot_config.py` explicitly, e.g.:

```python
DATABASES["default"]["ENGINE"] = "django_prometheus.db.backends.postgresql"
```
