### ISSUE TITLE
Normalize Colorscheme

### ISSUE THREAD

**Issue by KalleDK** [nautobot/nautobot#2586]
### As ...

Austin - Network Automation Engineer

### I want ...

To have persistent colorschemas for same actions. So if add device is green, then add device is always green.

![image](https://user-images.githubusercontent.com/574334/194483603-4b1df94b-0a95-43b3-80e0-a11c6969ccf9.png)

My brain keeps getting confused based on where I do an action.

- Blue means add, unless it means import
- Green is export unless it means add
- Lightblue is import

### So that ...

My brain doesn't have to keep getting "confused" as in I have to revalidate that the button does what I want it to do.

### I know this is done when...

The colors in the menu and the site it matches have same colorscheme

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by jathanism** [comment]
You're speaking my language! Thanks for the submission @KalleDK.

**Comment by lampwins** [comment]
I think we have mostly covered this in 2.1, but please feel free to open more specific issues if you find things in the future.

**Comment by KalleDK** [comment]
Thank you very much @lampwins
