### ISSUE TITLE
Update screenshots in github README to gifs

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#2589]
### Proposed Changes

Change static screenshots to gifs of some common Nautobot workflows (add a new device from the rack elevation view, cable up an interface, filter a list view). I think [the haystack repo](https://github.com/deepset-ai/haystack/blob/main/README.md) has a good example of a gif that tells you at a glance exactly what the application does.

### Justification

Make it easier for potential users to understand what it is that Nautobot can do for them.

**Comment by Santhusha-bit** [comment]
Can I work on this issue?
