### ISSUE TITLE
Add more detail to the synopsis section at the top of the README

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#2591]
### Proposed Changes

Add more of the information from the [what is Nautobot](https://docs.nautobot.com/projects/core/en/stable/#what-is-nautobot) section of the documentation to the README.

## Some examples from around github

![image](https://user-images.githubusercontent.com/75227981/194581206-f1609c17-f468-4e8d-ab69-26c13c0eba03.png)

---

![image](https://user-images.githubusercontent.com/75227981/194585928-f8bd94be-ce90-451d-b175-ffcf58214d3f.png)

---

![image](https://user-images.githubusercontent.com/75227981/194588243-3a1b99db-7ac7-4453-b18a-818abf3d014f.png)

### Justification

To help somebody get a quick understanding of what kind of problems they can solve by using Nautobot when they visit the github repo. Technical users will click on the github link first when doing a google search and we should present the information they need up front so they can decide if Nautobot is something that could benefit their environment.

**Comment by Santhusha-bit** [comment]
Can I work on this issue?

**Comment by glennmatthews** [comment]
Done in #2599.
