### ISSUE TITLE
Increase Device/VirtualMachine name limit to at least 80 chars (vSphere limit)

### ISSUE THREAD

**Issue by jakubkrysl** [nautobot/nautobot#2603]
### As ...

Isabella - Infrastructure Owner

### I want ...

Sync VMs from VMware with the same name

### So that ...

I have the same data in Nautobot and I can use it as SSoT

### I know this is done when...

- I can create VirtualMachine with name on the limit from VMware vSphere (80 chars)

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [x] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

Yes, increase CharField max length to at least 80 chars

### External Dependencies

None

**Comment by glennmatthews** [comment]
Thanks for the request! For most models with a `name` field, the max length is currently 100 characters, although for `Device` and `VirtualMachine` it's currently limited to 64 for some reason. I'd definitely be on board with increasing the limit on both `Device` and `VirtualMachine` to at least 100 characters.

**Comment by lampwins** [comment]
Closing this as it will be covered in #2906
