### ISSUE TITLE
Create and use `assertQuerysetEqualAndNotEmpty` test method

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#2633]
### Proposed Changes

- Create a `TestCase.assertQuerysetEqualAndNotEmpty()` test method that works like `assertQuerysetEqual()` but additionally asserts that the provided querysets are non-empty, i.e. actually contain at least one matching record in both cases.
- Update usage of `assertQuerysetEqual()` throughout our test code to use the new method.

### Justification

As part of the of the work towards #2226, our various `test_filters.py` test scripts are being updated to use `assertQuerysetEqual(self.filterset(params, self.queryset).qs, self.queryset.filter(...))` rather than `self.assertEqual(self.filterset(params, self.queryset).qs.count(), HARDCODED_NUMBER)`in many cases. This is generally desirable as it allows the tests to gracefully handle cases where the specific contents of the queryset are not known in advance (due to the use of pseudo-random generation), but I'm concerned about the possibility of the updated tests failing to catch a case where neither the filterset nor the filtered queryset actually contain any records, which could be "expected" or could be due to a bug in the test code or in the filtering code itself.

**Comment by gsnider2195** [comment]
`nautobot.utilities.testing.mixins.NautobotTestCaseMixin` method `assertQuerysetEqualAndNotEmpty` added in #2579

**Comment by bryanculver** [comment]
Implemented via #2579
