### ISSUE TITLE
subnet "over" allocation

### ISSUE THREAD

**Issue by soeren-n** [nautobot/nautobot#2648]
### Steps to Reproduce
1. 	Create some test /24 container and enable “Is a pool” option
![image](https://user-images.githubusercontent.com/115686203/196607127-7727dc1e-567f-4540-af54-edbbcd357ed8.png)

2.	Call /api/ipam/prefixes/{ID}/available-prefixes/ API endpoint to allocate /24 subnet
![image](https://user-images.githubusercontent.com/115686203/196607230-8cfca266-73e0-496a-ad1e-cdfe7f1cc298.png)

3.	Then make the same call again and you still get a subnet in return (instead of getting 204 code)
![image](https://user-images.githubusercontent.com/115686203/196607318-c42d3d8c-a22e-45d9-8e1a-75a71ad00a4e.png)

That Nautobot will not "give away" the same subnet more than once

You can do "over allocation"
![image](https://user-images.githubusercontent.com/115686203/196607024-b5870264-4a39-41b0-8bc6-da332a2b4e61.png)

**Comment by lampwins** [comment]
We will be addressing this in the swath of 2.0 changes to the IPAM functionality. See #1362 & #2916. We will leave this open as a bug, for now, to make sure this case gets covered.
