### ISSUE TITLE
"Device" Tab vanishes when selecting Tab from Plugin

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#2649]
### Environment
* Nautobot version (Docker tag too if applicable): bb9ed6e52a8b (v1.4.7), Docker version 20.10.12, build e91ed57
* Python version: 3.9
* Database platform, version: Postgres
* Middleware(s):

### Steps to Reproduce
1. Install plugin that adds extra tab on device detail page
2. Activate the tab
3.

### Expected Behavior
The Tab "Device" is still there

### Observed Behavior
The Tab "Device" gets invisible if the "Wires" Tab will be selected. but there is a small active area that is visible on mouse over that opens the "Device" Tab on Click.

![image](https://user-images.githubusercontent.com/8406301/196649191-304bbf96-d657-48c1-bfa4-f2d61c66e07b.png)

**Comment by bryanculver** [comment]
Thanks for the report @jifox! Is this an internally developed plugin or an open source?

**Comment by jifox** [comment]
@bryanculver The plugin is now available at

https://github.com/jifox/nautobot-plugin-wires

**Comment by bryanculver** [comment]
View in plugin was missing context variables. Proposed fix in: https://github.com/jifox/nautobot-plugin-wires/pull/1
