### ISSUE TITLE
Filter form modal tab view

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#2652]
### Proposed Changes
In the new filter form modal, add a tab view which will allow us to show the existing filter forms as a default view, and an "advanced" tab which will show the new dynamic filter form functionality.

### Justification
We have a need in 1.5 to maintain support for the existing filter forms because of a lack of grooming across the filter sets and more importantly, for plugin registration of filter form fields.

This tab feature strikes a balance between simplicity and maintaining the existing functionality. We will look for better solutions in 2.0.

**Comment by bryanculver** [comment]
Closed with #2680
