### ISSUE TITLE
Autogenerate a table of fields as part of object_retrieve.html

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#2660]
### Discussed in https://github.com/nautobot/nautobot/discussions/2604

<div type='discussions-op-text'>

<sup>Originally posted by **nlgotz** October 11, 2022</sup>
The NautobotUIViewSets make things a lot simpler when developing apps but one thing that would make it even easier would be to have the object_retrieve.html template display a table of developer defined fields to eliminate some extra templating work needed for the plugin.

I find myself creating a lot of very simple and repeated retrieve.html templates that are just generating a table of fields in the model.  It would be nice to not have to create these templates just to add in a block for the content_left_page to display a simple table.

The general idea is that developers could use a variable (`retrieve_fields` in the example below) in the model class similar to the csv_headers variable. Then, the generic/object_retrieve.html template would check to see if the object has retreive_fields defined and if so, display the table.

This is just an example I borrowed from the nautobot-plugin-bgp-models app to show what I'd like to see

```python
class AutonomousSystem(PrimaryModel, StatusModel):
    # [...stripped for brevity...]
    retrieve_fields = ["asn", "description", "status", "provider"]
```

The following table gets displayed in via the generic object_retrieve.html template:

![image](https://user-images.githubusercontent.com/775979/195131391-130f7410-a69c-4d5f-9897-43687ac354a6.png)
</div>

**Comment by bryanculver** [comment]
Similar but this is geared towards developer reduction but constraining fields displayed by some simple definition user-side is: https://github.com/nautobot/nautobot/issues/1500

**Comment by glennmatthews** [comment]
See #6135.
