### ISSUE TITLE
Child locations up to 1 level down are able to have a site

### ISSUE THREAD

**Issue by amtypaldos** [nautobot/nautobot#2669]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.5
* Python version: 3.8.10
* Database platform, version: Postgres 12.12
* Middleware(s):

### Steps to Reproduce
1. Create a parent location and attach it to a site
2. Create a child of the above parent, and attach to a site

### Expected Behavior
I expected to be unable to add a child location to a site as I am unable to do so with child locations two levels down, IE the child of a child location.

### Observed Behavior
I was able to attach a child location to a site

![Screen Shot 2022-10-21 at 12 34 11 PM](https://user-images.githubusercontent.com/9521210/197245261-c76b8e63-5068-4887-bf2e-0d297924fa6f.png)
![Screen Shot 2022-10-21 at 12 34 58 PM](https://user-images.githubusercontent.com/9521210/197245405-2e9d44c7-3557-438d-8b44-9b1f301702a5.png)

**Comment by glennmatthews** [comment]
Based on discussion on Slack, it sounds like this may have happened because the "Floor" `LocationType` was changed to no longer have the "Building" `LocationType` as its parent. We probably need to disallow changing the `parent` of a `LocationType` that's already in use?
