### ISSUE TITLE
searching for /31 prefixes throws an error with v1.0.0b3

### ISSUE THREAD

**Issue by evdzande** [nautobot/nautobot#269]
### Environment
* Python version: 3.7.3
* Nautobot version: 1.0.0b3

### Steps to Reproduce
1. search for a /31 prefix such as 10.150.255.2/31
2. click the Search button
3. Server Error appears:

> <class 'TypeError'>
> 
> cannot convert 'NoneType' object to bytes
> 
> Python version: 3.7.3
> Nautobot version: 1.0.0b3

### Expected Behavior
Search results with the /31 prefix

### Observed Behavior
Server Error appears:

> <class 'TypeError'>
> 
> cannot convert 'NoneType' object to bytes
> 
> Python version: 3.7.3
> Nautobot version: 1.0.0b3
> 

This was working correctly in Nautobot version: 1.0.0b2

**Comment by glennmatthews** [comment]
Reproduced. Note that the "search" field must be used to trigger this issue, not the "Search within prefix" field:

![image](https://user-images.githubusercontent.com/5603551/114208318-54c87980-992b-11eb-836a-0fd341b47d89.png)
