### ISSUE TITLE
Implement user guide for working with custom fields

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#270]
### Environment
* Python version:
* Nautobot version: 1.0.0b3

### Proposed Functionality

Add a "user guide" to the documentation specifically focusing on use cases, applications, tips, and caveats in using the Custom Fields feature.

### Use Case

Custom fields are a surprisingly complex and nuanced feature. The current documentation is fairly bare-bones in this regard, and doesn't describe:

- worked examples of regular expression validation
- explanation of how creating or changing a custom field does (or does not!) apply to existing data records, especially as involves "required" custom fields
- examples of filtering ORM queries, REST API queries, GraphQL queries based on custom field values

### Database Changes

None

### External Dependencies

None

**Comment by brobare** [comment]
Related to custom fields and documentation, I was wondering if it might be possible to add "help" context bubbles to custom fields in the UI. 

A lot of the other areas in the UI have the "help" icon that points at, I believe, markdown files. An example: https://demo.nautobot.com/dcim/sites/ams01/edit/

I was thinking it would be nice to be able to point at the location of a file when defining the custom field. Then, whenever that custom field is rendered, the "help" icon would be there and clicking on it would pull up the markdown. 

Thoughts? Can open a new issue if that would be a better path.
