### ISSUE TITLE
Spike: Identify Existing Natural Keys Needing to be Change to Support Uniqueness Constraints

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2716]
Aligned with #1574, we need to identify which models have existing natural keys that need to be changed for the larger plan to move away from slugs and leverage more natural keys. We want to break existing natural keys in 2.0 and can add missing ones in 2.X

**Comment by jathanism** [comment]
Just gonna leave this here: https://github.com/wq/django-natural-keys

**Comment by bryanculver** [comment]
> Just gonna leave this here: https://github.com/wq/django-natural-keys

ACK

Useful for how we implement the change but we need to identify which models and places we are using psudo-natural-keys today.

**Comment by jathanism** [comment]
This work ended up being addressed in #2764
