### ISSUE TITLE
Apps Refactor: Collapse Utilities App to Core

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2721]
The bulk of the guts of the `utilities` app should no longer exist in v2. The primitives such as filters, forms, fields, template tags, etc., should move to `core`.

Ultimately, we might need to leave it around until v2.2 if we decide we want to maintain any modicum of forward-compatibility, otherwise we may just consider this entire endeavor a breaking change.

- [x] Subdivide different components of utilities
- [x] Lift-and-shift the code from utilities to core
- [x] Correct import paths from other apps to the now core import path
- [x] Create migration docs for Apps to fix imports from now missing module

**Comment by glennmatthews** [comment]
Implemented by #3132 for 2.0.
