### ISSUE TITLE
Dynamic filter form field value persistence is surprising.

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#2732]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.x
* Python version: *
* Database platform, version: n/a
* Middleware(s): n/a

### Steps to Reproduce

> This was done using the demo dataset.

0. Go to device list view
1. Click "Filter", then "Advanced" and input an advanced filter such as "name regex = ^ams01".
2. Click "Apply"
3. Observe that the filter `name__re=^ams01` is displayed in list view
4. Click "Filter" again, then select any "Default" filter such as "has interfaces = Yes"
5. Click "Apply"
6. Observe that the previous filter was replaced and that only `has_interfaces=True` is displayed in list view.

### Expected Behavior

The filter values between both tabs should persist.

### Observed Behavior

This appears to only be the case if you mix "advanced' and "default" filters using the "default" tab. If you select the same set of filter criteria using only the "advanced" tab, they always persist.

**Comment by gsnider2195** [comment]
Potential fix in django if a JS fix isn't feasible:

```diff
diff --git a/nautobot/extras/forms/base.py b/nautobot/extras/forms/base.py
index d4e8febe3..60da60697 100644
--- a/nautobot/extras/forms/base.py
+++ b/nautobot/extras/forms/base.py
@@ -1,3 +1,4 @@
+from django import forms
 from nautobot.utilities.forms import BootstrapMixin
 from .mixins import (
     CustomFieldModelBulkEditFormMixin,
@@ -38,6 +39,20 @@ class NautobotFilterForm(BootstrapMixin, CustomFieldModelFilterFormMixin, Relati
     needed.
     """
 
+    def __init__(self, *args, **kwargs):
+        super().__init__(*args, **kwargs)
+        for name, value in self.data.items():
+            if name == "q" or name not in self.fields:
+                if isinstance(value, (list, tuple)):
+                    widget = forms.widgets.MultipleHiddenInput
+                else:
+                    widget = forms.widgets.HiddenInput
+                self.fields[name] = forms.CharField(
+                    required=False,
+                    initial=value,
+                    widget=widget,
+                )
+
 
 class NautobotBulkEditForm(
     BootstrapMixin, CustomFieldModelBulkEditFormMixin, RelationshipModelBulkEditFormMixin, NoteModelBulkEditFormMixin
```

**Comment by gsnider2195** [comment]
Yeah probably easier to test than a js based fix. Call a list view with some dynamic filter form parameters in the query that are not fields in the default filterset. Then make sure the dynamic filters show up in the default filter form as hidden inputs.

**Comment by jathanism** [comment]
> Yeah probably easier to test than a js based fix. Call a list view with some dynamic filter form parameters in the query that are not fields in the default filterset. Then make sure the dynamic filters show up in the default filter form as hidden inputs.

Could probably just even compare the rendered form output without necessarily having to call the view, but yeah, I follow.
