### ISSUE TITLE
NautobotUIViewSet should include routes for change log and notes

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#2740]
### As ...

P.D. - Plugin Developer

### I want ...

The NautobotUIViewSet to automatically include routes for change log and notes

### So that ...

I do not have manually account for these routes in the traditional pattern when using the viewset

### I know this is done when...

- Routes for notes and changelog are automatically accounted for when I use the viewset and a corresponding model
- The viewset router can handle cases where the model does not support change logging or notes appropriately

### Optional - Feature groups this request pertains to.

- Plugins (and other Extensibility)

### Database Changes

None

### External Dependencies

None

**Comment by smk4664** [comment]
I would like to take this, but on the condition I can call in backup if I get too far over my head.
