### ISSUE TITLE
Dockerfile permission denied config file

### ISSUE THREAD

**Issue by Yannis100** [nautobot/nautobot#2755]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.8 -> 1.4.9
* Python version: 3.10.6
* Database platform, version: postgres 14 alpine
* Middleware(s):

Change in #2715 #2671 
### Steps to Reproduce
1. Own Dockerfile based on official Nautobot docker image
2. Try to overwrite config file with `cat /opt/nautobot/nautobot_config.append.py >> /opt/nautobot/nautobot_config.py`
3. `cannot create /opt/nautobot/nautobot_config.py: Permission denied`

### Expected Behavior
Able to change the configuration file while building the image

### Observed Behavior
Permission denied error

I think changing the line https://github.com/nautobot/nautobot/blob/9f7b414408cef9931d675abfbc5d394e65a6e420/docker/Dockerfile#L314 :
`COPY --from=final-dev /opt/nautobot/nautobot_config.py /opt/nautobot/nautobot_config.py` to 
`COPY --chown=nautobot --from=final-dev /opt/nautobot/nautobot_config.py /opt/nautobot/nautobot_config.py`
should solve the issue

**Comment by bryanculver** [comment]
Thanks for the report @Yannis100!

Can you provide a sanitized example of your Dockerfile?

Going to use it as an example for some future housekeeping tests.

**Comment by glennmatthews** [comment]
Confirmed:

```
nautobot@692f1c8a9a0d:~$ ls -l
total 32
-rw-r--r-- 1 nautobot nautobot  1980 Nov  4 21:36 nautobot.crt
-rw------- 1 nautobot nautobot  3276 Nov  4 21:36 nautobot.key
-rw-r--r-- 1 root     root     18818 Nov  4 21:36 nautobot_config.py
-rw-r--r-- 1 nautobot nautobot  2198 Nov  4 21:27 uwsgi.ini
```

**Comment by Yannis100** [comment]
Thanks for the quick fix !

@bryanculver 
My Dockerfile is basically a mix between the LDAP and Plugins ones in docker-compose project https://github.com/nautobot/nautobot-docker-compose/blob/main/Dockerfile-LDAP & https://github.com/nautobot/nautobot-docker-compose/blob/main/plugin_example/Dockerfile-Plugins

I just didn't want to copy a full config file as it might change between versions, so I use
````
COPY --chown=nautobot config/nautobot_config.append.py /opt/nautobot/
RUN cat /opt/nautobot/nautobot_config.append.py >> /opt/nautobot/nautobot_config.py && \
    rm -f /opt/nautobot/nautobot_config.append.py
````
With the plugins and LDAP configs in nautobot_config.append.py file
