### ISSUE TITLE
Natural Keys: Identify Uniqueness Constraint Changes Necessary to Sufficiently Implement Natural Keys

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2764]
#### Spikes
- [x] Review Core App for Desirable Changes to Uniqueness Constraints
- [x] Review DCIM App for Desirable Changes to Uniqueness Constraints
- [x] Review IPAM App for Desirable Changes to Uniqueness Constraints
- [x] Review Circuits app
- [x] Review Extras app
- [x] Review Tenancy app
- [x] Review Users app
- [x] Review Virtualization app

**Comment by jathanism** [comment]
## IPAM

    $ grep -r "^class.*Model" nautobot/ipam/models.py | sort
    nautobot/ipam/models.py:class Aggregate(PrimaryModel):
    nautobot/ipam/models.py:class IPAddress(PrimaryModel, StatusModel):
    nautobot/ipam/models.py:class Prefix(PrimaryModel, StatusModel):
    nautobot/ipam/models.py:class RIR(OrganizationalModel):
    nautobot/ipam/models.py:class Role(OrganizationalModel):
    nautobot/ipam/models.py:class RouteTarget(PrimaryModel):
    nautobot/ipam/models.py:class Service(PrimaryModel):
    nautobot/ipam/models.py:class VLAN(PrimaryModel, StatusModel):
    nautobot/ipam/models.py:class VLANGroup(OrganizationalModel):
    nautobot/ipam/models.py:class VRF(PrimaryModel):

### Aggregate

- Will be merged into `Prefix` for v2

### IPAddress

> See Nautobot 2.0 PI Planning docs

Prefix

> See Nautobot 2.0 PI Planning docs

### RIR

- `name` is unique and is likely sufficient
- `slug` can be removed.
- Implements `natural_key()`
- Uses `RIRQuerySet` merely to provide `get_by_natural_key()` 

### Role

- `name` is unique and is likely sufficient
- `slug` can be removed
- Does not implement `natural_key()`

### RouteTarget

- `name` is unique and is likely sufficient
- Does not implement `natural_key()`

### Service

> Has no uniqunenss constraints outside of FK relationship to `Device`

- `name` is not unique and should be
- Service can only have a foreign key to a device/VM (from here on `Device` since these wil be merged) so services are not currently re-usable
- We might consider changing this data model to be m2m to `Device` so that we can assert `name` uniqueness and also constraints around the m2m (e.g. only one assignment per device)
- Additionally this object has a forward m2m without a through table to `ipam.IPAddress` which should be considered to be changed to a new intermediate model as discussed in PI planning

### VLAN

- This is it:
            unique_together = [
                # 2.0 TODO: since group is nullable and NULL != NULL, we can have multiple non-group VLANs with
                # the same vid and name. We should probably fix this with a custom validate_unique() function.
                ["group", "vid"],
                ["group", "name"],
            ]
- Similar to what we’ve discussed with `Prefix` and `IPAddress`, the same uniqueness “boundaries” for other relations should be considered here, e.g:
    - `tenant`
    - `role`
- `name` is not unique and IMO should absolutely be unique, unless we consider the `unique_together` along with other boundaries described above
VLANGroup
- Has `slug` with unique
- Also:
        unique_together = [
            # 2.0 TODO: since site is nullable, and NULL != NULL, this means that we can have multiple non-Site VLANGroups
            # with the same name. This should probably be fixed with a custom validate_unique() function!
            ["site", "name"],
            # 2.0 TODO: Remove unique_together to make slug globally unique. This would be a breaking change.
            ["site", "slug"],
        ]
- We should absolutely swap the uniqueness from `slug` to `name` and remove `slug`
- At a minimum, the `site` constraint needs to be replaced with `location`

### VRF

- `rd` is unique, but not `name`? 
    - What is the use-case for duplicate `name` values with unique `rd`?
- Similar to what we’ve discussed with `Prefix` and `IPAddress`, the same uniqueness “boundaries” for other relations should be considered here, e.g:
    - `tenant`

**Comment by bryanculver** [comment]
> According to its docstring (but not the actual model implementation), a VLAN "must" belong to a Site or Location:
> 
> > Each VLAN must be assigned to a Site or Location, however VLAN IDs need not be unique within a Site or Location.
> > A VLAN may optionally be assigned to a VLANGroup, within which all VLAN IDs and names but be unique.
> 
> It seems like a common user request/point of confusion is the wish to have a common VLAN definition across multiple sites ([netbox-community/netbox#10854](https://github.com/netbox-community/netbox/discussions/10854), [netbox-community/netbox#10132](https://github.com/netbox-community/netbox/discussions/10132), [netbox-community/netbox#6911](https://github.com/netbox-community/netbox/discussions/6911), [netbox-community/netbox#8619](https://github.com/netbox-community/netbox/discussions/8619), [netbox-community/netbox#9418](https://github.com/netbox-community/netbox/discussions/9418), etc.), which is not really feasible in the current data model. Need to decide whether a VLAN record is "a specific L2 broadcast domain" (site-specific, may exist multiple times within a site) or "a configuration attribute" (globally or locally unique, may be shared across multiple devices and sites)

😬 I can see two desirable use cases:
- Specific VLAN(s) "spanned" across all locations (Location is `null`)
- VLAN(s) "spanned" across specific locations (same VLAN has a to-many association to Location)

Theoretically, we could have:

VLAN 100 [instance 1] ("spanned")
- Building 1
- Building 3

VLAN 100 [instance 2] (not spanned)
- Floor 2

Complicated further with nesting.

I don't see an easy way to support uniqueness (can't create two of the same VLANs at the same location or globally). Providing abstracted searches ("Show me all VLAN 100's across these locations") doesn't necessarily mean they are spanned or should be.

**Comment by jathanism** [comment]
> I don't see an easy way to support uniqueness (can't create two of the same VLANs at the same location or globally). Providing abstracted searches ("Show me all VLAN 100's across these locations") doesn't necessarily mean they are spanned or should be.

Let's also consider other available fields here including `vid` and `name`. Neither of these fields are unique on their own, but perhaps these could also be a unique set along with `location`.

Further `site` and `location` are each currently nullable, so while the docstring claims there must be a relation there, it's not enforced in the data model, at least not from the database constraints.

**Comment by jathanism** [comment]
# DCIM

    $ grep -r "^class.*Model" . | sort
    ./cables.py:class Cable(PrimaryModel, StatusModel):
    ./cables.py:class CablePath(BaseModel):
    ./device_component_templates.py:class ComponentTemplateModel(BaseModel, ChangeLoggedModel, CustomFieldModel, RelationshipModel):
    ./device_component_templates.py:class ConsolePortTemplate(ComponentTemplateModel):
    ./device_component_templates.py:class ConsoleServerPortTemplate(ComponentTemplateModel):
    ./device_component_templates.py:class DeviceBayTemplate(ComponentTemplateModel):
    ./device_component_templates.py:class FrontPortTemplate(ComponentTemplateModel):
    ./device_component_templates.py:class InterfaceTemplate(ComponentTemplateModel):
    ./device_component_templates.py:class PowerOutletTemplate(ComponentTemplateModel):
    ./device_component_templates.py:class PowerPortTemplate(ComponentTemplateModel):
    ./device_component_templates.py:class RearPortTemplate(ComponentTemplateModel):
    ./device_components.py:class BaseInterface(RelationshipModel, StatusModel):
    ./device_components.py:class CableTermination(models.Model):
    ./device_components.py:class ComponentModel(PrimaryModel):
    ./device_components.py:class ConsolePort(CableTermination, PathEndpoint, ComponentModel):
    ./device_components.py:class ConsoleServerPort(CableTermination, PathEndpoint, ComponentModel):
    ./device_components.py:class DeviceBay(ComponentModel):
    ./device_components.py:class FrontPort(CableTermination, ComponentModel):
    ./device_components.py:class Interface(CableTermination, PathEndpoint, ComponentModel, BaseInterface):
    ./device_components.py:class InventoryItem(MPTTModel, ComponentModel):
    ./device_components.py:class PathEndpoint(models.Model):
    ./device_components.py:class PowerOutlet(CableTermination, PathEndpoint, ComponentModel):
    ./device_components.py:class PowerPort(CableTermination, PathEndpoint, ComponentModel):
    ./device_components.py:class RearPort(CableTermination, ComponentModel):
    ./devices.py:class Device(PrimaryModel, ConfigContextModel, StatusModel):
    ./devices.py:class DeviceRedundancyGroup(PrimaryModel, StatusModel):
    ./devices.py:class DeviceRole(OrganizationalModel):
    ./devices.py:class DeviceType(PrimaryModel):
    ./devices.py:class Manufacturer(OrganizationalModel):
    ./devices.py:class Platform(OrganizationalModel):
    ./devices.py:class VirtualChassis(PrimaryModel):
    ./locations.py:class Location(TreeNode, StatusModel, PrimaryModel):
    ./locations.py:class LocationType(TreeNode, OrganizationalModel):
    ./power.py:class PowerFeed(PrimaryModel, PathEndpoint, CableTermination, StatusModel):
    ./power.py:class PowerPanel(PrimaryModel):
    ./racks.py:class Rack(PrimaryModel, StatusModel):
    ./racks.py:class RackGroup(MPTTModel, OrganizationalModel):
    ./racks.py:class RackReservation(PrimaryModel):
    ./racks.py:class RackRole(OrganizationalModel):
    ./sites.py:class Region(MPTTModel, OrganizationalModel):
    ./sites.py:class Site(PrimaryModel, StatusModel):


## Cable

- The only constraints appear to be at the type/id of a/b sides:

```python
            unique_together = (
                ("termination_a_type", "termination_a_id"),
                ("termination_b_type", "termination_b_id"),
            )
```


- Model validation in `Cable.clean()` is incredibly complex. Can some of this instead be moved to `validate_unique()` to at least clarify some of this?

## CablePath

- Constraints:

```python
            unique_together = ("origin_type", "origin_id")
```


    - For example if `origin` is `<Interface: Ethernet1>`
        - `origin_type = dcim.interface` (content_type)
        - `origin_id = origin.id` (pk)
    - This dictates that any given cable path must have a uniquely connected endpoint interface/termination.

## ComponentTemplateModel

> This is the abstract base for all the other `FooTemplate` models

- FK to `device_type` 
- `name`/`_name` are not unique
- No `Meta.unique_together` defined on the abstract base `ComponentTemplateModel`
    - This is duplicated on every other subclass:

```python
    class Meta:
        ordering = ("device_type", "_name")
        unique_together = ("device_type", "name")
```

- Every subclass (except `DeviceBayTemplate`) defines a `type` field with the only difference being the `choices` provided to that field
    - This should be made into a class attribute that could then allow the `type` field to be used as a factor in uniqueness
    - Additionally `type` in all cases has `blank=True` meaning that this selection is not required?

**ConsolePortTemplate**

- type: `ConsolePortTypeChoices`

**ConsoleServerPortTemplate**

- type: `ConsolePortTypeChoices`

**DeviceBayTemplate**

- The only one to not defined a `type`.

**FrontPortTemplate**

- This model extends `Meta.unique_together` to include `rear_port`

```python
        unique_together = (
            ("device_type", "name"),
            ("rear_port", "rear_port_position"),
        )
```

**InterfaceTemplate**

- type: `InterfaceTypeChoices`

**PowerPortTemplate**

- type: `PowerPortTypeChoices`

**PowerOutletTemplate**

- type: `PowerOutletTypeChoices`

**RearPortTemplate**

- Interestingly this model does not extend uniqueness to account for `front_port`, but may not need to so long as the `FrontPortTemplate` validation works

----------

##  BaseInterface

> Base for `dcim.nterface` and `virtualization.VMInterface`

- No base uniqueness constraints outside of FK/GFK relations
- FK to `self` for `parent_interface`
- FK to `self` for `bridge`

## CableTermination

> Base for all cable termination objects

- No base uniqueness constraints outside of FK/GFK relations
- FK to `cable`
- GFK to `_cable_peer_type`, `_cable_peer_id`

## ComponentModel

> Base for any model that has a parent device

- FK to `device`
- `name`/`_name` not unique

## ConsolePort

- type: `ConsolePortTypeChoices`
- Constraints:

```python
            unique_together = ("device", "name")
```

## ConsoleServerPort
- type: `ConsolePortTypeChoices`
- Constraints:

```python
            unique_together = ("device", "name")
```

## DeviceBay

- `installed_device` one-to-one (FK w/ unique) to `Device`
- Constraints:

```python
            unique_together = ("device", "name")
```

## FrontPort

- type: `PortTypeChoices`
- Constraints:

```python
        unique_together = (
            ("device", "name"),
            ("rear_port", "rear_port_position"),
        )
```

## Interface

- FK to `self` for `lag`
- Validation is absurdly complex and is split-brained between LAG, parent interface, bridge, and physical/virtual interface types.
- Constraints:

```python
            unique_together = ("device", "name")
```

## InventoryItem

- `parent` as `TreeForeignKey` to `self`
    - NB: This will need to be migrated to `django-tree-queries` primitives vs. that of `django-mptt`
- FK to `Manufacturer`
- Constraints:

```python
            unique_together = ("device", "parent", "name")
```

## PathEndpoint

> Base for any `CableTermination` subclass representing the end of a `CablePath`.

- `_path` FK to `CablePath`

## PowerOutlet

- type: `PowerOutletTypeChoices`
- Constraints:

```python
            unique_together = ("device", "name")
```

## PowerPort

- type: `PowerPortTypeChoices`
- Constraints:

```python
            unique_together = ("device", "name")
```

## RearPort

- type: `PortTypeChoices`
- Constraints: 

```python
            unique_together = ("device", "name")
```

----------

## Device

- `name` is non-unique and also nullable
    - `null=True` should be removed from this field as it means `None` or `""` are valid values
- Constraints:

```python
        unique_together = (
            ("site", "tenant", "name"),  # See validate_unique below
            ("rack", "position", "face"),
            ("virtual_chassis", "vc_position"),
        )
```

- `site` constraint must be replaced with `location`
- `asset_tag` is unique
- FKs
    - `device_type` → `DeviceTyper`
    - `device_role` → `DeviceRole`
    - `platform` → `Platform`
    - `rack` → `Rack`
    - `cluster` → `Cluster`
    - `device_redundancy_group` → `DeviceRedundancyGroup`
    - `secrets_group` → `SecretGroup`
- OneToOnes
    - `primary_ip4` → `IPAddress` (v4)
    - `primary_ip6` → `IPAddress` (v6)
- `validate_unique()` is overloaded as follows to assert uniqueness for `site` or `tenant`:

```python
        def validate_unique(self, exclude=None):
    
            # Check for a duplicate name on a device assigned to the same Site and no Tenant. This is necessary
            # because Django does not consider two NULL fields to be equal, and thus will not trigger a violation
            # of the uniqueness constraint without manual intervention.
            if self.name and hasattr(self, "site") and self.tenant is None:
                if Device.objects.exclude(pk=self.pk).filter(name=self.name, site=self.site, tenant__isnull=True):
                    raise ValidationError({"name": "A device with this name already exists."})
    
            super().validate_unique(exclude)
```

- `clean()` is very complex to account for all the permutations of the foreign keys not having any database-level constraints

## DeviceRedundancyGroup

- `name` is unique and is likely sufficient
- `slug` can be removed

## DeviceRole

- `name` is unique and is likely sufficient
- `slug` can be removed
- We’ve talked about merging `DeviceRole` and `Role` (#1063)

## DeviceType
-
- FK to `Manufacturer`
- Constraints:

```python
            unique_together = [
                ["manufacturer", "model"],
                # TODO: Remove unique_together to make slug globally unique. This would be a breaking change.
                ["manufacturer", "slug"],
            ]
 ```


- As we’ve discussed elimination of `slug`, this field should be replaced by a `name` field and should be unique

## Manufacturer

- `name` is unique and is likely sufficient
- `slug` can be removed

## Platform

- `name` is unique and is likely sufficient
- `slug` can be removed
- FK to `Manufacturer` (nullable)

## VirtualChassis

- `master` 1-to-1 (FK w/ unique) `Device`
- `name` is not unique but should be
    - or perhaps a `unique_together` of `(``"``name``"``,` `"``domain``"``)`?

**Comment by jathanism** [comment]
# Core

- Not really applicable because core only publishes generic model bases including `BaseModel`, `OrganizationalModel`, and `PrimaryModel`.
    - We might consider merging `OrganizationalModel` and `PrimaryModel` as the only difference between them is that `PrimaryModel` includes `tags`
- Base models should inherit from `django-natural-keys` base `NaturalKeyModel` and use `NaturalKeyModelManager` so that…
    - `natural_key()` is automatically provided using the uniqueness constraints
        - Currently for each model, we must define `natural_key()` method 
    - `Foo.objects.get_by_natural_key()` is also automatically provided, reducing boilerplate
        - Currently for each model, we must subclass `RestrictedQuerySet` in order to publish a `get_by_natural_key()` method
        - And then set `objects = FooRestricrtedQuerySet.as_manager()` on the model
- Base models should also provide `get_absolute_url()` so that each model doesn’t have to hard-code this as well
    - e.g. If we’re aligning around `pk` for all objects, then this is even easier in that we know the app_label and model_name for the model, so we can automatically have something like:
    
```python
    class BaseModel(models.Model):
        def get_absolute_url(self):
            return reverse(get_route_for_model(self), args=[self.pk])
```

**Comment by jathanism** [comment]
Collated list mapped by filename of slug/uniqueness 2.0 TODO items:

```
nautobot/dcim/api/serializers.py
- # 2.0 TODO: Remove if/when slug is globally unique. This would be a breaking change.
- # 2.0 TODO: Remove if/when slug is globally unique. This would be a breaking change.
- # 2.0 TODO: Remove if/when slug is globally unique. This would be a breaking change.
- # 2.0 TODO: Remove if/when slug is globally unique. This would be a breaking change.

nautobot/dcim/models/devices.py
- # 2.0 TODO: Remove unique=None to make slug globally unique. This would be a breaking change.
- # 2.0 TODO: Remove unique_together to make slug globally unique. This would be a breaking change.

nautobot/dcim/models/racks.py
- # 2.0 TODO: Remove unique=None to make slug globally unique. This would be a breaking change.
- # 2.0 TODO: Remove unique_together to make slug globally unique. This would be a breaking change.

nautobot/ipam/api/serializers.py
- # 2.0 TODO: Remove if/when slug is globally unique. This would be a breaking change.
- # 2.0 TODO: Remove if/when slug is globally unique. This would be a breaking change.

nautobot/ipam/models.py
- # 2.0 TODO: Remove unique=None to make slug globally unique. This would be a breaking change.
- # 2.0 TODO: since site is nullable, and NULL != NULL, this means that we can have multiple non-Site VLANGroups
- # 2.0 TODO: Remove unique_together to make slug globally unique. This would be a breaking change.
- # 2.0 TODO: since group is nullable and NULL != NULL, we can have multiple non-group VLANs with
```

**Comment by jathanism** [comment]
# Circuits

```
    $ grep -r "^class.*Model" nautobot/circuits/models.py | sort
    nautobot/circuits/models.py:class Circuit(PrimaryModel, StatusModel):
    nautobot/circuits/models.py:class CircuitTermination(PrimaryModel, PathEndpoint, CableTermination):
    nautobot/circuits/models.py:class CircuitType(OrganizationalModel):
    nautobot/circuits/models.py:class Provider(PrimaryModel):
    nautobot/circuits/models.py:class ProviderNetwork(PrimaryModel):
```

## ProviderNetwork
- `name` is NOT unique, see constraints below
- `slug` should be removed
- Constraints:

```python
        constraints = (
            models.UniqueConstraint(fields=("provider", "name"), name="circuits_providernetwork_provider_name"),
        )
        unique_together = ("provider", "name")
```

    - Why are there both a `UniqueConstraint` and `unique_together` for the same fields? This seems broken.

## Provider

- `name` is unique and is likely sufficient
- `slug` can be removed
- Does not implement `natural_key()`

## CircuitType

- `name` is NOT unique but should be
- `slug` should be removed

## Circuit
- No unique fields at all
- FKs
    - `provider` → `Provider`
    - `type` → `CircuitType`
    - `tenant` → `Tenant`
    - `termination_a` → `CircuitTermination`
    - `termination_z` → `CircuitTermination`
- Constraints:

```python
            unique_together = ["provider", "cid"]
```

- Similar to what we’ve discussed with `Prefix` and `IPAddress`, the same uniqueness “boundaries” for other relations should be considered here, e.g:
    - `tenant`
    - `role`

## CircuitTermination

- No unique fields at all
- FKs
    - `site` → `Site`
    - `provider_network` → `ProviderNetwork`
    - `site` → `Site`
    - `location` → `Location`
- Constraints:

```python
            unique_together = ["circuit", "term_side"]
```

**Comment by jathanism** [comment]
# Tenancy

```
    $ grep -r "^class.*Model" nautobot/tenancy/models.py | sort
    nautobot/tenancy/models.py:class Tenant(PrimaryModel):
    nautobot/tenancy/models.py:class TenantGroup(MPTTModel, OrganizationalModel):
```

## TenantGroup

- `name` is unique and is likely sufficient
- `slug` can be removed
- Does not implement `natural_key()`

## Tenant

- `name` is unique and is likely sufficient
- `slug` can be removed
- Does not implement `natural_key()`

**Comment by jathanism** [comment]
# Users

```
    $ grep -r "^class.*Model" nautobot/users/models.py | sort
    nautobot/users/models.py:class ObjectPermission(BaseModel):
    nautobot/users/models.py:class Token(BaseModel):
    nautobot/users/models.py:class User(BaseModel, AbstractUser):
```

## User

- n/a

## Token

- n/a

## ObjectPermission

- No uniqueness constraints whatsoever
    - This means the same exact object permission could be implemented and assigned with no reasonable way to differentiate them
    - At a minimum I think that `name` should be made to be unique and be the natural key
- Several m2m relations
    - `object_types` → `ContentType`
    - `groups` → `Group`
    - `users` → `User`
- Does not (can not) implement `natural_key()`

**Comment by jathanism** [comment]
# Virtualization

```
    $ grep -r "^class.*Model" nautobot/virtualization/models.py | sort
    nautobot/virtualization/models.py:class Cluster(PrimaryModel):
    nautobot/virtualization/models.py:class ClusterGroup(OrganizationalModel):
    nautobot/virtualization/models.py:class ClusterType(OrganizationalModel):
    nautobot/virtualization/models.py:class VMInterface(BaseModel, BaseInterface, CustomFieldModel, NotesMixin):
    nautobot/virtualization/models.py:class VirtualMachine(PrimaryModel, ConfigContextModel, StatusModel):
```

## ClusterType

- `name` is unique and is likely sufficient
- `slug` can be removed
- Does not implement `natural_key()`

## ClusterGroup

- `name` is unique and is likely sufficient
- `slug` can be removed
- Does not implement `natural_key()`
- Further, could this just go way entirely in exchange for `DynamicGroup(content_type=``"``virtualization.Cluster``"``)` ?
- `ClusterType` and `ClusterGroup` are identical models.
Cluster
- `name` is unique, yet there are several FKs that might need to be considered
- FKs
    - `group` → `ClusterGroup`
    - `tenant` - `Tenant`
    - `site` → `Site`
    - `location` → `Location`

## VirtualMachine

- To be merged with `Device`
- Same concerns as `Device`

## VMInterface
- To be merged with `Interface`
- Same concerns as `Interface`

**Comment by jathanism** [comment]
# Extras

```
    $ grep -r "^class.*Model" nautobot/extras/models | sort
    nautobot/extras/models/change_logging.py:class ChangeLoggedModel(models.Model):
    nautobot/extras/models/change_logging.py:class ObjectChange(BaseModel):
    nautobot/extras/models/customfields.py:class ComputedField(BaseModel, ChangeLoggedModel, NotesMixin):
    nautobot/extras/models/customfields.py:class CustomField(BaseModel, ChangeLoggedModel, NotesMixin):
    nautobot/extras/models/customfields.py:class CustomFieldChoice(BaseModel, ChangeLoggedModel):
    nautobot/extras/models/customfields.py:class CustomFieldModel(models.Model):
    nautobot/extras/models/datasources.py:class GitRepository(PrimaryModel):
    nautobot/extras/models/groups.py:class DynamicGroup(OrganizationalModel):
    nautobot/extras/models/groups.py:class DynamicGroupMembership(BaseModel):
    nautobot/extras/models/jobs.py:class Job(PrimaryModel):
    nautobot/extras/models/jobs.py:class JobHook(OrganizationalModel):
    nautobot/extras/models/jobs.py:class JobLogEntry(BaseModel):
    nautobot/extras/models/jobs.py:class JobResult(BaseModel, CustomFieldModel):
    nautobot/extras/models/jobs.py:class ScheduledJob(BaseModel):
    nautobot/extras/models/jobs.py:class ScheduledJobs(models.Model):
    nautobot/extras/models/models.py:class ConfigContext(BaseModel, ChangeLoggedModel, ConfigContextSchemaValidationMixin, NotesMixin):
    nautobot/extras/models/models.py:class ConfigContextModel(models.Model, ConfigContextSchemaValidationMixin):
    nautobot/extras/models/models.py:class ConfigContextSchema(OrganizationalModel):
    nautobot/extras/models/models.py:class CustomLink(BaseModel, ChangeLoggedModel, NotesMixin):
    nautobot/extras/models/models.py:class ExportTemplate(BaseModel, ChangeLoggedModel, RelationshipModel, NotesMixin):
    nautobot/extras/models/models.py:class FileAttachment(BaseModel):
    nautobot/extras/models/models.py:class FileProxy(BaseModel):
    nautobot/extras/models/models.py:class GraphQLQuery(BaseModel, ChangeLoggedModel, NotesMixin):
    nautobot/extras/models/models.py:class HealthCheckTestModel(BaseModel):
    nautobot/extras/models/models.py:class ImageAttachment(BaseModel):
    nautobot/extras/models/models.py:class Note(BaseModel, ChangeLoggedModel):
    nautobot/extras/models/models.py:class Webhook(BaseModel, ChangeLoggedModel, NotesMixin):
    nautobot/extras/models/relationships.py:class Relationship(BaseModel, ChangeLoggedModel, NotesMixin):
    nautobot/extras/models/relationships.py:class RelationshipAssociation(BaseModel):
    nautobot/extras/models/relationships.py:class RelationshipModel(models.Model):
    nautobot/extras/models/secrets.py:class Secret(PrimaryModel):
    nautobot/extras/models/secrets.py:class SecretsGroup(OrganizationalModel):
    nautobot/extras/models/secrets.py:class SecretsGroupAssociation(BaseModel):
    nautobot/extras/models/statuses.py:class Status(BaseModel, ChangeLoggedModel, CustomFieldModel, RelationshipModel, NotesMixin):
    nautobot/extras/models/statuses.py:class StatusModel(models.Model):
    nautobot/extras/models/tags.py:class Tag(TagBase, BaseModel, ChangeLoggedModel, CustomFieldModel, RelationshipModel, NotesMixin):
    nautobot/extras/models/tags.py:class TaggedItem(BaseModel, GenericUUIDTaggedItemBase):
```


## ChangeLoggedModel
- n/a

## ComputedField

-  `slug` is unique and we might rename it to `name` it here for alignment with `CustomField.name`
- Constraints:

```python
            unique_together = ("content_type", "label")
```

## ConfigContext

- `name` is not unique 
- FKs
    - `owner_content_type` → `ContentType`
    - `schema` → `ConfigContextSchema`
- A bunch of M2Ms:

```python
        regions = models.ManyToManyField(to="dcim.Region", related_name="+", blank=True)
        sites = models.ManyToManyField(to="dcim.Site", related_name="+", blank=True)
        locations = models.ManyToManyField(to="dcim.Location", related_name="+", blank=True)
        roles = models.ManyToManyField(to="dcim.DeviceRole", related_name="+", blank=True)
        device_types = models.ManyToManyField(to="dcim.DeviceType", related_name="+", blank=True)
        device_redundancy_groups = models.ManyToManyField(to="dcim.DeviceRedundancyGroup", related_name="+", blank=True)
        platforms = models.ManyToManyField(to="dcim.Platform", related_name="+", blank=True)
        cluster_groups = models.ManyToManyField(to="virtualization.ClusterGroup", related_name="+", blank=True)
        clusters = models.ManyToManyField(to="virtualization.Cluster", related_name="+", blank=True)
        tenant_groups = models.ManyToManyField(to="tenancy.TenantGroup", related_name="+", blank=True)
        tenants = models.ManyToManyField(to="tenancy.Tenant", related_name="+", blank=True)
        tags = models.ManyToManyField(to="extras.Tag", related_name="+", blank=True)
```

- Constraints:

```python
            unique_together = [["name", "owner_content_type", "owner_object_id"]]
```

## ConfigContextModel

- Abstract base so largely n/a
- Several FKs

## ConfigContextSchema

- `name` is not unique and should be IMO
- `slug` should be removed
- Constraints:

```python
        constraints = [
            models.UniqueConstraint(fields=["name", "owner_content_type", "owner_object_id"], name="unique_name_owner"),
        ]
```

## CustomField

- n/a already covered in #824

## CustomFieldChoice

- n/a already covered in #824

## CustomFieldModel

- n/a

## CustomLink

- `name` is unique and should be sufficient
- Does not implement `natural_key()`

## DynamicGroup

- `name` is unique and should be sufficient
- `slug` can be removed
- Implements `natural_key()`

## DynamicGroupMembership

- n/a already implements `natural_key()`

## ExportTemplate

- No uniqueness except through constraints
- FKs
    - `owner_content_type` → `ContentType`
    - `content_type` → `ContentType`
- GFK for `owner_content_type`/`owner_object_id`
- Constraints:

```python
            unique_together = [["content_type", "name", "owner_content_type", "owner_object_id"]]
```

## FileAttachment

- No uniqueness, internally used by Jobs, so possibly n/a

## FileProxy

- No uniqueness, internally used by Jobs, so possibly n/a

## GitRepository

- `name` is not unique and should be
- `slug` should be removed
- No other constraints
- FK `secrets_group` → `SecretsGroup`

## GraphQLQuery

- `name` is unique and is likely sufficient
- `slug` can be removed

## HealthCheckTestModel

- `title` is the only field and this is only used for testing
- n/a

## ImageAttachment

- No uniqueness constraints
- We might consider `name` or a 2-tuple of `name, content_type`

## Job

- No unique fields
- Constraints:

```python
            unique_together = [
                ("source", "git_repository", "module_name", "job_class_name"),
                ("grouping", "name"),
            ]
```

- Also overloads `validate_unique()`:


```python
        def validate_unique(self, exclude=None):
            """
            Check for duplicate (source, module_name, job_class_name) in the case where git_repository is None.
    
            This is needed because NULL != NULL and so the unique_together constraint will not flag this case.
            """
            if self.git_repository is None:
                if Job.objects.exclude(pk=self.pk).filter(
                    source=self.source, module_name=self.module_name, job_class_name=self.job_class_name
                ):
                    raise ValidationError(
                        {"job_class_name": "A Job already exists with this source, module_name, and job_class_name"}
                    )
    
            super().validate_unique(exclude=exclude)
```

## JobHook

- `name` is unique and should be sufficient
- `slug` can be removed
- FK `job` → `Job`
- M2M `content_types` → `ContentType`
- No other constraints

## JobLogEntry

- No uniqueness constraints
- FK `job_result` → `JobResult`

## JobResult

- `job_id` is unique
- No other uniqueness constraints
- FKs
    - `job_model` → `Job`
    - `user` → `User`
    - `obj_type` → `ContentType`
    - `schedule` → `ScheduledJob`
 
## Note

- No uniqueness constraints except FK/GFK relations
- FKs
    - `user` → `User`

## ObjectChange

- n/a

## Relationship

- `name` is unique and should be sufficient
- FKs
    - `source_type` → `ContentType`
    - `destination_type` → `ContentType`
    - 
- `slug` probably needs to stay for programmable interfaces like GraphQL

## RelationshipAssociation

- No unique fields but constraints are good to go!
- Constraints:


```python
        unique_together = (
            "relationship",
            "source_type",
            "source_id",
            "destination_type",
            "destination_id",
        )
```


- Doest not implement `natural_key()`

## RelationshipModel

- n/a

## ScheduledJob

- `name` is not unique
- FKs
    - `job_model` → `Job`
    - `user` → `User`
    - `approved_by_user` → `User`
- No other constraints
- A conditional set of natural keys might be considered here for different schedule types
    - e.g. `name` and `one_off=True` must be unique while `last_run_at=None`
    - One a scheduled job has been ran, the `name` can be re-used
    - If it’s a recurring job, the `name` cannot be reused
    - etc.
 
## ScheduledJobs

- `ident` is unique and set to PK
- No other uniqueness constraints

## Secret

- `name` is unique and should be sufficient
- `slug` should be removed
- Does not implement `natural_key()`

## SecretsGroup

- `name` is unique and should be sufficient
- `slug` should be removed
- m2m to `Secret` through `SecretsGroupAssociation`
- Does not implement `natural_key()`

## SecretsGroupAssociation

- No unique fields but constraints are good to go!
- Constraints:

```python
            unique_together = (
                # Don't allow the same access-type/secret-type combination to be used more than once in the same group
                ("group", "access_type", "secret_type"),
            )
```

- Does not implement `natural_key()` but is ready to!

## Status

- n/a already implements `natural_key()`
- Except that `slug` should be removed

## StatusModel

- n/a

## Tag

- `name` is unique and should be sufficient
- `slug` is inherited from `taggit.models.TagBase` and likely can’t be easily removed
- Does not implement `natural_key()`

## TaggedItem

- n/a

## Webhook

- `name` is unique and should be sufficient
- Does not iplemente `natural_key()`
