### ISSUE TITLE
500 - FieldError When attempting to sort by prefix in UI (Affects others explained below)

### ISSUE THREAD

**Issue by FragmentedPacket** [nautobot/nautobot#278]
### Environment
* Python version: 3.7
* Nautobot version: 1.0.0b3

### Steps to Reproduce
1. Attempt to sort by Prefix (ipam/prefix) on prefix's UI list view
2. FieldError occurs

This also happens when attempting to sort IP addresses and Aggregates on their respective list views

### Expected Behavior
Sort prefixes/ip address/aggregates appropriately

### Observed Behavior
500 for FieldError

```
exception
FieldError: Cannot resolve keyword 'prefix' into field. Choices are: _custom_field_data, broadcast, children, created, description, id, is_pool, last_updated, network, parents, prefix_length, role, role_id, site, site_id, status, status_id, tagged_items, tags, tenant, tenant_id, vlan, vlan_id, vrf, vrf_id
```

**Comment by jathanism** [comment]
More IPAM field type bugs. This also affects `IPAddress` and `Aggregate` objects.

This can be solved with a quick fix to the respective column objects by adding an `order_by` argument. (See: https://django-tables2.readthedocs.io/en/latest/pages/ordering.html#ordering-by-accessors)
