### ISSUE TITLE
CSS footer margin is gone and swagger UI authorization box is broken

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#2789]
### Environment
* Nautobot version (Docker tag too if applicable): v1.5.1b1
* Python version: 3.10.7
* Database platform, version: Postgres 13
* Middleware(s):

### Steps to Reproduce
Go to test.nautobot.com, scroll to the footer and then navigate to the API 

![image](https://user-images.githubusercontent.com/75227981/200877779-41df0791-10c6-4e55-81fd-6be7a6f3f455.png)
![image](https://user-images.githubusercontent.com/75227981/200877839-3171dd45-7ebe-4098-9ceb-3e7acca0cc0b.png)
![image](https://user-images.githubusercontent.com/75227981/200877916-bbac42cb-c1bf-4a6e-8e0c-25b447c76ab2.png)

It looks like this was a regression from #2553. #2747 resolves the footer issue without impacting the margin or the swagger API. Reverting #2553 appears to resolve this issue.

**Comment by glennmatthews** [comment]
In general if we're making changes to the header and footer, we need to check for impact to:

1) Ordinary Nautobot UI pages
2) Swagger UI
3) GraphiQL

**Comment by gsnider2195** [comment]
> In general if we're making changes to the header and footer, we need to check for impact to:
> 
> 1. Ordinary Nautobot UI pages
> 2. Swagger UI
> 3. GraphiQL

Agreed. After reverting I made sure this looks ok in large and small viewports on the home page, list view with a lot of objects, swagger ui and graphql. We should also check light mode and dark mode.
