### ISSUE TITLE
Changelog difference displays "No changes" for old entries

### ISSUE THREAD

**Issue by u1735067** [nautobot/nautobot#2795]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.7
* Python version: 3.10
* Database platform, version: pgsql
* Middleware(s):

### Steps to Reproduce
1. Install an old (1.2.x) Nautobot version
2. Change some objects
3. Upgrade to the latest 1.4.x
4. Check the objects changelogs

### Expected Behavior
Changelog difference is displayed

### Observed Behavior
Changelog difference displays "No changes" or displays only the new version (for changelog entries of existing objects created in the latest Nautobot version)

### Additional informations

This seems to be caused by https://github.com/nautobot/nautobot/commit/b44947ca5c2429f23033b810e0850c1b776fb8d5 + https://github.com/nautobot/nautobot/commit/fac90d29061825e5a14a36dffbd532ab578e37d5, where an new `object_data_v2` is introduced (v1.3) and `get_snapshots()` (v1.4) uses this field at https://github.com/nautobot/nautobot/blob/v1.4.10/nautobot/extras/views.py#L1595 to display diff, without having fallback to `object_data` for older entries.

**Comment by gsnider2195** [comment]
Possibly related to #1830 #1530
