### ISSUE TITLE
FilterSet Cleanup: Change Shadowed IPAM Fields IPAM

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2807]
Review https://gist.github.com/jathanism/7c585954da4cb1a54997be31991cdaac#ipam for fields to be changed under "Incorrect Fields"

#### Incorrect fields

- `present_in_vrf_id` should be `has_vrf` on the `vrf__rd` field

#### Incorrect fields

- `present_in_vrf_id` should be `has_vrf` on the `vrf__rd` field
- `vlan_vid` should just be called `vlan` and search on the `vid` using `to_field_name`
    - Add `TODO` until #4229 can be addressed
- `mask_length` ( and `__gte/__lte`) should just be replaced with `prefix_length` and support multiple lookup expressions without resorting to method fiilters
    - Automatically generating `lt`,`gt`, etc for these is ideal which when NOT a method filter happens automatically (See: `nautobot.utilities.constants.FILTER_NUMERIC_BASED_LOOKUP_MAP`)

#### Incorrect fields

* `port` -> `ports`

#### Incorrect fields

- `exporting_vrf` -> `exporting_vrfs`
- `importing_vrf` -> `importing_vrfs`

#### Incorrect fields

* `import_target` -> `import_targets`
* `export_target` -> `export_targets`

**Comment by bryanculver** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Engineering-64a875e74842500d9e80e23e/issues/nautobot/nautobot/2807?planning-poker) with Zenhub @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1

**Comment by gsnider2195** [comment]
> vlan_vid should just be called vlan and search on the vid using to_field_name

Probably blocked by #4229

**Comment by bryanculver** [comment]
> > vlan_vid should just be called vlan and search on the vid using to_field_name
> 
> Probably blocked by #4229

Other than that (which could be added as a TODO) is the rest doable/sizeable?

**Comment by glennmatthews** [comment]
>     * `present_in_vrf_id` should be `has_vrf` on the `vrf__rd` field

`present_in_vrf_id` accounts for both `vrfs=value` and `vrfs__export_targets__in=value.import_targets.all()`, in other words both for IPAddress/Prefix that are native to a VRF but also for VRFs that this VRF's networks are imported into. `has_vrf` would have a different semantic; I can add that as a *new* filter field if desired but I don't think it replaces these.

>     * `vlan_vid` should just be called `vlan` and search on the `vid` using `to_field_name`

`vid` is not a globally unique field nor is it a natural key for VLAN objects. I'd expect a `vlan` filter to filter by natural-key or by PK, not by an arbitrary attribute of the vlan?

**Comment by glennmatthews** [comment]
Implemented by #4284.
