### ISSUE TITLE
DynamicGroup Server Error when Region set

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot#2824]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.8 1.4.9 1.5.0
* Python version: 3.8 
* Database platform, version: postgres
* Middleware(s):

### Steps to Reproduce
1. Create dynamic group
2. Add a region as filter
3. save

Can be replicated on demo.nautobot.com and next.demo.nautobot.com

### Expected Behavior
FIlter by region

### Observed Behavior
500 Server Error, `Device has no field named 'site__region'`

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/26559188/201690986-58d75c83-be50-4d64-9ec7-3e1419701ff0.png">

**Comment by jathanism** [comment]
Confirmed. Thanks. This looks related to #2695. No good deed goes unpunished.
