### ISSUE TITLE
Add Child Location from Location Detail View Returns Server Error

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2832]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.0
* Python version: 3.7
* Database platform, version: Postgres
* Middleware(s): NA

### Steps to Reproduce
(all via UI)
1. Create a "Building" `LocationType` and "Room" `LocationType`, "Building" being a parent of "Room"
2. Create a `Location` of "Building" `LocationType`, example "Turner Hall"
3. View the created `Location` detail view
4. Select "Add Child" in bottom right of page (in "Children" table)

### Expected Behavior

Presented with the `Location` create form with parent location set to "Turner Hall".

### Observed Behavior

<img width="721" alt="image" src="https://user-images.githubusercontent.com/31187/201945386-f1f3cdc5-7ea1-48b8-9ea0-63e2808abed3.png">

**Comment by glennmatthews** [comment]
Need to retest with 1.5.1 - this *should* be addressed by #2773.

**Comment by bryanculver** [comment]
Confirmed closed via #2773. This issue is fixed in v1.5.1.
