### ISSUE TITLE
Update dark mode color for new filter selection boxes in 1.5

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot#2838]
### As ...

Ozzie - Operator

### I want ...

The filter selection boxes in Nautobot 1.5 to have a similar theme to the rest of the colors in dark mode.  They are currently a pure black background.

### So that ...

The colors match and the theme looks more consistent overall.

### I know this is done when...

The color of the filter selection boxes is not solid black, but matches (or is similar to) the dark mode background color.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

n/a

### External Dependencies

n/a

**Comment by matt852** [comment]
Example: 
![Screen Shot 2022-11-15 at 11 11 56 AM](https://user-images.githubusercontent.com/536467/201969548-0e9d7fd3-dc2e-4db4-8926-267ad3aa95ac.png)

**Comment by bryanculver** [comment]
Follow-up from: https://github.com/nautobot/nautobot/issues/2508
