### ISSUE TITLE
Epic: 2.0 TODO Housekeeping

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#2854]
### Proposed Changes

Sweep each application and address any lingering `2.0 TODO` items.

- [x] #2855 (Groomed)
- [ ] #2856 (Groomed)
- [ ] #2857 (Groomed)
- [x] #2858 (Groomed)
- [x] #2859
- [x] #2860

### Justification

This is to clean up legacy cruft and address breaking changes for v2 cleanup.

**Comment by bryanculver** [comment]
#2856 and #2857 are small stories at this point and are already tracked in the backlog.
