### ISSUE TITLE
2.0 TODO Housekeeping: Core

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#2855]
## Core
nautobot/core/views/generic.py
- `# 2.0 TODO: Remove this method in 2.0. Can be retrieved from instance itself now`
- `"changelog_url": changelog_url,  # 2.0 TODO: Remove in 2.0. This information can be retrieved from the object itself now.`

**Comment by bryanculver** [comment]
These have been replaced by separate stories that will remove them:

nautobot/core/graphql/schema.py
- `# 2.0 TODO: str_to_var_name is lossy, it may cause different relationships to map to the same rel_name` via #824


nautobot/core/models/generics.py
- `# 2.0 TODO: remove this, force migration to the newer django-taggit API.` #1633
