### ISSUE TITLE
2.0 TODO Housekeeping: Utilities

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#2859]
## Utilities

nautobot/utilities/forms/fields.py
- `filter = django_filters.ModelChoiceFilter  # 2.0 TODO(Glenn): can we rename this? pylint: disable=redefined-builtin`

nautobot/utilities/testing/views.py
- `# 2.0 TODO(jathan): Eliminate the need to overload `_get_base_url()` at all and just rely on `get_route_for_model()``
- `# 2.0 TODO(jathan): Eliminate the need to overload `_get_url()` at all and just rely on `get_route_for_model()``

**Comment by bryanculver** [comment]
Utilities doesn't exist anymore so... DONE!

Moved these items to the core housekeeping story.
