### ISSUE TITLE
content_types field missing from extras/tags serializer

### ISSUE THREAD

**Issue by aj-cruz** [nautobot/nautobot#2864]
### Environment
* Nautobot version: 1.5.1-py3.9 (Docker)
* Python version: 3.9
* Database platform, version: Postgres 14
* Middleware(s):

### Steps to Reproduce
1. ```requests.post("https://nautobot/api/extras/tags/", headers=headers, json=data, verify=False)```
data =
```
{
    "name": "phx-dc-access",
    "color": "c7ea80",
    "content_types": [
        "dcim.device",
        "ipam.vlan"
    ],
    "slug": "phx-dc-access"
}
```

### Expected Behavior
Tag is created with content types limited to dcim|device & ipam|vlan

### Observed Behavior
Tag is created with all content types.
First noticed this using the Nautobot Ansible Collection, confirmed using requests.
Also I don't see the content_types attribute in the swagger schema documentation for extras/tags

**Comment by glennmatthews** [comment]
The `content_types` are only supported when using the REST API version 1.3 and later, and if no API version is specified (as appears to be the case above) the API defaults to version 1.2 in all Nautobot 1.x versions. Unfortunately Django REST Framework just silently discards data that it doesn't understand/support - the `content_types` field doesn't exist in API version 1.2, so it's being ignored in the above case.

See https://docs.nautobot.com/projects/core/en/stable/rest-api/overview/#versioning for more details, but in short - please try adding an `Accept: application/json; version=1.5` header to your request and see if it resolves this issue. (Similarly, try adding `?api_version=1.5` to the URL for the Swagger docs and the `content_types` field should then appear.)

**Comment by aj-cruz** [comment]
Woops, I missed that, thanks
