### ISSUE TITLE
Searching never shows IP

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#287]
### Environment
* Python version: 3.8.5
* Nautobot version: 1.0.0b3

When I search for IP, nothing ever shows.
![image](https://user-images.githubusercontent.com/26114847/114364291-8c2c6580-9b79-11eb-97d8-24dc099ba7f5.png)

But I know it exists because when I search it in the navbar, I can find the prefix and by going to the prefix and it's IPs, I can find the IP.
![image](https://user-images.githubusercontent.com/26114847/114364624-dd3c5980-9b79-11eb-8b4c-683737abca01.png)
![image](https://user-images.githubusercontent.com/26114847/114364737-fcd38200-9b79-11eb-9a1b-f3d3896ff7fc.png)
![image](https://user-images.githubusercontent.com/26114847/114364978-4328e100-9b7a-11eb-8849-5ec38ec2524d.png)

### Steps to Reproduce
1. Try to find existing IP

### Expected Behavior
IP found

### Observed Behavior
No IP found even if it exists

**Comment by jathanism** [comment]
@Thetacz Thanks for this report. I've confirmed this behavior and it appears in our changes the `address` field dropped out of this filter.

**Comment by jathanism** [comment]
This was fixed in #295
