### ISSUE TITLE
Direct parent prefix does not show when viewing IP

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#288]
### Environment
* Python version: 3.8.5
* Nautobot version: 1.0.0b3

When I open an IP, the direct parent prefix is not show in the list of parent prefixes even though it exists.
![image](https://user-images.githubusercontent.com/26114847/114378551-1ed40100-9b88-11eb-903a-3e2c0304305f.png)

This is how it looks in Netbox with the same data:
![image](https://user-images.githubusercontent.com/26114847/114378788-5642ad80-9b88-11eb-8fe4-8966dc68416d.png)

And yes, the prefix with this IP exists in Nautobot:
![image](https://user-images.githubusercontent.com/26114847/114379068-a883ce80-9b88-11eb-840f-3ed54a3a66f5.png)

### Steps to Reproduce
1. Create new prefix
2. Create IP in this prefix
3. Open the IP and try to find the created prefix as last item in list of parent prefixes

### Expected Behavior
Parent prefix is in the list of parent prefix

### Observed Behavior
Direct parent not shown, only parents of that prefix

**Comment by jathanism** [comment]
Confirmed this one, too. Thanks. Seems we have a few weird quirks here.
