### ISSUE TITLE
UI Prototype: Dynamically Load/Hotload React-NodeJS Micro-Frontend (Codename `Rodimus`)

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2889]

**Comment by gsnider2195** [comment]
## Requirements
- Plugins can reuse components from core (Plugin X uses core list view component)
  - [Webpack 5 module federation](https://webpack.js.org/concepts/module-federation/)
- Plugins can modify behavior of core components (Plugin X adds a menu item to the nav bar)
  - TBD

**Comment by gsnider2195** [comment]
# Design

## Use [django collectstatic](https://docs.djangoproject.com/en/4.1/ref/contrib/staticfiles/) to collect js bundles from core and plugins

- [ ] Update `STATICFILES_DIRS` before `collectstatic` runs
  - Use `PLUGINS` config to build dynamically?

## Use [webpack 5 module federation](https://webpack.js.org/concepts/module-federation/) to allow plugins to use components from core

- [ ] Can this be used with static js bundles or does it require being served by node.js?

## Use api to build dynamic core components that can be extended by plugins

- [ ] Nav menu (@timizuoebideri1's react prototype [get-menu](https://github.com/nautobot/nautobot/pull/2272/files#diff-220b8706cba160bd531aa47d67ede85abbbba543c4ed97e59d4dd3512025b7dfR693-R715))
- [ ] Object detail view panels
- [ ] Object detail view extra tabs

**Comment by gsnider2195** [comment]
Working prototype in https://github.com/nautobot/nautobot/tree/gas-2889-ui-micro-frontend-prototype

## Build steps

```sh
cd nautobot-react
npm install
npm run build
cp build/index.html ../nautobot/core/templates/index_js.html
cp build/static/js/* ../nautobot/project-static/js/
cp build/static/css/* ../nautobot/project-static/css/
```

- Start nautobot and navigate to the root view
- Click on `organization > Sites` to go to the site list view

**Comment by gsnider2195** [comment]
Prototype in nextjs at https://github.com/nautobot/nautobot/tree/gas-2889-ui-micro-frontend-prototype-nextjs

**Comment by bryanculver** [comment]
Prototype complete. See #2950
