### ISSUE TITLE
UI Prototype: Compile React-NodeJS Frontend on Server Startup (Codename `Optimus`)

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2890]

**Comment by jathanism** [comment]
My thought is the "what if" we don't necessarily have to compile on startup, allowing the core app and each Nautobot app (née: plugin) to provide their own pre-compiled JS bundle that can be referenced as a part of the front-end application's registry. Can this work?

Here is an article that appears to approach pattern this using a "code-splitting" technique: https://varunon9.medium.com/loading-multiple-bundles-in-react-native-code-splitting-using-metro-44d45530e958
