### ISSUE TITLE
UI Prototype: Run React-NodeJS Parallel w/ Django to Serve Frontend (Codename `Smokescreen`)

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2894]

**Comment by timizuoebideri1** [comment]
# UI Prototype 

This prototype's current focus is on the smooth integration of plugins with nautobot UI's (React) development environment.

## How to get started.
- Clone this nautobot branch -> [nautobot-dev-with-react](https://github.com/nautobot/nautobot/tree/nautobot-dev-with-react)
- Create a plugin
- Add desired `plugin_ui` directory name to Plugin app conf, This would be the name of the directory where all your UI elements would be:
```python
class ExamplePluginConfig(PluginConfig):
   nautobot_ui="example_plugin_ui"
   ...
```
- Run `nautobot-server init_ui <plugin name>` e.g `nautobot-server init_ui example_plugin`. This command would create all required folders and files which are needed for integration with `nautobot_ui`
- Add plugin to `nautobot_config.py`
- Start nautobot server
- Cd into `nautobot` > `nautobot_ui` and start npm server.
- If you go to "/plugins/<plugin-path>," you should be able to see the plugin's welcome page. e.g `/plugins/example-plugin`.
