### ISSUE TITLE
Sorting by computed fields throws a FieldError

### ISSUE THREAD

**Issue by joaopsys** [nautobot/nautobot#2898]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.5
* Python version: 3.8.12
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Create a computed field assigned to a model. For example IP Address. Make that computed field fetch the IP's VRF's RD (example)
2. Add the computed field to the IP Address table view
3. Try to sort the table by the newly created computed field

### Expected Behavior
Either the table is sorted by the computed field selected, or the sorting does nothing

### Observed Behavior
A FieldError is raised

```
FieldError at /ipam/ip-addresses/
Cannot resolve keyword 'cpf_my_computed_field' into field. Choices are: _custom_field_data, assigned_object, assigned_object_id, assigned_object_type, assigned_object_type_id, broadcast, created, description, destination_for_associations, dns_name, host, id, interface, last_updated, nat_inside, nat_inside_id, nat_outside_list, prefix_length, primary_ip4_for, primary_ip6_for, role, services, source_for_associations, status, status_id, tagged_items, tags, tenant, tenant_id, vminterface, vrf, vrf_id
```

Seems similar to https://github.com/nautobot/nautobot/issues/1020 where @jathanism predicted FieldErrors would be present in many other places.

**Comment by glennmatthews** [comment]
Computed fields definitely should not be sortable columns. Thanks for the report!
