### ISSUE TITLE
Correct Existing Natural Keys 3 of 3 [Advanced] - Boundary Uniqueness

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#2909]
## Blocked by: #2900, #3244

```[tasklist]
### VLAN - 3
- [ ] **VLAN Group:** `name` becomes unique with an enumeration for collisions, drop unique with `location`
- [ ] **VLAN:** make `vlan_group` required, keep existing unique together, make default `vlan_group`
```

```[tasklist]
### User - 2
- [ ] **ObjectPermission:** `name` unique, move on. For collisions just enumerate.
```

- **Provider:** `name` is sufficient at this time
- **VRF:** Prefer `(namespace, name)` but `(namespace, rd)` also available
- **Virtualization/Cluster:** Would be good to consider in a future for making `group` part of it but fine for now since `name` is unique

**Comment by glennmatthews** [comment]
> #### Tenancy vs. Global
> 
>     * Duplicate objects can only be in Tenants

Should this read "in *different* Tenants"?

> 
> #### IPAM Duplicates
> 
>     * Use a VRF with `enforce_unique=False`

Personally I'd like to get rid of this as even being an option. Can we instead enumerate the cases where "duplicate" entries are needed and figure out how to design the data model and uniqueness constraints accordingly?

>     * IPAM "Namespaces" should still be a thing, so you could have multiple namespaces per Tenant

Is this being proposed as a new/distinct model from `VRF`?

> 
>     * IPAddress shouldn’t have a relationship to Tenant. It should be inherited from the Prefix.

Not sure I understand why we want to remove this as a feature?

> ## Circuits
> ### Provider
> 
>     * Similar to what we’ve discussed with `Prefix` and `IPAddress`, the same uniqueness “boundaries” for other relations should be considered here, e.g:
>       
>       * `tenant`
>       * `role`

Neither of these are currently fields on a Provider. I'm also not clear on why `role` would be a uniqueness boundary?

> ## IPAM
> 
>     * Tenant/name might not be good for L2 objects (such as VRF, VLAN)
> 
>     * VLAN/location might make sense in this context, but not Tenant?
>       
>       * We might want `name/location` or `vid/location` as an example for VLAN?

I'm honestly not entirely clear what's being proposed for any of these three.

> ### VLAN
> 
>     * Constraints:
> 
> ```python
>         unique_together = [
>             # 2.0 TODO: since group is nullable and NULL != NULL, we can have multiple non-group VLANs with
>             # the same vid and name. We should probably fix this with a custom validate_unique() function.
>             ["group", "vid"],
>             ["group", "name"],
>         ]
> ```
> 
>     * Similar to what we’ve discussed with `Prefix` and `IPAddress`, the same uniqueness “boundaries” for other relations should be considered here, e.g:
>       
>       * `tenant`
>       * `role`

Same here, I'm not clear why we'd want to permit two VLANs with the same name/group/vid/tenant but differing Roles?

> 
>     * `name` is not unique and IMO should absolutely be unique, unless we consider the `unique_together` along with other boundaries described above

VLAN "voice" at Location Alpha may have a different VID than VLAN "voice" at Location Beta. Pretty sure we want to still keep this possible to model.

>       
>       * `name`, `vid` may be a great idea for `unique_together`

As opposed to the current `(vlan_group, vid)` and `(vlan_group, name)` constraints? What's the benefit?


> ## Users
> ### ObjectPermission
> 
>     * No uniqueness constraints whatsoever
> 
>     * This means the same exact object permission could be implemented and assigned with no reasonable way to differentiate them
>       
>       * At a minimum I think that name should be made to be unique and be the natural key

This seems reasonable to me.

> 
>     * Several m2m relations
>       
>       * `object_types` → `ContentType`
>       * `groups` → `Group`
>       * `users` → `User`

Yes? These all seem necessary and appropriate to me. 

>     * Do we want unique permissions per tenant, or at least to have it be an optional constraint of some sort?

Not sure how we'd model that or what the benefit would be. Can you clarify?

> ## Virtualization
> ### Cluster
> 
>     * name is unique, yet there are several FKs that might need to be considered
> 
>     * FKs
>       
>       * `group` → `ClusterGroup`
>       * `tenant` - `Tenant`
>       * `site` →` Site`
>       * `locatio`n → `Location`

If you're proposing making `name` non-globally-unique for Cluster, I think that's an idea worth considering.

**Comment by bryanculver** [comment]
Carved into #3850, #3851
