### ISSUE TITLE
Inconsistent Device KeyError Exceptions when running jobs with Celery billiard multi-processing

### ISSUE THREAD

**Issue by aj-cruz** [nautobot/nautobot#2912]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.1-py3.9 (Docker)
* Python version: 3.9.15
* Database platform, version: postgres 14
* Middleware(s): celery 5.2.7, billiard 3.6.4.0, napalm 3.4.1

### Steps to Reproduce
1. Add a new job to Nautobot jobs folder that uses celery billiards multiprocessing to gather NAPALM facts (get_facts getter) from Nautobot device inventory. Here's my job file: [softwarelist.py](https://gist.github.com/aj-cruz/79f82fdb174dbb8ba1c7d4e2aa29b86e)
2. Run job

### Expected Behavior
Facts returned for all devices

### Observed Behavior
Inconsistent results. Sometimes it completes with no errors, sometimes one or more devices fail with KeyError exceptions.
I don't know if it is my code (admittedly I'm not the best coder), Nautobot, or Celery, but I've got a few different log files for the various results:
- [3-failed-job.log](https://gist.github.com/aj-cruz/b1edbf35f2b306a652f7b59a16bf34d8)
- [1-failed-job.log](https://gist.github.com/aj-cruz/d4656f4eb42fccf352e70ea02d57e06c)
- [0-failed-job.log](https://gist.github.com/aj-cruz/20210e4ae4ee191fcc0c701034bd7c83)

If I remove multi-processing and do the NAPALM functions sequentially, I have no problem they always finish.

I haven't tried to dig into it, I'm not sure what mixins.py is doing here:
```
nautobot-docker-compose-celery_worker-1     | Traceback (most recent call last):
nautobot-docker-compose-celery_worker-1     |   File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 173, in __get__
nautobot-docker-compose-celery_worker-1     |     rel_obj = self.field.get_cached_value(instance)
nautobot-docker-compose-celery_worker-1     |   File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
nautobot-docker-compose-celery_worker-1     |     return instance._state.fields_cache[cache_name]
nautobot-docker-compose-celery_worker-1     | KeyError: 'primary_ip4'
```
but I know I'm not using the ```primary_ip4``` field in my code.

**Comment by lampwins** [comment]
Unfortunately, we are unable to dive into these sorts of general debugging issues. If you are able to narrow down the specific issue, we will be able to address it.
