### ISSUE TITLE
IPAM Overhaul: Prefix-Prefix Parent Concrete Relationship

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2915]
Similar to #1673 in concert with #1032, Make Prefixes have a concrete relationship to each other for performance and get away from derivative assumed parent/children.

Address issues like:

- #780

```[tasklist]
### TODO
- [ ] https://github.com/nautobot/nautobot/issues/3466
- [ ] https://github.com/nautobot/nautobot/issues/3467
- [ ] #3681
- [ ] #3687 
```

**Comment by jathanism** [comment]
Watch this space for better clarity based on uniqueness constraint discussions.
