### ISSUE TITLE
IPAM Overhaul: Refactor utilization/allocation calculation logic

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#2916]
- [ ] Based on #2915, make calculations work
- [ ] Separate UI context for prefix vs IP address calculations
- [ ] Address #2648

**Comment by bryanculver** [comment]
Need to do #2531 so solving this with that story (and IPAddress) while moving the existing code.

**Comment by gsnider2195** [comment]
Adding a second utilization column slows down the list view even more (over 5 seconds to load 46 prefixes on my dev machine). I'm going to combine the columns for now.
