### ISSUE TITLE
RIRs Aggregate Count Not Updating

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#292]
### Environment
* Python version: 3.6
* Nautobot version: 1.0.0b3

### Steps to Reproduce
1. Create RIR named `RFC1918`
2. Add aggregate underneath `RFC1918` named `10.0.0.0/8`
3. Add another aggregate in the same RIR, named `192.168.0.0/16` and `172.16.0.0/12`
4. Navigate to primary RIR page, Aggregate count does not get updated

### Expected Behavior

Expected the count to show `3`

### Observed Behavior

Count showed `1`

### Additional Testing Notes

Attempted to invalidate cache through @nniehoff as this was tested on hosted host, and then the right count appeared. *However*, immediately after went and added a fourth Aggregate under the RIR and it still showed 3 after the update, where it should have shown 4. 

Also present in 1.0.0b1

**Comment by jathanism** [comment]
I am not able to reproduce this on beta3 or develop branch head with or without caching enabled. Based on your additional notes, it seems as if there may be some kind of invalidation bug with aggregates or RIRs, but to confirm we'll need to be able to consistently reproduce this.

**Comment by tim-fiola** [comment]
I was unable to replicate using beta 4

**Comment by nniehoff** [comment]
@jvanderaa were you able to reproduce this locally or only on demo.nautobot.com?

**Comment by jvanderaa** [comment]
I was able to recreate locally as well on full install. Not on the dev environment as there were errors with Redis there.

**Comment by FragmentedPacket** [comment]
I started to try and reproduce this and I was able to with @jvanderaa's steps.

You can have it update right after creating an Aggregate within the RIR, by going to the list view of the RIR and them clicking on the **Aggregates** column header, but once you refresh the page, it reverts back to the previous count, until a specific time or some trigger (??) happens and then the page shows the correct amount with the newly added aggregate.

**Comment by jvanderaa** [comment]
I saw this bug as well when working on the Manufacturers and Device Types. Done:

1. Create new Manufacturer
2. Add device types 
3. Verify the device types are there
4. Delete the all device types added
5. Check the manufacturers page and the count is still there

@jathanism @FragmentedPacket

**Comment by FragmentedPacket** [comment]
You're correct. Basically anything with `LinkedCountColumn` appears to be affected.

**Comment by dgarros** [comment]
Sounds like this could be a caching issue
As far as I understand most `LinkedCountColumn` field are leveraging the `count_related` function to generate a SubQuery

here is an example of query leveraging `count_related` to insert the number of associated devices for each platform
```pyhon
Rack.objects.prefetch_related("site", "group", "tenant", "role", "devices__device_type").annotate(
        device_count=count_related(Device, "rack")
    )
```
and here is the code of count_related for reference 
https://github.com/nautobot/nautobot/blob/develop/nautobot/utilities/utils.py#L97

Just curious, has someone tested if the issue is present in Netbox as well ?

**Comment by FragmentedPacket** [comment]
Yes, one of my updates shows that is is happening in NetBox as well.

Is there something quick that can be done or is this working as intended? Or some kind of signal to flush cache for the object that gets updated?

**Comment by carbonarok** [comment]
Unable to reproduce this issue. If this issue comes back please feel free to re-open this bug.
