### ISSUE TITLE
Syntax highlighting for config contexts

### ISSUE THREAD

**Issue by UnityDG** [nautobot/nautobot#2929]
### As ...

Austin - Network Automation Engineer

### I want ...

Syntax highlighting for config contexts.

### So that ...

I can easily tell data apart in config contexts with minimal effort.

### I know this is done when...

- Syntax highlighting is present on the editor for config contexts
- Syntax highlighting is present on the config context page for assets.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- N/A

**Comment by lampwins** [comment]
We have implemented general JSON & YAML syntax highlighting the detail views in 2.2. We may be able to explore syntax highlighting in the editor during future UI work.
