### ISSUE TITLE
POST to `/circuits/circuit-types/<slug>/delete/` returning a 404 in v1.5.3

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#2936]
### Environment
* Nautobot version (Docker tag too if applicable): v1.5.3
* Python version: 
* Database platform, version: 
* Middleware(s):

### Steps to Reproduce
1. Create a test circuit type
2. Navigate to the circuit type object detail view
3. Click on delete to try to delete the object
4. Click confirm

### Expected Behavior
Circuit type deletes successfully

### Observed Behavior
Nautobot returns a 404

**Comment by bryanculver** [comment]
This was introduced due to #2473 / #2644 because we "fixed the glitch" of DRF advertising we support multipart and urlencoded forms on the API.
