### ISSUE TITLE
Relationship from/to object with big population makes object's list unusably slow 

### ISSUE THREAD

**Issue by apanagio** [nautobot/nautobot#2944]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.4 ( beb9c335ae90 )
* Python version: 3.10
* Database platform, version: PostgreSQL 14.5
* Middleware(s): apache2 reverse proxy

### Steps to Reproduce
1. Create one to many relationship from site to site
2. Create many sites (~30000)
3. Make sure relationship is not hidden in source nor destination object
4. Go to sites page (# per page does not matter)

### Expected Behavior
Load list of sites in less than 5 seconds

### Observed Behavior
List of sites loads in more than 60 seconds, sometimes it doesn't load at all.
If the relationship is hidden in source and destination, there is no delay

**Comment by itdependsnetworks** [comment]
I am not the expert to comment if there is an easy or direct fix to the specific github issue opened here, that being said:

I think this is a good point. There are tradeoffs for performance and scalability compared to developer efficiency. While it is clear, there is no "one size fits all" recommendations we can make, I do think we can document better the performance impact in each design choice made.

In a similar issue, for golden config, I documented the potential impact here: https://docs.nautobot.com/projects/golden-config/en/latest/user/app_feature_sotagg/#performance which simply makes it more clear to the user to consider the performance impact for them.

**Comment by bryanculver** [comment]
Computed fields and Relationships were discussed to be performance impacts and there isn’t much we can do to make them more-so; computed fields must be evaluated at display time and cannot be DB optimized, and relationships are generic foreign keys which have non-simple querying logic.

But yes, as Ken pointed out that there should be clear documentation to that effect in our docs. Because your relationships are site-to-site I believe this is impacting your performance significantly because it appears you’re looking up objects on a very large table on every row.

**Comment by glennmatthews** [comment]
Does showing/hiding the table column for the relationship in question affect the performance at all? IMO if the relationship impacts the render performance even when its column is hidden, that feels like a bug to me.

**Comment by bryanculver** [comment]
> Does showing/hiding the table column for the relationship in question affect the performance at all? IMO if the relationship impacts the render performance even when its column is hidden, that feels like a bug to me.

This is easily repeatable in the demo environment on Devices:

- List devices (`~1-2sec load`)
- Create a M2M relationship between Devices & Devices (named "Device Friends")
- Default column view exhibits normal performance (`~1-2sec load`)
- Enabling either (or both) sides of the relationship columns exhibit a 2x+ slowdown on only ~400 devices.  (`~2-3sec load` for one side, regardless of which;  `~4-5sec load` for two sides)
- Resetting columns displayed restores normal performance (`~1-2sec load`)

**Comment by apanagio** [comment]
> Does showing/hiding the table column for the relationship in question affect the performance at all? IMO if the relationship impacts the render performance even when its column is hidden, that feels like a bug to me.

The performance is poor even when the column is hidden.  Doesn't degrade further when the column is shown. 
When the column is shown but the relationship is hidden from both source and destination the response shows no lag.

When there is a site <-> site relationship, regions are also very slow.
Could there be a bug in the rendering of the filters?

**Comment by Kircheneer** [comment]
We have tried hiding the relationship in a similar (😆) environment (also Site to Site custom relationship with 30k+ sites) and our load times also went down from ~45s to >2s.

**Comment by apanagio** [comment]
Hello, 

It certainly does address the issue!

Details:
We have 36.000 sites with a one to many relationship from site -> site (denoting colocation).
Up until nautobot 1.5.11 if the relationships were not hidden from source or destination the urls sites/ and sites/XYZ  would timeout most of the time and would rarely reply within 60 seconds.

From 1.5.16 with the relationship not hidden from source nor destination 
sites/ loads in 1-4 seconds
sites/XYZ loads in 0.2 - 2 seconds

Thanks a lot.
Keep up the good work

**Comment by bryanculver** [comment]
> Hello,
> 
> It certainly does address the issue!
> 
> Details: We have 36.000 sites with a one to many relationship from site -> site (denoting colocation). Up until nautobot 1.5.11 if the relationships were not hidden from source or destination the urls sites/ and sites/XYZ would timeout most of the time and would rarely reply within 60 seconds.
> 
> From 1.5.16 with the relationship not hidden from source nor destination sites/ loads in 1-4 seconds sites/XYZ loads in 0.2 - 2 seconds
> 
> Thanks a lot. Keep up the good work

😎 I'll take an estimated 30x improvement!
