### ISSUE TITLE
Allow computed fields to be urls

### ISSUE THREAD

**Issue by phoenixswiss** [nautobot/nautobot#2947]
### As ...

Nelly - Network Engineer

### I want ...

... to define a computed field as an url.

### So that ...

... I'm able to click on the link in the nautobot gui and open an external application / website in a new window. The url will be dynamically generated based on the obj data like this is already the case for "normal" computed field

### I know this is done when...

... I'm able to create computed fields which represents links in the gui.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [X] Circuits
- [X] DCIM
- [X] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

An additional data field, which identifies the computed field as an url. The default value for all existing computed field will be non-url field.

**Comment by lampwins** [comment]
Please see the docs on Custom Links for this https://docs.nautobot.com/projects/core/en/stable/user-guide/platform-functionality/customlink/
