### ISSUE TITLE
Site, Region -> Location: Ensure Objects that have Site or Region set have a Location set

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2956]
- Probably should be done in the same PR/work with the migrations of Site&Region to Location
- Docs update

**Comment by HanlinMiao** [comment]
Circuits:
    CircuitTermination
DCIM:
   Device
   PowerPanel
   RackGroup
   Rack
IPAM:
   Prefix site not required
   VLANGroup site not required
   VLAN site not required
Virtualization:
   Cluster site not required

All of the above models have a site ForeginKey and a location ForeginKey. This is the same as doing:
```
>>> ContentType.objects.filter(FeatureQuery("locations").get_query())
<QuerySet [<ContentType: circuits | circuit termination>, <ContentType: dcim | device>, <ContentType: dcim | power panel>, <ContentType: dcim | rack group>, <ContentType: dcim | rack>, <ContentType: ipam | prefix>, <ContentType: ipam | VLAN group>, <ContentType: ipam | VLAN>, <ContentType: virtualization | cluster>]>
```
