### ISSUE TITLE
Device labels hidden when images are enabled in Rack view

### ISSUE THREAD

**Issue by lschweiss** [nautobot/nautobot#2966]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.4
* Python version: 3.9
* Database platform, version: Postgres 14
* Middleware(s): N/A

### Steps to Reproduce
1. Add a device to a Rack
2. Add a device name and image for the device 

### Expected Behavior
Expect the device name to show over the image

### Observed Behavior
The device name is seen for a split second as the page loads.  Then the image is rendered over the device name.

With images enabled:
![image](https://user-images.githubusercontent.com/584942/206472372-a209c40a-51bb-4650-b13f-707b4a0100c5.png)
With images disabled:
![image](https://user-images.githubusercontent.com/584942/206472440-5fad8a31-28cc-4f37-adb7-7adfe0b35eb7.png)

**Comment by lschweiss** [comment]
Looking at the code, the primary cause is the order of images being added in `nautobot/dcim/elevations.py`. 

Putting the `if self.include_images` code before the `link.add()` statements get the labels on top.   However, they also need a shadow rendered, or the text is not always legible.  

This change: [https://github.com/lschweiss/nautobot/commit/5498c6cfdc617f24af23c61ce64ffd83d2cb752a](https://github.com/lschweiss/nautobot/commit/5498c6cfdc617f24af23c61ce64ffd83d2cb752a)

Renders this way:
![image](https://user-images.githubusercontent.com/584942/206487277-14184bb6-68a7-4f5d-a90e-587f2819ddf1.png)

**Comment by bryanculver** [comment]
I think an issue here is the legibility of your example which I believe is why this approach was chosen. However, maybe a text background can be applied to help with that.

**Comment by lschweiss** [comment]
I loaded the same data in Netbox.  It renders nicely creating shadows:
![image](https://user-images.githubusercontent.com/584942/206564376-3b8bd6c9-56b5-4b99-8b1e-06af70826285.png)

The code seems to have diverged quite a bit in elevations.py.  I'm not more than a python script kiddie, so I don't see an obvious way to duplicate this.
