### ISSUE TITLE
[LTM] Deleting/Restoring git repo with jobs results in database error

### ISSUE THREAD

**Issue by abates** [nautobot/nautobot#2974]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.5
* Python version: 3.8
* Database platform, version: PostgreSQL 12

### Steps to Reproduce
1. Add a repository with a job.
2. Delete the repository.
3. Add the repository one more time.

### Expected Behavior
The job should be re-enabled after the repository is re-added.

### Observed Behavior
When the repo is re-added and then sync'd there is a database constraint violation as the sync tries to add the job back (the job already exists in the database, but is marked as not installed).

**Comment by bryanculver** [comment]
This may be easier to implement once #2611 is implemented.

**Comment by glennmatthews** [comment]
Confirmed not an issue in 2.2. Will test with 1.6 next.

**Comment by glennmatthews** [comment]
Addressed by #5695.
