### ISSUE TITLE
Restructure Documentation Top-Level Structure

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2982]
As Cora the developer, I want consolidated developer documentation in the docs so that I am not confused by having several locations for different docs today and so I can easily find the specific type of developer docs I want.

**Comment by lampwins** [comment]
Let's consolidate all "developer docs" into one top level item and then further split out app/core/jobs/etc. from there. Having them is separate locations in the docs today is very confusing.

Note that the docs.nautobot.com landing page has some hard coded links that will need to be updated.

**Comment by bryanculver** [comment]
@nautobot/core I believe this is done in `next`?
