### ISSUE TITLE
Save GraphQL queries to easily re-run from a REST API

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#3]
### Proposed Functionality
Support ability to create, update, and delete GraphQL queries in the UI and API. 

### Use Case
As a user, I want a way to save and re-run common GraphQL queries from an API endpoint.  I also want to be able to easily execute saved queries within GraphiQL.

### Database Changes
Yes - will likely require a model for saving GraphQL queries to the DB - maybe just a JSONField?

### External Dependencies
None.

**Comment by carbonarok** [comment]
Test comment for issue assignment
