### ISSUE TITLE
Allow config-context in Git to be assigned to locations

### ISSUE THREAD

**Issue by gertzakis** [nautobot/nautobot#3014]
### As ...

Dan - Data Owner

### I want ...

Config Contexts stored in Git repos to be assigned by location, as it is already happening with Sites and Regions.

### So that ...

I can store specific confic context data in Git repos and be assigned to the proper Nautobot objects when synced. 

### I know this is done when...

- I have a Config Context under 
```
config_contexts/
  location_building/
    building_A.yaml
```
and after sync building_A.yaml is synced with the proper location and device objects related to that location.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [X] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by glennmatthews** [comment]
We need to make sure to include this under the umbrella of #2517 in 2.0; however it might also be valuable to implement this minor feature in 1.5.x as a forward-compatibility item?
