### ISSUE TITLE
Performance issue of Advanced Filters

### ISSUE THREAD

**Issue by martin-networker** [nautobot/nautobot#3030]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.2
* Python version: 3.10
* Database platform, version: -
* Middleware(s): -

### Steps to Reproduce
1. Click the "Filter" button on any list view
2 .Click the "Advanced" tab
3. Try load Lookup Values and values for various Filters
4. Apply filters

### Observed Behavior
For some Search Fields it takes quiet some time to load Lookup type and Value.
Applying Advanced Filters takes longer than previous version of filtering.

**Comment by bryanculver** [comment]
Thanks for reporting @martin-networker. Can you provide examples of known poor-performing filters?

**Comment by martin-networker** [comment]
@bryanculver I can't reproduce this issue. It was probably overutilization of our nautobot server.
