### ISSUE TITLE
Job Buttons - Single Click Execution

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#3033]
### As ...

Ozzie - Operator

### I want ...

I am looking to be able to make a custom link that will make a POST request, an action button.

### So that ...

This would allow for Nautobot to source a custom activity, such as launch a job on another system.

### I know this is done when...

- There is the ability to do web hook like activity from a button from a custom link.

### Optional - Feature groups this request pertains to.

- [X] Automation
- [X] Circuits
- [X] DCIM
- [X] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

Unsure

### External Dependencies

None

**Comment by itdependsnetworks** [comment]
Action == a job hook essentially?

**Comment by jeffkala** [comment]
POST request without the requirement of "CRUD" operation on the object. A custom link on a Nautobot object that can (webhook) to an external system. The key to this requirement is that clicking the link does this versus a change in state on the Nautobot object itself.

**Comment by jvanderaa** [comment]
Correct, a POST and I think if we are looking at that need to be able to support parameters to be included in the POST URL as well. I think that the Jinja would take care of that natively.

**Comment by itdependsnetworks** [comment]
Love the idea! 

One other consideration is making this a part of template_content, may be able to be a bit more expressive/descriptive there.

**Comment by glennmatthews** [comment]
Based on discussion this morning it sounds like what's really being asked for is the ability to provide a button to trigger either a WebHook or a JobHook (with all of the functionality and configurability that either of those features offers).

**Comment by bryanculver** [comment]
What is the event data for the button though?

JobHooks and WebHooks are firing off of an event (created/edited [what changed]/deleted). Should the payload of this just be a snapshot of the object at present?

**Comment by jvanderaa** [comment]
There are two possibilities here. 

1) An action button similar to custom link, that would just be a link addition with a POST request instead of a GET request. @bryanculver is that something done via a browser then? I think it is.
2) Creating this as a webhook, where there is then significant payload additions.

**Comment by bryanculver** [comment]
>This would allow for Nautobot to source a custom activity, such as launch a job on another system.

A job on another system likely has it's own payload requirements but with WebHooks and JobHooks the sender defines the structure, not the receiver.

**Comment by jeffkala** [comment]
Ultimately its a WebHook that is firing off of a button click, where that custom link definition can pull in {{ obj }} and the payload could be formatted via j2 or something would be my thought.

**Comment by lampwins** [comment]
I think we may be confusing the discussion by referring to webhooks and jobs/jobhooks. Those are existing features. What is being asked here is for a button on an object detail view that takes a user to an external link, but the web request used to do so is a POST request, correct? The point of custom links is that the user navigates away from Nautobot when using them.

@jvanderaa are you able to provide anything more concrete use case-wise? Is the expectation that the user would be directed to an external system? If not, what is the UX?

**Comment by jvanderaa** [comment]
The use case here is to provide a button that will say go do something. Custom Link, but with a POST.

**Comment by lampwins** [comment]
After talking with Josh, we are going to turn this request in "Job Buttons" which are single-click job execution buttons.

Managed the same way custom links are today, but instead of providing a templated link, the user provides a job to execute. On the UX, the button click would return the user to the same object detail view they were on before, but with a message banner that contains the link to the job result object that was enqueued.

**Comment by jvanderaa** [comment]
This sounds like a good win.

**Comment by jvanderaa** [comment]
@itdependsnetworks do you agree that this would be a fit? I very much think so.

**Comment by itdependsnetworks** [comment]
Yes, this is exactly it

**Comment by bryanculver** [comment]
> After talking with Josh, we are going to turn this request into "Job Buttons" which are single-click job execution buttons.
> 
> Managed the same way custom links are today, but instead of providing a templated link, the user provides a job to execute. On the UX, the button click would return the user to the same object detail view they were on before, but with a message banner that contains the link to the job result object that was enqueued. The job would have to have no input.

This seems much more obtainable. As far as "no input" is concerned, I suspect you'd at least like the object you're currently viewing to be in the context when triggering the job?

**Comment by jvanderaa** [comment]
Yeah, that is what would make sense to pass along. I was thinking perhaps asking if we can do something around Jinja, but it just makes sense that if a Job is being launched that the Job can search the database for whatever else may be needed.

**Comment by itdependsnetworks** [comment]
Correct, the context of obj would be expected to be used as part of the execution, in golden config we used this pattern to show you a concrete example (this requires two steps right now vs the one being asked). 

https://github.com/nautobot/nautobot-plugin-golden-config/blob/24f18388ee8c0aded7200b21a426de39be83fc42/nautobot_golden_config/templates/nautobot_golden_config/content_template.html#L74

**Comment by bryanculver** [comment]
So in that case we can have the triggered-from object be a key-value in the `data` argument for `run()`, where we would need to pass in _either_ the actual object (instantiated) or something like `{"object_id": "uuid", "object_type": "dcim:device"}`. This would allow for not needing to define and ensure the Job specifies the proper variable & type as `object = ObjectVar(model=Device)`

**Comment by joewesch** [comment]
As an update, I am currently working on an implementation for this. I just don't have the ability to assign myself to this issue.
