### ISSUE TITLE
Raising `AbortTransaction` during job execution causes job to show as `Running` forever

### ISSUE THREAD

**Issue by joaopsys** [nautobot/nautobot#3058]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.5
* Python version: 3.8.12
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Create a simple job.
2. Within the `run` method do:
```
def run(self, data, commit):
    self.log_failure("Failed")
    raise nautobot.utilities.exceptions.AbortTransaction
```
3. Job will stop, `post_run` will be called, but the job status will be `Running` forever.

### Expected Behavior
Job fails and is marked as `Failed` just like it happens with the following code:

```
def run(self, data, commit):
    self.log_failure("Failed")
    return
```

### Observed Behavior
Job is marked as `Running` for eternity.

**Comment by jathanism** [comment]
You should not be raising an `AbortTransaction` yourself. Instead raise any error. I think our documentation needs to be adjusted here. See the code here, for how the exceptions are handled:

https://github.com/nautobot/nautobot/blob/develop/nautobot/extras/jobs.py#L1204-L1209

**Comment by joaopsys** [comment]
I understand that no matter what, the database will be rolledback in the end, right?

But how do I immediately stop the job execution from a different function running outside of the `run` method? Do I always need to go back to the main `run` method and return after an error?

For example

```
def run(self, data, commit):
    for x in range(5):
        do_stuff(x)

def do_stuff(x):
    if x == 3:
        self.log_failure("Failed, abort")
        return
        ## How do I abort right now?
```

Might be a confusing example, but we have jobs that call several other functions and we have been using the `raise` to abort them, even if the Job stays `Running`, so that we don't have to check the return code after every function call.

**Comment by joewesch** [comment]
I think the key here from Jathan's response needs some emphasis:

> **Instead raise any error.**

Just raise any other error instead. AbortTransaction is caught separately from other exceptions and will not set the job status.

I also agree that the `Note` in the section of the documentation that you linked does suggest to use AbortTransaction and should change.
