### ISSUE TITLE
FK, Related Name Cleanup: `extras` App

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#3067]
See spike https://github.com/nautobot/nautobot/issues/2960#issuecomment-1349809073 for details

**Comment by glennmatthews** [comment]
Details of the needed changes are in https://github.com/nautobot/nautobot/issues/2960#issuecomment-1349809073 I believe?

**Comment by gsnider2195** [comment]
> Details of the needed changes are in [#2960 (comment)](https://github.com/nautobot/nautobot/issues/2960#issuecomment-1349809073) I believe?

That's right. I am going to update the description on these to include that
