### ISSUE TITLE
Jobs Overhaul: Merge `TaskResult` and `JobResult` data models

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#3085]
- [x] Augment `JobResult` with `TaskResult` fields
- [x] Replace `JobResultStatusChoices` enum values with those of Celery task states
- [x] Replace `TaskResult` with `JobResult` on `NautobotDatabaseBackend`
- [x] Migrate state transition machinery from `run_job()` task to `NautobotDatabaseBackend` state handlers and `NautobotTask` state handlers
- [x] Fix double JSON encoding/decoding for task args/kwargs (especially `request`) and result/data fields.
- [x] Fix system tasks compatibility with `JobResult` (these weren't previously stored in database)
- [x] Assert that `JobResult.data` is updated correctly.
- [x] Get all the tests running and updated
- [x] Remove `NAUTOBOT_CELERY_RESULT_BACKEND` environment variable
- [x] Remove optional settings docs for `CELERY_RESULT_BACKEND` and `CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS`

**Comment by bryanculver** [comment]
Let's see if we can pull in #3089 as a part of this.

**Comment by bryanculver** [comment]
Let's figure out how much of https://github.com/nautobot/nautobot/issues/275 is quasi-resolved or started because of the changes for this (#3164 👀)
