### ISSUE TITLE
Jobs Overhaul: UI Updates for database backend

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#3088]
Tests have been revised for the work done in #3085, however, this issue should assert the following:

- Make sure that the notable field/semantics changes are documented (status value changes, `created` => `date_created`, etc.) in migration guide
- Document how to use Celery `task_prerun` signals (and other signals) to debug Jv2 Jobs
- Document how to use `rdb` to do remote debugging on v2 Jobs ran inside of workers

To Do:
- [ ] Core documentation and examples must be revised for v2
- [ ] Developer documentation should be shored up for v2 changes
- [ ] v2 UI elements such as whether to display tracebacks or `task_kwargs` payloads, that may contain sensitive variables or secrets (data exposure concerns, such as CSRF tokens, etc.). We may also decide to display them but sanitize them first? This one is tricky, but should be considered here.

**Comment by bryanculver** [comment]
Updated the collection of these issues to #765
