### ISSUE TITLE
Jobs Overhaul: Documentation updates for database backend

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#3089]
- [ ] Document how to migrate an existing job to 2.0.
- [ ] Document how to implement dry-run support in a new or existing job (including but not limited to `transaction.atomic()`)
- [ ] Document how to implement equivalent functionality to the 1.x `post_run()` in a job.
- [ ] Add an entry to the 2.0 Release Overview docs summarizing the Job changes.
- [ ] Make sure to call out that `Job.after_return()` MUST be called in order for chords to work

**Comment by bryanculver** [comment]
To be done in #3085

**Comment by jathanism** [comment]
Reopened because the documentation did not get done in #3085 and still needs to be completed.

**Comment by bryanculver** [comment]
Documentation tasks moved up to a task list in #765
