### ISSUE TITLE
Power Cables Display as connected to Circuits

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#309]
### Environment
* Python version: 3.6
* Nautobot version: 1.0b3

Power cables connected to power feeds are displayed as terminating to Circuits with Providers.  This might be a feature request, apologies if so, NetBox reports the cable in the same way.

### Steps to Reproduce
1.  Create a device with a powerport
2.  Create a power panel and power feed
3.  Connect the power port to the power feed
4. view the cable object

### Expected Behavior

I would expect the power feed termination to be listed as power feed or power outlet of some sort.  Instead, it is listed as Circuit with Provider.

### Observed Behavior

![Screen Shot 2021-04-13 at 2 37 38 PM](https://user-images.githubusercontent.com/14947575/114617838-db4fc480-9c65-11eb-85da-a06aa1447cb7.png)

**Comment by jathanism** [comment]
IMO this is certainly a bug, but not a showstopper, so I'm going to push this beyond the fold for v1.0.0
