### ISSUE TITLE
Error when accessing device detail page.

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#3096]
### Environment
* Nautobot version (Docker tag too if applicable): 3ae58803badd (v1.4.10)
* Python version: 3.9.15
* Database platform, version: PostgreSQL 14
* Middleware(s): 

### Steps to Reproduce
1. Delete an IP Address that is used as primary IP for a device
2. Open Device that had the IP address assigned as primary ip
3.
4.

### Expected Behavior
Device detail page opens

### Observed Behavior

**Server Error**

There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

```
<class 'nautobot.ipam.models.IPAddress.DoesNotExist'>

IPAddress matching query does not exist.

Python version: 3.9.15
Nautobot version: 1.4.10
```

**Comment by jifox** [comment]
Workaround: Assign a new primary IP to the device

**Comment by lampwins** [comment]
Sounds like cacheops, do you have it enabled?

**Comment by jifox** [comment]
Yes, cacheops is enabled.

**Comment by bryanculver** [comment]
I cannot reproduce this locally with Cacheops disabled.

**Comment by bryanculver** [comment]
Won't be fixed as is a Cacheops bug and that will be removed.
