### ISSUE TITLE
Filter dropdown menu moves too high while scrolling

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#3097]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.7
* Python version: 3.10.9
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Open Prefix Filter menu
2. Scroll down 
3. Open `Status` field (any field with drop-down options)

### Expected Behavior
Drop down options are shown right under the field
![image](https://user-images.githubusercontent.com/26114847/211298453-c3aa2d0c-0e74-4955-b1db-0ef78047b3f7.png)

### Observed Behavior
Drop down options are moved 2x the distance scrolled up resulting in the options showing above the field (sometimes out of view for the lower ones).
![image](https://user-images.githubusercontent.com/26114847/211298515-63c997a2-f07d-4142-8b6b-52f37ce50069.png)
and when moved too much down:
![image](https://user-images.githubusercontent.com/26114847/211298877-95b5512f-4bb4-46a5-a28e-eb3e6b753f99.png)

**Comment by bryanculver** [comment]
This seems to be a side-effect of fixing this bug: https://github.com/nautobot/nautobot/issues/3018
