### ISSUE TITLE
Custom Link restriction

### ISSUE THREAD

**Issue by martin-networker** [nautobot/nautobot#3102]
### As ...

Ozzie - Operator

### I want ...

To be able to restrict custom link based on specific parameter.

### So that ...

I can create a custom link/button for devices of certain vendor.

### I know this is done when...

For example we offer some extra information via Custom link (URL) for Cisco devices but for other devices I do not want to see the button as it does not work for them.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by glennmatthews** [comment]
Thanks for the request! This is very similar to #889, just for custom-links instead of custom-fields.

**Comment by martin-networker** [comment]
@glennmatthews It is similar just for different object. Do you mean that this also has to wait for the 2.2.0 version.

**Comment by glennmatthews** [comment]
It would probably make sense to implement both at around the same time given that it's a very similar feature. That's only my opinion though. :-)

**Comment by lampwins** [comment]
So in terms of custom links, this is already possible today. Check out the "Conditional Rendering" sections in the docs https://docs.nautobot.com/projects/core/en/stable/models/extras/customlink/?h=custom+links#conditional-rendering

**Comment by martin-networker** [comment]
@lampwins Thank you. I have missed this documentation. This solves my problem :)
