### ISSUE TITLE
Cannot Choose Location for Device - Fresh Installation

### ISSUE THREAD

**Issue by Dustin-Wi** [nautobot/nautobot#3108]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.7
* Python version: 3.9.14
* Database platform, version: PostgreSQL 10.19
* Middleware(s): Only what comes with the nautobot python package

### Steps to Reproduce
1. Followed steps from https://docs.nautobot.com/projects/core/en/stable/installation/nautobot/ to install prerequisites and nautobot
2. Add Location Groups and Locations
3. Try to select a location while creating a Rack or Device

### Expected Behavior
I expected to see my created locations in the "Locations" drop down selection when creating a rack or device.

### Observed Behavior
No locations were listed in the drop down when creating a rack or rack group.

### Other Notes
I was able to create locations in a hierarchy.
I was able to associate locations to sites.
I am able to assign a site to Racks and Devices, but not locations.
I want to be able to assign a room location to racks and devices.  If I'm not organizing my data correctly, or if I should be doing this another way please point me to any documentation that discusses nautobot's intended data structures, hierarchies, and relationships.  I'm still new to nautobot, and I accept that I may misunderstand the intended relationships of the data.
Lastly, If there is a better place to submit these types of questions, please let me know.  I cannot participate on the Slack channels because it is blocked at work.

**Comment by glennmatthews** [comment]
Opening issues is fine, sorry to hear you can't access the Slack!

I would guess that the missing step here is that you need to edit the LocationTypes that can contain Racks and Devices to specify that this is permitted:

![image](https://user-images.githubusercontent.com/5603551/211825502-3b13235e-1b1c-4387-99a0-9f1e5c821847.png)

This is so that if you have a hierarchy of LocationTypes (say Building -> Floor -> Room) you might want to specify that Rooms can contain Racks but Buildings cannot, etc.

**Comment by Dustin-Wi** [comment]
I'm a dummy.  I didn't find the "Content Sections" for location types in the documentation till after a while of playing with this.

For any new folks who also run into this and find this issue, edit your "Location Types" to include all the necessary types that are allowed to be assigned to each location type.

**Comment by Dustin-Wi** [comment]
> Opening issues is fine, sorry to hear you can't access the Slack!
> 
> I would guess that the missing step here is that you need to edit the LocationTypes that can contain Racks and Devices to specify that this is permitted:
> 
> ![image](https://user-images.githubusercontent.com/5603551/211825502-3b13235e-1b1c-4387-99a0-9f1e5c821847.png)
> 
> This is so that if you have a hierarchy of LocationTypes (say Building -> Floor -> Room) you might want to specify that Rooms can contain Racks but Buildings cannot, etc.

Thanks for the info.  This is exactly the issue I was having! :)
