### ISSUE TITLE
Unable to Bulk Import Cables Connected to Power Feeds

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#311]
Even though cables can be created using the UI connecting a device's power port to a power feed, you can not import the cable.  This issue also exists in NetBox and has been reported as issue [5952](https://github.com/netbox-community/netbox/issues/5952) with a potential fix in or [6111](https://github.com/netbox-community/netbox/pull/6111) for NetBox.

### Environment
* Python version: 3.6
* Nautobot version: 1.0b3

### Steps to Reproduce
1.  Create a device with a power port
2.  Create a power feed
3.  Create a cable connecting the power port to the power feed via import (it works in the UI).

### Expected Behavior

Import to succeed and a cable connecting the power port and the power feed to be created

### Observed Behavior

Import fails with:

```
Row 1 side_b_device: Object not found.
Row 1 __all__: Termination B type has not been specified
```

**Comment by glennmatthews** [comment]
Probably no longer relevant as originally reported given the overhaul of CSV import in v2.0.
