### ISSUE TITLE
Controllers

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#3111]
### As ...

Nelly - Network Engineer

### I want ...

A way to model and track network controllers

### So that ...

I can track the relationships between controllers, and the devices that they control

### I know this is done when...

- I have a model to define a controller
- Controllers have a Controller-specific role.
- Devices can be optionally related to one or more controllers with a defined priority

### Optional - Feature groups this request pertains to.

- Automation
- DCIM

### Database Changes

A new controller model and relationships with devices

### External Dependencies

None

**Comment by davidban77** [comment]
A few examples that have been brought up for this type of model/relationship:

- Wireless Controllers + APs
- F5 BIG-IQ Centralized Management + F5 BIG IPs
- Firewall Managers + Firewall boxes

A way to model out this controller/worker relationship might prove useful for representing solutions like the above. A way to track the relationships basically.

Regarding the tag system I have some questions and comments:

- What if the tag ecosystem within the Nautobot environment is already overwhelmed?
- For me personally, a tag is great to categorize the data that is useful to the external systems/operators. Not so much for indicating internal relationships between data in the same system.
- Keeping track of tags for the relationship between controllers/workers would need to be done externally by a process? If is properly modelled, this should not be the case correct?

I have limited knowledge of the models and tags capabilities and if there are also performance and/or maintenance aspects to consider. But it would be really nice to have a controller view with all of its workers in Nautobot 😄

**Comment by gsnider2195** [comment]
Could this work similarly to `DeviceRedundancyGroup`s? Since the controller is likely already a device in Nautobot would this kind of model work? Here's the `DeviceRedundancyGroup` for reference:

```py
class DeviceRedundancyGroup(PrimaryModel, StatusModel):
    name = models.CharField(max_length=100, unique=True)
    slug = AutoSlugField(populate_from="name")
    description = models.CharField(max_length=200, blank=True)
    failover_strategy = models.CharField(...)
    comments = models.TextField(blank=True)
    secrets_group = models.ForeignKey(to="extras.SecretsGroup", ...)

class Device(PrimaryModel, ConfigContextModel, StatusModel, RoleRequiredRoleModelMixin):
    ...
    device_redundancy_group = models.ForeignKey(to="dcim.DeviceRedundancyGroup", ...)
    device_redundancy_group_priority = models.PositiveSmallIntegerField(...)
```
