### ISSUE TITLE
Tests are making assumptions about underlying data

### ISSUE THREAD

**Issue by PavelSafronov** [nautobot/nautobot#3116]
### Environment
* Nautobot version (Docker tag too if applicable): tip of master, tested with commit 0341ca3783b78c9f6550f9871de55420a59e7bea
* Python version: 3.7
* Database platform, version: unsure
* Middleware(s): unsure

### Steps to Reproduce
1. open https://github.com/nautobot/nautobot/blob/develop/nautobot/extras/tests/test_views.py
2. on line 286, change the JSON string in a trivial way, either by adding/removing spaces or by swapping the order of `type` and `properties` fields
  - for example, `"data_schema": '{"type": "object", "properties": {"baz": {"type": "string"}}},'` => `"data_schema": '{"type":"object","properties":{"baz":{"type":"string"}}}',` 
4. run tests, for example `inv unittest -l nautobot.extras.tests.test_views.ConfigContextSchemaTestCase.test_edit_object_with_permission --debug --keepdb --verbose --skip-docs-build`

### Expected Behavior

Tests pass.

### Observed Behavior

Test fails with an error:
```
FAIL: test_edit_object_with_permission (nautobot.extras.tests.test_views.ConfigContextSchemaTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/source/nautobot/utilities/testing/views.py", line 447, in test_edit_object_with_permission
    self.assertInstanceEqual(self._get_queryset().get(pk=instance.pk), self.form_data)
  File "/source/nautobot/utilities/testing/mixins.py", line 203, in assertInstanceEqual
    self.assertEqual(new_model_dict, relevant_data)
AssertionError: {'nam[52 chars]{"type": "object", "properties": {"baz": {"type": "string"}}}'} != {'nam[52 chars]{"type":"object","properties":{"baz":{"type":"string"}}}'}
- {'data_schema': '{"type": "object", "properties": {"baz": {"type": "string"}}}',
?                          -         -             -       -        -

+ {'data_schema': '{"type":"object","properties":{"baz":{"type":"string"}}}',
   'name': 'Schema X',
   'slug': 'schema-x'}
```

This is happening because `data_schema` is a JSON column, and MySQL makes no guarantees about JSON being returned in the same format or with properties staying in the same order. From the [official docs](https://dev.mysql.com/doc/refman/8.0/en/json.html#json-normalization):

>  To make lookups more efficient, MySQL also sorts the keys of a JSON object. *You should be aware that the result of this ordering is subject to change and not guaranteed to be consistent across releases.*

The current tests are attempting to verify that the `data_schema` string that was stored is identical to the retrieved `data_schema` data, and therefore easily break when the data is changed or if a different DB is used.

**Comment by glennmatthews** [comment]
Looks like we may need to enhance our `assertInstanceEqual` logic to account specifically for JSON fields in some way. Wonder if just checking for `value.startsWith("{")` would be sufficient as a naive approach?
