### ISSUE TITLE
image-attachments API POST Request: Unsupported media type "multipart/form-data"

### ISSUE THREAD

**Issue by phoenixswiss** [nautobot/nautobot#3124]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.7
* Python version: 3.8.10
* Database platform, version: postgresql, Ubuntu 12.12-0ubuntu0.20.04.1
* Middleware(s): - 

### Steps to Reproduce
1. Upload a jpg file via api POST request and "multipart/form-data" content type to https://nautobot-server/api/extras/image-attachments/ 

### Expected Behavior
The image will be uploaded like in 1.4.x releases

### Observed Behavior
Upload is not possible anymore and cancels with the error message "Unsupported media type "multipart/form-data; boundary="xxxxxxx""

According to the api documentation only "application/json" is available in v1.5.7. With older nautobot versions multipart/form-data was available. The API POST command for image-attachments is useless without multipart/form-data as content-type.

**Comment by phoenixswiss** [comment]
The issue was caused by the following commit:

[Allow and Handle Multipart Payloads Job API (](https://github.com/nautobot/nautobot/commit/3aa950a2a84cdcc1a4655882489f900c20d64d3f)https://github.com/nautobot/nautobot/pull/2644[)](https://github.com/nautobot/nautobot/commit/3aa950a2a84cdcc1a4655882489f900c20d64d3f)

After adding ``"DEFAULT_PARSER_CLASSES": ("rest_framework.parsers.JSONParser",),``
[nautobot/core/settings.py](https://github.com/nautobot/nautobot/commit/3aa950a2a84cdcc1a4655882489f900c20d64d3f#diff-6c6cc147c8188d94be8fd3b11345aa4bfef52a760e0961643b6b84d0c26da43a)

If I remove this line in nautobot/core/settings.py , multipart/form-data is available via api again.

**Comment by krono** [comment]
The mentioned issue also affects https://pypi.org/project/nautobot-ui-plugin/ , because it uses a jquery x-www-form-urlencoded way of submitting its data.

**Comment by glennmatthews** [comment]
Might be as simple as adding `parser_classes = [JSONParser, MultiPartParser]` to `ImageAttachmentViewSet`.

**Comment by smk4664** [comment]
> Might be as simple as adding `parser_classes = [JSONParser, MultiPartParser]` to `ImageAttachmentViewSet`.

I have done this in another app, this is the solution that worked for me.
