### ISSUE TITLE
LLDP interface may show mac address instead of remote port name

### ISSUE THREAD

**Issue by ozmusic** [nautobot/nautobot#3129]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.7
* Python version: 3.8.13
* Database platform, version: postgresql 9.6
* Middleware(s): napalm 4.0.0

When using the LLDP neighbors tab in the device view, some devices return a mac address for the remote LLDP interface.

### Steps to Reproduce
1. Configure napalm
2. Go to device
3. Click on LLDP Neighbors tab

### Expected Behavior
LLDP interface name to be displayed

### Observed Behavior
With some device types/napalm drivers, LLDP interface shows the remote mac address. On these devices, LLDP reports the port name under `remote_port_description` instead of `remote_port`

Potential fix to the ajax function
```
var neighbor_port = neighbor['remote_port'] || ""; // sanitize port if it's null to avoid breaking the split func
if (neighbor_port.match(/^[a-fA-F0-9]{2}(:[a-fA-F0-9]{2}){5}$/)) {
    neighbor_port = neighbor['remote_port_description'] || ""; // use remote_port_description if remote_port is a mac address
}
```

**Comment by abates** [comment]
This was fixed in #5413
