### ISSUE TITLE
Swagger UI Doesn't Report Status as a Required Field Correctly

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#313]
Not sure if this is global or specific to power-feeds status but I also checked devices and status is not required there either in swagger.

### Environment
* Python version: 3.6
* Nautobot version: 1.0b3

### Steps to Reproduce
1.  Go to the swagger UI
2.  Look for POST `POST ​/dcim​/power-feeds​/`
3.  Look under parameters in the model view, status is shown as not required

### Expected Behavior

Status should have a required * as it is a required field.

### Observed Behavior

Swagger shows it as not required

**Comment by jathanism** [comment]
Thanks @nniehoff for reporting this. Interestingly it's marked as non-required field in the serializer mixin, but obviously that's now how it is behaving:

https://github.com/nautobot/nautobot/blob/develop/nautobot/extras/api/serializers.py#L611-L614

**Comment by jathanism** [comment]
It's because of model validation. The field not being required is overridden by the fact that the field is required when the model is validated.

**Comment by glennmatthews** [comment]
Updating the link: https://github.com/nautobot/nautobot/blob/develop/nautobot/extras/api/serializers.py#L873 (StatusModelSerializerMixin). It probably should be `required=True` - maybe just change this and test to see what breaks?
