### ISSUE TITLE
Unable to Create Power Cables via API

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#316]
### Environment
* Python version: 3.6
* Nautobot version: 1.0b3

This is similar and likely related to #311 however we need to make sure the API gets fixed as well.

### Steps to Reproduce
1.  Create a power panel and power feed
2.  Create device with a power port
3.  Create json payload:

```json
{
  "termination_a_type": "dcim.powerport",
  "termination_a_id": "d877836e-b17a-4bce-865d-8fd66fdd4a0d",
  "termination_b_type": "dcim.powerfeed",
  "termination_b_id": "4ef2ee36-df60-4a47-bbcf-3397242e2957",
  "type": "power",
  "status": "connected"
}
```

4.  Adjust IDs appropriately
5.  POST the json as an authenticated request to `/dcim/cables/`

### Expected Behavior

A 200 response and the cable created.

### Observed Behavior

Response 400 with:

```json
{
    "non_field_errors": [
        "The fields termination_b_type, termination_b_id must make a unique set."
    ]
}
```

**Comment by nniehoff** [comment]
As with issue #311 this issue is also from NetBox

**Comment by glennmatthews** [comment]
Can you confirm that you don't already have a cable connected to that powerfeed? The "must make a unique set" error text suggests that Nautobot thinks you already have such a cable.

**Comment by nniehoff** [comment]
Thanks Glenn apparently it's impossible to connect 2 power ports to the same powerfeed.
