### ISSUE TITLE
Clarify Functional Roles Purposes in IP Address Documentation

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3163]
### Discussed in https://github.com/nautobot/nautobot/discussions/3159

<div type='discussions-op-text'>

<sup>Originally posted by **kovalev94** January 24, 2023</sup>
Hello.
Documentaion has an example that VIP is a virtual ip address for VRRP,
then what is the purpose of VRRP/HSRP roles?
Also I don't understand wich role i should use for vlan interfaces, and phisical interfaces.
Can anybody help me?</div>

- The phrase "for example, use as a loopback or as the the virtual IP for a VRRP group" is slightly oblique (you'd use "VRRP" to denote the virtual IP for a VRRP group and "VIP" is a more generic form)
- Role doesn't have to be specified for cases associated to VLAN interfaces and physical interfaces

**Comment by lampwins** [comment]
I think we have negated this with the generic role model. Docs can always be improved though.
