### ISSUE TITLE
Error when connecting a cable from CircuitTermination to CircuitTerminaiton

### ISSUE THREAD

**Issue by HanlinMiao** [nautobot/nautobot#3179]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.7
* Python version: 3.7.16
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Connect a cable from CircuitTermination to CircuitTermination from CircuitDetailPage
2. After creating, nautobot will try to redirect you back to CircuitDetailPage
3. 

### Expected Behavior
CircuitDetailPage is correctly rendered

### Observed Behavior
Attribute Error occurred
![Screen Shot 2023-01-27 at 10 55 59 AM](https://user-images.githubusercontent.com/46973263/215130367-83917c13-6840-4ed0-8014-0ae10d7ac128.png)

**Comment by HanlinMiao** [comment]
See this [comment](https://github.com/nautobot/nautobot/pull/3174#discussion_r1088970237) on `CircuitCircuitTerminationSerializer` for a possible fix

**Comment by slappey-ibkr** [comment]
What's the fix here?  I'm getting the same error and I'm unable to access the detail view of many circuits.  I'm running nautobot v1.5.11 and python v3.10.2.  Also, I'm unable to delete cables via api that are connected to circuit terminations.  I keep getting "CablePath matching query does not exist".

**Comment by alhogan** [comment]
This came up again, user accidentally connected two Circuits via Front and Rear ports on a patch panel Device. The corresponding Cable objects can't be deleted from the GUI due to the error @HanlinMiao posted above. We were able to workaround this issue by deleting the cable via the Nautobot Shell.
