### ISSUE TITLE
Spike: IP to Multiple Interfaces: Can this be done with a single table instead of two separate ones (we eventually do want to collapse Device and VM)

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3190]

**Comment by glennmatthews** [comment]
Appears pretty straightforward with two ManyToManyFields sharing a single through table:

```diff
diff --git a/nautobot/dcim/models/device_components.py b/nautobot/dcim/models/device_components.py
index 27bc04d6d..dc7b5f947 100644
--- a/nautobot/dcim/models/device_components.py
+++ b/nautobot/dcim/models/device_components.py
@@ -617,6 +617,14 @@ class Interface(CableTermination, PathEndpoint, ComponentModel, BaseInterface):
         object_id_field="assigned_object_id",
         related_query_name="interface",
     )
+    # TODO migrate and remove "ip_addresses" and rename "ip_addresses_new" to "ip_addresses"
+    ip_addresses_new = models.ManyToManyField(
+        to="ipam.IPAddress",
+        through="ipam.IPAddressToInterface",
+        related_name="interfaces",
+        blank=True,
+        verbose_name="IP Addresses",
+    )
 
     csv_headers = [
         "device",
diff --git a/nautobot/ipam/models.py b/nautobot/ipam/models.py
index 3ab96dbe3..565c14695 100644
--- a/nautobot/ipam/models.py
+++ b/nautobot/ipam/models.py
@@ -11,6 +11,7 @@ from django.db.models import F, Q
 from django.urls import reverse
 from django.utils.functional import classproperty
 
+from nautobot.core.models import BaseModel
 from nautobot.core.models.fields import AutoSlugField, JSONArrayField
 from nautobot.core.models.generics import OrganizationalModel, PrimaryModel
 from nautobot.core.models.utils import array_to_string
@@ -742,6 +743,7 @@ class IPAddress(PrimaryModel, StatusModel, RoleModelMixin):
         blank=True,
         null=True,
     )
+    # TODO: remove assigned_object fields
     assigned_object_type = models.ForeignKey(
         to=ContentType,
         limit_choices_to=IPADDRESS_ASSIGNMENT_MODELS,
@@ -975,6 +977,23 @@ class IPAddress(PrimaryModel, StatusModel, RoleModelMixin):
     mask_length = property(fset=_set_mask_length)
 
 
+class IPAddressToInterface(BaseModel):
+    ip_address = models.ForeignKey("ipam.IPAddress", on_delete=models.CASCADE)
+    interface = models.ForeignKey("dcim.Interface", blank=True, null=True, on_delete=models.CASCADE)
+    vm_interface = models.ForeignKey("virtualization.VMInterface", blank=True, null=True, on_delete=models.CASCADE)
+
+    def clean(self):
+        super().clean()
+
+        if self.interface is not None and self.vm_interface is not None:
+            raise ValidationError(
+                {"interface": "Cannot use a single instance to associate to both an Interface and a VMInterface."}
+            )
+
+        if self.interface is None and self.vm_interface is None:
+            raise ValidationError({"interface": "Must associate to either an Interface or a VMInterface."})
+
+
 @extras_features(
     "custom_fields",
     "custom_validators",
diff --git a/nautobot/virtualization/models.py b/nautobot/virtualization/models.py
index e808212d0..6d02d4fe4 100644
--- a/nautobot/virtualization/models.py
+++ b/nautobot/virtualization/models.py
@@ -461,6 +461,14 @@ class VMInterface(BaseModel, BaseInterface, CustomFieldModel, NotesMixin):
         object_id_field="assigned_object_id",
         related_query_name="vminterface",
     )
+    # TODO migrate and remove "ip_addresses" and rename "ip_addresses_new" to "ip_addresses"
+    ip_addresses_new = models.ManyToManyField(
+        to="ipam.IPAddress",
+        through="ipam.IPAddressToInterface",
+        related_name="vm_interfaces",
+        blank=True,
+        verbose_name="IP Addresses",
+    )
     tags = TaggableManager(through=TaggedItem, related_name="vminterface")
 
     csv_headers = [
```


```python
>>> ip = IPAddress.objects.first()
>>> intf = Interface.objects.first()
>>> vmintf = VMInterface.objects.first()
>>> intf.ip_addresses_new.add(ip)
>>> vmintf.ip_addresses_new.add(ip)
>>> intf.ip_addresses_new.all()
<IPAddressQuerySet [<IPAddress: 661:cd9a:7f5:32c5:9c58:26f9:1747:45d4/128>]>
>>> vmintf.ip_addresses_new.all()
<IPAddressQuerySet [<IPAddress: 661:cd9a:7f5:32c5:9c58:26f9:1747:45d4/128>]>
>>> ip.interfaces.all()
<RestrictedQuerySet [<Interface: Eth1>]>
>>> ip.vm_interfaces.all()
<RestrictedQuerySet [<VMInterface: Eth1>]>
>>> another_intf = Interface.objects.last()
>>> ip.interfaces.add(another_intf)
>>> ip.interfaces.all()
<RestrictedQuerySet [<Interface: Eth1>, <Interface: Eth3>]>
>>> another_intf.ip_addresses_new.all()
<IPAddressQuerySet [<IPAddress: 661:cd9a:7f5:32c5:9c58:26f9:1747:45d4/128>]>
```

**Comment by bryanculver** [comment]
> Appears pretty straightforward with two ManyToManyFields sharing a single through table:
> 
> ```diff
> diff --git a/nautobot/dcim/models/device_components.py b/nautobot/dcim/models/device_components.py
> index 27bc04d6d..dc7b5f947 100644
> --- a/nautobot/dcim/models/device_components.py
> +++ b/nautobot/dcim/models/device_components.py
> @@ -617,6 +617,14 @@ class Interface(CableTermination, PathEndpoint, ComponentModel, BaseInterface):
>          object_id_field="assigned_object_id",
>          related_query_name="interface",
>      )
> +    # TODO migrate and remove "ip_addresses" and rename "ip_addresses_new" to "ip_addresses"
> +    ip_addresses_new = models.ManyToManyField(
> +        to="ipam.IPAddress",
> +        through="ipam.IPAddressToInterface",
> +        related_name="interfaces",
> +        blank=True,
> +        verbose_name="IP Addresses",
> +    )
>  
>      csv_headers = [
>          "device",
> diff --git a/nautobot/ipam/models.py b/nautobot/ipam/models.py
> index 3ab96dbe3..565c14695 100644
> --- a/nautobot/ipam/models.py
> +++ b/nautobot/ipam/models.py
> @@ -11,6 +11,7 @@ from django.db.models import F, Q
>  from django.urls import reverse
>  from django.utils.functional import classproperty
>  
> +from nautobot.core.models import BaseModel
>  from nautobot.core.models.fields import AutoSlugField, JSONArrayField
>  from nautobot.core.models.generics import OrganizationalModel, PrimaryModel
>  from nautobot.core.models.utils import array_to_string
> @@ -742,6 +743,7 @@ class IPAddress(PrimaryModel, StatusModel, RoleModelMixin):
>          blank=True,
>          null=True,
>      )
> +    # TODO: remove assigned_object fields
>      assigned_object_type = models.ForeignKey(
>          to=ContentType,
>          limit_choices_to=IPADDRESS_ASSIGNMENT_MODELS,
> @@ -975,6 +977,23 @@ class IPAddress(PrimaryModel, StatusModel, RoleModelMixin):
>      mask_length = property(fset=_set_mask_length)
>  
>  
> +class IPAddressToInterface(BaseModel):
> +    ip_address = models.ForeignKey("ipam.IPAddress", on_delete=models.CASCADE)
> +    interface = models.ForeignKey("dcim.Interface", blank=True, null=True, on_delete=models.CASCADE)
> +    vm_interface = models.ForeignKey("virtualization.VMInterface", blank=True, null=True, on_delete=models.CASCADE)
> +
> +    def clean(self):
> +        super().clean()
> +
> +        if self.interface is not None and self.vm_interface is not None:
> +            raise ValidationError(
> +                {"interface": "Cannot use a single instance to associate to both an Interface and a VMInterface."}
> +            )
> +
> +        if self.interface is None and self.vm_interface is None:
> +            raise ValidationError({"interface": "Must associate to either an Interface or a VMInterface."})
> +
> +
>  @extras_features(
>      "custom_fields",
>      "custom_validators",
> diff --git a/nautobot/virtualization/models.py b/nautobot/virtualization/models.py
> index e808212d0..6d02d4fe4 100644
> --- a/nautobot/virtualization/models.py
> +++ b/nautobot/virtualization/models.py
> @@ -461,6 +461,14 @@ class VMInterface(BaseModel, BaseInterface, CustomFieldModel, NotesMixin):
>          object_id_field="assigned_object_id",
>          related_query_name="vminterface",
>      )
> +    # TODO migrate and remove "ip_addresses" and rename "ip_addresses_new" to "ip_addresses"
> +    ip_addresses_new = models.ManyToManyField(
> +        to="ipam.IPAddress",
> +        through="ipam.IPAddressToInterface",
> +        related_name="vm_interfaces",
> +        blank=True,
> +        verbose_name="IP Addresses",
> +    )
>      tags = TaggableManager(through=TaggedItem, related_name="vminterface")
>  
>      csv_headers = [
> ```
> 
>  ```python
> >>> ip = IPAddress.objects.first()
> >>> intf = Interface.objects.first()
> >>> vmintf = VMInterface.objects.first()
> >>> intf.ip_addresses_new.add(ip)
> >>> vmintf.ip_addresses_new.add(ip)
> >>> intf.ip_addresses_new.all()
> <IPAddressQuerySet [<IPAddress: 661:cd9a:7f5:32c5:9c58:26f9:1747:45d4/128>]>
> >>> vmintf.ip_addresses_new.all()
> <IPAddressQuerySet [<IPAddress: 661:cd9a:7f5:32c5:9c58:26f9:1747:45d4/128>]>
> >>> ip.interfaces.all()
> <RestrictedQuerySet [<Interface: Eth1>]>
> >>> ip.vm_interfaces.all()
> <RestrictedQuerySet [<VMInterface: Eth1>]>
> >>> another_intf = Interface.objects.last()
> >>> ip.interfaces.add(another_intf)
> >>> ip.interfaces.all()
> <RestrictedQuerySet [<Interface: Eth1>, <Interface: Eth3>]>
> >>> another_intf.ip_addresses_new.all()
> <IPAddressQuerySet [<IPAddress: 661:cd9a:7f5:32c5:9c58:26f9:1747:45d4/128>]>
> ```

Seeing as this enforcement is on the clean method how much risk is there for use of bulk operations for this use case creating bad data? Are these relationships more prone to bulk uses?

**Comment by glennmatthews** [comment]
No more so than many of the other cases where we recommend against using bulk operations, IMO.

**Comment by jathanism** [comment]
> ```diff
> ```diff
> diff --git a/nautobot/ipam/models.py b/nautobot/ipam/models.py
> index 3ab96dbe3..565c14695 100644
> --- a/nautobot/ipam/models.py
> +++ b/nautobot/ipam/models.py
> @@ -11,6 +11,7 @@ from django.db.models import F, Q
>  from django.urls import reverse
>  from django.utils.functional import classproperty
>  
> +from nautobot.core.models import BaseModel
>  from nautobot.core.models.fields import AutoSlugField, JSONArrayField
>  from nautobot.core.models.generics import OrganizationalModel, PrimaryModel
>  from nautobot.core.models.utils import array_to_string
> @@ -742,6 +743,7 @@ class IPAddress(PrimaryModel, StatusModel, RoleModelMixin):
>          blank=True,
>          null=True,
>      )
> +    # TODO: remove assigned_object fields
>      assigned_object_type = models.ForeignKey(
>          to=ContentType,
>          limit_choices_to=IPADDRESS_ASSIGNMENT_MODELS,
> @@ -975,6 +977,23 @@ class IPAddress(PrimaryModel, StatusModel, RoleModelMixin):
>      mask_length = property(fset=_set_mask_length)
>  
>  
> +class IPAddressToInterface(BaseModel):
> +    ip_address = models.ForeignKey("ipam.IPAddress", on_delete=models.CASCADE)
> +    interface = models.ForeignKey("dcim.Interface", blank=True, null=True, on_delete=models.CASCADE)
> +    vm_interface = models.ForeignKey("virtualization.VMInterface", blank=True, null=True, on_delete=models.CASCADE)
> +
> +    def clean(self):
> +        super().clean()
> +
> +        if self.interface is not None and self.vm_interface is not None:
> +            raise ValidationError(
> +                {"interface": "Cannot use a single instance to associate to both an Interface and a VMInterface."}
> +            )
> +
> +        if self.interface is None and self.vm_interface is None:
> +            raise ValidationError({"interface": "Must associate to either an Interface or a VMInterface."})
> +
> +
>  @extras_features(
>      "custom_fields",
>      "custom_validators",
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> Seeing as this enforcement is on the clean method how much risk is there for use of bulk operations for this use case creating bad data? Are these relationships more prone to bulk uses?
> ```

We'd also want to consider using a `m2m_changed.pre_add` signal to block creation on validation like what we did with Dynamic Groups and Dynamic Group Memberships.
