### ISSUE TITLE
Migrate Existing ScheduledJobs to Support New Format

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#3192]
### Proposed Changes

~In #3132 `NautobotFakeRequest` was moved from `nautobot.utilities.utils` to `nautobot.core.utils.requests`. All `ScheduledJob` instances need to be updated to reflect this change.~

`NautobotFakeRequest` has been removed in #3611 so this would need to extract any relevant fields from the `NautobotFakeRequest` in the 1.x version of `ScheduledJob` and set it in the new version of `ScheduledJob` .

`kwargs["commit"]` (drop it)
`kwargs["data"]` => `kwargs`
`kwargs["user"]` => `user` if `user` was not already set on the `ScheduledJob`
`kwargs["task_queue"]` => `queue` and `celery_kwargs["queue"]`

### Justification

Scheduled jobs will fail with `Can't decode message body: DecodeError(ModuleNotFoundError("No module named 'nautobot.utilities.utils'")` until this is fixed.

**Comment by gsnider2195** [comment]
> Is/would this be negated if we do #3210 ?

Yes. A migration would still be needed but it would need to be done as part of #3210 and this issue could be cancelled

**Comment by HanlinMiao** [comment]
Closed by #3824
