### ISSUE TITLE
Consider Retaining Netbox Commit History

### ISSUE THREAD

**Issue by carlmontanari** [nautobot/nautobot#32]
Preface/disclaimer: I don't know enough to have any smart words about the actual legal bits of licensing/forking and I want to make it clear I am not trying to say that things were done in bad faith or against a license or anything like that -- this is just a friendly comment/inquiry!

Would you consider retaining the Netbox commit history? Fork away, by all means, but it :feelsbadman: that 147 peoples work that made Netbox what it is, and made it into something ya'll wanted to fork and build off of has been completely erased from this project. Removing that history, while maybe totally legit per licensing things (I have no idea, and again, not speculating if its right or wrong), is a pretty bad look. 

Feel free to close, but thought it was worth raising.

**Comment by jedelman8** [comment]
The decision to remove the git history was a technical one (we will publish more details on why in a blog post), but we recognize it wasn't the right move.  We will be publishing the git history later on today.

**Comment by glennmatthews** [comment]
We have restored the Git history from NetBox. The blog post with more context has been posted as well: https://blog.networktocode.com/post/why-did-network-to-code-fork-netbox/ .

Note that restoring the Git history means that any existing forks of this repository will become out of sync; the recommended approach for any such fork is to save their local diffs to file, delete and re-create the fork.

**Comment by carlmontanari** [comment]
Thank you @jedelman8  and @glennmatthews! I know ya'll didn't remove it out of spite or anything like that, but it is really nice and important to have the history back to show all the hard work everyone has put into Netbox. Wish ya'll the best on with Nautobot!
