### ISSUE TITLE
DRF Spectacular generating warnings "<class> is not compatible with schema generation"

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#3218]
### Environment
* Nautobot version (Docker tag too if applicable): v2.0.0a1
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce

This can also be seen in CI

https://github.com/nautobot/nautobot/actions/runs/4057146859/jobs/6982545543#step:5:440

Not seeing it in v1.5.9 so something introduced in 2.0.0 alpha is causing this warning to be generated

**Comment by gsnider2195** [comment]
This appears to be coming from the [django-filter](https://github.com/carltongibson/django-filter/blob/54d143fec55cd5220bdd9119b58dc32c4538fd58/django_filters/rest_framework/backends.py#L148) package

**Comment by glennmatthews** [comment]
Maybe?

```python
>>> DeviceViewSet().get_queryset()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/source/nautobot/extras/api/views.py", line 172, in get_queryset
    request = self.get_serializer_context()["request"]
  File "/source/nautobot/extras/api/views.py", line 289, in get_serializer_context
    context = super().get_serializer_context()
  File "/usr/local/lib/python3.7/site-packages/rest_framework/generics.py", line 135, in get_serializer_context
    'request': self.request,
AttributeError: 'DeviceViewSet' object has no attribute 'request'
```

**Comment by glennmatthews** [comment]
I don't see this in current `next` CI (checked the five most recent runs as of this comment). @gsnider2195 are you still seeing this locally at all?

**Comment by gsnider2195** [comment]
> I don't see this in current `next` CI (checked the five most recent runs as of this comment). @gsnider2195 are you still seeing this locally at all?

I see it when I pull down `ghcr.io/nautobot/nautobot-dev:2.0.0-alpha.1` and run `check-schema` but I don't see it when I run it against `ghcr.io/nautobot/nautobot-dev:next`. Maybe another fix or a dependency update fixed the error message so may be good to close?
