### ISSUE TITLE
Ability to schedule jobs more frequently

### ISSUE THREAD

**Issue by tbotnz** [nautobot/nautobot#3221]
### As ...

Patti - Platform Admin

### I want ...

To be ability to schedule jobs to trigger every 1,5,15,30 minutes

### So that ...

i can use jobs to update information in the db more frequently

### I know this is done when...

on the job scheduling form i can select every 1 minute, 5 minutes or 15 minutes

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

Yes, additional choices required

**Comment by tbotnz** [comment]
happy to look into doing this if it will be accepted anytime soon

**Comment by bryanculver** [comment]
<img width="833" alt="image" src="https://user-images.githubusercontent.com/31187/216511530-37bd36e5-fb74-4fcc-afd3-b01f6b87b025.png">


Does recurring custom solve this? You can write your own cron expression for the schedule. Introduced in 1.3.10: https://github.com/nautobot/nautobot/issues/1226

**Comment by tbotnz** [comment]
Cheerw @bryanculver thats what i was looking for didnt even notice it in the UI lol
