### ISSUE TITLE
Searching for an IP-Address in the main search field causes server error

### ISSUE THREAD

**Issue by sirtux** [nautobot/nautobot#323]
### Environment
* Python version: 3.8.5
* Nautobot version: 1.0.0b3

### Steps to Reproduce
1. Enter in the main search field on top something which looks like an IP 
2. This calls an URL like https://nautobot.local/search/?q=192.168.10.1
3.

### Expected Behavior
A search result is displayed

### Observed Behavior

```
The complete exception is provided below:


<class 'TypeError'>

cannot convert 'NoneType' object to bytes

Python version: 3.8.5
Nautobot version: 1.0.0b3
```

**Comment by dd1245** [comment]
I have this same issue when searching for IP addresses. Other objects seem ok.

**Comment by jathanism** [comment]
This is fixed in #301. 

Can you please try installing beta4 from the `develop` branch and confirm that this fixes it for you? We have a handful of other IP-related fixes as well.

**Comment by sirtux** [comment]
Can confirm that it works in b4.

**Comment by jathanism** [comment]
Thanks @sirtux
