### ISSUE TITLE
Jobs Overhaul: Cleanup dummy tasks and other alpha/prototype code

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#3230]
- [ ] Remove dummy tasks from `nautobot.extras.tasks`
- [ ] Remove `nautobot.core.celery.tasks.debug_task_prerun` signal
- [ ] Assert that all **new** `TODO(jathan)` comments have been addressed or converted into backlog items before this ships.

**Comment by bryanculver** [comment]
Being done with #3228
