### ISSUE TITLE
Jobs Overhaul: Establish `JobResultManager` as true subclass

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#3231]
IN #3164 a `nautobot.extras.managers.JobResultManager` class was introduced and is used as the manager for `JobResult` in v2, but it is subclassing `RestrictedQuerySet.as_manager().__class__` vs using a real manager class (because one doesn't exist).

Realistically the work for `django-natural-keys` and establishing managers vs. `FooQuerySet.as_manager()` patterns across the board will be the right palce to do this, as we can then just subclass the new base manager class.

**Comment by bryanculver** [comment]
#2900 is now complete.

**Comment by bryanculver** [comment]
@nautobot/core I believe this was addressed in #2900 and can be closed https://github.com/nautobot/nautobot/pull/3423/files#diff-b510d41222c70c0e90ac572276472713e1bfa1ed9c4e3d6bf26544b538f9d35aL8-R10
