### ISSUE TITLE
Assign IP to Multiple Interfaces: Prototype M2M Change

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3236]
Investigate how other aspects need to be changed/improved (potentially create some one-off stories for future follow-on in 2.0)

- Primary IP on Device is a 1-to-1 enforcement, this likely can be derived 
- What additional fields should live on the through table
- Primary IP of interface vs Primary IP of device
    - #1099

This should be the master issue and branch to go into `next`. Other subsequent PRs will target this (as it likely won't be mergable initially, forms and filters will be broken).

Since a spike of this nature will almost certainly be a "draw the rest of the owl" problem, it will build on #3190. It will help size the following story in #2403.

**Comment by gsnider2195** [comment]
## Through table fields

|  field  |  type  |  choices  |  constraints  |
|-------|--------|-----------|---------------|
| `source`[^3] | `BooleanField` | `True`/`False` | |
| `destination`[^3] | `BooleanField` | `True`/`False` | |
| `primary`[^1] | `BooleanField` | `True`/`False` | |
| `secondary`[^2] | `BooleanField` | `True`/`False` | |
| `default`[^1] | `BooleanField` | `True`/`False` | |
| `preferred`[^1] | `BooleanField` | `True`/`False` | |
| `primary_for_device` | `BooleanField` | `True`/`False` | Limited to one per device |



[^1]: [JunOS interface configuration](https://www.juniper.net/documentation/us/en/software/junos/interfaces-fundamentals/topics/topic-map/protocol-family-interface-address-properties.html#id-configuring-default-primary-and-preferred-addresses-and-interfaces)
[^2]: [Cisco IOS configuration](https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/ipaddr/command/ipaddr-cr-book/ipaddr-c1.html#wp1930336422)
[^3]: [Cisco tunnel configuration](https://www.cisco.com/c/en/us/td/docs/security/vpn_modules/6342/vpn_cg/6342site3.html#wp1036092)

**Comment by lampwins** [comment]
One point of clarification on primary IP, it needs to be zero or one of each family type (v4, and v6) per device. I.e. a device may have both a primary v4 and v6 address at the same time.

**Comment by gsnider2195** [comment]
> One point of clarification on primary IP, it needs to be zero or one of each family type (v4, and v6) per device. I.e. a device may have both a primary v4 and v6 address at the same time.

Thanks for the reminder. I probably would have forgotten to account for different address families!

**Comment by bryanculver** [comment]
Completed with #3399
