### ISSUE TITLE
UI 2.0: How should we serve the UI & API seamlessly?

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3240]
- `/api`, `/ui`, etc
- Going to need to keep legacy UI views servable
- Easy upgrading/migrating existing views that can easily adopt new UI

**Comment by glennmatthews** [comment]
Per https://github.com/nautobot/nautobot/pull/3285#discussion_r1103060850, current plan is to group all UI-related API URLs under `/api/ui/`, e.g. `/api/ui/get-menu/`, `/api/ui/filterset-fields/lookup-choices/` etc.

**Comment by bryanculver** [comment]
> Per [#3285 (comment)](https://github.com/nautobot/nautobot/pull/3285#discussion_r1103060850), current plan is to group all UI-related API URLs under `/api/ui/`, e.g. `/api/ui/get-menu/`, `/api/ui/filterset-fields/lookup-choices/` etc.

Can we ensure we don't needlessly spend time publishing/maintaining serializers or swagger docs for our UI? They are not needed and can and should break as they will be tightly coupled with our UI and are not meant for integrating externally.

**Comment by glennmatthews** [comment]
It's absolutely possible to exclude endpoints from the schema, and I agree that we should do so for the API-UI endpoints.

**Comment by jathanism** [comment]
> It's absolutely possible to exclude endpoints from the schema, and I agree that we should do so for the API-UI endpoints.

Further, the UI API endpoints should be considered "private" despite being public, so that we don't have to support them for anything other than what we need until such time we feel it is sufficiently stable to say otherwise. This give us license to say "sorry, please use the primitives, calling the UI API endpoints directly is not supported".

**Comment by HanlinMiao** [comment]
Closed by #3385
