### ISSUE TITLE
UI 2.0: Authentication (session, cookies, etc) to be able to hit both the API and UI

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3242]
This should be possible using cookies and session-based authentication. We may need to implement some additional API endpoints to check for session validity, but perhaps not. 

We already have DRF configured for `rest_framework.authentication.SessionAuthentication`, so this shouldn't be too bad.

Some references:

- https://testdriven.io/blog/django-spa-auth/
- https://www.django-rest-framework.org/api-guide/authentication/#sessionauthentication

**Comment by gsnider2195** [comment]
May be able to use an implementation similar to [this](https://blog.logrocket.com/adding-login-authentication-secure-react-apps/)

**Comment by bryanculver** [comment]
Closed via #3356
