### ISSUE TITLE
Add User to override the UI view for Time Zone

### ISSUE THREAD

**Issue by mattmiller87** [nautobot/nautobot#3263]
### As ...

Ozzie - Operator

### I want ...

Preface: UTC is the recommendation for consistent time across the platform and tech stack.
What we would like to see is the ability for a user to override their view of time presented to them. Nautobot's UI would allow users to specify their time zone and the conversion would be done on the front end for them. 

### So that ...

This would improve user's understanding of local time and events in relation to their time zone.

### I know this is done when...

- A user can specify their timezone in their profile and override what the application presents to them

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by lampwins** [comment]
I think the proper way to do this will be to introduce a new template tag that is used to render datetime objects. It will read from a new user config setting for "display timezone" and fallback to the django settings configured timezone. In all cases, the template tag should include the timezone in the display string.

Identify and implement the template tag in all locations where we render a datetime value in the UI today.

**Comment by lampwins** [comment]
Another option might be django native TimezoneMiddleware to identify the user's timezone. https://docs.djangoproject.com/en/4.2/topics/i18n/timezones/#selecting-the-current-time-zone
