### ISSUE TITLE
Have child devices installed in bays list their interfaces in the parent interface list.

### ISSUE THREAD

**Issue by TheFuzzyTech** [nautobot/nautobot#3275]
### As ...

Nelly - Network Engineer

### I want ...

Child devices installed in device bays to show their interfaces as part of the parent device, with a boolean to determine if that should happen.

### So that ...

uplink cards in access switches can be tracked as separate hardware, but have their interfaces be part of the parent device.

### I know this is done when...

installing a device into a device bay:

- there is a checkbox to allow the child device interfaces to either become listed with the parent interfaces
- a way to order the interfaces, IE with cisco devices, each card typicaly iterates by one number device/card/interface meaning 1/1/1 would be port one on bay one of device one, 1/2/1 would be port one on bay two of device 1
- the interfaces show up under the parent device interfaces, and are removed when the child is uninstalled

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

I believe the data is already present, there would need to be a model change for determining if the child device should have it's interfaces listed, and how it should be formatted.

**Comment by lampwins** [comment]
Hi, this sounds like a known misunderstanding of the intend of device bays (parent/child devices). They are intended for modeling chassis based hardware where there is no shared control or data plane, i.e. the devices are all managed independently and the parent chassis more or less only provides power and housing. Think of things like blade servers. Line card based chassis devices where there is one control plane are not meant to be modeled this way.

The litmus test for this distinction is to ask whether or the chassis device has a single management IP from which you configure and control the entire device, across all line cards. If you do have a case where you are managing line cards independently of one another (thereby logically managing each line card as its own device), device bays might be an acceptable means of modeling such devices, but we typically find that to be rare.

Instead, it would be more appropriate to create the chassis network device as normal, but create all of the interfaces across the line cards as discrete interfaces on the chassis (named accordingly) and track the line cards as inventory items on the device. There are means for bulk renaming interfaces if you need to move line cards around.

Chassis devices are also not meant to model distinct network devices with a shared control plane, like a Cisco Stackwise switch. The Virtual Chassis model is suited for that purpose and will be discussed later in this chapter.

You brought up an important point about interface naming and sorting, which Nautobot supports. Meaning there is so called natural ordering functionality that specifically understands how to order interfaces in the networking context when they are named as they appear on the device.

**Comment by TheFuzzyTech** [comment]
Thank you for the clarification.
