### ISSUE TITLE
IP address import - Global VRF

### ISSUE THREAD

**Issue by dbbtuss** [nautobot/nautobot#3286]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.10
* Python version: 3.8.13
* Database platform, version: (PostgreSQL) 10.19
* Middleware(s):

### Steps to Reproduce
1. Import a VRF named "Global" from CSV:
```
name,rd,tenant,enforce_unique,description
Global,,,True,
```

2. Create a Prefix 10.0.0.0/24 without a VRF assigned using the GUI
3. Create an IP Address 10.0.0.65/26 within the prefix using the GUI, do not assign a VRF ("NULL VRF")
4. Import a list of IP Addresses with the VRF "Global" assigned:
```
address,vrf,tenant,status,role,device,virtual_machine,is_primary,dns_name,description
10.0.0.65/26,Global,,active,,,,,,cs1.domain.local
```

If the IP already exists, I should be warned that there is a duplicate.  If there isn't, the IP address should be assigned to the default "NULL" Global VLAN.

Importing the VRF named Global created a "Global" named VRF in the interface, while the default VRF is also called Global.  If I filtered by IP, in the drop-down, I could choose the assigned VRF of "Global" or "Global", which threw up a red flag.

The IP address was allowed to be imported, creating a duplicate IP in the named "Global" VRF rather than the "NULL" Global VRF.  The IP was not assigned to the prefix and was essentially on an island.

The ability to create a VRF either manually or by import named "Global" should be prevented to avoid this confusion.

**Comment by bryanculver** [comment]
Something to note when we address our uniqueness boundaries for IP Address and #254

**Comment by lampwins** [comment]
With the advancements in this area of 2.0 with namespaces, I am going close this one out. If there are new concerns with the data model, let's open specific issues for 2.X.
