### ISSUE TITLE
WebHook should provide old data together with new data

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot#330]
### Environment
* Python version: 3.6.8
* Nautobot version: 1.0.0b3

### Proposed Functionality
I'm submitting this feature request on behalf of @itdependsnetworks for webhooks to include old and new data (pre/post changes).  There was an active issue with Netbox for this same issue, where the feature was recently merged in.  It may be possible to reference this issue/PR and replicate the functionality in Nautobot.

https://github.com/netbox-community/netbox/issues/3451
https://github.com/netbox-community/netbox/commit/c6641ec1de69102162b94a5e7b95246ef903ed8e

### Use Case
An example use case from the linked issue above:
User creates Device/VM in Nautobot and assigns IP address with DNS Name --> DNS Name gets written into the DNS Server. User changes the DNS Name, old DNS Name gets deleted in the DNS and the new one created.

### Database Changes
No

### External Dependencies
None

**Comment by jedelman8** [comment]
@glennmatthews does this need to be a breaking change?  Can we only add a new key-value pair with the original/old data so receiving systems don't break?

**Comment by glennmatthews** [comment]
Looking at the NetBox implementation, it was done as a new parallel set of key-value pairs, so if we follow that pattern, it should be reasonable.

**Comment by bryanculver** [comment]
Merged into `next`.
