### ISSUE TITLE
Review Release Overview of `next`

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3303]
Review the current state of the Release Overview to identify any missing merged changes as well as improvements to the migrators/upgraders guides.

DOD: A PR opened to `next` to add the section headings for the changes, with "TODO" in the paragraph following (see: https://docs.nautobot.com/projects/core/en/stable/release-notes/version-1.5/#database-query-caching-is-now-disabled-by-default-1721)

This way we can open stories to write out the overview of the changes.

**Comment by lampwins** [comment]
Reviewed in sprint 46 and identified TODO items called out above, thus leaving open to resolve those.

**Comment by gsnider2195** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Engineering-64a875e74842500d9e80e23e/issues/nautobot/nautobot/3303?planning-poker) with Zenhub @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1
