### ISSUE TITLE
Branching Naming Conventions

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3314]
### Proposed Changes

Establish a branch naming convention, something like:

- `main`
- `develop`
- `next`
- `prototype/0000-branch-summary` (long-lived prototypes like the one for https://github.com/nautobot/nautobot/issues/2308#issuecomment-1424786991)
- `u/[un/initials]-0000-branch-summary`

Where `0000` is the Github issue number.

### Justification

Finding high-interest branches (`main`,`develop`,`next`) can be hard since alpha sorted they are mixed between issue-number leading branch names or users who's names are before the letter N.

**Comment by gsnider2195** [comment]
I'd like to nominate `u/[un/initials]-0000-branch-summary` for an optional branch name

**Comment by bryanculver** [comment]
Whatever we accept here I would update the pre-commit hook (https://github.com/nautobot/nautobot/blob/develop/scripts/git-hooks/pre-commit) to ensure you commit to a user-leading branch name (taking in consideration @gsnider2195's comment above).

**Comment by cmsirbu** [comment]
I'm not sure there's a need for numbers in the branch name - unless they are tied to an issue or some other reference?

**Comment by jathanism** [comment]
> I'm not sure there's a need for numbers in the branch name - unless they are tied to an issue or some other reference?

Some people tend to put the issue number in the branch name. It's optional.

**Comment by bryanculver** [comment]
> > I'm not sure there's a need for numbers in the branch name - unless they are tied to an issue or some other reference?
> 
> Some people tend to put the issue number in the branch name. It's optional.

I am proposing making it required.

**Comment by bryanculver** [comment]
> I'm not sure there's a need for numbers in the branch name - unless they are tied to an issue or some other reference?

They are intended to map to the issue number in Github. It should be an exception to not have them.

**Comment by jathanism** [comment]
> I am proposing making it required.

🤐
