### ISSUE TITLE
ObjectChange Created Regardless of Change

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot#3321]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.10
* Python version: 3.7
* Database platform, version: PostgreSQL/MySQL
* Middleware(s): Golden Config

### Steps to Reproduce
1. Stand up instance of Nautobot.
2. Fill instance with devices and associated data.
3. Edit a Device and save without changing anything.
4. Review changelog for Device and see another change log entry was created with no diff filled in as nothing changed on the Device object.

### Expected Behavior
Expect no change log entry to be created as nothing changed.

### Observed Behavior
It appears that regardless of whether any fields were changed on an object an ObjectChange, ie changelog, entry is created upon object save. This means that any objects that are saved, even if nothing changes, has an entry. This leads to a large number of garbage logs that are unnecessary in the database. This becomes even more of a concern with Apps like Golden Config where each compliance feature has a changelog and an entry is created everytime a compliance Job is ran. This means that if there are 30 features to be evaluated for 1000 Devices, even if nothing has changed for these Devices there are now 30k more change log entries in the database.

**Comment by bryanculver** [comment]
@jdrew82 Does the last updated field get updated though...

**Comment by Kircheneer** [comment]
Changing this could be considered a breaking change as currently this also triggers job hooks.

**Comment by jdrew82** [comment]
@bryanculver It does appear that the `last_updated` field is being updated to be close to the `time` field for the ObjectChange object.

**Comment by lampwins** [comment]
So the question is, do we want the `last_updated` to be updated with no other object data changed? Sure, that's what django does in this case, but is it really what we want?

**Comment by jdrew82** [comment]
IMO, if no other data about the object has changed, ie no fields have changed, then there's no reason for a changelog to be created cause nothing about it changed. The object wasn't actually "updated" in this cause so the `last_updated` being changed to the save data is a bit of a misnomer cause there was no update.

**Comment by lampwins** [comment]
@nautobot/core just to confirm, with the recent work in this area, this issue still exists, right?

**Comment by glennmatthews** [comment]
To the best of my knowledge, yes.
