### ISSUE TITLE
New Install On Jetson Nano Appliance

### ISSUE THREAD

**Issue by jimthedj65** [nautobot/nautobot#3325]
### Environment
When running through the nautobot install, there are a few pip3 errors
 
Following the steps documented here https://docs.nautobot.com/projects/core/en/stable/installation/nautobot/#prepare-the-virtual-environment

### Steps to Reproduce
Install Nautobot[¶](https://docs.nautobot.com/projects/core/en/stable/installation/nautobot/#install-nautobot)

Use Pip to install Nautobot:
pip3 install nautobot
 
produces these errors?
 
 
```Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/etl/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ksqatnpv/psycopg2-binary_1168853d0dbf45cf8a09e4eb819417b9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ksqatnpv/psycopg2-binary_1168853d0dbf45cf8a09e4eb819417b9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-o2a92dak
       cwd: /tmp/pip-install-ksqatnpv/psycopg2-binary_1168853d0dbf45cf8a09e4eb819417b9/
  Complete output (7 lines):
  running egg_info
  creating /tmp/pip-pip-egg-info-o2a92dak/psycopg2_binary.egg-info
  writing /tmp/pip-pip-egg-info-o2a92dak/psycopg2_binary.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-o2a92dak/psycopg2_binary.egg-info/dependency_links.txt
  writing top-level names to /tmp/pip-pip-egg-info-o2a92dak/psycopg2_binary.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-o2a92dak/psycopg2_binary.egg-info/SOURCES.txt'
  Error: b'You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.\n'

```
  ----------------------------------------
```WARNING: Discarding https://files.pythonhosted.org/packages/fc/51/0f2c6aec5c59e5640f507b59567f63b9d73a9317898810b4db311da32dfc/psycopg2-binary-2.8.6.tar.gz#sha256=11b9c0ebce097180129e422379b824ae21c8f2a6596b159c7659e2e5a00e1aa0 (from https://pypi.org/simple/psycopg2-binary/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Collecting nautobot
  Downloading nautobot-1.2.10-py3-none-any.whl (26.2 MB)
     |████████████████████████████████| 26.2 MB 887 bytes/s
ERROR: Cannot install nautobot==1.0.0, nautobot==1.0.1, nautobot==1.0.2, nautobot==1.0.3, nautobot==1.1.0, nautobot==1.1.1, nautobot==1.1.2, nautobot==1.1.3, nautobot==1.1.4, nautobot==1.1.5, nautobot==1.1.6, nautobot==1.2.0, nautobot==1.2.1, nautobot==1.2.10, nautobot==1.2.11, nautobot==1.2.2, nautobot==1.2.3, nautobot==1.2.4, nautobot==1.2.5, nautobot==1.2.6, nautobot==1.2.7, nautobot==1.2.8 and nautobot==1.2.9 because these package versions have conflicting dependencies.
 
The conflict is caused by:
    nautobot 1.2.11 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.2.10 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.2.9 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.2.8 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.2.7 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.2.6 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.2.5 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.2.4 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.2.3 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.2.2 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.2.1 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.2.0 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.1.6 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.1.5 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.1.4 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.1.3 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.1.2 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.1.1 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.1.0 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.0.3 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.0.2 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.0.1 depends on psycopg2-binary<2.9.0 and >=2.8.6
    nautobot 1.0.0 depends on psycopg2-binary<2.9.0 and >=2.8.6
```
 
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
 
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

### Expected Behavior
Nautobot can complete install

### Observed Behavior
The install fails with dependencies on psycopg2-binary

**Comment by bryanculver** [comment]
Two observations:
- Is there a reason you're installing Nautobot 1.2?
- `Error: b'You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.\n'` suggests a system dependency for Postgres is missing (which uses the system binary for the Postgres client in the psycopg2 library). I suspect you skipped over this step (https://docs.nautobot.com/projects/core/en/stable/installation/centos/#postgresql-setup) but that could probably be enhanced for a client-only install step.

**Comment by jimthedj65** [comment]
> Two observations:
> 
> * Is there a reason you're installing Nautobot 1.2?
> * `Error: b'You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.\n'` suggests a system dependency for Postgres is missing (which uses the system binary for the Postgres client in the psycopg2 library). I suspect you skipped over this step (https://docs.nautobot.com/projects/core/en/stable/installation/centos/#postgresql-setup) but that could probably be enhanced for a client-only install step.

Hi Bryan 

I was following the instructions https://docs.nautobot.com/projects/core/en/stable/installation/nautobot/#prepare-the-virtual-environment 
I have postgres installed and running, I did create my own database and not the install default? will the install script look for the default DB name and user?

I ran through all the dependencies here https://docs.nautobot.com/projects/core/en/stable/installation/ubuntu/#install-system-packages
``` the only change I made was as follows:
psql (12.5 (Ubuntu 12.5-0ubuntu0.20.04.1))
Type "help" for help.

postgres=# CREATE DATABASE mydb;
CREATE DATABASE
postgres=# CREATE USER myuser WITH PASSWORD 'mypassword';
CREATE ROLE
postgres=# GRANT ALL PRIVILEGES ON DATABASE myuser TO mydb;
GRANT
postgres=# \q

```

the install script that runs this as default; maybe a compatibility issue and its searching for a library not available to the jetson nano architecture?

I can connect to my postgres db ```sudo psql --username myuser --password --host localhost mydb```

hope that helps

**Comment by jimthedj65** [comment]
I installed **sudo apt-get install libpq-dev** and added .local/bin to my path and now I get 

Installing collected packages: nautobot
Successfully installed nautobot-1.2.11

Thanks for pointing out the missing dependency, which was detailed in the original instructions, possibly. a platform specific thing.


Then I run below 
```
when I run nautobot-server check
Configuration file does not exist at '/home/myhome/.nautobot/nautobot_config.py'

or 
nautobot-server runserver 0.0.0.0:8080 --insecure

Configuration file does not exist at '/home/pxcghost/.nautobot/nautobot_config.py'
```

**Comment by bryanculver** [comment]
@jimthedj65 did the app eventually start? It says no issues identified.

**Comment by bryanculver** [comment]
Closing as this has gone stale. @jimthedj65 Please update if you're still experiencing this issue.
