### ISSUE TITLE
API Docs page should redirect to login

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#3328]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.10
* Python version: 3.10
* Database platform, version: MySQL
* Middleware(s):

### Steps to Reproduce
1. Be logged out
2. Navigate to /api/docs/

### Expected Behavior
I should be redirected to login and then then return to the API docs

### Observed Behavior
I get a 403 and a message that tells me that I do not have permission to view this page which is confusing to me because it is not immediately clear that I am not logged it, or that I need to be logged in.

**Comment by glennmatthews** [comment]
I don't see this behavior at https://demo.nautobot.com/api/docs/ when logged out.

**Comment by lampwins** [comment]
I would venture to guess this is related to `HIDE_RESTRICTED_UI` which I don't think is enabled in demo.

**Comment by glennmatthews** [comment]
Could be... I didn't think HIDE_RESTRICTED_UI even applied to api/docs/ except maybe to the rendering of the navbar?

**Comment by bryanculver** [comment]
Tried to validate this locally and I couldn't. Maybe combined with SSO this presents?

**Comment by bryanculver** [comment]
@nautobot/core I believe this was addressed by: https://github.com/nautobot/nautobot/issues/3646

@lampwins Any need/desire to make this redirect in all cases, even without `HIDE_RESTRICTED_UI` enabed?

**Comment by glennmatthews** [comment]
After #4787 this page now always redirects to login if not authenticated.
