### ISSUE TITLE
Tell me I don't have any permissions

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#3329]
### As ...

Ozzie - Operator

### I want ...

Nautobot tell me that I don't have any any assigned permissions when I login

### So that ...

It is clear to me why I am not seeing anything in the UI when I login (when I don't actually have any permissions assigned)

### I know this is done when...

- When I don't have any permissions, and I login, show message to the user to indicate they don't have any permissions assigned.
- When I don't have any permissions, hide the both search inputs.

### Optional - Feature groups this request pertains to.

- UI/UX

### Database Changes

None

### External Dependencies

None

**Comment by glennmatthews** [comment]
Is this different than #1646?

**Comment by lampwins** [comment]
Hehe, yes. They guy that opened that one even provided more detail :)
