### ISSUE TITLE
Clarify Custom Relationship UI for list references

### ISSUE THREAD

**Issue by mzbroch** [nautobot/nautobot#333]
### Proposed Functionality

Custom relationships, depending on the relation type, create a url-redirect inside a view either to a list of relations, either to the related object.

This is misleading in some cases, where numbers are used as the object names (ie. vlan name, or the circuit name).

For those cases, it would be useful to distinguish for those two different situations. 

Object Redirect :
![image](https://user-images.githubusercontent.com/16935122/115064108-d3ee1c80-9eec-11eb-8a9d-2ede8643d2d9.png)

List View Redirect :
![image](https://user-images.githubusercontent.com/16935122/115064159-e36d6580-9eec-11eb-83e2-1123ca127a84.png)

**Comment by glennmatthews** [comment]
Thanks for the report! Would just adding some words to the list case, making it something like:

```
IPs         2 related records
```

be an adequate fix here?

**Comment by mzbroch** [comment]
Sounds good to me
