### ISSUE TITLE
Dynamic Groups UI content_types filtering raises KeyError exception

### ISSUE THREAD

**Issue by timizuoebideri1** [nautobot/nautobot#3334]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.6
* Python version: 3.9
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Go to `/extras/dynamic-groups/` 
2. Filter on content_types using the default filter
3.

### Expected Behavior
The filter is applied

### Observed Behavior
![Screenshot 2023-02-17 at 08 19 14](https://user-images.githubusercontent.com/94907097/219576440-eb73985d-0f49-44f8-9550-44118b030b37.png)

**Comment by lampwins** [comment]
Not able to reproduce this on 2.0.4
