### ISSUE TITLE
Prototype: Network Namespaces, RouteDistinguisher, VRF Models

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3337]
Implement the `Namespace`, `RouteDistinguisher`, and `VRF` models (new or changed) from the design described here: https://github.com/nautobot/nautobot/issues/3245#issuecomment-1434806956 and https://github.com/nautobot/nautobot/issues/3245#issuecomment-1433620448.

This is only a prototype so there is no expectation of implementing the data migrations from existing models (current VRF will likely be split up to RD and VRF). A UI-only implementation will be sufficient for getting data entered.

The purpose of this prototype is to take a vanilla install and confirm if the model supports expected use cases. The goal is to ship this in Alpha 2 where we can get real-world validation of these new models.

### To Be Implemented
- [x] `Namespace` model
- [x] `RouteDistinguisher` model
- [x] Updates to `VRF` model
- [x] FK from `Prefix` to `Namespace`
- [x] Optional FK from `Interface` to `VRF`
- [ ] Uniqueness constraints necessary to validate the ultimate goal of #2909 to support #2915 and #1673

### To NOT Be Implemented (we will NOT ship a beta without these)
- Fixing existing test cases
    - Comment them, set them to "expected to fail", leave `TODOs`
- Extensive new test cases
    - We will have minimal-to-missing validations so creating a rich test suite is not necessary at this point
- IPtoInterface M2M
    - (that will come via #3236)
- Extensive data enforcement
    - Ideally based upon the design linked to above an Interface cannot have an IP address from a Prefix in a Namespace it's parent device isn't a part of via VRF->RD
- Overhauls to the natural keys of Prefix, VRF, etc

**Comment by gsnider2195** [comment]
# Use cases

## No namespace, VRF or RD

```mermaid
classDiagram
    class RootPrefix
    RootPrefix : network 10.0.0.0/8
    RootPrefix : namespace null
    class Prefix1
    Prefix1 : network 10.0.0.0/16
    RootPrefix <-- Prefix1
    class Prefix2
    Prefix2 : network 10.128.0.0/16
    RootPrefix <-- Prefix2
    class IPAddress1
    IPAddress1 : address 10.0.0.1
    Prefix1 <-- IPAddress1
    class IPAddress2
    IPAddress2 : address 10.128.0.1
    Prefix2 <-- IPAddress2
    Interface1 --> Device1
    IPAddress1 <-- "primary" Interface1
    IPAddress2 <-- "secondary" Interface1
    Interface2 --> Device2
    IPAddress1 <-- "secondary" Interface2
    IPAddress2 <-- "primary" Interface2
```

## One Namespace, One VRF

## Multiple Namespaces, VRFs and RDs

**Comment by jathanism** [comment]
# Use-Cases

As illustrated in diagrams above.

## No Namespace, VRF or RD

- Most basic, just tracking IPs in “global” namespace
- Only actual constraints are prefix/IP uniqueness in global namespace

## One Namespace, No VRF

- All objects constrained to Namespace
- Same as “No Namespace”, except for FK to Namespace is vs. null

## One Namespace, One VRF

- VRF bound to Namespace
- RootPrefix bound to Namespace
- Child Prefixes (Prefix1, Prefix2) bound to Namepace inherited from Root Prefix
- VRF assigned to Device
- VRF assigned to Interfaces on Device
- Prefixes assigned to VRF (constrained to same Namespace)
- IPAddresses assigned to Interface (constrained by VRF and Prefixes matching VRF/Namespace)

## Multiple Namespaces, VRFs and RDs

> Same VRF name (e.g. data, voice), they should each be in a distinct Namespace
- In the real world
    - If you want the same network in two places, they have to be in different routing tables
        - The same network can’t exist in two places
    - If you want to re-use a VRF name, it must be in the same Namespace
- Namespace NYC
    - VRFs
        - Data
        - Voice
    - Prefixes
        - 10/8
            - 10/16
                - VRF Data
            - 10.128/16
                - VRF Voice
- Namespace SFO
    - VRFs
        - Data
        - Voice
    - Prefixes
        - 192.168/16
            - 192.168/24
                - VRF Data
            - 192.168.128/24
                - VRF Voice

## Not Yet Covered 
- `Namespace` of `Parent` prefix is inherited by child `Prefixes` and `IPAddresses`
    - If the `Namespace` of a child `Prefix` is changed, it gets reparented in the new `Namespace`
        - If there is a eligible parent in the new `Namespace`, that becomes the new parent
        - If there is no eligible parent in the new `Namespace`, the `Prefix` becomes a root 
    - All child `Prefixes`/`IPAddresses` of this `Prefix` also move to the new `Namespace` as in inherited from their top-most parent

# Differences from Agreed Prototype

As codified in prototype #3378

## RouteDistinguisher

- `RouteDistinguisher` is not a uniqueness constraint on `VRF`
- `RouteDistinguisher` is an attribute on the intermediate model (`VRFDeviceAssignment`) when a `Device` is assigned to a `VRF`

## VRF

- `VRF` does not have a foreign key to `RouteDistinguisher`
- `VRF` has a foreign key to `Namespace` which IS used as a uniqueness constraint (`name`, `namespace`)
    - `Namespace` is no longer derived through `RouteDistinguisher` 
        - `VRF` has a many-to-many to `Devices` through intermediate model `VRFDeviceAssignment`
    - You don't need to create a unique `VRF` for every single `Device`
    - This was facilitated by the desire to be able to assign `Prefixes` to a `VRF`
    - Optional `RouteDistinguisher` (if set) must namespace of `VRF`
- `VRF` has a many-to-many to `Prefixes` through intermediate model `VRFPrefixAssignment`
    - `Prefix` namespace must namespace of `VRF` (if set on `Prefix`)
- No direct relationship between `VRF` and `RouteDistinguisher`
    - To filter `VRFs` by RD, the `VRFDeviceAssignment` objects would need to be used
        - `VRFDeviceAssignment.objects.filter(vrf__name="vrf1").values("rd")`
    - To filter RDs by VRF, the VRFDeviceAssignment objects would need to be used
        - `VRFDeviceAssignment.objects.filter(rd__rd="65000:1").values("vrf")`

## Nullable vs. Non-nullable Namespace Relationship

- Non-nullable relationship to `Namespace` with default
    - Default: `Namespace.objects.get_or_create(name=``"``Global``"``)`
    - `default=get_default_namespace` of `Namespace(name=``"``Global``"``)`
    - Always magically creates `Namespace(name="Global")` which may be surprising; would need to be documented
- Non-nullable relationship to `Namespace` NO default
    - Identical pattern to `Status`
    - We ship a `Namespace(name="Global")` (a la `Status`)
    - Users can rename it, but there must always be one if you want to use IPAM
    - UI/UX would need to be clear that at least one `Namespace` is required for `Prefix`, `RouteDistinguisher`, `VRF`, et al.
- Nullable relationship to `Namespace`
    - `unique_together` constraint is upheld at database layer if none of compound fields are null 
    - `FooModel.validate_unique()` required to assert that duplicate objects with `namespace=None` cannot be created
        - Only validated when `full_clean()` is called
        - Can be enforced using a `pre_save` signal to always call `full_clean()`
        - Signal is only required for enforcing clean when mutating objects using ORM as (forms/serializers always call `full_clean()`

**Comment by jathanism** [comment]
Documented use-cases from brainstorming session:

# IPAM Prototype Use-Cases

## Basic IPAM

Simple IPAM for a single location.

### Requirements

- One location, flat network
- Prefixes/IPs only

### Solution

- Global (null) namespace
- No duplicate prefixes
- No VRFs

## Intermediate IPAM

Remote offices all independent satellites with their own egress.

### Requirements

- Multiple locations
- Same prefix (e.g. 10/8) in each location (SOHO NAT)

### Solution

- One namespace for each location

## Avast

- Merged 3 companies together
- Overlapping prefixes
- They don't want to create new prefixes
- They use VRFs without RD (VRF Lite)

### Requirements

- View into which prefixes are overlapping
- View into which prefixes are available across namespaces

### Solution

- One namespace per entity (prefix)

## MSP

- Managed customers
- Overlapping private IPs spaces (e.g. 10.0.0.1 is always gateway)

### Requirements

- Identify allocations per customer
- No routing between customers
- Internal VRF
- VRF/RD for each customer

### Solution

- One namespace per customer
- One VRF for MSP
- One VRF for each customer, may not need RD

## Datacenter

- Managed customers
- MPLS LSPs routed on core network
- Potential peering between two customers
- NAT might be used by customer, presenting mapped prefixes

### Requirements

- Routing between customers
- Possibly 1:1 NAT from private to public peering

### Solution

- One namespace per customer
- One VRF for DC
- One VRF/RD for each customer

## VRF "Core" in diffrent namespaces

- Duplicates of VRF "Core" all in different routing tables
- Not *actually* the same VRF, only the same name

### Problem

- VRF "Core" with same prefixes
  - prefix1, device1
- VRF "Core" with distinct prefixes
  - !prefix1, device2

### Solution

- VRF "Core" with same prefixes can be re-used across the same namespace
- VRF "Core" with distinct prefixes, unique to each namespace
- No need to create a unique VRF to assign to each device

**Comment by whitej6** [comment]
As an MSP with multiple tenants in a domain, I need the ability to filter which tenant has which namespaces available/assigned to better understand assignment/availability.

**Comment by jathanism** [comment]
# IPAM Namespace TODO

```[tasklist]
## General/Model

- [ ]Fix csv_fields, clone_fields on new/updated objects
- [ ] Fix filtersets
- [ ] Fix UI forms
- [ ] Fix UI views/viewsets
- [ ] Fix API views/viewsets
```

```[tasklist]
## Factories
- [ ] PrefixFactory add namespace
- [ ] PrefixFactory remove VRF
- [ ] VRFFactory remove RD
- [ ] VRFFactory add devices
- [ ] VRFFactory add prefixes
- [ ] IPAddressFactory remove VRF
```

```[tasklist]
## Unit Tests
- [ ] Unit tests for Namespace
- [ ] Unit tests for RouteDistinguisher
- [ ] Unit tests for VRF
- [ ] Unit tests for VRFDeviceAssignment
- [ ] Unit tests for VRFPrefixAssignment
- [ ] Unit tests for Prefix
- [ ] Unit tests for IPAddress
```

```[tasklist]
## Namespace
- [ ] FK to Tenant?
- [ ] FK to Location?
- [ ] Description field?
- [ ] What other extras features do we want?
- [ ] Adjust "default=" relationship for other models. Currently it is using `get_default_namespace` which simplifies `unique_together` constraints since it is not nullable.
- [ ] UI: Show related objects (prefixes, RDs, VRFs) akin to Roles detail view?
```

```[tasklist]
## RouteDistinguisher
- [ ] Name field?
- [ ] Description field?
- [ ] What other extras features do we want?
- [ ] It shouldn't be possible to add an RD to a VRF in another namespace
- [ ] UI: Show related objects (devices) akin to Roles detail view?
```

```[tasklist]
## Prefix
- [ ] UI: Child Prefixes nav tab in Prefix detail view (PrefixDetailTable) defaults to showing "Global" namespace, not matching that of the Prefix (should be same namespace as parent, once parenting implemented)
- [ ] When you go to "add child prefix", it should default to the same Namespace as the parent
```

```[tasklist]
## VRF
- [ ] `VRF.add_device(device, rd)` and `VRF.remove_device(device)` model methods to discourage use of `vrf.devices.add()`
- [ ] `VRF.add_prefix(prefix)` and `VRF.remove_prefix(prefix)` model methods `vrf.prefixes.add()`
- [ ] UI: Need to devise a way to assign an RD to a VRF when associated to a Device
- [ ] UI: Show assigned RDs/devices and ability to edit RDs

**Comment by bryanculver** [comment]
Prototype completed and demonstrated in Sprint 46 with #3378. The decision is to move forward and ship Namespaces and related changes in an upcoming alpha (#3429)
