### ISSUE TITLE
Docs version flyout menu overflows screen

### ISSUE THREAD

**Issue by cmsirbu** [nautobot/nautobot#3343]
### Environment
* Online Nautobot Docs: https://docs.nautobot.com/projects/core/en/stable/
* Firefox and Chrome on a 1080p screen

### Steps to Reproduce
1. Open https://docs.nautobot.com/projects/core/en/stable/
2. In the bottom right of the page, click on the flyout version selector `v:stable` menu.
![image](https://user-images.githubusercontent.com/9288571/220425972-66ac2cc7-b5d2-4927-955a-f9eae02d7fbb.png)

### Expected Behavior
The full flyout menu should fit onto the screen.

### Observed Behavior
3. The pop-up menu now overflows out of the visible browser area in a 1080p resolution. It seems a bit worse in Firefox than in Chrome, but both behave similarly.
![image](https://user-images.githubusercontent.com/9288571/220425474-e18a588d-fec7-4115-8d57-b7ceff43fdfa.png)
4. It's not possible to collapse it back down without reloading the page or zooming out.

Some proposed solutions in the discussion thread: https://github.com/nautobot/nautobot/discussions/2507

**Comment by bryanculver** [comment]
Done! 
<img width="323" alt="image" src="https://github.com/nautobot/nautobot/assets/31187/8eeb68e1-726a-4b25-85e9-12329bd73d10">

**Comment by cmsirbu** [comment]
Bliss.
