### ISSUE TITLE
Editing a Location does not auto-fill parent field in edit form

### ISSUE THREAD

**Issue by mzbroch** [nautobot/nautobot#3347]
### Environment
* Nautobot version (v2.0.0a1)
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Create a hierarchy of LocationTypes
2. Create parent Location
3. Create child Location
4. Edit child Location

### Expected Behavior
Newly opened Location edit-form should auto-fill parent

### Observed Behavior
Newly opened Location edit-form does not auto-fill parent
<img width="568" alt="Screenshot 2023-02-22 at 09 52 14" src="https://user-images.githubusercontent.com/16935122/220570304-2aeffbae-8d62-4e15-a70a-69caa51273ab.png">
<img width="722" alt="Screenshot 2023-02-22 at 09 52 30" src="https://user-images.githubusercontent.com/16935122/220570268-2873d5a4-392a-40c0-b10d-45a40a908e12.png">

**Comment by glennmatthews** [comment]
Sounds very similar to #2311; I wonder if something's regressed here.

**Comment by glennmatthews** [comment]
Looks to have regressed in #2773 despite attempts to avoid doing so. This is a thorny corner of code.
