### ISSUE TITLE
`nautobot.extras.plugins.api.views.PluginsAPIRootView` creates `null` entries when `PluginConfig` does not define a `base_url`

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#337]
### Environment
* Python version: 3.9
* Nautobot version: 1.0.0b3

### Steps to Reproduce
1. Create a plugin with `name` set to `myplugin` but in its `PluginConfig` do not define a `base_url`
2. Create a model and standard API viewset in the plugin
3. Navigate to the `/api/plugins/` endpoint

### Expected Behavior
The response should contain the hyperlink to the plugin's root view with the key `myplugin`

### Observed Behavior
The plugin's hyperlink key is `null`.

<img width="356" alt="Screen Shot 2021-04-17 at 10 08 02 PM" src="https://user-images.githubusercontent.com/1297132/115131881-6fed5600-9fc9-11eb-9395-e54b13d3aa73.png">

This is caused because `nautobot.extras.plugins.PluginConfig` defines `base_url = None` and `nautobot.extras.plugins.api.views.PluginsAPIRootView` incorrectly checks if `base_url` has been define in the plugin's config. See https://github.com/nautobot/nautobot/blob/ac1768ab78448955c42425144ddfa91509a13aa1/nautobot/extras/plugins/__init__.py#L41 and https://github.com/nautobot/nautobot/blob/ac1768ab78448955c42425144ddfa91509a13aa1/nautobot/extras/plugins/views.py#L72

The `base_url` attribute is actually defined but it is `None` so `label` is never actually considered. We just need to adjust this logic.

**Comment by FragmentedPacket** [comment]
I'm curious after looking into this. Do we need to check/validate what settings should NOT be left as `None`?

It appears we aren't doing any validations for required attributes for `PluginConfig`, but just for the plugin's actual settings.
