### ISSUE TITLE
Add new `dcim.choices`

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot#3377]
### As ...

Ozzie - Operator

### I want ...

to have more `dcim.choices` for:

- `PortTypeChoices`
- `PowerPortTypeChoices`
- `InterfaceTypeChoices`

and others, such as the ones added to Netbox lately. Idea: An import of the differences in the dcim/choices.py file in [Netbox](https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/choices.py) vs [Nautobot](https://github.com/nautobot/nautobot/blob/develop/nautobot/dcim/choices.py) would make it pretty straight-forward.

### So that ...

I could have more type options to choose.

### I know this is done when...

- The newer type choices are available when creating the related `dcim` objects

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [X] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by bryanculver** [comment]
Related: https://github.com/nautobot/nautobot/issues/838

**Comment by alextremblay** [comment]
I'll tackle this. I'll update all existing choicesets in dcim/choices.py with new entries from netbox, while we wait for movement on #838. Can you assign me the issue?

**Comment by glennmatthews** [comment]
Gladly :-) Thank you!
