### ISSUE TITLE
Migration Doc Revision: Database Backup

### ISSUE THREAD

**Issue by HanlinMiao** [nautobot/nautobot#3386]
### Proposed Changes

We should add a guide elaborating on how to make a copy of the database with all database backends (PostgreSQL and MySQL).

### Justification

Since 2.0.0 involves many database migrations and it is heavily recommended to back up the current database before committing to any data migrations, we should help users to correctly back up their database regardless of their database backends. Right now, the only similar documentation we have is `docs/installation/migrating-from-postgresql` but it is PostgreSQL-specific and we do not have any documentation on exporting data from MySQL.

**Comment by bryanculver** [comment]
Closed via #4206
