### ISSUE TITLE
Migration Doc Revision: Getting a Nautobot App v2.0 Ready

### ISSUE THREAD

**Issue by HanlinMiao** [nautobot/nautobot#3387]
### Proposed Changes

We should add a guide as a part of our migration docs to teach users how to upgrade their Nautobot Apps (how to squash migrations and etc) so that they can be installed correctly in a Nautobot V2.0 environment.

### Justification

There are many existing Nautobot apps out there that rely on v1.X Nautobot Core models (`Site`, `Region`,  `Aggregate`...). Some of these core models are removed in 2.0.0 and their information is only retained and transferred by correct migrations. We need to publish a guide to allow Nautobot App developers to upgrade their apps to be v2.0 compatible.

**Comment by bryanculver** [comment]
A Core team member should work with an app maintainer and document anything that is missing in our current documentation around migrating those apps. This will be done once we ship an RC for apps to be able to start migrating against but deliverable before 2.0.0.

**Comment by glennmatthews** [comment]
Would be good to look at current app PRs for 2.0 to see what changes they've had to make and make sure they're documented appropriately as necessary tasks:

- https://github.com/nautobot/nautobot-plugin-bgp-models/pull/109
- https://github.com/nautobot/nautobot-plugin-ssot/pull/142
- https://github.com/nautobot/nautobot-plugin-ssot/pull/151
