### ISSUE TITLE
Unable to select multiple entries on (Multiple) selection custom fields in filter

### ISSUE THREAD

**Issue by phoenixswiss** [nautobot/nautobot#3391]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.11
* Python version: 3.8.10
* Database platform, version: postgresql, Ubuntu 12.12-0ubuntu0.20.04.1
* Middleware(s): -

### Steps to Reproduce
1. Create a custom field (selection, or multiple selection) with multiple options and assign it to interfaces or devices
2. Fill the custom field with some information
3. Open the filter on the device or interface overview and switch to the Default tab

**on custom field of the type selection**

5. move to the custom field and try to select multiple entries

**on custom field of the type multiple selection**

5. move to the custom field and select multiple entries

6. Press Apply

### Expected Behavior
As with the Device field, multiple entries can be selected and all entries matching the filter will be displayed.

### Observed Behavior
**on custom field of the type selection**
Only one entry can be selected.

**on custom field of the type multiple selection**
Multiple entries can be selected, but only the last selected entry will be used for the filter.

**Comment by bryanculver** [comment]
I believe this is related to: https://github.com/nautobot/nautobot/pull/3342

**Comment by lampwins** [comment]
Appears fixed in 2.0.4
