### ISSUE TITLE
DeviceType power port templates: types available in netbox but not nautobot

### ISSUE THREAD

**Issue by alextremblay** [nautobot/nautobot#3398]
### As ...

Tammy - Tools Integrator

### I want ...

To write a datasource provider plugin to import DeviceTypes and their associated device type component templates from https://github.com/netbox-community/devicetype-library

The only problem, so far, is that there exist a few power port device types in netbox which don't exist in nautobot:
 - dc-terminal
 - saf-d-grid
 - ubiquiti-smartpower
 - hardwired
 - other

### So that ...

Nautobot users can import device types from an existing library instead of manually creating them all by hand

### I know this is done when...

The power port types listed abouve are added to `nautobot.dcim.choices.PowerPortTypeChoices

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [X] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

AFAIK no database model changes / migrations will be needed for this change

**Comment by alextremblay** [comment]
"iec-60320-c22" Also appears to be missing from the list

**Comment by glennmatthews** [comment]
This probably falls under the same umbrella as #3377. It should be a pretty easy set of changes to port over from NetBox if anyone wants to make a quick win here.

**Comment by alextremblay** [comment]
Thanks @glennmatthews. I've made a comment in that issue volunteering to tackle this and submit a PR. Should I close this issue as duplicate?

**Comment by glennmatthews** [comment]
Yeah I think that makes sense. Thanks again!
