### ISSUE TITLE
Plugin Development: Received Message to use `python manage.py migrate`

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#340]
### Environment
* Python version: 3.7.7
* Nautobot version: 1.0.0b3

### Steps to Reproduce
1. Create a plugin with some model changes
2. Execute makemigrations step
3. Restart Nautobot (no migrate)

### Expected Behavior

Expected the response to be run `nautobot-server migrate` to apply them

### Observed Behavior

Got a message:
```
You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): <app_name.>.
Run 'python manage.py migrate' to apply them.
```

**Comment by jedelman8** [comment]
Sounds like we have two options for now:

1) Add documentation on this, optionally adding a `nautobot-server` command as a wrapper.
2) What @jathanism documented above overloading those two classes

**Comment by smk4664** [comment]
PR incoming.  I found that we also need to override the runserver from django.contrib.staticfiles.

**Comment by jathanism** [comment]
Sorry about not being clear before. I should have stated that I didn't think the juice was worth the squeeze on this one, but do appreciate the effort spent on it nonetheless.

**Comment by smk4664** [comment]
Yeah, so marking it as a feature and adding it to the MIlestone made me think that this was accepted.
