### ISSUE TITLE
Job Hooks - Not Showing in Jobs Menu / Unable to Enable in Same Fashion as Jobs

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#3400]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.12
* Python version: 3.9
* Database platform, version: Postgres, 13
* Middleware(s): None

### Steps to Reproduce
1. Create a Job Hook following the documentation - https://docs.nautobot.com/projects/core/en/stable/models/extras/jobhook/?h=job+hook#configuration
2. Set up the Job Hook
3. Run a test and get the error that the Job is not enabled, which jives with the current flow
4. Check for the Job under **Jobs** > **Jobs** Menu
5. Unable to see the existing Job Hook

### Expected Behavior

Expected to see the JobHooks in the Jobs list. Or at least an easier method to find the Job Hooks in similar fashion to Jobs in order to enable the Job Hook.

### Observed Behavior

The only way to get to the Jobs Hook to enable it is to:
1. Navigate to **Jobs** > **Job Hooks**
2. From the list of Job Hooks, select the _Job_
3. Then I get the expected Job Detail page that allows the job to be enabled

**Comment by jvanderaa** [comment]
A view of Job Hooks would be something applicable here. 

The Job was synced to Nautobot via Git Repos.

**Comment by bryanculver** [comment]
This was done by applying a default filter as Job Hooks cannot be run the same way as other Jobs, possibly causing a confusing UX.

https://github.com/nautobot/nautobot/blob/v1.5.12/nautobot/extras/views.py#L1039-L1040

But on the Job list view under the filter menu you can set "Is job hook receiver" to True which should show all job hooks in the system.

**Comment by jvanderaa** [comment]
Agreed. Is that default filter setting going to remain? If so, I can see just a quick doc update to include how to view them is something that I could get done.
