### ISSUE TITLE
URL Paths Have Option for Natural Keys

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#3406]
### As ...

Ozzie - Operator

### I want ...

To have natural keys for objects, such as Jobs can have a single path that is consistent across Nautobot instances.

### So that ...

So jobs that may be shared via Git repo, that the ability to launch the job via the API with a natural key (or class path as implemented in 1.2 API).

### I know this is done when...

There are no deprecated paths for launching a job that would be consistent between Nautobot installs.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [X] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- ?

**Comment by lampwins** [comment]
@jvanderaa if we consider only jobs, is this satisfied today?

**Comment by jvanderaa** [comment]
I think that is the case here @lampwins of just Jobs.
