### ISSUE TITLE
time_zone attribute of the Site object emits Null if not set.

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot#342]
GET vs PUT/PATCH/POST endpoint for `/api/dcim/site/` does not represent the `time_zone` attribute in the same fashion. GET will represent an unset time_zone as `null` but attempting to create/edit that field via the API it does not allow for the field to be `null` only `""` or not part fo the payload.

### Environment
* Python version: 3.7
* Nautobot version: develop

### Steps to Reproduce
1. GET to `/api/dcim/sites/<UUID>/` 
2. Return payload `{"name": "Foo", "slug": "foo", "time_zone": null}` (omitted for brevity)

### Expected Behavior
1. GET to `/api/dcim/sites/<UUID>/` 
2. Return payload `{"name": "Foo", "slug": "foo", "time_zone": ""}` (omitted for brevity)

### Observed Behavior
The field within the database does not allow null but allows blank, this can lead to confusion in the API if attempting to POST/PUT/PATCH the same payload back to Nautobot the API will not allow `{"time_zone": null}`.

**Comment by whitej6** [comment]
@jathanism please assign to me.

**Comment by jathanism** [comment]
Thanks for reporting this @whitej6. Confirmed that `Site.time_zone` is a non-nullable char field. The API should emit an unset `time_zone` as an empty string, not `null`.

**Comment by jathanism** [comment]
I am a comment. Shh
