### ISSUE TITLE
Tags - Content Types Allow to Fold Up

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#3428]
### As ...

Ozzie - Operator

### I want ...

To be able to get the content types to fold up.

### So that ...

 so that I don't have a really long page when all content types are selected.

### I know this is done when...

The content types on tags view page has an optional fold up icon that remembers the setting from tag view to tag view.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [X] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by lampwins** [comment]
@jvanderaa curious what you think of this?

<img width="1329" alt="Screen Shot 2023-03-17 at 7 10 09 PM" src="https://user-images.githubusercontent.com/1297132/226067506-18ac4f65-e0c5-4178-87be-3eafdac23583.png">

**Comment by jvanderaa** [comment]
Far left is similar to what we see now. The right most one is looking the most promising here. When selecting all options for content types on tags the list gets pretty long at this point. This is on the tag detailed view.

<img width="703" alt="Screenshot 2023-03-18 at 15 02 47" src="https://user-images.githubusercontent.com/22228848/226135269-7e69bccb-118e-4230-abcd-e048bb39f121.png">
