### ISSUE TITLE
Add slug to virtualization cluster objects

### ISSUE THREAD

**Issue by MeganerdDev** [nautobot/nautobot#3430]
### As ...

Cora - Coder

### I want ...

Add the `slug` field to cluster objects in Virtualization > Clusters.
Presently Cluster Types and Cluster Groups have the slug field but not the Cluster objects.

### So that ...

Instead of using the UUID I can use the slug of the object

### I know this is done when...

- You can specify slug on cluster object creation
`>>> cluster = Cluster.objects.create(name="foobar", type=cluster_type, slug="foobar")`

- You can filter cluster objects by it's slug
`>>> cluster = nautobot.virtualization.clusters.get(slug="foobar")`

- cluster objects have object.slug attribute
`>>> print(cluster.slug)`
 `>>> foobar`

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

Edit: Persona

**Comment by glennmatthews** [comment]
Thanks for the request! This will likely be addressed in 2.0 by the `natural key` feature work (see #3423 and #2900) rather than by adding a new `slug` field to the model.
