### ISSUE TITLE
Missing uniqueness constraint on TaggedItem

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#3437]
### Environment

While [django-taggit's base TaggedItem class has a unique_together constraint](https://github.com/jazzband/django-taggit/blob/master/taggit/models.py#L191), Nautobot's [implementation of this class does not](https://github.com/nautobot/nautobot/blob/develop/nautobot/extras/models/tags.py#L89). We should add this constraint in 2.0 and handle any deduplication of data needed in migrations.

### Steps to Reproduce

```python
>>> TaggedItem.objects.create(content_type=ContentType.objects.get_for_model(Location), object_id=Location.objects.first().pk, tag=Tag.objects.first())
<TaggedItem: Campus-00 tagged with Amber>
>>> TaggedItem.objects.create(content_type=ContentType.objects.get_for_model(Location), object_id=Location.objects.first().pk, tag=Tag.objects.first())
<TaggedItem: Campus-00 tagged with Amber>
>>> TaggedItem.objects.create(content_type=ContentType.objects.get_for_model(Location), object_id=Location.objects.first().pk, tag=Tag.objects.first())
<TaggedItem: Campus-00 tagged with Amber>

>>> TaggedItem.objects.filter(object_id=Location.objects.first().pk)
<RestrictedQuerySet [<TaggedItem: Campus-00 tagged with Amber>, <TaggedItem: Campus-00 tagged with Amber>, <TaggedItem: Campus-00 tagged with Amber>]>
```

### Expected Behavior

Database should prevent duplicate TaggedItem objects from being created.

### Observed Behavior

Duplicate TaggedItem objects can be created.

### TODO

- Delete duplicates as there is no inherent data loss
- UniqueTogether: `(content_type, object_id, tag)`

**Comment by bryanculver** [comment]
Closed with #3813
