### ISSUE TITLE
Create dedicated queues for Jobs and Git repository sync

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#345]
### Proposed Changes

Consider creating dedicated worker queues for Job execution and for Git repository sync -- currently they share the 'default' queue. 

See also:
- https://github.com/nautobot/nautobot/pull/208
- https://github.com/nautobot/nautobot/pull/290/files#r612942314

### Justification

Other background tasks (webhooks, check_releases, custom_fields) each have their own dedicated queues.

**Comment by jathanism** [comment]
The good news is in the new config pattern this is practically a one-liner. :)

**Comment by bryanculver** [comment]
This appears to be out of date. We should allow specifying the queue(s) for these tasks but will likely be superseded by #1860.

**Comment by bryanculver** [comment]
@nautobot/core It seems with the refactoring in 2.0 and #1860 this should be doable now?
