### ISSUE TITLE
Git Repos not sync'd in HA environment after successful sync

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#3490]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.12
* Python version: 3.11
* Database platform, version: Postgres
* Middleware(s):

### Steps to Reproduce

1.  Deploy Nautobot in HA environment without shared git storage (i.e. Kubernetes via helm)
2.  Add Git Repo
3.  Modify the file in git repo
4. Sync (1x)
5. expect both Nautobot instance's local filesystems for change

### Expected Behavior

If the git repo sync succeeds in Nautobot (expected) the git repo should be sync'd across all Nautobot instances. 

### Observed Behavior

Local filesystem copies of the git repo differ between nodes.

**Comment by nniehoff** [comment]
This issue was brought to light when we were debugging https://github.com/nautobot/nautobot/issues/3491 it likely isn't a common occurrence considering the repos should be updated when the jobs are executed however this issue brought to light the fact they are not.  This may be very low impact today but as Nautobot matures we may need to address keeping multiple frontend deployments of Nautobot updated

**Comment by lampwins** [comment]
@nautobot/core is related to the ongoing git issues or something different?

**Comment by gsnider2195** [comment]
I don't think this was ever a feature that was implemented. In 2.x we have the ability to tell the celery workers to sync a git repo but I don't think that applies to other instances of the web server.

**Comment by lampwins** [comment]
The operating model for git repo jobs is to be eventually consistent. When a job is run and the current filesystem copy is out of sync, the worker should first sync the repo and then run the job.
