### ISSUE TITLE
Add ability to store device cost and expose metrics for report creation

### ISSUE THREAD

**Issue by schreyack** [nautobot/nautobot#3492]
### As ...

Mary - Manager

### I want ...

I want to be able to track both the operational and capital costs associated with my environments.  This would include things like purchase cost of hardware and depreciation period.  I would also want to track costs of things like circuits, floor space, power, etc...

### So that ...

I need to be able to create reports to understand how much a group of devices costs me.  For example, how much does Rack X cost?  Or, how much does Site A cost?  Or, how much does my entire environment cost?

### I know this is done when...

I have access to the metrics needed that can be consumed by a reporting tool like Grafana.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

New models perhaps, or can be extended via Device Lifecycle App.

**Comment by whitej6** [comment]
Would like to see this as a higher level acquisition cost for the device type level (not at an individual device) with a depreciation percent per year plus a purchase date field.

**Comment by jvanderaa** [comment]
Depreciation is something that I would go with in the Device Lifecycle Plugin for a starting place.

**Comment by lampwins** [comment]
This is good app candidate but not likely something we will take on in core any time soon.
