### ISSUE TITLE
assign a location to a device in the same site

### ISSUE THREAD

**Issue by r000m5** [nautobot/nautobot#3494]
### Environment
* Nautobot version: 1.5.14
* Python version: 3.9.2
* Database platform, version: Postgresql 13
* Middleware(s):

### Steps to Reproduce
1. create a device using the GUI
2. create a location type with only the mandatory parameters
3. create a location with only the mandatory parameters, with Active status and in the same site than the device
5. edit the device and set device's location

### Expected Behavior
I expect to be able to associate the location I previously created to the device.

### Observed Behavior
When trying to set the location of the device, no location is available for selection ("no result found")

**Comment by glennmatthews** [comment]
Thanks for the report! Can you confirm whether you specified that the `LocationType` permits Devices? 

![image](https://user-images.githubusercontent.com/5603551/228040907-aeb7d20e-8f9f-4729-ac88-324a4759dcfb.png)
