### ISSUE TITLE
FieldError when sorting VMs list by primary IP

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#3503]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.7
* Python version: 3.7.16
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Sort VirtualMachines by primary IP column
https://demo.nautobot.com/virtualization/virtual-machines/?sort=primary_ip

### Expected Behavior
VMs sorted by primary IP

### Observed Behavior
![image](https://user-images.githubusercontent.com/26114847/228221835-64fd73de-79e6-48a1-9b4a-318b8b0f2100.png)

**Comment by david-kn** [comment]
It works for other model(s) e.g. `devices` though: https://demo.nautobot.com/dcim/devices/?sort=primary_ip
So it's some funny inner bug in relationships probably...

**Comment by glennmatthews** [comment]
Thanks for the report and for the context! 

`DeviceTable` has `primary_ip = tables.Column(linkify=True, order_by=("primary_ip6", "primary_ip4"), verbose_name="IP Address")` while `VirtualMachineTable` has just `primary_ip = tables.Column(linkify=True, verbose_name="IP Address")`. Probably adding the missing `order_by` to the latter would be sufficient to fix this.
