### ISSUE TITLE
Admin search field hidden by nav bar

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#3514]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.13
* Python version: 3.9
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Have enough top level Nav menu items to cause the nav bar to expand vertically
2. Navigate to a list view within the admin interface
3. 
4.

### Expected Behavior
Be able to see and use the search bar for that admin component (not the global search)

### Observed Behavior
The nav bard vertical wrap hides the search field

If you zoom the page out far enough to bring the nav bar back to a single line, the search is visible again.

**Comment by bryanculver** [comment]
Probably the admin UI needs the same treatment as https://github.com/nautobot/nautobot/pull/1542

**Comment by lampwins** [comment]
Closing this out with the changes in 2.1
