### ISSUE TITLE
duplicate IDs from nb.ipam.prefixes.all()

### ISSUE THREAD

**Issue by NobodyIsPerfect78** [nautobot/nautobot#3519]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.9 
* Python version: 3.9.16
* Database platform, version: postgres 13.10.1
* Middleware(s):

### Steps to Reproduce

nb = api(url=NB_URL, token=NB_TOKEN, threading=True, retries=0)

prefix_list=nb.ipam.prefixes.all()
print (len(prefix_list))

prefix_id_dict={}
for prefix in prefix_list:
    id=prefix["id"] 
    if id in prefix_id_dict:
        print("Duplicate ID found")
    else:
        prefix_id_dict[id] = prefix

### Expected Behavior

The expectation is that:
1. all existing prefixes are supplied by the function.
2. no duplicate prefixes or duplicate ID are returned.

The number of missing prefixes is equal to the duplicate prefixes

### Observed Behavior

With approx. 170000 prefixes I get approx. 50 duplicates

**Comment by jvanderaa** [comment]
Just to verify that this is an issue within Nautobot and not the pynautobot SDK (https://github.com/nautobot/pynautobot) can you verify the number of prefixes that are returned from the raw API call (such as https://demo.nautobot.com/api/ipam/prefixes/ -> which shows "count" on that page)

**Comment by NobodyIsPerfect78** [comment]
So the number of prefixes is identical both via pynautobot and via the API. 
My thesis is that it sends multiple get requests in parallel due to the high number of prefixes. These are provided with an offset. But between the get-requests the order in the prefix table changes, so several prefixes are passed twice.

**Comment by bryanculver** [comment]
Interesting...

@NobodyIsPerfect78 do you have Cacheops enabled?

**Comment by NobodyIsPerfect78** [comment]
No, we have cacheops disabled:

NAUTOBOT_CACHEOPS_ENABLED=False

**Comment by bryanculver** [comment]
This is not really fixable in 1.5 because of the way the parenting algorithm and non-concrete relationships are being handled within the context of pagination. You should be getting duplicate objects, but not different objects with the same IDs.

This has been addressed in 2.0 with #2915
