### ISSUE TITLE
REDIS Port os.getenv() with integer fails pylint

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#353]
### Environment
* Python version: 3.7.10
* Nautobot version: 1.0.0b4

### Steps to Reproduce
1. Load latest nautobot_config.py from develop into chatops plugin development
2. Run through tests on chatops plugin
3. Pylint errors as environment vars are all strings, and the config defaults to an integer for inconsistent data types

### Expected Behavior

Expected no pylint errors on chatops plugin

### Observed Behavior

Pylint errors for inconsistent import of environment variable (string) vs default int

**Comment by jathanism** [comment]
Oh, I see why you submitted #354 now. What is the exact error from pylint?
