### ISSUE TITLE
Include Scheduled Jobs Name in Job Results 

### ISSUE THREAD

**Issue by JimmyKip** [nautobot/nautobot#3535]
### As ...

Ozzie - Operator

### I want ...

The Job Results page to include the Schedule Name as well as the Job name as we schedule the same job with different parameters (eg it may run on different Tenant devices at different times of the day), and give each schedule a unique name.

### So that ...

I can easily determine which Job Result is from a Scheduled job without needing to cross-reference the time it ran to the Scheduled Jobs page.

### I know this is done when...

Viewing the Job Results page there is an additional column for the Schedule Name if the Job Result was generated from a Scheduled Job.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [X] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

I think this probably does require DB changes as the extras_jobresult table doesn't include any reference to the Schedule currently.

**Comment by glennmatthews** [comment]
#6167.
