### ISSUE TITLE
IPAM related queries missing in GraphQL API

### ISSUE THREAD

**Issue by sirtux** [nautobot/nautobot#355]
### Environment
* Python version: 3.8.5
* Nautobot version: v1.0.0b4

### Steps to Reproduce
1. Run the following GraphQL Query:
```
prefixes{
  id
}
```

### Expected Behavior
Getting results

### Observed Behavior
```
{
  "errors": [
    {
      "message": "Syntax Error GraphQL (1:1) Unexpected Name \"prefixes\"\n\n1: prefixes{\n   ^\n2:   id\n",
      "locations": [
        {
          "line": 1,
          "column": 1
        }
      ]
    }
  ]
}
```

The same issue appears for all IPAM-related stuff, as it sees.

**Comment by sirtux** [comment]
A manual redis clear helped after the update - ticket closed.

**Comment by jathanism** [comment]
Caching strikes again! Thanks @sirtux!
