### ISSUE TITLE
Hardware Family

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#3559]
### As ...

Austin - Network Automation Engineer

### I want ...

Models to express hardware and software families

### So that ...

I can form higher level relationships like "all Nexus 3k devices" regardless of specific device types in play.

### I know this is done when...

- A hardware family model is created and is offered as an optional FK on the device type model

### Optional - Feature groups this request pertains to.

- Automation

**Comment by glennmatthews** [comment]
Implemented in #5040.
