### ISSUE TITLE
Implement a "startplugin" management command to ease plugin development

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#356]
### Environment
* Python version: *
* Nautobot version: next

### Proposed Functionality

I propose that we implement a management command called `startplugin` inspired by Django's built-in [`startapp`command](https://docs.djangoproject.com/en/3.2/ref/django-admin/#startapp).

### Use Case

The current documentation informs the reader about the skeleton of a Nautobot plugin but expects them to create them from scratch. Since every Nautobot plugin is in fact a Django app, basing a command to help bootstrap a new plugin from the Django `startup` command greatly reduce the barrier to entry to developing Nautobot plugins.

Starting with the `startapp` command and then adding extra files or directories required by Nautobot plugins would be something that would also simplify the documentation.

I envision developers using `nautobot-server startplugin <path>` to create a new plugin structure, with base files/directories.

### Database Changes

None.

### External Dependencies

None.

**Comment by smk4664** [comment]
Would you mind if I take this one?  I will start by just building out the template to allow `django-admin startapp --template` and then see how to get `nautobot-server startplugin` to call it.

**Comment by smk4664** [comment]
Or I could use management commands and cookiecutter.

**Comment by glennmatthews** [comment]
Thanks for offering! I'd vote for at least seeing how far you can go with the `startapp` approach since that doesn't require adding `cookiecutter` as a dependency, but I'm not opposed to the cookiecutter approach if it provides functionality that `startapp` lacks.
