### ISSUE TITLE
Can't move IP Addresses between Namespaces

### ISSUE THREAD

**Issue by mzbroch** [nautobot/nautobot#3580]
### Environment
* Nautobot version (Docker tag too if applicable): Nautobot 2 alpha.3
* Python version: 3.8
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Create 2 namespaces, 2 prefixes
2. Allocate an IP Address to namespace
3. Try moving IP Address between namespaces

### Expected Behavior
🤷‍♂️ 

### Observed Behavior
Nautobot UI confirms the IP address was modified, however there is no actual result - IP Address is not moved.

This is either by design , either false message is shown

**Comment by jathanism** [comment]
That's certainly not something that was tested, so thanks for testing that. Obviously we'll cover this when we resume the Namespace work soon. Thanks for the report!

**Comment by jathanism** [comment]
The reason this isn't working currently is because of `IPAddress.save()`:

```python
       if not self.present_in_database:
            if self._namespace is None:
                raise ValidationError({"parent": "Namespace could not be determined."})
            namespace = self._namespace
        else:
            namespace = self.parent.namespace
```

See: https://github.com/nautobot/nautobot/blob/next/nautobot/ipam/models.py#L1008-L1013

We'd need to change it to this:

```python
       if self._namespace is None:
           raise ValidationError({"parent": "Namespace could not be determined."})
       namespace = self._namespace
```

... And then of course write some extra tests.
