### ISSUE TITLE
Circuit export with filter not working

### ISSUE THREAD

**Issue by FloLaco** [nautobot/nautobot#3599]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.2 (even in demo.nautobot.com )
* Python version: 3.8
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Go to Circuits
2. Filter some circuit (by type, or anything else)
3. Click on `Export`

### Expected Behavior
We should have a CSV with only filtered result

### Observed Behavior
We have all circuit, even the filtered one

**Comment by glennmatthews** [comment]
Sounds a lot like #3274, which is fixed in 1.5.11 and later.

**Comment by FloLaco** [comment]
Oops, didn't saw it, and I thought demo.nautobot.com was to the latest version because I tried in the demo before submited the issue
