### ISSUE TITLE
Unable to filter Dynamic Groups

### ISSUE THREAD

**Issue by tanleach** [nautobot/nautobot#3612]
### Environment
* Nautobot version (Docker tag too if applicable): v1.5.16
* Python version: 3.10.11
* Database platform, version: Postgres 15.1
* Middleware(s): N/A

### Steps to Reproduce
1. <nautobot_url>/extras/dynamic-groups/?&content_type=ipam.prefix&q=

### Expected Behavior
Dynamic groups would show only entries where content_type is 'ipam.prefix' (not specific to `ipam.prefix`)

### Observed Behavior
Server Error:
``` 
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'KeyError'>

'dynamic groups'

Python version: 3.7.16
Nautobot version: 1.5.7
```
FWIW: also able to reproduce here: https://demo.nautobot.com/extras/dynamic-groups/?&content_type=dcim.device&q=

**Comment by glennmatthews** [comment]
Thanks for the report! Looks like a bug in the [`get_filterset_parameter_form_field` function ](https://github.com/nautobot/nautobot/blob/develop/nautobot/utilities/utils.py#L909-L920)- it's looking for content-types corresponding to the feature `dynamic groups` but the feature is registered as `dynamic_groups`.

**Comment by jathanism** [comment]
> Thanks for the report! Looks like a bug in the [`get_filterset_parameter_form_field` function ](https://github.com/nautobot/nautobot/blob/develop/nautobot/utilities/utils.py#L909-L920)- it's looking for content-types corresponding to the feature `dynamic groups` but the feature is registered as `dynamic_groups`.

I did a little triage and determined that this occurs with the `model._meta.verbose_name_plural` being passed through without being slugified. I suspect we would run into this issue on other objects but it's somewhat hidden from other models of `content_type` relationships because most of them have single-word names.
