### ISSUE TITLE
Circuits cannot be filtered by location

### ISSUE THREAD

**Issue by Phill93** [nautobot/nautobot#3616]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.16
* Python version: 3.9.2
* Database platform, version: Postgres 13.9 
* Middleware(s): None

### Steps to Reproduce
1. Create a Location
2. Create Circuits and assign them to the location
3. Try to filter the Circuits list with the location

### Expected Behavior
A list of circuits assigned to this location

### Observed Behavior
```
<class 'django.core.exceptions.FieldError'>

Unsupported lookup 'slug' for AutoSlugField or join on the field not permitted.

Python version: 3.9.2
Nautobot version: 1.5.16
```

**Comment by glennmatthews** [comment]
Thanks for the report! Confirmed reproducible on demo.nautobot.com.

**Comment by glennmatthews** [comment]
Interestingly appears to not be an issue in `next` as far as I can tell.

**Comment by Phill93** [comment]
Is there a release date for `next`?
