### ISSUE TITLE
Replace `ChoiceSet` with Django built-in enumeration types

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#3619]
### Proposed Changes

I propose that we eliminate `nautobot.core.choices.ChoiceSet` (`nautobot.utilities.choices.ChoiceSet` in v1) and replace all custom choice enums with instances of Django built-in [enumeration types such as `django.db.models.TextChoices`](https://docs.djangoproject.com/en/4.2/ref/models/fields/#enumeration-types). 

It's also worth noting that there is also an `IntegerChoices` enum. Additionally, these objects are fundamentally just Python standard library [`enum`](https://docs.python.org/3/library/enum.html#functional-api) types under the hood.

### Justification

The `ChoiceSet` implementation is unwieldy and requires a lot of boiler plate. It also does not currently support membership tests such as `foo in MyChoiceSet`. While certainly we could continue to extend and maintain `ChoiceSet`, it is my professional opinion that this provides little value at the cost of maintaining yet another bespoke solution that is already more thoroughly solved within the Django core.

This would result in the reduction of hundreds of lines of code and corresponding unit tests for `ChoiceSet` itself.

Compare the following examples:

#### ChoiceSet

The only way to do a membership test is to cast the `ChoiceSet` to a dict using its `as_dict()` method. Additionally, the definition requires manually constructing the `CHOICES` enum on the object including having to specify the mapped value of the choice, which is prone to error and inconsistencies.

```python
>>> from nautobot.core.choices import ChoiceSet
>>> class MyVersionChoices(ChoiceSet):
...     KV_VERSION_1 = "v1"
...     KV_VERSION_2 = "v2"
...     CHOICES = (
...             (KV_VERSION_1, "V1"),
...             (KV_VERSION_2, "V2"),
...     )
...
>>> "v1" in MyVersionChoices
False
>>> "v1" in MyVersionChoices.CHOICES
False
>>> "v1" in MyVersionChoices.as_dict()
True
>>> MyVersionChoices.CHOICES
(('v1', 'V1'), ('v2', 'V2'))
```

#### TextChoices

All that is required is establishing the enum values and everything else happens automatically.

```python
>>> from django.db import models
>>> class MyVersionChoices(models.TextChoices):
...     v1 = "v1"
...     v2 = "v2"
...
>>> "v1" in MyVersionChoices
True
>>> MyVersionChoices.choices
[('v1', 'V1'), ('v2', 'V2')]
```

**Comment by jathanism** [comment]
Considerations:

- Named groups such as [`InterfaceTypeChoices.CHOICES`](https://github.com/nautobot/nautobot/blob/develop/nautobot/dcim/choices.py#L376-L390) are [not supported by enumeration types](https://docs.djangoproject.com/en/3.2/ref/models/fields/#field-choices-named-groups)

**Comment by smk4664** [comment]
I should probably comment that I am taking this.

Also need to consider [CustomLinkButtonClassChoices](https://github.com/nautobot/nautobot/blob/develop/nautobot/extras/choices.py#L104-L106) Since this is going in 2.0, I am okay with removing the CustomLinkButtonClassChoices, since it was previously deprecated, but it is important to note that Inheritance of an Enum Class that has members (i.e. ButtonClassChoices) is prohibited. https://docs.python.org/3/howto/enum.html#restricted-enum-subclassing

**Comment by smk4664** [comment]
Another issue will be [`ButtonActionColorChoices](https://github.com/nautobot/nautobot/blob/0710c6f7672f7a76b9bcd6dc2efc05c7eefbe0b5/nautobot/utilities/choices.py#L180) as Enum's cannot contain duplicate values.
