### ISSUE TITLE
IP-Interface M2M: Validate GraphQL Representation

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3635]
GraphQL changes (see: https://github.com/nautobot/nautobot/pull/3399/files#diff-9687b347d7a3698e4a385d4fd99ceea3b22424c81f9ec9cdd74bc9a558ac30d1R25)

- M2Ms "Just Work ™️ "
- Need to clean up TODO comments here for no longer relevant fields

**Comment by glennmatthews** [comment]
Closed by #3899.
