### ISSUE TITLE
IP-Interface M2M: Model `clean`, ORM Enforcement

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3637]
- [x] H: IPAddress `clean` (see: https://github.com/nautobot/nautobot/blob/9fe1ffdc6d23bbe86d8d2e9c3ae087233b15e8fc/nautobot/ipam/models.py#L692-L711)
    - This enforcement needs to be moved to the Device/Interface save methods to ensure:
        - Removing an IP address from Interface does not break the `primary_ip` FK from Devices to IP Address
    - This clean on `IPAddress` likely can be removed because we've moved that relationship management to just on Device or Interface
- [x] H: IPAddressToInterface Unique Enforcement (via ORM) (see: https://github.com/nautobot/nautobot/blob/next/nautobot/ipam/models.py#L799-L811)
    - Add `UniqueTogether` constraints for `(ip_address, vm_interface)`, `(ip_address, interface)`
    - Needs to be a pre_add signal to ensure `clean` is called to address

**Comment by HanlinMiao** [comment]
Closed by #3807
