### ISSUE TITLE
Grouped job buttons that require confirmation will always be disabled

### ISSUE THREAD

**Issue by jfach** [nautobot/nautobot#3660]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.16
* Python version: 3.9
* Database platform, version: MySQL
* Middleware(s):

### Steps to Reproduce
1. Create a grouped job button that requires confirmation
2. Navigate to the detail view, and click the dropdown menu. 
3. Notice the job is disabled.

### Expected Behavior
Job button is enabled. 

### Observed Behavior
Job button is disabled.

**Comment by bryanculver** [comment]
🖖 @jfach
