### ISSUE TITLE
NautobotUIViewset with lookup_filed set to 'pk' but slug exist on model causes issues

### ISSUE THREAD

**Issue by jeffkala** [nautobot/nautobot#3663]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5-1.5.17
* Python version: 3.8
* Database platform, version: postgres
* Middleware(s): n/a

While migrating an existing application from oldering `generic.<x>views` to `NautobotUiViewset` hitting a bug where `edit` and `delete` buttons don't show up only when `lookup_field = "pk"` is used but `slug` field does exist on model.

 I have a model where the retrieve view doesn’t show edit/delete buttons. Is there any chance having a slug on a model but modifying everything else including lookup_field = "pk" to use PK could some how cause issues?  Another model that is basically identical is working fine (it does not have a slug field at all). And we’re using the same lookup_field = "pk" on it. Tried versions from 1.5.3 through 1.5.16 with the same result. This is the only model that has a slug field in GC so pulling at straws to figure it out.  Everything else is identical template wise/ model wises/ view wise etc.

### Steps to Reproduce
1. Migrate a models view from the older generic views to NautobotUiViewset.
2. Set `lookup_field = "pk"` on the model.
3. Change the `get_absolute_url` to using `args=[self.pk]`
4. Load the detail(retrieve) view.
5. Buttons (edit,delete) will not display at all.

To get the buttons to show up I can add below to the view.
```
    lookup_field = "pk"
    lookup_url_kwarg = "slug"
```

But the buttons themselves when clicked will fail since they're trying to resolve to the /blah/<slug> url.

### Expected Behavior
Eventhough the model has the slug field, I should be able to use `lookup_field` as a pk to be uniform throughout the app.

### Observed Behavior
buttons don't show up.  If workaround to get buttons to display is implemented the button links fail.

**Comment by jeffkala** [comment]
related to https://github.com/nautobot/nautobot-plugin-golden-config/pull/471

**Comment by bryanculver** [comment]
Thanks for the report @jeffkala

**Comment by HanlinMiao** [comment]
Hi @jeffkala can you try the following steps to see if it works for your case?

1. Migrate a models view from the older generic views to NautobotUiViewset.
2. Set lookup_field = "pk" on the model.
3. Change the get_absolute_url to using args=[self.pk]
4. Load the detail(retrieve) view.
5. In `object_retrieve.html` or your own object detail template override the `{% block buttons %}`. More specifically add `key="pk"` to `{% edit_button object %}` and `{% delete_button object %}. See `rackgroup.html` for an example.
6. The buttons should render correctly and take you to the correct path.
`

**Comment by itdependsnetworks** [comment]
For easier reference: `https://github.com/nautobot/nautobot/blob/2b1ec02285c5f94edb651f2fb5a840d65b1f511a/nautobot/dcim/templates/dcim/rackgroup.html#LL5C1-L15C23`

**Comment by jeffkala** [comment]
That does indeed work.  Did also have to `{ load_buttons }` but figured that step was just assumed.
Would we consider this a bug? Or lack of documentation in this scenario?

**Comment by glennmatthews** [comment]
IMO, the `edit_button` and `delete_button` templatetags should be enhanced to try both `slug` and `pk` and use whichever one actually results in a valid reverse URL lookup. Currently they default to `slug` and if that fails to result in a reversible URL, the buttons are omitted, as you have seen.
