### ISSUE TITLE
Custom field date-type objects AssertionError in GraphQL

### ISSUE THREAD

**Issue by MeganerdDev** [nautobot/nautobot#3664]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.17b1, also tested in 1.5.8
* Python version: 3.9
* Database platform, version: psql 13.10
* Middleware(s): None

### Steps to Reproduce
1. Create a [custom field object](https://demo.nautobot.com/extras/custom-fields/last_backup/?tab=main) for the Device type template with the type as Date
2. Set a date on a [device](https://demo.nautobot.com/dcim/devices/4d7aecac-addd-4f3c-8efc-e102872b54e5/?tab=main) in YYYY-MM-DD iso8601 format
3. You have to restart nautobot-server; we may need a post_save signal event for this as well, which would be a separate issue if so
4. Using GraphQL attempt to retrieve the value of this field from a device
`
{
  devices (name: "ams01-dist-01") {
    name,
    cf_last_backup
  }
}
`

### Expected Behavior
Query to return the value of the Date

### Observed Behavior
* GrapQL returns `"message": "Received not compatible date \"'2023-04-26'\""`
* stdout from nautobot-server gets an exception

`[27/Apr/2023 17:20:01] "POST /graphql/ HTTP/1.1" 200 4437611
Traceback (most recent call last):
  File "/home/meganerd/.cache/pypoetry/virtualenvs/nautobot-Sgl-QJQc-py3.9/lib/python3.9/site-packages/graphql/execution/executor.py", line 480, in complete_value_catching_error
    completed = complete_value(
  File "/home/meganerd/.cache/pypoetry/virtualenvs/nautobot-Sgl-QJQc-py3.9/lib/python3.9/site-packages/graphql/execution/executor.py", line 563, in complete_value
    return complete_leaf_value(return_type, path, result)
  File "/home/meganerd/.cache/pypoetry/virtualenvs/nautobot-Sgl-QJQc-py3.9/lib/python3.9/site-packages/graphql/execution/executor.py", line 626, in complete_leaf_value
    serialized_result = return_type.serialize(result)
  File "/home/meganerd/.cache/pypoetry/virtualenvs/nautobot-Sgl-QJQc-py3.9/lib/python3.9/site-packages/graphene/types/datetime.py", line 23, in serialize
    assert isinstance(
AssertionError: Received not compatible date "'2023-04-26'"`

**Comment by bryanculver** [comment]
> 3. You have to restart nautobot-server; we may need a post_save signal event for this as well, which would be a separate issue if so

This is a known issue: https://github.com/nautobot/nautobot/issues/446

**Comment by bryanculver** [comment]
@MeganerdDev I confirmed this bug. As a workaround, you should be able to access the value via `_custom_field_data`: `{ devices (name: "ams01-dist-01") { name, _custom_field_data } }` and inside you will find the data you're looking for.

**Comment by MeganerdDev** [comment]
@bryanculver The mitigation is working however I was wondering if this can be looked at again for a bugfix? I did some investigation I think might be useful for context

In the serialize method of the Data class in `graphene==2.1.9` ./graphene/types/datetime.py
The serializer expects a date object, and is getting a string instead

Not sure if we wanted to apply a monkey-patch with something like the following, or alternatively ensure the TYPE_DATE custom field object is converted before this serialization?
```python
if not isinstance(date, datetime.date) and isinstance(date, str):
    date = datetime.datetime.strptime(date, "%Y-%m-%d").date()
```

The monkey-patched method
```python
@staticmethod
def serialize(date):
    if isinstance(date, datetime.datetime):
        date = date.date()
    if not isinstance(date, datetime.date) and isinstance(date, str):
        date = datetime.datetime.strptime(date, "%Y-%m-%d").date()
    assert isinstance(
        date, datetime.date
    ), 'Received not compatible date "{}"'.format(repr(date))
    return date.isoformat()
```


Screenshot of testing -> result: working as expected
![image](https://github.com/nautobot/nautobot/assets/114895043/475474a5-e320-43fc-b8d8-cef7af14cc79)

**Comment by lampwins** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Product-64a8783b7a3f4b1225973a0c/issues/nautobot/nautobot/3664?planning-poker) with Zenhub @bryanculver @gsnider2195 @HanlinMiao @jathanism

**Comment by lampwins** [comment]
Need to backport to 1.6
