### ISSUE TITLE
Status field internals documentation for creating new forms is confusing

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#367]
### Environment
* Python version: *
* Nautobot version: b4

### Steps to Reproduce
1. Try to implement a new model w/ a `status` field
2. Go to implement a new model form by following the [Status Internals documentation](https://nautobot.readthedocs.io/en/latest/models/extras/status/#statusfilter-filter-field)
3. Get confused because it doesn't mention that for models that inherit from `nautobot.extras.models.StatusModel`, you don't need to provide a form mixin.

### Expected Behavior

The reader should be able to clearly understand that for base model forms. e.g. if my model is `Foo`, the base `FooForm` for create/update of an object only needs to inherit from base `django.forms.ModelForm`.

### Observed Behavior

The instructions do not reference this explicitly. The reader seems to be directed to inherit from `nautobot.extras.forms.StatusFilterFormMixin`, which is incorrect and will lead to confusion.

**Comment by bryanculver** [comment]
@nautobot/core Since we are no longer implementing `StatusModel` in 2.0, instead preferring `StatusField` (https://github.com/nautobot/nautobot/pull/3785), is this still relevant?
