### ISSUE TITLE
Asset tag size limit increase

### ISSUE THREAD

**Issue by nvallepalli1** [nautobot/nautobot#3693]
### As ...

Austin - Network Automation Engineer

### I want ...

To increase the size limit of the Device Asset Tag field to 100 characters.

### So that ...

We use the Nautobot as SOT to store our CSP assets. With the asset tag size limit of 100 characters, I cannot add the resource ID to the asset tag field. With the increase in the size limit of the asset tag, I can add the ID of the cloud resources to Nautobot. 

### I know this is done when...

- Nautobot UI and API accepts 100 characters for the asset tag of a device

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [X] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- Models already exist and need to increase the size of an asset tag attribute

### External Dependencies

Unsure

**Comment by cmacnevin** [comment]
This is us :) Not sure how you want to treat the max value limit, but hopefully this is an easy fix which can go into a smaller point release?

**Comment by cmacnevin** [comment]
Bump

**Comment by glennmatthews** [comment]
Could possibly be done in 1.6 since we're going to have other migrations in that release anyway?

**Comment by HanlinMiao** [comment]
Closed by #4148
