### ISSUE TITLE
Aggregate Page - Significant Impairment with Large Number of Prefixes

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#3699]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.16
* Python version: 3.9
* Database platform, version: Postgres
* Middleware(s): 

### Steps to Reproduce
1. Assign a large number of Prefixes to an Aggregate (500 seems sluggish, 1000+ may cause time outs)
2. Navigate to Aggregates
3. Then select one of the aggregates with large number 
4. The page load takes a significant amount of time

### Expected Behavior

Expected page load to be pretty quick

### Observed Behavior

Page load on 500 prefixes in an aggregate takes some time
Page load on 2000 prefixes in an aggregate has gateway timeouts

**Comment by lampwins** [comment]
@jvanderaa can you clarify what page is slow here? Step 3 seems to indicate you are talking about the detail view for an aggregate.

**Comment by bryanculver** [comment]
> @lampwins this page in the demo instance (although it may be getting made by hand and not in our data)
> https://demo.nautobot.com/ipam/aggregates/4caf329d-dec9-48c1-86fa-221d45c38603/?tab=main

It's not. I created it to test. The demo dataset for this has 1300 prefixes, well above your timeout threshold. I also produced locally and while it is slow, I don't see it close to the timeout limits.

Would it be sufficient to move these Prefixes to their own tab under Aggregate? Similar to "Child Prefixes" on the Prefix detail view?
