### ISSUE TITLE
CSV Cable Import causes a ValueError

### ISSUE THREAD

**Issue by sirtux** [nautobot/nautobot#371]
### Environment
* Python version: 3.8.5
* Nautobot version: 1.0.0b4

### Steps to Reproduce
1. Go to import cables
2. Try to enter something like:
```
side_a_device,side_a_name,side_b_device,side_b_name,status,side_a_type,side_b_type,type,length,length_unit,color
DH01-A-06-17,eth0,DH01-A-06-28,swp31,active,dcim.interface,dcim.interface,cat5e,2,m,0000ff
```

### Expected Behavior
Cables are imported

### Observed Behavior
```
<class 'ValueError'>

'CableCSVForm' has no field named 'termination_a_id'.

```

**Comment by glennmatthews** [comment]
Thanks for the report! Possibly related to #311 as well?

**Comment by jathanism** [comment]
Sure seems like those two are related. Thanks!

**Comment by glennmatthews** [comment]
Needs some investigation to see whether this can be simply fixed by correcting some error in the CSV import code specific for Cables, or whether it's part of a more general import/export pattern problem of the sort described by #254.
