### ISSUE TITLE
Display custom fields in listings/tabular views

### ISSUE THREAD

**Issue by ggidofalvy-tc** [nautobot/nautobot#372]
### Environment
* Python version: 3.7.3
* Nautobot version: 1.0.0b4

### Proposed Functionality
The ability to select / display custom fields as columns in tabular/listing views (e.g. interfaces on a device) along with the built-in fields.

### Use Case
When one adds a custom field, it is due to having a specific requirement that NetBox is not able to model natively yet. There might be properties that are important enough to display in the overview, and not just in the details of a given object (for example: the "custom role" of an interface).

I am not familiar with the roadmap, but in case custom fields do become "first-class citizens" in the Nautobot ecosystem, this would be a straightforward addition (as opposed to having hardcoded columns for each object type).

### Database Changes
None, as far as I can tell.

### External Dependencies
Don't think so.

**Comment by jathanism** [comment]
Thanks for this request. We'll review it and see if it fits with what we're trying to do!

**Comment by Thetacz** [comment]
FYI: The code for this was already implemented in Netbox and tested in v2.10 (but will be deployed in v2.11), so maybe Nautobot could use it. https://github.com/netbox-community/netbox/pull/5460

This is something we would very much like to see in Nautobot too, few different people already asked me about this possibility.

**Comment by jathanism** [comment]
Fixed in #469
