### ISSUE TITLE
Splash page for Nautobot

### ISSUE THREAD

**Issue by MeganerdDev** [nautobot/nautobot#3732]
### As ...

Patti - Platform Admin

### I want ...

I want to have a splash page for Nautobot, preferably a splash page that can have a generic appearance.

### So that ...

I want to prevent users who stumble on the Nautobot instance from directly knowing the application is Nautobot.

### I know this is done when...

When I use a web browser to reach the homepage Nautobot (while not-authenticated) I am presented with a splash page.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [x] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by glennmatthews** [comment]
See also #3646.

**Comment by lampwins** [comment]
Are there existing industry examples of how this would work? I can think of any number of tools such a nmap that would immediately fingerprint the app as Nautobot. What problem are we trying to solve with this, because it sounds like an argument for security through obscurity?

**Comment by smk4664** [comment]
While not completely obscured, [`HIDE_RESTRICTED_UI`](https://docs.nautobot.com/projects/core/en/stable/configuration/optional-settings/?h=hide#hide_restricted_ui) Does hide the Toolbar and Home Page Elements for unauthenticated users.

**Comment by bryanculver** [comment]
If you're not logged in the splash page for Nautobot should be the login screen.

**Comment by MeganerdDev** [comment]
Thanks for prompt feedback everyone

@lampwins security through obscurity was the idea, but I agree that network scanners will still identify Nautobot from its signatures making this moot for attackers. With that being the case, it seems more accurate to say this is only UI/UX instead of Security.

@smk4664 thanks for bringing [HIDE_RESTRICTED_UI](https://docs.nautobot.com/projects/core/en/stable/configuration/optional-settings/?h=hide#hide_restricted_ui) to my attention, I'll check it out

**Comment by glennmatthews** [comment]
After #4787, the "splash page" for unauthenticated users is the login screen.
