### ISSUE TITLE
Simplified Join/Prefetch Operation on RestrictedQuerySet

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3734]
A prototype of this exists:

- https://github.com/nautobot/nautobot/tree/prototype/3734-with_related-on-restrictedqueryset (via #2657)

### As ...

P.D. - Plugin Developer

### I want ...

A single function I can call to either perform a prefetch (`prefetch_related`) or join (`select_related`) depending on the related information I am requesting.

### So that ...

I do not have to understand the implications or limitations of either method and know that my DB calls will be made more optimally.

### I know this is done when...

A single method on RestrictedQuerySet is available and can take in a list of fields that may or may not support `select_related` and automagically performs the `prefetch_related` as necessary.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [X] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [X] Other (not directly a platform feature)

### Database Changes

?

### External Dependencies

Maybe an impact to `graphene-django-optimizer`?

**Comment by lampwins** [comment]
I'd rather see us focus this towards automatic optimization in common use cases. Closing this one out for now.
