### ISSUE TITLE
Retention Cleanup as Jobs

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3749]
### As ...

Patti - Platform Admin

### I want ...

Have a built-in job to clean up old `JobLogEntry` and `ObjectChange` records instead of settings.

### So that ...

I...
- Can schedule the cleanups for more opportune times (avoiding things #2352)
- Don't have to re-deploy my config to change my retention settings
- Don't have to drop into the ORM for one-off cleanups
- Have a pattern I can mimic if I want to refine my cleanup further (by types, etc)

### I know this is done when...

Job(s) exist in the Jobs list view I can run and/or schedule to clean up my logs.

Could eliminate #2865, #2501, #2352, #2006, #3678.

### Optional - Feature groups this request pertains to.

- Automation
- Other (not directly a platform feature)

**Comment by glennmatthews** [comment]
Added for 2.3 in #5442
