### ISSUE TITLE
UI 2.0: Organize and distinguish React Component Prop attributes and inline CSS style attributes.

### ISSUE THREAD

**Issue by HanlinMiao** [nautobot/nautobot#3763]
### Proposed Changes
We should establish a pattern to clean up and codify the inline CSS style attributes that exist in our React Components. Possibly a dedicated .CSS file for each .js file?

### Justification
Sometimes the React component's prop attributes will get mingled up with inline CSS style attributes, making it hard to distinguish between the types of attributes. We should get rid of CSS style attributes entirely and codify the CSS attributes with style sheets and/or CSS modules. In addition, inline CSS styling is not as performant.

**Comment by bryanculver** [comment]
What are the places we are doing manual CSS that there isn't a style prop for already? https://chakra-ui.com/docs/styled-system/style-props#margin-and-padding
