### ISSUE TITLE
Add Dynamic Group Support to Highly Sought-after Models

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3765]
### Proposed Changes

Add `@extras_features("dynamic_groups")` to the following models:

- Circuits
- Interfaces
- Locations
- Prefix  - completed in #2200
- IPAddress  - completed in #2200

### Justification

FilterSets have been groomed as a part of #1483 and #1737. Toss these ones in for 2.0.0 for now and ensure full coverage (or as a base) in #1822

**Comment by bryanculver** [comment]
Careful consideration on `Location` and `Prefix` as these are tree models and may have weird behavior when it comes to their recursive nature.

**Comment by bryanculver** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Engineering-64a875e74842500d9e80e23e/issues/nautobot/nautobot/3765?planning-poker) with Zenhub @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1

**Comment by bryanculver** [comment]
Split this story, IPAM is blocked by #2807

**Comment by glennmatthews** [comment]
Done through #5473 and related work.
