### ISSUE TITLE
UI 2.0: detail views never populate if /detail-view-config endpoint returns 404

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#3767]
### Environment
* Nautobot version (Docker tag too if applicable): next
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce

Example: https://next.demo.nautobot.com/extras/object-changes/ce20d17c-ed11-455b-93a3-d7efc59594be/

### Expected Behavior

Page to render with some default layout

### Observed Behavior

![image](https://github.com/nautobot/nautobot/assets/5603551/3308c271-451f-4dd9-9a58-b6cff2fbe72a)

![image](https://github.com/nautobot/nautobot/assets/5603551/f9b73ce4-72c3-4f55-9e17-1c9b9b512723)

**Comment by glennmatthews** [comment]
The underlying trigger appears to be that `ObjectChangeViewSet` is not a `NautobotModelViewSet` subclass and so it doesn't implement the `detail-view-config` API action. Regardless, the front-end needs to account for this possibility.

**Comment by HanlinMiao** [comment]
Should this be blocked by https://github.com/nautobot/nautobot/issues/3526?

**Comment by HanlinMiao** [comment]
Closed by #3805
