### ISSUE TITLE
UI 2.0: home page breaks if recent object-changes reference objects that no longer exist

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#3768]
### Environment
* Nautobot version (Docker tag too if applicable): next.demo.nautobot.com
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Create then delete any object
2. View new-UI homepage

### Expected Behavior

Page to render successfully

### Observed Behavior

Page begins to render than displays a blank page. JS console shows errors related to `objectChange.changed_object` being unexpectedly `null`.

**Comment by HanlinMiao** [comment]
Closed by https://github.com/nautobot/nautobot/pull/3781
