### ISSUE TITLE
2.0 Next: New Device Page Doesn't Supply Drop Downs Where Drop Downs Would Be Expected

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#3769]
### Environment
* Nautobot version (Docker tag too if applicable): Next.demo.nautobot.com
* Python version: Next.demo.nautobot.com
* Database platform, version: Next.demo.nautobot.com
* Middleware(s): Next.demo.nautobot.com

### Steps to Reproduce
1. Go to device page (in new view)
2. Create new
3. Expect that things such as Status are a drop down

### Expected Behavior

Expected a drop down for selection items such as Status

### Observed Behavior

Just a text box.

**Comment by glennmatthews** [comment]
The create/edit UI is not complete yet, as we're focusing on the list/retrieve UI at present. But thanks for documenting this!

**Comment by bryanculver** [comment]
Not a bug as not implemented yet.
