### ISSUE TITLE
Next 2.0: Left Hand Nav is Difficult to Read

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#3770]
### Environment
* Nautobot version (Docker tag too if applicable):
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Navigate to next 2.0 UI
2. Look at the left hand panel
3. Make it difficult

### Expected Behavior

Expected to be able to clearly see the left hand nav bar. You should make the screen a bit brighter color.

### Observed Behavior

 This is tough on both large and small screens alike.

**Comment by cmsirbu** [comment]
Couple of additional comments:

1. Dark gray text is indicative of a disabled behaviour.
2. Low contrast (fg-to-bg) is bad in general accessibility/eye strain wise - https://contrastrebellion.com/

![image](https://github.com/nautobot/nautobot/assets/9288571/60b39295-4650-4a0c-b113-4a3bdcac01fe)

**Comment by glennmatthews** [comment]
Closed by nautobot/nautobot-ui#31 and by #3893, with additional refinement in #3784.
