### ISSUE TITLE
Bug present in v1.5.13: "Bulk Add IP Addresses" missing as option when adding new IP #334 

### ISSUE THREAD

**Issue by ICA24** [nautobot/nautobot#3776]
Hi,

Screenshot:
https://ibb.co/12hGfyR
https://ibb.co/kq9NLNZ

In version  v1.5.13 when Bulk importing devices there is no option to specify mgmt IP address. ( ip_address that seems to be used in the system generally does not exist under CSV field options and nor is accepted Unexpected column header "ip_address" found. ) 

Is there a workaround to this? Adding first devices in bulk and then their corresponding mgmt IP addresses in IPAM seems a bit redundant.

Kind Regards,

**Comment by bryanculver** [comment]
Thanks for the report @ieneicsongorattila22!

This is part of our general import/export problems: not being inverses and not having access to all fields. Thankfully this is being solved in 2.0: #254. In 2.0.0 they _generally_ should be able to import all fields available on the object but may have cases (generic foreign keys, M2M) that aren't supported on day 1, also considering the impact from #2403.

**Comment by lampwins** [comment]
This is supported in v2 now.
