### ISSUE TITLE
Rename `Natural-key slug` to `Composite key` throughout the UI and documentation

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#3793]
In sprint review it was determined that `natural-key slug` is not an intuitive name to users and `composite key` would be the preferred terminology. We should update the UI and documentation accordingly.

**MAYBE** also rename the `natural_key_slug` property to `composite_key` in the code as well?

**Comment by itdependsnetworks** [comment]
To provide some of the context. 
* Primary Key will have the chance to be conflated for the terminology of the same name, e.g. giving multiple definitions to the same thing
* Slug is confusing to the average user
* Composite Key is still a standard Computer Science terminology that would result correctly if an interested party was to "Google it"
