### ISSUE TITLE
Add Virtual-Chassis info to starting page

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#380]
### Environment
* Python version: 3.8.5
* Nautobot version: 8fe3909a4f62 (v1.0.0b5)

### Proposed Functionality

Add the Virtual Chassis information to the main webpage in DCIM area (below Devices)

### Use Case

User wants to see the number of locical devices.

When using stacked devices with common management the number of virtual-chassis will be equal the count of logical devices.

### Database Changes

None

### External Dependencies

None

**Comment by jathanism** [comment]
Thanks for the idea @jifox. We'll review this and follow up.
