### ISSUE TITLE
Input validation - forbid using double-quote char '"'

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#381]
### Environment
* Python version: N/A
* Nautobot version: N/A

### Proposed Functionality

When using .csv data the char '"' (double quote) will be used as a string delimiter. This leads to an error when trying to import the exported data.

Additionally a conversion of char `"` to char `'` (single quote) should be implemented, so importing an exported file will not lead to an error.

### Use Case

Allow importing a previously exported .csv file when data contains a `"` character

### Database Changes

None

### External Dependencies

None

**Comment by glennmatthews** [comment]
Thanks for the report! Can you provide a sanitized example of the sort of data you are trying to import to encounter this issue?

**Comment by jifox** [comment]
@glennmatthews I'll upload it tomorrow

**Comment by jathanism** [comment]
> @glennmatthews Wrong issue, I think I've used an external created racks.csv file instead of the exported one. It contains data that did not escape the `"` char correctly as `""`.
> 
> But I noticed that the field `type` will be exported as `4-post cabinet` but for import the value `4-post-cabinet` is required. Also the `status` field contains the value `Active` but must be imported as `active`.
> 
> exported Racks data:
> 
> ```
> site,group,name,facility_id,tenant,status,role,type,serial,asset_tag,width,u_height,desc_units,outer_width,outer_depth,outer_unit,comments
> DEBE,Racks-DEBE,Rack-1,Schrank-1_1-Stock_DEBE,ACME-DEBE,Active,,4-post cabinet,,,19,42,,,,,"### Schrank-1 1. Stock""
> 
> **Wartung (Office):**
> 
> - Jane Doe
> 
> mail: jane.doe@example.com"
> ```

Ok this is definitely a bug and appears to be related to if not the same issue as #254 in that what is exported doesn't match the format of what is required for import. As far as I'm concerned this is not desirable user experience. Import/export should be identical.

**Comment by jathanism** [comment]
We won't be able to get to this immediately, but it's worth noting that a [similar change was made in NetBox 2.11](https://github.com/netbox-community/netbox/issues/4999). We would happily welcome contributions from anyone willing to port the change over, with proper credit of course.

**Comment by glennmatthews** [comment]
I'm going to close this as a specific instance of the more general problem described by #254.
