### ISSUE TITLE
Model interfaces with shared cabling

### ISSUE THREAD

**Issue by nward** [nautobot/nautobot#385]
### Environment
* Python version: any
* Nautobot version: future

### Proposed Functionality

- Add modelling for multiple interfaces which share a single physical cable - such as QSFP+ going to a breakout cable or panel.
- Add modelling for cables with different numbers of connectors at each end (i.e. MPO one end, 4 x LC pair the other), and a way to create new cables / pinouts to describe different cable types (MPO-MPO A/B/C polarity, MPO-4xLC etc.)

### Use Case

PSM4(PLR4) optics have an MPO/MTP connector, and are recognised by the device a 4 separate physical interfaces (and can be 10/25/100g per interface).

There are 2 ways these are used:
- MPO breakout cable, which has an MPO connector on one end, and 4 x LC pairs on the other.
- MPO breakout panel, usually a cassette which fits in a panel, and has 4 x LC pairs on the front, and 1 x MPO on the back. An MPO cable is connected from the panel to the QSFP+ in the equipment.

Multimode QSFP+ optics can be used with a breakout MPO cable as in the same way.

Currently, we have to model the 4 physical interfaces as SFP+ 10G, and connect cables directly to them - and cannot model the existence of either a breakout cable, or a breakout panel.

Some users achieve this by creating front/back connections in the device with the QSFP+ optic installed - however this is very cumbersome and does not accurately represent reality.

### Database Changes

I'm not sure - proposing this so we can discuss the requirements, then address how to achieve this in the DB.

I think fibre modelling should be changed, to model individual strands rather than pairs - trying to build this feature without this is possible, but means that there needs to be code for all the different options - better do model fibre strands so users can define cables / etc. themselves.

I expect cables would need to be modelled differently to allow different numbers of connectors.

### External Dependencies

I expect no external dependency changes.

**Comment by jathanism** [comment]
Thanks @nward for the request. We'll give this a good review and follow up.
