### ISSUE TITLE
Nautobot 2.0: default view in "Networks" is IP Addresses but should be Prefixes

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#3854]
### Environment
* Nautobot version (Docker tag too if applicable):
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Log into next.demo.nautobot.com
2. Change to the new UI
3. Select Networks

### Expected Behavior

Expected to see my prefixes with the root at the top

### Observed Behavior

I start off by seeing /32 network IP addresses at the top of the page. Appears to be a list view only instead of a tree view.

**Comment by glennmatthews** [comment]
Are you sure you're viewing "Prefixes" and not "IP Addresses"? The `Networks` category link currently takes you to the IP Addresses view as a starting point.

**Comment by jvanderaa** [comment]
Agreed now. I think I found it with navigation on the left expanding IP Management. Can we have that menu expanded by default? 

I looked to the left when looking at it but it did not see "Prefixes" (reducing clicks for what is likely a common thing). Thus the issue addition. Can we look at having Prefixes as the default view on Networks? It's one of those start at the highest level and navigate further down idea.

**Comment by bryanculver** [comment]
Related: #3936

**Comment by bryanculver** [comment]
Short term: Change default context for "Networks" to Prefixes
Long term: Context splash pages/dashboards

Discussing in the design meeting.

**Comment by bryanculver** [comment]
Closed via #3951
