### ISSUE TITLE
Custom Field Query

### ISSUE THREAD

**Issue by Cesarec88** [nautobot/nautobot#3886]
### As ...

Cora - Coder

### I want ...

Could be possible to have the possibility of being able to query  devices, sites etc by using any custom_field? 
that could be a private identifier determined by the user? 

### So that ...

users can be able to retrieve for instance all the 
sites at once they are insterested in by using their private identifiers

### I know this is done when...

I create a new device and I add a custom_field 
and I use graphql plugin to query my device using the custom_field as a searching key
and then I get the wanted device

I create a new site and I add a custom_field 
and I use graphql plugin to query my site using the custom_field as a searching key
and then I get the wanted site

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [X] Circuits
- [X] DCIM
- [X] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [X] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by bryanculver** [comment]
If I understand your FR, this is already supported today: 

https://demo.nautobot.com/dcim/devices/?cf_flavor=vanilla

Where CustomField `Flavor` (slugged to `flavor`) is filterable by `cf_flavor`. 

If it's GraphQL specifically, you might be running into https://github.com/nautobot/nautobot/issues/2127 / https://github.com/nautobot/nautobot/issues/446

**Comment by bryanculver** [comment]
As I understand the FR this is already implemented today. Please re-open with clarification if https://github.com/nautobot/nautobot/issues/3886#issuecomment-1584559517 doesn't address your use case.
