### ISSUE TITLE
Nautobot 2.0: Circuit ID shows ID Instead CID

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#3887]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0
* Python version: ?
* Database platform, version: ?
* Middleware(s): ?

### Steps to Reproduce
1. Log into next.demo.nautobot.com
2. Go to inventory -> Circuits
3. See IDs instead of CIDs

### Expected Behavior

See the CIDs

### Observed Behavior

See the UUIDs

**Comment by glennmatthews** [comment]
CIDs are present in the table too, but agreed that they should be the first column, not the UUID.

![image](https://github.com/nautobot/nautobot/assets/5603551/a1b5888e-fc15-4718-a047-6dfc989cb3ee)

**Comment by lampwins** [comment]
We will revisit this down the road. Closing for now as we will not action it at this time.
