### ISSUE TITLE
Nautobot 2.0 Duplicate Job Logging

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot#3892]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.0b1
* Python version: 3.8
* Database platform, version: PostgreSQL 13
* Middleware(s): SSoT framework

### Steps to Reproduce
1. Setup Nautobot 2.0.0b1 environment with SSoT App framework.
2. Update Jobs to use new log statements on the job_result object and specify a logger.
3. Attempt Job run and watch log entries.

### Expected Behavior
Expect that there are only one log statement for each actual log from the App.

### Observed Behavior
There appear to be duplicate logs, one from the main group and one from log group. If you remove the logger specification it no longer duplicates the lines. It appears that is redundant and no longer necessary?

## TODO

- [x] Fix: Remove the ability to pass in a logger
- [ ] Open a pylint-nautobot rule request to encourage the use of self.logger instead

**Comment by gsnider2195** [comment]
@jdrew82 can you add some code examples of how you're doing the logging?

**Comment by glennmatthews** [comment]
AIUI from Slack, the issue is if you call `job_result.log(message, logger=logging.getLogger(...))` then the JobResult directly creates a JobLogEntry, then the `logger.log()` gets called resulting in a second JobLogEntry with the same message.

**Comment by jdrew82** [comment]
@gsnider2195 What @glennmatthews said. I was able to track ti down to specifying the logger var in the log method like so:

```
self.job_result.log(
    "Loading current data from source adapter...",
    level_choice=LogLevelChoices.LOG_INFO,
    logger=self.logger,
)
```

**Comment by gsnider2195** [comment]
Is this a bug or working as intended? `self.logger` is supposed to log to the database.

**Comment by bryanculver** [comment]
Fix: Remove the ability to pass in a logger that would result in duplicate log entries.

Also open a pylint-nautobot rule request to encourage the use of self.logger instead.

**Comment by gsnider2195** [comment]
Initial work completed by #4166 still working on the pylint rule

**Comment by gsnider2195** [comment]
Putting back in the backlog for the pylint rule. I'm not able to get pylint with pylint_django to infer the `JobResult` node in the `visit_call` method. Without sufficient documentation from either project I'm not able to write a rule that works.

**Comment by gsnider2195** [comment]
Opened pylint nautobot issue https://github.com/nautobot/pylint-nautobot/issues/42
