### ISSUE TITLE
Duplicate provision_field tasks

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot#3912]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.0b1
* Python version: 3.8
* Database platform, version: PostgreSQL
* Middleware(s): SSoT framework and Infoblox App

### Steps to Reproduce
1. Stand up Nautobot environment with 2.0.0b1 version.
2. Install Infoblox App and update for 2.0.0b1. Infoblox App has signals that create a CustomField.
3. Look at JobResults list and see if `nautobot.extras.tasks.provision_field` is seen multiple times.

### Expected Behavior
Expect to see one JobResult instance for provisioning a CustomField.

### Observed Behavior
See 144 duplicate JobResult records for the same exact date & time.

**Comment by jathanism** [comment]
In local testing we were unable to reproduce this issue. It is possible that the `provision_field` tasks were queued up in a local Redis instance and picked up when a worker started. If this pops up again, we'll reopen the issue.
