### ISSUE TITLE
Creating a VirtualChassis with a master device changes the master device's vc_position

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#393]
### Environment
* Python version: 3.6
* Nautobot version: 1.0.0

### Steps to Reproduce
1. Via the REST API or the ORM (`vc_position` is not directly settable via the Device create/edit web UI), create a Device and set its `vc_position` attribute to any value other than `null` or `1`.
2. Via the REST API or the ORM (`master` is not directly settable via the VirtualChassis create web UI), create a new VirtualChassis and assign the aforementioned Device as the `master` of this VC.
3. Inspect the Device and/or VirtualChassis and observe that the master device now shows its position within the VirtualChassis as `1`, regardless of what it was initially set to.

### Expected Behavior

Device `vc_position`, if set to any non-null value, should be preserved when assigning this device as the master of a VirtualChassis.

### Observed Behavior

Device `vc_position` is silently and unconditionally changed to `1`.

This impacts data imports via the `nautobot-netbox-importer` plugin -- in the case where the VC master occupies any non-`1` `vc_position`, and some other device occupies `vc_position 1`, a database integrity error is reported due to two Devices attempting to occupy the same `vc_position` on the same VirtualChassis. https://github.com/nautobot/nautobot-plugin-netbox-importer/pull/43 works around this, but I believe that this should be changed/fixed in Nautobot itself as well.

See also https://github.com/netbox-community/netbox/issues/2087; this appears to be a regression.

**Comment by glennmatthews** [comment]
Code reference: https://github.com/nautobot/nautobot/blob/develop/nautobot/dcim/signals.py#L92

**Comment by smk4664** [comment]
If you don't mind, I would like to take a stab at this on Monday.

**Comment by smk4664** [comment]
Okay, I didn't wait till Monday. It ended up being a fairly straightforward fix.  I hope the test is in a good place.
