### ISSUE TITLE
Inconsistent test behavior in 2.0

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#3930]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.0b1
* Python version: 3.10
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Run `invoke unittest -l nautobot.extras.tests.test_jobs`
2. Run `invoke unittest -l nautobot.extras.tests.test_jobs.JobHookTest`

### Expected Behavior

Both tests behave the same

### Observed Behavior

`JobHookTest` fails when running independently

**Comment by glennmatthews** [comment]
Fixed by #3933 and #3931.
