### ISSUE TITLE
Test output unpredictable when using --cache_test_fixtures

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#3952]
### Proposed Changes

There is some internal state from factory boy and faker that isn't being saved which is causing test cases that use factories to generate data to behave inconsistently when loading test fixture data. We have a few options:

- Stop using factories in individual test cases
- Save the rest of the state when saving the test fixtures file
  - The unique value pool for `UniqueFaker`
  - The sequence iterator for every factory
  - The `factory.random.get_random_state()`

### Justification

Predictable unit test behavior

**Comment by glennmatthews** [comment]
I believe this is generally addressed at this time.
