### ISSUE TITLE
Refine natural keys for various DCIM models

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#3972]
- [x] Fix natural-keys for `ComponentModel` base class to be `[name, device]` due to variadic device-location key.
- [x] Fix natural-key field ordering for PowerOutlet and PowerPanel likewise
- [x] Change Cable natural-key to simply `pk` as this is one of the rare cases where the PK is a user-facing identifier for the model.
- [x] Change natural-keys for CablePath and TaggedItem to `pk` as these are not user-facing models
- [x] Add `[units, rack]` natural-key for RackReservation
- [x] VirtualChassis natural-key should just be `name`

**Comment by bryanculver** [comment]
Closed with #4133
