### ISSUE TITLE
Add config knob to allow Device and Location `name` to be used as sole natural key if desired

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#3977]
For both `Device` and `Location` models, the `name` is not guaranteed globally-unique at the database level (as there are use cases for a `null` Device name, and also for reuse of Location names such as `Floor 2`) but in many deployments these names will in practice be globally unique nonetheless. It would therefore be really useful for natural-key purposes (including CSV import/export) to provide a `settings` (or Constance) config knob(s) to allow these models to use just their `name` as their natural-key definition (instead of `name, parent__name, parent__parent__name, ...` for Location and `name, tenant__name, location__name, location__parent__name, location__parent__parent__name, ...` for Device).

**Comment by bryanculver** [comment]
- Not doing any enforcement
- If a natural key lookup returns multiple results, fail
- If turned on:
    - Lookup would perform on name only
    - Export would emit only the name

**Comment by glennmatthews** [comment]
Implemented by #4194.
