### ISSUE TITLE
Notes associated to a VRF aren't deleted via GUI

### ISSUE THREAD

**Issue by netgitdom** [nautobot/nautobot#3990]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.21
* Python version: 3.8.17
* Database platform, version: postgres 13
* Middleware(s):

We use the "note" model for VRF descriptions that are tool long to fit in the description field. So we add Notes to the VRF via GUI and they are somehow linked to the VRF. If we now delete the VRF via GUI the notes are still existent and aren't deleted.

### Steps to Reproduce
1. add a VRF via GUI and add a note.
2. Navigate to the Note in a separate window to get the URL and/or ID
3. Delete the VRF in the GUI
4. Refresh the URL to see, that the note is still existent.

### Expected Behavior
If I delete a VRF via GUI, all "associated" notes should be deleted as well.

### Observed Behavior
VRF is gone, but the note(s) are still existing.

```
In [28]: VRF.objects.get(name="issue-vrf").notes[0].id
Out[28]: UUID('9847e9e3-0a90-400e-8e6e-30195420ec61')
### VRF is now deleted in GUI
In [29]: Note.objects.get(id="9847e9e3-0a90-400e-8e6e-30195420ec61")
Out[29]: <Note: issue-vrf-2023-06-26t102025848158>
```

Or alternative via "edit URL" of the note:
'http://localhost:8080/extras/notes/issue-vrf-2023-06-26t102025848158/edit/?return_url=/ipam/vrfs/730a809b-1889-475c-bb11-dce706312576/notes/' 

VRF is gone but note is still existent.

**Comment by glennmatthews** [comment]
I suspect this is an issue with all models supporting notes.

**Comment by Thetacz** [comment]
I confirm this happens for Prefixes too.

**Comment by bryanculver** [comment]
Likely a missing cascade-esque delete when deleting an instance.
