### ISSUE TITLE
Show user that created and last updated object in advanced tab

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#3994]
### As ...

Dan - Data Owner

### I want ...

I easily see at a glance the user that created and last updated an object in nautobot

### So that ...

I can quickly audit this important detail without having to go to the changelog

### I know this is done when...

- The user name that created and last updated the object are shown in the advanced tab
- If the user name for the object in either case is not know, simple show an em dash
- The advanced tab should show this data in a new "Data Provenance" section

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by bryanculver** [comment]
The quickest way to address this would be to look up the first and most recent `ObjectChange` record but those may have been cleaned up, especially the first.

Should we add a `created_by`, `changed_by` (and do similar username caching we do for `ObjectChange` in the event of a deleted user) to `ChangeLoggedModel?

What is the "user" if we don't have historical information?

What is the "user" in the direct ORM change case?

**Comment by lampwins** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Product-64a8783b7a3f4b1225973a0c/issues/nautobot/nautobot/3994?planning-poker) with Zenhub @bryanculver @gsnider2195 @HanlinMiao @jathanism

**Comment by bryanculver** [comment]
> The quickest way to address this would be to look up the first and most recent `ObjectChange` record but those may have been cleaned up, especially the first.
> 
> Should we add a `created_by`, `changed_by` (and do similar username caching we do for `ObjectChange` in the event of a deleted user) to `ChangeLoggedModel?
This should "Just Work :tm:" with `ChangeLoggedModel` (app developers shoudln't be required to add migrations)

Either attempt performant indexing of the ObjectChange records or use Redis caching

> What is the "user" if we don't have historical information?

Do not show or em-dash.
 
> What is the "user" in the direct ORM change case?

Outside of scope.

**Comment by gsnider2195** [comment]
Also needs to be presented in the API for new UI to display

**Comment by bryanculver** [comment]
> Also needs to be presented in the API for new UI to display

Does not need to be. We can make a separate API call to get this data.
