### ISSUE TITLE
Create custom fields that are computed based on referencing other data 

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#4]
### Proposed Functionality
Read-only computed custom fields using existing data already stored in the database.  This will allow users to be able to build lightweight Jinja (or Python) templates to populate a read-only custom field value.

### Use Case
As a user, I want to dynamically generate interface descriptions using device, neighboring device, circuit, or circuit ID.  All data already stored in Nautobot, I should be able to use Jinja templating, similar to custom links, to build that string thus simplifying the network configuration templates that are used to generate full configurations.  As a user, I should be able to auto-generate fields that are required by automation systems like Ansible, e.g. ansible_network_os being "{{ vendor }}.{{ os }}.{{ os }}".  

### Database Changes
Will require some sort of database record to define and store these templates. Probably a new model as the existing custom-fields model is not directly applicable.

### External Dependencies
None.

**Comment by jifox** [comment]
Is there also a possibilty to add such functionality to interface templates?

For e.g. a stacked switch has 48 Ports that have a name that depends on chassis nr

Gi1/0/[1-48] for switch 1
Gi2/0/[1-48] for switch 2

so to define 

Gi{% chassis_nr %}/0/[1-48]

**Comment by jedelman8** [comment]
@jifox Where would `chassis_nr` be defined in this example?  Proposing to use a custom field to define the number and then use that in the template?

**Comment by jifox** [comment]
@jedelman8 It should reference the `Position` field of Members to Virtual Chassis

![Virtual_Chassis_add_device](https://user-images.githubusercontent.com/8406301/112180631-03667d80-8bfc-11eb-86f5-eaec684f0dff.PNG)

**Comment by jifox** [comment]
@jedelman8 with a default value of `1`

**Comment by jfach** [comment]
I'll take this one!

**Comment by dgarros** [comment]
I think we should be good to close this one

**Comment by glennmatthews** [comment]
Fixed by #577
