### ISSUE TITLE
Official OpenAPI / swagger bindings

### ISSUE THREAD

**Issue by clienthax** [nautobot/nautobot#40]
### Environment
* Python version: N/A
* Nautobot version: N/A

### Proposed Functionality
Officially maintained bindings (Generated from swagger) for golang / others
There is an existing community maintained version for Netbox here https://github.com/netbox-community/go-netbox
However due to various swagger definition problems in Netbox the generated client generally needed modification in areas.
Issues: 4808, 4804, 4803 among others

Most of the existing issues can be resolved by fixing up the swagger definitions and by adding tests.

### Use Case
Enhanced usability in external applications for automation tooling.

### Database Changes
N/A

### External Dependencies
N/A

**Comment by jathanism** [comment]
Just to clarify, you're effectively asking for an OpenAPI 2.0-compliant `go-nautobot` fork?

**Comment by clienthax** [comment]
> Just to clarify, you're effectively asking for an OpenAPI 2.0-compliant `go-nautobot` fork?

That would be my personal use case here, however maintaining the openapi swagger definitions will allow for usable bindings to be generated for other languages.

**Comment by jathanism** [comment]
Okay, I'm with you. So far we've maintained whatever was already part of NetBox core and extended it slightly for the changes we've made.

Discussions are ongoing right now as to continue to support OpenAPI 2.0 support, or move to OpenAPI 3.0 (w/ [drf-spectacular](https://github.com/tfranzel/drf-spectacular)) for the new API work we'll be doing. As I understand it drf-yasg, which is what is being used to define the v2.0 schema, is end-of-life in this regard.

Longer term, we 100% want to be able to support auto-enumerating clients for other languages, so it sounds like that's what you're looking for. When that time comes it's almost certainly going to be OpenAPI 3.0 but no final decisions have been made.

**Comment by clienthax** [comment]
Aha I wasn't aware that OpenAPI 3 was a thing,
I am not too worried about what form it takes, as long as its maintained and has at least the same functionality as the current one.

Nice to hear its being planned 👍

**Comment by sdktr** [comment]
I'd suggest looking at polishing up the graphql api for the long-term 'mother of all nautabot interfacing'.

With a good gql backend thats the only access for the UI and external clients a lot of duplicate effort in maintaining duplicate code/logic can be avoided. For the clients depending on REST style api a gql2rest mapper could be packaged.

**Comment by dgjustice** [comment]
+1 on @sdktr sdktr's comment.  It is difficult to keep the OpenAPI bindings 100% accurate with the core API, and the core API isn't always well-behaved since it is written in a dynamic language.  [Is it an `int`, a `str`, nullable, all-of-the-above?](https://github.com/netbox-community/go-netbox/issues/116)  It may be a better option long-term to refer users of statically-typed languages to the GraphQL API and let them figure out how to build their own structs based on crafted responses.  [Golang has tooling](http://json2struct.mervine.net/) for this, and I'm sure the same can be done in other languages.  go-netbox is a sprawl of boilerplate with practically no tests and several bugs (nature of the beast, no offense to the project or idea).  I would be reluctant to replicate that for Nautobot.

**Comment by UnityDG** [comment]
> +1 on @sdktr sdktr's comment. It is difficult to keep the OpenAPI bindings 100% accurate with the core API, and the core API isn't always well-behaved since it is written in a dynamic language. [Is it an `int`, a `str`, nullable, all-of-the-above?](https://github.com/netbox-community/go-netbox/issues/116) It may be a better option long-term to refer users of statically-typed languages to the GraphQL API and let them figure out how to build their own structs based on crafted responses. [Golang has tooling](http://json2struct.mervine.net/) for this, and I'm sure the same can be done in other languages. go-netbox is a sprawl of boilerplate with practically no tests and several bugs (nature of the beast, no offense to the project or idea). I would be reluctant to replicate that for Nautobot.

Isn't it a bad thing that the API can return undefined results that don't match the defined API in the first place?
Making the API itself use static types should be seen as a good thing as you know for certain what to expect from it, regardless of the clients language and weather or not it may be statically typed.

Json2struct is not a great solution in general to what could be automatically generated fairly easily with the templates being maintained, and which will likely lead to a more stable API going forward in general.

Personally as a heavy automation user of the current netbox-go integration I would like to see the OpenAPI solution upgraded as per @jathanism's comment.

I do not believe that GraphQL should replace a good rest API.

**Comment by jathanism** [comment]
After several internal discussions, I have submitted a proposal togo all-in on OpenAPI 3.0. See: https://github.com/nautobot/nautobot/issues/595

**Comment by Kircheneer** [comment]
From the experience we had with [go-nautobot](https://github.com/nautobot/go-nautobot/) it looks like we have had success in providing these, anything missing here?

**Comment by clienthax** [comment]
> From the experience we had with [go-nautobot](https://github.com/nautobot/go-nautobot/) it looks like we have had success in providing these, anything missing here?

Is that a private repo?, I can't access it

**Comment by Kircheneer** [comment]
Oh, spoiler alert, sorry! We're working on getting that published, not quite there yet.

**Comment by UnityDG** [comment]
> Oh, spoiler alert, sorry! We're working on getting that published, not quite there yet.

Is there an ETA on getting this published?

**Comment by mristok** [comment]
> > Oh, spoiler alert, sorry! We're working on getting that published, not quite there yet.
> 
> Is there an ETA on getting this published?

Also hoping for an ETA, any updates?

**Comment by Letsu** [comment]
Any updates?

**Comment by Kircheneer** [comment]
@UnityDG @mristok @Letsu apologies for the delayed answer, the [repository](https://github.com/nautobot/go-nautobot/) is now public and in beta!
