### ISSUE TITLE
Markdown custom field type

### ISSUE THREAD

**Issue by MeganerdDev** [nautobot/nautobot#4006]
### As ...

Austin - Network Automation Engineer

### I want ...

to have a custom field with multi-line and markdown support, similar to the CommentField (Textarea/SmallTextarea) widget.

### So that ...

- I can better represent what I want
- I can exceed the present 255-character limit of CharField without having to use JSON

### I know this is done when...

- I can select a custom field type choice of: markdown
- The markdown is rendered when the custom field is applied to an object in Nautobot

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- We can re-use the existing CommentField class used for comments
- A new custom field type would need created

### External Dependencies

None

**Comment by glennmatthews** [comment]
Completed in #4007.
