### ISSUE TITLE
Refine IP Address View in New UI

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#4015]
As a Nautobot 2.0 user, I want the IP address list and detail views to function in the new UI.

List:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFFoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--24871570f2cc595b4e9896ffeb6a8e182ceea278/Screenshot%202023-08-21%20at%201.39.35%20PM.png)

Fix the H1 "Ip Addresses" > "IP Addresses"

Detail:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFVoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--73f29caafd30738e9fda55322e432e3f487a9c01/Screenshot%202023-08-21%20at%201.39.44%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFloIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--11db42c1f3ed57933ad7f73963b7806c5c8d44d7/Screenshot%202023-08-21%20at%201.39.56%20PM.png)

- Move object type to advanced
- Remove the notes URL entirely
- Ignore tags, custom fields, computed fields, relationships, etc (they will be solved generically)

**Comment by lampwins** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Product-64a8783b7a3f4b1225973a0c/issues/nautobot/nautobot/4015?planning-poker) with Zenhub @bryanculver @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1
