### ISSUE TITLE
Refine Locations View in New UI

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#4016]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckloIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--33fc81a4a2b2c43a966c24ffe3804b7fbe2c58ce/Screenshot%202023-08-21%20at%202.01.21%20PM.png)
 Mostly looking at the order with the legacy view.

**Comment by lampwins** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Product-64a8783b7a3f4b1225973a0c/issues/nautobot/nautobot/4016?planning-poker) with Zenhub @bryanculver @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1

**Comment by HanlinMiao** [comment]
Closed by #4365
