### ISSUE TITLE
Refine Device Type View in New UI

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#4017]
As a Nautobot 2.0 user, I want to be able to interact with the Device Type list and detail views in the new UI.

Strive for parity with the legacy UI, for top level, concrete fields:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWdoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c79da50328d51cdae7b5353c1599c48cd36e755e/Screenshot%202023-08-21%20at%201.05.43%20PM.png)

- Show the image fields with just the image file names (we will worry about rendering the images later)
- Move object type to advanced
- Remove the notes URL entirely
- Ignore tags, custom fields, computed fields, relationships, etc (they will be solved generically)

**Comment by glennmatthews** [comment]
Implemented in #4352.
