### ISSUE TITLE
Device & Virtual Machine

### ISSUE THREAD

**Issue by JHarrison712** [nautobot/nautobot#4030]
### As ...

Isabella - Infrastructure Owner

### I want ...

I would like to see a OS / Memory / CPU / Boot Hard Drive and then maybe about to link to a storage array for storage drive. 

### So that ...

This makes Datacenter Engineers & even System Administrator & Technicians to understand what hardware resources are assign to the device or VM so we can understand whats hook into that machine without looking into the hyperv or vmware host.

### I know this is done when...

> Devices
>>Operation System 
>> Memory
>>CPU and how many processors
>> Hard Drive
>> Secondary Drive

Not sure if this is the format I know Netbox did something for this in the cluster / vm. 

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [X] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by glennmatthews** [comment]
Thanks for the request! See also #1178.

**Comment by bryanculver** [comment]
Might be worth taking a look at https://github.com/Thetacz/nautobot-plugin-device-resources

**Comment by bryanculver** [comment]
> > Might be worth taking a look at https://github.com/Thetacz/nautobot-plugin-device-resources
> 
> Looks like its only for Docker :( But this is right up what I was looking for.

He actually published it to PyPi: https://pypi.org/project/nautobot-device-resources/

**Comment by lampwins** [comment]
We are adding software version support in 2.2 which can be used to track the OS. The rest can be tracked as inventory items, or in the case of VMs, directly on the VM. Custom fields are also always possible.
