### ISSUE TITLE
2.0 Migration Guide / Documentation for Custom Fields, Computed Fields and Custom Relationships

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot#4042]
### As ...

Austin - Network Automation Engineer

### I want ...

to have access to a clear migration guide and documentation for how custom fields, computed fields and custom relationships behave in 2.0.

### So that ...

I don't have to extract this information from the code.

### I know this is done when...

- There is a section somewhere in the docs that describes `label` and `key` for the aforementioned models (this may be [this](https://docs.nautobot.com/projects/core/en/v2.0.0-beta.1/user-guides/custom-fields/#grouping) page which currently is not updated)
- This section is linked to from a location in the 2.0 release notes/migration guide (such as [here](https://docs.nautobot.com/projects/core/en/v2.0.0-beta.1/installation/upgrading-from-nautobot-v1/#renamed-database-fields))

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [X] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

None

### External Dependencies

None

**Comment by HanlinMiao** [comment]
Closed by #4137
