### ISSUE TITLE
Installation Metrics

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#4047]
### Proposed Changes

Collect anonymous installation metrics during `post_upgrade` about the installation of Nautobot, opt-out-able

Stats to collect:

- Nautobot version
- Python version
- Installed apps and their version

To protect the privacy of our users, we must one-way hash the installed apps. We would know the input strings for our open-sourced apps but other apps (internal or otherwise) would not be known.

`SHA512("nautobot_golden_config") => 646f9502c613484fc8590361551728d5dd813ddacec5af59457669fcb8063a502f5c8da84f1ae96897dd82773a485927a606ef3f6da24cf22e62624f5dc898a2 `

We would maintain a mapping of SHA hashes and community apps and versions. This would prevent any false negatives from any string matching on the plugin name.

To help minimize duplicate reports for the same installation, a unique deployment ID should be created. This should be inserted as constance config item, permitting administrators to rotate it at their own discretion.

Two settings to be created:

- `INSTALLATION_METRICS_ENABLED` (`boolean`, default `True`) - Control whether these metrics are collected
- `DEPLOYMENT_ID` (`string`, generate new UUID if not set and store) - Unique-ish identifier for an installation

Payload endpoint: `https://nautobot.cloud/api/nautobot/installation-metric/`
Payload example:

```json
{
  "deployment_id": "02678ace-b7af-4d5d-bee2-8a5db2bfbb03",
  "nautobot_version": "1.6.0",
  "python_version": "3.9.6",
  "app_versions": {
    "646f9502c613484fc8590361551728d5dd813ddacec5af59457669fcb8063a502f5c8da84f1ae96897dd82773a485927a606ef3f6da24cf22e62624f5dc898a2": "1.4.1",
    "31361566d60837144a2bf35793f7ffdd8652fda8f4afa0f2b81e583a2b0947ed15cc760e96a4f9ac5c67f1ac9d7e297356887126fccea9880f9d98491345d656": "1.3.0"
  }
}
```

This needs to be called out explicitly in upgrade docs. As well, `nautobot-server init` should have an explicit prompt to ask if the user wants to leave this enabled or not.

### Justification

At present as maintainers, we have only a loose understanding of what version(s) our average users are on. Do we have predominantly early/rapid adopters? Are people holding onto the previous minor release? 

The same issue applies to our plugin/app ecosystem.

In order to ensure our LTM and general support models are in line with our install base, knowing the most popular community apps and upgrade cycles from our users more concretely would be very helpful.

**Comment by bryanculver** [comment]
The current focus is on versions, general install numbers, and support considerations. Therefore this does not need to be performed on the startup of each Nautobot instance (cloud containers) and workers.

It may also be helpful to include which DB platform is being used, especially if we start supporting more (see: #796, #2308, MariaDB)

**Comment by bryanculver** [comment]
> > Therefore this does not need to be performed on the startup of each Nautobot instance (cloud containers) and workers.
> 
> I will also point out that we don't need to spend a bunch of time 100% optimizing this because we are mostly after high level trends over time. Having x number of duplicate reports from a deployment is not a huge concern.

I suspect the trade-off here is:

- `post_upgrade`: _may_ miss an installation or two if someone forgot to run it but significantly fewer duplicates
- service start: never miss an install, much higher amount of duplication, much higher traffic to the collector

**Comment by gsnider2195** [comment]
I think it's important that the `DEPLOYMENT_ID` does not include any potentially confidential information. I would suggest a one-way hash of `echo "$(hostname) $(uname -a)"`

**Comment by gsnider2195** [comment]
Perhaps also send the value of the `DEBUG` variable so that non-prod environments can be filtered out?

**Comment by bryanculver** [comment]
> Do we need to account for installations that can't verify our ssl certificate? This may be encountered in corporate environments that restrict their servers' CA certificates.

For now, no. Fail fast.

**Comment by gsnider2195** [comment]
Thoughts on skipping if `DEBUG = True`?

**Comment by glennmatthews** [comment]
Implemented in #4077. Keeping this open until we're able to validate the end-to-end flow with the cloud receiver.

**Comment by chadell** [comment]
@gsnider2195 , "debug" is not an expected parameter in the API

**Comment by gsnider2195** [comment]
> @gsnider2195 , "debug" is not an expected parameter in the API

Is that an acceptable change to make on the cloud side? We added that key so that dev environments can be filtered out if desired.

**Comment by chadell** [comment]
yes, sure. Going to create a task for it

**Comment by gsnider2195** [comment]
Closing as completed by #4077
