### ISSUE TITLE
Provide Customization for Help Link in UI to Proper Documentation Page

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#4052]
> Not having a consistent static file path for all "models" documentation makes it a lot harder to have a link from the UI to the corresponding documentation, FWIW. (Currently we have this from the `(?)` button when creating/editing a model, but I could see a strong argument in the future for also adding a link from the list and detail views as well.

_Originally posted by @glennmatthews in https://github.com/nautobot/nautobot/pull/4041#discussion_r1250775740_

> Thanks for calling this out. We need to come up with a solution to be able to point the help links to any part of the docs structure. One reason is for this case, where I'd much prefer the UX of the docs not be constrained to a technical detail of the web UI. Second, I want help links for other feature areas that aren't directly models, in the future.

_Originally posted by @lampwins in https://github.com/nautobot/nautobot/pull/4041#discussion_r1253196185_

**Comment by glennmatthews** [comment]
Completed by #4059
