### ISSUE TITLE
Possible incorrect handling of ManyToMany field in serializer.

### ISSUE THREAD

**Issue by mgsimpson-i2** [nautobot/nautobot#4063]
### Environment
* Nautobot version (Docker tag too if applicable): v2.0.0-beta.1
* Python version: 3.9.17
* Database platform, version: Postgres.app running PostgreSQL 15
* Middleware(s): --

### Steps to Reproduce
1. Create a plugin model, MyParent, that includes a M2M field "tenants" back to Tenant:
```
@extras_features("graphql")
class MyParent(PrimaryModel):
    [ ... ]
    tenants = models.ManyToManyField(
        to="tenancy.Tenant",
        related_name="my_parents",
        blank=True,
    )
    [ ... ]
```

2. Define an API serializer, MyParentSerializer, for that model:
```
class MyParentSerializer(NautobotModelSerializer, TaggedModelSerializerMixin):
    class Meta:
        model = MyParent
        fields = (
            [ ... ]
            "tenants",
            [ ... ]
        )
```

3. Create a second plugin model, MyChild, that includes a FK field "my_parent" back to MyParent, and a corresponding serializer MyChildSerializer:
```
@extras_features("graphql")
class MyChild(PrimaryModel):
    [ ... ]
    my_parent = models.ForeignKey(
        to=MyParent,
        on_delete=models.PROTECT,
        related_name="my_children",
    )
    [ ... ]
```
```
class MyChildSerializer(NautobotModelSerializer, TaggedModelSerializerMixin):
    class Meta:
        model = MyChild
        fields = (
            [ ... ]
            "my_parent",
            [ ... ]
        )
```

### Expected Behavior
- Using the REST API, pulling an instance of MyChild, you correctly see the serialization, with the expected URL-format PK for "my_parent" in the output.
- Using the REST API, pulling an instance of MyChild with "depth=1", you should see the same serialization, but with "my_parent" expanded to a full serialization.

### Observed Behavior
- In that second case (with "depth=1"), the full serialization of the MyParent object doesn't show the "tenants" M2M field at all.
- Testing with "depth=2", "depth=3", etc. produces the same result.
- Best guess is that somewhere in the magic expansion being triggered by that "depth" parameter, M2M fields are getting lost.

**Comment by bryanculver** [comment]
I think this is working as expected at the moment but I'd be inclined to a feature request for a query parameter to turn on a more detailed output.

**Comment by mgsimpson-i2** [comment]
Turned this into a feature request per Bryan's note above, closing the issue.
