### ISSUE TITLE
PLUGINS = [] causes a 502 bad gateway 

### ISSUE THREAD

**Issue by VincentKlanderman** [nautobot/nautobot#4067]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.23b1

* Python version: 3.10.6
* Database platform, version: Ubuntu 22.04
* Middleware(s):N/a

### Steps to Reproduce
1. installed nornir, golden config, and device life cycle management.
2. followed steps on documentation.
3. did the expected restart. 
4. went to nautobot gui and was given a 502 bad gateway.

nautobots gui to open as normal.

### Observed Behavior
I commentated out the "PLUGINS = ["nautobot_plugin_nornir", "nautobot_golden_config", "nautobot_device_lifecycle_mgmt"]" in the nautobot_config.py and the page works, but the installed plugins are not there.

**Comment by bryanculver** [comment]
Thanks for the report @VincentKlanderman. Do you have server logs from when you received the 502 error?
