### ISSUE TITLE
Sort by Status on dcim/device-bays

### ISSUE THREAD

**Issue by mattmiller87** [nautobot/nautobot#4075]
### Environment
* Nautobot version (Docker tag too if applicable): v1.5.21
* Python version: Python 3.10.12
* Database platform, version: PostgreSQL 13.8
* Middleware(s): None

When accessing Device Bays and sorting, sorting by status does not work.
### Steps to Reproduce
1. Navigate to Devices > Device bays (`dcim/device-bays/?q=&sort=name`)
2. Select "Status" at the top of the page

### Expected Behavior
Sort the device bays by status

### Observed Behavior
Django Error
![image](https://github.com/nautobot/nautobot/assets/17132988/f393142e-13bf-4995-9bce-2d92c7d3295c)

**Comment by glennmatthews** [comment]
The "status" column is not a field directly on `DeviceBay` it's instead derived from the DeviceBay's `installed_device.status`. A naive fix would be to simply disable sorting on this column, but it's probably fixable more completely by changing the column to use an appropriate `Accessor` to retrieve the nested value.
