### ISSUE TITLE
Able to connect interfaces without specifying device

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot#408]
### Environment
* Python version: Unsure
* Nautobot version: v1.0.0

When configuring a connected device in Nautobot, you are able to select a connected interface in the **Name** dropdown without selecting a device or other filters (rack, site, etc).
Ideally the interface names should not populate until a specific device is selected.  Currently it displays all possible interfaces, even with duplicate names.

### Steps to Reproduce
1.  In Nautobot, select a device
2.  Go to its "Interfaces" tab
3.  On an unconnected interface, select the green "Ethernet" icon.  Select "Interface" in the cursory dropdown menu
4. On the **B Side** menu, verify nothing is selected for "Device".  Then expand the dropdown for "Name".  Select any available listed.
5. Set a Status and click the Connect button.

### Expected Behavior
In the **Name** dropdown for the **B Side** section, interfaces should *not* appear unless a specific device is selected in the **Device** field.

### Observed Behavior
I am able to show all interfaces available to connect to without specifying a device.

**Comment by smk4664** [comment]
This might be a "By Design", the Device dropdown is not required here, and the interface dropdown works the same way that other dropdown menus in Nautobot work.  The related code is:
https://github.com/nautobot/nautobot/blob/develop/nautobot/dcim/forms.py#L3365
and
https://github.com/nautobot/nautobot/blob/develop/nautobot/utilities/forms/fields.py#L357

**Comment by lampwins** [comment]
We can address this in later UI work related to forms and multi-step workflows, but as of now, I don't think this is worth the effort or risk of breaking the already fragile select2 widgets.
