### ISSUE TITLE
Interface type represented differently between GraphQL and REST

### ISSUE THREAD

**Issue by jamesharr** [nautobot/nautobot#4080]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.0-beta.1
* Python version: 3.11.4
* Database platform, version: N/A
* Middleware(s): N/A

### Steps to Reproduce
1. Create an interface (and other supporting instances, such as a device)
2. Query the interface type via GraphQL, note that the type field contains an upper-case value, such as `LAG` or `OTHER`.
3. Attempt to update interface type via REST, using a similar style (upper case) and the REST API fails.

The core issue seems to be a slight difference in the way that GraphQL reports an interface type and the values that the Rest API will accept for an interface type. The GraphQL reports an upper-case value and the Rest API seems to accept the same text, but only in lower-case values.

It's entirely possible that this is not simply a case-mismatch and that it's more subtle, but this is what I have observed so far.

### Expected Behavior
I expect to create/update objects using the Rest API with the same kinds of values I get back from the GraphQL instead of having to translate between sets of values accepted by different APIs.

### Observed Behavior
I have to translate values. IE, if I update an interface type via Rest, I have to use "other" as the type, but when I query it via GraphQL, I get "OTHER".

### References
- [NTC#nautobot Slack thread](https://networktocode.slack.com/archives/C01NWPK6WHL/p1689000174671749)
- [Graphene choices-to-enum conversion docs](https://docs.graphene-python.org/projects/django/en/latest/queries/#choices-to-enum-conversion)

**Comment by lampwins** [comment]
This is an unfortunate constraint in GraphQL and rather than trying to modify representations in the rest API, I would like to focus on mutations if GraphQL.
