### ISSUE TITLE
Improve New UI Rebuild Performance

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#4083]
### Proposed Changes

Either:
- Eject our React app to fix this bug (CRA is dead) so we can improve rebuild time: https://github.com/facebook/create-react-app/pull/12391
- For 2.0.0, stop rebuilding the new UI on every start until we can address the above

This is a time-boxed story: If we can't reasonably do option one in the time permitted, switch to option two as a stop-gap and we can revisit option one in a fast follow-up.

### Justification

The developer side and app start-up are slow because every `post_upgrade` is doing a full rebuild of the UI, even if things are unchanged. In 2.0.0 there won't really be anything to rebuild.

**Comment by gsnider2195** [comment]
[Create](https://dev.to/ag2byte/create-react-app-is-officially-dead-h7o) [React](https://medium.com/@dawid.niegrebecki/create-react-app-is-dead-what-to-use-instead-fcdd46b70295) [App](https://www.linkedin.com/pulse/end-era-react-team-longer-recommends-create-app-vivek-dwivedi) appears to be dead.

**Comment by gsnider2195** [comment]
Potential path forward (next.js with react-router): [Building a single-page application with Next.js and React Router
](https://colinhacks.com/essays/building-a-spa-with-nextjs)

Links to [Replacing Create React App with the Next.js CLI](https://gist.github.com/tannerlinsley/65ac1f0175d79d19762cf06650707830)

**Comment by bryanculver** [comment]
## Today:

We have #4214 but requires more time to review and document which parts are coming in from ejecting and which parts are overridden by us (because of CRACO/other overrides). We will commit time to review the PR (2 story points), ensure it has proper documentation, and move forward with that approach.

## Future Story:

We can eject and own our build tools (build) vs find a replacement for Create React App (buy).

To quote @jathanism:
> We bought something and the company went out of business.

We need to figure out what we're taking on with either approach:

_Build_: We accept an amount of tech debt and knowledge and understanding on how to continue building what we need with the tools and dependencies we have (or evolving them).

_Buy_: Find a replacement of CRA/CRACO that offloads a larger amount of the maintenance of the tools for a client-side app to reduce the overhead.

**Comment by glennmatthews** [comment]
Implemented by #4214.
