### ISSUE TITLE
Implement `structlog` Support

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#4087]

**Comment by lampwins** [comment]
Maybe we will do this in the future, but it needs to be better defined.

**Comment by glennmatthews** [comment]
Reopening this as a starting point for further discussion.

**Comment by glennmatthews** [comment]
https://django-structlog.readthedocs.io/en/latest/index.html

**Comment by glennmatthews** [comment]
Added as opt-in by #5687. Can revisit later (3.0?) whether we want to enable it by default.
