### ISSUE TITLE
Missing libxmlsec1-openssl package in Docker image

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#4093]
### Environment
* Nautobot version (Docker tag too if applicable): [1.5.19-py3.10](https://hub.docker.com/layers/networktocode/nautobot/1.5.19-py3.10/images/sha256-3c2e65afe7d0c0a70ef13e90dbb9032333bd8130685006b46d53ca85cd2d432a?context=explore)
* Python version: 3.10.11
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. enable SAML SSO
2. startup Nautobot from Docker image

Note: all Python packages for SSO are installed, this one is missing from system and should be installed too
Workaround: `apt-get install libxmlsec1-openssl` in the running container

### Expected Behavior
Nautobot started

### Observed Behavior
![image](https://github.com/nautobot/nautobot/assets/26114847/31685a6a-acdd-43db-96a8-ca9e367c5f95)

**Comment by glennmatthews** [comment]
Is this a new issue in the 1.5.19 image (i.e. a regression) or has this never worked as intended?

**Comment by glennmatthews** [comment]
Thanks for the offer! We haven't changed how we install system packages in the Docker build in quite some time so I suspect it's a long-standing issue - possibly as far back as v1.3 and #1620.

**Comment by Thetacz** [comment]
> Thanks for the offer! We haven't changed how we install system packages in the Docker build in quite some time so I suspect it's a long-standing issue - possibly as far back as v1.3 and #1620.
> 
> (edit) I won't ask you to try and go _that_ far back though! :-)

Hi,
Sorry it took me so long, I did not have the time to get to it :/
I tried following previous versions, all showed the package is missing and installing the package to the container fixed the error.
- 1.5.2
- 1.4.7
- 1.3.0
I tried even 1.2.0, but could not get it running due to changes to webserver.

**Comment by glennmatthews** [comment]
Thank you for going above and beyond! We'll get this fixed.

**Comment by bryanculver** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Engineering-64a875e74842500d9e80e23e/issues/nautobot/nautobot/4093?planning-poker) with Zenhub @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1
