### ISSUE TITLE
Interface(s), Interface Parent(s) Columns IP Address List View

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#4100]
Previously the Interface and Interface Parent column on IPAddressTable(s) were single links because of the FK of `assigned_object`. With the changes in #2403, this now can't be a single entity.

Context: https://github.com/nautobot/nautobot/pull/3399/files#diff-021d8b804e061261cd8b357ff540dd4730b04eef1ca56f0247ca38adcf6c0cd1R399

Move these to counts with links to their resulting filter but that will expand to four columns instead of the two today. Consider a tab view on IP Address detail view to combine these item types (Interface and VMInterface) instead of a link to each of their list views.

This is focused on the legacy view for this story.

**Comment by gsnider2195** [comment]
Unable to filter the interface list view until #4099 is implemented. For now, will implement the counts only.

**Comment by gsnider2195** [comment]
Completed by #4230
