### ISSUE TITLE
`IPAddressToInterface`: `primary_for_device` was Removed, Left in Data Migration

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#4104]
`primary_for_device` was removed from the through table but was mistakenly left in the data migration and should be fixed (see: https://github.com/nautobot/nautobot/pull/3399/files#diff-5b80e8c4aec86a1835c0513142525508a775003912987e6285c4a31646d42c21R39)

**Comment by glennmatthews** [comment]
Implemented by #4192
