### ISSUE TITLE
Update dockerfile to use official debian repos for node.js

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#4110]
### Proposed Changes

Debian bookworm supports node.js v18 and our base python container image is now based off of bookworm. We should be able to get rid of the extra step in our dockerfile to add the `nodesource` repos [here](https://github.com/nautobot/nautobot/blob/46e2210009d5602eef436cfe90e74f4462e72058/docker/Dockerfile#L116).

### Justification

Dependency cleanup

**Comment by glennmatthews** [comment]
Should we do anything to pin to a specific stable node.js version instead?

**Comment by glennmatthews** [comment]
At the moment, a bare `apt-get update && apt-get install nodejs npm` in `python:3.8-slim-bookworm` will get us node 18.13.0, while using `nodesource` gets us node 18.16.1, which looks to include a number of security updates compared to 18.13.

**Comment by gsnider2195** [comment]
We'll need to update our installation method soon. We're getting this in the docker container build now:


```
#10 5.883 ================================================================================
#10 5.883 
#10 5.883                            SCRIPT DEPRECATION WARNING                    
#10 5.883 
#10 5.883   
#10 5.883   This script, located at https://deb.nodesource.com/setup_X, used to
#10 5.883   install Node.js is deprecated now and will eventually be made inactive.
#10 5.883 
#10 5.883   Please visit the NodeSource distributions Github and follow the
#10 5.883   instructions to migrate your repo.
#10 5.883   https://github.com/nodesource/distributions
#10 5.883 
#10 5.883   The NodeSource Node.js Linux distributions GitHub repository contains
#10 5.883   information about which versions of Node.js and which Linux distributions
#10 5.883   are supported and how to install it.
#10 5.883   https://github.com/nodesource/distributions
#10 5.883 
#10 5.883 
#10 5.883                           SCRIPT DEPRECATION WARNING
#10 5.883 
#10 5.883 ================================================================================
```
