### ISSUE TITLE
Allow opt-in only setting for config contexts when searching / downloading devices

### ISSUE THREAD

**Issue by cmacnevin** [nautobot/nautobot#4111]
### As ...

Patti - Platform Admin

### I want ...

to be able to safeguard the performance of automation pipelines

### So that ...

users don't complain of slow read operations when querying large numbers of devices

### I know this is done when...

A configuration setting is available so we can enable 'FORCE-CONTEXT-OPT-IN', and default read operations no longer search contexts or include them in object downloads. Only those setting the opt-in flag will receive the info or include it in search operations

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [X] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

Unsure

**Comment by glennmatthews** [comment]
In 2.0 we've already changed the REST API so that device/VM config-contexts are opt-in rather than opt-out. :-) #3586.

I'll have to check to see what's involved in search - I hadn't been aware that searches were including config-context data by default.

**Comment by glennmatthews** [comment]
@cmacnevin As far as I can tell device search through the REST API (`/api/dcim/devices/?q=somestring`) does *not* search inside config-context data for the devices. Can you confirm what you're seeing in this regard and whether we can say that #3586 fully resolves this request for you or whether there's additional work to be done?

**Comment by bryanculver** [comment]
@cmacnevin Please feel free to re-open this issue if you feel #3586 doesn't address your need or if you are finding searches to be searching config-context data which should not be the case in 1.X or 2.0
