### ISSUE TITLE
Device Family Model

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot#4117]
### As ...

Austin - Network Automation Engineer

### I want ...

the ability to filter a set of devices based on their product family 

### So that ...

I can simplify my queries and more easily scale my api calls when adding new PIDs (DeviceType)

### I know this is done when...

- GET `/api/dcim/devices?device_family=c9300` # returns all devices with a device_type__family = `c9300`
- GET `/api/dcim/devices?device_type=c9300x-24y-a` # these devices would be in the above output

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [X] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [X] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- New DeviceTypeFamily model

**Comment by jdrew82** [comment]
Wouldn't this make more sense as an additional attribute on the DeviceType model?

**Comment by whitej6** [comment]
I'd say the how doesn't matter. In my mind it is either a new model with dev type having a Fk to family or it's an optional charfield on dev type. Would just need to be queryable from the device object.

**Comment by lampwins** [comment]
Implemented as HardwareFamily
