### ISSUE TITLE
Certificate-based API authentication

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot#4120]
### As ...

Patti - Platform Admin

### I want ...

Nautobot to offer certificate-based authentication for the API.

### So that ...

I can use certificates to authenticate to the REST API for Nautobot.

### I know this is done when...

- I can disable token-based authentication for the REST API
- I can enable certificated-based authentication for the REST API

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

Unsure

### External Dependencies

Unsure, but probably there would be something here.

**Comment by Kircheneer** [comment]
After internal discussion this may just be a matter of combining a [remote auth backend](https://docs.nautobot.com/projects/core/en/stable/configuration/authentication/remote/#installation) with that doing this task and documenting this in Nautobot.

**Comment by lampwins** [comment]
There is nothing stopping someone from implementing a custom remote auth backend and including it in configuration. This is such an advanced and specific topic, I don't see a need to explicitly document it.
