### ISSUE TITLE
Add `network_driver` field to Platform model

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#4136]
### As ...

Tammy - Tools Integrator

### I want ...

To have a consistent way that various apps and libraries (Ansible, Golden Config, etc.) can determine which ~Netmiko~ library-specific driver to use when communicating with a given class of devices.

### So that ...

Each individual integration does not need to reinvent the wheel, e.g. by adding a custom field or a config-context attribute, in order to solve this common problem.

### I know this is done when...

The Platform model allows me to define a ~`netmiko_driver`~ `network_driver` attribute, similar to the existing `napalm_driver` attribute, that apps and libraries can consume. See [comment below](https://github.com/nautobot/nautobot/issues/4136#issuecomment-1643015154) for more specifics.

### Optional - Feature groups this request pertains to.

- Automation
- DCIM

### Database Changes

Yes, new database field.

### External Dependencies

None directly - adding this field does *not* entail making Netmiko into a required dependency of Nautobot.

**Comment by itdependsnetworks** [comment]
I think it makes sense to have:

- “network_driver” or “netutils_driver” attribute should be added
- This should match, https://github.com/networktocode/netutils/blob/6a5eaa4c388cc9d124c85821368e1c59e072b85b/netutils/lib_mapper.py#L306-L315
- Then a property for each of ansible, napalm, netmiko, ntc_templates, pyats, scrapli, and hier_config.
- Netutils would do this automatically
- Allow the ability to update the mappings to be updated by config

In this design, it is important to consider:
- How the REST API will return list view for the methods
- How the REST API will return detail view for the methods
- How the GraphQL will return these methods
