### ISSUE TITLE
"No job log entries found" code in custom job via API call (randomly)

### ISSUE THREAD

**Issue by pibjndata** [nautobot/nautobot#4145]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.3
* Python version: Python 3.8.16
* Database platform, version:  PostgreSQL
* Middleware(s):

### Steps to Reproduce
1. I have developed a custom nautobot-job
2. from Nautobot GUI it always works correctly
3. we have issue with API calls, the error appears randomly. I have found only one rule that when they are some changes done on the production server (like any other job or plugin modification) and when nautobot-server is resarted, then the issue appear (and only from API, from GUI it always works). 
Error that we can see is :
<img width="941" alt="image" src="https://github.com/nautobot/nautobot/assets/90384031/e410205d-7729-404f-9a6f-d12abce58676">

it goes into Pending state and takes infinity till I kill the job manually 
I have verified payload that we provide , and it is always correct . when i do a restart of nautobot server (with command sudo systemctl restart nautobot nautobot-worker nautobot-scheduler ) and send the API call with the same payload - then it will work.
Also the issue appears in other different random situations not exactly related to changes a code on nautobot-server. It just stops working and presents always the same message (as on screenshot) and the Pending state.

API calls should always run the job correctly 

I will not be able to use my job on production, as we never know when it will work and when do not

**Comment by glennmatthews** [comment]
A stuck status of `Pending` usually means that the job was never picked up by a worker for execution. Can you check the logs of the nautobot-worker service for any relevant error messages?

**Comment by pibjndata** [comment]
thanks for answer,
could you please let me know where can i check those logs ? or which commend shall i use

**Comment by glennmatthews** [comment]
Depends on the specifics of your deployment but `journalctl -eu nautobot-worker.service` might be a starting point.

**Comment by pibjndata** [comment]
Could you please have a look, this is example of "pending" job, from the command from you:

ul 22 22:17:15 <server name>: [2023-07-22 22:17:15,330: CRITICAL/MainProcess] Can't decode message body: DecodeError(InterfaceError('connection already closed')) [type:'application/x-nautobot-json' encoding:'utf-8' headers:{'lang': 'py', 'task': 'nautobot.extras.jobs.run_job', 'id': '60d47f5d-cf0d-4629-9e9e-36c936a25e87', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, 10.0], 'root_id': '60d47f5d-cf0d-4629-9e9e-36c936a25e87', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': "{'data': {'server_name': 'TEST_SERVER', 'change_number': '12345', 'username': 'username'}, 'request': <nautobot.utilities.utils.NautobotFakeRequest object at 0x7fb6afe5e070>, 'commit': False, 'job_result_pk': UUID('028effc8-7af7-4d9c-9fc7-7aa2938dfd64')}", 'origin': 'gen167790@s>
Jul 22 22:17:15 <server name>: body: b'[[], {"data": {"server_name": "TEST_SERVER", "change_number": "12345", "username": "username"}, "request": {"__nautobot_type__": "nautobot.utilities.utils.NautobotFakeRequest", "META": {"CONTENT_LENGTH": "141", "CONTENT_TYPE": "application/json", "HTTP_ACCEPT": "*/*", "HTTP_ACCEPT_ENCODING": "gzip, deflate", "HTTP_HOST": "nautobot.sif.jndata.net", "HTTP_USER_AGENT": "python-requests/2.28.1", "QUERY_STRING": "", "REMOTE_ADDR": "10.99.216.25", "REQUEST_METHOD": "POST", "SERVER_NAME": "_", "SERVER_PORT": "443"}, "POST": {}, "GET": {}, "user": "c7e035b0-64cc-4d26-a8b5-07360082bd99", "path": "/api/extras/jobs/local/job_URL/run/", "id": null}, "commit": false, "job_result_pk": "028effc8-7af7-4d9c-9fc7-7aa2938dfd64"}, {"callbacks": null, "errbacks": null, >
Jul 22 22:17:15 <server name>: Traceback (most recent call last):
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 237, in _cursor
Jul 22 22:17:15 <server name>:     return self._prepare_cursor(self.create_cursor(name))
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
Jul 22 22:17:15 <server name>:     return func(*args, **kwargs)
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/django/db/backends/postgresql/base.py", line 236, in create_cursor
Jul 22 22:17:15 <server name>:     cursor = self.connection.cursor()
Jul 22 22:17:15 <server name>: psycopg2.InterfaceError: connection already closed
Jul 22 22:17:15 <server name>: The above exception was the direct cause of the following exception:
Jul 22 22:17:15 <server name>: Traceback (most recent call last):
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/kombu/serialization.py", line 39, in _reraise_errors
Jul 22 22:17:15 <server name>:     yield
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/kombu/serialization.py", line 252, in loads
Jul 22 22:17:15 <server name>:     return decode(data)
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/nautobot/core/celery/__init__.py", line 102, in _loads
Jul 22 22:17:15 <server name>:     return json.loads(obj, object_hook=nautobot_kombu_json_loads_hook)
Jul 22 22:17:15 <server name>:   File "/usr/lib64/python3.8/json/__init__.py", line 370, in loads
Jul 22 22:17:15 <server name>:     return cls(**kw).decode(s)
Jul 22 22:17:15 <server name>:   File "/usr/lib64/python3.8/json/decoder.py", line 337, in decode
Jul 22 22:17:15 <server name>:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Jul 22 22:17:15 <server name>:   File "/usr/lib64/python3.8/json/decoder.py", line 353, in raw_decode
Jul 22 22:17:15 <server name>:     obj, end = self.scan_once(s, idx)
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/nautobot/core/celery/__init__.py", line 88, in nautobot_kombu_json_loads_hook
Jul 22 22:17:15 <server name>:     return cls.nautobot_deserialize(data)
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/nautobot/utilities/utils.py", line 444, in nautobot_deserialize
Jul 22 22:17:15 <server name>:     obj.user = User.objects.get(pk=obj.user)
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
Jul 22 22:17:15 <server name>:     return getattr(self.get_queryset(), name)(*args, **kwargs)
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/cacheops/query.py", line 351, in get
Jul 22 22:17:15 <server name>:     return qs._no_monkey.get(qs, *args, **kwargs)
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/django/db/models/query.py", line 431, in get
Jul 22 22:17:15 <server name>:     num = len(clone)
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
Jul 22 22:17:15 <server name>:     self._fetch_all()
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/cacheops/query.py", line 281, in _fetch_all
Jul 22 22:17:15 <server name>:     self._result_cache = list(self._iterable_class(self))
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
Jul 22 22:17:15 <server name>:     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
Jul 22 22:17:15 <server name>:     cursor = self.connection.cursor()
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
Jul 22 22:17:15 <server name>:     return func(*args, **kwargs)
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
Jul 22 22:17:15 <server name>:     return self._cursor()
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 237, in _cursor
Jul 22 22:17:15 <server name>:     return self._prepare_cursor(self.create_cursor(name))
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
Jul 22 22:17:15 <server name>:     raise dj_exc_value.with_traceback(traceback) from exc_value
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 237, in _cursor
Jul 22 22:17:15 <server name>:     return self._prepare_cursor(self.create_cursor(name))
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
Jul 22 22:17:15 <server name>:     return func(*args, **kwargs)
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/django/db/backends/postgresql/base.py", line 236, in create_cursor
Jul 22 22:17:15 <server name>:     cursor = self.connection.cursor()
Jul 22 22:17:15 <server name>: django.db.utils.InterfaceError: connection already closed
Jul 22 22:17:15 <server name>: During handling of the above exception, another exception occurred:
Jul 22 22:17:15 <server name>: Traceback (most recent call last):
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/celery/worker/consumer/consumer.py", line 596, in on_task_received
Jul 22 22:17:15 <server name>:     strategy(
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/celery/worker/strategy.py", line 135, in task_message_handler
Jul 22 22:17:15 <server name>:     if body is None and 'args' not in message.payload:
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/kombu/message.py", line 209, in payload
Jul 22 22:17:15 <server name>:     return self._decoded_cache if self._decoded_cache else self.decode()
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/kombu/message.py", line 194, in decode
Jul 22 22:17:15 <server name>:     self._decoded_cache = self._decode()
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/kombu/message.py", line 198, in _decode
Jul 22 22:17:15 <server name>:     return loads(self.body, self.content_type,
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/kombu/serialization.py", line 252, in loads
Jul 22 22:17:15 <server name>:     return decode(data)
Jul 22 22:17:15 <server name>:   File "/usr/lib64/python3.8/contextlib.py", line 131, in __exit__
Jul 22 22:17:15 <server name>:     self.gen.throw(type, value, traceback)
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/kombu/serialization.py", line 43, in _reraise_errors
Jul 22 22:17:15 <server name>:     reraise(wrapper, wrapper(exc), sys.exc_info()[2])
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/kombu/exceptions.py", line 21, in reraise
Jul 22 22:17:15 <server name>:     raise value.with_traceback(tb)
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/kombu/serialization.py", line 39, in _reraise_errors
Jul 22 22:17:15 <server name>:     yield
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/kombu/serialization.py", line 252, in loads
Jul 22 22:17:15 <server name>:     return decode(data)
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/nautobot/core/celery/__init__.py", line 102, in _loads
Jul 22 22:17:15 <server name>:     return json.loads(obj, object_hook=nautobot_kombu_json_loads_hook)
Jul 22 22:17:15 <server name>:   File "/usr/lib64/python3.8/json/__init__.py", line 370, in loads
Jul 22 22:17:15 <server name>:     return cls(**kw).decode(s)
Jul 22 22:17:15 <server name>:   File "/usr/lib64/python3.8/json/decoder.py", line 337, in decode
Jul 22 22:17:15 <server name>:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Jul 22 22:17:15 <server name>:   File "/usr/lib64/python3.8/json/decoder.py", line 353, in raw_decode
Jul 22 22:17:15 <server name>:     obj, end = self.scan_once(s, idx)
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/nautobot/core/celery/__init__.py", line 88, in nautobot_kombu_json_loads_hook
Jul 22 22:17:15 <server name>:     return cls.nautobot_deserialize(data)
Jul 22 22:17:15 <server name>:   File "/opt/nautobot/lib64/python3.8/site-packages/nautobot/utilities/utils.py", line 444, in nautobot_deserialize
Jul 22 22:17:15 <server name>:     obj.user = User.objects.get(pk=obj.user)

\

**Comment by bryanculver** [comment]
It looks like you're running into the DB connection/forking problem

> psycopg2.InterfaceError: connection already closed

There have been several handlings of this, one of the most recent being v1.5.8 (https://github.com/nautobot/nautobot/pull/3105)

You're on a quite old version of Nautobot. Can you see if upgrading helps?

**Comment by pibjndata** [comment]
those changes from your link are already added to the newest version of nautobot?

i will report this feedback to our team and see when we can do upgrade

**Comment by bryanculver** [comment]
Closing this as stale. @pibjndata Please feel free to re-open if you are able to reproduce this in 1.6
