### ISSUE TITLE
Unable to re-name Racks

### ISSUE THREAD

**Issue by tanleach** [nautobot/nautobot#4149]
### Environment
* Nautobot version (Docker tag too if applicable): v1.5.23
* Python version: 3.10
* Database platform, version: Postgres
* Middleware(s):

### Steps to Reproduce
1. Go to dcim/racks/
2. select any rack to edit
3. change the name of the rack

### Expected Behavior
Page would reload and name would be reflected. 

### Observed Behavior
When submitting an error shows up below the `name` field:
```
Device with `name` in ['2.5 960GB SSD (PCIE Gen3) Samsung', '40GBE Active Fiber Cable - Aqua - 03M', '40GBE Active Fiber Cable - Aqua - 05M', ... '2.5 960GB SSD  Intel'] and site=A52Plus already exists.
```

From [Slack Conversation with Glenn M.](https://networktocode.slack.com/archives/C01NWPK6WHL/p1689953425513139?thread_ts=1689951178.929749&cid=C01NWPK6WHL) it is suspected that #4025 may have introduced this.

**Comment by glennmatthews** [comment]
I think I've been able to reproduce this symptom by first cloning a device from the Rack in question into another Site (same device name, different site). Would still be good to confirm whether there are other scenarios that introduce this issue.
