### ISSUE TITLE
Last page in Pagination not updating when page size changes

### ISSUE THREAD

**Issue by DistantVoyager** [nautobot/nautobot#4154]
### Environment
* Nautobot version: 2.0.0 next https://github.com/nautobot/nautobot/commit/612f05347dc211dfef5555c9a6186087a09adb73
* Python version: 3.10

### Steps to Reproduce
1. Switch to the new UI in v2.0
2. View an object list such as Devices
3. Change the number of rows per page
4. The last page on "You are on page # out of {last_page}" does not change anymore

### Expected Behavior
The last page gets updated dynamically if the page size changes and increases/decreases the number of pages.

### Observed Behavior
The last page stays the same as it was and does not change to the new number. This seems to have gotten broken from the initial PR. 

![image](https://github.com/nautobot/nautobot/assets/111259311/3d339787-96fa-4496-817e-64d274082ce4)

![image](https://github.com/nautobot/nautobot/assets/111259311/556341f5-80a7-482b-8fb7-2e8db428f67d)

**Comment by lampwins** [comment]
Looks great! How hard would it be to add an arrow that takes you to the last page?

**Comment by lampwins** [comment]
@DistantVoyager works for me.

**Comment by lampwins** [comment]
Great, love it!

**Comment by HanlinMiao** [comment]
Closed by #4155
