### ISSUE TITLE
Add `docker-compose config` to `tasks.py`

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#4158]
### Proposed Changes

```diff
diff --git a/tasks.py b/tasks.py
index 9dc59ee2d..60b0b100f 100644
--- a/tasks.py
+++ b/tasks.py
@@ -533,6 +533,12 @@ def build_and_check_docs(context):
     build_example_plugin_docs(context)
 
 
+@task()
+def docker_config(context):
+    """Run docker-compose config."""
+    docker_compose(context, "config", pty=True)
+
+
 def build_nautobot_docs(context):
     "Build Nautobot docs."
     command = "mkdocs build --no-directory-urls --strict"
```

### Justification

This command shows your full merged docker compose config that's generated by all of the yaml files. This config comes in handy when updating one of the files or troubleshooting an issue.

**Comment by snaselj** [comment]
There is similar task already prepared in the PR here: https://github.com/nautobot/nautobot/pull/4112/files#diff-2e746c9eacad6e2c2fdefdc6a665b5ce4607ea384ebf97a729044b79acc778d6R1264-R1272

Can be customized with `--output` argument, to be able to pass the response to stdout.

**Comment by gsnider2195** [comment]
> There is similar task already prepared in the PR here: https://github.com/nautobot/nautobot/pull/4112/files#diff-2e746c9eacad6e2c2fdefdc6a665b5ce4607ea384ebf97a729044b79acc778d6R1264-R1272
> 
> Can be customized with `--output` argument, to be able to pass the response to stdout.

Nice! I see lots of good stuff in that PR. I'll mark this issue as being closed by your PR and I'll try to give it a review/merge as soon as possible.
