### ISSUE TITLE
Custom Field - inconsistent behaviour for defaults

### ISSUE THREAD

**Issue by mzbroch** [nautobot/nautobot#4175]
### Environment
* Nautobot version (Docker tag too if applicable): latest
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1.
2.
3.

### Expected Behavior

Nautobot raises Validation Error for a Null/None **required** custom field if created through ORM.
It should be coder responsibility to define value for required custom field.

### Observed Behavior

Due to #4123, Nautobot will now add a default custom field to the object created through ORM.

One of the common behaviours is to create custom field as follows:
- set `required` to True
- set `default` to empty

This way, the user has to specify the custom field explicitly through UI. As a result of that, database is populated with Non-Null value.

In the current behaviour implemented via #4123 , Nautobot-ORM will ingest a Null value.

FYI See the onboarding unit tests of how we have implemented this before #4123 https://github.com/nautobot/nautobot-plugin-device-onboarding/blob/develop/nautobot_device_onboarding/tests/test_nautobot_keeper.py

**Comment by glennmatthews** [comment]
I'm at a bit of a loss to explain this one, as if I'm reading https://github.com/nautobot/nautobot/blob/develop/nautobot/extras/models/customfields.py#L233-L240 correctly this specific scenario *should* already be accounted for?
