### ISSUE TITLE
Incorrectly named computed fields break GraphQL

### ISSUE THREAD

**Issue by ebusto** [nautobot/nautobot#4176]
### Environment
* Nautobot version: networktocode/nautobot:1.5.24-py3.10
* Python version: Python 3.10
* Database platform, version: PostgreSQL
* Middleware(s): N/A

### Steps to Reproduce
1. Create a computed field that starts with a number.
2. Browse to the GraphQL route (https://nautobot.foo.com/graphql)
3. Observe the error.

### Expected Behavior
To see the GraphiQL app.

### Observed Behavior
An exception: `Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "123_field" does not.`

**Comment by lampwins** [comment]
GraphQL has historically not allowed tokens the schema to begin with numbers, so how would you prefer this be solved? I could see perhaps adding the `cf_` prefix (or similar) in cases where the field starts with a number. We do that today with the interface types in GraphQL.

**Comment by ebusto** [comment]
Adding a prefix seems reasonable. Another option is to require that computed field names start with a letter, although migrating existing compute fields that don't adhere to that would be ugly.

**Comment by bryanculver** [comment]
This was fixed in 2.0 by forcing them to be GraphQL compatible: https://github.com/nautobot/nautobot/blob/next/nautobot/extras/models/customfields.py#L114-L117

**Comment by lampwins** [comment]
We are calling this fixed in 2.0
