### ISSUE TITLE
File exists error when running tests in parallel (pants/pytest-xdist)

### ISSUE THREAD

**Issue by erjac77** [nautobot/nautobot#4179]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.19
* Python version: 3.9.16
* Database platform, version: PostgreSQL 13
* Middleware(s):

I know `pytest` is not supported for Nautobot, but with the help of @jathanism a year ago (he shared a pattern with `pytest-django` to us), we figured out how to make it works. However, when we recently wanted to enable parallelism to speed up CI runs, things started to get ugly. We get (almost every run) a `File exists` error for one of the storage directories. This is caused to a race condition between `xdist` nodes trying to create the directories at the same time. If we disable parallelism, our tests complete successfully. Take note that we use `pants` with `xdist_enable` to parallelize our tests in our monorepo containing custom Nautobot/Nornir plugins.

### Steps to Reproduce
1. Run `pants test ::`

### Expected Behavior
The errors are handled gracefully (with a `try...except` or the parameter `exist_ok=True`?).

### Observed Behavior

A `FileExistsError` is thrown. The following is one example, but it happens virtually for all the storage directories (`settings.GIT_ROOT`, `settings.JOBS_ROOT`, `settings.MEDIA_ROOT`, `settings.STATIC_ROOT`, etc.), but not always in the same run.

```shell
21:06:33.06 [ERROR] Completed: Run Pytest - tests/python/nautobot_tests/nautobot_animal_sounds_tests/test_api.py:../tests - failed (exit code 1).
Traceback (most recent call last):
  File "/root/.cache/pants/named_caches/pex_root/venvs/s/ba4a4c2a/venv/lib/python3.9/site-packages/nautobot/core/runner/runner.py", line 116, in settings_callback
    initializer(
  File "/root/.cache/pants/named_caches/pex_root/venvs/s/ba4a4c2a/venv/lib/python3.9/site-packages/nautobot/core/cli.py", line 120, in _configure_settings
    os.makedirs(os.path.join(settings.MEDIA_ROOT, "devicetype-images"))
  File "/usr/local/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/root/.nautobot/media/devicetype-images'
```

**Comment by bryanculver** [comment]
FWIW we've run into the same issues #4112 #4190

**Comment by bryanculver** [comment]
Because we don't list support for this at the time and will take some work to get working, going to mark this as a feature request

**Comment by erjac77** [comment]
@bryanculver Thx for the quick reply. Do you think it would be possible to do a quick fix just for the storage directories? Something like the following:

```python
https://github.com/nautobot/nautobot/blob/develop/nautobot/core/cli.py

#
# Storage directories
#
os.makedirs(settings.GIT_ROOT, exist_ok=True)
os.makedirs(settings.JOBS_ROOT, exist_ok=True)
Path(os.path.join(settings.JOBS_ROOT, "__init__.py")).touch(exist_ok=True)
os.makedirs(settings.MEDIA_ROOT, exist_ok=True)
os.makedirs(os.path.join(settings.MEDIA_ROOT, "devicetype-images"), exist_ok=True)
os.makedirs(os.path.join(settings.MEDIA_ROOT, "image-attachments"), exist_ok=True)
os.makedirs(settings.STATIC_ROOT, exist_ok=True)
```

I haven't tested it, but I'm willing to do so, and open a PR. Let me know.
