### ISSUE TITLE
App Development Environment Breaks Due To Image Tags in V2 alpha/beta

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot#4182]
### Environment
* Nautobot version (Docker tag too if applicable): ghcr.io/nautobot/nautobot-dev:2.0.0-beta.2-py3.10
* Python version: 3.10
* Database platform, version: NA
* Middleware(s): NA

### Steps to Reproduce
1. Update app code to work with v2
2. update tasks.py context to map to support version
3. invoke build migrate start

### Expected Behavior
1. Image builds
2. migrations apply
3. services start

### Observed Behavior
1. MOST app dev environments default to py3.8 & there is not a 3.8 dev image for v2
2. Image only builds if targeting 3.10
3. Image tag is `ghcr.io/nautobot/nautobot-dev:2.0.0-beta.2-py3.10` and following current patterns it should be `ghcr.io/nautobot/nautobot-dev:2.0.0b2-py3.10` to be fully compatible with poetry & current dev env standards.

**Comment by bryanculver** [comment]
Very likely bugs in our pre-release labeling and overall CI failures with long-running builds. Not intended long-term.

**Comment by bryanculver** [comment]
This has been resolved with several recent PRs. RC1 and RC2 had full publishes.
