### ISSUE TITLE
2.0.0b2: namespaces legacy list view reports "Missing views for action(s) import"

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#4197]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.0b2

### Steps to Reproduce
1. Navigate to legacy UI view for `/ipam/namespaces/`

### Expected Behavior

No UI errors

### Observed Behavior

![image](https://github.com/nautobot/nautobot/assets/5603551/5fa7a82c-d846-4f4e-8716-b5f48f44d78e)

We probably should just go ahead and implement bulk-import for namespaces as the fix for this issue, it shouldn't be particularly complex.

**Comment by bryanculver** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Engineering-64a875e74842500d9e80e23e/issues/nautobot/nautobot/4197?planning-poker) with Zenhub @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1
