### ISSUE TITLE
Golden Configuration Plugin referenced from docs but missing from github

### ISSUE THREAD

**Issue by falz** [nautobot/nautobot#42]
### Change Type
[ ] Addition
[X ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ X] Installation instructions
[ ] Configuration parameters
[ X] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes

On the readthedocs page, there's a reference to Golden Configuration plugin:

* https://nautobot.readthedocs.io/en/latest/#key-use-cases

.. which links to a missing project on github:

* https://github.com/nautobot/nautobot-plugin-golden-configuration

Should this exist? Is it locked down? Is this plug-in commercial?

**Comment by itdependsnetworks** [comment]
Apologies, this is on me. Looking to address this tonight. You can pip install it, but the instructions are not there yet to reasonably install it.

**Comment by itdependsnetworks** [comment]
@falz wrong link, plus not public. I have now made it public, and you can reach it at https://github.com/nautobot/nautobot-plugin-golden-config

I have also put in a PR to resolve the issues.
