### ISSUE TITLE
toml dependency removed in 1.6.0rc1 causing test failures in apps

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot#4205]
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.0rc1
* Python version: <3.11
* Database platform, version: NA
* Middleware(s): NA

### Steps to Reproduce
1. deploy nautobot on v1.6.0rc1 with golden config (many other are affected just simple example)
2.
3.

### Expected Behavior
Tests pass

### Observed Behavior
ImportError for unable to find `toml`

**Comment by bryanculver** [comment]
Closed via #4204
