### ISSUE TITLE
git: Reference at 'refs/heads/master' does not exist

### ISSUE THREAD

**Issue by ggiesen** [nautobot/nautobot#421]
### Environment
* Python version: 3.6.8
* Nautobot version: 1.0.1

### Steps to Reproduce
1. Create git repo in GitLab
2. Assign user with maintainer status
3. Create personal access token
4. Add git repository to Nautobot with the following values:
- Name: nautobot
- Slug: nautobot
- Remote URL: https://host.example.com/nautobot.git
- Branch: master
- Token: `<token>`
- Username: oath2
- Provides: ["config contexts", "export templates", "jobs"]

### Expected Behavior
Clone and sync the repository locally

### Observed Behavior
Creating/refreshing local copy of Git repository "nautobot"...
Reference at 'refs/heads/master' does not exist
Error while refreshing nautobot: Reference at 'refs/heads/master' does not exist
Repository synchronization completed in 0 minutes, 0.06 seconds

Manually doing a git pull in Nautobot's local git repository (`/opt/nautobot/git/nautobot/` in my case) solves the problem, and allows sync going forward

**Comment by FragmentedPacket** [comment]
It seems like whatever repo you're attempting to clone down doesn't have a `master` branch. If it's Nautobot repo, it would be `main`.

When you're in the local directory and run a `git branch`, what branches does it show?

**Comment by jedelman8** [comment]
@ggiesen can you confirm you tried what @FragmentedPacket proposed and if this is still an issue?

**Comment by ggiesen** [comment]
Still an issue:

$ git branch
* master

The workaround is easy (doing one git pull before initial sync), but yeah, this should be fixed at some point

**Comment by smk4664** [comment]
@ggiesen Was your repo empty at the time you attempted?

**Comment by ggiesen** [comment]
It may have been empty, though I thought it had at least a README.md.
