### ISSUE TITLE
Metrics should include the number or workers reachable per queue

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#4210]
### As ...

Patti - Platform Admin

### I want ...

to be alerted when the number of available workers drops below a threshold

### So that ...

I can take corrective action

### I know this is done when...

I can query a Nautobot endpoint (likely `/metrics`) to determine the number of available workers.  I can then use this information to create alerts in my telemetry stack

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

NA

### External Dependencies

NA

**Comment by nniehoff** [comment]
Please note capacity metrics used to provide a `nautobot_queue_number_workers` metric however this is only applicable to RQ workers and I feel like "capacity" metrics shouldn't really be operational metrics like this

**Comment by nniehoff** [comment]
This is related to https://github.com/nautobot/nautobot/issues/1545 and in general we need a better Celery worker healthcheck for docker so this process can be handled automatically

**Comment by Kircheneer** [comment]
https://github.com/nautobot/nautobot/pull/4128 currently includes this. I might just reduce the scope of that PR to just this and put a docs recommendation to use flower alongside.

**Comment by lampwins** [comment]
Because this is covered in #4128, we will close this out.
