### ISSUE TITLE
Slow page rendering with thousands of Tags present on objects

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#4216]
## Environment
* Nautobot version (Docker tag too if applicable): 1.6.0rc1, 2.0.0b2
* Python version:
* Database platform, version:
* Middleware(s): django-debug-toolbar (optional)

### Steps to Reproduce
1. Configure 2000+ Tags that apply to a particular model (or all models)
2. Create instances of that model such that each tag is used one or more times
3. Navigate to the list view for that model

nbshell example:

```python
>>> for i in range(1, 2001):
...     t = Tag.objects.create(name=f"Tag {i}", slug=f"tag-{i}")
...     t.content_types.add(ContentType.objects.get_for_model(Prefix))
... 
>>> for i in range(1, 2001):
...     p = Prefix.objects.create(prefix=f"2001:{i}::/64")
...     p.tags.add(Tag.objects.get(name=f"Tag {i}"))
... 
>>>
```

### Expected Behavior

Page to load relatively quickly regardless of the number of tags.

### Observed Behavior

Page loads substantially slower due to the large number of tags.

Investigation suggests that this is due to server-side rendering of the list of all possible tags as part of `TagFilterField`. When django-debug-toolbar is enabled, it can be seen that thousands of copies of the `selectwithdisabled_option.html` template have been included in the page; DJDT's memory consumption can grow into the gigabytes as a result due to it caching the complete template rendering context for each such copy.

List view of Prefix with page size of 50 and no Tags applied:

![Screenshot 2023-08-04 at 10 40 27 AM](https://github.com/nautobot/nautobot/assets/5603551/21bb51f5-4a22-40e9-b69e-653e76bfb6ba)
![Screenshot 2023-08-04 at 10 40 32 AM](https://github.com/nautobot/nautobot/assets/5603551/144dec68-707f-4895-a0d3-7a7084d844d2)

Same list view with 2000 Tags in use:

![Screenshot 2023-08-04 at 10 38 16 AM](https://github.com/nautobot/nautobot/assets/5603551/d2fce90f-0831-47a7-a483-2c578f96b55e)
![Screenshot 2023-08-04 at 10 38 20 AM](https://github.com/nautobot/nautobot/assets/5603551/6ac7c6bc-60e9-4e3d-bd84-9acaf3ee7f9e)

Initial investigation suggests that changing `TagFilterField` to use `DynamicModelMultipleChoiceField` like most other filter fields, instead of statically rendering it at page load time, mitigates the issue.

**Comment by glennmatthews** [comment]
As a mitigation for django-debug-toolbar, adding `DEBUG_TOOLBAR_CONFIG = {... "SHOW_TEMPLATE_CONTEXT": False, ...}` greatly reduces DJDT's memory consumption when rendering this page, making it possible to at least continue to use the toolbar for its other functionality.

**Comment by lampwins** [comment]
Remove the tag object count, and make the filter queryset be all tags for the given content type.
