### ISSUE TITLE
Dynamic Groups: incorrect tags logic

### ISSUE THREAD

**Issue by ebusto** [nautobot/nautobot#4237]
### Environment
* Nautobot version: 1.6.0
* Python version: 3.11
* Database platform, version: PostgreSQL 11
* Middleware(s): N/A

### Steps to Reproduce
1. Create a dynamic group that includes multiple tags.

### Expected Behavior
The query logic to match the text representation, where tag assignment is OR'ed together.

### Observed Behavior
The query logic matches that of other filters (UI, API), where tag assignment is AND'ed together.

**Comment by gsnider2195** [comment]
To make this configurable would be a separate feature. We'll fix the display bug in dynamic group detail view for `Filter Query Logic`

![image](https://github.com/nautobot/nautobot/assets/75227981/030282af-7019-4826-aa07-ed48beb48901)
