### ISSUE TITLE
Set NAUTOBOT_INSTALLATION_METRICS_ENABLED=false in the dockerfile dev stage

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#4242]
### Proposed Changes

This should propagate to all of the app dev instances since they base off of nautobot dev images. Make sure to unset this in the final stage

### Justification

We don't want to send metrics for dev environments

**Comment by bryanculver** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Engineering-64a875e74842500d9e80e23e/issues/nautobot/nautobot/4242?planning-poker) with Zenhub @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1

**Comment by glennmatthews** [comment]
Is this applicable to `dev` or to `final-dev`?

**Comment by bryanculver** [comment]
@glennmatthews Probably both. App maintainers are firing off installation metrics during development.

**Comment by glennmatthews** [comment]
apps generally use `final_dev` rather than `dev` which is why I asked. :-) I guess we decided not to have `DEBUG = True` disable install metrics?

**Comment by bryanculver** [comment]
> apps generally use `final-dev` rather than `dev` which is why I asked. :-) I guess we decided not to have `DEBUG = True` disable install metrics?

No, because DEBUG !== development. Would be setting the environment variable to disable for `dev` and `final-dev` be sufficient?
