### ISSUE TITLE
RTD No Longer Has Copy Code Button

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#4258]
### Environment
* Nautobot version (Docker tag too if applicable): RTD

### Steps to Reproduce
1. Go to RTD page
2. Look for copy code button
3. Missing

### Expected Behavior

Expected to see copy code button

### Observed 
Missing button.

**Comment by jvanderaa** [comment]
https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button

**Comment by jvanderaa** [comment]
There should be a copy code button here.

![Screenshot from 2023-08-14 14-52-24](https://github.com/nautobot/nautobot/assets/22228848/9292c3bf-7b95-4af1-961e-bd4f093c2da5)

**Comment by gsnider2195** [comment]
We upgraded to [`mkdocs-material` `9.0.0`](https://github.com/squidfunk/mkdocs-material/releases/tag/9.0.0) which made this change:

> Added support for removing copy-to-clipboard button

The default is now disabled so we need to add this to our `mkdocs.yml` to re-enable the feature:

```yml
theme:
  features:
    - content.code.copy
```
