### ISSUE TITLE
Add API endpoint for VRFPrefixAssignment model

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#4270]
### As ...

Austin - Network Automation Engineer

### I want ...

To add an API endpoint for the VRFPrefixAssignment model

### So that ...

I can create, update and delete vrf to prefix relationships through the API

### I know this is done when...

There is an /api/ipam/vrf-prefix-assignment (or similar) api endpoint that can be used for `GET`, `PUT`, `POST`, `PATCH` requests. Similar to the work done for IPAddressToInterface in https://github.com/nautobot/nautobot/issues/4249

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [X] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by HanlinMiao** [comment]
Closed by https://github.com/nautobot/nautobot/pull/5291
