### ISSUE TITLE
Status text change to a link when opening object and became unreadable

### ISSUE THREAD

**Issue by martin-networker** [nautobot/nautobot#4280]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.0b2
* Python version:3.10.9
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
Thia affects Nautobot 2.0.0b2 it does not happen in 1.5.19.
1. In GUI open list of prefixes (IPAM > Prefixes) or IP addresses (IPAM > IP Addresses).
2. Statuses are displayed as white text in colorful frame
3. Open any prefix/IP and the Stats text became a link which makes it very hard to read when the frame color is darker (red

list view:
![image](https://github.com/nautobot/nautobot/assets/84594831/5799984e-69a9-441a-866c-b3fe4de0f3b3)

object view:
![image](https://github.com/nautobot/nautobot/assets/84594831/82de48bc-37a9-4378-bb11-1df618424757)

When opening a specific object, the status should be still a white text.

When opening a specific object, the status became a link (blue color) and become unreadable.

**Comment by jathanism** [comment]
Hi @martin-networker thanks for the report!

I have confirmed that this is not just unique to `IPAddress` or `Prefix` objects, but any object that has a `status` field. In list view, the style is correct, in detail view it is now.

It is merely a side effect of the fact that in list (table) view, the status field does not link to the status object, whereas in detail view it does. 

A simple fix to the CSS for status fields that are linked should do the trick to address this. Specifically in templates this is a result of the `hyperlinked_object` template filter defined in `nautobot/core/templatetags/helpers.py`. See:

https://github.com/nautobot/nautobot/blob/next/nautobot/core/templatetags/helpers.py#L703-L708
