### ISSUE TITLE
Tokens are not writable except for superusers

### ISSUE THREAD

**Issue by bsmeding** [nautobot/nautobot#429]
### Environment
* Python version: 3.7.3
* Nautobot version: nautobot-device-onboarding==1.0.1
* nautobot-golden-config: develop
* nautobot-plugin-nornir: 0.9.0

### Steps to Reproduce
1. Create a normal active user 
2. Add token to user with 'write enabled' checked
3. Set group permission to all permissions (all items and add, delete, change etc)
3. Try to update via the API (I use the nautobot ansible collection)
4. Not possible to update, message:

Device Updated

```
"msg": "{\"detail\":\"You do not have permission to perform this action.\"}"}
```

**Comment by itdependsnetworks** [comment]
I suspect this needs to be addressed in golden config, but may be a gitpython issue. You can see the code here where it pushes https://github.com/nautobot/nautobot-plugin-golden-config/blob/develop/nautobot_golden_config/utilities/git.py#L59-L62

**Comment by bsmeding** [comment]
are you sure? I just want to update devices, interfaces and inventory from within an Ansible playbook. Used it with Netbox without problems and without those plugins

**Comment by itdependsnetworks** [comment]
My mistake, I thought you were talking about a git token. you can safely disregard my statement :)

**Comment by jathanism** [comment]
@bsmeding Can you please provide details on the group permission? Did you create a new group and assign permissions? Can you please provide the exact permission set you added to the group? Thank you!

**Comment by dgarros** [comment]
FYI, I tested quickly on https://demo.nautobot.com/ and I was able to modify an existing object with the `demo` user (not super admin)
Specifically I was able to do a PATCH on a site to change the description

```
curl --location --request PATCH 'https://demo.nautobot.com/api/dcim/sites/a325e477-62fe-47f0-8b67-acf411b1868f/' \
--header 'Authorization: Token aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' \
--header 'Content-Type: application/json' \
--data-raw '{
    "description": "Updated from the API with demo user"
}'
```

**Comment by bsmeding** [comment]
Hi @jathanism, almost all the permissions are set:
<img width="1916" alt="Schermafbeelding 2021-05-13 om 18 47 17" src="https://user-images.githubusercontent.com/15137675/118158113-a7f68600-b41b-11eb-970f-7684000cbaf9.png">

Will try the API directly, but can do this only next week

**Comment by bsmeding** [comment]
I tried the same CURL, without success, 

ansible01 user, standard user with almost all permissions in group setting described above
```
root@ansible01:/data/ansible/cmdb# curl -k --location --request PATCH 'https://10.1.2.3/api/dcim/sites/7907ed8b-82e3-4979-8832-81f335b69f9f/' \
> --header 'Authorization: Token aaaaaaaaaaaaaaaaaaaaaaaaa' \
> --header 'Content-Type: application/json' \
> --data-raw '{
>     "description": "Updated from the API with ansible01 user"
> }'
{"detail":"You do not have permission to perform this action."}root@ansible01:/data/ansible/cmdb#
root@ansible01:/data/ansible/cmdb#
```


same CURL now with admin token
```
root@ansible01:/data/ansible/cmdb# curl -k --location --request PATCH 'https://10.1.2.3/api/dcim/sites/7907ed8b-82e3-4979-8832-81f335b69f9f/' \
> --header 'Authorization: Token bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb' \
> --header 'Content-Type: application/json' \
> --data-raw '{
>     "description": "Updated from the API with admin user"
> }'
{"id":"7907ed8b-82e3-4979-8832-81f335b69f9f","url":"https://10.1.2.3/api/dcim/sites/7907ed8b-82e3-4979-8832-81f335b69f9f/","name":"poc_schiedam","slug":"poc_schiedam","status":{"value":"active","label":"Active"},"region":null,"tenant":null,"facility":"","asn":null,"time_zone":null,"description":"Updated from the API with admin user","physical_address":"","shipping_address":"","latitude":null,"longitude":null,"contact_name":"","contact_phone":"","contact_email":"","comments":"","tags":[],"custom_fields":{},"created":"2021-05-10","last_updated":"2021-05-17T10:40:58.496993+02:00","circuit_count":0,"device_count":8,"prefix_count":0,"rack_count":0,"virtualmachine_count":0,"vlan_count":0,"display":"poc_site"}root@ansible01:/data/ansible/cmdb#
root@ansible01:/data/ansible/cmdb#
```

**Comment by dgarros** [comment]
@bsmeding are you sure your user is inheriting the `Network Developers` permissions ? in your screenshot it looks like `Network Developers` is not associated with any users or any groups

**Comment by bsmeding** [comment]
Yes the user is in the correct/only group created
<img width="1085" alt="Schermafbeelding 2021-05-17 om 13 53 57" src="https://user-images.githubusercontent.com/15137675/118484290-5a2d9680-b717-11eb-99ee-8c6207951f04.png">

**Comment by dgarros** [comment]
@bsmeding it looks like you have both a `Group` and an `Object Permission` named `Network Developers` but they are not associated with each other.  

This screenshot clearly shows that the Object Permisson Network developers is not associated with any user or group 
![image](https://user-images.githubusercontent.com/304126/118491645-335a6a80-b6ed-11eb-9474-20356db34187.png)

Please can you try to add the group `Network Developers` to the Object Permission `Network Developers`, you can do that in the object permission edit view

**Comment by bsmeding** [comment]
@dgarros Yes that was missing thanks!, my bad overlooked the assignment. working from curl and ansible now
