### ISSUE TITLE
Nautobot 2.0.0rc1 Docs: References NPM Where It Should Be Node

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#4294]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.0rc1
* Python version: N/A
* Database platform, version: N/A
* Middleware(s):

### Steps to Reproduce
1. Review the docs around installing Node
2. Install docs indicate to install NPM, which should be Node
3.

### Expected Behavior

Expected to request install of Node

### Observed Behavior

Requests to install NPM

**Comment by gsnider2195** [comment]
Are you referencing the ubuntu install guide [here](https://docs.nautobot.com/projects/core/en/next/user-guide/administration/installation/ubuntu/?h=npm#install-nodejs)?

**Comment by gsnider2195** [comment]
`nodejs` is required for installation of the `npm` package on ubuntu lunar. What version are you using? https://packages.ubuntu.com/lunar/npm

**Comment by jvanderaa** [comment]
When I installed for Ubuntu 22.04 just installing NPM I didn't get Node. I also had to remove something as well, so I may need to get that documented.

**Comment by gsnider2195** [comment]
It looks like `apt install npm` doesn't work on 22.04. You have to do `apt install nodejs` which installs npm as well.

**Comment by gsnider2195** [comment]
Anyway, sorry for the trouble. I thought I tested on 22.04!

**Comment by jvanderaa** [comment]
No worries here, I'm the one that read later than `22.10` as `22.04` earlier. So this may work out, and it moves the node install to the very beginning to do all system stuff at the same spot.

**Comment by jathanism** [comment]
Sounds like there is some confusion here. Node is not required for production deployments, only NPM. Node is required for development only, and even then, only for dynamic rendering.

We should at least revise the documentation to be explicit about the required Node.js version, which is 18 LTS. We have had issues with "later" versions of Node, so until we can certify them, let's keep it crisp.

**Comment by jdrew82** [comment]
I wanted to mention also that the upgrade docs [here](https://docs.nautobot.com/projects/core/en/stable/user-guide/administration/upgrading/from-v1/upgrading-from-nautobot-v1/) also makes no mention of needing NodeJS/npm installed for the upgrade.
