### ISSUE TITLE
Add better-exceptions for the development

### ISSUE THREAD

**Issue by snaselj** [nautobot/nautobot#4296]
### Proposed Changes

Add `better-exceptions` for the development.

This can be added to `development/nautobot_config.py`:

```python
try:
    import better_exceptions
    better_exceptions.hook()
except ImportError:
    pass
```

### Justification

`better-exceptions` helps with the debugging process. It shows the stack trace in a more readable way, and it also shows the values of the variables in the stack trace.

[Project GitHub pages](https://github.com/qix-/better-exceptions)

**Comment by lampwins** [comment]
Not interested in making this a system dependancy. As you note, this can easily be implemented in a developer's environment if they so choose.
