### ISSUE TITLE
Commands for adding dependencies to local_requirements.txt are incorrect

### ISSUE THREAD

**Issue by chipn** [nautobot/nautobot#43]
### Change Type
[ ] Addition
[ x] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[x ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes
In sections "Configuring Napalm" and "Remote File Storage", the docs recommend using the following commands:

```
sudo echo napalm >> /opt/nautobot/local_requirements.txt
sudo echo django-storages >> /opt/nautobot/local_requirements.txt
```

These commands do not work as sudo does not apply to the redirect. Using these commands will result in permission denied:

```
vagrant@ubuntu:/opt/nautobot$ sudo echo napalm >> /opt/nautobot/local_requirements.txt
-bash: /opt/nautobot/local_requirements.txt: Permission denied
```

Potential fix:
```
sudo sh -c "echo 'napalm' >> /opt/nautobot/local_requirements.txt"
sudo sh -c "echo 'django-storages' >> /opt/nautobot/local_requirements.txt"
```

**Comment by jathanism** [comment]
Ah yes. Another option would be `echo 'napalm' | sudo tee -a /opt/nautobot/local_requirements.txt`. Thanks for this.
