### ISSUE TITLE
Add Missing Information to Nautobot App Migration Doc.

### ISSUE THREAD

**Issue by HanlinMiao** [nautobot/nautobot#4301]
### Proposed Changes
There are some of the changes we forgot to document in the https://github.com/nautobot/nautobot/blob/next/nautobot/docs/development/apps/migration/from-v1.md.
Some of the missing info so far:

- [x] `CustomField.name`renamed to `CustomField.key` (same for Relationships and ComputedField).
- [x] Add an explicit reference to https://docs.nautobot.com/projects/core/en/next/user-guide/administration/upgrading/from-v1/upgrading-from-nautobot-v1/#database-field-behavior-changes and etc.
- [x] Remove `RoleModelSerializerMixin` reference since we revamped the serializer to use field = "__all__".
- [x] API serializers for any model that is a potential target of a generic foreign key from a core model (including `ObjectChange.changed_object` for any `ChangeLoggedModel`) *must* inherit from `BaseModelSerializer` at a minimum so that they have a properly generated `object_type` field. Otherwise schema generation may report:
    ```(drf_spectacular.E001) Schema generation threw exception "Field name `object_type` is not valid for model `OnboardingTask`."```
- [ ] Recommendation to remove `tag = TagFilter(...)` from FilterSet definitions, as `NautobotFilterSet` can provide a more-correctly-named `tags` filter if `tags` is added to `fields` in Meta.

### Justification
App migration documentation before 2.0.0 release should be as complete as possible.

**Comment by bryanculver** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Product-64a8783b7a3f4b1225973a0c/issues/nautobot/nautobot/4301?planning-poker) with Zenhub @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1
