### ISSUE TITLE
Documentation On Identifying Slug-less Models in Nautobot 2.0

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#4303]
### As ...

Austin - Network Automation Engineer

### I want ...

Concise documentation on how to identify a unique instance of an object in Nautobot 2.0, now that slugs no longer exist (#2312).

### So that ...

I know if I should be slugging the name, using the composite key, default to PKs, etc and what the pros and cons are of each approach, if there are more than one.

### I know this is done when...

- A document named "Uniquely Identifying a Nautobot Object" exists in the developer guide
- A comparison/trade-off chart exists for each approach

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [X] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

NA

### External Dependencies

NA

**Comment by bryanculver** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Engineering-64a875e74842500d9e80e23e/issues/nautobot/nautobot/4303?planning-poker) with Zenhub @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1

**Comment by gsnider2195** [comment]
Resolved by #4372
