### ISSUE TITLE
NoteDetailView is not accessible due to missing template.

### ISSUE THREAD

**Issue by HanlinMiao** [nautobot/nautobot#4309]
### Environment
* Nautobot version (Docker tag too if applicable): v1.6.0 and v2.0.0-rc
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Go to demo.nautobot.com
2. Try accessing extras/notes/[slug]/ in v1.6.0 or extras/notes/[uuid]/ in v2.0.0

### Expected Behavior
NoteDetailView renders correctly.

### Observed Behavior
![Screen Shot 2023-08-23 at 1 36 29 PM](https://github.com/nautobot/nautobot/assets/46973263/efd9686d-f9aa-45df-b5a4-0dbcc253d219)

We probably need to add a template to render a single Note instance since the NoteDetailView URL does exist.

**Comment by bryanculver** [comment]
@lampwins @smk4664 Does it make sense for an individual Note to have a detail view or should it be redirected to the list view of the associated object?

**Comment by gsnider2195** [comment]
This is also an issue when creating a new note. The notice presented to the ui links to this non-existent route:

![image](https://github.com/nautobot/nautobot/assets/75227981/a5c84103-aec5-4ea7-b67d-046e952c8965)

![image](https://github.com/nautobot/nautobot/assets/75227981/48663cd1-2771-40ca-9d24-e6c74f9e5fea)

**Comment by smk4664** [comment]
> This is also an issue when creating a new note. The notice presented to the ui links to this non-existent route:
> 
> ![image](https://user-images.githubusercontent.com/75227981/279699185-a5c84103-aec5-4ea7-b67d-046e952c8965.png)
> 
> ![image](https://user-images.githubusercontent.com/75227981/279699335-48663cd1-2771-40ca-9d24-e6c74f9e5fea.png)

#4555 Addresses this as well, but I don't know if this is going to be the accepted solution.

**Comment by gsnider2195** [comment]
Fixed by #4555
