### ISSUE TITLE
Update `Integration` CI Workflow

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#4310]
### Proposed Changes

Make the following changes `ci_integration.yml`

- Remove ARM from Docker builds
- Change the unit test matrix to test:
    - Max supported Python version on Postgres DB
    - Min supported Python version on MySQL DB
    - (the above are inverse of PRs for sufficient coverage)
- Remove linter checks (keep check-schema checks for peace of mind for now)
- Run Integration Test in parallel with Unit Tests
- Run Migration Tests in parallel with Unit Tests
- Add Action keyword to allow manually re-running this workflow on-demand

### Justification

- ARM builds are slow
- ARM builds of pre-pre-release (`latest`, `develop`, etc) builds aren't intended for local (ARM-heavy) or production (lower-cost) use
- We rarely find intermediate-supported Python failures
    - Either you used too new of a language feature and that would be caught by min test, or
    - You used a potentially deprecated/removed language feature and that would be caught by the max test
- Lint checks in PRs check the same code, redundant
    - We have "keep PRs up to date" enforcement
- Integration tests test different things than unit tests and with fail-fast can be grouped together, no point in waiting 30min for unittest only to find out you'll fail integration and need to re-run again
- Migration tests test different things and are always good to have, but same as integration: you'll have to fix it and might as well cancel unittests if they're going to fail
- Being able to manually re-run integration tests

**Comment by bryanculver** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Engineering-64a875e74842500d9e80e23e/issues/nautobot/nautobot/4310?planning-poker) with Zenhub @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1

**Comment by gsnider2195** [comment]
Completed by #4354
