### ISSUE TITLE
Update `Pull Request` CI Workflow

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#4311]
### Proposed Changes

- Run all linters (including pylint) and `check-schema` and `check-migrations` in parallel
    - Pylint can be excluded from the "depends on" for unit tests
- Change the unit test matrix to test:
    - Max supported Python version on MySQL DB
    - Min supported Python version on Postgres DB
    - (the above are inverse of Integration for sufficient coverage, these are aimed at speed: fastest Python with slowest DB and vise versa)
- Run integration tests in parallel with unit tests
- Run migration tests in parallel with unit tests
- Add a container build in parallel with unit tests
    - Max supported Python version
    - x86 only
    - Don't publish

### Justification

- All linters are reasonably performant and schema/migration checks will cause unittest to fail anyway
- We rarely find intermediate-supported Python failures
    - Either you used too new of a language feature and that would be caught by min test, or
    - You used a potentially deprecated/removed language feature and that would be caught by the max test
- Integration tests test different things than unit tests and with fail-fast can be grouped together, no point in waiting 30min for unittest only to find out you'll fail integration and need to re-run again
- Migration tests test different things and are always good to have, but same as integration: you'll have to fix it and might as well cancel unittests if they're going to fail
- Only way we can check container builds currently is by merging them into an integration branch

**Comment by gsnider2195** [comment]
> Run migration tests in parallel with unit tests

Migration tests aren't currently run in `CI - Pull Request`. Did we decide to add this test?

**Comment by gsnider2195** [comment]
Never mind. That's only in `next`.

**Comment by bryanculver** [comment]
Closed with #4340
