### ISSUE TITLE
2.0 Pre-Migrate Helper: Management Command to Set `Platform.network_driver` From `platform.slug`

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot#4316]
### As ...

P.D. - Plugin Developer

### I want ...

to programmatically migrate my plugin from a dependency on `Platform.slug` to `Platform.network_driver` 

### So that ...

On upgrade of nautobot & my plugin  AND there is NOT a requirement for my users to manually go in and update every Platform instance to set the network_driver field.

### I know this is done when...

- Platforms do NOT have to be manually updated post upgrade
- Changes to platform_mapping settings are NOT required
- Accounts for the NON-STANDARD use of slug values (cisco_ios as slug)
- All jobs/integrations should be able to run without ANY object changes post upgrade

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [X] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [X] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [X] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- No migration/model changes
- Possibly a management command or system job available for 1.6 database state (must be done after database is migrated to 1.6 state and not before running any migrations for 2.0)
- Should not be available IF database is at 2.0 state

**Comment by itdependsnetworks** [comment]
Yea, this would be helpful

**Comment by lampwins** [comment]
Would the expectation be that if a platform slug value can be mapped to a known network_driver, this done, but if not, it's a no-op? Or thing else?

**Comment by whitej6** [comment]
The backend code yes, but as a user I should not have to make changes to the each platform object manually post upgrade for all of the plugin integrations to work.

The concern is not the work on the plugin developer to change the code the big concern is requiring a user to upgrade then go into each platform and set the `network_driver` field AND if it is done after 2.0 migrations are complete you have no idea what it may need to be set to.

For example

1.5
```
Platform.objects.create(name="Cisco IOS", slug="cisco_ios")
```

1.6
```
platform.network_driver ## This is added via `Migration.AddField` and would initially be populated as ""
platform.slug ## This would be the same as 1.5
```

2.0
```
platform.network_driver ## Same as 1.6 state
platform.slug ## No longer exists and cant be referenced to populate the network_driver attr
```

**Comment by bryanculver** [comment]
@whitej6 @lampwins @itdependsnetworks

Is it OK if this is implemented as a management command in 1.6.X?

**Comment by lampwins** [comment]
Yeah the 1.6 part didn't click with me. A management command seems like a reasonable compromise given the complexity of migrations in this scenario with 1.6/2.0.

**Comment by whitej6** [comment]
I would vote for introducing in 1.6, I am not terribly opinionated on when it is removed and it very well may never be in 2.0. 

I think it's reasonable to say & document the following steps (and not include the management command at all in 2.0)

1. upgrade to >=1.6.x <2.0
2. run management command
3. upgrade to 2.x

**Comment by bryanculver** [comment]
> I would vote for introducing in 1.6, I am not terribly opinionated on when it is removed and it very well may never be in 2.0.

This already exists for many of our pre-migrate helpers (#3747): they are removed in 2.0

> I think it's reasonable to say & document the following steps (and not include the management command at all in 2.0)
> 
>     1. upgrade to >=1.6.x <2.0

Our recommendation will be to update to 1.6 before migrating to 2.0 so you have the full toolset of our pre-migrate helpers before performing the upgrade.

**Comment by bryanculver** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Engineering-64a875e74842500d9e80e23e/issues/nautobot/nautobot/4316?planning-poker) with Zenhub @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1

**Comment by whitej6** [comment]
@bryanculver one requirement I would add is when running the management command is if the network_driver is set then it is excluded.

example queryset to apply update to `Platform.objects.exclude(network_driver__exact="")`

**Comment by gsnider2195** [comment]
Isn't the `network_driver` field intended to replace the `napalm_driver` field? Would we want to try to derive the new value from the reverse mapping of whatever is in `napalm_driver` and only fall back to slug if that doesn't work?

**Comment by whitej6** [comment]
> Isn't the `network_driver` field intended to replace the `napalm_driver` field? Would we want to try to derive the new value from the reverse mapping of whatever is in `napalm_driver` and only fall back to slug if that doesn't work?

Separate field and all documentation has treated `slug` as the equivalent of the netmiko `device_type` which is different than `napalm_driver`.
https://github.com/nautobot/nautobot/blob/v2.0.0-rc.2/nautobot/dcim/models/devices.py#L332-L345

**Comment by gsnider2195** [comment]
My proposal is to use the reverse mapping from the `napalm_driver` field if one can be derived:

```py
>>> from netutils.lib_mapper import NAPALM_LIB_MAPPER
>>> NAPALM_LIB_MAPPER
{'asa': 'cisco_asa', 'cisco_wlc_ssh': 'cisco_wlc', 'eos': 'arista_eos', 'fortios': 'fortinet', 'huawei': 'huawei_vrp', 'ios': 'cisco_ios', 'nxos_ssh': 'cisco_nxos', 'nxos': 'cisco_nxos', 'iosxr': 'cisco_xr', 'junos': 'juniper_junos', 'panos': 'paloalto_panos', 'sros': 'nokia_sros', 'vyos': 'brocade_vyos', 'aoscx': 'aruba_aoscx', 'ros': 'mikrotik_routeros'}
```

If not, fall back to slug.
