### ISSUE TITLE
Add new towncrier category: housekeeping

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#4331]
### Proposed Changes

New category for towncrier for documenting changes that don't generally affect the users of Nautobot such as documentation updates and making changes to CI.

### Justification

Get rid of some of the noise in the release notes.

**Comment by bryanculver** [comment]
> Such as documentation
Hopefully this is required going forward for adding features (so just added with the feature), fixing missing documentation (`.fixed`), or in the case of adding solution/use cases ("How to model a spine-and-leaf network") it's a feature `.added`.

But for making changes to CI, updating maintainer docs (#4326), yes big 👍 👍 for `.housekeeping`.

**Comment by bryanculver** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Engineering-64a875e74842500d9e80e23e/issues/nautobot/nautobot/4331?planning-poker) with Zenhub @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1
