### ISSUE TITLE
Nautobot 2.0 Docker Containers now use a venv

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#4333]
## Proposed Change:

Remove the use/procedure of a Python virtual environment in the 2.0 `Dockerfile`, instead opting to use the system Python environment to contain the packages to be installed.

No changes to the Node.JS or other tooling are intended.

---
### Environment
* Nautobot version (Docker tag too if applicable): 2.0rc2
* Python version: 3.11
* Database platform, version: NA
* Middleware(s): NA

The new docker containers for Nautobot 2.x now install the python virtual environment in /opt/nautobot.  This is a breaking change from the 1.x series as containers adding dependencies to Nautobot now need to install in this now location.

1.  Why are we using a virtual environment inside of a docker container (this is already a virtual environment dedicated to Nautobot)
2. If we really need to create a venv the final Nautobot container should NOT be based on a python upstream container as to not have 2 separate python environments installed creating disk bloat

**Comment by bryanculver** [comment]
Related: https://github.com/nautobot/nautobot/pull/4082

**Comment by gsnider2195** [comment]
WRT "should NOT be based on a python upstream container as to not have 2 separate python environments installed creating disk bloat" I'm only seeing an extra 25k used (31k actual disk usage) after creating the virtualenv so I don't think that should be a concern.

**Comment by bryanculver** [comment]
From @glennmatthews 

Some notes/context on the changes made in #4082:
* Nautobot 2.0 needs to be able to (re)build the React UI (nautobot-server build_ui / post_upgrade)
    * This requires a directory writable by the nautobot user (in final image)
    * This requires a directory writable by the root user (in dev and final-dev images, since we’ve already backed away from the initial change in #4082 to use nautobot user in all three images)
    * /opt/nautobot/ui was selected
    * Note that building dev vs. final-dev/final are two separate build_ui invocations, because dev includes the example plugins and final-dev/final do not
    * For simplicity/consistency, run both build_ui commands as the nautobot user in both cases, not as root
    * However nautobot user can’t install to the system python, so for simplicity and consistency with the non-Docker install process, I switched the build to using a virtualenv in /opt/nautobot so as to not have to keep switching between users
* We don’t want to have installed Node dependencies “leak out” to the host filesystem when doing dev
    * Nor do we want the compiled UI to “leak out” from dev containers
    * Volume mount ../nautobot/ui to /opt/nautobot/ui but exclude /opt/nautobot/ui/build and /opt/nautobot/ui/node_modules from the mount
* Question: final image normally runs as nautobot user - I guess downstream targets are explicitly doing USER root before installing any new Python dependencies at present? Is this desirable long-term or does switching to a virtualenv that the default user can write to actually make things simpler downstream?

**Comment by bryanculver** [comment]
Per discussion today with @nautobot/core, we are going to change the Dockerfile to perform the Python installation without the use of a virtual environment. This deviation from the system/venv installation method in our docs is intentional, not a gap.

**Comment by bryanculver** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Engineering-64a875e74842500d9e80e23e/issues/nautobot/nautobot/4333?planning-poker) with Zenhub @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1
