### ISSUE TITLE
Allow `Prefixes` to belong to many `Locations`

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot#4334]
### As ...

Nelly - Network Engineer

### I want ...

to have a prefix shared across many different locations.

### So that ...

I could model a prefix shared across many different locations (e.g., building), a common use case for Campus Networks where a segment is spread over building on the same Campus.

### I know this is done when...

I can relate a Prefix to many Locations without the current single association limit.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [X] DCIM
- [X] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- Change type of relationship

**Comment by chadell** [comment]
> I think I misunderstood when we spoke last week, shouldn't the thing be to have a location that represents the higher level thing here? Like shouldn't there be a campus location and multiple building locations under it?

You understood me correctly. One way to solve the challenge is to create a parent location (Campus), that contains children (buildings), and use a logic that allows a building to use the prefixes from a parent.

But, this issue is to open the door for a more flexible prefix association with locations (a different way to solve it)

**Comment by lampwins** [comment]
Would a compromise here be the ability to assign a prefix higher in the location hierarchy and have that context visible to child locations? I.e. You assign the prefix to the campus, and Build A is able to know that the prefix applies to it?

**Comment by chadell** [comment]
Yes, that would be great. It's what we are implementing to get the desired functionality, actually.
But, having it generally available, would be much better for my use case, even thought this FR could serve other mode diverse use cases.

**Comment by gt732** [comment]
@chadell I have a use case currently that needs this. Just curious what you did in the meantime to get this working. Thanks!

**Comment by chadell** [comment]
@gt732 , I decided to wait until https://github.com/nautobot/nautobot/issues/4412 it's implemented, and leverage it.
Meanwhile, depending on the amount of data, you can leverage custom relationships or implement a custom model that creates this many to many relationship by its own (we picked this second one for our use case)

**Comment by Kircheneer** [comment]
I don't think assigning to a higher location hierarchy level is _always_ appropriate as a solution. Consider a scenario where a prefix is only available in 2/3 rooms in a given building, if I attach the prefix to the building I lose information.

**Comment by gsnider2195** [comment]
## Overview of the work involved based on similar work in #4412 
- Add field to model / migration
- Data migration
- Remove old field migration
- Add backward compatible properties to model
- Location view
- Prefix view
- Versioned serializers for Prefix
- Prefix filter
- Prefix form
- Prefix filter form
- Template updates for Prefix detail and edit views
- Tests

**Comment by glennmatthews** [comment]
Implemented for 2.2 by #5281.
