### ISSUE TITLE
Establish Long-Term Maintenance Branch

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#4338]
- Branch `ltm/1.6` off of `develop`
- Update CI to protect and test LTM branches
- Enable for upstream testing workflows for apps
- Document the changes
- Consider merging `next` down into `develop`

**Comment by bryanculver** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Product-64a8783b7a3f4b1225973a0c/issues/nautobot/nautobot/4338?planning-poker) with Zenhub @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1

**Comment by gsnider2195** [comment]
The weekly report job on the dev server will need to be updated for the upstream testing workflow

**Comment by bryanculver** [comment]
Renovate Config: https://github.com/nautobot/nautobot/blob/next/renovate.json
Integration Workflow: https://github.com/nautobot/nautobot/blob/next/.github/workflows/ci_integration.yml
PR Workflow: https://github.com/nautobot/nautobot/blob/next/.github/workflows/ci_integration.yml
Branch Management: https://github.com/nautobot/nautobot/settings/branches
