### ISSUE TITLE
Include Scalene profiling

### ISSUE THREAD

**Issue by BlackDark** [nautobot/nautobot#4345]
### As ...

Isabella - Infrastructure Owner

### I want ...

To investigate performance bottlenecks more precisely.

### So that ...

`cProfile` is already integrated but maybe add an additional one with more features.
https://github.com/plasma-umass/scalene

### I know this is done when...

- Available option to get profiling output via scalene on top to cprofile

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [X] Other (not directly a platform feature)

### External Dependencies

- https://github.com/plasma-umass/scalene

**Comment by lampwins** [comment]
We have actually implemented django-silk which has cProfile capabilities. This will come in upcoming 2.1 and 1.6 patches.
