### ISSUE TITLE
ERROR syslog regarding 'note_list' during Nautobot startup

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#4349]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.0rc2
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
Run any `nautobot-server` command

### Expected Behavior

Nautobot to run without errors

### Observed Behavior

```
18:55:28.739 ERROR   nautobot.core.apps   __init__.py                                url() :
  Error in link construction for Notes: Reverse for 'note_list' not found. 'note_list' is not a valid view function or pattern name.
```

**Comment by HanlinMiao** [comment]
This occurs https://github.com/nautobot/nautobot/blob/1f5c38eee6a0926f1bc769a2bf667e827e5cec9c/nautobot/extras/navigation.py#L704C1-L713C1. And the TODO comment addresses why the link is there. Related to https://github.com/nautobot/nautobot/issues/4309

**Comment by skumarmallampeta** [comment]
Hi, I am running into a similar issue running nautobot version 1.5.11 in a docker, can you please let me know how to resolve this issue

nautobot_1         |                                     [--no-refresh-dynamic-group-member-caches]
nautobot_1         | nautobot-server post_upgrade: error: unrecognized arguments: --no-invalidate-all
nautobot_1         | ⏳ Waiting on DB... (6s / 30s)
nautobot-worker_1  | Grafana ChatOps integration is not available.
nautobot-worker_1  | NoneType: None
nautobot_1         | Grafana ChatOps integration is not available.
nautobot_1         | NoneType: None
nautobot-worker_1  | 20:44:32.003 ERROR   nautobot.core.apps :
nautobot-worker_1  |   Error in link construction for Notes: Reverse for 'note_list' not found. 'note_list' is not a valid view function or pattern name.
nautobot-worker_1  | usage: nautobot-server post_upgrade [-h] [--version] [-v {0,1,2,3}]
nautobot-worker_1  |                                     [--settings SETTINGS]
nautobot-worker_1  |                                     [--pythonpath PYTHONPATH] [--traceback]
nautobot-worker_1  |                                     [--no-color] [--force-color]
nautobot-worker_1  |                                     [--skip-checks] [--no-build-ui]
nautobot-worker_1  |                                     [--no-clearsessions] [--no-collectstatic]
nautobot-worker_1  |                                     [--no-migrate]
nautobot-worker_1  |                                     [--no-remove-stale-contenttypes]
nautobot-worker_1  |                                     [--no-trace-paths]
nautobot-worker_1  |                                     [--no-send-installation-metrics]
nautobot-worker_1  |                                     [--no-refresh-content-type-cache]
nautobot-worker_1  |                                     [--no-refresh-dynamic-group-member-caches]
nautobot-worker_1  | nautobot-server post_upgrade: error: unrecognized arguments: --no-invalidate-all
