### ISSUE TITLE
Standardize display of nested fields in NewUI detail views

### ISSUE THREAD

**Issue by timizuoebideri1** [nautobot/nautobot#4355]
### Proposed Changes
The NewUI detail views currently do not have a standardized way of displaying fields from nested serialised data from the API. 

For example:

- The IPAddress API response contains nested namespace and vrfs fields that cannot be directly accessed like flat keys:
  - namespace is nested under `parent`: `api_response.parent.namespace`
  - vrfs is nested under `parent`: `api_response.parent.vrfs`
 
This makes it difficult to generically render all the desired fields in the detail views. We need to create a standardized way of accessing and displaying nested fields in detail views.

### Justification

This would simplify displaying all relevant fields in detail views even if they are not flat keys in the serializer data.

**Comment by bryanculver** [comment]
I think this will be a case of "A schema can only define so much". Might be easier to create custom views for complex things like IP Address and Prefix.

**Comment by HanlinMiao** [comment]
This could be accomplished alternatively by adding those fields onto the serializer and processing and displaying the data in the front end as we desire. We have some helper functions to build nested fields like these.
