### ISSUE TITLE
Possible Redis error when using new nautobot_config.py file in 1.0.1

### ISSUE THREAD

**Issue by tim-fiola** [nautobot/nautobot#436]
### Environment
* Python version: python 3.8.5
* Nautobot version: 1.0.1
* OS: Ubuntu 20.04.2

### Steps to Reproduce
1.  Follow [Nautobot install docs](https://nautobot.readthedocs.io/en/latest/installation/nautobot/) for Ubuntu 20.04.2 up to [nautobot-server createsuperuser](https://nautobot.readthedocs.io/en/latest/installation/nautobot/#create-a-superuser)
2. Run `nautobot-server createsuperuser`
3. You will see an error after defining the `Username`

### Expected Behavior
```
nautobot@gipsy-danger:~$ nautobot-server createsuperuser
Username: tim
Email address: 
Password: 
Password (again): 
Superuser created successfully.
nautobot@gipsy-danger:~
```

### Observed Behavior
```
nautobot@november-ajax:~$ nautobot-server createsuperuser
Username: tim
/opt/nautobot/lib/python3.8/site-packages/cacheops/redis.py:19: RuntimeWarning: The cacheops cache is unreachable! Error: Client sent AUTH, but no password is set
  warnings.warn("The cacheops cache is unreachable! Error: %s" % e, RuntimeWarning)
Email address: 
Password: 
Password (again): 
Superuser created successfully.
```

### Troubleshooting
It was suggested to manually define `CACHEOPS_REDIS` in the `nautobot_config.py` file.  This is what I did for a new, fresh troubleshooting install:
```
CACHEOPS_REDIS = "redis://@localhost:6379/1"
```

When I did that, I did not see the error on the fresh troubleshooting install:
```
nautobot@gipsy-danger:~$ nautobot-server createsuperuser
Username: tim
Email address: 
Password: 
Password (again): 
Superuser created successfully.
nautobot@gipsy-danger:~$
```

**Comment by jathanism** [comment]
So after performing a fresh `nautobot-server init`, the following is inside of the newly generated `nautobot_config.py`:

```
# Nautobot uses Cacheops for database query caching. These are the following defaults.
# For detailed configuration see: https://github.com/Suor/django-cacheops#setup
CACHEOPS_REDIS = "redis://localhost:6379/1"
```

Can you please confirm that this is your experience? The only difference here being that `@` not being there, which isn't necessary you're not passing in credentials anyhow.

**Comment by tim-fiola** [comment]
Yes, let me clarify a bit.

After doing a fresh `nautobot-server init`, the `nautbot_config.py` file has the following by default:
```
CACHEOPS_REDIS = os.getenv("NAUTOBOT_CACHEOPS_REDIS", f"{redis_protocol}://:{cache_ops_pwd}@{cache_ops_host}:{cache_ops_port}/1")
```

When left like that, I receive that error upon superuser creation.

On my most recent install, when I replaced the above with `CACHEOPS_REDIS = "redis://localhost:6379/1"`, I did not receive that error.

**Comment by tim-fiola** [comment]
You can see the `CACHEOPS_REDIS` value in 1.0.1 in the `nautobot_config.py.j2` template file

https://github.com/nautobot/nautobot/blob/3a6d2628f41bc3b89e7a7b59e91f4930b36d86fd/nautobot/core/templates/nautobot_config.py.j2#L61

**Comment by jathanism** [comment]
Okay, yeah, for some reason my local environment had `1.0.1b1` installed? Confirmed. I'll get a fix out.

**Comment by jathanism** [comment]
This is what is happening:

```
>>> from django.conf import settings
>>> settings.CACHEOPS_REDIS
'redis://:None@localhost:6379/1'
```
