### ISSUE TITLE
Custom Messaging for Error Pages (403, 404, 500)

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#4361]
### As ...

Patti - Platform Admin

### I want ...

Custom branding support on the 500 error page

### So that ...

My users can follow my organization's specific steps for support, instead of the current text at the bottom, which instructs then to join the #nautobot channel in slack.

### I know this is done when...

- A new custom branding entry for the error pages
- This setting allows me to specify text and links to present to the user on the page when an error is rendered
- When I specify a value in the new setting, the existing support text is removed

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by lampwins** [comment]
Target 1.6 LTM with this

**Comment by david-kn** [comment]
We'd love to see this capability implemented.

And as 500 error page would be useful indeed, is there any chance on expanding this possibility to customize also 404/403 pages as well? IMHO this would be useful for improved user navigation in these cases :-)

**Comment by lampwins** [comment]
Yes, let's expand this to cover all error handler pages we serve from the app.

**Comment by bryanculver** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Product-64a8783b7a3f4b1225973a0c/issues/nautobot/nautobot/4361?planning-poker) with Zenhub @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1

**Comment by bryanculver** [comment]
Are we OK with limiting the messaging on these pages to only supporting plain-text or Markdown?

This gets us around "how to easily redefine" if it's HTML-only or bust as well as any script injection concerns.

**Comment by bryanculver** [comment]
> Are we OK with limiting the messaging on these pages to only supporting plain-text or Markdown?
> 
> This gets us around "how to easily redefine" if it's HTML-only or bust as well as any script injection concerns.

From @lampwins:

> I just need to be able to specify text which may contain links. How that is done I don't really care. Markdown is fine

Markdown it is!
