### ISSUE TITLE
Tag filter silently ignores non-existent values

### ISSUE THREAD

**Issue by snaselj** [nautobot/nautobot#4371]
### Environment

* Nautobot version v2.0.0rc2
* Python version: 3.8
* [Floor Plan test](https://github.com/nautobot/nautobot-plugin-floor-plan/blob/83b59ced5626d8a833150319c904a7d870538504/nautobot_floor_plan/tests/test_filters.py#L45)

### Steps to Reproduce

When specifying non-existent value in tag filter, it returns all objects.

Following test returns all `FloorPlan` objects:

```python
class TestFloorPlanFilterSet(TestCase):

    ...

    def test_tag(self):
        """Test filtering by Tag."""
        self.floors[0].floor_plan.tags.add(Tag.objects.create(name="Planned"))
        params = {"tag": ["planned"]}
        self.assertEqual(self.filterset(params, self.queryset).qs.count(), 1)
```

Tests passes when I change `params` to:

```python
...
        params = {"tag": ["Planned"]}
...
```

### Expected Behavior

Expecting some error, when specifying non-existent value in tag filter.

### Observed Behavior

Filter is ignored silently, and all objects are returned.

**Comment by glennmatthews** [comment]
Wonder if there's something more nuanced going on here. For example the below reports an error as would be expected:

https://next.demo.nautobot.com/dcim/racks/?tags=foobar

**Comment by snaselj** [comment]
Strange thing is there is `tag` key in the test, with `tags` it ignores the filter with both values

**Comment by HanlinMiao** [comment]
> Strange thing is there is `tag` key in the test, with `tags` it ignores the filter with both values

You mean when `tags` is specified, "planned" and "Planned" both return the same queryset (all `FloorPlan` objects)?

**Comment by bryanculver** [comment]
> Strange thing is there is `tag` key in the test, with `tags` it ignores the filter with both values

https://github.com/nautobot/nautobot-plugin-floor-plan/blob/83b59ced5626d8a833150319c904a7d870538504/nautobot_floor_plan/filters.py#L24

**Comment by gsnider2195** [comment]
Were you able to verify that this is indeed a problem in core and not with the app?

**Comment by snaselj** [comment]
> Were you able to verify that this is indeed a problem in core and not with the app?

Indeed, the issue was in the app, filter defined `tag` field, instead of using `tags` from `PrimaryModel`, thanks for pointing me the right direction.

**Comment by snaselj** [comment]
Issue was in the app.
