### ISSUE TITLE
nautobot-plugin-floor-plan: allow objects to take parts of tiles

### ISSUE THREAD

**Issue by martin-networker** [nautobot/nautobot#4380]
### As ...

Ozzie - Operator

### I want ...

I want objects to be able to take parts of tiles.

### So that ...

So that I can create objects which takes only one third of tile or racks which takes one full tile plus one third of tile.
1) The benefit of this tool is that it depicts not only racks but also objects around (hot/cold aisle, etc.). We have racks in cages and we need to display the cage and where are doors to cage positioned. Creating doors with the same size as rack (one tile) makes it look unnatural so I wanted to create it with size of one third of tile.
2) All our racks are of the same size except few racks (usually network racks) which requires more cabling and thus more space. So these rack are wider. It is helpful to see which racks are larger. But I am unable to model racks which takes one and one third of tile.

Possible solution would be to create bigger raster so lets say for every real tile we will have 3x3 raster of tile. This would be feasible but instead of floor plan 26x12 of tiles we would need to create floor plan with 78x36 tiles.
Problem is this makes the problem described in "#4379 increase size of displayed text" even bigger.

### I know this is done when...

creating objects in floor plan

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [X] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by whitej6** [comment]
Please open this feature request on the floor plan repo.
