### ISSUE TITLE
nautobot-plugin-floor-plan: missing name parameter and possibility of multiple floor plans per location

### ISSUE THREAD

**Issue by martin-networker** [nautobot/nautobot#4381]
### As ...

Ozzie - Operator

### I want ...

I want to be able to create more than one floor plan per location. And I want to be able to search the floor plan based on defined name.

### So that ...

Floor plan does not have a name parameter. It has only display parameter which can't be set but is derived from location,  e.g. "Floor Plan for Location \"room_x\". This cause two problems:
1) floor plan can be searched only by location or displayed name which is derived from location
2) We are unable to create more floor plans per location. Below are use cases for this request:
    a ) creation of two or three floor plan versions for discussion with Datacenter team to find out which will be most useful
    b) create temporary floor plan just for discussion about moving something it the room

### I know this is done when...

during creation of floor plan.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [X] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by whitej6** [comment]
Please open this feature request on the floor plan repo.
