### ISSUE TITLE
Config contexts applied to parent locations missing from rendered config context

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#4388]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.0rc1 (next.demo.nautobot.com)

### Steps to Reproduce
1. Based on the demo data on next.demo.nautobot.com, create the following config-contexts:
    a. "americas", applicable to location Americas
    b. "united-states", applicable to location Americas -> United States
    c. "ATL01", applicable to location Americas -> United States -> ATL01
2. View the config context tab for any device in ATL01

### Expected Behavior

Rendered config context to include data from all three of these config contexts

### Observed Behavior

Although all three contexts appear as "Source Contexts" on the right, the rendered config context only includes ATL01 and not the other two:

![image](https://github.com/nautobot/nautobot/assets/5603551/2bee3c7e-9e20-44bc-93d5-149ed7e00434)

**Comment by gsnider2195** [comment]
We need to make sure we have test coverage for this use case
