### ISSUE TITLE
Missing features in Tags REST API

### ISSUE THREAD

**Issue by EdificomSA** [nautobot/nautobot#4394]
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.2
* Python version: 3.10
* Database platform, version: postgres 14
* Middleware(s):

The tags.content_types field is not represented in the REST API.

![Screenshot 2023-09-06 081839](https://github.com/nautobot/nautobot/assets/118285649/e3c5fc74-77d0-488b-84cf-8b352dcc145d)
![Screenshot 2023-09-06 082146](https://github.com/nautobot/nautobot/assets/118285649/5e08caf1-c30e-46bc-af32-f2442f5e8b3d)

Filter only shows content_types though (advanced tab also has name, slug, etc.)
![Screenshot 2023-09-06 082313](https://github.com/nautobot/nautobot/assets/118285649/d30e01b5-3fd9-495e-aef7-e7393f849101)

#872
#1505

**Comment by glennmatthews** [comment]
Expected with API version 1.2 (as shown in your screenshot) as this feature was added in version 1.3. Opting in to API version 1.3 or later (e.g. https://demo.nautobot.com/api/extras/tags/?api_version=1.3) shows the `content_types` field as expected:

![image](https://github.com/nautobot/nautobot/assets/5603551/05f8d9b9-5025-44cb-9f69-6b91ba484b9f)

See also https://docs.nautobot.com/projects/core/en/v1.6.2/rest-api/overview/#versioning
