### ISSUE TITLE
Rack object creation fails with mandatory custom field (web form data handling issue)

### ISSUE THREAD

**Issue by david-kn** [nautobot/nautobot#4396]
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.1
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Let's have a custom field that is required for `dcim.rack` model (let's say custom field "owner")
2. Try to create a new rack via web GUI and fill in all mandatory data (including that mandatory custom field).

BUT 
- adding new rack works in `nbshell` when using `validated_save()` (it seems that the problem is not within the validators)
- adding new device works via API also works
e.g. following minimalistic API payload works just fine:
```
{
  "name": "rack1234",
  "site": "a87d0362-3a21-5cee-a147-57dee074e9ab",
  "status": "Active",
  "custom_fields": {
       "owner" : "ownerABC_of_the_rack"
  }
}
```

Hence it seems that the problem is somewhere in the handing the data between a form to the backend. 

Tested also on your demo.nautobot.com instance and received the same error.

### Expected Behavior
A new rack to be created.

### Observed Behavior
Object creation fails with an error message `Missing required custom field 'owner'`

**Comment by Thetacz** [comment]
Note: *any* custom field value from edit form gets discarded, not only required fields

**Comment by gsnider2195** [comment]
Replicated on `demo.nautobot.com` and `next.demo.nautobot.com`

**Comment by bryanculver** [comment]
It appears not to affect all models. Validated in Demo that IP Address works fine.

**Comment by lampwins** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Product-64a8783b7a3f4b1225973a0c/issues/nautobot/nautobot/4396?planning-poker) with Zenhub @bryanculver @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1
