### ISSUE TITLE
Interface Role

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#4406]
### As ...

Nelly - Network Engineer

### I want ...

To be able to specify a role for interfaces

### So that ...

I can track common interface configurations based on role meaning

### I know this is done when...

- I can create Role instances that can be assigned to interfaces
- Interface role assignment is optional

### Optional - Feature groups this request pertains to.

- DCIM

### Database Changes

- Add role field to Interface and VMInterface

**Comment by nitzan-tz** [comment]
For this feature please also add a template of trunk/access + vlans.
This way if you have to add or remove a vlans to a lot of common interfaces you can do it in one place

**Comment by aedwardstx** [comment]
So glad this idea came up! My team and I brainstormed on this for a bit yesterday and feel that this feature can initially be pretty minimal. I’m thinking the InterfaceRole model would need a `name`, `description`, and a list of `relevant_device_roles`. Custom fields linked from InterfaceRole to VLANs, VLAN_roles, or other models may be used to enhance functionality in the way @nitzan-tz is suggesting.

It may be a good idea to also add a config context schema to InterfaceRole. This schema could live under the interface config context allowing for properties relevant to the specific interface_role to be set.

Example workflows this could enable:
- More streamlined interface configuration using a custom Job
    - Select a device
    - Select an interface
    - Based on the device’s device_role, you’d be given a list of interface_roles
    - Select an interface_role
    - Fill out the interface_role config_context per the interface_role config_context schema
- Classifying existing interfaces into interface_roles
- Minimizing the interface details stored in Nautobot

**Comment by nrnvgh** [comment]
For the record, I'm also interested in this, and like (in theory at least) @aedwardstx 's notion of Config Contexts on interface roles.
