### ISSUE TITLE
Allow associating a `VLAN` to many `Locations`

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot#4412]
### As ...

Nelly - Network Engineer

### I want ...

to have the ability to associate one `VLAN` to more than one `Location`

### So that ...

I could map the traditional campus network design where a VLAN is routed in one building but it's spread as layer2 across several buildings (usually part of the same campus).
However, we can't assume that all the buildings on the campus have the same VLAN associated, so it must be granular enough.

### I know this is done when...

- I can associate a VLAN to more than one Location

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [X] DCIM
- [X] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- I would advocate to not try to replace the current ForeignKey from VLAN to Location to not make it a breaking change, but add it as an additional feature for now.

**Comment by gsnider2195** [comment]
Related #752

**Comment by lampwins** [comment]
Consider the constraint on vlan groups and locations

**Comment by lampwins** [comment]
John will ask around to see if the group location constraint can just be ripped out.
