### ISSUE TITLE
Support Multiple Roles

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#4415]
### As ...

Nelly - Network Engineer

### I want ...

to allow a device to serve multiple roles in my environment.

### So that ...

In small sites I may want to apply multiple roles to a single device, so that I can apply multiple policies.

### I know this is done when...

- Go to a device
- Select roles
- Allow for multiple selections

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [X] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- Update relationship

**Comment by lampwins** [comment]
This has been discussed through the years in both communities and the general consensus has always been that a single, descriptive role is better at accurately describing the function of a device than multiple, often less granular roles.

The example I always come back to is to consider a network with layer 2 access switches, layer 3 routers at the distribution, and then top of rack switches in the DC. The argument is to say that the TOR gets both of the layer 2 and layer 3 roles assigned. The counter, is that a TOR is neither a layer 2 switch nor layer 3 router, it is instead, a TOR, which is something else.

IMO when folks are trying to go down the multiple role route, what they are often trying to model is configuration features, which I think we should compose at a higher level above the role definition. I.e. "this role is comprised of layer 2 and layer 3 features."

I'm not saying no, I just think there is a deeper rooted need that can be solved in a different way.


> In small sites I may want to apply multiple roles to a single device, so that I can apply multiple policies.

@jvanderaa can you elaborate on what about "small sites" presents a unique challenge here?

**Comment by jvanderaa** [comment]
This gets back to my retail background mostly.

I'm thinking of the 3-tier design and branch sites. Most of the time 3-tier you will have a specific policy for your Access, Distribution, and Core layers. So at a small site that has a flat network design at it then you would often have the Core / Distribution layer devices, and policies applied to the router, and then your access design applied to the access switches.

I would solve this today using tags of something like `role: core` to be able to attribute devices to filling the particular role for the environment. 

In some of these environments where there is a larger/smaller footprint you may change the design either scaling up the number of devices to have a full distribution switch because it is needed, or consolidate things further down, say into just a single device for really small sites.

**Comment by lampwins** [comment]
I appreciate the thoughts here, but we will stick with single role associations. We will add support for interface roles in 2.3, which I imagine will help in some use cases which multiple device roles may have been desired.
