### ISSUE TITLE
`CablePath matching query does not exist.` when deleting a device with multiple types of connected interfaces.

### ISSUE THREAD

**Issue by ebusto** [nautobot/nautobot#4416]
### Environment
* Nautobot version: 1.6.2
* Python version: 3.11.5
* Database platform, version: PostgreSQL 14
* Middleware(s): N/A

### Steps to Reproduce
1. Create two devices, along with at least two types of interfaces (network, console + console server) in each device.
2. Create cables between both types of interfaces.
3. Try to delete one device.

### Expected Behavior
The device to be successfully deleted.

### Observed Behavior
An exception:
```
<class 'nautobot.dcim.models.cables.CablePath.DoesNotExist'>

CablePath matching query does not exist.
```

**Comment by ebusto** [comment]
Assuming the database doesn't get reset with any regularity, you can see this issue on the public demo instance by trying to delete [this](https://demo.nautobot.com/dcim/devices/c88a2ef4-3de8-4387-a99e-36f77959268e/?tab=main) device.

**Comment by lampwins** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Product-64a8783b7a3f4b1225973a0c/issues/nautobot/nautobot/4416?planning-poker) with Zenhub @bryanculver @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1
