### ISSUE TITLE
Nautobot2: Ip version wording

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#4423]
### Environment
* Nautobot version (Docker tag too if applicable): next.demo.nautobot.com
* Python version: next.demo.nautobot.com
* Database platform, version: next.demo.nautobot.com
* Middleware(s): next.demo.nautobot.com

### Steps to Reproduce
1. Navigate to https://next.demo.nautobot.com/ipam/prefixes/54882e13-e359-462b-8f57-3dbab7595bc8/
2. See the wording `Ip version` 

### Expected Behavior

Should probably be `IP version`

### Observed Behavior

Seeing `Ip version`

**Comment by bryanculver** [comment]
Duplicate: https://github.com/nautobot/nautobot/issues/4014
