### ISSUE TITLE
Cannot assign VLAN to VLAN Group (UI)

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot#4430]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.0rc1
* Python version: 3.10
* Database platform, version: postgres13
* Middleware(s): None

### Steps to Reproduce
1. Create a VLAN Group
2. Click the 4094 vlans available to create a VLAN
3. Create VLAN

### Expected Behavior
Created VLAN shows up in the VLAN Group

### Observed Behavior
VLAN is created but not associated to the VLAN Group. Additionally, you cannot edit an existing VLAN and add it to the group.

**Comment by glennmatthews** [comment]
Looks to have been broken by #3094. That renamed the form field from `VLANForm.group` to `VLANForm.vlan_group` but didn't update `templates/ipam/vlan_edit.html` accordingly. Fixing this specific issue should be a one-line fix to the template.
