### ISSUE TITLE
Can't use LAG as Parent to Virtual Interface

### ISSUE THREAD

**Issue by mngan** [nautobot/nautobot#4436]
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.0
* Python version: 3.9
* Database platform, version: Postgres 14
* Middleware(s):

### Steps to Reproduce
1. Create LAG interface ae0
2. Create Virtual Interface ae0.0
3. While creating Virtual interface, try to select LAG Interface as Parent

### Expected Behavior
I was hoping that the LAG interface would be in the list of valid parents, but that does not seem to be the case.

### Observed Behavior
 It appears that only physical interfaces can be selected as parents. Is this expected? Or am I modeling the the subinterface of a LAG incorrectly? In this case, the sub interface is an IP interface not a switched interface. So using the Bridge model doesn't seem appropriate.

**Comment by glennmatthews** [comment]
Looks like the same issue as netbox-community/netbox#6106, which should be a very simple fix a la https://github.com/netbox-community/netbox/commit/81193eb55054763ede647b0eb27cf61632b5ba3d.

**Comment by mngan** [comment]
This would work. I guess this will also fix the case of `lo.0` and `lo` where both of these are virtual. I was going to work around this by making `lo`'s interface type to `other`.
