### ISSUE TITLE
Sync Git Repository requires different permissions for UI vs API

### ISSUE THREAD

**Issue by MeganerdDev** [nautobot/nautobot#4444]
### Environment
* Nautobot version (Docker tag too if applicable): v1.6.2b1
* Python version: 3.11
* Database platform, version: pg15
* Middleware(s): n/a

From the API it requires “add” and “change” permissions for “extras > Git repository” to sync git repositories. However from the UI a user with only the “change” permission can perform a sync git repository operation
### Steps to Reproduce
For UI
1. Create object permission for `extras > git repository`
2. Create one with "can change" permission item checked ("can view" as well, but not related to reproducing issue)
4. Assign to Group and assign that to User
5. You can perform sync from UI

For API
1. Create object permission for `extras > git repository`
2. Create one with "can change" permission item checked ("can view" as well, but not related to reproducing issue)
4. Assign to Group and assign that to User
5. You cannot perform sync from API
6. Edit permission for the group, adding "can add"
7. You can now perform the sync from the API

### Expected Behavior
Required permissions to be the same for action

### Observed Behavior
Required permissions were not the same for action

**Comment by MeganerdDev** [comment]
API endpoint -> /api/extras/git-repositories/{id}/sync/

**Comment by glennmatthews** [comment]
Per the code both views are only explicitly checking for `extras.change_gitrepository` permission. Likely the API is automatically checking for `add` permission because it's a POST endpoint which by default in DRF would be considered a `create` action. Thanks for the report!

**Comment by lampwins** [comment]
We will set it up such that a user only needs the change permission to do the sync. They do not need the add permission.
