### ISSUE TITLE
Ability to include custom non-packaged python code

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot#4456]
### As ...

Patti - Platform Admin

### I want ...

the ability to develop a single python module and place in a defined location on the application host(s)

### So that ...

The module is importable in python without having to build a plugin OR build/publish a python package that must be installed

### I know this is done when...

- Nautobot config can consume an import string path to the module
- Module can be imported directly in other python code

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [X] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

None

### External Dependencies

None

**Comment by whitej6** [comment]
This is possible today by setting the `PYTHONPATH` environment variable that points to the directory that contains the python code.

I believe this should just be documented as part of the install process

**Comment by jathanism** [comment]
> This is possible today by setting the `PYTHONPATH` environment variable that points to the directory that contains the python code.
> 
> I believe this should just be documented as part of the install process

For the sake of experimentation, if you were to drop an old Python file into `JOBS_ROOT`, are you able to import it? I'm asking because in v2 all jobs are treated as actual Python modules. So we might be able to leverage a similar pattern for this feature request.

**Comment by whitej6** [comment]
I can try it out :-)

**Comment by lampwins** [comment]
We should push people to apps. Those can be installed locally too, without build orchestration. Yes, existing (IMO hacky) python methods exist, I don't want to document them as supported means for extending the application, because of the associated support overhead.
