### ISSUE TITLE
Add filterset field data to uiSchema in REST API for all models with filtersets

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#4462]
### As ...

Cora - Coder

### I want ...

To be able to access filterset information in the REST API

### So that ...

I can build the dynamic filter form in the Nautobot 2.0 React UI

### I know this is done when...

The uiSchema for all models includes a json schema similar to:

```json
{
    "Platform (name or ID)": {
        "filters": [
            {
                "id": "platform",
                "name": "exact"
            },
            {
                "id": "platform__n",
                "name": "not exact (n)"
            }
        ]
    },
    "Is full depth": {
        "filters": [
            {
                "id": "is_full_depth",
                "name": "exact"
            }
        ]
    },
    "Name": {
        "filters": [
            {
                "id": "name__n",
                "name": "not exact (n)"
            },
            {
                "id": "name__ic",
                "name": "contains (ic)"
            },
            {
                "id": "name__nic",
                "name": "not contains (nic)"
            },
            {
                "id": "name__iew",
                "name": "ends with (iew)"
            },
            {
                "id": "name__niew",
                "name": "not ends with (niew)"
            },
            {
                "id": "name__isw",
                "name": "starts with (isw)"
            },
            {
                "id": "name__nisw",
                "name": "not starts with (nisw)"
            },
            {
                "id": "name__ie",
                "name": "exact (ie)"
            },
            {
                "id": "name__nie",
                "name": "not exact (nie)"
            },
            {
                "id": "name__re",
                "name": "matches regex (re)"
            },
            {
                "id": "name__nre",
                "name": "not matches regex (nre)"
            },
            {
                "id": "name__ire",
                "name": "matches regex (ire)"
            },
            {
                "id": "name__nire",
                "name": "not matches regex (nire)"
            }
        ]
    }
}
```

Where the top level key is the filter `label` and the value is derived from the filters in the filterset. This will eventually be a consolidation of the functionality already built into the `/api/ui/core/filterset-fields/lookup-value-dom-element/` and `/api/core/filterset-fields/lookup-choices/` but moving them to the list view OPTIONS request uiSchema key and building the information for the entire filterset by iterating over the `FilterSet().filters.keys()`.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

No

**Comment by bryanculver** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Engineering-64a875e74842500d9e80e23e/issues/nautobot/nautobot/4462?planning-poker) with Zenhub @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1

**Comment by gsnider2195** [comment]
Completed by #4521
