### ISSUE TITLE
Docs Inconsistency with METRICS_ENABLED

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#4472]
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.2
* Python version: 3.10
* Database platform, version: MySQL
* Middleware(s):

### Steps to Reproduce
1. Create a new nautobot_config
2. Update the settings
3. See inconsistency for the databases

### Expected Behavior

I expect the possibility of using MySQL with METRICS_ENABLED set, that there would not be the condition met to set the `charset` as it is without

## Python Code

Here is the Python in the nautobot_config.py:

```python
DATABASES = {
    "default": {
        "NAME": os.getenv("NAUTOBOT_DB_NAME", "nautobot"),  # Database name
        "USER": os.getenv("NAUTOBOT_DB_USER", ""),  # Database username
        "PASSWORD": os.getenv("NAUTOBOT_DB_PASSWORD", ""),  # Database password
        "HOST": os.getenv("NAUTOBOT_DB_HOST", "localhost"),  # Database server
        "PORT": os.getenv("NAUTOBOT_DB_PORT", ""),  # Database port (leave blank for default)
        "CONN_MAX_AGE": int(os.getenv("NAUTOBOT_DB_TIMEOUT", "300")),  # Database timeout
        "ENGINE": os.getenv(
            "NAUTOBOT_DB_ENGINE",
            "django_prometheus.db.backends.mysql" if METRICS_ENABLED else "django.db.backends.mysql",
        ),  # Database driver ("mysql" or "postgresql")
    }
}

# Ensure proper Unicode handling for MySQL
#
if DATABASES["default"]["ENGINE"] == "django.db.backends.mysql":
    DATABASES["default"]["OPTIONS"] = {"charset": "utf8mb4"}

```

If METRICS_ENABLED is set to true in this instance, the last if conditional will not be met. Since the backend would be `django_prometheus.db.backends.mysql`. Is that a viable option?

**Comment by jathanism** [comment]
Oh lord, good catch. We should revise that to be and `.endswith("mysql").

**Comment by jvanderaa** [comment]
I absolutely love the simplicity of the fix that you brought there.
