### ISSUE TITLE
Execute Job API by name

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#4476]
As a Network Automation Engineer, want to execute Nautobot Jobs in the API, referenced by their name, so that I can use the most natural identifier, instead of having to know (or first obtain) the job's UUID, or class path.

I will know this is done when the API and its schema allow accessing and executing a job by reference of the job's name alone. This should now be achievable since Job.name is unique: `/api/extras/jobs/{name}/`

The 2.0 schema those these routes:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdmFzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0fed3e2b923bb8c5f54a0bcfffb3a3649f42074f/Screenshot%202023-09-18%20at%2011.53.45%20AM.png)

1.6 shows these routes, notably with class path being deprecated:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnlzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c7e7256ac58f6099b294eb194af67ca803710999/Screenshot%202023-09-18%20at%2011.54.29%20AM.png)

**Comment by bryanculver** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Product-64a8783b7a3f4b1225973a0c/issues/nautobot/nautobot/4476?planning-poker) with Zenhub @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1

**Comment by bryanculver** [comment]
For reference: https://www.django-rest-framework.org/api-guide/generic-views/#attributes
