### ISSUE TITLE
Expose django slugify in jinja filters

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#4477]
As a Network Automation Engineer, I want the django slugify utility function to be exposed for use in Nautobot jinija2 templates, so that I can have feature parity with the fact it is already exposed as a django template filter.

I will know this is complete when the django slugify function is exposed a registered jinja2 filter.

**Comment by bryanculver** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Product-64a8783b7a3f4b1225973a0c/issues/nautobot/nautobot/4477?planning-poker) with Zenhub @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1
