### ISSUE TITLE
Show child device interfaces under parent device

### ISSUE THREAD

**Issue by BoudewijnSwen** [nautobot/nautobot#4482]
### As ...

Ozzie - Operator

### I want ...

I would like to be able to view all interfaces of a device + all it's child devices in 1 view. (preferably under the parent device)

### So that ...

It's clear for everyone that the port they are looking for is not 'forgotten to create', but just under a PCIe network card that is a separate child-device in the device bays.

### I know this is done when...

- Either a separate tab under each device classified as a 'parent' with all interface on its mounted child-devices.
- Or just add them under the 'interfaces' tab of the parent device, with a clear distinction that shows the interface is located on a child device.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [X] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by jathanism** [comment]
Thanks for the submission @BoudewijnSwen! This is a nice ask of what I can interpret as a "device hierarchy detail view".

**Comment by lampwins** [comment]
As the data model exists today, this would go against the intent of device bays, which are meant to model blade server type devices.

In v2.3 we will implement device models which will support a much more rich set of hierarchical interface relationships. Namely linecard use cases.
