### ISSUE TITLE
invoke cli add command string parameter

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#4495]
### As ...

Patti - Platform Admin

### I want ...

To be able to execute commands inside a container using a script. e.g. for starting a database backup from within the db contaioner. etc.

### So that ...

I can automate tasks that needs to access the container cli

### I know this is done when...

- I execute the command for e.g. to restore a backup `invoke -e cli --service=db --command="bash -c '/usr/lib/postgresql/${postgres_version_number}/bin/psql ${NAUTOBOT_DB_NAME} -U ${NAUTOBOT_DB_USER} < /backups/${sqlname}'"`

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [X] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- None

### External Dependencies

- None

**Comment by jathanism** [comment]
Hi @jifox, thanks for the submission. To clarify, it sounds like you are asking for an enhancement to `invoke cli` to support more arguments for explicitly running commands?

If I'm following, some of the new arguments are:

- `--service`
- `--command`

Am I on the right track? Thanks!

**Comment by jifox** [comment]
Yes, you are right.

I'm using the command parameter to specify the command that will be executed in container

**Comment by gsnider2195** [comment]
Would this be covered by #4431?

> Added `--command` argument to cli task to specify command to run

**Comment by jifox** [comment]
@gsnider2195 Yes that is covered by #4431
