### ISSUE TITLE
multiple functions named register_jobs

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#4498]
### Proposed Changes

One of these should be renamed

- `nautobot.extras.plugins.register_jobs`
- `nautobot.core.celery.register_jobs`

### Justification

It's confusing having these named the same

**Comment by jathanism** [comment]
This is my fault and was not meant to persist out of prototype. The former pattern is what inspired the latter. The only thing really differs is `plugins.register_jobs` adds the job model to `plugin_jobs` in the Nautobot registry, and `celery.register_jobs` calls `app.register_task()` to add to the Celery registry.

Ideally new should just unify them if we can, or if we leave them as-is, simply rename them (e.g. `register_plugin_jobs` and `register_celery_jobs` respectively).

**Comment by gsnider2195** [comment]
I think the original idea was to make BaseJob a meta class and make the subclass automatically register in celery but we haven't been able to implement that yet 😦
