### ISSUE TITLE
UI buttons incorrect when editing an existing interface

### ISSUE THREAD

**Issue by chipn** [nautobot/nautobot#45]
### Environment
* Python version: 3.8.5
* Nautobot version: 1.0.0b1

### Steps to Reproduce
1. Navigate to an existing  device -> interfaces tab
2. Click "Edit" button for any interface or navigate to interface and click "Edit"

### Expected Behavior

Buttons at bottom of edit form should be "Update" / "Update and Continue Editing"

### Observed Behavior

Buttons at bottom of edit form are "Create" / "Create and Add Another" 

Issue appears to be here:
https://github.com/nautobot/nautobot/blob/3d936d3007172b006df9ae1bdc875d0065b03307/nautobot/dcim/templates/dcim/interface_edit.html#L40-L47

**Comment by jathanism** [comment]
Ah the `editing` bool is new. Looks like the logic is inverted or `editing` is missing from the template context. Educated guess is the former.
