### ISSUE TITLE
Remove placeholder numbers in new UI

### ISSUE THREAD

**Issue by DistantVoyager** [nautobot/nautobot#4510]
### Environment
* Nautobot version (Docker tag too if applicable): v2.0.0rc3
* Python version: 3.8

### Steps to Reproduce
1. View new UI home page

### Expected Behavior
No value is shown since the logic isn't implemented at this time.

### Observed Behavior
Confusing placeholder values are shown.

![image](https://github.com/nautobot/nautobot/assets/111259311/8ec43f57-c396-4613-9c83-8d5da67ae246)

**Comment by jathanism** [comment]
Thanks for the submission @DistantVoyager! Obviously this panel is still just a mockup, but I can see how it would be confusing or misleading to have numbers show without any actual context.
