### ISSUE TITLE
KeyError on custom action not present in `PERMISSIONS_ACTION_MAP`

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot#4511]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.0rc3
* Python version: 3.11
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Create UI viewset with additional action
2. Attempt to use additional action
3.

### Expected Behavior
View works

### Observed Behavior
KeyError exception for action not being in `PERMISSIONS_ACTION_MAP`

**Comment by jathanism** [comment]
Just for the sake of clarity we're talking about custom view actions derived from viewset methods. Thanks for this submission.

**Comment by whitej6** [comment]
Yes

**Comment by lampwins** [comment]
Solving via #4529
