### ISSUE TITLE
Status not showing up in choices for DCIM/Cables

### ISSUE THREAD

**Issue by FragmentedPacket** [nautobot/nautobot#452]
### Environment
* Python version: 3.7
* Nautobot version: 1.0.1

### Steps to Reproduce (Using pynautobot)
```
>>> from pynautobot import api
>>> nb = api("http://localhost:8000", "0123456789abcdef0123456789abcdef01234567")
>>> nb.dcim.cables.choices().keys()
dict_keys(['termination_a_type', 'termination_b_type', 'type', 'length_unit'])
```

These are fetched when using the OPTIONS HTTP verb against the list view.

I swear I've submitted an issue or two on this previously, but cannot seem to find them.

### Expected Behavior
To list the three choices that come default for `dcim |  cables`

![image](https://user-images.githubusercontent.com/29315002/118302396-66a8b980-b4a1-11eb-846e-a485f26d7822.png)

### Observed Behavior
See above. Status is not available as choices and fails playbooks in `nautobot-ansible` due to not finding the status when attempting to create a cable.

**Comment by glennmatthews** [comment]
Possibly related to #382?

**Comment by FragmentedPacket** [comment]
Not quite. These don't show up at all rather than having the incorrect key (`display` vs. `display_name`).

I'm wondering if the issue was tracked prior to public release. The endpoint provides no choices for status. I'll dig in deeper once I figure out which content types provide the status (programmatically) to make sure there aren't others.

**Comment by FragmentedPacket** [comment]
Ok I found the commit - https://github.com/networktocode-llc/grimlock/pull/59/files?file-filters%5B%5D=.html&file-filters%5B%5D=.py

I'm attempting to figure out a way to have a dynamic test for any model that has `status` as an attribute for it test that choices are properly rendered, but not entirely sure how to accomplish the test or if a test should exist in multiple spots? Part of the provided API tests class and maybe the viewset as it looks like that is really where it's implemented as well.

**Comment by glennmatthews** [comment]
Rather than any dynamic magic for 'status' field, probably simpler (better?) to add another test case mixin class that can be explicitly included in any API tests that should cover it.
