### ISSUE TITLE
Automatically register Jobs

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#4526]
### As ...

P.D. - Plugin Developer

### I want ...

To have job classes be automatically registered with the celery app when subclassing the `Job` base class

### So that ...

I don't have to call `register_jobs` to register my jobs

### I know this is done when...

I can create a subclass of `nautobot.extras.jobs.Job` in a plugin's jobs.py and it automatically gets registered in celery and a database job model gets created. I don't want to have to add a `jobs = (MyJob)` or `register_jobs(MyJob)` to the jobs.py

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [X] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

none

### External Dependencies

none

**Comment by gsnider2195** [comment]
Prototyped in https://github.com/nautobot/nautobot/tree/prototype/jobs-meta-class

Still need to discuss removing the `registry["plugin_jobs"]` so that the `plugin.jobs.jobs` property can just go away.

**Comment by gsnider2195** [comment]
Related to https://github.com/nautobot/nautobot/pull/4513

**Comment by lampwins** [comment]
Per my comments in #4398, going to mark this as a duplicate, since I think it will result in the same implementation described here.

**Comment by gsnider2195** [comment]
I think this is a different feature from #4398 but we could implement this there. This feature was to remove the requirement to call `register_jobs` on all job classes so that they're registered with celery. #4398 is related to the job database model where this is related to the job class.
