### ISSUE TITLE
JobResult view should robustly handle cases where `data` format is not as expected

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#453]
### Environment
* Python version: any
* Nautobot version: 1.0.1

### Steps to Reproduce
1. Via a `Job` or via `nbshell`, create or modify a `JobResult` object so that its `data` attribute is formatted differently than the "standard" data format constructed and modified by calling `JobResult.log`, for example `jobresult.data = {'hello': 'world', 'this': ['is', 'a', 'list'], 'logger': {'log': [['x', 'y', 'z', 'p', 'd', 'q', 'b', 'b', 'q']]}}`.
2. In the UI under `extras/job-results/`, click on the timestamp link, as if to view details of this JobResult record

### Expected Behavior

JobResult detail view should render successfully:

* Since this JobResult doesn't conform to the "standard" data for logging format, the usual table of log results should presumably not be shown
* For bonus points, the raw JSON of the `data` should be displayed as a fallback option.

Alternatively (though in my opinion less desirably) the JobResult `clean()` or `save()` APIs should verify that the data format is as expected and reject any attempt to create data that does not conform to the format.

### Observed Behavior

ValueError is thrown, for example:

![image](https://user-images.githubusercontent.com/5603551/118307816-32d98e00-b4b9-11eb-95c9-473e1f50ffd7.png)

**Comment by glennmatthews** [comment]
Personally I'd love to address this via a larger JobResult rework that would move log entries into their own separate standalone data model and return `JobResult.data` to being an arbitrary JSON store.

**Comment by glennmatthews** [comment]
#1030 may address this - need to circle back here and verify.

**Comment by smk4664** [comment]
> #1030 may address this - need to circle back here and verify.

Yes it does, I knew I was missing one, but couldn't find it.  Adding to the Fixes...

**Comment by glennmatthews** [comment]
Fixed by #1030.
