### ISSUE TITLE
MKDOCs publishing dependency issues in apps

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot#4571]
Placeholder for tshooting and understanding how we can prevent this from happening again https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/actions/runs/6357489571/job/17268988951

**Comment by glennmatthews** [comment]
As I understand this specific breakage, our dependency `mkdocstrings` had a loosely constrained dependency on `griffe`, and `griffe` made a new release with breaking changes that fell within the version range permitted by `mkdocstrings`. The issue was fixed by `mkdocstrings` improving its dependency pinning, and then by us updating to the fixed version of `mkdocstrings`. Not entirely sure what we can do in general here.

**Comment by pawamoy** [comment]
@glennmatthews that is correct!

I released a version of mkdocstrings-python that rejected the upcoming breaking Griffe version, then I waited one week before releasing the breaking Griffe version, and then released a mkdocstrings-python version that supported it the next day.

In this particular case, the breakage was avoidable by updating dependencies earlier, or making sure both mkdocstrings-python and Griffe dependencies were updated at once. 

An alternative is not to track the lock file and always install latest versions in CI, but that can be a drastic change depending on your workflow :smile: 

I believe this kind of known breakage won't happen often, it was a rare occurrence :slightly_smiling_face: 
It was also announced using a GitHub discussion, and mentioned in our changelogs. Maybe you could subscribe to our announcements (using the watch button), or have a bot that parses changelogs for breaking changes.

**Comment by gsnider2195** [comment]
I think this was also related to the `docs/requirements.txt` in apps. I wonder if we can switch to using the new [`mkdocs get-deps` feature](https://www.mkdocs.org/about/release-notes/#new-command-mkdocs-get-deps) in mkdocs v1.5

**Comment by whitej6** [comment]
@cmsirbu do you feel the docs check in CI plus globally implementing drift manager is enough to close this placeholder I opened on v2 release day?

**Comment by cmsirbu** [comment]
> @cmsirbu do you feel the docs check in CI plus globally implementing drift manager is enough to close this placeholder I opened on v2 release day?

Yup, not sure it's a core issue anyway. Something for the ecosystem tooling to address, and drift-manager is there together with the cookiecutter-app templates. We might find new things breaking when Python 3.8 gets EOL, but IMHO we'll deal with those in the templates when the time comes.
