### ISSUE TITLE
Data Provenance

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#4576]
As Darla the Data Engineer, I want data provenance metadata in Nautobot so I can more easily track things like who owns the data, where it came from, when it was last synced, etc.

**Comment by lampwins** [comment]
New a design mockup for how this is to be presented to the user.

**Comment by lampwins** [comment]
Converted to epic

**Comment by Kircheneer** [comment]
@lampwins possibly I am blind but where is this epic?
