### ISSUE TITLE
Fix Docker Container Images from 2.0 and 1.6.4

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#4595]
Publishing 1.6.3 overrode 2.0.0 for our `stable` and `latest` images in the GitHub container registry. Let's fix this.

**Comment by HanlinMiao** [comment]
[v2.0.1](https://github.com/nautobot/nautobot/releases/tag/v2.0.1) is released and the container issue is closed by https://github.com/nautobot/nautobot/pull/4597
