### ISSUE TITLE
Very is SITE in version 2.0, I need my SITE!!!

### ISSUE THREAD

**Issue by saman-com** [nautobot/nautobot#4602]
I am not sure who has decided to remove site concept and add the location type, location, parent idea. it is really complex and making any import of data from CSV is very complex and unusable!!!!!

just compare the CSV Header from version 1.x:
name,status,location_type,tenant,facility,asn,time_zone,description,physical_address

with version2.0:
name,display,id,object_type,natural_slug,tree_depth,time_zone,circuit_count,device_count,prefix_count,rack_count,virtual_machine_count,vlan_count,description,facility,asn,physical_address,shipping_address,latitude,longitude,contact_name,contact_phone,contact_email,comments,parent__name,parent__parent__name,parent__parent__parent__name,location_type__name,status__name,tenant__name,created,last_updated,tags

you can see Millions of parent!!!!

Please rollback the site concept

**Comment by saman-com** [comment]
edit

**Comment by HanlinMiao** [comment]
Hi @saman-com, thanks for submitting the issue. We understand this is a drastic change that can take some time to adjust to. However, most of the csv column headers you pointed out are optional and you do not have to specify all the parents of the location. You just need to fill out the required columns.
