### ISSUE TITLE
GraphiQL interface save query function giving error

### ISSUE THREAD

**Issue by scetron** [nautobot/nautobot#4606]
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.2
* Python version: 3.9.16
* Database platform, version: postgres 
* Middleware(s): n/a

### Steps to Reproduce
1. Have an existing saved Graphql query (initially from an earlier version of Nautobot)
2. Using the Graphiql interface
3. Update the query with a new value or delete a value
4. Attempt to save the query and observe the error

*note* the saved query editor in the primary Nautobot GUI works

### Expected Behavior
Query to save

### Observed Behavior
An error:

<img width="815" alt="Screenshot 2023-10-04 at 21 26 48" src="https://github.com/nautobot/nautobot/assets/10200477/2f1f2b2e-f94e-412e-9be4-d2e5c6b8a9c1">

**Comment by scetron** [comment]
A workaround is to use the Saved Graphql queries under Extensibility top level menu item, but this is a nicer interface.

**Comment by glennmatthews** [comment]
Can confirm still reproducible in 2.1.0.
