### ISSUE TITLE
Migration guide/tool for GraphQL queries to 2.0

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#4607]
As Austin the Network Automation Engineer, I want docs and preferably a tool to help me migrate by GraphQL queries to 2.0, so that I know the specific changes that need to be made and their implications.

At a minimum, we need to clearly document the necessary changes to queries based on the breaking naming (and other) changes in the schema for 2.0.

Preferably, we have a way to do this validation as a part of Saved GraphQL Queries (or some other such tool) so users could validate their existing saved queries, or create new ones to validate their queries used in other clients.

In the validation approach, the MVP would be to tell the user that a given key in the query is no longer valid. Beyond that, the goal would be to tell the user how to fix it.

**Comment by bryanculver** [comment]
- Similar to the management command to validate Dynamic Groups, let's have one check GraphQL Queries too
- Add documentation to guide users of this feature what things to take a look at (instead of going by change and listing out which features this might change)
