### ISSUE TITLE
Dynamic Groups defined in <2.0 break in >2.0

### ISSUE THREAD

**Issue by JimmyKip** [nautobot/nautobot#4612]
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.x ->2.0.1
* Python version: 3.11 
* Database platform, version: psql
* Middleware(s): n/a

### Steps to Reproduce
1. In Nautobot 1.6.x create Dynamic Group using Tag tenant & status as a filter. 
2. Upgrade Nautobot to 2.0.1
3. Attempt to open the dynamic group in the GUI

Expected the dynamic groups defined in 1.6.x to migrate safely to 2.0.1 and be able to open, view & edit the pre-upgrade dynamic group.

#4515 has restored tags to be used for filtering, and can successfully be applied to new dynamic groups, but so far all of the groups already setup cause log & display errors.

eg:

```
(
  tags__slug='campus' AND status__slug='active' AND tenant__slug='<tenant>'
)
```

Logs show warnings when NB2 launches:
```
07:33:41.815 WARNING nautobot.extras.models.groups :
  Filter for DynamicGroup "<tenant> Campus" is not valid
```

When attempting to open the dynamic group in GUI receive a Server Error:
```
<class 'KeyError'>

'tag'

Python version: 3.11.6
Nautobot version: 2.0.1
```

**Comment by JimmyKip** [comment]
Hi,

They are associated with dcim.device; and yes they're using tag filters. I can make new groups ok now, but I can't view or edit the existing ones.

**Comment by HanlinMiao** [comment]
Thank you so much for the prompt response.

Can you go to `nbshell` and run this for loop to see if it fixes the issue? I can reproduce the `KeyError` when there is an outdated `tag` filter in my DynamicGroup filter data. This for loop goes through all the DPs and replace `tag` with `tags`.
```
for dp in DynamicGroup.objects.all():
    if "tag" in dp.filter:
        dp.filter["tags"] = dp.filter.pop("tag")
        dp.save()
```

**Comment by JimmyKip** [comment]
Yep, that's perfect - they now load as expected.
