### ISSUE TITLE
View in New UI not working ("viewNewUI is not defined")

### ISSUE THREAD

**Issue by JonathanNathanson** [nautobot/nautobot#4618]
### Environment
* Nautobot version: 2.0.1
* Python version: 3.8.10
* Database platform, version: PSQL 12.16
* Middleware(s):
* 
### Steps to Reproduce
1. Open dashboard or devices page 
2. Click "View in New UI" in footer

### What did you expect to happen?
To see the new UI

### What happened instead?
Nothing, browser console shows error:

VM1270 :1 Uncaught ReferenceError: viewNewUI is not defined
    at HTMLAnchorElement.onclick (VM1270 :1:1)
onclick @ VM1270 :1

**Comment by gsnider2195** [comment]
`viewNewUI` is defined in `nautobot/project-static/js/theme.js`. Did you run `nautobot-server post_upgrade` or `nautobot-server collectstatic` to update your static files after installing/upgrading? If so, you may have a cached version of the theme.js file in your browser. Can you try to reset your browser cache and see if you're still experiencing this?
