### ISSUE TITLE
Broken link for Nautobot installation instructions

### ISSUE THREAD

**Issue by collin-wicker** [nautobot/nautobot#4619]
### Environment
* Nautobot version: Not applicable
* Python version: Not applicable
* Database platform, version: Not applicable
* Middleware(s): Not applicable

### Steps to Reproduce
1. Navigate to https://github.com/nautobot/nautobot
2. Scroll down on page until you see the **Installation** section
3. Click on the "documentation" hyperlink
4. See existing 404 error

### Expected Behavior
Expected to be redirected to a web page explaining Nautobot installation instructions.

### Observed Behavior
Was redirected to a broken link (https://docs.nautobot.com/projects/core/en/stable/installation/) due to the documentation being moved.

**Comment by glennmatthews** [comment]
Thanks for the report! In addressing this, we should also probably correct the links later in README.md to the contributing guide and to the related/community projects, as both of those are also somewhat wrong.
