### ISSUE TITLE
Documentation mentions 1.5 as the LTM release for the 1.x major release

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot#4622]
Nautobot Version: 2.0.1, but all others since LTM was introduced theoretically apply

The [documentation](https://docs.nautobot.com/projects/core/en/v2.0.1/development/core/?h=maintenance#launch-of-maintenance-release-schedule-as-an-example) mentions that 1.5 will be the LTM release for 1.x, where in reality this has become 1.6.

**Comment by Kircheneer** [comment]
I would have quickly updated this myself but I lack the source for [this](https://github.com/nautobot/nautobot/blob/develop/nautobot/docs/media/development/index_release_cadence.jpg) image

**Comment by gsnider2195** [comment]
> I would have quickly updated this myself but I lack the source for [this](https://github.com/nautobot/nautobot/blob/develop/nautobot/docs/media/development/index_release_cadence.jpg) image

The source for the image is [here](https://github.com/nautobot/nautobot/blob/develop/nautobot/docs/media/development/index_release_cadence.drawio)
