### ISSUE TITLE
VRFs Prefix Filter issue

### ISSUE THREAD

**Issue by saman-com** [nautobot/nautobot#4626]
in version 2.0.1

if in VRF section if I click on Prefixes number it will show :

![Screenshot 2023-10-11 070103](https://github.com/nautobot/nautobot/assets/39319461/daf7cf60-6bed-482c-afee-e66db2f63557)

Invalid filters were specified:

    vrf
        Unknown filter field

![Screenshot 2023-10-11 070214](https://github.com/nautobot/nautobot/assets/39319461/e019a907-9ee3-43cf-829d-bff4ef563b24)

**Comment by gsnider2195** [comment]
Thanks for the report! I was able to verify that in 2.0 this filter name should be `vrfs`, not `vrf`
