### ISSUE TITLE
JSON custom field being returned as a `repr()` string when using GraphQL

### ISSUE THREAD

**Issue by jamesharr** [nautobot/nautobot#4627]
### Environment
* Nautobot version (Docker tag too if applicable):
   - v2.0.0b1 (yes, I know I need to upgrade, but this is where I found it)
   - 1.6.1
* Python version: Python 3.10.12
* Database platform, version: `docker.io/bitnami/postgresql:15.3.0-debian-11-r7`
* Middleware(s): Kubernetes / NGINX Ingress

### Steps to Reproduce
1. Create a custom field `test_json`
  - Set type to JSON
  - Associate with `device` (though it can be any object)
2. Restart Nautobot server
3. Create/edit an object (device) with some JSON data in that custom field. For example use the following.
    ```json
    {
      "a-number": 1,
      "a-string": "hello world!",
      "a-null": null,
      "a-list": [5, 6, 7],
      "a-dict": {"foo": "bar"},
      "a-bool1": true,
      "a-bool2": false
    }
    ```
4. View the object via the Rest API, and observe the JSON data being returned:
    ```json
    {
      "id": "7c5cefba-9bb7-4f72-aead-9402f5558ad5",
      ...,
      "custom_fields": {
        "test_json": {
          "a-number": 1,
          "a-string": "hello world!",
          "a-null": null,
          "a-list": [5, 6, 7],
          "a-dict": {
            "foo": "bar"
          },
          "a-bool1": true,
          "a-bool2": false
        }
      }
    }
    ```
5. Use the GraphQL to execute the following query:
    ```graphql
    query {
      devices {
        _custom_field_data
        cf_test_json
      }
    }
    ```
### Expected Behavior

I'd expect the GraphQL to return structured JSON data, such as:

 ```json
      "cf_test_json": {"a-number": 1, "a-string": "hello world!", "a-null": null, "a-list": [5, 6, 7], "a-dict": {"foo": "bar"}, "a-bool1": true, "a-bool2": false}
 ```

### Observed Behavior
Observe that the value returned for cf_test_json is python `repr()`

```json
       "cf_test_json": "{'a-number': 1, 'a-string': 'hello world!', 'a-null': None, 'a-list': [5, 6, 7], 'a-dict': {'foo': 'bar'}, 'a-bool1': True, 'a-bool2': False}"
```

It's also worth noting that the value shown in `_custom_field_data` is actual JSON data, which is what I'd expect.

### References:

- [thread in #nautobot on NTC slack](https://networktocode.slack.com/archives/C01NWPK6WHL/p1696964530853869)
- TY to @joewesch for reproducing the issue in 1.6.1

**Comment by gsnider2195** [comment]
Thanks for the report! Confirmed this is still the behavior in 2.0
