### ISSUE TITLE
Raising Custom Exceptions in Jobs causes billiard.exceptions.WorkerLostError

### ISSUE THREAD

**Issue by rlad78** [nautobot/nautobot#4631]
### Environment
* Nautobot version 2.0.1 (Docker tag: `2.0.1-py3.10`)
* Python version: 3.10.4
* Database platform, version: Postgres 13, Redis 8
* Middleware(s): None

### Steps to Reproduce
1. Create, register, and enable a Job that raises a custom exception. A working example would be:
```py
from nautobot.extras.jobs import Job


class CustomException(BaseException):
    pass


class DemoIssue(Job):
    def run(self) -> str:
        self.logger.info("Job started!")
        raise CustomException("Hello world")
        return ""
```
2. Run the Job
3. Observe the Job Results

### Expected Behavior
The custom exception should be raised and display in the Job Results like any other built-in exception.

### Observed Behavior
An odd and non-descript exception is raised instead, with no traceback:

![Screenshot 2023-10-11 at 11 00 36 AM](https://github.com/nautobot/nautobot/assets/5733291/e0cc8b44-bfd1-45ab-8aba-126629cdc538)

![Screenshot 2023-10-11 at 11 01 15 AM](https://github.com/nautobot/nautobot/assets/5733291/ed2f3e07-7f9c-4c96-adc4-e6b7b1ce22d1)

From the Celery worker's log, we can see a traceback from the `billiard` module:
```
[2023-10-11 14:47:02,653: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: exitcode 0 Job: 51.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.einfo.ExceptionWithTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: exitcode 0 Job: 51.
"""
```

**Comment by glennmatthews** [comment]
Thanks for the report! Is there a specific reason you're inheriting from `BaseException` rather than the more typical `Exception` as base class?

**Comment by rlad78** [comment]
Honestly, a lack of understanding of the difference between the two...which I have now begun to realize is problematic.

> BaseException is the common base class of all exceptions. One of its subclasses, Exception , is the base class of all the non-fatal exceptions. Exceptions which are not subclasses of Exception are not typically handled, because they are used to indicate that the program should terminate.

I tried the Job again with a user-defined exception based on Exception, and it works fine now. Thank you for humoring my issue haha.
