### ISSUE TITLE
Dynamic Tag Generation - Replace Dynamic Groups

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#4634]
### As ...

Austin - Network Automation Engineer

### I want ...

to evaluate the removal of Dynamic Groups in favor of dynamic tags. Dynamic Groups has caused significant slow downs as well in several areas of Nautobot so far where viewing objects with a tag are just part of the generic list views.

### So that ...

We no longer need to use the Dynamic Groups to get the same functionality that we do in tags. When I look at Dynamic Groups, it is putting together groups of objects into one grouping. When I look at Tags, I'm basically getting the same behavior. 

So the thought that I have here is that we look at the set up that is in place around JobHooks and that Jobs can provide filters as well. Can we migrate the functionality of data that is fully dynamic towards the idea of making to close enough to real time dynamic with the use of JobHooks to assign tags to items.

Within this, we may have to allow for a user override as well. I've been thinking through this for two of our plugins specifically that are better suited to use Tags so there can be a manual override rather than a dynamic group controlling everything. That is for Golden Config and Telegraf plugins.

In every instance of Golden Config that I deploy, I'm using tags to control what devices get run within what Job. This allows for instance of a Device being moved or being put in an offline status. I say tags here, because the status field may be used for some other component, such as whether or not to monitor the device. At which point you need to have individual overrides for each plugin that is taking actions rather than the status as a whole.

### I know this is done when...

- I can have tags get applied systematically through a JobHook or similar process.
- That a user can override the tag, and that the tag will not be re-applied until another action is taken.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by lampwins** [comment]
Putting the tag part aside, what you are basically getting at is the (always) dynamic resolution of group membership is problematic in a number of areas and I fully agree with that.

I think we should first look at ways to denormalize the group membership so it can be calculated in the background and lookups are then very fast.

**Comment by gsnider2195** [comment]
Discussed in [design meeting](https://networktocode.atlassian.net/wiki/x/KoBHlg)

**Comment by lampwins** [comment]
We will implement the concept of static groups and refactor the way dynamic groups work in 2.3 which should address the concerns here to the point where the you could do it this way if you wanted to.
