### ISSUE TITLE
Device Redundancy Group creation requires failover strategy when using the API but not when using the GUI.

### ISSUE THREAD

**Issue by nrnvgh** [nautobot/nautobot#4645]
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.3
* Python version: 3.11.6
* Database platform, version: MySQL 8.1.0
* Middleware(s): pynautobot or the browser-based API interface, using API 1.2 or 1.6

### Steps to Reproduce
1. Create a device redundancy group in the UI specifying only Name/Slug and Status. This succeeds.
2. Attempt to create DRG via the API thusly:
```python
    drg = nb.dcim.device_redundancy_groups.create(
        {
            "name": "test-group",
            "slug": "test-group",
            "status": "Active",
        }
    )
```

### Expected Behavior
DRG gets created just like it would in the UI.

### Observed Behavior
pynautobot throws an exception:

```python
pynautobot.core.query.RequestError: The request failed with code 400 Bad Request: {'failover_strategy': ['This field is required.']}
```

The same issue is seen in the browser-based API interface:
```bash
curl -X 'POST' \
  'https://REDACTED/api/dcim/device-redundancy-groups/' \
  -H 'accept: application/json; version=1.6' \
  -H 'Content-Type: application/json' \
  -H 'X-CSRFTOKEN: REDACTED' \
  -d '{
  "name": "test-group",
  "slug": "test-group",
  "status": "Active"
}'
```
![Screenshot 2023-10-13 at 12 22 08 PM](https://github.com/nautobot/nautobot/assets/120611026/334ea9c9-04b6-4ff3-966b-6bd2d8807e2e)

**Comment by gsnider2195** [comment]
Thanks for the report @nrnvgh! This bug was fixed in Nautobot 2.0 in #3722. Please let us know if this bug is preventing you from implementing an integration through the API and we might be able to help you find a workaround.

**Comment by nrnvgh** [comment]
It is, and while Nautobot 2 is on our roadmap, it's still a ways off. Applying the attached patch (which I've only done to the local test instance I run for myself, not the real one which I don't manage) seems to resolve the issue, although I'm not certain it's correct/complete. Just for starters, I don't know if it should have `allow_blank` or `allow_null` parameters as well. Thoughts?

[dcim_api_serializers.patch](https://github.com/nautobot/nautobot/files/12898589/dcim_api_serializers.patch)

**Comment by gsnider2195** [comment]
That field is a blankable CharField so you just need `allow_blank`. This was the [fix](https://github.com/nautobot/nautobot/pull/3722/files#diff-4bbc9a1bf3902cda064d30c4f3a2643010ae123247bbd139f3759fcfddc2000aR646-R650) applied in 2.0:

```py
    failover_strategy = ChoiceField(
        choices=DeviceRedundancyGroupFailoverStrategyChoices,
        allow_blank=True,
        default=DeviceRedundancyGroupFailoverStrategyChoices.FAILOVER_UNSPECIFIED,
    )
```

**Comment by nrnvgh** [comment]
Updated patch; thoughts? And if it looks good, what are the chances this could be backported to 1.6? If not, how would you suggest I proceed?

[4645.patch](https://github.com/nautobot/nautobot/files/12918626/4645.patch)

Not directly related to this report, but I also opened #4649 related to working with redundancy groups. I mentioned this here only because if the fix in this ticket can be backported it would be useful to also have the other backported as well.

**Comment by glennmatthews** [comment]
Looks solid to me as a 1.6 patch. If you'd like to open a PR against `ltm/1.6` we can see it through to completion. Thanks!
