### ISSUE TITLE
Expose Prefix vrf_assignments in GraphQL

### ISSUE THREAD

**Issue by grahamjohnston** [nautobot/nautobot#4650]
### As ...

Austin - Network Automation Engineer

### I want ...

to be able to query a device, it's interfaces and IP addresses and be able to reference a parent prefixes vrf_assignments within GraphQL. Today, I can only access the parent's prefix vrfs in general.

### So that ...

I can help identify which VRF a prefix may be operationally associated to for a given specific device.

### I know this is done when...

the vrf_assignments object is available in GraphQL

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [X] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

I'm unsure, but I don't expect a database or ORM change is necessary.

### External Dependencies

None that I know of.

**Comment by gsnider2195** [comment]
The `Prefix.vrf_assignments` is just the through table for the ManyToManyField for `vrfs`. There are no extra fields on the through table so there shouldn't be any need to access that model. What is the use case?

**Comment by grahamjohnston** [comment]
I feel as though you can close this. I opened it with an incomplete understand of the new ipam model in 2.x and had missed that an interface is now assigned to a vrf.
