### ISSUE TITLE
GraphiQL errors when querying for Interface mode

### ISSUE THREAD

**Issue by pke11y** [nautobot/nautobot#466]
### Environment
* Python version: 3.8.5
* Nautobot version: 1.0.1

### Steps to Reproduce
1. Open GraphiQL interface
2. Enter the following query and execute on demo.nautobot.com
```

{
  devices{
    interfaces{
      name
      mode
    }
  }
}
```

### Expected Behavior
A list of interfaces returned. 
 ```
     {
        "interfaces": [
          {
            "name": "Ethernet1",
            "mode": null
          },
          {
            "name": "Ethernet2",
            "mode": null
          },
          {
            "name": "Ethernet3",
            "mode": null
          },
```

### Observed Behavior
Errors returned for each interface at the top of the results pane. Correct data is actually returned below the errors

```
{
  "errors": [
    {
      "message": "Expected a value of type \"DcimInterfaceModeChoices\" but received: ",
      "path": [
        "devices",
        0,
        "interfaces",
        0,
        "mode"
      ]
    },
    {
      "message": "Expected a value of type \"DcimInterfaceModeChoices\" but received: ",
      "path": [
        "devices",
        0,
        "interfaces",
        1,
        "mode"
      ]
    },
    {
      "message": "Expected a value of type \"DcimInterfaceModeChoices\" but received: ",
      "path": [
        "devices",
        0,
        "interfaces",
        2,
        "mode"
      ]
    },
```

**Comment by jathanism** [comment]
Hmmm it looks as if we've got some more broken typing here. Inspecting the schema shows this emit as type `mode: DcimInterfaceModeChoices`. It seems to want to treat it like an enum.

**Comment by FragmentedPacket** [comment]
This seems to be related to any fields on a model that provide choices, but cannot be null (but has `blank=True`). Role for IPAddresses is similar in this fashion that it raises an error.

I found this issue: https://github.com/graphql-python/graphene-django/issues/474

Making the following change fixes the described issue:

```python
    mode = graphene.Field(graphene.String, source='mode')
```

This appears to show `mode: ""` for interfaces that don't have a mode set.

Another related issue that is old but not closed: https://github.com/graphql-python/graphene-django/issues/1005

The other one that may work to fix this temporarily would be:

```python
class InterfaceType(DjangoObjectType, PathEndpointMixin):
    """Graphql Type Object for Interface model."""

    class Meta:
        model = Interface
        filterset_class = InterfaceFilterSet
        exclude = ["_name"]

    ip_addresses = graphene.List("nautobot.ipam.graphql.types.IPAddressType")

    def resolve_ip_addresses(self, args):
        return self.ip_addresses.all()

    def resolve_mode(interface, info):
      if interface.mode:
        return interface.mode
      return None
```

This one will show it as `mode: null` and doesn't appear to like it if we return `""`.
