### ISSUE TITLE
Installation Guide Typo for RHEL8 + Derivatives

### ISSUE THREAD

**Issue by WTI-Dan** [nautobot/nautobot#4660]
### Environment
* Nautobot version (Docker tag too if applicable):
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. User Guide > Administration > Installation > Installing System Dependencies
2. Install System Packages > RHEL8 + Derivatives
3. Typo dns should be dnf

### Expected Behavior
sudo dnf module install -y nodejs:18/common # Install Node.js 18.x

### Observed Behavior
sudo dns module install -y nodejs:18/common # Install Node.js 18.x
sudo: dns: command not found

**Comment by glennmatthews** [comment]
Thanks for the report! We just fixed this in #4636 and it'll be included in the next release.
