### ISSUE TITLE
Device Primary IP not shown in /api/dcim/devices in 2.0

### ISSUE THREAD

**Issue by travisjohnsonga** [nautobot/nautobot#4666]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.1
* Python version: 3.10
* Database platform, version: pgsql
* Middleware(s): none

### Steps to Reproduce
1. View API for dcim.devices
2. IP Addresses are no longer displayed - but rather the reference information 

### Expected Behavior
IP addresses are shown in device api data

### Observed Behavior
"primary_ip4": {
                "id": "9a19a6dd-d2bb-482d-b9e8-7ba960bb3263",
                "object_type": "ipam.ipaddress",
                "url": "https://al001netboxdev01.us.chs.net/api/ipam/ip-addresses/9a19a6dd-d2bb-482d-b9e8-7ba960bb3263/"
            },

**Comment by glennmatthews** [comment]
This is a part of the general REST API restructuring in 2.0 documented [here](https://docs.nautobot.com/projects/core/en/stable/release-notes/version-2.0/#rest-api-query-depth-parameter-3042) and [here](https://docs.nautobot.com/projects/core/en/stable/user-guide/platform-functionality/rest-api/overview/#depth-query-parameter). You can either "walk" the API to the URL given for the related object (here, `primary_ip4`) to get its details, or, if you're OK with the potential performance impact of querying *all* related objects of the Device in a single request, use the `?depth=1` query parameter to get a more verbose API response.

**Comment by travisjohnsonga** [comment]
Thanks Glenn - I guess I don't see it as much more of a performance impact than having to do multiple queries for data?
