### ISSUE TITLE
Flag away React UI for now

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#4668]
As a Nautobot Admin, I want the the React alpha UI to be entirely disabled so that I am not bothered the build components which take a long time to start up.

I will know this is complete when:
- Change the post_upgrade default so it does not build the UI
- Add a config setting (off by default) to gate the "view in new UI link"

**Comment by Kircheneer** [comment]
As a different question, why does the startup of the container have to rebuild the UI? Couldn't it be built into the container?
