### ISSUE TITLE
500 error page doesn't respect dark mode

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot#4675]
### Environment

* Nautobot version (Docker tag too if applicable): latest
* Python version: 3.11
* Database platform, version: N/A
* Middleware(s):

### Steps to Reproduce

1. Be in dark mode
2. Create a 500 :) 

### Expected Behavior

Be skinned in dark mode

### Observed Behavior

Still skinned in light mode

**Comment by itdependsnetworks** [comment]
Per @glennmatthews

> it does look like the 500.html template doesn’t include the inc/media.html include that adds the base/dark theme CSS.

Should likely do a quick audit to see where else this is happening

**Comment by glennmatthews** [comment]
More specifically, `500.html` doesn't inherit from `base.html` for some reason, whereas other error pages like `40x.html` do inherit from it. Probably fixing up the inheritance of this file would be appropriate as a fix.
