### ISSUE TITLE
Job failed when using RabbitMQ as message broker

### ISSUE THREAD

**Issue by erjac77** [nautobot/nautobot#4678]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.1 (`networktocode/nautobot-dev:2.0.1-py3.11`)
* Python version: 3.11
* Database platform, version: Postgres
* Middleware(s): 
* Plugin(s): `nautobot-secrets-providers[thycotic]==2.0.1`

### Steps to Reproduce
1. Start our dev Nautobot container (and related containers like pg, celery, celery-beat, redis and rabbitmq) via docker-compose (fresh installation).
2. Log in as superuser.
3. Create the required secrets (username + token) and secret group.
4. Add a Git repository using the previously created secret group and try running a dry-run or sync.

### Expected Behavior
The Git repository is synched successfully.

### Observed Behavior
The dry-run/sync failed with the following traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/jobs.py", line 125, in __call__
    change_context = context_class(user=self.user, context_detail=self.class_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/context_managers.py", line 30, in __init__
    raise TypeError("Either user or request must be provided")
TypeError: Either user or request must be provided
```

We tried the same setup with `nautobot==1.6.2` and `nautobot-secrets-providers[thycotic]==1.4.1` and it works as expected.

**Comment by erjac77** [comment]
Just to let you know, I have the same result for every job I try to run.

**Comment by glennmatthews** [comment]
Strange issue! It looks like somehow the task is getting enqueued with a null user. The user *should* be coming in via `request.user` when you submit the job and should be getting rejected outright by the view if `request.user` is none (i.e. unauthenticated user). I haven't been able to reproduce this symptom so far but will continue investigating.

Does it make any difference if you point to a repository that doesn't require a secret (e.g. https://github.com/nautobot/demo-git-datasource), or if you run the job via the REST API instead of via the GUI?

**Comment by glennmatthews** [comment]
Does the JobResult created by the run have an associated "user"? In the `Additional Data` tab of the JobResult, is there a value for `"nautobot_job_user_id"` under the "Job Celery Keyword Arguments"?

**Comment by erjac77** [comment]
@glennmatthews Thanks for your quick reply. Strangely, there no `nautobot_job_user_id` under the "Job Celery Keyword Arguments". But I'm logged in!! Synchronizing with a repository that doesn't require a secret or running the job via the REST API makes no difference. Like you said, really strange issue.

**Comment by glennmatthews** [comment]
Is `nautobot_job_user_id` absent entirely or is it present with a null/empty value? Neither makes sense to me, tbh, as the code seems pretty clear that it's always going to set that value to a user object's PK, but it might be helpful to know.

**Comment by glennmatthews** [comment]
Do you have any non-default/custom Celery configuration by chance? I see you mentioned rabbitmq in the original issue, which isn't part of a "standard" Nautobot deployment.

**Comment by erjac77** [comment]
`nautobot_job_user_id` is absent entirely.

For Celery, we use RabbitMQ as broker, and `NAUTOBOT_CELERY_TASK_SOFT_TIME_LIMIT` and `NAUTOBOT_CELERY_TASK_TIME_LIMIT` are set to 3600.

**Comment by erjac77** [comment]
@glennmatthews Your intuition was right. If I replace RabbitMQ with Redis the job succeeds. I'll investigate further and let you know.

**Comment by erjac77** [comment]
@glennmatthews I tried setting the logging level to `DEBUG` for the Celery Worker, but nothing new there. RabbitMQ logs show this message: `2023-10-23 16:08:52.952851+00:00 [debug] <0.982.0> Deleting auto-delete queue 'bc8f38ca-ad08-3948-9cb2-3fa86229ae78.reply.celery.pidbox' in vhost '/' because its last consumer with tag 'None1' was cancelled`
It's as if the Celery client computed the [Consumer Tag](https://www.rabbitmq.com/consumers.html#consumer-tags) and that value ended up being `None`. The reason, I don't know.

What I can see so far, is that something has changed in Nautobot 2.0 that is giving RabbitMQ a run for its money. But the problem does not seem to be present on branches 1.5.x/1.6.x. I remember seeing RabbitMQ as a use case in the discussion for [replacing RQ with Celery](https://github.com/nautobot/nautobot/issues/223). For our part, we have happily used RabbitMQ with Nautobot since 1.2, mainly for clustering and persistence reasons.

So I'm going to change the title of this issue to reflect my findings in the hope that it will be taken into account. Thanks for your help.

**Comment by lampwins** [comment]
RabbitMQ is not officially supported. We might endeavor to support it in the future, but we will open a targeted issue to do so at that time.
