### ISSUE TITLE
Dynamic Group with Tag-Filter without Member-Device

### ISSUE THREAD

**Issue by gygetho** [nautobot/nautobot#4680]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.1 on virtual machine
* Python version: 3.10.12
* Database platform, version: postgres v14.9
* Middleware(s): none

### Steps to Reproduce
1. all steps are done in GUI
2. create TAG "testtag" with scope Devices
3. make sure no device has this tag applied
4. create a dynamic group with filter based on tag from step 2
5. error occures: Select a valid choice. testtag is not one of the available choices.

6. repeat step1-2
7. make sure a device has applied the testtag
8. create a dynamic group with filter based on tag from step 2
9. everything works fine

### Expected Behavior
to have dynamic groups based on tags even if theres curently no device with this tag

### Observed Behavior
the dynamic group with filter based on tag can only be created if an device with this tag applied already exist

**Comment by glennmatthews** [comment]
Thanks for the report! This may be related to the code changes made in #4322, specifically https://github.com/nautobot/nautobot/pull/4322/files#diff-2b8d45fb821f9852b3de63ce5ce1a14214ba942e34466c386578500b5e42e735R782
