### ISSUE TITLE
NAPALM device detail view functions assume 'Active' as the default status for a device

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot#4681]
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.4/2.0.2
* Python version: n.a.
* Database platform, version: n.a.
* Middleware(s): n.a.

### Steps to Reproduce
1. Have a status other then `Active` on a device
2. Navigate to its detail page
3.

### Expected Behavior

The NAPALM view functions are available.

### Observed Behavior

The NAPALM view functions are unavailable.

### Use Case

When making use of the customization of statuses, you may not want to use `Active` as the active status, but something else (e.g. `Live`)

**Comment by glennmatthews** [comment]
https://github.com/nautobot/nautobot/blob/develop/nautobot/dcim/templates/dcim/device/base.html#L130 is the offending line. This definitely shouldn't be hard-coded; I think it would probably be perfectly fine to just remove this check and let the tabs be available regardless of the device's `status`. If the device isn't reachable, that should be handled by the NAPALM call.
