### ISSUE TITLE
Invalid link to IP Address in an Interface View

### ISSUE THREAD

**Issue by mzbroch** [nautobot/nautobot#4685]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.0
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Create IP Address on an Interface
2. Navigate to the interface view (`dcim/interfaces/9b9d6eb2-3755-4ac3-b341-15694c50de15/?tab=main`)
3. Click on IP Address

### Expected Behavior
Navigates to the Detail View

### Observed Behavior
Navigates to the IP Address **Edit** View

<img width="496" alt="Screenshot 2023-10-23 at 08 51 45" src="https://github.com/nautobot/nautobot/assets/16935122/37d1bac1-b981-4331-a0a7-7d05f7eb7098">

<img width="912" alt="Screenshot 2023-10-23 at 08 53 01" src="https://github.com/nautobot/nautobot/assets/16935122/bd006be4-d6c7-46f4-8a1b-8f108e457979">

**Comment by glennmatthews** [comment]
Looks to have been changed in #2762, specifically https://github.com/nautobot/nautobot/pull/2762/files#diff-021d8b804e061261cd8b357ff540dd4730b04eef1ca56f0247ca38adcf6c0cd1R509.
