### ISSUE TITLE
ChoiceVar not valid in form happenning randomly

### ISSUE THREAD

**Issue by SenReda** [nautobot/nautobot#4688]
### Environment
* Nautobot version :1.5.24
* Python version: 3.10
* Database platform, version: postgres 15.3
* Middleware(s):

### Steps to Reproduce
1. Create a job and add a ChoiceVar in your inputs
2. Open the job and choose an input from the choices you have.
3. Click on "Run"

### Expected Behavior
The job running correctly and using the inputs i selected

### Observed Behavior
The job doesn't run because there is an error in my choiceVar input > "Select a valid choice. ['choice1'] is not one of the available choices"
This error happens randomly at different times. Somtimes it works without any problem and sometimes not.
To make it work, i can do something like, adding another choice in my input, delete it, then run the job again > this make it work sometimes. or i just have to quit the job, and try again a number of times until it works.

**Comment by glennmatthews** [comment]
This sounds a lot like #4222, which is fixed in 1.6.0 and later. Are you able to upgrade?

**Comment by SenReda** [comment]
Yes, i think we can upgrade. thank you for your fast response.
