### ISSUE TITLE
Document custom relationships feature

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#47]
### Change Type
[x] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[x] Configuration parameters
[x] Functionality/features
[x] REST API
[x] Administration/development
[ ] Other

### Proposed Changes

The new custom relationships feature is not yet tested or documented. This should track the work for documentation.

The way I see it, this is an advanced feature and the documentation for it needs to be verbose, and would be better with screenshots and examples. For example, the source/destination filters are easy to get wrong, and after defining them, how should they be tested to make sure they work as intended? I think the `Device to VLANs` example we've been using to describe this would be perfect use-case for how to implement and expand the documentation.

Documentation should include
- [ ] User guide
- [ ] Developer guide

**Comment by glennmatthews** [comment]
Reopening this as incomplete per Jathan's comment on #56:

> This is a great start to documenting this, and I'm happy to merge this as-is, but IMO this is not verbose enough and would be better with screenshots and examples. This is a pretty advanced feature, and the source/destination filters are easy to get wrong. I think the Device to VLANs example we've been using to describe this would be perfect use-case for how to implement and expand the documentation.

**Comment by glennmatthews** [comment]
Re-closing this - additional documentation for this feature will be handled under #86.
