### ISSUE TITLE
Allow bulk editing of interfaces to set VRF in Nautobot 2.x

### ISSUE THREAD

**Issue by grahamjohnston** [nautobot/nautobot#4708]
### As ...

Nelly - Network Engineer

### I want ...

To be able to mass edit a set of interfaces and be able to assign a VRF, as is now possible in Nautobot 2.x

### So that ...

I can do this en masse rather than having to edit a set of interfaces individually.

### I know this is done when...

The VRF field is present on the bulk edit interface page, and it works to let me set or change an assigned VRF.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [X] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

None that I'm aware of.

### External Dependencies

None that I'm aware of.

**Comment by gsnider2195** [comment]
> To be able to mass edit a set of interfaces and be able to assign a VRF, as is now possible in Nautobot 2.x

Can you clarify? Are you asking for a 2.x feature to be implemented in 1.x or something else?

**Comment by glennmatthews** [comment]
I believe the request here is to enhance the Interface bulk-edit form to include a `vrf` field, which it appears to currently be lacking.

**Comment by grahamjohnston** [comment]
Sorry. I'm looking for an enhancement of 2.x that expands the capability of
bulk interface edits to include vrf changes.

**Comment by gsnider2195** [comment]
Got it. Thanks!

**Comment by gsnider2195** [comment]
Resolved by #4957
