### ISSUE TITLE
Documentation Bug in calling GraphQL from restapi

### ISSUE THREAD

**Issue by mroe1234** [nautobot/nautobot#4717]
### Environment
* Nautobot version: v2.0.1
* Python version: 3.11
* Database platform, version: Postgres 13
* Middleware(s): None

The UUID is required not name when calling a saved query.  Further, it might be useful to mention that when using POST to send variables, Nautobot requires the post data to be of the format { variables: { <parameters }}.
### Steps to Reproduce
Wrong Documentation: https://docs.nautobot.com/projects/core/en/stable/user-guide/platform-functionality/graphql/#saved-queries

Right Documentation: https://docs.nautobot.com/projects/core/en/stable/user-guide/feature-guides/graphql/#saving-queries

**Comment by HanlinMiao** [comment]
Closed by #4713
