### ISSUE TITLE
Job Results Page - Use Meta Name Attribute

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#472]
### Environment
* Python version: 3.6.13
* Nautobot version: 1.0.1

### Proposed Functionality

When displaying Job Results we should display the attribute in the Meta as the name of the Job result. The current job display is: `<folder path>/file/class_name`

### Use Case

Allow for friendly names
Allow for customized names (such as many branch sites to filter on the one item)

### Database Changes

None

### External Dependencies

None

**Comment by jedelman8** [comment]
This could also be a configurable option for those that prefer the directory path as the name.  However, I personally agree having a user friendly name is definitely needed.
