### ISSUE TITLE
Dark mode not available in 2.x

### ISSUE THREAD

**Issue by travisjohnsonga** [nautobot/nautobot#4724]
### As ...

Ozzie - Operator

### I want ...

Be able to switch to dark mode again, but in 2.0.1 it's gone

### So that ...

I can view in dark mode again

### I know this is done when...

1.x is used

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by travisjohnsonga** [comment]
Thanks Glenn - 

In 1.x, when I clicked on admin in the top right corner, it had a button to change to dark mode - that is missing now, perhaps it was moved somewhere else to toggle between light and dark.

Currently on 2.0.1

**Comment by glennmatthews** [comment]
The link is in the page footer:

![image](https://github.com/nautobot/nautobot/assets/5603551/2fef1684-56c1-48d6-b42d-a5f2cdb8edce)

**Comment by travisjohnsonga** [comment]
Thank you - I completely missed that
