### ISSUE TITLE
Add support for plugins to be able to leverage `get_return_url`

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#473]
### Environment
* Python version: 3.6+
* Nautobot version: 1.0.1

### Proposed Functionality

Plugins should be able to take advantage of the full suite of primitives & generics available in the Nautobot core. While many have been added recently, it appears we may have overlooked [`nautobot.utilities.views.GetReturnURLMixin.get_return_url()`](https://github.com/nautobot/nautobot/blob/develop/nautobot/utilities/views.py#L127), which does not consider the `plugins` namespace:

```python
        # Attempt to dynamically resolve the list view for the object
        if hasattr(self, "queryset"):
            model_opts = self.queryset.model._meta
            try:
                return reverse(f"{model_opts.app_label}:{model_opts.model_name}_list")
            except NoReverseMatch:
                pass

        # If all else fails, return home. Ideally this should never happen.
        return reverse("home")
```

This particular code tends get exercised when doing a bulk import. The list view that results from there confirming the object imports has two buttons for "Import more" and "View All". The view all button is supposed to link back to the list view if it can resolve it (see above), otherwise it falls back to "home" view. In the case of plugins at this time, this button will always fallback to "home".

### Use Case

Enabling plugin authors to take advantage of all primitives and generics.

### Database Changes

None

### External Dependencies

None

**Comment by smk4664** [comment]
Given #474 I think this should be filed as a bug, as it causes undesirable UX on officially blessed uses of the Nautobot Generics in Plugins.

**Comment by smk4664** [comment]
Also, there is a workaround for plugins to use default_return_url on the bulk import or object edit views.

**Comment by smk4664** [comment]
You can assign me, working on integration tests for this.

**Comment by glennmatthews** [comment]
Done, thank you!
