### ISSUE TITLE
RestAPI not allign with Graphql output

### ISSUE THREAD

**Issue by gygetho** [nautobot/nautobot#4742]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.1 on vm
* Python version: 3.10.12
* Database platform, version: Postgres, 14.9
* Middleware(s): none

### Steps to Reproduce
1. Make a GraphQL querie:
 query ($device_id: [String]) {
  interfaces(device_id: $device_id) {
    media_type: type
    switchport_mode: mode
  }
}

2.. Use the value of media_type and switchport_mode to update an interface via RestAPI
3. an value error occures. A_1000BASE_T and TAGGED_ALL are not valid
4. postprocess the querie and change A_1000BASE_T to 1000base-t and TAGGED_ALL to tagged_all
5. with step 4 in place it works

### Expected Behavior
graphql querie output aligns with RestAPI parameter, or having "type" in graphql with subfield "value"

### Observed Behavior
Graphql output don't align with expected API params

**Comment by glennmatthews** [comment]
Unfortunately `1000base-t` is not a valid value for an enum in GraphQL, hence the prepended `A_` and replacement of `-` with `_`.

**Comment by gygetho** [comment]
@glennmatthews so, but then i have at least the possibility to make a generic post-processing if a "-" is in the value.. Prepend A_ and replace - with _. thanks a lot!

**Comment by glennmatthews** [comment]
More specifically, values can't start with digits, and the tooling "fixes" that by prepending `A_` in that specific case.
