### ISSUE TITLE
AWS S3 Backend not possible when Public Access is blocked

### ISSUE THREAD

**Issue by CameronEx** [nautobot/nautobot#4747]
### Issue Summary
When attempting to use AWS S3 for static file storage, if a bucket is **not** set to public, some resources cannot be accessed. They return HTTP403 due to an invalid timestamp appended to the request for the resource.

Our environment has public access blocked at an organisation level, in-line with the [AWS CIS benchmarks](https://docs.aws.amazon.com/securityhub/latest/userguide/s3-controls.html#s3-1). We do not desire to change this.

### Environment
* Nautobot version (Docker tag too if applicable): v2.0.3
* Python version: 3.10.12
* Database platform, version: AWS RDS Aurora Postgresql 15.3
* Middleware(s): Cloudflare access

### Steps to Reproduce
1. Create S3 bucket with all recommended settings, except public access and public-read ACL. Ideally, with the above organisation-level control applied.
2. modify nautobot_configuration.py to utilise Django S3 backend.
3. Create s3 bucket without public access
4. `nautobot-server collectstatic`
5. Browse to nautobot front-end

### Expected Behavior
Nautobot application should load and be usable.

The request should include a valid timestamp, and a HTTP 200 should be received with the content of the requested resource.

### Observed Behavior
A version number is appended to the request, preventing S3 from recognising the timestamp:

**Request:**
`https://*redact*.s3.amazonaws.com/css/base.css\?AWSAccessKeyId\=*redact*\&Signature\=*redact*\&x-amz-security-token\=*redact*\&Expires\=1698958450\?v2.0.3`

**Response:**
```
<Error><Code>AccessDenied</Code><Message>Invalid date (should be seconds since epoch): 1698958450?v2.0.3</Message><RequestId>*redact*</RequestId><HostId>*redact*</HostId></Error>%
```
The error tells us the timestamp is being interpreted as `1698958450?v2.0.3` where `?v2.0.3` should not be included.

This appears to be caused by the appending of the version numbers [here](https://github.com/nautobot/nautobot/blob/fd7cab05b69de1beb2eab2a72b00ad9c95a986ce/nautobot/core/templates/inc/media.html#L27), and does not happen for all resources. For example, the following resource is loaded without issue:
`https://*expires*.s3.amazonaws.com/bootstrap-3.4.1-dist/css/bootstrap.min.css?AWSAccessKeyId=*redact*&Signature=*redact*&x-amz-security-token=*redact*&Expires=1698959075`

**Comment by CameronEx** [comment]
There are multiple instances where this occurs. A non-exhaustive list:
* [forms.js](https://github.com/nautobot/nautobot/blob/fd7cab05b69de1beb2eab2a72b00ad9c95a986ce/nautobot/core/templates/inc/javascript.html#L17C31-L17C31)
* [dark.css](https://github.com/nautobot/nautobot/blob/fd7cab05b69de1beb2eab2a72b00ad9c95a986ce/nautobot/core/templates/inc/media.html#L24)
* [base.css](https://github.com/nautobot/nautobot/blob/fd7cab05b69de1beb2eab2a72b00ad9c95a986ce/nautobot/core/templates/inc/media.html#L27)

Modifying the following appears to move past the issue:
**From:** `<script src="{% static 'js/forms.js' %}?v{{ settings.VERSION }}"`
**To:** `<script src="{% static 'js/forms.js' %}&v{{ settings.VERSION }}"`

Where the `?v` is changed to `&v`. I am not sure how this would effect more 'normal' deployments.

**Comment by gsnider2195** [comment]
Thank you for the report! It looks like appending the query parameters needs to be a little bit smarter.

**Comment by CameronEx** [comment]
@gsnider2195 yep. After performing the hand modifications to the aforementioned files, I also note the .woff files being loaded in by the CSS files aren't being signed either.
![image](https://github.com/nautobot/nautobot/assets/18748269/31735dc8-e269-4f65-a064-f8d91bbc6fb1)

I followed one back to this line:
```
@font-face{font-family:"Material Design Icons";src:url("../fonts/materialdesignicons-webfont.eot?v=6.5.95");
```
in file `static/materialdesignicons-6.5.95/css/materialdesignicons.min.css`. 

This appears to be the only other content having issues.
