### ISSUE TITLE
Consistently use the nautobot.apps module for the Developer Guide

### ISSUE THREAD

**Issue by cardoe** [nautobot/nautobot#4759]
So this is a subjective issue but I think it would help folks approach development of jobs and apps a little bit easier by making the usage of `nautobot.apps` consistent in the documentation.

So if you go to https://docs.nautobot.com/projects/core/en/latest/development/ today, you'll be presented with three categories:
- Jobs Developer Guide
- App Developer Guide
- Core Developer Guide

In Nautobot 1.5.2 you guys introduced the `nautobot.apps` module that re-exports a number of surfaces which is great. But then the docs covering registering jobs in Nautobot 2.0.0 mention using `nautobot.core.celery.register_jobs` when it should use `nautobot.apps.jobs.register_jobs`.

The non-`nautobot.apps` module should just be reserved for the Core Developer Guide.

Ultimately you could have plugin authors be able to lint their code to ensure it only uses `nautobot.apps` so they know they would have a stable API surface.

**Comment by cardoe** [comment]
I believe the label should really be type:documentation

**Comment by gsnider2195** [comment]
Appears to be a duplicate of #4460

**Comment by cardoe** [comment]
Good point @gsnider2195. I'll close this one.
