### ISSUE TITLE
Configuration Context not applied based on nested Tenant Groups

### ISSUE THREAD

**Issue by MeganerdDev** [nautobot/nautobot#4768]
### Environment
* Nautobot version (Docker tag too if applicable): v2.0.4b1
* Python version: 3.11
* Database platform, version: PG15
* Middleware(s): N/A

### Steps to Reproduce
1. Create nested Tenant Groups with test configuration context
2. Put an object (device) as a Tenant which is a member of a nested Tenant Group
3. Open the `Config Context` tab, observe the contents of `Rendered Context` and `Source Contexts` widget

### Expected Behavior
To see the configuration context applied in `Rendered Context` and also `Source Contexts` as a source for context

### Observed Behavior
The configuration context is not applied

### Notes
- Similar to #3432

**Comment by vladanmilosevic73** [comment]
Thank you @MeganerdDev I had this on the list for this week, but chaos took over. I appreciate it.

**Comment by gsnider2195** [comment]
@MeganerdDev Does this work for the immediate TenantGroup, just not the ancestors?

**Comment by vladanmilosevic73** [comment]
@gsnider2195 it works for immediate tenant groups, only nested are the problem

**Comment by glennmatthews** [comment]
May be a consequence of the switch from `django-mptt` to `django-tree-queries` for the TenantGroup model - sounds similar to #4388, which was fixed for Locations by #4417.
