### ISSUE TITLE
`nautobot.utilities.filters.BaseFilterSet.FILTER_DEFAULTS` does not allow `models.TextField` to use multi-value filtering

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#477]
### Environment
* Python version: 3.9
* Nautobot version: 1.0.1

### Steps to Reproduce
1. Create a model with a `models.TextField`
2. Create a filterset that exposes this field
3. Attempt to filter this field with multiple values

### Expected Behavior
The filterset should implement the standard `MultiValueCharFilter` filter class capabilities, allowing for multi-value search using an `OR` condition.

### Observed Behavior
The field only supports single-value search.

This is because `nautobot.utilities.filters.BaseFilterSet.FILTER_DEFAULTS` does not update the `filter_class` to use `MultiValueCharFilter`.

**Comment by glennmatthews** [comment]
Should be a pretty straightforward change to `FILTER_DEFAULTS`. I don't *think* this will impact the REST API, though it may impact FilterForms for the affected fields?
