### ISSUE TITLE
Update postgres install docs to explicitly set encoding

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#4778]
### Proposed Changes

Update any docs where we create the nautobot database to include the supported encoding utf8

```
CREATE DATABASE nautobot WITH ENCODING 'UTF8' LC_COLLATE='en_US.utf8' LC_CTYPE='en_US.utf8';
```

### Justification

To prevent postgres from guessing an unsupported encoding (recently saw this with `SQL_ASCII`)

**Comment by glennmatthews** [comment]
Had a second report of this issue recently on slack. Would be good to prioritize this and identify whether something's changed in Postgres to make this happen more frequently of late?

**Comment by cmong-nextech** [comment]
Chiming in that I was the source of Glenn's comment here.
Feel free to reach out if you want/need more info. I'm happy to bumble my way through things to act helpful.

**Comment by gsnider2195** [comment]
> Had a second report of this issue recently on slack. Would be good to prioritize this and identify whether something's changed in Postgres to make this happen more frequently of late?

It could be due to using minimal installs of operating systems without generating a proper locale. This database was initialized with `LC_ALL=C`:

```
~ $ initdb -D /var/lib/postgresql/data/
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".
```

**Comment by gsnider2195** [comment]
This isn't as simple as specifying the encoding on database creation. If the encoding doesn't match the template database you'll get an error. I think we need to add a section the troubleshooting doc instead.
