### ISSUE TITLE
Support getting custom field choices ID in GraphQL

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#478]
### Environment
* Python version: 3.6.8
* Nautobot version: 1.0.1

### Proposed Functionality
Add support to query custom field choice ID via GraphQL, getting similar information to REST API endpoint `api/extras/custom-field-choices/`. So I could do something like this pseudo-code:
```
{
  devices {
    custom_field_choices {
      field(name: $my_custom_field) {
        id
      }
    }
  }
}
```

### Use Case
Custom fields are used to extend core functionality and save data not possible in core models. These can be used in interaction with other systems. We have a custom field we use as synchronization point between multiple systems. One of our teams is downloading assets data from Netbox v2.9.9, taking this custom field and comparing to data in other system based on it. They are using the ID for it. With Nautobot REST API this requires another call to `api/extras/custom-field-choices/` to get the UUID as string in the custom field can change and REST API is returning only values (strings), not the UUID itself. Being able to get this information in single call via GraphQL would be very helpful.

### Database Changes
None

### External Dependencies
None

**Comment by jathanism** [comment]
Hi @Thetacz, thanks for the suggestion! 

We're currently unable to do nested filters right now. In this context "nested" being "anything other than the top-level object". 

(Blocked by #248)

**Comment by jedelman8** [comment]
Hi @Thetacz! Would you be able to include an actual real workflow that you're currently using to make sure we're understanding this giving an example of the CFs too? Please include actual GraphQL queries (and responses) that are possible today along with the REST API  (and response).  Thanks.

**Comment by glennmatthews** [comment]
Coming in 1.2 via #886.
