### ISSUE TITLE
REST API Error creating a rack: rack_group required, but not required in UI or ORM

### ISSUE THREAD

**Issue by Tibo-nauto** [nautobot/nautobot#4790]
Hi, 

I am using Nautobot v2.0.3 with pynautobot v2.0.1.

When creating a rack via pynautobot, the error message :
`pynautobot.core.query.RequestError: The request failed with code 400 Bad Request: {'rack_group': ['This field is required.']}` appears.

even if we add the rack_group field, leaving it empty. the request is unsuccessful :
`pynautobot.core.query.RequestError: The request failed with code 400 Bad Request: {'rack_group': ['Related objects must be referenced by ID or by dictionary of attributes. Received an unrecognized value: null']}` 

The rack_group field is not mandatory in the documentation.

Regards,

**Comment by pszulczewski** [comment]
I have moved the issue to nautobot as it's a bug in the core.
