### ISSUE TITLE
Regression - Dynamic filter form population can alter presentation of ChoiceFields elsewhere in the UI

### ISSUE THREAD

**Issue by grahamjohnston** [nautobot/nautobot#4791]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.3

### Steps to Reproduce
1. Log in to Nautobot
2. In one tab, open the /dcim/devices/ list view, open the Filter modal, and switch to the Advanced tab.
3. In another browser tab, open the "run" view for a Job that defines a ChoiceVar. Observe that the ChoiceVar is correctly represented as a single-value Select2 widget in the UI.
4. In the first tab, in the Filter modal, select "Rack Face" in the first column, then "exact" in the second column.
5. Refresh the second tab.

### Expected Behavior
No change on page refresh

### Observed Behavior
The `ChoiceVar` now gets incorrectly rendered as a multi-value Select2 widget.

There is a belief that the issue lies here: https://github.com/nautobot/nautobot/blob/develop/nautobot/core/utils/filtering.py#L152-L155 - compare against https://github.com/nautobot/nautobot/blob/ltm-1.6/nautobot/utilities/utils.py#L857-L936 and specifically https://github.com/nautobot/nautobot/pull/4223/files#diff-1163f5bad3157eeb8af809244f6b84ad3b27580d2ba6ba4907e4c32525025a2c

**Comment by joewesch** [comment]
Assumed regression of #4222
