### ISSUE TITLE
Add InterfaceRedundancyGroupAssociation (and priority) to GraphQL

### ISSUE THREAD

**Issue by milan2655** [nautobot/nautobot#4796]
### As ...

Ozzie - Operator

### I want ...

enhance the graphql schema, because `interface priority` is not exposed via graphql on the Interface Redundancy Group Association.

### So that ...

when `interface priority` is exposed via graphql , this value can be used in jinja2 templates.

### I know this is done when...

graphql is executed and the `interface priority` is missing.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by glennmatthews** [comment]
Thanks for the report! Indeed, we need a pattern for exposing all of the various custom "through" tables in GraphQL:

- InterfaceRedundancyGroupAssociation
- IPAddressToInterface
- VRFDeviceAssignment
- VRFPrefixAssignment

**Comment by milan2655** [comment]
without exposing `priority` value it is no possible to make intended config for a redundant interface.

**Comment by lampwins** [comment]
Extending my thoughts from #4797, this is another good example of feature sets that make sense for these M2M through models.

**Comment by lampwins** [comment]
We will increase the scope of this to include all M2M through models to the schema.

**Comment by glennmatthews** [comment]
Added for 2.1 by #4861
