### ISSUE TITLE
Re-Skin - Recommend menu items to be non-bolded font

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#4808]
### As ...

Ozzie - Operator

### I want ...

To have a less bulky menu font on the reskin. The left navigation such as Floor Plan Maps are too tight.

![Screenshot 2023-11-15 at 10 44 29](https://github.com/nautobot/nautobot/assets/22228848/404a9936-f16d-4b79-a4bb-231b24852bb7)

### So that ...

Things look a bit better.

### I know this is done when...

There is a bit more space between the buttons and the menu item.

Maybe not a font bold change, but add a bit more space.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by glennmatthews** [comment]
Implemented by #4859.
