### ISSUE TITLE
Sidebar sub menus not visible in DarkMode

### ISSUE THREAD

**Issue by timizuoebideri1** [nautobot/nautobot#4816]
### Environment
* Nautobot version (Docker tag too if applicable): 2.1.0b1
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. 
2.
3.
![Screenshot 2023-11-16 at 2 19 32 PM](https://github.com/nautobot/nautobot/assets/94907097/fd2fede4-8078-4ea4-80e5-8b5e2a0e0fb3)

**Comment by glennmatthews** [comment]
Fixed by #4818.
