### ISSUE TITLE
Cluster missing in Device bulk edit parameters

### ISSUE THREAD

**Issue by martin-networker** [nautobot/nautobot#4817]
### As ...

Ozzie - Operator

### I want ...

To be able to change Cluster parameter along with other Device parameters during one bulk update.

### So that ...

Cluster parameter along with other Device parameters during one bulk update instead of changing/clearing Cluster parameter for every Device.

### I know this is done when...

In our case a lots of Devices needed to be moved from Site A to Site B. Site is one of parameters which can be changed in bulk update but this change ended with an error as those devices were assigned to a Cluster which is still on Site A.
I have advised to our Data Center Management team that they should first go to the each Cluster, unassigned those Devices and then change the Site parameter. It would be great if we could set Cluster to null and change Site in one bulk edit.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [X] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by david-kn** [comment]
Hi, any update here? Some teams working with us tend to time to time hit this issue... It would ease the flow if it would be possible update in a single step (incl. in device bulk edit).
