### ISSUE TITLE
Not able to populate "Assignment" Field in v2.x

### ISSUE THREAD

**Issue by virtualpetey** [nautobot/nautobot#4819]
### Environment
Nautobot version 2.0.3
Python version 3.11
Database Postgresql version 14.9

### Steps to Reproduce
1. Navigate to any IP Address page.
2. Notice that there is a field on that page called "Assignment", and that it is empty.
3. Click "Edit" button.
4. Notice there are no options to add an assignment for a device and interface to that IP Address.
5. Navigate to any device page.
6. Click "Interfaces" tab.
7. Click "Edit" button.
8. Assign IP Address to that interface.
9. Click "Update" button.
10. Navigate back to the Device tab.
11. Click "Edit" button.
12. Assign Primary IP Address.
13. Click "Update" button.
14. Click the link for the Primary IP Address.
15. Notice that the Assignment field is still empty.

### Expected Behavior
I expected to see options to add device and interface at the IP Address edit page, as well as a checkmark to make it primary for the device. 

Or, alternately, be able to assign an IP Address to a device interface and make it primary for the device, with the "Assignment" field populating on the respective IP Address page automatically.

### Observed Behavior
No options were shown in the edit page, and any workarounds, like setting the primary IP on the device page, were not able to populate the "Assignment" field on the IP Address page.

**Comment by glennmatthews** [comment]
See https://github.com/nautobot/nautobot/blob/develop/nautobot/ipam/templates/ipam/ipaddress.html#L98 and also https://github.com/nautobot/nautobot/blob/develop/nautobot/ipam/templates/ipam/ipaddress.html#L109 - we had these as TODO comments but didn't get back around to fixing them yet.

**Comment by lampwins** [comment]
Since the 80% use case will be single assignments, let's show the value when there is a single assignment. When there are multiple, show the count, and that is a link to the tab for details.
