### ISSUE TITLE
Enable Download of Export Template Results Via API

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot#4820]
### As ...

Nelly - Network Engineer

### I want ...

The capability to download the generated results of an Export Template formatted file via the API.

### So that ...

I'm able to programmatically retrieve a pre-formatted list of object information without having to go into the UI.

### I know this is done when...

I'm able to query the API and download the results of a preconfigured Export Template.

### Optional - Feature groups this request pertains to.

- [x] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

I don't think this should require database changes.

**Comment by jdrew82** [comment]
Similar to FR https://github.com/nautobot/nautobot/issues/2225

**Comment by lampwins** [comment]
2.1 moves csv and export templates to a system job. We will use this story to support retrieval of those files over the jobs API.

**Comment by glennmatthews** [comment]
Implemented for 2.1 by #4860
