### ISSUE TITLE
Documentation contains a description of the `invalidate all` command although the command was removed in 2.x

### ISSUE THREAD

**Issue by ubajze** [nautobot/nautobot#4831]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.4
* Python version: 3.11.6
* Database platform, version: PostgreSQL 15
* Middleware(s): /

### Steps to Reproduce
1. The command `invalidate all` is described here: https://docs.nautobot.com/projects/core/en/v1.4.7/additional-features/caching/#invalidating-cached-data, although the command no longer exists:
```
$ nautobot-server invalidate all
12:09:30.266 ERROR   nautobot.core.apps :
  Error in link construction for Notes: Reverse for 'note_list' not found. 'note_list' is not a valid view function or pattern name.
12:09:30.266 ERROR   nautobot.core.apps :
  Error in link construction for Notes: Reverse for 'note_list' not found. 'note_list' is not a valid view function or pattern name.
Unknown command: 'invalidate'. Did you mean validate_models?
Type 'nautobot-server help' for usage.
```

### Expected Behavior
Remove the documentation or add the command.

### Observed Behavior
The documentation is still present for the command that doesn't exist.

**Comment by timizuoebideri1** [comment]
This command does not appear in the documents for v2.x.x, and the link to the docs provided is for v1.4.7.

**Comment by ubajze** [comment]
Oh, @timizuoebideri1 you are right. For some reason, I thought the doc version was in the upper right corner. Not enough ☕ , I guess :). I am closing the issue.

![image](https://github.com/nautobot/nautobot/assets/6861762/8f9eb241-b1ca-41a1-b875-f455f86e7cde)
