### ISSUE TITLE
Disabled text input forms too dark after 2.1 reskin

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#4835]
### Environment
* Nautobot version (Docker tag too if applicable): 2.1.0b1
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Go to the jobs list view
2. Edit any job
3. Observe the disabled text input forms

### Expected Behavior

They look like disabled text input forms and don't clash with the color scheme

### Observed Behavior

They're too dark, on dark mode they're the same color as the background.

![image](https://github.com/nautobot/nautobot/assets/75227981/d6d2a8c2-2e6e-4011-ad61-5d07bc1a1dd3)

![image](https://github.com/nautobot/nautobot/assets/75227981/48d47908-1ede-4c90-a9b8-236b33665426)

**Comment by glennmatthews** [comment]
Fixed by #4900.
