### ISSUE TITLE
Computed fields not return by GraphQL query

### ISSUE THREAD

**Issue by atcrowe17** [nautobot/nautobot#4851]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.3
* Python version: 3.10.12
* Database platform, version: postgres, 14.9
* Middleware(s):

### Steps to Reproduce
1. Upgraded from Nautobot 1.5. to 2.0.3
2. Created new computed field
{% if obj.type == "xgs-pon" %}
olt-{{ obj.mac_address }}
{% endif %}
4. Attempted GraphQL for new and pre-upgrade computed fields from the web interface and with pynautobot. 

Computed field key:value is returned

Received this error after a query from the web interface:
“CustomFieldModel.get_computed_field() got an unexpected keyword argument ‘slug’”

**Comment by atcrowe17** [comment]
Tested on a fresh install of v2.0.4. Get the same error message.

**Comment by glennmatthews** [comment]
Confirmed, incorrect code is [here](https://github.com/nautobot/nautobot/blob/develop/nautobot/core/graphql/generators.py#L119).
