### ISSUE TITLE
`post_upgrade` fails after an app is uninstalled and `migrate zero` for the affected app

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot#4862]
### Environment
* Nautobot version (Docker tag too if applicable): v2 
* Python version: 3.11
* Database platform, version: pg
* Middleware(s):

### Steps to Reproduce
1. Install an app that provides models based on `PrimaryModel`
2. Create some instances
3. Uninstall app
4. `migrate zero` for the app
5. `nautobot-server post_upgrade`

### Expected Behavior
The post_upgrade commands succeeds as expected

### Observed Behavior
Post upgrade calls `remove_stale_contenttypes` and fails to remove contenttypes due to [on_delete=models.PROTECT](https://github.com/nautobot/nautobot/blob/e28a4d264861a5c31f746fd4cf7631833b30cdfe/nautobot/extras/models/change_logging.py#L87) on the ObjectChanged model.

**Comment by glennmatthews** [comment]
implemented for 2.1 by #4863.
