### ISSUE TITLE
Nautobot API Issue: Multiple Prefix Query Returns a Single Prefix

### ISSUE THREAD

**Issue by gbs098** [nautobot/nautobot#4891]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.5
* Python version:3.11.6
* Database platform, version: PostgreSQL 15.5
* Middleware(s):

### Steps to Reproduce
1.Send a GET request to the Nautobot API to retrieve multiple IP prefixes using the following format:
```
GET /api/ipam/prefixes/?prefix=10.112.56.0%2F25&prefix=10.112.56.128%2F28&prefix=10.112.56.192%2F29
```
2. Tried from nautobot web
3. Go to the section ipam->prefixes
4.In this section, locate and click on the 'Advanced Filter' tab.
In the advanced filter, enter the following prefixes to filter the data:
After entering the prefixes, submit the filter/search request.

### Expected Behavior
The API should return all requested prefixes (10.112.56.0/25, 10.112.56.128/28, and 10.112.56.192/29).

### Observed Behavior
The API only returns one prefix (e.g., 10.112.56.0/25) instead of all the specified prefixes.

**Comment by glennmatthews** [comment]
Looks like the `PrefixFilterSet.prefix` filter (and several others on this FilterSet) are defined as a `CharFilter` rather than a `MultiValueCharFilter`. See also #1730.

**Comment by gsnider2195** [comment]
There are only 5 filters that are still single value CharFilters. Lets go ahead and fix those as part of this

`PrefixFilterSet.prefix`
`PrefixFilterSet.within`
`PrefixFilterSet.within_include`
`PrefixFilterSet.contains`
`IPAddressFilterSet.prefix`

**Comment by itdependsnetworks** [comment]
Is there concrete logic that we can add to pylint-nautobot to find these?
