### ISSUE TITLE
Enhancements to External Integration Model

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#4895]
As a Network Automation Engineer, I want jinja2 template support and additional concrete fields on the External Integration Model, so that I can more effectively use this new model.

Add fields:
- HTTP Method: choice field (GET, POST, PATCH, PUT, DELETE), not required
- Headers: json field, not required
- CA File Path: char field, not required

We can hide these under an "advanced accordion" in the form.

Add support for templating in the URL, headers, and extra config fields. Provide a method on the model that users can call to render the model instance with user provided template data.

**Comment by glennmatthews** [comment]
Implemented by #4929.
