### ISSUE TITLE
Update screenshots in README and docs to reflect UI changes

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#4897]
6 GIFs in the readme. I think @bryanculver did these originally.

Need to also go through the docs.

**Comment by bryanculver** [comment]
> 6 GIFs in the readme. I think @bryanculver did these originally.
> 
> Need to also go through the docs.

https://github.com/nautobot/nautobot/pull/2973

**Comment by glennmatthews** [comment]
@zackt25 has agreed to handle the GIF updates again - thanks! We'll need to handle the static screenshots in the docs.

**Comment by zackt25** [comment]
@bryanculver @lampwins @glennmatthews am I doing this on the develop branch or next branch?

**Comment by lampwins** [comment]
@zackt25 next, please. Thanks again!

**Comment by glennmatthews** [comment]
Implemented through #4958 and #5003.
