### ISSUE TITLE
Count of VLANs is incorrect when displaying vlan_groups

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#490]
### Environment
* Python version:
* Nautobot version: 4aa3f3706287 (v1.0.1)

### Steps to Reproduce
1. Add non concurrent VLANs to a vlan Group
2. display the vlan group

### Expected Behavior
The "VLANs" count should match the vlans in this group

### Observed Behavior
The count ist higher that the ammount of vlans defined in Nautobot

I argue that the lines showing "VLANs avaliable" will be counted as VLANs too

![Screenshot 2021-05-26 094827](https://user-images.githubusercontent.com/8406301/119622783-c25f3500-be07-11eb-88c1-27ff595f4510.jpg)

**Comment by scetron** [comment]
@glennmatthews if this is done with review, I can take this one

**Comment by glennmatthews** [comment]
Thanks!
