### ISSUE TITLE
`location_hierarchy` inc template renders slowly

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot#4917]
### Environment
* Nautobot version: 1.6.6
* Python version: 3.8
* Database platform, version: PostgresQL version 16
* Middleware(s): -

### Steps to Reproduce
1. Have a big enough location hierarchy with lots of layers (regions + normal locations
2. Load for example the device detail page
3.

### Expected Behavior

The page loads reasonably quickly.

### Observed Behavior

The page takes 25s to load.

**Comment by glennmatthews** [comment]
Fixed for 1.6 by #4918 - as mentioned in https://github.com/nautobot/nautobot/pull/4918#discussion_r1419547034 it would be good to forward-port part of the fix to `develop` for 2.x as well.
