### ISSUE TITLE
Support for JSONField in Nautobot Jobs

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot#4926]
### As ...

P.D. - Plugin Developer

### I want ...

the ability to have a JSON field as a job input

### So that ...

I can pass JSON data to my job

### I know this is done when...

- Pass in valid JSON and inside the job I can interact with the serialized data

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- None

### External Dependencies

- None

**Comment by glennmatthews** [comment]
Implemented for 2.1 by #4927.
