### ISSUE TITLE
Performance issues sorting regions by site count with a high number of regions

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot#4941]
### Environment
* Nautobot version: 1.6.6
* Python version: 3.8
* Database platform, version: PostgresQL 13+16
* Middleware(s): -

### Steps to Reproduce
1. Have a high number of regions (~20.000) with nesting/tree depth of 3 layers
2. Navigate to the region table and sort by number of sites
3. Wait

### Expected Behavior

The page loads in a reasonable amount of time. 

### Observed Behavior

The page takes >60s to load.

### Observations

The performance problems are caused by this query alone (note that omitting the custom field filter doesn't change the performance issues):

```
SELECT "dcim_region"."id",
       "dcim_region"."created",
       "dcim_region"."last_updated",
       "dcim_region"."_custom_field_data",
       "dcim_region"."parent_id",
       "dcim_region"."name",
       "dcim_region"."slug",
       "dcim_region"."description",
       "dcim_region"."lft",
       "dcim_region"."rght",
       "dcim_region"."tree_id",
       "dcim_region"."level",
       (
        SELECT count
          FROM (
                SELECT U0."id"
                  FROM "dcim_site" U0
                 INNER JOIN "dcim_region" U1
                    ON (U0."region_id" = U1."id")
                 WHERE (U1."lft" >= "dcim_region"."lft" AND U1."lft" <= "dcim_region"."rght" AND U1."tree_id" = "dcim_region"."tree_id")
               ) _count
       ) AS "site_count"
  FROM "dcim_region"
 WHERE ("dcim_region"."_custom_field_data" -> 'Location Type') = '"Campus"'
 ORDER BY "site_count" ASC
 LIMIT 50
```

If I naively re-create this query myself, I get to the following result:
```
In [15]: list(Region.objects.annotate(count_site=Count("sites")).order_by("-count_site")[0:50])
SELECT "dcim_region"."id",
       "dcim_region"."created",
       "dcim_region"."last_updated",
       "dcim_region"."_custom_field_data",
       "dcim_region"."parent_id",
       "dcim_region"."name",
       "dcim_region"."slug",
       "dcim_region"."description",
       "dcim_region"."lft",
       "dcim_region"."rght",
       "dcim_region"."tree_id",
       "dcim_region"."level",
       COUNT("dcim_site"."id") AS "count_site"
  FROM "dcim_region"
  LEFT OUTER JOIN "dcim_site"
    ON ("dcim_region"."id" = "dcim_site"."region_id")
 GROUP BY "dcim_region"."id"
 ORDER BY "count_site" DESC
 LIMIT 50

Execution time: 0.128422s [Database: default]
```

### Things I have tried

I tried removing the `name` field from the displayed fields on the table, as I saw that it is MPTT-specific code [here](https://github.com/nautobot/nautobot/blob/ltm-1.6/nautobot/dcim/tables/sites.py#L25). This didn't help.

**Comment by glennmatthews** [comment]
The first query is getting site counts per region and aggregating them up to the parent regions (`queryset = Region.objects.add_related_count(Region.objects.all(), Site, "region", "site_count", cumulative=True)`), whereas the second query is only getting the count of directly attached sites per region (`Region.objects.annotate(count_site=Count("sites"))`), so this would be a behavior change to swap these out.

Note that in 2.0, due to the switch from django-mptt to django-tree-queries, which [doesn't currently have](https://github.com/feincms/django-tree-queries/issues/21) an `add_related_count` equivalent API, this performance issue is absent.

**Comment by Kircheneer** [comment]
So if django-tree-queries does not have this API, the way this field is achieved in 2.0 could give us an idea of how to do this better, shouldn't it?

**Comment by glennmatthews** [comment]
Sorry, I may not have stated that very clearly. In 2.0 we don't/can't do a nested/cumulative/aggregate count at all, only a count of the records directly attached to each Location. "Fixing" this performance issue in 1.x would involve making a similar behavior change for the Region list view, but this *would* be a behavior change and so is likely considered undesirable in an LTM branch.

**Comment by Kircheneer** [comment]
I was able to utilize a [View Override](https://docs.nautobot.com/projects/core/en/stable/development/apps/api/views/core-view-overrides/) as a workaround:

```python
"""View overrides."""
import nautobot.dcim.views
from django_tables2 import tables
from nautobot.dcim.models import Region
from nautobot.dcim.tables import RegionTable
from nautobot.utilities.tables import BaseTable


class RegionTableWithoutSiteCount(RegionTable):
    """Remove the 'site_count' field from the region table.

    This is necessary because of the bad performance of that field,
    see https://github.com/nautobot/nautobot/issues/4941.
    """

    class Meta(BaseTable.Meta):
        """Remove 'site_count' field."""

        model = Region
        fields = ("pk", "name", "slug", "description", "actions")
        default_columns = ("pk", "name", "description", "actions")


class RegionListViewOverride(nautobot.dcim.views.RegionListView):
    """Override the region list view removing the 'site_count' view from the table."""

    table = RegionTableWithoutSiteCount


override_views = {
    "dcim:region_list": RegionListViewOverride.as_view(),
}
```

**Comment by lampwins** [comment]
We are not going to be able to make this change in 1.6. We also have other plans to solve of the related problem with locations in v2, so I am going to close this out.
