### ISSUE TITLE
search for prefixes does not find all prefixes

### ISSUE THREAD

**Issue by evdzande** [nautobot/nautobot#495]
### Environment
* Python version: 3.7.3
* Nautobot version: 1.0.1

### Steps to Reproduce
1. create a couple of prefixes under 100.64.0.0/10. i.e.: 100.64.8.0/21, 100.64.16.0/30, 100.64.16.4/30, 100.64.16.8/30, etc.
2. search for "100.64" or "100.64." these prefixes in global search or the search box under IPAM > Prefixes

### Expected Behavior
All prefixes starting with "100.64" should be shown

### Observed Behavior
Only prefix 100.64.0.0/10 is shown.
IP adresses within these prefixes are shown, the prefixes associated with the IP adresses are not.
If you go to IPAM > Prefixes and fill in the field "Search within" 100.64.0.0/10 then all prefixes are shown.

**Comment by evdzande** [comment]
also reproducable on https://demo.nautobot.com.
Search for 10.0 in the top right search box or under the All Objects search box.
Only 10.0.0.0/8, 10.0.0.0/16, 10.0.0.0/18 and 10.0.0.0/24 are shown. With these results you think those are the only subnets registered in the system but in reality there are many more 10.0.0.0 subnets registered on the https://demo.nautobot.com site.

**Comment by glennmatthews** [comment]
Thanks for the report! This is probably a consequence of https://github.com/nautobot/nautobot/pull/78 - at the time I believe we'd accepted the loss of this "partial address search" functionality as a necessary evil, but with subsequent refinements (especially #246) I think it *might* in fact be possible for us to restore this functionality. We'll look into it.
