### ISSUE TITLE
UI Feedback from 2.1.0beta1

### ISSUE THREAD

**Issue by cmsirbu** [nautobot/nautobot#4961]
### Environment
* Nautobot version (Docker tag too if applicable): 2.1.0b1
* https://next.demo.nautobot.com/
* Browser: Chrome (120.0.6099.71) on Ubuntu 20.04

## User menu

![image](https://github.com/nautobot/nautobot/assets/9288571/0d33fa87-95d1-495e-a611-f8617ea91d77)

User pop-up menu is out of place at the top or bottom of the nav - suggestion: move it to the bottom of the nav panel as a fixed line anchored to the bottom of the page with always visible Profile/Logout buttons. Something like this (just a quickie image edit):

![image](https://github.com/nautobot/nautobot/assets/9288571/19acd15e-6978-4914-b119-198a66cc61e8)

## Large nav menu pop-ups cause a scrollbar to appear

![image](https://github.com/nautobot/nautobot/assets/9288571/43eb9c63-36a4-4f08-9207-7cbb4041c839)

Click on `DEVICES` in the nav. The drop-down menu overflows the page and causes a scroll-bar to appear, which causes the usable space in the nav to shrink.

Expected behaviour: the scrollbar does not affect the layout of the nav column by reducing its width.

## Vertical side-bar nav does not behave as one would expect

Using drop-down pop-ups in a vertical side nav bar is not a common pattern and completely unexpected UI wise.

It's not entirely obvious that it indeed is a temporary drop-down instead of a menu expansion inline, until one opens a smaller category, like `POWER`:

![image](https://github.com/nautobot/nautobot/assets/9288571/0834e145-c17f-42be-b7c1-5c91e3a9ffec)

A side-effect of this temporary drop-down is that when navigating to a particular page (e.g. the Devices page within the `DEVICES` category), the nav resets to the default collapsed mode not showing the location of the current page within the larger menu.

![image](https://github.com/nautobot/nautobot/assets/9288571/2bdf4867-1119-452d-b00d-59c09cfafd9c)

Expected behaviour: the left-hand side nav expands inline (no drop-downs) and tracks the current location of the main view, highligting the "Power Feeds" menu item when viewing the respective page.

## The nav is too narrow

When expanding categories with longer names, the scrollbar makes the layout overflow on a new line and a horizontal scroll-bar appears:

![image](https://github.com/nautobot/nautobot/assets/9288571/fcdc7d4a-7c5c-4267-a7e5-2e90af9ace83)

Expected behaviour: no horizontal scrollbar at the very least and a more controlled method to display longer names.

## The nav is too narrow reloaded

Expand the `ROUTING` section - the text boxes overflow under the buttons, which doesn't happen for shorter menu items. Some of these menu items end up on 3 rows due to their length.

![image](https://github.com/nautobot/nautobot/assets/9288571/22fc9001-1a41-414a-bc30-d7b418146f31)

## Nav item button styles changed but plugins not affected

This is a consistency issue in the making - all the `+` buttons in the nav now use a blue color (`btn-info`) while Device Lifecycle uses `btn-success`. Unsure if this is a DLM issue or not, as it looks like all other plugins are blue.

![image](https://github.com/nautobot/nautobot/assets/9288571/04d868e1-31a1-45da-8126-278317bd3f45)

![image](https://github.com/nautobot/nautobot/assets/9288571/fc79be39-12e1-4ef5-a9ae-47daac440f40)

## Highlight color of selected nav item is white in dark mode

Selecting any category in the nav while in dark mode makes it highlight white. This is too bright and seems like a bug, since in light mode the highlight is barely visible as a dark color. Seems to happen when the drop-down is open and the window loses focus (i.e. you click on another window), sometimes getting stuck like this, sometimes reverting to dark.

![image](https://github.com/nautobot/nautobot/assets/9288571/37ad1130-1fc5-4e8d-b94e-668dd04fe972)

Video from focus loss flashes in Firefox (same behavior in Chrome):

[Peek 2023-12-12 19-23.webm](https://github.com/nautobot/nautobot/assets/9288571/ef4ecdb5-9cae-4ac5-9dcf-f4a5b74375b6)

**Comment by glennmatthews** [comment]
- User menu
Can investigate to see if it'd be an easy fix, otherwise probably not worth the time

- Large nav menu pop-ups cause a scrollbar to appear
- Vertical side-bar nav does not behave as one would expect
Unavoidable in the current bootstrap-3 implementation of the nav without a fair amount of work

- [ ] The nav is too narrow
We should widen it just enough to permit all of the "standard" app menus to fit comfortably, and also add CSS so that any excessively longer menu headings get truncated with an ellipsis rather than wrapping.

- The nav is too narrow reloaded
Unavoidable compromise I think - the only alternatives would be to make the nav far wider or truncate menu items, and I don't think either is preferable.

- [ ] Nav item button styles changed but plugins not affected
Looks like DLM is using NavMenuButton base class instead of the provided NavMenuAddButton and NavMenuImportButton classes. We should chase it down to fix.

- [ ] Highlight color of selected nav item is white in dark mode
Yup, needs some CSS tweaks.

**Comment by gsnider2195** [comment]
Feedback from today on the user menu anchoring to the bottom. If this is not something that we're able to do with the current ui, it would be nice to have some separation between the last menu item and the user menu.

**Comment by glennmatthews** [comment]
Initial changes implemented in #5013.

**Comment by glennmatthews** [comment]
Opened nautobot/nautobot-plugin-device-lifecycle-mgmt#266

**Comment by lampwins** [comment]
Going close this out as we have done what we can on the current tech stack. In the future we will redesign the nav menu as a part of a larger UI change and we will more than likely take care of all of this.
