### ISSUE TITLE
Add MMF OM5 as a cable choice

### ISSUE THREAD

**Issue by nrnvgh** [nautobot/nautobot#4965]
### As ...

Nelly - Network Engineer

### I want ...

I'd like to have `Multimode Fiber (OM5)` appear in the cable type drop-down

### So that ...

We can accurately model our networks

### I know this is done when...

I can set the cable type to `Multimode Fiber (OM5)`

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [X] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

None

### External Dependencies

None

**Comment by nrnvgh** [comment]
Added patch against `ltm-1.6`; PR for `develop` available shortly.

**Comment by nrnvgh** [comment]
Patches added; I saw there's also a 'next' branch...for tracking 2.1? Is there anything I need to do to ensure these changes (and others, such as the ones for #4873) are rolled into 2.1?

**Comment by glennmatthews** [comment]
Thanks for the PRs! `next` is indeed tracking 2.1 - we'll make sure all of the content in `develop` gets merged with that branch before we ship 2.1.0. :-)

**Comment by nrnvgh** [comment]
Saw this got assigned to me; do you need any action from me on this?

**Comment by glennmatthews** [comment]
Nope, sorry for the noise - just since you've been kind enough to open the PRs to implement this, wanted to make it clear that no one else needs to do so. Thanks again!
