### ISSUE TITLE
Nautobot 2.1 - Admin Missing API/Logger

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#4974]
### Environment
* Nautobot version (Docker tag too if applicable): 2.1 rc
* Python version: na
* Database platform, version:na
* Middleware(s): na

### Steps to Reproduce
1. PR 4646 was to include an API to address programmatic access to the data
2. This was pulled out
3.

### Expected Behavior

Have a programmatic behavior access to the admin log changes

### Observed Behavior

Only available via UI

See https://github.com/nautobot/nautobot/pull/4646

**Comment by jvanderaa** [comment]
This does not need to be an API endpoint necessarily. API endpoint or logger.

**Comment by jvanderaa** [comment]
An API endpoint actually adds more complexity to the end request. The end result needs to get to a logger mechanism. So ideal state is to just add to a logger. 

The previous part of having an API was going to be something that could be worked around.

**Comment by glennmatthews** [comment]
Can you provide more specifics as to what content you'd want to expose in the syslog? I'll also note that the admin LogEntry records provided by Django aren't nearly as detailed as Nautobot's ObjectChange records, so if you want more information than what they currently include that would increase the scope significantly - here's some example data:

```python
>>> import pprint
>>> for le in LogEntry.objects.all():
...     pprint.pprint(le.__dict__)
... 
{'_state': <django.db.models.base.ModelState object at 0x7f1e576d3670>,
 'action_flag': 2,
 'action_time': datetime.datetime(2023, 12, 13, 15, 22, 53, 198886, tzinfo=<UTC>),
 'change_message': '[{"changed": {"fields": ["Object types"]}}]',
 'content_type_id': 121,
 'id': 5,
 'object_id': '6d5773ae-7e04-404d-8830-44dd82bb3440',
 'object_repr': 'demo_read',
 'user_id': UUID('b6aec21e-e816-4e1c-b1c2-9380b7653468')}
{'_state': <django.db.models.base.ModelState object at 0x7f1e576f5040>,
 'action_flag': 1,
 'action_time': datetime.datetime(2023, 12, 13, 15, 21, 27, 974899, tzinfo=<UTC>),
 'change_message': '[{"added": {}}]',
 'content_type_id': 121,
 'id': 4,
 'object_id': '6d5773ae-7e04-404d-8830-44dd82bb3440',
 'object_repr': 'demo_read',
 'user_id': UUID('b6aec21e-e816-4e1c-b1c2-9380b7653468')}
{'_state': <django.db.models.base.ModelState object at 0x7f1e576f54f0>,
 'action_flag': 1,
 'action_time': datetime.datetime(2023, 12, 12, 18, 59, 48, 266010, tzinfo=<UTC>),
 'change_message': '[{"added": {}}]',
 'content_type_id': 102,
 'id': 3,
 'object_id': '6873bfc7-b7c4-447f-81f4-016d9dbd7c7d',
 'object_repr': 'nautobot_example_models.csv',
 'user_id': UUID('b6aec21e-e816-4e1c-b1c2-9380b7653468')}
{'_state': <django.db.models.base.ModelState object at 0x7f1e576f5550>,
 'action_flag': 1,
 'action_time': datetime.datetime(2023, 12, 7, 21, 32, 16, 648849, tzinfo=<UTC>),
 'change_message': '[{"added": {}}]',
 'content_type_id': 118,
 'id': 2,
 'object_id': 'aa9e6296-4a3f-4204-8919-e8bcbeba00b9',
 'object_repr': 'glenn.matthews@networktocode.com',
 'user_id': UUID('b6aec21e-e816-4e1c-b1c2-9380b7653468')}
{'_state': <django.db.models.base.ModelState object at 0x7f1e576f5610>,
 'action_flag': 1,
 'action_time': datetime.datetime(2023, 11, 27, 18, 37, 42, 517992, tzinfo=<UTC>),
 'change_message': '[{"added": {}}]',
 'content_type_id': 121,
 'id': 1,
 'object_id': 'a20525b8-e5e6-4320-857d-29099a37b464',
 'object_repr': 'test',
 'user_id': UUID('b6aec21e-e816-4e1c-b1c2-9380b7653468')}
>>>
```

Each LogEntry basically just has an `action_time` timestamp, a *brief* `change_message`, the `user_id` that took the action, and a GenericForeignKey to the object that was created/updated/deleted.

**Comment by lampwins** [comment]
Closing this in favor os #4992
