### ISSUE TITLE
Setting for file size limit on job generated files

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#4984]
### As ...

Patti - Platform Admin

### I want ...

A global configuration setting that allows me to specify a max file size for files generated by a job.

### So that ...

Job authors and their uses cannot accidentally (or nefariously) overwhelm the storage backend with large files.

### I know this is done when...

- A new configuration setting for job_generated_file_max_size
- Default of 10 MB (or some agreeable, sane default)
- Available in constance

It would be ideal if the enforcement of the file size is not easily overridable by a knowledgeable job author, but if this proves to be a large effort, this is acceptable as a guardrail only.

**Comment by glennmatthews** [comment]
As part of this work, we should enhance the FileProxy admin UI table to display the size of each stored file.

**Comment by glennmatthews** [comment]
implemented by #5007
