### ISSUE TITLE
Add a quick button/link to an object detail view to get to the API browser for that object

### ISSUE THREAD

**Issue by joewesch** [nautobot/nautobot#4989]
### As ...

Austin - Network Automation Engineer

### I want ...

To have a button that quickly opens the current object in the API browser

### So that ...

I can see all API field values, and more importantly their API specific keys, instead of waiting to load the full API swagger and drilling down to it there or having to manually updated the URL in my browser by adding `/api` and also removing any query param that isn't a valid API filter (e.g. `?tab=main`).

### I know this is done when...

- I can click a single button or link to quickly get to an object in the API browser

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by lampwins** [comment]
I know you are looking for something in core, but you could do this with a custom link today.

**Comment by joewesch** [comment]
Yes, I know I can do that per instance. This is more of a QOL addition that I plan to put in a PR for that would help me when troubleshooting with someone over zoom. It's easier to guide them to a button in the Advanced tab rather than guiding them to modifying the URL manually.
