### ISSUE TITLE
Bitbucket Git Repository Failure

### ISSUE THREAD

**Issue by dkoolhov** [nautobot/nautobot#4990]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.6
* Python version: 3.10.12
* Database platform, version: ?
* Middleware(s): ?

### Steps to Reproduce
1. Install Nautobot v2.0.6 (I had upgraded from a prior version)
2. Configure secrets as environment variables, and check that secret was successfully retrieved
3. Configure secrets group using Username and Token
4. Create Git Repository - Extensibility > Git Repositories
5. Associate the above secrets group with the above new git repo
6. Once repo is created and sync started you should see an error:
```
<class 'nautobot.extras.models.jobs.JobResult.DoesNotExist'>

JobResult matching query does not exist.

Python version: 3.10.12
Nautobot version: 2.0.6
``` 
7. At this point on the cli of the OS and as the Nautobot user run command 
```
nautobot-server post_upgrade
``` 
You should see a message similar to this:
```
Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -- https://mybitbucket.example.net/automation/nautobot-jobs.git /opt/nautobot/git/stash_jobs
  stderr: 'Cloning into '/opt/nautobot/git/stash_jobs'...
fatal: could not read Username for 'https://mybitbucket.example.net': terminal prompts disabled
``` 
8. Manually running this same git command will indeed prompt for username and password 

### Expected Behavior
Git repository will sync and make the jobs within that repo available

### Observed Behavior 
Nautobot GUI gives no indication this situation was occurring in the background, the "Job Result: Git Repository: Sync" is stuck pending but the log messages show completed - see attachment. /opt/nautobot/git does not have a new repository and thus no repo jobs are available.
<img width="1285" alt="Screenshot 2023-12-15 at 9 40 44 AM" src="https://github.com/nautobot/nautobot/assets/141774611/8124ffdd-7db5-4f33-93d5-dace47968f14">

Note: I followed https://docs.nautobot.com/projects/core/en/stable/user-guide/platform-functionality/gitrepository/#repository-configuration, noting the 2nd blue box about secrets group.

**Comment by angelsollaperez** [comment]
Hi, I have the same exact problem.

**Comment by glennmatthews** [comment]
Strange - I just tested locally with a non-Bitbucket private repository and the error correctly bubbles up to the user UI:

![image](https://github.com/nautobot/nautobot/assets/5603551/5b05c2da-0323-4e32-815a-6aaf120797ad)

I can't see why Bitbucket specifically would matter here as this is generic `git` functionality.

**Comment by gsnider2195** [comment]
@dkoolhov @angelsollaperez Are you able to monitor the logs of your workers while running this sync? I'm also not able to replicate this issue on Nautobot v2.0.6 and Python 3.10. Can you try running `nautobot-server showmigrations` to make sure all of your migrations are applied?

**Comment by gsnider2195** [comment]
I did some troubleshooting with another user having their git repo sync jobresult stuck in pending and it appears that the jobresult was not saved by the job because the `worker` field was still `None` after the job completed. It's possible one of the datasource callbacks is saving the jobresult with old data? Also possible that a transaction rollback is being performed somewhere.

**Comment by gsnider2195** [comment]
Can you make sure that you don't have a custom `CELERY_RESULT_BACKEND` setting? We changed this in 2.x and no longer require/support changing that setting. Related to #5201

**Comment by justinbrink** [comment]
I recreated this issue with a fresh install and can confirm that having `CELERY_RESULT_BACKEND` set for version 2.x causes the job to sit in a pending state after the authentication failure, but removing it causes it to fail the job as expected.

**Comment by angelsollaperez** [comment]
> I recreated this issue with a fresh install and can confirm that having `CELERY_RESULT_BACKEND` set for version 2.x causes the job to sit in a pending state after the authentication failure, but removing it causes it to fail the job as expected.

@gsnider2195 I have the same experience.

**Comment by chadell** [comment]
sorry @angelsollaperez , do you mean that without the `CELERY_RESULT_BACKEND`, it works well? or that even removing it, the problem persists?

**Comment by justinbrink** [comment]
I just came back to this and realized the original cause for the failure wasn't addressed here. The error `fatal: could not read Username for ...` comes up when the connection requires a username, but the SecretsGroup doesn't have one assigned for HTTP(s)/Username. Basically it's the same as this:
`jbrink@ubuntu:~$ GIT_TERMINAL_PROMPT=0 git clone -v -- https://''@bitbucket.org/jbrink-dev/nautobot-test.git test/
Cloning into 'test'...
fatal: could not read Username for 'https://bitbucket.org': terminal prompts disabled`
So the two steps to follow up on this are:
1. Verify that the nautobot_config.py does not contain `CELERY_RESULT_BACKEND`
2. Verify that the SecretsGroup assigned to the Git Repository has a HTTP(s)/Username Secret defined and is returning a non-blank value

**Comment by dkoolhov** [comment]
@gsnider2195 and @justinbrink, confirmed that commenting the `CELERY_RESULT_BACKEND` line in Nautobot config and restarting services resolves the issue. The other issue was missing the EnvironmentFile line in the systems conf for nautobot-worker.service in addition to nautobot.service. But with errors reporting properly that was easy to track down.
