### ISSUE TITLE
Bulk import tree models

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#4998]
### As ...

Dan - Data Owner

### I want ...

to be able to import a hierarchy of LocationTypes using the bulk import feature

### So that ...

I don't have to create the entire hierarachy individually

### I know this is done when...

I can reference a LocationType created in row 1 as the parent of a LocationType created in row 2 of my csv

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

no

### External Dependencies

no

**Comment by timizuoebideri1** [comment]
If I understand correctly, this import is limited to only parent-child imports, which implies you can't import more than one parent because every other line is below another line, making the above line its parent.

**Comment by timizuoebideri1** [comment]
will this not result in the desired outcome:
```csv
name,parent
parent-1,
child-1,parent-1
```
