### ISSUE TITLE
Add Git repository “dry-run” capability

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#5]
### Proposed Functionality
Provide an option to do a “dry run” of a Git repository sync/refresh and report what data (config contexts, export templates, etc.) would be changed as a result, without actually applying the change.

### Use Case
Sanity checks, especially when adding a new Git repository for the first time.

### Database Changes
None.

### External Dependencies
None.

**Comment by bryanculver** [comment]
Merged into `next`.
