### ISSUE TITLE
Implement cache for IP Addresses in Prefixes view

### ISSUE THREAD

**Issue by apast0r** [nautobot/nautobot#5001]
### As ...

Austin - Network Automation Engineer

### I want ...

I use alot, the Prefix IP Addresses view to check avaliable IP ranges.

But this view is slow. Depending of the prefix it can take some time.

In this example with a /21 it took **6s**

![image](https://github.com/nautobot/nautobot/assets/99388425/cc458315-2c49-4ec8-8574-b55c3f79ca1f)

![image](https://github.com/nautobot/nautobot/assets/99388425/408a33ac-ef8e-41f3-83a0-c7a4bf18bac6)

I check the mysql databse when this occur, and the query is fast. So is the nautobot that is doing calculations.
Can this calculations be saved in cache, so the next time if there isn't any IP changes it loads faster?

### So that ...

Faster page loads, more work in the same time.

### I know this is done when...

The Prefix IP Addresses view loads faster.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [X] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by apast0r** [comment]
I have updated to the [v2.1.2](https://github.com/nautobot/nautobot/releases/tag/v2.1.2), and now load significantly faster. 

It seems that these two fixes help in the loading times:

- https://github.com/nautobot/nautobot/issues/5024 Fixed a bug that caused IPAddress objects to query their parent Prefix and Namespace every time they were instantiated.
- https://github.com/nautobot/nautobot/issues/5024 Improved performance of the IPAddress list view by including the namespace in the table queryset.

Now it takes 815ms, this is 735% more fast!

![imagen](https://github.com/nautobot/nautobot/assets/99388425/92356d90-99b0-4e16-a5e4-8358ed59ff37)

Any tips or tricks to further improve loading times?

**Comment by lampwins** [comment]
Great to here @apast0r! We have some ongoing efforts for performance testing that I am sure will uncover additional opportunities, but we don't have anything more specific on the plate right now.
