### ISSUE TITLE
Config Context Schema Regression

### ISSUE THREAD

**Issue by rifen** [nautobot/nautobot#5005]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.3-py3.9
* Python version: 3.9
* Database platform, version: Postgres 13
* Middleware(s): Docker Compose

### Steps to Reproduce
1. Navigate to Config Context
2. Add/Update Config Context
3. Nowhere to apply Config Context Schema

### Expected Behavior
![image](https://github.com/nautobot/nautobot/assets/10360333/d21e7d10-9c83-4819-88df-d1dab87c7668)

### Observed Behavior
![image](https://github.com/nautobot/nautobot/assets/10360333/87a35c3d-6861-414a-86dd-3e4bca97e4c8)

**Comment by glennmatthews** [comment]
Looks like a miss in the field renaming in 2.0:

https://github.com/nautobot/nautobot/blob/develop/nautobot/extras/templates/extras/configcontext_edit.html#L11

should be changed to `{% render_field form.config_context_schema %}` now.
