### ISSUE TITLE
not easy/intuitive (any more) to add new IP address and prefix

### ISSUE THREAD

**Issue by evdzande** [nautobot/nautobot#501]
### Environment
* Python version: 3.7.3
* Nautobot version: 1.0.2

### Steps to Reproduce
1. find a free IP address. i.e. go to **IPAM > Prefixes > 10.0.0.0/24 > IP Addresses** in the **https://demo.nautobot.com** site. and click on **254 IPs available**. The **Add a new IP address** form appears with the **Address** field empty/None.

2. find a free prefix. i.e. go to **IPAM > Prefixes > 10.0.0.0/18** in the **https://demo.nautobot.com** site. and click on **10.0.8.0/21**. The **Add a new prefix** form appears with the **Prefix** field empty/None.

### Expected Behavior
1. The **Address** field should be filled with the first available free IP address as was the case within Netbox.

2. The **Prefix** field should be filled with the first available free prefix as was the case within Netbox

### Observed Behavior
1. the **Address** field is empty/None
the URL is: **https://demo.nautobot.com/ipam/ip-addresses/add/?address=10.0.0.1/24** so the first available IP was discovered but not filled into the form.

2. the **Prefix** field is empty/None
the URL is: **https://demo.nautobot.com/ipam/prefixes/add/?prefix=10.0.8.0/21** so the first available prefix was discovered but not filled into the form.

**Comment by glennmatthews** [comment]
Thank you for the report! I think we fixed a similar issue before under https://github.com/nautobot/nautobot/issues/224. This is probably a side effect of #78.

**Comment by Thetacz** [comment]
Hi, thank you for reporting this, wanted to do the same. Few people already noticed this in our instance and asked for the fix. This feature seems to be used quite a lot.
