### ISSUE TITLE
ObjectChange missing indexes for common use cases

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#5012]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.5
* Python version:
* Database platform, version: mysql
* Middleware(s):

### Steps to Reproduce
1. Have a very large change log table across all object types
2. Query the changelog for common use cases:

--- 
1. Device detail object change view
[This view](https://github.com/nautobot/nautobot/blob/84fba7bf2c020658878be9961c258cc70316cad6/nautobot/extras/views.py#L1618C7-L1618C26) uses this query:
https://github.com/nautobot/nautobot/blob/84fba7bf2c020658878be9961c258cc70316cad6/nautobot/extras/views.py#L1636-L1641

Which uses a combination of (`changed_object_type`,`changed_object_id`) and (`related_object_type`, `related_object_id`), however those combinations are not indexed together. They do exist with other combinations of fields, but we need an index that the query in this view can use. This should be two new indexes for the pairs.

2. Lookup by user
Both the user FK and the `user_name` fields should be indexes. Today only the user FK is indexed.

3. Lookup by user & object
There should be a triple index on `user`, `changed_object_type`, and `changed_object_id`. Likewise, the same triple should exist for `user_name`.

**Comment by lampwins** [comment]
Will target 2.1.X

**Comment by glennmatthews** [comment]
Implemented in #5041
