### ISSUE TITLE
Update default sanitizer pattern to support dictionary logging redactions

### ISSUE THREAD

**Issue by jeffkala** [nautobot/nautobot#5031]
### As ...

Austin - Network Automation Engineer

### I want ...

Update the default sanitizer pattern to support redacting the same keys when the logging is a python dictionary.

### So that ...

Logging python dictionary objects in the job result will also capture the basic username/password/secrets and redact them.

### I know this is done when...

- Logging a python dictionary with secrets included within a job result log and seeing the default sanitizer redact the sensitive data.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

n/a

### External Dependencies

n/a

**Comment by gsnider2195** [comment]
Can you provide an example output that isn't being sanitized by the current pattern?

**Comment by jeffkala** [comment]
![Screenshot 2024-01-02 at 8 44 07 AM](https://github.com/nautobot/nautobot/assets/48843785/71a1e56e-0e16-4831-b63d-770971f40f7a)

Here's an example @gsnider2195 basically the PR #4994 will help also catch the same sensitive data if you're logging a dictionary.
