### ISSUE TITLE
login page elements overlap on smaller viewports

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#5045]
### Environment
* Nautobot version (Docker tag too if applicable):
* Python version:
* Database platform, version:
* Middleware(s):

change viewport width to something between 1000 and 1100 pixels (on default zoom and scaling)

### Expected Behavior

elements don't overlap

### Observed Behavior

![image](https://github.com/nautobot/nautobot/assets/75227981/e478dbde-3b61-4122-8b65-aa03705d4cf8)

**Comment by glennmatthews** [comment]
Related: #5062

**Comment by glennmatthews** [comment]
Probably we need to adjust the CSS breakpoints for `xs`/`sm`/`md`/`lg` layouts now that the sidebar nav is taking up some of the horizontal space.
