### ISSUE TITLE
UI Jobs Display Width too small

### ISSUE THREAD

**Issue by jifoxpa** [nautobot/nautobot#5062]
### Environment
* Nautobot version (Docker tag too if applicable): 2.1.0
* Python version: 3.11
* Database platform, version: postgres:14
* Middleware(s): allow_cidr.middleware.AllowCIDRMiddleware

### Steps to Reproduce
1. Open jobs form /extras/jobs/1624b58c-0e28-4510-beb5-92b17df39b25/edit/
2.
3.

### Expected Behavior
Page width sould be used so all data is displayed without being clipped

### Observed Behavior
Data is clipped

![image](https://github.com/nautobot/nautobot/assets/108326576/e491a232-e31e-4764-806c-9e6c8571a860)

**Comment by glennmatthews** [comment]
Improved somewhat in the general case by #5080, but this specific template still needs some adjustment.

**Comment by lampwins** [comment]
Let's do this across the board.
