### ISSUE TITLE
Spike: Django 4 investigation

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#5096]
As a Nautobot Engineer, I want to understand the impact an upgrade to Django 4 so that I can plan stories accordingly.

- Review django changes and fixes
- Determine impact of breaking changes
- Investigate impact to core code base
- Investigate support for dependancies
  - Determine impact of breaking changes caused specifically by dependency upgrades
- Create new stories under this epic for implementation during the 2.3 release cycle

**Comment by glennmatthews** [comment]
Dependencies:
- Python minimum version for Django 4.2 is 3.8 (:ok:)
- Postgres minimum version is now 12 (:ok:)
- MySQL minimum version is now 8 (:ok:)
- `pytz` is deprecated (to be removed entirely in Django 5) and as of Django 4.0 the default is now `zoneinfo`
   - May have migration implications, especially as relates to `django-timezone-field`

Breaking Changes:
- `USE_TZ` now defaults to True
- `USE_L10N` now defaults to True
- `default_app_config` is removed (4.1)
- "Setting update_fields in Model.save() may now be required" (4.2)

New features of interest:
- Template-based form rendering (4.0)
- `LoginView.next_page` and `get_default_redirect_url()` (4.0)
- `QuerySet.contains(obj)` API (4.0)
- Model `Meta.constraints`, (4.0) now checked during model full_clean (4.1)
- New `div`-based form templates (4.1), will become default in 5.0 - `FORM_RENDERER` setting, `Form.template_name` property, etc.
- `optimizemigration` management command (4.1)
- `pre_delete` and `post_delete` signals now include an `origin` (4.1)
- `psycopg` (v3) as a replacement for `psycopg2`
- `makemigrations --update` flag

Deprecations:
- Logout via GET requests (use POST instead) (4.1)
- `DEFAULT_FILE_STORAGE` and `STATICFILES_STORAGE` -- use `STORAGES` instead (4.2)
- `get_storage_class()` (4.2)
- `Meta.index_together` - use `indexes` instead (4.2)
- `assertQuerysetEqual` - use `assertQuerySetEqual` (4.2)

**Comment by glennmatthews** [comment]
- Surprisingly, `poetry add Django~4.2` goes through without complaint.
- db_file_storage throws an exception at startup (looks like the project got transferred to a new owner, this may get fixed soon)

**Comment by glennmatthews** [comment]
Something seems to be wrong with `NaturalKeyOrPKMultipleChoiceFilter` not supporting filtering by PK after the update, needs investigation. Likely there will be other issues uncoverable by tests as well. I've pushed up a `prototype/3581-django-4.2` branch to GitHub.

**Comment by glennmatthews** [comment]
```
Ran 7871 tests in 2787.927s

FAILED (failures=241, errors=183, skipped=176, expected failures=1)
```

- The majority of the `failures` appear to be in filter test cases, so hopefully a single fix or set of fixes will resolve many of these. 
- Some `failures` in Location testing to do with the `time_zone` field, will need investigation
- Many `errors` in filter tests related to SQL errors in tree models, will need investigation
- A number of GraphQL tests are `error`ing out due to infinite recursion between `graphql` and `graphene`, along the lines of:
  ```
  File "/usr/local/lib/python3.8/site-packages/graphene/types/schema.py", line 96, in __getattr__
    _type = super(Schema, self).get_type(type_name)
  File "/usr/local/lib/python3.8/site-packages/graphql/type/schema.py", line 126, in get_type
    return self._type_map.get(name)
  File "/usr/local/lib/python3.8/site-packages/graphene/types/schema.py", line 96, in __getattr__
    _type = super(Schema, self).get_type(type_name)
  File "/usr/local/lib/python3.8/site-packages/graphql/type/schema.py", line 126, in get_type
    return self._type_map.get(name)
  File "/usr/local/lib/python3.8/site-packages/graphene/types/schema.py", line 96, in __getattr__
    _type = super(Schema, self).get_type(type_name)
  ```
  - Might be related to graphene-django-optimizer, which has known issues with Django 4?

**Comment by glennmatthews** [comment]
Updated the prototype branch with a prototype fix for `NaturalKeyOrPKMultipleChoiceFilter` and for the GraphQL test errors. All GraphQL tests are passing locally now and a few quick manual tests of graphql functionality appear to be fine as well.

**Comment by glennmatthews** [comment]
Slightly better now:
```
----------------------------------------------------------------------
Ran 7871 tests in 2815.168s

FAILED (failures=7, errors=55, skipped=176, expected failures=1)
```

**Comment by HanlinMiao** [comment]
Looks great! Do we need to open some issues or perhaps an epic for the story and call it done?

**Comment by glennmatthews** [comment]
Yup, that's the plan :)

**Comment by glennmatthews** [comment]
Opened:

- #5157 
- #5158 
- #5159
- #5160

and also tagged #5123 as a related issue.
