### ISSUE TITLE
JSONSchema for core settings

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#5097]
As a Platform Admin, I want a JSONSchema that describes the schema for nautobot settings/configuration so that I can be assured I am producing valid config.

- The schema will describe core settings and mostly target any and settings that would reasonably be configured/manipulated by an end consumer.
- The schema will be versioned with the release of nautobot.
- The schema will be easily accessible as a file, but also available via the REST API.
- The schema is not used for actively validating a nautobot config, but instead for defining what is valid. So no validation tooling is needed related to the schema.

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

- [ ] **Scenario 1: Accessing JSONSchema file**
  - Given a Platform Admin
  - When they want to access the JSONSchema file
  - Then the file should be easily accessible

- [ ] **Scenario 2: Accessing JSONSchema via REST API**
  - Given a Platform Admin
  - When they want to access the JSONSchema via the REST API
  - Then the JSONSchema should be available through the API

- [ ] **Scenario 3: JSONSchema versioning**
  - Given a Platform Admin
  - When a new release of nautobot is made
  - Then the JSONSchema should be versioned accordingly

- [ ] **Scenario 4: Configuring/manipulating settings**
  - Given an end consumer
  - When they want to configure or manipulate settings
  - Then the JSONSchema should include descriptions for all settings that can be reasonably configured/manipulated

**Comment by lampwins** [comment]
In the first pass, let's use the schema to build the docs for settings.

**Comment by glennmatthews** [comment]
Implemented by #5235.
