### ISSUE TITLE
Syntax highlighting for JSON/YAML

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#5098]
As a Network Automation Engineer, I want nautobot to show properly formatted and syntax highlighted JSON & YAML whenever such data is presented in the UI, so that I can more easily consume and manage this data.

The primary focus of this story is in the presentation of the data, but a stretch goal of offering syntax highlighting in edit forms is a nice to have.

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

- [ ] **Syntax highlighting for JSON/YAML**
  - Given a Network Automation Engineer
  - When I view JSON or YAML data in the nautobot UI
  - Then the data should be properly formatted and syntax highlighted
  - And I should be able to easily consume and manage the data

**Comment by gsnider2195** [comment]
Implemented in #5176
