### ISSUE TITLE
Evaluating permission constraints referencing the current user

### ISSUE THREAD

**Issue by gertzakis** [nautobot/nautobot#5104]
### As ...

Patti - Platform Admin

### I want ...

a constrains mechanism to reference the present User in a abstract manner. For example, I would like to have functionality in order to create a constrain that allows a User to see only his own Changelog and journal entries, barring him from viewing everyone else's. 

### So that ...

we can enforce a granular Data protection policy without having to create a Group for every User. 

### I know this is done when...

- a User can see only his own Changelog and Journal entries
- Administrator can continue to view all User's entries

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- I think not but not sure

**Comment by glennmatthews** [comment]
Potential inspiration: https://github.com/netbox-community/netbox/commit/12c138b341faff6d2413c620488e124cbbacf8ec
