### ISSUE TITLE
Implement template tags to render phone and email fields in Django Template,

### ISSUE THREAD

**Issue by HanlinMiao** [nautobot/nautobot#5107]
Some models in Nautobot (Contact, Team, and Location) have non-mandatory phone numbers and emails associated with them. It would be nice not to explicitly render them in one template tag instead of in an if/else block that has multiple lines.

_Originally posted by @glennmatthews in https://github.com/nautobot/nautobot/pull/5069#discussion_r1449221680_

**Comment by glennmatthews** [comment]
Implemented for 2.2 by #5302.
