### ISSUE TITLE
Table Config Form for Associated Contacts Table

### ISSUE THREAD

**Issue by HanlinMiao** [nautobot/nautobot#5112]
The Table Config Form for the table in the `contacts` tab of any objects is not working. The config button and the form are now hidden away from the template and the user. Documenting it in this issue so we can have a second look at it.

_Originally posted by @glennmatthews in https://github.com/nautobot/nautobot/pull/5069#discussion_r1449185835_

**Comment by lampwins** [comment]
Let's punt this for now and revisit if we have a more pressing use case.
