### ISSUE TITLE
Cloning Device or IP with a tag applied results in a Server Error

### ISSUE THREAD

**Issue by waydh** [nautobot/nautobot#512]
### Environment
* Ubuntu 20.04
* Python version: 3.8.5
* Nautobot version: 1.0.2

### Steps to Reproduce
1. Install NautoBot 1.0.2 per the directions on https://nautobot.readthedocs.io
2. Create a Site, Manufacturer, Device Role, Tag, and then a Device with all applied
3. Click clone on the created device and receive a Server Error
4. Remove the tag from the device (so there are no tags at all) click Clone and it works
5. Issue also occurs with IPs

### Expected Behavior
Clone button works without error allowing the device to be cloned

### Observed Behavior
Server Error like the following - the invalid UUID is not always 'a', it changes alphabet or number

 Server Error

There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'django.core.exceptions.ValidationError'>

['“a” is not a valid UUID.']

Python version: 3.8.5
Nautobot version: 1.0.2

If further assistance is required, please post to the #nautobot channel on NetworkToCode's Slack.

**Comment by glennmatthews** [comment]
Thanks for the report! This may be related to #499.

**Comment by glennmatthews** [comment]
Looks to be an issue with pre-populating values for any form that uses a `DynamicModelMultipleChoiceField`. Continuing to investigate.
