### ISSUE TITLE
Jobs tile view

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#5129]
As a network automation engineer I want a tile based view of jobs as an alternative to the table list view, so that I have a more elegant way to interact with my automations.

I will know this is complete when a user has the ability to toggle between two view options in the jobs list view:
![Screenshot 2024-01-18 at 11 11 29 AM](https://github.com/nautobot/nautobot/assets/1297132/4acef8f7-88c6-40c4-818d-e08cf6493d05)

Create a card element for jobs like this:
![Screenshot 2024-01-18 at 11 10 00 AM](https://github.com/nautobot/nautobot/assets/1297132/8f7a5a53-d25a-49a0-a714-11ed6561d7df)

Create a view which shows these cards, grouped by the existing grouping headers.
![Screenshot 2024-01-18 at 11 12 52 AM](https://github.com/nautobot/nautobot/assets/1297132/521ef719-9b34-4448-82ed-0c091e75a3da)

Out of scope, but in the future, we will do things like allow users to move and reorder the cards in the view to suit their preferences, and save favorited job cards to the top of the page.

**Comment by glennmatthews** [comment]
Implemented for 2.2 by #5237.
