### ISSUE TITLE
Read the Docs - Search field is missing

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#513]
### Environment
* Python version: N/A
* Nautobot version: 185c5691baf4 (v1.0.2)

### Proposed Functionality

Standard search field should be available like in screenshot.

![image](https://user-images.githubusercontent.com/8406301/120162355-93c2cf00-c1f8-11eb-9b17-96290195a24a.png)

### Use Case

The user wants to search the documentation

**Comment by jathanism** [comment]
Huh. I'll be damned. Where did it go!

**Comment by smk4664** [comment]
I will take this.  I believe I (accidently) caused this issue.  It seems that mkdocs ships with the search plugin enable by default.  And their configuration file overwrites instead of appends.

**Comment by glennmatthews** [comment]
Thank you Stephen!
