### ISSUE TITLE
Add default Statuses (and Roles?) for Contact and Team associations

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#5145]
### As ...

Nelly - Network Engineer

### I want ...

To have an appropriate set of Statuses and Roles provided in a new (or freshly upgraded) Nautobot instance for the ContactAssociation content-type.

### So that ...

I can immediately begin assigning Contacts and Teams to my data without needing to first create a baseline set of Statuses/Roles before the feature is usable.

### I know this is done when...

Nautobot 2.2 migrations include appropriate data migrations to create/update Statuses and Roles (similar to existing patterns for other content-types) that apply to ContactAssociation records.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [X] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

n/a

### External Dependencies

n/a

**Comment by HanlinMiao** [comment]
What would be the names of some appropriate statuses and roles that we should populate via the data migration?

**Comment by lampwins** [comment]
Open to others, but I think:

Status:
- Primary
- Secondary
- Active

Role:
- Administrative
- Billing
- Support
- On site

**Comment by glennmatthews** [comment]
Implemented by #5358.
