### ISSUE TITLE
UI Navigation Menu will be partly hidden by browser link display

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#5152]
### Environment
* Nautobot version (Docker tag too if applicable): 2a8a24ac5281 (v2.1.2)
* Python version: 3.11
* Database platform, version: PostgreSQL 15-alpine
* Middleware(s):

### Steps to Reproduce
1. Move the mouse over a menu item
2.
3.

### Expected Behavior
All menu items should be visible

### Observed Behavior
The last menu item is partially hidden even when fully scrolled down - see screenshot

![image](https://github.com/nautobot/nautobot/assets/8406301/440e0a38-70d0-454f-bb31-0d77ef6f3633)

**Comment by bradh11** [comment]
Indeed it does address this issue @glennmatthews.  The dropdown menus no longer cover the menu items below and they will push down when ones above it are expanded.  There are various other improvements in the #5146 PR related to the side navigation.
