### ISSUE TITLE
Invalid request URL when trying to add a VLAN to an interface belonging to a Virtual Machine

### ISSUE THREAD

**Issue by Lennahrt** [nautobot/nautobot#5155]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.5
* Python version: Python 3.8.17
* Database platform, version: PSQL 10.23
* Middleware(s):

### Steps to Reproduce
1. Create a Virtual Machine 
2. Create an interface within the Virtual Machine
3. Choose 802.1Q Mode (Doesn't matter which mode)
4. Click the Untagged VLAN or Tagged VLANs dropdown list. 
![nautobot_interface_vm](https://github.com/nautobot/nautobot/assets/14165718/23ea7c2a-1297-4353-8b45-8e69ef965e59)
5. An invalid GET request shall be created ( https://mydomain.local/api/ipam/vlans/q=&limit=50&offset=0&depth=0&location_id=null ) -- see picture ( ![HTTP 400](https://github.com/nautobot/nautobot/assets/14165718/bc6922cc-2958-4ba6-aadd-6ca836002c2c) )

6. If you remove the "location_id" part from the URL, you get a HTTP 200 OK with all the correct information.

### Expected Behavior

I expected to see all of my created VLANs, which I do see if I remove the "location_id" part from the request url.

### Observed Behavior

The drop down list says "The results could not be loaded" - because of a HTTP 400 being generated.

**Comment by glennmatthews** [comment]
I think this is likely a duplicate of #5058, which was just fixed in yesterday's 2.1.2 release. If you're able to upgrade, I'd recommend it.

**Comment by Lennahrt** [comment]
Hello @glennmatthews,

You seem to be absolutely correct, thank you. I'll close this ticket as it is a duplicate of https://github.com/nautobot/nautobot/issues/5058.
