### ISSUE TITLE
[1.x] Incorrect variable for Rack Group in Device detail template

### ISSUE THREAD

**Issue by qduk** [nautobot/nautobot#5162]
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.10
* Python version: 3.8
* Database platform, version: Postgresql, 13
* Middleware(s): DebugToolbarMiddleware

### Steps to Reproduce
1. Create a Rack Group
2. Create a Rack in that rack group
3.Create a device and rack it in newly created rack

### Expected Behavior
The device detail page should show both the rack and rack group in the format `{Rack Group}/{Rack}` 

### Observed Behavior
Only the rack is shown.

**Comment by glennmatthews** [comment]
Line 38:

```
{% if object.rack and object.rack_group %}
```

should be `object.rack.group` in 1.x. The template looks correct in 2.x already.

**Comment by HanlinMiao** [comment]
Closed by #5168
