### ISSUE TITLE
Test celery threaded worker pool against SSoT job

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#5164]
Test plan for SSoT:

- Checkout `u/gas-5063-git-repo-sync` branch
- Install SSoT in dev environment
    - `poetry add nautobot_ssot`
    - `inv build`
    - Add `nautobot_ssot` to the `PLUGINS` section of `development/nautobot_config.py`
- Add `--pool threads` to your celery worker's entrypoint (`nautobot-server celery worker --events --pool threads`)
- Start Nautobot `inv destroy migrate debug`
- Run Nautobot <-> Nautobot SSoT against Demo in threaded mode
    - You should see `ThreadPoolWorker` in the console log output. If it says `ForkPoolWorker` you're not running a threaded worker
    - Record run time
- Remove `--pool threads` from celery worker entrypoint
- Destroy database and restart nautobot `inv destroy migrate debug`
- Run Nautobot <-> Nautobot SSoT against Demo in prefork mode
    - You should see `ForkPoolWorker` in the console log output. If it says `ThreadPoolWorker` you're not running a prefork worker
    - Record run time

**Comment by glennmatthews** [comment]
- Parallel Job execution with threaded workers is consistently slower than with the default process workers
- Looks like the bottleneck is CPU on the worker, not CPU on the db container
- cProfile shows the extra time being spent in Django’s query infra, and also in logger calls needing to acquire a lock
- With threading (only) we also noticed a symptom where Job file outputs were being attached to the wrong JobResult - it appears that our implementation of Job.job_result and other cached properties is not properly thread-safe, so we’d have to address and test that as well before switching to threaded workers.
