### ISSUE TITLE
Exporting IP addresses directly

### ISSUE THREAD

**Issue by dbbtuss** [nautobot/nautobot#5173]
### Environment
* Nautobot version (Docker tag too if applicable): 2.1.1
* Python version: 3.11
* Database platform, version: MySQL
* Middleware(s):

When trying to directly export all IP addresses using the "Export" button, instead Power connections are exported.

### Steps to Reproduce
1. Click IP Addresses in left menu
2. When IP's show, click green Export button at the top

### Expected Behavior
Export IP's, not power

I'm able to export successfully via the export job "Export object list" and selecting IP addresses.

**Comment by dbbtuss** [comment]
Tested again today, it seems to be functioning.  I'll keep open in case there is an issue, but it may have been transient.

**Comment by lampwins** [comment]
We were also unable to reproduce this, but feel free to let us know if you run into it again.
