### ISSUE TITLE
Search by Scheduled Job Name in Job Results

### ISSUE THREAD

**Issue by jtdub** [nautobot/nautobot#5180]
### As ...

Ozzie - Operator

### I want ...

The ability to search by a scheduled job name in the job results.

### So that ...

I can quickly identify job results for a job that has multiple scheduled jobs.

### I know this is done when...

I can utilize the search filter in the Job Results page to search for executed jobs based on the name of the scheduled job name.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

I believe this will require an addition to the `nautobot.extras.models.jobs.JobResult` model to account for the additional attribute, but I haven't looked too closely at it, yet.

### External Dependencies

NA

**Comment by gsnider2195** [comment]
Should just need an extra line in the `JobResultFilterSet` `q` filter
