### ISSUE TITLE
UI - Toggle "Hide-NavBar" 

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#5183]
### As ...

Nelly - Network Engineer

### I want ...

... to collapse the NavMenu to the left (only an icon to expand again is displayed) 

### So that ...

... there is more horizontal space for displaying data like tables without having linebreaks in colums-data.

### I know this is done when...

... I open a page that needs a lot of horizontal space to display

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by itdependsnetworks** [comment]
Have you seen https://github.com/nautobot/nautobot/pull/5172

**Comment by jifox** [comment]
@itdependsnetworks Yes, that is exactly the requested functionality.
