### ISSUE TITLE
IPAddress Missing ip_version when created by host/mask_length

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot#5186]
### Environment
* Nautobot version (Docker tag too if applicable): 2.1.2
* Python version: 3.9
* Database platform, version: Postgres
* Middleware(s): SSoT Framework

### Steps to Reproduce
1. Setup Nautobot.
2. Create IPAddress object using `host`, `mask_length`, and `namespace` fields.
3. Attempt to assign IPAddress as primary IP to Device and run validated_save().
4. See ValidationError regarding IPAddress not being IPv4.
5. Evaluate IPAddress field values and see that ip_version is None.

### Expected Behavior
Expect that IPAddress is created and has ip_version defined using host and mask_length.

### Observed Behavior
It appears IPAddress is created but the `_deconstruct_address` method is never called to have ip_version defined so will fail when trying to use as primary IP.

**Comment by jdrew82** [comment]
This will directly impact anybody trying to create IPAddresses in an SSoT App if they're using the NautbotModel(s)/NautobotAdapter pattern as you can't use class properties as class attributes on the NautobotModel.

**Comment by gsnider2195** [comment]
Lets add the logic in `save` to populate this field in 2.1 and then make the field non-nullable in 2.2.

**Comment by glennmatthews** [comment]
Actually Prefix works correctly currently due to a nuance of its implementation. I'll still add some test cases to prove this though.
