### ISSUE TITLE
Webhooks for custom fields definition

### ISSUE THREAD

**Issue by david-kn** [nautobot/nautobot#519]
### Environment
* Python version: any
* Nautobot version: v1.0.1

### Proposed Functionality
Add webhooks also for custom fields.

### Use Case
Notify other systems about data change in Nautobot. 

Other systems that work with and rely on data (custom field choices) in Nautobot as a Source of truth can be notified via such a webhook immediately that custom field data has been modified and should sync them. No checks (requests) towards Nautobot would have to regularly triggered to monitor this change.

### Database Changes
?

### External Dependencies
None

**Comment by jathanism** [comment]
Thanks for the suggestion! We'll need to think about this one and review it.

**Comment by chadell** [comment]
I could take it!

**Comment by glennmatthews** [comment]
Thank you!

**Comment by glennmatthews** [comment]
Addressed in `next` by #823.
