### ISSUE TITLE
Child or unracked device still has face

### ISSUE THREAD

**Issue by sslhansen** [nautobot/nautobot#5196]
### Environment
* Nautobot version (Docker tag too if applicable): 2.1.0 - networktocode/nautobot:2.1.0-py3.10
* Python version: 3.10
* Database platform, version: postgresql 13
* Middleware(s): none

### Steps to Reproduce
1. Create device with face front or rear.
2. Set device position to being unracked
3. Create device and call device.face

### Expected Behavior
As the device is set to unracked, i would expect it to ignore the face input. If the device is a child device, i would expect it to have the face of parent device or even none(and then query the position through parent device).

### Observed Behavior
The device.face call will produce with the face chosen in creation process.

**Comment by sslhansen** [comment]
I am not sure if this design is on purpose, but i figured i would flag this anyway :)

**Comment by glennmatthews** [comment]
Huh. This is supposed to be enforced in `Device.clean()`:

```python
        if self.rack is None:
            if self.face:
                raise ValidationError(
                    {
                        "face": "Cannot select a rack face without assigning a rack.",
                    }
                )
            if self.position:
                raise ValidationError(
                    {
                        "position": "Cannot select a rack position without assigning a rack.",
                    }
                )
```

and in a quick manual test, I see that it appears to be working as intended:

![image](https://github.com/nautobot/nautobot/assets/5603551/cc57719a-0124-47ff-bfaa-fbedb72edccb)


Can you be more specific about how exactly you're creating the device?

**Comment by sslhansen** [comment]
Sorry for the response time on this!
I found out that it was my own fault.

Going back to this now, i see that i explained this quite poorly though. These are not devices that are not in a rack, but unracked(no position in the rack).
We somehow managed to get a device(child) to have face = front, but the _parent_ device had face = rear. I think this was done by messing around with device types, not sure.

When i created this issue i was **sure** that i created the device as a device type that enforced it to become a child device, but no. That was wrong. Which means i can't recreate the issue, because it was in ... my brain. When trying with the correct device type, i was met with the correct error:
<img width="716" alt="image" src="https://github.com/nautobot/nautobot/assets/56868370/eb87f018-f18d-4d51-ad32-a3c6fa69d575">

Sorry for wasting your time! :)

**Comment by glennmatthews** [comment]
No worries! Glad you figured it out.
