### ISSUE TITLE
XLS import support for Nautobot

### ISSUE THREAD

**Issue by MeganerdDev** [nautobot/nautobot#5205]
### As ...

Nelly - Network Engineer

### I want ...

To import files in Excel file format

### So that ...

I do not have to use an intermediate CSV file

### I know this is done when...

I can import XLS files from the user-interface of Nautobot, eg: /dcim/devices/import/

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- Unsure

### External Dependencies

- Django Excel renderer, eg: https://github.com/wharton/drf-excel

**Comment by MeganerdDev** [comment]
It looks like this was explored in #2276

**Comment by lampwins** [comment]
We are unlikely to pursue this as it would add yet another dependency and importing/exporting CSV in excel is rather trivial.
