### ISSUE TITLE
ContactAssociation make Role required

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#5207]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.0a1
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Create a contact association to an object without selecting a role
2. Assign that same contact to the same object with the same status and no role

### Expected Behavior
Failure because contact already exists on that object

### Observed Behavior
Multiple associations are created because `null` != `null` on the `role` field

![image](https://github.com/nautobot/nautobot/assets/75227981/f9771055-127c-436c-adcf-909053f81f0b)

**Comment by gsnider2195** [comment]
As discussed, make role required

**Comment by glennmatthews** [comment]
Implemented in #5279.
