### ISSUE TITLE
Contact Model Feedback

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot#5208]
Contacts tab disappears #5214

| Contact Tab Clicked | Notes Tab Clicked, Contact Tab Missing |
| - | - |
| ![image](https://github.com/nautobot/nautobot/assets/9260483/650ca1da-47dc-43f2-adb2-82d05a863156) |![image](https://github.com/nautobot/nautobot/assets/9260483/0c6e1cfe-2a4e-4e1a-9a5e-6d7bdf14b648) |

Assign Contact tab should be the first one, you will rarely be adding contacts from another model, so let's put the default form as the assign, which will happen most often #5213 

![image](https://github.com/nautobot/nautobot/assets/9260483/a78de0ae-ce64-43af-b7cf-ba435ad87971)

I should be able to multi-select objects in list view (e.g. devices) and set contact from there. (i inspect edited in screenshot to show what it could be) #5211 

![image](https://github.com/nautobot/nautobot/assets/9260483/2a76ac01-cbcf-4e39-9dd7-e51c6368c4a9)

I should be able to filter, or at worst advance filter on contact in a list view (e.g. devices) (inspect edit example included) #5212 

![image](https://github.com/nautobot/nautobot/assets/9260483/28da7c44-40d3-47e0-87ec-f76823b47607)

**Comment by lampwins** [comment]
> Assign Contact tab should be the first one, you will rarely be adding contacts from another model, so let's put the default form as the assign, which will happen most often

It's going to depend on if you source data from somewhere else or not. I can easily see it being the other way around, just depends on the org. That said, I don't have a problem with assign being the default action.

I don't like the current UI pattern here anyway and want to explore ways to consolidate all of this into one single, dynamic form.

**Comment by lampwins** [comment]
Thanks @itdependsnetworks I have opened specific issues for each and updated the original issues with those links.
