### ISSUE TITLE
Make contact assignment, the default form action

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#5213]
As a nautobot user, I expect the default action when assigning a contact to an object to be the assignment of an existing contact, not the creation of a new one.

Reorder the tabs so assignment is the default.

![image](https://github.com/nautobot/nautobot/assets/9260483/a78de0ae-ce64-43af-b7cf-ba435ad87971)

**Comment by glennmatthews** [comment]
Implemented in #5279.
