### ISSUE TITLE
Contact Tab disappearing when the user navigates to Notes and Changelog Tabs

### ISSUE THREAD

**Issue by HanlinMiao** [nautobot/nautobot#5214]
### Environment
* Nautobot version (Docker tag too if applicable): v2.1
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Go to any device's detail view.
2. Navigate to the notes tab.
3. Notice that the contacts tab disappeared on that page.

![Screen Shot 2024-02-01 at 3 21 10 PM](https://github.com/nautobot/nautobot/assets/46973263/ad30ebf7-403d-448f-9e7a-1633b2d619b4)
![Screen Shot 2024-02-01 at 3 21 18 PM](https://github.com/nautobot/nautobot/assets/46973263/8645cb27-134d-402d-8d94-97db2756e839)

4. Also notice this behavior is not present in model views with `NautobotUIViewSet`.
![Screen Shot 2024-02-01 at 3 20 44 PM](https://github.com/nautobot/nautobot/assets/46973263/5aed79ad-9550-4aed-935a-6d594eee1b85)
![Screen Shot 2024-02-01 at 3 21 33 PM](https://github.com/nautobot/nautobot/assets/46973263/a14d4264-dcd5-4cab-86a6-f4b969683bf8)

### Expected Behavior
The contacts tab remains on the page and it is still navigatable.

### Observed Behavior
The contacts tab disappeared.

**Comment by glennmatthews** [comment]
Fixed in #5279.
