### ISSUE TITLE
Add Contacts From ObjectDetailView's return url should redirect to the contacts tab instead of the main tab.

### ISSUE THREAD

**Issue by HanlinMiao** [nautobot/nautobot#5221]
### Proposed Changes
After adding/assigning a contact/team from ObjectDetailView, the web page should be redirected to the contacts tab of the `ObjectDetailView` instead of the main tab.

### Justification
The user can see immediately that the add/assign operations are successful from the contacts tab. Now the user has to click an extra button to navigate to the contacts tab.

**Comment by glennmatthews** [comment]
Implemented by #5358
