### ISSUE TITLE
After selecting Update on a Job Button Receiver navigation takes you to Jobs general

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#5227]
### Environment
* Nautobot version (Docker tag too if applicable): 2.1.2
* Python version: 3.11
* Database platform, version: Postgres, unsure
* Middleware(s): No

### Steps to Reproduce
1. Create Job Button Receiver
2. Filter to buttons, then edit the one receiver that I just created
3. Enable the Job Button Receiver, then select Update at the Bottom
4. Taken to the Jobs list view

### Expected Behavior

I expected to be taken back to just the filtered Job Button Receiver, really just a list view that has the job that I just updated listed there. So I can have this fixed by having Job Button Receivers show up in the Job list by default. :D

### Observed Behavior

I'm taken to a view that I can't see the Job that I just finished updating.

**Comment by glennmatthews** [comment]
Note that #5150 changed the behavior of the Job list view to show job button receivers and job hook receivers by default - will be in 2.1.3.

**Comment by jvanderaa** [comment]
I'm good with closing this out @glennmatthews with that in the plan. Just one of the things that I am like, this is peculiar.
