### ISSUE TITLE
With version 2.1.0, Navigation items now require the permissions arg to be passed

### ISSUE THREAD

**Issue by jmcgill298** [nautobot/nautobot#5241]
### Environment
* Nautobot version (Docker tag too if applicable): 2.1.0
* Python version: 3.8
* Database platform, version: N/A
* Middleware(s):

### Steps to Reproduce
1. Have an app with a NavMenuItem that does not pass the permissions argument
2. Start Nautobot
3. Login as admin
4. Click on NavMenuTab where the NavMenuItem should appear
5. Observe that NavMenuItem does not appear

### Expected Behavior
To see the NavMenuItem (or alternatively for the changelog and core Navigation docs to be updated)

### Observed Behavior
NavMenuItem was a ghost

**Comment by glennmatthews** [comment]
Likely a side-effect of #4787.

**Comment by glennmatthews** [comment]
Probably just needs each of the `if request.user|has_one_or_more_perms:<permissions list>` checks in `nautobot/core/templates/inc/nav_menu.html` to change to `if <permissions_list> and if request.user|has_one_or_more_perms:<permissions list>`
