### ISSUE TITLE
Support nested values for `display_field` in `DynamicModelChoiceField`

### ISSUE THREAD

**Issue by skrobul** [nautobot/nautobot#5243]
### As ...

P.D. - Plugin Developer

### I want ...

Currently, when the UI presents the end-user with a list of dynamically generated choices (for example list of available vlans on the interface), the list is rendered using the `display` attribute of the results returned by the backend API.  The request to the API is made by the machinery included in [select2](https://select2.org) library and [processed on the Nautobot side](https://github.com/nautobot/nautobot/blob/25cef5bb1e4126fcea2801e9b0685d542399e5ab/nautobot/project-static/js/forms.js#L260) to formulate how the list of choices looks like. By default, it uses the `display` value of each record in the response.

This behavior is not always desirable and in some cases, does not provide enough information to the end-user. One particular use case we are currently facing involves selecting a VLAN while editing the Interface, where the list of available choices includes VLAN 200 from VlanGroup "A" and VLAN 200  from VlanGroup "B". With the default behavior, the list of rendered choices just lists "VLAN 200" twice with no way of clarifying which is which.

As a plugin developer, I was able to override a `dcim:interface_edit` view to replace a model form with a custom form. This custom form uses an adjusted `DynamicModelChoiceField` with a custom `display_field`. This is what is possible with the current version of Nautobot at the moment. 
Unfortunately, in its current form `display_field` allows accessing only root-level entries in the API's response. In other words, one can access `id`, `name`, and `display` attributes, but cannot access `vlan_group.name`.

### So that ...

Plugin developers should be able to specify custom display fields, such as `computed_fields.description_with_vg` or `vlan_group.name` instead of just top-level fields.

### I know this is done when...

I would like to propose a small change (PR incoming) in `processResult()` that would allow accessing arbitrary fields in the API response. During our testing, we  used `computedFields.description_with_vg` successfully after modifying's nautobot code and adding the below code to our plugin:

```python
# view_overrides/views.py
from nautobot.core.forms.fields import DynamicModelChoiceField
from nautobot.dcim.forms import InterfaceForm
from nautobot.dcim.views import InterfaceEditView
from nautobot.ipam.models import VLAN


class MyInterfaceForm(InterfaceForm):
    untagged_vlan = DynamicModelChoiceField(
        queryset=VLAN.objects.all(),
        required=False,
        label="Modified Untagged VLAN",
        display_field="computed_fields.description_with_vg",
        query_params={
            "available_on_device": "$device",
            "include": "computed_fields"
        },
    )

class InterfaceEditViewOverride(InterfaceEditView):
    model_form = MyInterfaceForm

override_views = {
    "dcim:interface_edit": InterfaceEditViewOverride.as_view(),
}
```

I would consider this issue "done" when the above code renders a list of choices displaying a value of `computed_fields.description_with_vg` returned by the API.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [X] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

No changes are required.

### External Dependencies

No external dependencies.

**Comment by glennmatthews** [comment]
Relates to #2668 but more narrowly scoped.
