### ISSUE TITLE
Job Buttons do not commit changes in their job.

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot#5261]
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.11
* Python version: 3.11
* Database platform, version: MySQL
* Middleware(s): NA

### Steps to Reproduce
1. Create  JobButtonReciever, set it to commit by default.
2. Create a Job Button and assign to a ContentType.
3. Click the Job Button on the assigned Content Type.

### Expected Behavior

The job runs and commits the changes.

### Observed Behavior

The Job runs and the database changes are reverted.
![image](https://github.com/nautobot/nautobot/assets/17092348/c98724cf-ec91-4e58-aad2-b940346b80b8)

**Comment by glennmatthews** [comment]
Regression in 1.6.8 due to #4995.
