### ISSUE TITLE
Bottom status bar (footer) does not responsively resize as viewport narrows

### ISSUE THREAD

**Issue by cmsirbu** [nautobot/nautobot#5285]
### Environment
* Nautobot version (Docker tag too if applicable): 2.1.4
* Python version: https://demo.nautobot.com/
* Database platform, version: https://demo.nautobot.com/
* Middleware(s): https://demo.nautobot.com/

### Steps to Reproduce
1. Log in to https://demo.nautobot.com/
2. Resize browser window until status bar gets both horizontal and vertical scrollbars

It seems to happen when the width of the `footer` element reaches 1261 px. Both light and dark theme are affected.

### Expected Behavior

The footer / status bar has plenty of padding available, so it should responsively resize as the viewport gets narrower without scrollbars showing.

### Observed Behavior

A horizontal scrollbar appears, which in turn causes a vertical scrollbar to appear as well.

![image](https://github.com/nautobot/nautobot/assets/9288571/9d2fb379-2cde-430e-a8d8-bfdc365a796a)

**Comment by glennmatthews** [comment]
I believe a fix for this will be part of #5172.
