### ISSUE TITLE
`nautobot.core.api.serializers.WritableNestedSerializer` docstring is incorrect and confusing

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#530]
### Proposed Changes
The docstring should read something like this:
> Returns a nested representation of an object on read, but accepts either the nested representation or just the PK value on write operations.

### Justification
The current docstring is in conflict with the actual implementation by stating that only the PK value is supported on write, which is incorrect.

**Comment by glennmatthews** [comment]
Good call! I've been confused by exactly this in the past. :-)

**Comment by Joezeppe** [comment]
I can start with this first good issue.
