### ISSUE TITLE
Custom Fields Association with Git Repositories

### ISSUE THREAD

**Issue by mattmiller87** [nautobot/nautobot#5307]
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.8
* Python version: 3.11
* Database platform, version: postgres
* Middleware(s):

### Steps to Reproduce
1. Create a custom field and provide the object content type `extras | Git repository`
2. Go to edit the git repository - you cannot remove this custom field
3. All existing Git repositories now have this custom field attached
4. Add a new git repository and it will not have the custom field attached

### Expected Behavior
Custom fields should be assignable per object

### Observed Behavior
The new custom field is applied to all existing objects.  New objects do not gain the custom field.
Editing the Git repository should allow a way to view the custom field and remove as needed.

**Comment by HanlinMiao** [comment]
The GitRepo edit form is missing custom field form field and possibly relationship as well. We need to fix them in both 1.6 and 2.1
