### ISSUE TITLE
Standard docker image includes dev dependencies

### ISSUE THREAD

**Issue by mathiaswegner** [nautobot/nautobot#5332]
### Environment
* Nautobot version (Docker tag too if applicable): nautobot 1.6.12, networktocode/nautobot:1.6-py3.10
* Python version: 3.10
* Database platform, version: Aurora PostgreSQL, 13.8
* Middleware(s):

### Steps to Reproduce
1. docker run -ti --entrypoint bash networktocode/nautobot:1.6-py3.10
2. pip install nautobot[sso]

### Expected Behavior
I expected that pip would install one or more dependencies.

### Observed Behavior
All dependencies were already satisfied.

**Comment by glennmatthews** [comment]
Looks like we regressed on #4282 as part of the merge resolution process for 2.0, perhaps?

**Comment by glennmatthews** [comment]
Actually, wait - the Dockerfile in `ltm-1.6` looks correct to me:

https://github.com/nautobot/nautobot/blob/ltm-1.6/docker/Dockerfile#L106

Compare to `develop` (2.x):

https://github.com/nautobot/nautobot/blob/develop/docker/Dockerfile#L51

Can you confirm the issue you're seeing?

**Comment by mathiaswegner** [comment]
ISC20-0562-ML:~ mwegner$ docker run --user root -ti --rm --entrypoint bash networktocode/nautobot:1.6-py3.10
root@4e39ae790220:/opt/nautobot# pip install nautobot[sso]
Requirement already satisfied: nautobot[sso] in /usr/local/lib/python3.10/site-packages (1.6.12)
...
Requirement already satisfied: social-auth-core<4.5.0,>=4.4.2 in /usr/local/lib/python3.10/site-packages (from social-auth-core[openidconnect,saml]<4.5.0,>=4.4.2; extra == "all" or extra == "sso"->nautobot[sso]) (4.4.2)
...
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/site-packages (from prompt-toolkit>=3.0.36->click-repl>=0.2.0->celery<5.4.0,>=5.3.1->nautobot[sso]) (0.2.13)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@4e39ae790220:/opt/nautobot#

**Comment by glennmatthews** [comment]
So that looks like the `sso` extra python packages are installed in the final image, which is expected.

I thought the issue we were discussing on slack previously was that the *OS* dependencies for this extra (`libxmlsec1-dev`, `libxmlsec1-openssl`) were *missing* from the image. (I'd also assumed we were talking about a 2.x image rather than 1.6, mea culpa). Sorry if I'm muddying the waters here!

**Comment by mathiaswegner** [comment]
Oh!  I got that entirely wrong!  The two libxmlsec1 packages are present in the image.  `pkg-config` is also listed in the documentation and is not present in the image, but I'm guessing that's needed to build the other two and not at runtime.
