### ISSUE TITLE
Add ability to inject banner from a plugin

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#534]
### User Story

As P.D the plugin developer, 

I want to have the ability to inject a banner at the top of all pages from a plugin similar to the banner that can be added from the Nautobot config file.

So that I can make sure specific and important information can be provided to the user such as ensuring they know what "branch" of the database they are on.  This example is specific branch-able and versionable database such as Dolt.

I will know this is done when it is possible to:
* Add a banner from a plugin
* Choose the color of the banner displayed from the plugin
* Persist the banner across multiple pages without queuing multiple banners up
* It is not possible to remove the banner by clicking an "x" within the banner
* When using a Nautobot banner (such as in the sandbox), this banner should persist just beneath that with all other notification banners coming below that
* Configure and have a Small, Medium, Large "height" for the banner

**Comment by glennmatthews** [comment]
Resolved in `next` by #756.
