### ISSUE TITLE
Configuration Context not applied based on nested Tenant Groups in LTM

### ISSUE THREAD

**Issue by MeganerdDev** [nautobot/nautobot#5354]
### Environment
* Nautobot version (Docker tag too if applicable): v1.6.4
* Python version: 3.11
* Database platform, version: PG15
* Middleware(s): N/A

### Steps to Reproduce
1. Create nested Tenant Groups with test configuration context
2. Put an object (device) as a Tenant which is a member of a nested Tenant Group
3. Open the Config Context tab, observe the contents of Rendered Context and Source Contexts widget

### Expected Behavior
To see the configuration context applied in Rendered Context and also Source Contexts as a source for context

### Observed Behavior
The configuration context is not applied

### Notes

- Previously a nested tenant issue (#4768) was reported as affecting Nautobot 2.x. Subsequently this was patched for 2.x and closed with #4838. However it is also the case that the 1.6 release is still affected by this bug.
- On first discussions for back-port of the fix in #4838, the issue identified and fixed was noted to be for 2.x only.
- Configuration Context is working for immediate Tenant Groups, the nested Tenant Groups are affected

**Comment by gsnider2195** [comment]
Confirmed this is also affecting LTM

# Testing Data

![image](https://github.com/nautobot/nautobot/assets/75227981/acb1142b-d8f3-4238-9369-3b170fafd1d7)

![image](https://github.com/nautobot/nautobot/assets/75227981/6c30cf52-7690-4be0-b644-9f4d8ca21e67)

![image](https://github.com/nautobot/nautobot/assets/75227981/bca19f42-7125-47ae-b7b1-f8097b99af7d)

# Scenario 1 (Confirmed working on 2.2)

![image](https://github.com/nautobot/nautobot/assets/75227981/2caab073-b875-4e3c-916d-c2cf894ce43f)

![image](https://github.com/nautobot/nautobot/assets/75227981/3604b77b-85e6-45fd-b25d-a7cb8a0e2a54)


# Scenario 2

![image](https://github.com/nautobot/nautobot/assets/75227981/ac99cf44-0381-4443-8066-a56892b979a6)

![image](https://github.com/nautobot/nautobot/assets/75227981/56cf88c8-4de7-4e6f-b979-7a6ca224889f)
