### ISSUE TITLE
Nautobot 2.2 can't import DeviceType yaml or json files

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#5405]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.0a1
* Python version: n/a
* Database platform, version: n/a
* Middleware(s): n/a

### Steps to Reproduce
1. Go to `next.demo.nautobot.com`
2. Click on `Devices` -> `Device Types`
3. Click on the `Import` button

### Expected Behavior
I'm directed to the form at https://next.demo.nautobot.com/dcim/device-types/import/ or a job form that can accept YAML or JSON

### Observed Behavior
I'm directed to the generic CSV job import form at https://next.demo.nautobot.com/extras/jobs/nautobot.core.jobs.ImportObjects/run/?content_type=110

**Comment by glennmatthews** [comment]
IMO we should keep the default CSV import button for DeviceTypes and add a new "Import Single YAML/JSON" button to the list view that explicitly goes to the `/import/` URL.

**Comment by gsnider2195** [comment]
Perhaps they could be separate tabs on the device type import view? That view already has tabs so we could add one more?

![image](https://github.com/nautobot/nautobot/assets/75227981/a05c4f28-3ede-4b5c-8930-964929f62ae2)

**Comment by lampwins** [comment]
<img width="878" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0RJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9e5745cf1bb34f38361041869518b874470bc347/Screenshot%202024-03-08%20at%202.43.59%20PM.png" alt="Screenshot 2024-03-08 at 2.43.59 PM.png" />

Let's use one of these on the device type list view where the yaml import is the default action.

**Comment by glennmatthews** [comment]
Fixed by #5425.
