### ISSUE TITLE
Navbar collapse does not work properly on graphql page

### ISSUE THREAD

**Issue by bradh11** [nautobot/nautobot#5422]
### Environment
* Nautobot version (Docker tag too if applicable): v2.1.7
* Python version: 3.11.
* Database platform, version: postgresql
* Middleware(s): n/a

### Steps to Reproduce
1. browse to graphql editor page from link in the footer
2. click side navbar toggle button to collapse the side navbar

### Expected Behavior
The main content area should expand as the navbar is collapsed

### Observed Behavior
The sidebar collapses, but the main content area does not expand when the navbar is collapsed
Other minor styling issues exist which can be improved with footer overflow scroll bar appearing when it is not needed

This is observed on pages which did not leverage the main wrapper div that most other content leveraged. The following pages are affected.
* /api/
* /graphql
* /admin/

**Comment by cmsirbu** [comment]
@bradh11 since you mentioned footer issues here, I'll add one more. I've noticed that as you resize the window the "Help" and "Code" links sometimes end up outside the viewport.

[where-help-button.webm](https://github.com/nautobot/nautobot/assets/9288571/eca97081-bf2e-4392-97dc-6e0094e3e162)

**Comment by bradh11** [comment]
@cmsirbu noted - I’ll be addressing that as part of #5423
