### ISSUE TITLE
GitPython and Cloning Down 7k+ repositories

### ISSUE THREAD

**Issue by mattmiller87** [nautobot/nautobot#5447]
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.4
* Python version: python 3.8
* Database platform, version: postgres 
* Middleware(s):

With this many repositories, and Nautobot not needing the historical information on the repository, it would make sense for Nautobot to shallow clone the repository.  Alternatively perhaps there is a [caching option](https://networktocode.atlassian.net/wiki/spaces/PP/pages/2614329389/Nautobot+Caching+Analysis) so that this process is mitigated.
Known issues in GitPython to workaround:
 - https://github.com/gitpython-developers/GitPython/issues/718
 - I’m thinking getting Nautobot Core current thoughts on the shallow clone mitigation, and also if any ongoing caching fix is appropriate/preferred/alternative means on addressing.  Perhaps also potentially deleting the local copy after pushing upstream.

I understand this example references Golden Config, but the problem is inherently in Nautobot Core per conversations with Glenn.

### Steps to Reproduce
1. Have 7k+ sites with 7k+ git repositories
2. Perform a GC compliance job

### Expected Behavior
Updates to git repos

### Observed Behavior
Perform a clone down of all repositories for an app such as Golden Config to perform updates
See 50GB in memory required
Host OOMs and kills the process

**Comment by itdependsnetworks** [comment]
For Golden Config, we should approach it this way. https://github.com/nautobot/nautobot-app-golden-config/issues/683

For Nautobot Core in general, I am not sure what the best path forward is.

**Comment by glennmatthews** [comment]
As far as I understand the original issue, the current biggest problem is https://github.com/gitpython-developers/GitPython/issues/718, which may be mitigated by ensuring that we explicitly delete any `git.Repo` objects when done with them, most likely either by explicitly calling `Repo.__del__()` at the end of our `ensure_git_repository()` utility function, or by calling `Repo.__del__()` when a `nautobot.core.utils.git.GitRepo` instance is deleted.

Shallow clone might be a nice feature to mitigate disk space requirements but to the best of my knowledge the memory leak is the current problem to solve.

**Comment by glennmatthews** [comment]
Thus far in some manual testing I'm unable to trigger the GitPython memory leak. Even after re-cloning a repository 1000 times, or cloning 100 separate repos, there are no extraneous open file handles and no apparent increase in memory consumption. This leads me to believe that my previous understanding was perhaps incorrect, and perhaps the "OOM" referenced in the issue was due to disk space exhaustion rather than memory exhaustion -- @mattmiller87 can you provide any additional clarity?
