### ISSUE TITLE
Controllers remaining work

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#5454]
- [x] Add a blurb in the `version-2.2.md` `Release Overview` about this feature
- [x] Refine JS in `nautobot/dcim/templates/dcim/controllerdevicegroup_create.html`:
  - Remove jQuery if possible
  - Replace console.log() in case of AJAX failure with something more user-friendly
- [x] Refine `controller_retrieve.html` layout (https://github.com/nautobot/nautobot/pull/5325#discussion_r1528782587)
- [x] Consolidate controller "developer" documentation with "user" documentation (https://github.com/nautobot/nautobot/pull/5325#discussion_r1528789550)
- [x] Investigate whether changing the default columns shown in `ControllerTable` provides a better UX (https://github.com/nautobot/nautobot/pull/5325#discussion_r1526761529)
- [x] Come to a conclusion about SET_NULL vs PROTECT on `Controller.external_integration` (https://github.com/nautobot/nautobot/pull/5325#discussion_r1526772273) and `Controller.deployed_controller`/`Controller.deployed_controller_group` (https://github.com/nautobot/nautobot/pull/5325#discussion_r1526772664)

Update Controllers based on the discussion during the demo as follows:

- [x] Remove `Add` button from the Controller Device Group main menu.
- [x] Rename `ControllerDeviceGroup` => `ControllerManagedDeviceGroup` / `Managed Device Group`
- [x] Rename `Device.controller_device_group` => `controller_managed_device_group`
- [x] Rename `Controller.deployed_*` => `controller_device` / `controller_device_redundancy_group`.
- [x] Controller Edit:
    - [x] Split into sections, similar to retrieve.
    - [x] Fields `managed*` exclusive similar to Provider Network vs Location tabs in Circuit Terminations.
- [x] Controller Retrieve:
    - [x] Rename `Devices` => `Managed devices`.
    - [x] Remove duplicity role.
    - [x] Merge `Deployed*` to the single field.
- [x] Controller Device Group Edit:
  - [x] Disabled fields are not included in the post, render field as hidden, use something like: `{% render_field form.associated_object_id.as_hidden %}`
  - [x] Move `Controller` above `Name`.

**Comment by snaselj** [comment]
> * [ ]  Come to a conclusion about SET_NULL vs PROTECT on `Controller.external_integration` ([Initial work on Controller Models #5325 (comment)](https://github.com/nautobot/nautobot/pull/5325#discussion_r1526772273)) and `Controller.deployed_controller`/`Controller.deployed_controller_group` ([Initial work on Controller Models #5325 (comment)](https://github.com/nautobot/nautobot/pull/5325#discussion_r1526772664))

This is the last remaining question, what's your opinion pls.? @glennmatthews @whitej6 @mzbroch

**Comment by mzbroch** [comment]
> This is the last remaining question, what's your opinion pls.? @glennmatthews @whitej6 @mzbroch

👍  for protect

**Comment by snaselj** [comment]
Both fields can be null, so keeping `SET_NULL`, no change is necessary.

**Comment by glennmatthews** [comment]
> If field is `null=True` then `on_delete=models.SET_NULL` should be used. I originally used PROTECT but when Glenn pushed back I rethought

I've changed my thinking since the initial pushback though :-) I think from a principle-of-least-astonishment standpoint it makes more sense to prevent users from deleting an ExternalIntegration that's actively in use by a Controller. Similarly for deleting a Device or DeviceRedundancyGroup that represent a Controller?

**Comment by whitej6** [comment]
Then I amend my amended vote to protect 😂

**Comment by snaselj** [comment]
As we are still on beta, I just updated the migration.
