### ISSUE TITLE
add ability to inject content on homepage from plugins

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#546]
### Proposed Functionality 

Nautobot should allow more flexibility with what data is displayed on the Nautobot homepage.    If there is also key data used/driven/stored by a plugin, the plugin author should also be able to inject content to the home page.

### Use Cases

As P.D the plugin developer, 
I want to have the ability to inject content on the Nautobot homepage,
So that I can have plugin-specific data be treated as a first class citizen.  

Providing more contextual examples, we can examine a few existing plugins such as Nautobot ChatOps, Circuit Maintenance, and Golden Configuration.  Each of these plugins has key data that warrant being displayed on the homepage.  Imagine being able to see upcoming circuit maintenances on the homepage?  Imagine being able to see status of configuration backups? Users should be able to control the homepage more than is possible today.

I will know this is done when it is possible to:
* Inject tables/widgets onto the homepage from a plugin

**Comment by glennmatthews** [comment]
Added in `next` by #674
