### ISSUE TITLE
Team/Contact not included in global serach

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#5469]
### Environment
* Nautobot version (Docker tag too if applicable): v2.2.0b1
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Add a contact and a team
2. Try to search for either of those with the global search (https://next.demo.nautobot.com/search/?q=<name>)

### Expected Behavior
Search returns the team or contact searched for

### Observed Behavior
Nothing returns

**Comment by lampwins** [comment]
Add a test for missing models.
