### ISSUE TITLE
Migrate user, social auth, and system settings from Django Admin to be first-class citizens in UI/API

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#547]
### Proposed Functionality 

Before the launch of Nautobot, there was significant work to migrate functionality from Django Admin into core and create first-class views and APIs for webhooks, custom links, and export templates.  Custom fields are also coming soon in #229.  This proposes doing the same for everything in the Users, Python Social Auth, and System sections in Django Admin.

### Use Cases

As Patti the Platform Admin,
I want to have the ability to manage users, groups, and permissions from the Nautobot UI without going into Django Admin,
So that there is a more consistent user experience for my team as well as APIs for anything else that doesn't have an API currently within Django Admin, e.g. Social Auth, retrieving background tasks, etc. 

One option is to create an "Admin" dropdown in the navigation bar which contains "Users (no change)," "Social Auth (drop 'Python')," and "System" sections. We may need one additional section called "plugins" for when plugins have created entries in Django Admin.

I will know this is done when it is possible to:
* Manage what is currently under Users, Python Social Auth, and System sections in Django Admin in the main Nautobot UI
* Manage what is currently under Users, Python Social Auth, and System sections in Django Admin through Nautobot REST API calls

**Comment by glennmatthews** [comment]
Did we narrow the scope of this issue to simply "hide social auth" (#877) or are we still planning to migrate Users and System out of the admin? I *think* it's the former.
