### ISSUE TITLE
Saved Views: User and Global Defaults

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#5471]
As a Nautobot Admin, I want to be able to set a predefined saved view as the default for all users, so that these users do not have to select the view for themselves.

AC:

I know this is complete when a user with adequate permissions is able to assign existing saved views to be the global default for all users for a given model list view.

Individual users can still create their own views and set their own, specific default which then overrides the global default.

- An order of precedence will be defined as:
  - User-specific default saved view
  - Globally defined default saved view
  - No default saved view

As a "shared" boolean to the view model to specify if the view is private to a user or shared for all users.

**Comment by lampwins** [comment]
Per #5774 when this is implemented, the permissions need to then allow for "views I own, or shared views."

**Comment by lampwins** [comment]
For setting the global default, that should be an operation that can happen only from the saved view list view, not for the normal, user facing management of saved views.

When a global has already been set for a given content type, allow the admin user to set a new global and display in a message: "Global default saved view for devices has been changed from A to B"

**Comment by HanlinMiao** [comment]
1. Setting a global default view when a global default view already exists should display a message informing the users that the global default view is changing from `saved view 1` to `saved view 2`.
2. Setting a global default view should only be available to admin users with `users.change_savedview` from the SavedViewListView
