### ISSUE TITLE
[v2.2] Inconsistent required fields for Contact & Team for UI vs API

### ISSUE THREAD

**Issue by joewesch** [nautobot/nautobot#5489]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.0b1
* Python version: 3.11.8
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Try and create a Contact or Team via both UI and API

### Expected Behavior
Either Phone and Email are required or not required for both methods

### Observed Behavior
Phone and Email are **not required for UI**:
![Screenshot 2024-03-26 at 3 45 29 PM](https://github.com/nautobot/nautobot/assets/10467633/97974371-ad1b-45be-aad2-23cf381fb908)
Phone and Email are **required for API**:
![Screenshot 2024-03-26 at 3 45 21 PM](https://github.com/nautobot/nautobot/assets/10467633/b50f789d-d901-425d-8350-7f8744464d9b)

**Comment by glennmatthews** [comment]
Looks like the recurrent DRF issue where any field included in a `unique_together` gets incorrectly auto-marked as required in the API. Solution is to override the automatically generated validators on the serializer and do the validation manually instead. (Example: https://github.com/nautobot/nautobot/blob/develop/nautobot/dcim/api/serializers.py#L208-L209 and https://github.com/nautobot/nautobot/blob/develop/nautobot/dcim/api/serializers.py#L239-L247)

**Comment by joewesch** [comment]
FYI, it looks like Teams are also affected.
