### ISSUE TITLE
Nautobot 2.1.9 + pynautobot RequestError: Authentication credentials were not provided.

### ISSUE THREAD

**Issue by kingfetty** [nautobot/nautobot#5490]
### Environment
* Nautobot version (Docker tag too if applicable): 2.1.9
* Python version: 3.10.12
* Database platform, version: postgresql-14
* Middleware(s):

### Steps to Reproduce
1. Install pynautobot version 2.1.0
2. Install Nautobot version 2.1.9
3. Attempt to connect to Nautobot using pynautobot using token  (ex: `nb = pynautobot.api(url='xxx', token='yyy'` )

### Expected Behavior
pynautobot connects and is able to communicate with nautobot. 

### Observed Behavior
Exception:
```
RequestError
The request failed with code 403 Forbidden: {'detail': 'Authentication credentials were not provided.'}
 
pynautobot.core.query.RequestError: The request failed with code 403 Forbidden: {'detail': 'Authentication credentials were not provided.'}
```

**Comment by joewesch** [comment]
The latest versions of pynautobot are out now to account for this.
