### ISSUE TITLE
[Nautobot 2.2] Unable to add Software to Device without also specifying Software Image

### ISSUE THREAD

**Issue by progala** [nautobot/nautobot#5494]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.0-beta.1
* Python version: 3.11

### Steps to Reproduce
1. Create Software object
2. Try to assign Software object to a Device by editing existing Device object
3. Try saving the object

### Expected Behavior

Save operation should succeed and Software object should be associated with the Device.

### Observed Behavior

Save operation fails with form error stating that no software image files for software version, matching device's device type, are found.

![image](https://github.com/nautobot/nautobot/assets/27512690/05940be4-14aa-4be4-be50-f9b90c77005e)

**Comment by dylanbob** [comment]
Hi. I agree with progala, being able to associate a software version to a device without needing to manage software file versions + their associations with software versions + the devices types' associations with software file versions would really ease the process of very simply storing the version of the device's platform.

**Comment by bakern** [comment]
I ran into this as well.  It looks like it's coming from this validation block in the model:
https://github.com/nautobot/nautobot/blob/6808148732c8824bacca156eadae0e103077fbc3/nautobot/dcim/models/devices.py#L807-L821
Is this validation block needed for some other purpose?  I tested after removing those lines and was able to set a software version in the web GUI and with pynautobot.

**Comment by dylanbob** [comment]
Hi. Following a [question on slack](https://networktocode.slack.com/archives/C01NWPK6WHL/p1723218768830309?thread_ts=1720005031.646459&cid=C01NWPK6WHL), I confirm this is not fixed in 2.3.
