### ISSUE TITLE
Data Sources User/Pass Fields

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot#55]
### Environment
* Python version: 3.7
* Nautobot version: 1.0.b

### Proposed Functionality

The removal of user/password fields from in a way that will not auto-fill for users of standard browser password management systems.

### Use Case

As a user of the git data source, it is highly likely that I would not realize my password manager filled out the user/passwords when filling out the data source and accidentally populate with my own credentials unintentionally.

### Database Changes

N/A

### External Dependencies
N/A

**Comment by jathanism** [comment]
Hmm, I'd like to try to reproduce this myself. Can you please provide how you encountered this? It feels like we might be better off treating this as a bug and then if it can be reproduced, asserting a fix from there?

**Comment by jathanism** [comment]
Related? https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#the_autocomplete_attribute_and_login_fields

**Comment by itdependsnetworks** [comment]
I have used the autocompletion to demo, then went to any data source, this cause the auto-complete to be filled in. Let me know if that helps describe what i am seeing.

**Comment by jedelman8** [comment]
Thoughts on disabling auto-completion in general or just for usernames and passwords?

**Comment by jathanism** [comment]
> Thoughts on disabling auto-completion in general or just for usernames and passwords?

It's worth a shot, but as noted in the link I posted, most password managers ignore the `autocomplete="off"` HTML attribute on `<form>` elements.

**Comment by jedelman8** [comment]
Given that password managers ignore this, closing for now.  We can re-open if needed in the future.
