### ISSUE TITLE
2.1.9: may need to change Nautobot health check due to new authentication requirements on previously unauthenticated endpoint

### ISSUE THREAD

**Issue by UntestedEngineer** [nautobot/nautobot#5503]
### Environment
* Nautobot version (Docker tag too if applicable): v2.1.9-py3.11
* Python version: 3.11 (Built into the docker image)
* Database platform, version: Postgres 16.2 inside container
* Middleware(s): Traefik to control ingress routing to Nautobot pod(s)

Upgraded to v2.1.9-py3.11 and receiving the following error in the nautobot-default container logs.  Rolling back to v2.1.8-py3.11 stabilizes the nautobot-default container.

```
[uWSGI] getting INI configuration from /opt/nautobot/uwsgi.ini
[uwsgi-static] added mapping for /static => /opt/nautobot/static
*** Starting uWSGI 2.0.23 (64bit) on [Fri Mar 29 15:33:31 2024] ***
compiled with version: 12.2.0 on 25 March 2024 20:07:05
os: Linux-6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01)
nodename: nautobot-default-5fcf6dc4b6-mxztn
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /opt/nautobot
detected binary path: /usr/local/bin/python3.11
!!! no internal routing support, rebuild with pcre support !!!
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1545 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8080 fd 6
uWSGI http bound on 0.0.0.0:8443 fd 7
uwsgi socket 0 bound to TCP address 127.0.0.1:40585 (port auto-assigned) fd 5
Python version: 3.11.8 (main, Mar 12 2024, 11:52:02) [GCC 12.2.0]
--- Python VM already initialized ---
Python main interpreter initialized at 0x7f83f4198218
python threads support enabled
your server socket listen backlog is limited to 128 connections
your mercy for graceful operations on workers is 60 seconds
mapped 333504 bytes (325 KB) for 6 cores
*** Operational MODE: preforking+threaded ***
15:33:31.168 INFO    nautobot :
  Nautobot initialized!
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7f83f4198218 pid: 1 (default app)
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 9, cores: 2)
15:33:31.184 INFO    nautobot.core.wsgi :
  Closing existing DB and cache connections on worker 1 after uWSGI forked ...
spawned uWSGI worker 2 (pid: 10, cores: 2)
15:33:31.185 INFO    nautobot.core.wsgi :
  Closing existing DB and cache connections on worker 2 after uWSGI forked ...
spawned uWSGI worker 3 (pid: 12, cores: 2)
spawned uWSGI http 1 (pid: 14)
15:33:31.186 INFO    nautobot.core.wsgi :
  Closing existing DB and cache connections on worker 3 after uWSGI forked ...
15:33:36.584 WARNING django.request :
  Forbidden: /api/
[pid: 9|app: 0|req: 1/1] 10.42.11.1 () {30 vars in 354 bytes} [Fri Mar 29 15:33:36 2024] GET /api/ => generated 58 bytes in 23 msecs (HTTP/1.1 403) 8 headers in 239 bytes (1 switches on core 0)
```

### Steps to Reproduce
1. Roll out version 2.1.9 from 2.1.8 via Kubernetes
2. Observe pod state as new pods are spun up to replace the 2.1.8 pods
3. Observe the nautobot-default pod throwing the described errors above in the logs and preventing container from fully stabilizing (container keeps restarting)

### Expected behavior
nautobot-default pod should fully stabilize without throwing said errors in the logs

### Observed behavior
nautobot-default pod fails to stabilize and constantly restarts

**Comment by glennmatthews** [comment]
This is the same root cause as #5490 and https://github.com/nautobot/helm-charts/issues/371. The `/api/` endpoint is no longer accessible as an unauthenticated health-check. If you're using the `helm-charts` repo, upgrading to chart version 2.1.0 should fix the issue. Sorry for the trouble!

**Comment by UntestedEngineer** [comment]
What if one does not use the helm chart install method?  I am a bit more manual in that I like to control the deployment of individual components.  Wait for 2.1.10?

**Comment by glennmatthews** [comment]
You just need to change the health-check that your container is using - either to `/health/` rather than `/api/`, or calling the CLI `nautobot-server health_check` are our recommendations (we added the documentation https://docs.nautobot.com/projects/core/en/stable/user-guide/administration/installation/health-checks/#nautobot-server-container-in-k8s in the 2.1.9 release)

**Comment by UntestedEngineer** [comment]
Thanks, sorry it was not obvious by looking at the links you referenced without interrogating the helm chart.
