### ISSUE TITLE
Rollback Jobs as Celery Singleton Classes

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#5537]
Turns out the juice was not worth the squeeze in turning Jobs into Celery native task instances. We will rollback to the 1.x architecture of having a celery task which handles the setup, run, and teardown of job executions.

AC:
- Don't break the existing `JobResult.enqueue_job()` pattern
- django celery results should remain, so that we still properly track state
- Access to results should remain the same
- Fixes these issues:
  - #5063
  - #5498
  - #5407
  - #5094
  - #4889
  - #4498 

Stretch goal:
- Implement sub process wrapper(s) to intercept all logging/stdout/stderr
  - If not achieved in this issue, we will address it as a follow on.

**Comment by glennmatthews** [comment]
Initial exploratory work: https://github.com/nautobot/nautobot/compare/u/glennmatthews-5537-celery-rollback
