### ISSUE TITLE
Can not search for parts of IPv6 addresses

### ISSUE THREAD

**Issue by PhillSimonds** [nautobot/nautobot#554]
### Environment
* Python version: 3.6.11
* Nautobot version: 1.0.2

### Steps to Reproduce
1. Under IPAM/Prefixes, create a new IPv6 prefix (e.g. 2001:DB8::/29)
2. After the prefix is created, in the `ipam/prefixes/` view, search for a portion of the prefix (e.g. 2001:DB8)
3. Notice that the created prefix doesn't show up when searched for
4. Search for the full prefix (e.g. 2001:DB8::/29)
5. Notice that the full prefix now shows up

### Expected Behavior
Expected searches for subsets of the prefix to return the prefix in the `ipam/prefixes` view.

### Observed Behavior
Searches for subsets of the prefix do not return the prefix. Only exact searches return the prefix.

**Comment by glennmatthews** [comment]
Probably closely related to #495.

**Comment by jathanism** [comment]
This is related to the fact that we implemented string search for `IPAddress` but not `Prefix` or `Aggregate`. Relatively quick fix by moving the `IPAddressQuerySet.string_search` method to `NetworkQuerySet` base.
