### ISSUE TITLE
Unable to use selection type custom field for dynamic group filter option

### ISSUE THREAD

**Issue by joewesch** [nautobot/nautobot#5545]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.0
* Python version: 3.11.8
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Create a selection type custom field for dcim.device (for my example, I used 'Yes' and 'No' for the choices)
2. Create a dynamic group for dcim.device
3. Edit dynamic group and try to add one of the selection options in the Custom Fields section

### Expected Behavior
It creates a dynamic group of devices that all have that custom field choice

### Observed Behavior
> Errors encountered when saving Dynamic Group associations. See below.

![Screenshot 2024-04-09 at 8 12 59 AM](https://github.com/nautobot/nautobot/assets/10467633/ec476e69-2340-4ead-833a-c2b12ee5705f)

**Comment by glennmatthews** [comment]
Similar to #4353. Needs to be addressed holistically, i.e. #2782.

**Comment by lampwins** [comment]
We currently know of issues with:
- Custom fields (this issue)
- Relationships (https://github.com/nautobot/nautobot/issues/4353)
- Secret groups (also https://github.com/nautobot/nautobot/issues/4353)

**Comment by lampwins** [comment]
In this issue, we will address just custom fields and go after the larger issue in v3.
