### ISSUE TITLE
Jobs from Git Repository not being registered

### ISSUE THREAD

**Issue by TheBirdsNest** [nautobot/nautobot#5550]
### Environment
* Nautobot version (Docker tag too if applicable): v2.1.9
* Python version: 3.11.8
* Database platform, version: Postgres 15.5
* Middleware(s): N/A

### Steps to Reproduce
1. Define a job that has been tested in $JOBS_ROOT and move it to a Git Repository under the root folder /jobs/
2. Define __init__.py files and import the relevant job `from . import example_job`
3. Sync Git repository containing jobs and validate job has been modelled.
4. Trigger job hook (from model update)

### Expected Behavior
The job is created/updated in Nautobot and available (installed). When an object is modified that triggers the related Job Hook, the job is executed. 

### Observed Behavior
The job is successfully created and installed and in the UI we can see the Module, Job Class and Class Path are all present, however when the job is executed, a traceback is raised stating the job has not been registered.

![image](https://github.com/nautobot/nautobot/assets/31070227/25040e61-c69d-403b-821c-5f58855750cf)

![image](https://github.com/nautobot/nautobot/assets/31070227/fdd9e090-bf92-429a-94a5-23de27d7e17b)

Additionally, running the post_upgrade CLI command removes the job from the list of installed jobs.

**Comment by timizuoebideri1** [comment]
I could only reproduce this bug when `JobHookReceiver` is triggered from a `Job` which alters the database.

STEPS to reproduce:

- Create a `Job`(`name`: `Add New Tag`) that adds a new `tag` 
- Create a `JobHookReceiver`(`name`: `Add New Tag Jo Hook Receiver`) that checks if the last tag created color is red.
- Create a git repo for this jobs and sync repo in Nautobot.
- Enable the jobs
- Create a JobHook for `Add New Tag Jo Hook Receiver`, check `Type create`.
 
**TRIAL 1:** 
Add new tag from Tag UI page - (`Add New Tag Jo Hook Receiver` is successful)
![Screenshot 2024-04-11 at 8 21 19 AM](https://github.com/nautobot/nautobot/assets/94907097/2437cd37-e25d-4949-b290-53f617711dda)

**Trial 2**
Run the `Add New Tag` Job - (`Add New Tag Jo Hook Receiver` fails)
![Screenshot 2024-04-11 at 8 06 49 AM](https://github.com/nautobot/nautobot/assets/94907097/e9296679-da84-4167-a11d-38b25b187e24)




NOTE: Also running post_upgrade did not remove the job from installed jobs

**Comment by glennmatthews** [comment]
Would be good to retest and confirm whether this is still an issue after the Job/Git fixes made in v2.2.3 (i.e. #5586).

**Comment by lampwins** [comment]
Let's setup a test repo for jobs and proper integration tests for this.

**Comment by lampwins** [comment]
We should also look into allowing any valid ref instead of just branch names in the GitRepo model.

**Comment by glennmatthews** [comment]
Reading between the lines of the original submission, the error is referencing job `ot_config_firewall.FirewallConfiguration` but the screenshot is showing job `alethia_git_repository.jobs.config_ot_firewall.FirewallConfiguration`. I therefore wonder if the underlying issue here is not actually the Git repository, but maybe that there was a leftover JobHook record still pointing to the $JOBS_ROOT job that had been removed and migrated to the GitRepository.
