### ISSUE TITLE
Import/Export label vs slug

### ISSUE THREAD

**Issue by gmoisio** [nautobot/nautobot#556]
### Environment
* Python version: 3.8.1
* Nautobot version: v1.0.2

### Steps to Reproduce
Try to export object that have "Active" as a characteristic.
The exported CSV contains the label "Active", but the import feature wants the slug "active"

### Expected Behavior
To work without find/replace "Active" with "active" in the CSV file.

Regards

**Comment by glennmatthews** [comment]
Thanks for the report! This is another aspect of the general import/export asymmetry issues we are tracking under #254.

**Comment by gmoisio** [comment]
Thanks for your answer. Sometimes we have the same issue on header names that are not the same between export and import.
Regards
