### ISSUE TITLE
Cannot create custom boolean fields with default value 'false'

### ISSUE THREAD

**Issue by teunvink** [nautobot/nautobot#5563]
### Environment
* Nautobot version (Docker tag too if applicable): 2.1.9
* Python version: 3.10.12
* Database platform, version: 12.12-1
* Middleware(s): N/A

### Steps to Reproduce
1. create a custom field of type boolean
2. set the default value to 'false'
3. save the custom field and look at the properties

### Expected Behavior
The default value should be 'false'

### Observed Behavior
The default value is undefined ("--")

When making this field required, you still need to explicitly select "False" instead of the default value being used when you edit objects using this custom field.

**Comment by teunvink** [comment]
@timizuoebideri1 I did, the quotes were to show what I entered, they were not part of what I entered.

**Comment by gsnider2195** [comment]
Tested on demo, this appears to just be a display issue.

**Comment by timizuoebideri1** [comment]
Bug could not be reproduced:

**Create Custom field of type boolean, false by default and required**
![Screenshot 2024-05-16 at 1 25 16 PM](https://github.com/nautobot/nautobot/assets/94907097/00a78cde-8e7f-4e48-b79c-4c8b3b396f42)

**Custom Field Created**
![Screenshot 2024-05-16 at 1 25 47 PM](https://github.com/nautobot/nautobot/assets/94907097/a1c9b3b4-6bce-4ac7-bbe6-b30232c762c6)

**Configuring the boolean custom field in tenant (leave the value as false)**
![Screenshot 2024-05-16 at 1 26 33 PM](https://github.com/nautobot/nautobot/assets/94907097/ff29fb1b-63e6-45f3-8b11-ab91567e8f8b)

**Boolean showing as X**
![Screenshot 2024-05-16 at 1 26 44 PM](https://github.com/nautobot/nautobot/assets/94907097/2b7ce11e-a623-4c92-9981-1834b67ac657)

@teunvink The screenshot up top shows that there doesn't appear to be a bug.
