### ISSUE TITLE
`ContactAssociationFilterSet.associated_object_type` should use `ContentTypeFilter`

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#5564]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.0

### Steps to Reproduce

https://demo.nautobot.com/api/extras/contact-associations/?associated_object_type=dcim.device

Returns:

```json
{
    "associated_object_type": [
        "Select a valid choice. That choice is not one of the available choices."
    ]
}
```

Compare to queries like:

https://demo.nautobot.com/api/extras/custom-fields/?content_types=dcim.location

which do work as expected.

### Expected Behavior

`associated_object_type` filter should behave like other ContentTypeFilter in Nautobot, allowing user to specify the content-type by app-label + model name, rather than requiring a PK.

### Observed Behavior

Filter requires content-type PK:

https://demo.nautobot.com/api/extras/contact-associations/?associated_object_type=4

**Comment by gsnider2195** [comment]
Also add a generic test to look for this and open an issue to have this added as a rule in pylint-nautobot
