### ISSUE TITLE
Add IPv4 /32 and IPv6 /128 prefix support

### ISSUE THREAD

**Issue by evdzande** [nautobot/nautobot#557]
### Environment
* Python version: 3.7.3
* Nautobot version: 1.0.2

### Proposed Functionality
Add IPv4 /32 and IPv6 /128 prefix support.

### Use Case
In larger subnet pools such as 172.29.240.0/20 we create both loopback /32 addresses and larger subnets such as /29, /30, /31 etc.
Currently if you create for example 172.29.240.1/32 and 172.29.240.2/32 as IP Address and look at the available prefixes you can still see 172.29.240.0/28 as free prefix and also can create prefix 172.29.240.0/28 without a warning. But in reality this prefix is already taken by 172.29.240.1/32 and 172.29.240.2/32.

See also this feature request for netbox from someone else:
https://github.com/netbox-community/netbox/issues/6455

Based on this I changed **/nautobot/ipam/models.py** and **removed** the **lines 557 t/m 565**
And **changed lines 668 to 672** to:
`        # All IP addresses within a point-to-point prefix (IPv4 /31 or IPv6 /127) are considered usable`
`        if (self.prefix.version == 4 and self.prefix.prefixlen >= 31) or (  # RFC 3021`
`            self.prefix.version == 6 and self.prefix.prefixlen >= 127  # RFC 6164`
`        ):`
`            return available_ips`

Which seems to do the trick we are looking for.

**Comment by jathanism** [comment]
I'm not opposed to this. I thought this was weird when I was mucking around changing stuff anyhow. One step closer to IP/Prefix/Aggregate all being the same objects IMO. :)

**Comment by evdzande** [comment]
Is there a time frame to tell when the PR #610 which implements this will be added to a release?
Thanks for your response.
