### ISSUE TITLE
Error raised when creating a DynamicGroup for namespace

### ISSUE THREAD

**Issue by timizuoebideri1** [nautobot/nautobot#5573]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.0
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Add a new Dynamic Group in the UI
2. Select `ipam | namespace` for Content Types
3. Click Create

### Expected Behavior
DynamicGroup created successfully 

### Observed Behavior
![Screenshot 2024-04-15 at 12 45 11 PM](https://github.com/nautobot/nautobot/assets/94907097/4e72404b-52a6-4aec-af84-5975bf1db961)

**Comment by HanlinMiao** [comment]
I think it might be that we are missing a `NamespaceFilterForm`. https://github.com/nautobot/nautobot/blob/4f9b04a4a66d1ab9cdb2e7dc5d728141186d3ef2/nautobot/extras/views.py#L837

**Comment by gsnider2195** [comment]
This should be generally resolved by #2782 but we should have some testing around Namespace DynamicGroups and some defensive coding around this particular situation where `filter_form is None`

**Comment by glennmatthews** [comment]
Confirmed no longer an issue in v2.2.5 after #5714.
