### ISSUE TITLE
Unable to assign tagged VLANs to interfaces when VLAN is in multiple locations

### ISSUE THREAD

**Issue by mdeng10** [nautobot/nautobot#5580]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.0
* Docker tag: ghcr.io/nautobot/nautobot:2.2.0-py3.9
* Python version: 3.9.19
* Database platform, version: AWS Elasticache

### Steps to Reproduce
1. Create a VLAN
2. Assign the multiple locations to the VLAN (new 2.2 feature)
3. Go to any device and attempt to assign the VLAN as a **tagged** to any interface

### Expected Behavior
Return to the interface page and no error

### Observed Behavior
![image](https://github.com/nautobot/nautobot/assets/72052134/14cb03e5-c2a8-47fc-bfcf-817a235549ed)

Likewise, another error occurs if i do the following

1. Remove the multiple locations on the VLAN (just have one location)
2. Assign VLAN to any interface
3. VLAN gets successfully added, however i am no longer able to access the interface, this error pops up

```
<class 'django.urls.exceptions.NoReverseMatch'>

Reverse for 'location' with no arguments not found. 1 pattern(s) tried: ['dcim/locations/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/\\Z']

Python version: 3.9.19
Nautobot version: 2.2.0
```

I saw #5513 but I'm not sure if this is related

Another possibly related error:

When I click on the hyperlinked number of locations in the VLANs page (`nautobot.com/ipam/vlans/`) 
![image](https://github.com/nautobot/nautobot/assets/72052134/136bd8e5-f9b1-4045-b5b1-ef54401839e2)

it returns the following error (regardless if 1 or multiple locations are assigned to the VLAN) 

```
<class 'ValueError'>

Field 'vid' expected a number but got 'c5b1ca60-134f-48d2-b8ce-4d19d5920fff'.

Python version: 3.9.19
Nautobot version: 2.2.0

**Comment by mdeng10** [comment]
I also saw v2.2.1 patchnotes which mentions

> https://github.com/nautobot/nautobot/issues/5009 - Added the option to filter objects with select/multi-select custom fields based on the UUID of the defined custom field choice(s), for example /api/dcim/locations/?cf_multiselect=1ea9237c-3ba7-4985-ba7e-6fd9e9bff813 as an alternative to /api/dcim/locations/?cf_multiselect=some-choice-value.

Is this a fix for the above issue? It doesn't seem to be from a glance

**Comment by glennmatthews** [comment]
Thanks for the report! #5513 is also a new bug but isn't the same issue as this, and #5009 is about custom fields not interfaces/VLANs, so this is a new issue.

**Comment by glennmatthews** [comment]
The third symptom you reported looks like #5123 / #4229.
