### ISSUE TITLE
Plugins not loaded with Gunicorn

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot#5592]
### Environment

* Nautobot version (Docker tag too if applicable): 2.2.1
* Python version: 3.11
* Database platform, version: psql
* Middleware(s):

### Steps to Reproduce
1. Use systemd
2. With gunicorn 21.2.0 or 22.0.0

### Expected Behavior

All applications to show 

### Observed Behavior

We attempted to upgrade our dev environment from 2.1.9 to 2.2.1 but are hitting a weird issue where our plugins are reported as missing.  We are only loading 1 or 2 basic plugins right now while we work on updating all our other plugins for 2.x.  Oddly we are only seeing this issue on 1 out of 3 identical servers with identical Nautobot installs.

This looks very much like this issue from 2021: [Plugin Load Failure · Issue #95 · nautobot/nautobot (github.com)](https://github.com/nautobot/nautobot/issues/95)

**Comment by gsnider2195** [comment]
Re-adding the `nautobot.setup()` call to `nautobot/core/wsgi.py` [here](https://github.com/nautobot/nautobot/pull/5310/files#diff-32ef18b2e4ae31a3c7c252c479ad8929f9b9a304a2924cd4c66a1320c01f126eL7-L15) resolves this issue. @glennmatthews do you see any problems with making this change?
