### ISSUE TITLE
IP Address Roles Similar to Prefix / VLAN Roles

### ISSUE THREAD

**Issue by aetherrealm** [nautobot/nautobot#5634]
### As ...

Austin - Network Automation Engineer

### I want ...

To define my own IP Address Roles like we can with Prefixes.

### So that ...

If I have a prefix whose role is Production Server Data, or something to that effect, an IP address inside of that prefix could have the role of "gateway" (custom made role) or something to that effect.

My use case is right now defining IP Addresses which are Multicast Group IPs.

### I know this is done when...

In addition to the pre-defined IP Address Roles, administrators can define their own roles as well.

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [X] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

Model would need to be edited to allow for creating new entries in that table.

**Comment by glennmatthews** [comment]
Good news! This is already supported in v2. :-) 

![image](https://github.com/nautobot/nautobot/assets/5603551/85cdee6d-e56a-47b9-b7b4-cc087e8b4dcb)

**Comment by lampwins** [comment]
As Glenn pointed out, this is implemented in v2, so I will close this out.
