### ISSUE TITLE
Cloning objects with special characters in a clone_field

### ISSUE THREAD

**Issue by jdueitt** [nautobot/nautobot#5640]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.2
* Python version: 3.10.12
* Database platform, version: postgres, 16.2
* Middleware(s):

### Steps to Reproduce
1. Set a field that is cloned on an object to contain a value that needs to be URL escaped (for instance a Location with the Description "9th & Vine")
![NautobotCloneIssue-0000](https://github.com/nautobot/nautobot/assets/635290/00111b7f-7402-484b-9bcf-3f754268dee8)
3. Press the Clone button on the environment

### Expected Behavior
The URL for creating the clone instance would be: https://nautobot.example.com/dcim/locations/add/?location_type=c1c796ba-fc7c-4f4c-8c03-a9378d220890&status=b43753f4-8814-47ad-a780-2883924eb795&parent=64965d9d-3fb5-4ae1-9a22-03937a1a3653&description=9th%20%26%20Vine

The Description field contains the value "9th & Vine"

### Observed Behavior
The URL created is The URL for creating the clone instance would be: https://nautobot.example.com/dcim/locations/add/?location_type=c1c796ba-fc7c-4f4c-8c03-a9378d220890&status=b43753f4-8814-47ad-a780-2883924eb795&parent=64965d9d-3fb5-4ae1-9a22-03937a1a3653&description=9th%20&%20Vine

The Description field contains the value "9th "
![NautobotCloneIssue-0001](https://github.com/nautobot/nautobot/assets/635290/4bbec75a-b2ae-4c6a-9926-1ad599584457)

**Comment by jdueitt** [comment]
I wanted to also comment, that I have a unit test and a PR I'll be generating shortly to fix this bug. It was impacting a production environment, so we had already patched our installs.

**Comment by glennmatthews** [comment]
Thank you @jdueitt - that's the best kind of bug report, one that already has a fix ready! 😃

**Comment by jdueitt** [comment]
@glennmatthews I always try to fix problems (unlike my usual users). Let me know if the PR looks good or if you or the team have any feedback.
