### ISSUE TITLE
Add Family column to Device Types table

### ISSUE THREAD

**Issue by EdificomSA** [nautobot/nautobot#5655]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.3
* Python version: 3.11
* Database platform, version: postgres 15
* Middleware(s):

### Steps to Reproduce
1. Go to Device Types list https://demo.nautobot.com/dcim/device-types/
2. Try to add Family in Table Configuration
3. Family is not in the list of available columns

#3559 #5040 
https://github.com/nautobot/nautobot/blob/42440ebd9b381534ad89d62420ebea00d703d64e/nautobot/dcim/tables/devicetypes.py#L95

### Expected Behavior
Family column can be selected in Device Types list

### Observed Behavior
Family column is not in the list of available columns

**Comment by glennmatthews** [comment]
Thanks for the report!
