### ISSUE TITLE
Metadata type model

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#5663]
Create a new model for representing the type of a metadata instance. This will be very similar in nature to custom fields types and in fact will likely share some of the same internals. Core provided types will include:

- DateTime
- Date
- Text
- Selection
- Multi selection
- JSON
- URL
- Integer
- Boolean
- Markdown

Other fields:
- name
- description

Note that datatime does not exist as a custom field type. We may add it as a part of this work.

For metadata specifically, we need to also support Contacts as a type.

**Comment by igpaec** [comment]
It would also be nice to have a "Floating Point Number" data type for this feature and the custom fields.
