### ISSUE TITLE
ObjectMetadata Model

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#5664]
Using a MetadataType allow of the association of the relevant data value to a field or set of fields on an object instance, or to the entire object.

We will implement the ability to view this data in the object detail views and in a new list view for metadata, but there will be no UI to manipulate metadata to begin with. The REST API and ORM will be the means to manage this metadata.

For the detail views, we will begin with a separate tab that shows a table of metadata objects filtered to the given model instance. In the future, we will enhance the UI to do tooltip, or hover, etc icons on the field values that the metadata is attached too.

Fields:
- FK to MetadataType
- JSON field for the actual value
- GFK to the assigned object
- Arrayfield[Charfield] for scoped fields (only direct fields on the model) (empty array implies all fields/entire model instance)
- FK to contact
- FK to team

BaseModel + ChangelogModel for now (more features later if they are warrented)

Unique together is MetadataType + assigned object + scoped fields. Likely will have be implemented in python.

Index on:
- GFK to the assigned object
- GFK to the assigned object + scoped fields
- GFK to the assigned object + contact
- GFK to the assigned object + team

**Comment by glennmatthews** [comment]
Reopening as the initial UI work for this model is not yet completed.
