### ISSUE TITLE
Exception thrown when deleting Software Version or Image from list views

### ISSUE THREAD

**Issue by Dav-C** [nautobot/nautobot#5669]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.3
* Python version: 3.11
* Database platform, version: PostgreSQL
* Middleware(s):

### Steps to Reproduce
1. Create a Software Version object
2. Create a Software Image File object and associate it with the Software Version object.
3. Associate a device with the new software and image objects
4. Delete either of the new objects using bulk delete from their respective list views.

### Expected Behavior
An warning should be displayed because of the protected relationships.

### Observed Behavior
AttributeError and traceback

**Comment by timizuoebideri1** [comment]
The error is raised in `handle_protectederror` when trying to get the `absolute_url` of a model that do not have a view I.e `DeviceTypeToSoftwareImageFile`

```python
def handle_protectederror(obj_list, request, e):
    ...

    err_message += format_html_join(
        ", ",
        '<a href="{}">{}</a>',
        ((dependent.get_absolute_url(), dependent) for dependent in protected_objects[:50]),
    )
    ...
```

A view for this model could be added or we skip attaching href to models without to an `absolute_url`
