### ISSUE TITLE
Unable to apply filter in Tenant Group UI view

### ISSUE THREAD

**Issue by timizuoebideri1** [nautobot/nautobot#5680]
### Environment
* Nautobot version (Docker tag too if applicable):v2.3.0
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Visit Tenant Group UI view
2. Click on the filter button
3. Select any filter combination
4. Click Apply

### Expected Behavior
Filtering is applied

### Observed Behavior
Nothing happens when you click on the Apply button

**Comment by glennmatthews** [comment]
Likely the same issue as #5690 - TenantGroup doesn't have a non-dynamic FilterForm either.

**Comment by glennmatthews** [comment]
Closing as a duplicate of #5690.
