### ISSUE TITLE
Search and Filter Unresponsive on Namespaces list view

### ISSUE THREAD

**Issue by mattmiller87** [nautobot/nautobot#5690]
### Environment
[demo.nautobot.com](https://demo.nautobot.com/ipam/namespaces/)

### Steps to Reproduce
1. Click the search field, type in "Global", then click search
Alternatively
1. Open the Filter box, Set the following: Field - Name, Lookup type - exact, Value - "Global"
2. Click Apply
In both cases, nothing happens.

### Expected Behavior
The search or the apply should trigger a filter on the ipam/namespaces api

### Observed Behavior
Nothing happens.

**Comment by glennmatthews** [comment]
`Uncaught TypeError: document.getElementById(...) is null`. Looks like this is probably happening because we don't have a non-dynamic `NamespaceFilterForm` defined, only the dynamic filter form.

**Comment by glennmatthews** [comment]
Let's go ahead and add FilterForms for Namespace and TenantGroup (#5680) and add some tests asserting that every list view has a filterform.
