### ISSUE TITLE
is_truthy() Pylint Error

### ISSUE THREAD

**Issue by mattmiller87** [nautobot/nautobot#5696]
https://github.com/nautobot/nautobot/blob/d4a0dee26ddf6acb386a84eb75abfad56ff429dc/nautobot/core/settings_funcs.py#L30

R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)

does this make sense as a fix?
```
    return_value = None
    if val in ("y", "yes", "t", "true", "on", "1"):
        return_value = True
    elif val in ("n", "no", "f", "false", "off", "0"):
        return_value = False
    else:
        raise ValueError(f"Invalid truthy value: `{arg}`")
    return return_value
```

**Comment by glennmatthews** [comment]
Experimenting with turning on additional currently-disabled pylint rules?

I'd think what pylint is trying to steer you towards is:

```python
    if val in ("y", "yes", "t", "true", "on", "1"):
        return True
    if val in ("n", "no", "f", "false", "off", "0"):
        return False
    raise ValueError(f"Invalid truthy value: `{arg}`")
```
