### ISSUE TITLE
Git imported template immediately removed during import

### ISSUE THREAD

**Issue by u1735067** [nautobot/nautobot#570]
### Environment
* Python version: 3.6
* Nautobot version: 1.0.2

### Steps to Reproduce
1. Create Git repo with /export_templates/ipam/vlan/html_export.html export template
2. Add Git repo in Nautobot
3. Launch (or relaunch) sync

### Expected Behavior
Template is imported and kept

### Observed Behavior
Template is imported and then immediately removed, in log we can observe: 
```
worker_1 | 11:52:36.095 INFO nautobot.datasources.git :
worker_1 | Loading `ipam.vlan` export template from `text_export.html`
worker_1 | 11:52:36.179 INFO nautobot.datasources.git :
worker_1 | Successfully created export template
worker_1 | 11:52:36.190 WARNING nautobot.datasources.git :
worker_1 | Deleted export template [GitLab] ipam | VLAN: text_export.html
```

This seems to be caused by https://github.com/nautobot/nautobot/blob/v1.0.2/nautobot/extras/datasources/git.py#L694, where `template_record.content_type.name` (=`VLAN`) is used instead of `template_record.content_type.model` (=`vlan`), may I submit a PR with this change?

**Comment by glennmatthews** [comment]
Thank you for the report and for the analysis! I agree with your analysis; please do feel free to submit a PR that fixes this and adds an appropriate unit test covering this issue.

**Comment by u1735067** [comment]
While I have a PR ready for the fix, I don't have the tests parts and cannot work on it until maybe wednesday because of workstation lacking ressources for another dev environment, so I'll then look into it, if you haven't already completed it by this time.
