### ISSUE TITLE
SAML issue in Nautobot 2.2.4 (lxml & xmlsec libxml2 library version mismatch)

### ISSUE THREAD

**Issue by gioccher** [nautobot/nautobot#5709]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.4
* Python version: 3.9
* Database platform, version: MySQL
* Middleware(s):

### Steps to Reproduce
1. Dockerfile snippet
```
FROM networktocode/nautobot:2.2.4-py3.9
USER 0
RUN apt-get install -y patch gcc libxmlsec1-dev libxmlsec1-openssl pkg-config
USER nautobot
RUN pip install --no-binary=lxml "nautobot[sso]==2.2.4"
```
3. enable SAML in nautobot config
4. open home page

### Expected Behavior
nautobot home page loads

### Observed Behavior
lxml & xmlsec libxml2 library version mismatch
![image](https://github.com/nautobot/nautobot/assets/921538/77bbfd12-1cc5-40b7-b1a4-196851db1089)

**Comment by glennmatthews** [comment]
Thanks for the report! Appears to be due to a recent update to `xmlsec` package publishing. Should be resolved by #5707.
