### ISSUE TITLE
Cloud Account model

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#5719]
Implement the Cloud Account model for tracking provider account details.

CloudAccount:
- name
- description
- account number (char field)
- provider (FK to manufacturer)
- secret group

This will be created in the new cloud app.

**Comment by glennmatthews** [comment]
@HanlinMiao Is the UI for this model completed, or is that being tracked by a different issue?

**Comment by HanlinMiao** [comment]
Sorry movd the issue to the closed column by accident. Reopening it now.
