### ISSUE TITLE
Can't add VLAN to Tagged or Access VM Interface

### ISSUE THREAD

**Issue by tcrowe-aop** [nautobot/nautobot#5738]
-->
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.3
* Python version: 3.10.12
* Database platform, version: PostgreSQL 14.10
* Middleware(s):

### Steps to Reproduce
1. Add VLANs to Nautobot
2. Create a Virtual Machine with at least one interface
3. After creating the VM interface, edit the interface and change the 802.1q mode to tagged or access.
4. Try to add a tagged or untagged vlan to the interface.

### Expected Behavior

Expect to get a selectable list of configured VLANs 

### Observed Behavior

The words "No results found" are displayed.

**Comment by glennmatthews** [comment]
Per discussion on Slack, the UI is sending the API query `/api/ipam/vlans/?q=&limit=50&offset=0&depth=0&locations=null&location=487e4ef2-e9e7-4033-a469-b9d679d28203`, i.e. mixing the `location` and `locations` query parameters in an unintended fashion.
