### ISSUE TITLE
Virtual Machine has no add IP address to interface button

### ISSUE THREAD

**Issue by byrn-baker** [nautobot/nautobot#5775]
### Environment
* Nautobot version (Docker tag too if applicable): Nautobot:2.2.0
* Python version: 3.11
* Database platform, version: Postgress
* Middleware(s): 

### Steps to Reproduce
1. Create a virtual Machine from the gui
2. add an interface to virtual machine
3. There is no way to add an IP address to the VM interface from the gui

### Expected Behavior
When creating a virtual machine interface expected to have the same green plus sign to add  and assign an IP address to the VM interface

![nautobot-vm-interface](https://github.com/nautobot/nautobot/assets/82524710/9ec0b7bc-0f26-476d-842a-fe12c5457078)

### Observed Behavior
There is no way to add an IP address to the VM interface

**Comment by glennmatthews** [comment]
Looks like a miss in #4224. Shouldn't be too difficult to implement with very similar code.
