### ISSUE TITLE
Able to assign non parent/child device to a device bay via ORM

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot#5796]
### Environment
* Nautobot version (Docker tag too if applicable): 2.1.2
* Python version: 3.9
* Database platform, version: Postgresql
* Middleware(s): Docker

### Steps to Reproduce
1. Create a location.  Assign all below new objects to this location
2. Create a rack
3. Create a device type named "chassis" in Nautobot.  Assign it parent status.
4. Create a device type named "server" in Nautobot.  Do not assign it parent or child status.
5. Create a device type named "blade" in Nautobot.  Assign it child status.
6.  Create a parent device named "chassis1" in Nautobot with device type "chassis".  Create a device bay for it.  Assign to the above location and rack.  Add to a rack slot
7. Create a third device named "blade1" in Nautobot with device type "blade".  Assign to the above location and rack.
8. Create another device named "server1" in Nautobot with device type "server".  Assign to the above location and rack. Do not add to rack slot
9. In the UI, attempt to assign device "server1" to the device bay in device "chassis1".  It should NOT appear in the dropdown.  The only device that should appear in the dropdown is "blade1"
10. In the ORM, run the following commands:

```python
chassis = Device.objects.get(name="chassis1")
server = Device.objects.get(name="server1")
bay = chassis.device_bays.first()
bay.installed_device = server
bay.validated_save()
```

### Expected Behavior
The `validated_save()` function for the device_bay should NOT allow a device without the `child` assignment to be assigned to a device bay.  The UI already filters out these devices.

### Observed Behavior
The `validated_save()` function allows the device to be assigned to a device bay.

**Comment by glennmatthews** [comment]
Confirmed that there's no check for this case in `DeviceBay.clean()`, only a queryset restriction in `PopulateDeviceBayForm.__init__()`.
