### ISSUE TITLE
GraphQL Device Query - Role filter issue

### ISSUE THREAD

**Issue by veprimk** [nautobot/nautobot#58]
### Environment
* Python version: Not known using https://demo.nautobot.com/
* Nautobot version: v1.0.0b1

### Steps to Reproduce
1. Open Nautobot Demo on https://demo.nautobot.com/
2. Click GraphQL at the footer
2. Try to query for Devices where role = "Backbone" using the GraphQL query below:
```
{ 
  devices(role: "Backbone") {
    id,
    name
  }
}
```

### Expected Behavior
Exected two see the two Backbone devices 
```
{
  "data": {
    "devices": [
      {
        "id": "7b871f65-d4d5-4ab5-8fd5-211a8e093976",
        "name": "jcy-bb-01.infra.ntc.com"
      },
      {
        "id": "bfcd2323-5b32-4388-af61-05a7ed1404f7",
        "name": "nyc-bb-01.infra.ntc.com"
      }
    ]
  }
}
```

### Observed Behavior
I am getting all the devices instead:
```
{
  "data": {
    "devices": [
      {
        "id": "60833d08-7bdd-4b40-a8c4-33c1984ccc90",
        "name": "ams-edge-01"
      },
      {
        "id": "c8886c88-6eff-4c4f-a079-4ef16b53d4f6",
        "name": "ams-edge-02"
      },
      {
        "id": "eee88e11-107f-4f19-b341-cbc6a61d7ab5",
        "name": "ams-leaf-01"
      },
      {
        "id": "fde5a607-4014-41c7-90bb-753dfc0f621c",
        "name": "ams-leaf-02"
      },
      {
        "id": "7815a8a8-ab8e-407a-a998-1f2ec961f06c",
        "name": "ams-leaf-03"
      },
      {
        "id": "8fa89044-c16f-497d-be85-03647a19433b",
        "name": "ams-leaf-04"
      },
      {
        "id": "6c71fd4f-15d8-4a6e-ae71-3fb82c809713",
        "name": "ams-leaf-05"
      },
      {
        "id": "a85ac1aa-094f-4de9-8ba6-16cb088a1b74",
        "name": "ams-leaf-06"
      },
      {
        "id": "7dc8d292-98fc-438e-b01e-962002ac5403",
        "name": "ams-leaf-07"
      }
     **** Omitted for brevity ****
    ]
  }
}
```

### Further check
If I filter by role_id and use the id of the "Backbone" role it works:

Query:
```
{ 
  devices(role_id: "28f69768-f251-49ee-976e-41e190dfd672") {
    id,
    name
  }
}
```

The output is as expected:

```
{
  "data": {
    "devices": [
      {
        "id": "7b871f65-d4d5-4ab5-8fd5-211a8e093976",
        "name": "jcy-bb-01.infra.ntc.com"
      },
      {
        "id": "bfcd2323-5b32-4388-af61-05a7ed1404f7",
        "name": "nyc-bb-01.infra.ntc.com"
      }
    ]
  }
}
```

**Comment by jathanism** [comment]
In this particular case, it appears that the `devices.role` filter is filtering on the `Device.device_role.slug` field and not the `name` field:

To illustrate this, I attempted a filter on `Backbone` and got the unfiltered results, which IMO is not the expected behavior if the filter parameter is incorrect. You'd think it would return no matches instead of all?

Query on `Backbone`:
```graphql
{
  devices(role: "Backbone"){
    id
    name
    device_role {
      name
      slug
    }
  }
}
```

Result (first item only):
```graphql
{
  "data": {
    "devices": [
      {
        "id": "60833d08-7bdd-4b40-a8c4-33c1984ccc90",
        "name": "ams-edge-01",
        "device_role": {
          "name": "edge",
          "slug": "edge"
        }
      },
```

Then I did it with `backbone`:

```graphql
{
  devices(role: "backbone"){
    id
    name
    device_role {
      name
      slug
    }
  }
}
```

With this result, matching your expected results:

```graphql
{
  "data": {
    "devices": [
      {
        "id": "7b871f65-d4d5-4ab5-8fd5-211a8e093976",
        "name": "jcy-bb-01.infra.ntc.com",
        "device_role": {
          "name": "Backbone",
          "slug": "backbone"
        }
      },
      {
        "id": "bfcd2323-5b32-4388-af61-05a7ed1404f7",
        "name": "nyc-bb-01.infra.ntc.com",
        "device_role": {
          "name": "Backbone",
          "slug": "backbone"
        }
      }
    ]
  }
}
```

Can you please confirm?

**Comment by veprimk** [comment]
I can confirm the same.

If the filters are coming from [here](https://github.com/nautobot/nautobot/blob/8176cae71e22376fa2b0ec1ded6af7bdbb6c8c89/nautobot/dcim/filters.py#L612).
Upon further research based on your comment, it seems that this might be a known issue with MultipleChoice Filter where filtering is becoming a NOOP due to no choice being present (assuming incorrect filter choice == no filter). This is based on this [documentation of the filter](https://django-filter.readthedocs.io/en/stable/ref/filters.html#multiplechoicefilter).

**Comment by carbonarok** [comment]
Similar issue: DjangoFilterConnectionField
