### ISSUE TITLE
"Mark As Planned" on interface connection does not work

### ISSUE THREAD

**Issue by JonathanNathanson** [nautobot/nautobot#5804]
### Environment
* Nautobot version (Docker tag too if applicable): v2.1.5 (have also tested on Nautobot Demo site which is running v2.2.5 at time of writing)
* Python version: 3.11
* Database platform, version: MySQL
* Middleware(s): None

### Steps to Reproduce
1. Navigate to Devices -> Interfaces Tab
2. Click "Mark as Planned" button on an interface which has a connected cable

### Expected Behavior
The cable status to be updated to "Planned"

### Observed Behavior
Nothing happens, developer tools shows API response to `PATCH /api/dcim/cables/c98e8fb7-9a3a-436c-9cf7-dad023650a4f/`:
```
{
    "detail": "Unsupported media type \"application/x-www-form-urlencoded; charset=UTF-8\" in request."
}
```
Indicating that the API endpoint does not expect to receive FormData, but more likely is expecting a JSON body.

**Comment by itdependsnetworks** [comment]
I can confirm this issue.

**Comment by glennmatthews** [comment]
Related: #3124, #2936, #2644.
