### ISSUE TITLE
Assign IPAddress: No error message when submitting an empty form

### ISSUE THREAD

**Issue by Phill93** [nautobot/nautobot#5811]
### Environment
* Nautobot version (Docker tag too if applicable): v2.1.8
* Python version: 3.9
* Database platform, version: Postgres 13.14
* Middleware(s): -

### Steps to Reproduce
1. Open the add an ip address form for an interface
2. Switch to assign an ip address
3. Search for an ip address
4. Do not check anything but click on "Assign selected IP addresses to the interface"

### Expected Behavior
Error Message

### Observed Behavior
=> UI Breaks

**Comment by gsnider2195** [comment]
Thanks for the report @Phill93 !

The only way to get to the `ipam:ipaddress_assign` view is through the "Assign IP address" button on the device interface tab here:

![image](https://github.com/nautobot/nautobot/assets/75227981/e036b997-0eb1-444b-99ef-198ba38b136b)


I think we may have intended to remove this view entirely after #2403. We should either fix this bug or remove the view and associated button.

**Comment by glennmatthews** [comment]
I don't think we want to remove this functionality - in fact IIRC we specifically restored it via #4224. If I'm reading the report correctly, the error specifically happens if you try to submit the form without selecting any IP? That seems like it should be reasonably straightforward to address.
