### ISSUE TITLE
SavedView modal JSON field is white in dark mode

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot#5814]
### Environment
* Nautobot version (Docker tag too if applicable): next (2.3)
* Python version: 3.11
* Database platform, version: Postgres 13
* Middleware(s):

### Steps to Reproduce
1. Switch to Dark Mode
2. Go to any list view (Ex. Devices)
3. Click Saved Views - Save As New View 

### Expected Behavior
The "New Changes" field is rendered in Dark Mode colors.

### Observed Behavior
The "New Changes" field is white.

**Comment by gsnider2195** [comment]
![image](https://github.com/nautobot/nautobot/assets/75227981/1f36f0d0-98ab-4652-96ff-2acab004fc50)

**Comment by gsnider2195** [comment]
```html
<code class="language-json hljs" style="background-color: #F2F2F2;" data-highlighted="yes">
```
