### ISSUE TITLE
Git repo jobs across multiple works do not seem to be in sync Nautobot 1.6

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#5816]
Python 3.10
Nautobot 1.6
Design builder 1.2

As a network automation engineer, I want jobs sourced from git repos to be in sync, when they are run, no matter which of multiple available workers the job lands on.

In environments with multiple workers, it can be observed where git repo syncs happen successfully but subsequent runs of a job that land on different workers either cannot find the job, or run outdated versions of the job.

Additionally, in the case of design builder, ancillary files are also subject to these same symptoms (yaml files for the designs).

**Comment by lampwins** [comment]
With the eventual consistency model for git repo syncing, please include in the job logs that they repo is being synced to a specific commit.

**Comment by gsnider2195** [comment]
Potential fixes from `develop`: #5825 #5828

**Comment by gsnider2195** [comment]
Pending confirmation that this specific issue can be fixed by using the correct directory structure for design builder git repos
