### ISSUE TITLE
GitRepository URL Validator does not allow for local DNS URLs

### ISSUE THREAD

**Issue by MeganerdDev** [nautobot/nautobot#5819]
### Environment
* Nautobot version (Docker tag too if applicable): v2.2.25
* Python version: 3.11
* Database platform, version: PG15
* Middleware(s): N/A

### Steps to Reproduce
1. Navigate to `extras/git-repositories` in the Nautobot UI
2. Press the `Add` button to begin creating a new GIT Repository object
3. On the `Remote URL` charfield entry provide a local DNS name eg: `https://local-dns-example/golden-config-backup.git`
4. Fill in remaining required entries and press `Update & Sync` button

### Expected Behavior
Object created and syncs as normal operation

### Observed Behavior
URL validator throws an error preventing creation of the object
![image](https://github.com/nautobot/nautobot/assets/114895043/fe48edd2-e6d4-4afb-897a-2f5af08d6408)

### Additional Details

- I wasn't sure if this would be a feature request or a bug report. I ended up with bug report.

- [URLValidator](https://github.com/nautobot/nautobot/blob/eb1a1796fce4be45d7086137f551e5f46e64e1a3/nautobot/extras/models/datasources.py#L9) is upstream and provided by Django
`from django.core.validators import URLValidator`

- URLValidator in [Django](https://github.com/django/django/blob/fa7848146738a9fe1d415ee4808664e54739eeb7/django/core/validators.py#L127-L209)

**Comment by MeganerdDev** [comment]
I was able to mitigate this over the ORM for now
```python
from nautobot.extras.models import GitRepository

GitRepository.objects.create(
    name="test",
    slug="test",
    remote_url="https://local-dns-example/golden-config-backup.git",
    branch="main"
)
```

Also unrelated to the URL Validator for local DNS names, but local pathfiles might also be considered during any refactoring change that is done to this entry? I had a separate case where I worked around this by creating the object over ORM

**Comment by glennmatthews** [comment]
Nautobot has a custom `nautobot.core.models.validators.EnhancedURLValidator` that supports hostnames, it looks like it might just be as simple as fixing the `GitRepository` definition to use that instead of Django's default `URLValidator`.

**Comment by glennmatthews** [comment]
Similarly the form itself needs to use `nautobot.core.forms.fields.LaxURLField` instead of Django's `forms.URLField`.
