### ISSUE TITLE
Column role is missing under device -> interfaces (and the configure button does nothing)

### ISSUE THREAD

**Issue by dainok** [nautobot/nautobot#5841]
### Environment

* Nautobot version: `next`
* Python version: `3.9.6`
* Database platform, version: Postgres
* Middleware(s):

In next version, https://github.com/nautobot/nautobot/pull/5488#issuecomment-2187099350 is implementing interface roles. In the interface table, under a specific device, role is not displayed and the `configure` button does nothing.

### Steps to Reproduce

1. Go to: https://next.demo.nautobot.com/dcim/devices/eaeca318-23f3-4ef0-805c-fceb9d23a0dd/interfaces/ (ams01-leaf-01)
2. Go to Interfaces
3. See `Roles` is missing from the table and pressing `configure` does nothing.

### Expected Behavior

I expect the `configure` button help me to add the `role` column. Also the `role` column should be displayed by default.

### Observed Behavior

`Roles` is missing from the interface table (under a specific device) table and pressing `configure` does nothing.

**Comment by glennmatthews** [comment]
The breakage of the `configure` button is tracked in #5818. This issue will cover adding the `Role` column to the `DeviceModuleInterfaceTable` class as a default column
