### ISSUE TITLE
Object Details UUID

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot#585]
### User Story

As **Austin the Network Automation engineer** I am often working within Postman building out my automation
  *I want to* be able to easily visualize the UUID's of objects in the UI 
  *so that* when I am building queries in Postman I can quickly copy the UUID to test API calls. 
  *I will know this is done when* every detailed object page has the UUID visible.

As **P.D. the Plugin Developer** I am often working within Postman building out my plugin
  *I want to* be able to easily visualize the UUID's of objects in the UI 
  *so that* when I am building queries in Postman I can quickly copy the UUID to test API calls. 
  *I will know this is done when* every detailed object page has the UUID visible.

As **Nelly the Network Engineer** I am often working in GraphQL building out my test queries
  *I want to* be able to easily visualize the UUID's of objects in the UI 
  *so that* when I am building my GraphQL queries to test GraphQL against various devices and objects using the query variables
  *I will know this is done when* every detailed object page has the UUID visible.

### Database Changes (Optional)

No

### External Dependencies (Optional)

No

**Comment by glennmatthews** [comment]
Thanks for the feature request! In my opinion this would best be implemented as a part of #479.

**Comment by jedelman8** [comment]
@glennmatthews did this by chance make it into #479 ?

**Comment by glennmatthews** [comment]
To the best of my knowledge, it did not - it should be an easy addition to make though now that #479 is in place.

**Comment by dgarros** [comment]
I don't mind doing this one if we can agree on how we want it to look like
After looking at the code, I think it would be easy to add it to the `created_updated.html` template from `core/teemplates/inc`

We could add the UUID one the same line as  created / updated info

<img width="1665" alt="Screen Shot 2021-08-30 at 3 58 14 PM" src="https://user-images.githubusercontent.com/304126/131397725-2bac49fd-fcf9-4327-a59f-4d24ad847808.png">

or we could add it below

<img width="1668" alt="Screen Shot 2021-08-30 at 3 57 13 PM" src="https://user-images.githubusercontent.com/304126/131397742-862a3830-4461-42dc-b026-4547a09e9c42.png">

thoughts ?

**Comment by glennmatthews** [comment]
It would belong in the base `object_detail.html` template rather than the `inc/created_updated.html` template, IMO. Do you think it's visible enough in that location/font? Just to throw another option out there, though perhaps this is *too* visible... :-)

![image](https://user-images.githubusercontent.com/5603551/131401639-e18e49d7-a726-4c1a-85e3-f3a9822f5c49.png)

**Comment by jedelman8** [comment]
> Do you think it's visible enough in that location/font?

How visible do we need this?

I do think those 3 ideas are _too much_ in the user's face.

Here are a few more ideas:

What about the idea of creating a new table (always in the bottom left half of the template beneath tags) called "Details" or "Object Details" and for now, it has one row for UUID? This table could also include date created, last updated, etc. timestamps too.

Another idea is embedding this as the first line within the Change Log tab.  Definitely wouldn't be front and center, but once users start to know it's there, they'd know right where it is

One final idea is putting it at the very bottom left not in a table, see below:

![image](https://user-images.githubusercontent.com/6332586/131506718-87dbe66d-632f-4cd5-833e-1a168f166e08.png)

**Comment by jathanism** [comment]
> > Do you think it's visible enough in that location/font?
> 
> How visible do we need this?
> 
> I do think those 3 ideas are _too much_ in the user's face.
> 
> Here are a few more ideas:
> 
> What about the idea of creating a new table (always in the bottom left half of the template beneath tags) called "Details" or "Object Details" and for now, it has one row for UUID? This table could also include date created, last updated, etc. timestamps too.
> 

IMO I think this is the best idea. It's a primary field (the primary **key** in fact), so it should be up top and prominent. And let's make sure it has a copy button like we have on `Device.hostname` in the Device detail view.

**Comment by glennmatthews** [comment]
Implemented in `next` (upcoming 1.2 release) by #933.
