### ISSUE TITLE
Consolidate list view bulk action buttons

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#5869]
Use a bootstrap split button dropdown (drop up) to consolidate common bulk action buttons in all list views.

The primary action should be edit, the dropdown should contain "update groups" and a line separated delete (in red).

In case of custom bulk actions like the device list view (add components), leave those alone for now. Specifically for add components, convert to a drop up.

Standardize that this primary/edit group is the first set of buttons and all others come after it. Look through core for other places where this needs to be updated.

<img width="563" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjZmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f715bc56278c85f14f6e9aaeb104318452f768c/Screenshot%202024-06-28%20at%202.45.56%E2%80%AFPM.png" alt="Screenshot 2024-06-28 at 2.45.56 PM.png" />

**Comment by glennmatthews** [comment]
Implemented by #5885.
