### ISSUE TITLE
CSS Static page linking error in either install documentation or in the /opt/nautobot/contrib file.

### ISSUE THREAD

**Issue by syyna** [nautobot/nautobot#59]
### Environment
* Python version:3.8.5
* Nautobot version: 1.0.0b1

### Steps to Reproduce
1. Follow the installation docs for http server: https://nautobot.readthedocs.io/en/latest/installation/5-http-server/
2.  When you get to the step of Confirm Connectivity, it will fail.  A static error for CSS errors will come up when you try to browse to the server page.

### Expected Behavior
1.  Expect to see the home page of nautobot.

### Observed Behavior
1.  You get a Static error CSS not found page.

### Root Cause
1.  The root cause for this error is because the static page linked in the /opt/nautobot/contrib/apache.conf (or nginx.conf) links to a non-existent directory.

When you git clone the repo, you get a /opt/nautobot/nautobot/project-static directory, and the .conf files references to /opt/nautobot/static instead.  I'd open a PR for this, but i'm not sure whether this is a documentation error, or a contrib config file error, so not sure which file to put the PR for.  Either way, should be a super easy fix.

**Comment by glennmatthews** [comment]
Thank you for opening this issue! We definitely need to clarify the docs here.

Just as a general note to hopefully make sure you're not blocked in the meantime, you generally shouldn't be pointing to `/opt/nautobot/nautobot/project-static`, but should instead be pointing to wherever `nautobot-server collectstatic` is copying the static files to. This is the `STATIC_ROOT` value in `settings.py`/`nautobot_config.py`, and if you haven't overridden it explicitly or set the `$NAUTOBOT_BASE_STORAGE_DIR` environment variable, it defaults to `~/.nautobot/static`.

We'll get the docs updated, thanks!

**Comment by jathanism** [comment]
Thanks for the report @syyna! Should have some totally new install docs in the coming days.

**Comment by jathanism** [comment]
Will be fixed in #62
