### ISSUE TITLE
support and have a defined a way to inject breadcrumbs via plugins

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#590]
### Proposed Functionality

For the vast majority of plugins, there are no breadcrumbs to ease UI navigation for users.  There are no standards around this and defined or blessed API to allow plugin developers to have breadcrumbs at the top of each of page in a given plugin.  This proposal is to create a defined API to simplify breadcrumbs for plugin developers. 

### Use Cases

As P.D. the plugin developer,
I want to add breadcrumbs to my plugin,
So that users can more easily know where they are and navigate within the plugin,
I will know this is done when:
* There is a defined API I can use when creating plugins.

As Ozzie the operator,
I want to know exactly where I am in the UI and easily navigate within a plugin,
So that I can think less of what I'm looking at and just know from the breadcrumbs while also not being forced to use a dropdown item to change pages within the plugin :) 
I will know this is done when:
* My fellow plugin developers have a defined way to add breadcrumbs ensuring the vast majority of plugins get breadcrumbs!

**Comment by glennmatthews** [comment]
Relates to #479 - if we have a well-defined detail view template, this will make it easier to consistently add and enforce breadcrumbs.

**Comment by glennmatthews** [comment]
Addressed by #737.
