### ISSUE TITLE
Vlan Group overhaul

### ISSUE THREAD

**Issue by mzbroch** [nautobot/nautobot#5903]
### As ...

Austin - Network Automation Engineer

### I want ...

Vlan Group model to be more advanced and provide new capabilities 

### So that ...

I can more efficiently group my Vlans.

### I know this is done when...

- `Vlan Group` has `.role`
- `Vlan Group` has GFK `scope` Location, Cluster, ClusterGroup
- `Vlan Group` has `min_vid`, `max_vid` or range in format `[1-10, 30-50, 99]`
- `VLANGroup` has tags

Related to #526 and #529

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Apps (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by HanlinMiao** [comment]
Sorry, do you mind explaining the purpose of the `scope` GFK within the context of this issue? VLANGroup also already has a `location` attribute, would that be confusing when `scope` is pointed to a location?

**Comment by mzbroch** [comment]
> Sorry, do you mind explaining the purpose of the `scope` GFK within the context of this issue? VLANGroup also already has a `location` attribute, would that be confusing when `scope` is pointed to a location?

I think group of vlans can be also related to a cluster or a rack etc. The GFK list in first post is not complete, but I think we could point vlanGroup to more objects (not only to location)

**Comment by glennmatthews** [comment]
Sounds very similar to #606.
