### ISSUE TITLE
Homepage and Job Result detail view bog down when job result contains a large input file

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#5904]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.7

### Steps to Reproduce
1. Export the 12303 Interface records on demo.nautobot.com to a CSV file (roughly 7 MB in size)
2. Upload this file as input to the CSV Import job on another Nautobot instance and run it to completion (it will fail, this is expected)

### Expected Behavior

Nautobot UI to remain adequately performant

### Observed Behavior

At least the Nautobot home page and the Job Result detail view take a tremendously long time to load while this JobResult record is present, likely due to the replication of the entire CSV file contents into several of the JobResult JSON fields (result, traceback, input args, etc.). Deleting the JobResult appears to restore normal performance.

**Comment by gsnider2195** [comment]
Did some testing today and determined that these changes would improve the load time on the homepage and are desirable anyway:

```diff
diff --git a/nautobot/extras/homepage.py b/nautobot/extras/homepage.py
index e063930b6..dd4453af5 100644
--- a/nautobot/extras/homepage.py
+++ b/nautobot/extras/homepage.py
@@ -7,14 +7,24 @@ def get_job_results(request):
     """Callback function to collect job history for panel."""
     return (
         JobResult.objects.filter(status__in=JobResultStatusChoices.READY_STATES)
-        .defer("result")
+        .restrict(request.user, "view")
+        .only("id", "name", "status", "date_done", "user")
         .order_by("-date_done")[:10]
     )
 
 
 def get_changelog(request):
     """Callback function to collect changelog for panel."""
-    return ObjectChange.objects.restrict(request.user, "view")[:15]
+    return ObjectChange.objects.restrict(request.user, "view").only(
+        "id",
+        "action",
+        "changed_object",
+        "changed_object_id",
+        "changed_object_type",
+        "object_repr",
+        "user_name",
+        "time",
+    )[:15]
 
 
 layout = (
```

Still need to look into why the entire file is being loaded into the `JobResult` `traceback` field and maybe figure out if we can get the input data to the job without having to use the `task_kwargs`.

**Comment by gsnider2195** [comment]
Possible fix is to add a `__repr__` to the FileVar field used by the job to truncate the file content to a reasonable length
