### ISSUE TITLE
GraphQL queries do not support filtering on M2M relationships

### ISSUE THREAD

**Issue by nkallergis** [nautobot/nautobot#5906]
### Environment
* Nautobot version: v2.2 for the locations/prefixes issue described below, probably all versions for the M2M in general
* Python version: N/A
* Database platform, version: N/A
* Middleware(s): N/A

### Steps to Reproduce
1. Craft a GraphQL query like this where a M2M query is traversed (`location`-`prefixes` in this case). This works as expected.
```
query ($device_id: ID!) {
  device(id: $device_id) {
    name
    location {
      name
    	prefixes {
    	  prefix
        prefix_length
    	}
    }
 }
}
```

2. Add a filter to the nested item (e.g. `prefix_length` for `prefixes`). Any filter will cause the issue to manifest.
```
query ($device_id: ID!) {
  device(id: $device_id) {
    name
    location {
      name
    	prefixes (prefix_length: 16){
    	  prefix
        prefix_length
    	}
    }
 }
}
```

### Expected Behavior
The GraphQL query is executed and the filtered list of prefixes is returned.

### Observed Behavior
An error is returned
`"Unknown argument \"prefix_length\" on field \"prefixes\" of type \"LocationType\".",`

Seems adjacent to [issue #5513](https://github.com/nautobot/nautobot/issues/5513) but not necessarily directly related. Based on the discussion had with @glennmatthews, this is probably due to "a gap in the graphql generation for all M2M fields", also present in the Device/VRF relationship.

**Comment by HanlinMiao** [comment]
Should be pretty similar to what we implmented in #799 for `ManyToOneRel`, see specifically `nautobot/core/graphql/schema.py`

**Comment by lampwins** [comment]
Please target the 7/22 patch release for 2.2
