### ISSUE TITLE
Retest 2.3 against ubuntu 24.04 and update documentation accordingly in `next`

### ISSUE THREAD

**Issue by HanlinMiao** [nautobot/nautobot#5920]
### Proposed Changes
We need to retest Nautobot v2.3 against Ubuntu 24.04 and update the Ubuntu documentation accordingly.

### Justification
In Nautobot v2.3, we added support for Python 3.12 which theoretically would enable us to support Ubuntu 24.04. Currently, the documentation in `develop` is stating that we do not officially support Ubuntu 24.04 in v2.2 so we need to change that. https://github.com/nautobot/nautobot/pull/5875

**Comment by glennmatthews** [comment]
Addressed by #6013 and #6019.
