### ISSUE TITLE
CloudType model needs to permit CloudService content-type

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#5933]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3

Looks like currently we only allow CloudType to select `cloud network` as its content type. `cloud service` should also be a permitted value here.

Additionally, when creating a CloudService or CloudNetwork, if we don't already, we need to only show and permit associated CloudTypes that include this content-type (i.e. if "AWS S3" is a CloudType for CloudServices only, you should not be able to create a CloudNetwork of this type).

**Comment by glennmatthews** [comment]
Additionally:
- Submenu grouping of `Accounts` in the Cloud menu is incorrect - probably should be `Cloud` for now?
- Consider whether `Cloud Type` name is confusing and should be changed in the UI at least to `Cloud Object Type`?

**Comment by gsnider2195** [comment]
> Additionally:
> 
>     * Submenu grouping of `Accounts` in the Cloud menu is incorrect - probably should be `Cloud` for now?
> 
>     * Consider whether `Cloud Type` name is confusing and should be changed in the UI at least to `Cloud Object Type`?

+1 for Cloud Resource Type from me
