### ISSUE TITLE
Device update times increase in proportion to the number of child devices it has

### ISSUE THREAD

**Issue by nrnvgh** [nautobot/nautobot#5935]
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.24,  e48f12217ae9 (v2.3.0a1)
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Create a parent Device with N bays (say 12)
2. Create N child devices
3. Measure the time it takes to save the parent device with zero child devices, 1, 2, ... N

### Expected Behavior
If no changes are made to the parent device, or if updates other than to rack/position are made to the parent device, the update time of the parent device should be O(1) vs the number of associated child devices.

### Observed Behavior
Save time increases linearly in proportion to the number of associated child Devices. This is obviously far more noticeable on an underpowered Nautobot instance (which we have one of, in addition to our more performant production instances).

**Comment by nrnvgh** [comment]
I've mocked up a test case for this patch, but haven't committed it yet because, if it's needed, I could use some guidance:

- Should it be included in nautobot/dcim/tests/test_models.py ?
- If so, I'll need to create some additional items in the database; would you prefer I do that in `DeviceTestCase.setUp()` or in the test case itself?

**Comment by glennmatthews** [comment]
test_models.py sounds like the appropriate place to me, and creating the additional records in DeviceTestCase.setup is probably fine. Thanks!

**Comment by nrnvgh** [comment]
Added PR #5941 with the same update for the `develop` branch.

**Comment by HanlinMiao** [comment]
PRs reviewed and approved thank you!
