### ISSUE TITLE
Implement REST API Versioning

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#594]
### Proposed Changes

I propose that we implement REST API versioning. There is [built-in support in DRF for versioning](https://www.django-rest-framework.org/api-guide/versioning/). There are many options to choose from for which style of versioning to use such as [`Accept` header versioning](https://www.django-rest-framework.org/api-guide/versioning/#acceptheaderversioning), and [query parameter versioning](https://www.django-rest-framework.org/api-guide/versioning/#queryparameterversioning), but my proposal would be to go with `Accept` header versioning because it affords that the URIs do not have to change and greatly simplifies client-side configuration and integration and is widely considered to to be the best practice.

We should consider the current REST API to be v1, and then introduce a v2 API with completely different code paths (serializers/views) where new API features are added for the v2.0.0 release of Nautobot.

Here is an illustrative basic example of adapting `DeviceSerializer` (obviously we'd probably want to come up with [base classes that do this kind of thing with less boiler plate](https://github.com/sentyaev/drf-versioning), but this is just for illustration):

```python
def get_serializer_class(self):
    if self.request.version == 'v1':
        return DeviceSerializerV1
    return DeviceSerializerV2
```

In this paradigm, once a new API version is introduced, new features would only be added to that API, and the previous version would be frozen. If users want to take advantage of the new features in the v2 API, similarly to how they must upgrade Nautobot, they must also upgrade their client code to migrate to the v2 API.

We would need to also consider what our versioning deprecation policy would be. I would suggest that w/ each new version of Nautobot a new REST API version is introduced, and the version from two releases back is removed. 

Illustrated:

Nautobot version | API version | Deprecated API version | Removed API version 
------------------|------------|------------------------|-----------------------
1.x | v1 | n/a | n/a
2.x | v2 | v1 | n/a
3.x | v3 | v2 | v1

### Justification

The biggest and most obvious justification is asserting predictability in upgrading Nautobot to new versions. Consider the example of upgrading to Nautobot 2.0 without API versioning. If we want to make changes to the API, we either have to consider backwards compatibility of the API, or we just have to steamroll forward and deliberately document every single change for users to be able to modify their client code to migrate interactions with the API on the newer version. This is not fun for anyone.

As maintainers, it's incredibly costly to continue to have to think about every change we make to the public API, and how it might impact previous versions. How far back to we go? Do we maintain regression tests for every single new feature we add to the API to assert that earlier versions of Nautobot still behave correctly? Are we having fun yet?

For users of Nautobot, at best it comes at a time and complexity cost. At worst, it could result in service outages or data integrity issues as users try to use the un-versioned Nautobot 2.0 API and run into quirks, or think they've updated everything but missed one critical field value where the intent may have changed between major versions of the platform.

With API versioning, users can safely upgrade to Nautobot 2.0 knowing that the v1 API will still work exactly as it did in Nautobot 1.x. Users can then deliberately prepare their client code to integrate with the v2 API when they are good and ready in order to take advantage of the new API features.

References
- https://gearheart.io/articles/api-versioning-with-django-rest-framework/
- https://resources.rescale.com/api-versioning-with-the-django-rest-framework/
- https://steveklabnik.com/writing/nobody-understands-rest-or-http#i_want_my_api_to_be_versioned

**Comment by jedelman8** [comment]
As we build plans for Nautobot 2.0, this is definitely a big top of consideration.

**Comment by glennmatthews** [comment]
See #1465 for further discussion and design, and #1521 for the implementation in version 1.3.
