### ISSUE TITLE
ValueError Raised when navigating to a VLAN's location list

### ISSUE THREAD

**Issue by housepbass** [nautobot/nautobot#5947]
### Environment
* 2.2.7:
* Python version: 3.11.9
* Database platform, version: demo nautobot environment
* Middleware(s): demo nautobot environment

### Steps to Reproduce
1. Navigate to [VLANs list view](https://demo.nautobot.com/ipam/vlans/)
2. Configure the `Location` column to be visible in table
3. Select the value in the `Location` column

### Expected Behavior
The link takes me to a list of `Locations` containing the relevant `VLAN`

### Observed Behavior
`ValueError` is raised with message:
`Field 'vid' expected a number but got '01acc3fb-d449-4f36-9789-df5503206528'.`

**Comment by glennmatthews** [comment]
Thanks! The fix will be in 2.3 - see #5737.

**Comment by lampwins** [comment]
Closing this as the beta for 2.3 is now out, with the final release soon to follow.
