### ISSUE TITLE
Improve help text for cloud-model `provider` form fields

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#5977]
### As ...

Ozzie - Operator

### I want ...

To easily understand the information needed to correctly populate the new Cloud models

### So that ...

I can enter my Cloud data into Nautobot with a minimum of false starts and confusion

### I know this is done when...

- The existing form-field help-text for the `provider` field is changed from `"Manufacturers are the recommended model to represent cloud providers."`, which is misleading because this isn't a *recommendation* but a *requirement*, to something along the lines of "Cloud providers are represented by the Manufacturer model".
- Appropriate help text is present for the `provider` field on both `CloudAccount` and `CloudResourceType`.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Apps (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

No, help-text/UI changes only

**Comment by lampwins** [comment]
We will also change the field name to `Cloud provider`

As for the help text, I am thinking `The Manufacturer instance which represents the Cloud Provider`
