### ISSUE TITLE
IPv6 Localhost Fails to Load Swagger Docs

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#598]
### Environment
* Python version: 3.7.7
* Nautobot version: 1.0.2

### Steps to Reproduce

Tested with both `DEBUG=True` and `DEBUG=False`

1. Start a container environment with Nautobot
2. Navigate to `http://[::]:8080/api/docs/
3. Receive error message on the CLI and API definition load error on screen

![Screen Shot 2021-06-21 at 12 38 27](https://user-images.githubusercontent.com/22228848/122804591-b55e2600-d28d-11eb-8a7a-500a0cf5b5f1.png)

### Expected Behavior

API docs to load

### Observed Behavior

```
drf_yasg.errors.SwaggerValidationError: spec validation failed: {'ssv': '(\'\\\'[::]:8080\\\' does not match \\\'^[^{}/ :\\\\\\\\\\\\\\\\]+(?::\\\\\\\\d+)?$\\\'\\n\\nFailed validating \\\'pattern\\\' in schema[\\\'properties\\\'][\\\'host\\\']:\\n    {\\\'description\\\': \\\'The host (name or ip) of the API. Example: \\\'\\n                    "\\\'swagger.io\\\'",\\n     \\\'pattern\\\': \\\'^[^{}/ :\\\\\\\\\\\\\\\\]+(?::\\\\\\\\d+)?$\\\',\\n     \\\'type\\\': \\\'string\\\'}\\n\\nOn instance[\\\'host\\\']:\\n    \\\'[::]:8080\\\'\', <ValidationError: "\'[::]:8080\' does not match \'^[^{}/ :\\\\\\\\\\\\\\\\]+(?::\\\\\\\\d+)?$\'">)'}
```

**Comment by jathanism** [comment]
Well isn't that lovely.

As annoying as this is, this looks like an issue with the JSON schema for the spec. I tracked it down to this: 

https://github.com/Yelp/swagger_spec_validator/blob/master/swagger_spec_validator/schemas/v2.0/schema.json#L1538-L1542

```json
        "host": {
            "description": "The host (name or ip) of the API. Example: 'swagger.io'",
            "pattern": "^[^{}/ :\\\\]+(?::\\d+)?$",
            "type": "string"
        },
```

Perhaps there is a way to override the schema easily, but for now I confirmed that if you're running using v6 on localhost, you can just use `localhost` to avoid this.
