### ISSUE TITLE
Big GraphQL performance regression in v2.2.8

### ISSUE THREAD

**Issue by gioccher** [nautobot/nautobot#5980]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.8
* Python version: 3.9
* Database platform, version: MySQL 8
* Middleware(s): 

### Steps to Reproduce
1. Run GraphQL query (doesn't matter where: as part of Golden Config intended config generation, from /extras/graphql-queries/, from /graphql/) 

### Expected Behavior
Query completes as fast as it did in v2.2.7

### Observed Behavior
Query takes 13 times longer to execute.

I have [a query](https://github.com/user-attachments/files/16352541/ssot-query.txt) that returns a lot of data that I use to generate the intended config from the golden config app. I can't slim the query down any further, I need all the data it returns. After upgrading to 2.2.8, it takes anywhere from 20 seconds to 38 to complete for each device. It used to take between 1.5 to 3 seconds with 2.2.7

**Comment by glennmatthews** [comment]
Thanks for the report. Most likely this is a side effect of #5931.

It would be useful to run some cprofile or similar to see where the added time is being spent.

**Comment by gioccher** [comment]
here are the profiler results [nb2.2.7&2.2.8-graphql.zip](https://github.com/user-attachments/files/16354151/nb2.2.7.2.2.8-graphql.zip)

I've run the same query 8 times on each NB version: 3 times without profiling to warm up the cache followed by 5 times with profiling. What you see in the archive is the median trace by amount of elapsed time.

Biggest change seems to be the number of queries: from 590 to 2000
<img width="1151" alt="SCR-20240723-mfjv" src="https://github.com/user-attachments/assets/1f291199-27f3-43b7-9a02-d46a8555035b">

**Comment by glennmatthews** [comment]
Thank you! That's super helpful. Looking into the data now.
