### ISSUE TITLE
Support for custom fields on JobResult

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#599]
### User Story

As Austin the Network Automation Engineer,

I want to be able to store additional data in my JobResult records,

So that other Jobs can build atop this data to provide features like reporting/summarizing previous Jobs, rolling back changes implemented by a previous Job, etc.

I will know this is done when I can define custom fields for the JobResult model and populate these fields from within a running Job.

 
### Database Changes (Optional)

Yes - addition of custom field data field to JobResult.

### External Dependencies (Optional)

None.

**Comment by carbonarok** [comment]
@glennmatthews do the custom fields need to be displayed on the job page?

**Comment by glennmatthews** [comment]
Not on the Job pages (since these would be on individual JobResults, not the Jobs) but absolutely on the JobResult detail view (i.e. `/extras/job-results/<uuid>/`) just as with any other detail view of any other model supporting CustomFields.

**Comment by glennmatthews** [comment]
Resolved by #636
