### ISSUE TITLE
Cache is invalid when doing a database flush

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#5992]
I've encountered this issue when running `nautobot-server generate_test_data --flush` where the cached ContentTypes in `nautobot.extras.utils.change_logged_models_queryset` don't get cleared out and the factories that use this fail. We probably just need to clear the cache in that specific management command.

**Comment by glennmatthews** [comment]
I think we should also ensure that `post_upgrade` or its `refresh_content_type_cache` subcommand also delete this cache key in particular.

**Comment by glennmatthews** [comment]
Maybe actually register a signal handler to the `post_migrate` signal specifically to clear this cache key?
