### ISSUE TITLE
Review the new model check list for cloud models to check for any gaps and anything that we might have missed

### ISSUE THREAD

**Issue by HanlinMiao** [nautobot/nautobot#6001]
### Proposed Changes
Review the new model check list to check for any gaps and anything that we might have missed

**Comment by smk4664** [comment]
Here is what I have found after reviewing the HLD and the model checklist.

Cloud Network:
- [ ] Unless there is a strong reason not to, all models should have a ForeignKey to tenancy.Tenant named tenant
- [ ] locations: Models that support a foreign key to Location, used for limiting the choices for the LocationType.content_types field (HLD has examples of tying to locations, but not in the diagram.)
- [ ] statuses: Models that support a foreign key to Status, used for limiting the choices for the Status.content_types field (This might be a good candidate for Statuses)
- [ ] NautobotUIViewSet: Use appropriate select_related/prefetch_related for performance

Cloud Account:
- [ ] Use appropriate @extras_features decorator values (has unnecessary "dynamic_groups"
- [ ] Unless there is a strong reason not to, all models should have a ForeignKey to tenancy.Tenant named tenant
- [ ] NautobotUIViewSet: Use appropriate select_related/prefetch_related for performance

Cloud Service:
- [ ] Unless there is a strong reason not to, all models should have a ForeignKey to tenancy.Tenant named tenant
- [ ] locations: Models that support a foreign key to Location, used for limiting the choices for the LocationType.content_types field (HLD has examples of tying to locations, but not in the diagram.)
- [ ] statuses: Models that support a foreign key to Status, used for limiting the choices for the Status.content_types field (This might be a good candidate for Statuses)
- [ ] NautobotUIViewSet: Use appropriate select_related/prefetch_related for performance
- [ ] Implement <Model>TestCase class in nautobot.<app>.tests.test_models module
    - [ ] Use appropriate ModelTestCases base class and mixin(s)

Cloud Resource Type:
- [ ] Unless there is a strong reason not to, all models should have a ForeignKey to tenancy.Tenant named tenant
- [ ] NautobotUIViewSet: Use appropriate select_related/prefetch_related for performance
