### ISSUE TITLE
Cloud accounts is shown in multiple places on the manufacturer detail view

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#6002]
![image](https://github.com/user-attachments/assets/bc6767fa-402d-4721-a5f9-665ca0d284bf)

**Comment by glennmatthews** [comment]
I’m not sure I agree with changing/removing this. The embedded tables for Devices and CloudAccounts related to the Manufacturer are useful, but so is the link above, as 1) it gives the count of related objects, which is not obvious from the table alone, especially if paginated, and 2) it provides a convenient link to the full filtered object-list view of the related objects. I’m inclined to leave it as-is personally.

**Comment by lampwins** [comment]
Because the current implementation is consistent with other areas (e..g Manufacturer detail view), we will not do this.
