### ISSUE TITLE
tagged vlans on module interfaces (tagged port)

### ISSUE THREAD

**Issue by digital-fortress** [nautobot/nautobot#6114]
nvironment
Nautobot version: 2.3.0
Python version: 3.11.9
Database platform, version: [ PostgreSQL 14]

Steps to Reproduce
Add a Cisco module to a Cisco device in Nautobot.
Edit the module interface and set it to "tagged port."
Attempt to add a tagged VLAN from the VLAN list.
Save the changes.
Expected Behavior
The VLAN should be successfully added to the module interface without any errors.

Observed Behavior
An error occurs upon saving: <class 'AttributeError'> 'NoneType' object has no attribute 'location'.

This issue does not occur if the module interface type is set to "access" or "tagged all." The error only appears when adding a VLAN to a "tagged port" interface.

This behavior can be reproduced on a demo instance by importing a Cisco module type, attaching it to a Cisco device, and following the steps above.

**Comment by aanghel123** [comment]
experienced the same issue.

**Comment by digital-fortress** [comment]
> experienced the same issue.

Actually this was fixed in the very next version.
