### ISSUE TITLE
Status field for VRFs in the IPAM module

### ISSUE THREAD

**Issue by jnmms** [nautobot/nautobot#6120]
### As ...

Ozzie - Operator

### I want ...

A status field for VRF objects in the IPAM module

![image](https://github.com/user-attachments/assets/9cc52c83-5d25-498a-a788-16ef1cc2dc05)

### So that ...

So that it can reflect reality, where it in the config of for example Nexus 7700 series equipment is possible to issue a shutdown command for the vrf.

### I know this is done when...

You can see, add and edit status on a VRF and also bulk edit/change status for VRF objects

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [X] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Apps (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

VRF model needs to be changed to include a relation to the StatusField datamodel

**Comment by glennmatthews** [comment]
Thanks for the feature request! As described, this might be better implemented as an attribute of the `VRFDeviceAssignment` model rather than the `VRF` model itself, perhaps?

**Comment by jnmms** [comment]
Yea it might be, I’m not so fluent inside the code and design, but I will try and take a look, and will se if I can come up with a PR myself – but not sure if I’m the right one to do this 😉

I will definitely take this a a pointer on where to look..


Venlig hilsen / Best regards

Martin Schyth
Netværks specialist
Network Engineering & Automation

Direct +4563639550
Mobile +4521685952
***@***.******@***.***>

***@***.***
JN Data A/S

|

Havsteensvej 4

|

4000 Roskilde

+4563636363

|

www.jndata.dk<https://www.jndata.dk>

|

***@***.***<https://www.linkedin.com/company/jn-data/>

***@***.***
