### ISSUE TITLE
Cable Status Colors do not show in tables when using Dark Theme

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot#6123]
### Environment
* Nautobot version (Docker tag too if applicable): 2.1.0+
* Python version: Python 3.11
* Database platform, version: Postgres (invoke environment)
* Middleware(s):

### Steps to Reproduce
1. Create a Device with a cable attached (Interface, Console Port, Console Server, Power Port, etc...)
2. Switch to Dark Theme

### Expected Behavior

The row is highlighted with the color matching the status (Green for "Connected", Blue for "Planned" and Red for "Decommissioning". 

### Observed Behavior

The row is the same color as other rows in the Interface table.

**Comment by smk4664** [comment]
This worked in 2.0.0, but not in 2.1.0+

**Comment by HanlinMiao** [comment]
So `[cable_status_color_css](https://github.com/nautobot/nautobot/blob/develop/nautobot/dcim/utils.py#L52)` function is explicitly setting the `background-color` attribute of the `tr` element to be a specific color. However, in our [dark.css](https://github.com/nautobot/nautobot/blob/develop/nautobot/project-static/css/dark.css#L62) file, we are using the `!important` to override that `backgroud-color` attribute. We need to look into using https://getbootstrap.com/docs/3.4/css/#tables-contextual-classes for the table row coloring as well
