### ISSUE TITLE
Any suggestions for entering Cloud Resource Types?

### ISSUE THREAD

**Issue by RenJiangZhou2163** [nautobot/nautobot#6127]
### Environment
* Nautobot version (Docker tag too if applicable):  2.3.1
* Python version: py3.11
* Database platform, version: postgresql14

### Steps to Reproduce
1.It is not possible to enter multiple cloud resource types with the same name.

### Expected Behavior
1.**Cloud Resource Types:** Multiple providers may offer the same services, such as VPC and IPSec VPN. Do you have any suggestions for entering Cloud Resource Types?

**Comment by glennmatthews** [comment]
In that scenario I'd just suggest including the provider name or alias as a part of the resource type name, e.g. `"AWS VPC"`.
