### ISSUE TITLE
Custom_fields ignored with available-prefixes API in later versions of Nautotbot

### ISSUE THREAD

**Issue by kristofferDuctus** [nautobot/nautobot#6131]
### Environment
* Nautobot version (Docker tag too if applicable): Present in docker images 2.2.7-py3.11 up to nautobot:2.3.1-py3.12
* Python version: Tested both 3.11 and 3.12 in different docker images
* Database platform, version: Postgres 14
* Middleware(s):

### Steps to Reproduce
1. Create a custom field that is possible to use under the prefixes
2. Allocate a new prefix with the custom field parameter (example curl below):

curl --location 'http://localhost:8080/api/ipam/prefixes/ccb2034f-75fe-433f-8c42-a6a1f90f849a/available-prefixes/' \
--header 'accept: application/json' \
--header 'Authorization: Token 0123456789abcdef0123456789abcdef01234567' \
--header 'Content-Type: application/json' \
--data '{
        "prefix_length": 24,
        "status": "Active",
        "custom_fields": {"service_id": "svc123213"}
}'

3. The response nor the prefix contains the custom field parameters.

### Expected Behavior
The same curl command is working fine in docker container 2.2.6-py3.11 and the custom_fields set through the curl command is stored on the actual object.

### Observed Behavior
All custom parameters are empty and not set through the API.

**Comment by glennmatthews** [comment]
Thanks for the report. Probably a regression due to #5856.
