### ISSUE TITLE
Spike: Event system design

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#6143]
Scope requirements and design for the event based system to include coverage for:
- standard model CRUD, Job execution, and user login/logout events
- App defined custom event type
- ~Filtering of events and routing config~
- Redis and Kafka initial support
- Focus on publishing of events, ~subscription is a maybe at this point~

Event types should follow a nested namespace pattern, to aid with wildcards: `create.dcim.device` or `jobs.execution.started`

Single app API for publishing events. See for inspiration: https://github.com/nautobot/nautobot-plugin-event-bus/blob/develop/nautobot_event_bus/jobs.py#L53

Brokers should implement a light Nautobot abstraction layer to standardize connection, topic terminology, and the event publish method. Using this, someone should be able to implement a "Syslog broker" as an example.

**Comment by HanlinMiao** [comment]
Goal here is to design the system such that we can eventually migrate `JobHooks`, `WebHooks` and `Changelogging` to be clients of the system.
