### ISSUE TITLE
Edit and Delete Button move to middle of each row after adding Custom Field

### ISSUE THREAD

**Issue by MeganerdDev** [nautobot/nautobot#6152]
### Environment
* Nautobot version (Docker tag too if applicable): v1.6.26
* Python version: 3.11
* Database platform, version: PG13
* Middleware(s): N/A

### Notes
Doesn't seem to be an issue in `ltm-1.6` but actually an issue up to `v2.2.8` and first resolved it [v2.3.0-beta.1](https://github.com/nautobot/nautobot/releases/tag/v2.3.0-beta.1). [#5657](https://github.com/nautobot/nautobot/pull/5657) seems to be the related change. The change seems to be a larger refactor and I'm not sure this bug was directly reported or identified at the time, but it does seem to be resolved by it.

### Steps to Reproduce
1. Create a test `Manufacturer` object
2. Create a test `Device Type` object
3. Create a Custom Field object with Content Type of `Interface Template`
4. Go to the Device Type object, the Edit and Delete buttons will rendered before the Custom Field(s)
![image](https://github.com/user-attachments/assets/88f06ede-8afa-4796-ad9d-9adeb5445240)

### Expected Behavior
Edit and Delete Buttons to be displayed at the right of custom field(s)

### Observed Behavior
Edit and Delete Buttons displayed to the left of any custom field(s). (see step-4 screenshot)

**Comment by MeganerdDev** [comment]
To help with this report I included the HTML difference between the view on `v2.3.0-beta.1` vs `v2.2.6`

![image](https://github.com/user-attachments/assets/01fa0113-c691-46e4-9084-89c171f5b59a)

**Comment by lampwins** [comment]
This is a backport to 1.6
