### ISSUE TITLE
Custom Fields can only be strings in the UI, but all JSON types are allowed with ORM/API

### ISSUE THREAD

**Issue by jmcgill298** [nautobot/nautobot#616]
### Environment
* Python version: 3.8
* Nautobot version: 1.0.2

### Steps to Reproduce
1. Create a Custom Field of type `Text` (example will assume it has been assigned to `dcim > device` and has a name of `my_custom_field`)
2. In UI route to Devices > Devices > Add Device
3. In `my_custom_field` that was created in step 1, provide a list value `["1.1.1.1"]` (we will name this device `my_device`)
4. Save the new Device
5. Launch nbshell
6. Get Device object that was just created (`device = Device.objects.get(name="my_device")`)
7. Inspect the `my_custom_field` value `device.cf["my_custom_field"]` and observe that is a string `"['1.1.1.1']"` or `isinstance(device.cf["my_custom_field"], str)`
9. Update the `my_custom_field` to be a list with the ORM (`device.cf["my_custom_field"] = ["1.1.1.1"]`)
10. Call validated save to update the changes in the database (`device.validated_save()`)
11. Refetch the device (`device = Device.objects.get(name="my_device")`)
12. Inspect the `my_custom_field` value `device.cf["my_custom_field"]` and observe that is is a list `['1.1.1.1']` or `isinstance(device.cf["my_custom_field"], list)`

### Expected Behavior
Based on the Custom Field Type being named `Text`, I would expect only string data to be stored in the custom field's value. So for this example, I would either expect `validated_save()` to fail validation, or type conversion to a string before storing it in the database.

Having said that, I would prefer the Type to be `JSON` and input from UI to be stored as "json"

### Observed Behavior
The UI and the ORM have different constraints on what type of data can be stored in the custom field

**Comment by jathanism** [comment]
Long story short this inconsistency is because the UI validation is being done in the forms where as API/ORM are falling back to "default" model field validation, therefore only type-checking valid JSON or not.

We'll need to move the strict validation out of the UI forms and closer to the model.

**Comment by glennmatthews** [comment]
#897 covers adding a separate "JSON" type for custom fields. For "Text" fields assigning a non-string value should be an error.

**Comment by glennmatthews** [comment]
Should be a simple matter of adding appropriate logic to `CustomField.validate()`.
