### ISSUE TITLE
support idempotent / upsert objects via the API

### ISSUE THREAD

**Issue by cardoe** [nautobot/nautobot#6166]
### As ...

Tammy - Tools Integrator

### I want ...

To develop integrations with Nautobot which need to create objects (like devices, prefixes, etc) in an idempotent way

### So that ...

So that I know the object I am creating beforehand

### I know this is done when...

I can create objects idempotently or via an upsert (update or insert).

So via REST it is common to have `POST /myobject/` create a new record and return a reference to that record via a 201 CREATED and Nautobot does this today. It's also common to support `PATCH /myobject/$REF` and include a subset or even all the fields to update. Which again is something that Nautobot supports. The last pattern is the idempotent create or upsert which is commonly `PUT /myobject/$REF` which requires the entire object and will either create it or update it. Nautobot returns a 404 if it doesn't exist and updates it if it does. This is something the Django REST framework is doing. Searching shows its a common-ish compliant and worked around via the serializer.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Apps (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [X] Other (not directly a platform feature)

### Database Changes

No

### External Dependencies

None.

**Comment by itdependsnetworks** [comment]
> This is something the Django REST framework is doing. Searching shows its a common-ish compliant and worked around via the serializer.

Could you link some of the relevant issues?

**Comment by cardoe** [comment]
So every example I've found is old and the API has changed. Or because of the way the custom classes are done in Nautobot it won't work. Mostly having to figure out how to workaround `editable=False` on the `id` field. Which causes DRF to set it to read-only. I've been trying to come up with the smallest possible change. Maybe https://github.com/nautobot/nautobot/blob/3d29e5d3ea635d0931804e3b03ac9c08f7835e5d/nautobot/core/api/serializers.py#L136 add `id` and use https://www.django-rest-framework.org/api-guide/validators/#createonlydefault while removing `id` from `read_only_fields`?

**Comment by cardoe** [comment]
So specifically adding
```
id = serializers.UUIDField(read_only=False, default=serializers.CreateOnlyDefault(uuid.uuid4))
```

I'm honestly not sure how `BaseModelSerializer` is adding in `id`. It says it does in the comment but I don't see it.

**Comment by glennmatthews** [comment]
It adds `id` here: https://github.com/nautobot/nautobot/blob/3d29e5d3ea635d0931804e3b03ac9c08f7835e5d/nautobot/core/api/serializers.py#L378-L379
