### ISSUE TITLE
Revise install documentation around new install and deployment pattern

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#62]
### Change Type
[x] Addition
[x] Correction
[x] Deprecation
[x] Cleanup (formatting, typos, etc.)

### Area
[x] Installation instructions
[x] Configuration parameters
[x] Administration/development

### Proposed Changes

The key changes that we made in Nautobot for how it can be installed, configured, developed, administered, and deployed need to be revised. The initial fork and release only did the minimum required to make sure Nautobot could be installed. As indicated above, the following key documentation areas need to be revised:

- Installation guide - spit into per-platform instructions, with a quick start guide for the common case)
- Configuration guide - centralize all optional settings including permissions and authentication, into a single configuration section
- Deployment guide - break install and production deployment into distinct sections. Getting Nautobot running is very different than running it in an enterprise-grade production environments
- Development guide - How to use "invoke", the basics of the Docker container that comes w/ Nautobot and how to use that

**Comment by glennmatthews** [comment]
Also need a generalized plugin installation and enablement guide, since it appears people are encountering issues in this area.

**Comment by jathanism** [comment]
From [ndom91 on Slack](https://networktocode.slack.com/archives/C01NWPK6WHL/p1614543515258200):

> So there seems to be some kinda minor, kinda major issues i've come across / had others mention to me in using nautobot today.
> 1. There seems to be some indecision amongst the team whether to use /opt/nautobot/ as the primary config dir or ~/.nautobot and this shows itself at multiple stages while trying to install (i.e. copying static files to wrong dir, looking for config in wrong place, etc.)
> 2. Also all? plugins (can only confirm with chat-ops and nautobot-netbox-importer ) don't seem to allow nautobot to run while enabled. Screenshot to follow
> 3. nautobot-netbox-importer seems to ahve problems with IPAM prefixes and throws warnings about 'apparent duplicates', but during the later reconciliation stage (i.e. after "Data loading from Nautobot complete") it errors out because of these
```
diffsync.exceptions.ObjectAlreadyExists: Object 62.67.123.123/31__None__{'name': 'abc'}__{'name': 'cba'} already present

```

**Comment by glennmatthews** [comment]
See #74.

**Comment by jifox** [comment]
I noticed that in current documentaion there is no reference to  `local_requirements.txt`` 

see Installation section: [ntc-nautobot-plugin-nornir](https://pypi.org/project/nautobot-plugin-nornir/)

> [...]
   To ensure Nautobot Nornir Plugin is automatically re-installed during future upgrades, create a file named
   local_requirements.txt (if not already existing) in the Nautobot root directory (alongside requirements.txt) and 
   list the nautobot_nornir package:
>   
>   `# echo nautobot-plugin-nornir>> local_requirements.txt`
>   
>   Once installed, the plugin needs to be enabled in your configuration.py
>   [...]

**Comment by jathanism** [comment]
> I noticed that in current documentaion there is no reference to `local_requirements.txt``

It does now. Thanks! :)

**Comment by glennmatthews** [comment]
Also need to consider #82 and how it might feed into the install/upgrade workflow.
