### ISSUE TITLE
Logs Cleanup job uses vast amounts of memory causing out of memory issues

### ISSUE THREAD

**Issue by gneville-ot** [nautobot/nautobot#6204]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3.2
* Python version: 3.11
* Database platform, version: PG15
* Middleware(s): N/A

### Steps to Reproduce
1. Have a nautobot instance with a large amount of job results and change logs
2. Run the "Logs Cleanup" job

### Expected Behavior

Logs over "Max Age" are deleted without issues 

### Observed Behavior

The job fails with logs on celery-worker showing:

```
[2024-09-09 15:50:04,540: ERROR/MainProcess] Process 'ForkPoolWorker-15' pid:193 exited with 'signal 9 (SIGKILL)'
[2024-09-09 15:50:04,560: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL) Job: 3.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.einfo.ExceptionWithTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 3.
```

Monitoring the container shows that it is using vasts amount of memory which is more than the memory allocated for docker to use.

![image](https://github.com/user-attachments/assets/b5524f92-b5bd-4b6a-9c65-dd4554c8388d)

The first spike is when trying to set max_age to 7, the second spike is going to 150 days. The oldest job result I have in the system is 158 days. 

Although this is a local development environment, our production instance will likely see the same issue if this job requires lots of memory to run.

**Comment by glennmatthews** [comment]
Thanks for the report. Do you have any apps installed with a FK to JobResult or ObjectChange models, or with signals related to either model, by chance?

**Comment by gneville-ot** [comment]
I'm only using NTC developed apps. The most used would be the SSoT App, which has an FK to JobResult (https://github.com/nautobot/nautobot-app-ssot/blob/ba8bc4b9cb4d5d0640283954f0d02d8c64fe3aeb/nautobot_ssot/models.py#L85)

**Comment by lampwins** [comment]
Any sense of an average number of `JobLogEntry` records for each `JobResult`? Just wondering what order of magnitude compared to `JobResults` they are. What ballpark percentage of `JobResults` are your SSoT runs?

**Comment by gneville-ot** [comment]
I'm not sure how to really check that, but if I just look at the "Logs" inside the Job Results (e.g. messages) there's probably an average of 100 lines for the most run SSoT job.

In terms of JobResults I have 9017 total, 2304 are SSoT related (25%), 6322 Git Sync (70%).

**Comment by lampwins** [comment]
Let's try to delete things in the right order, so that all leaf nodes are deleted first, to avoid Django's cascade lookup queries.
