### ISSUE TITLE
Cluster table link for Device count link uses renamed filter

### ISSUE THREAD

**Issue by MeganerdDev** [nautobot/nautobot#6207]
### Environment
* Nautobot version (Docker tag too if applicable): v2.3.2
* Python version: 3.11
* Database platform, version: PG13
* Middleware(s): N/A

The virtualization/clusters table view from the UI has a clickable link for the Devices column (which displays the count). The endpoint in the link is using and old filter pattern for dcim/devices. When you follow the hyperlink you will get a filter applied in the URL with an error displayed for `Unknown filter field`.

### Steps to Reproduce
1. Requires a Cluster object with 1 or more Devices (for hyperlink to be clickable) from [virtualization/clusters](https://demo.nautobot.com/virtualization/clusters/)
![image](https://github.com/user-attachments/assets/c9993e8f-95d8-4867-a8f7-92979d39f35c)
2. Press the hyperlink for the displayed count
3. Redirect is an invalid filter
![image](https://github.com/user-attachments/assets/f5156949-0359-4300-931d-390876a8d056)

### Expected Behavior
Redirect to dcim/devices with renamed filter

### Observed Behavior
Redirect uses old filter style of `_id`
eg: https://demo.nautobot.com/dcim/devices/?cluster_id=eb5a9d88-e5bb-4090-81d4-a6d2a2df5653

```
Invalid filters were specified:
cluster_id
Unknown filter field
```

### Supporting links and notes
Looks like #2804 was the related change

> Most <related>_id filters have been merged into the corresponding <related> filter (see ["Enhanced Filter Fields"]

(https://docs.nautobot.com/projects/core/en/stable/user-guide/administration/upgrading/from-v1/upgrading-from-nautobot-v1/#enhanced-filter-fields) below).
https://docs.nautobot.com/projects/core/en/stable/release-notes/version-2.0/#enhanced-filter-fields-2804

https://github.com/nautobot/nautobot/blob/20695bcca5e01f34dfbe6526112de6f1e2186c1a/nautobot/virtualization/tables.py#L86

**Comment by MeganerdDev** [comment]
https://github.com/nautobot/nautobot/blob/20695bcca5e01f34dfbe6526112de6f1e2186c1a/nautobot/docs/user-guide/administration/upgrading/from-v1/tables/v2-filters-renamed-fields.yaml#L27-L28

**Comment by HanlinMiao** [comment]
Thank you for the submission and will have a PR fix out soon
