### ISSUE TITLE
Build event publish API abstraction for internal CRUD events

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#6208]
Build the framework for publishing CRUD events. In order to do this, the skeleton of the broker API should just noop event payloads.

The design intention is to rely on the existing ChangeContext infrastructure but we need to consider the cost of `change.get_snapshots()` for this, as we want to avoid unnecessary serialization or DB calls, within the web request context.

**Comment by glennmatthews** [comment]
A potentially interesting avenue for investigation: [caching the initial values when loading a record from the database](https://docs.djangoproject.com/en/4.2/ref/models/instances/#customizing-model-loading).
