### ISSUE TITLE
Hadolint fails on `development` branch

### ISSUE THREAD

**Issue by ggidofalvy-tc** [nautobot/nautobot#621]
### Environment
* Python version: n/a
* Nautobot version: `development` / https://github.com/nautobot/nautobot/commit/92ac42c75dc6e67b31f7097fe438fbdd45470622
* Hadolint: 1.18.2-no-git

### Steps to Reproduce
1. Setup the pre-commit hooks and try to commit

### Expected Behavior
Hadolint should not find any issues with the Dockerfile that hasn't been modified

### Observed Behavior
```
...
Checking Dockerfile...
docker/Dockerfile:106 DL3013 Pin versions in pip. Instead of `pip install <package>` use `pip install <package>==<version>`
docker/Dockerfile:152 DL3013 Pin versions in pip. Instead of `pip install <package>` use `pip install <package>==<version>`
COMMIT FAILED
```

**Comment by glennmatthews** [comment]
Thanks for the report! In our linting and CI we are currently using hadolint 2.0.0 - can you update your hadolint to this version and confirm whether the issue persists?

**Comment by ggidofalvy-tc** [comment]
Hmmm, seems like for version 2.0.0, it no longer triggers for these two lines. I just assumed I'd have a pretty "fresh" version of this tool, considering I installed it straight from Fedora's RPM repos. Guess I can just close this issue now.
