### ISSUE TITLE
Git Sync - Include Commit Hash on Sync Page

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#623]
### Environment
* Python version: 3.6
* Nautobot version: 1.0.3

### Proposed Functionality

Add the Git hash to the git sync output display

### Use Case

To be able to verify the commit hash matches the version that is expected for troubleshooting.

### Database Changes

None

### External Dependencies

None

**Comment by glennmatthews** [comment]
Thank you for the request! I agree this would be useful information to include in the JobResult logging, and should be relatively simple to add.

**Comment by jeffkala** [comment]
@glennmatthews @jvanderaa I'd like to give this one a shot.

**Comment by glennmatthews** [comment]
Terrific! By all means go for it.

**Comment by jedelman8** [comment]
@jeffkala what's your timing on this?  If it is in the next 2-3 weeks, it'll make 1.2, otherwise, 1.3.  Can you let us know? :)

**Comment by jeffkala** [comment]
@jedelman8 , pretty sure I can get this in the next 2-3 weeks.

**Comment by jeffkala** [comment]
@jedelman8 PR is in, was actually much simpler than I thought to implement it.
