### ISSUE TITLE
k8s/kubectl connectivity/auth

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#6255]
For the k8s native jobs integration, we need to support specifying all the connectivity and auth parameters for talking the k8s API (kubectl equivalent commands) to enqueue jobs and check state.

It likely make sense to track this via ExternalIntration instances linked to JobQueue instances with appropriate secrets support.

The idea for now is to have a k8s scoped service account token that is pre-provisioned in the pod spec. We will need to build a built-in secrets provider that can read the token.

**Comment by glennmatthews** [comment]
Not necessarily getting the job fully running and working, but need to connect a k8s JobQueue to an ExternalIntegration and be able to begin loading information from that ExternalIntegration to make successful k8s API calls
