### ISSUE TITLE
Resources that are "too large" cause the nautobot process to crash

### ISSUE THREAD

**Issue by Mesona** [nautobot/nautobot#6297]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3.4 (Docker tag 'latest')
* Python version: 3.10.15
* Database platform, version: PostgreSQL 15.1
* Middleware(s): None

### Steps to Reproduce
1. Create 200k devices
2. Create a location
3. Create a new Dynamic Group -> dcim | device -> filter-defined
4. Edit the new Dynamic Group -> Add Location -> Save
5. Watch nautobot spin for 10 minutes before returning 502.

### Expected Behavior
Dynamic group gets updated to have the new location, and it takes far less than 10 minutes.

### Observed Behavior
Nautobot crashes. This is from the nautobot-server logs:

```
Mon Sep 30 19:39:09 2024 - *** HARAKIRI ON WORKER 14 (pid: 101, try: 1, graceful: yes) ***
Mon Sep 30 19:39:09 2024 - HARAKIRI !!! worker 14 status !!!
Mon Sep 30 19:39:09 2024 - HARAKIRI [core 0] 172.19.0.1 - POST /extras/dynamic-groups/61ba43ba-2eb7-4689-aeba-c37b978d2630/edit/ since 1727724549
Mon Sep 30 19:39:09 2024 - HARAKIRI !!! end of worker 14 status !!!
Mon Sep 30 19:39:09 2024 - HARAKIRI triggered by worker 14 core 0 !!!
2024/09/30 19:39:09 [error] 83#83: *1 upstream prematurely closed connection while reading response header from upstream, client: 172.19.0.1, server: , request: "POST /extras/dynamic-groups/61ba43ba-2eb7-4689-aeba-c37b978d2630/edit/ HTTP/1.1", upstream: "uwsgi://unix:/var/run/app.uwsgi:", host: "localhost:8081", referrer: "http://localhost:8081/extras/dynamic-groups/61ba43ba-2eb7-4689-aeba-c37b978d2630/edit/"
172.19.0.1 - - [30/Sep/2024:19:39:09 +0000] "POST /extras/dynamic-groups/61ba43ba-2eb7-4689-aeba-c37b978d2630/edit/ HTTP/1.1" 502 559 "http://localhost:8081/extras/dynamic-groups/61ba43ba-2eb7-4689-aeba-c37b978d2630/edit/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
DAMN ! worker 14 (pid: 101) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 14 (new pid: 248)
19:39:10.211 INFO    nautobot :
  Nautobot initialized!
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xaaab2500e750 pid: 248 (default app)
```

### Additional notes:
I am working on upgrading an existing system from 1.6 to 2.3.4. I am experiencing this issue as part of the upgrade. While this is not a brand new installation, the only plugin enabled is an access control plugin. I have not truly attempted with a brand new installation because that "Create 200k devices" step, but I have attached a screenshot of what my dynamic group looks like before I attempt a modification:
![Screenshot 2024-09-27 at 11 37 39 AM](https://github.com/user-attachments/assets/d6efae47-1eb5-4d2a-ac9a-f8bcd3766885)

I CAN successfully modify existing dynamic groups, as long as their filters keep their associated device count below the magic threshold. I have not identified said threshold yet, but it does not immediately appear to be resource dependent. I originally encountered this error in an environment using 20GB memory and 2 cores, but it still fails in the same amount of time (about 10 minutes) with 30 GB memory and 8 cores.

I have noticed similar behavior when I attempt to open up the "IP Addresses" tab in one of the namespaces that has 100k+ IPs assigned to it, so this does not appear to be limited exclusively to Dynamic Groups.

This also happens when I try to perform the update through pynautobot, with some slightly different information in case it helps:
```
>>> dg = nautobot.extras.dynamic_groups.get(id="61ba43ba-2eb7-4689-aeba-c37b978d2630")
>>> dg.update({"filter": {"location": ["DC1"]}})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kfischer/Workspace/stuff/scripts/nautobot_v2_migration/venv/lib/python3.12/site-packages/pynautobot/core/response.py", line 454, in update
    return self.save()
           ^^^^^^^^^^^
  File "/Users/kfischer/Workspace/stuff/scripts/nautobot_v2_migration/venv/lib/python3.12/site-packages/pynautobot/core/response.py", line 424, in save
    if req.patch({i: serialized[i] for i in diff}):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kfischer/Workspace/stuff/scripts/nautobot_v2_migration/venv/lib/python3.12/site-packages/pynautobot/core/query.py", line 428, in patch
    return self._make_call(verb="patch", data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kfischer/Workspace/stuff/scripts/nautobot_v2_migration/venv/lib/python3.12/site-packages/pynautobot/core/query.py", line 290, in _make_call
    raise RequestError(req)
pynautobot.core.query.RequestError: The request failed with code 502 Bad Gateway but more specific details were not returned in json. Check the Nautobot Logs or investigate this exception's error attribute.
```

And the associated nautobot server logs:
```
172.19.0.1 - - [30/Sep/2024:19:09:51 +0000] "PATCH /api/extras/dynamic-groups/61ba43ba-2eb7-4689-aeba-c37b978d2630/ HTTP/1.1" 400 38 "-" "python-requests/2.32.3"
19:09:57.465 INFO    nautobot.core.api.views.ModelViewSet :
  Updating dynamic group kfischer-test-dcim-device (PK: 61ba43ba-2eb7-4689-aeba-c37b978d2630)
Mon Sep 30 19:19:57 2024 - *** HARAKIRI ON WORKER 2 (pid: 89, try: 1, graceful: yes) ***
Mon Sep 30 19:19:57 2024 - HARAKIRI !!! worker 2 status !!!
Mon Sep 30 19:19:57 2024 - HARAKIRI [core 0] 172.19.0.1 - PATCH /api/extras/dynamic-groups/61ba43ba-2eb7-4689-aeba-c37b978d2630/ since 1727723397
Mon Sep 30 19:19:57 2024 - HARAKIRI !!! end of worker 2 status !!!
Mon Sep 30 19:19:57 2024 - HARAKIRI triggered by worker 2 core 0 !!!
2024/09/30 19:19:58 [error] 83#83: *24 upstream prematurely closed connection while reading response header from upstream, client: 172.19.0.1, server: , request: "PATCH /api/extras/dynamic-groups/61ba43ba-2eb7-4689-aeba-c37b978d2630/ HTTP/1.1", upstream: "uwsgi://unix:/var/run/app.uwsgi:", host: "localhost:8081"
172.19.0.1 - - [30/Sep/2024:19:19:58 +0000] "PATCH /api/extras/dynamic-groups/61ba43ba-2eb7-4689-aeba-c37b978d2630/ HTTP/1.1" 502 157 "-" "python-requests/2.32.3"
DAMN ! worker 2 (pid: 89) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 2 (new pid: 170)
19:19:59.171 INFO    nautobot :
  Nautobot initialized!
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xaaaae1b46750 pid: 170 (default app)
```

**Comment by Mesona** [comment]
I attempted to get more solid information on the Namespace issue, and now have sorta solid data.

We have a Namespace with 100k+ assigned IP Addresses, a single VRF, and 14k prefixes. I misread my notes on this issue in my original post, but I attempted to get more solid information this morning. I CAN successfully open the "IP Addresses" tab in the Namespace, possibly because it is paginated. Attempting to open the associated VRF, however, is where it crashes, but only my browser, and only sometimes.

It took me 3 attempts to try to get solid information. The first two crashed my browser, but the nautobot process stayed alive. The third actually fully loaded, after about 15 minutes and with no other tabs open.

I see nothing in the logs to indicate any issues with nautobot. VRFs appear to just have trouble loading that many "Assigned Prefixes" into a single frame.

**Comment by glennmatthews** [comment]
That makes sense. From a quick look at the code, `VRFView` appears to be missing logic to paginate any of its related-object tables (prefixes, route-targets, device assignments) so it presumably is trying to render all 14k prefixes as a single table view. That should be a straightforward fix compared to the DynamicGroup issue. :-)

**Comment by Mesona** [comment]
I do not imagine many people are in a position to experience this issue, but any idea on the timescale for a fix?

**Comment by cmacnevin** [comment]
Please note that this is a serious blocker for us

**Comment by glennmatthews** [comment]
Working on a quick fix for the VRF view and related IPAM views. Fixing the dynamic group case may take a bit longer but it's on my radar.

**Comment by glennmatthews** [comment]
Hi @cmacnevin, @Mesona, please try out the branch in #6364 if you get a chance and let us know if it is a sufficient improvement in the performance of dynamic groups to unblock you.

**Comment by Mesona** [comment]
I am seeing a definite improvement in the VRF, about 75 seconds to load the one with 14k prefixes.

Dynamic groups are still crashing nautobot.

```
Sat Oct 12 00:01:11 2024 - *** HARAKIRI ON WORKER 4 (pid: 118, try: 1, graceful: yes) ***
Sat Oct 12 00:01:11 2024 - HARAKIRI !!! worker 4 status !!!
Sat Oct 12 00:01:11 2024 - HARAKIRI [core 0] 172.20.0.1 - POST /extras/dynamic-groups/5d43763c-94d8-4ec6-9766-9fddb26ccb80/edit/ since 1728690671
Sat Oct 12 00:01:11 2024 - HARAKIRI !!! end of worker 4 status !!!
Sat Oct 12 00:01:11 2024 - HARAKIRI triggered by worker 4 core 0 !!!
2024/10/12 00:01:12 [error] 110#110: *33 upstream prematurely closed connection while reading response header from upstream, client: 172.20.0.1, server: , request: "POST /extras/dynamic-groups/5d43763c-94d8-4ec6-9766-9fddb26ccb80/edit/ HTTP/1.1", upstream: "uwsgi://unix:/var/run/app.uwsgi:", host: "localhost:8081", referrer: "http://localhost:8081/extras/dynamic-groups/5d43763c-94d8-4ec6-9766-9fddb26ccb80/edit/"
172.20.0.1 - - [12/Oct/2024:00:01:12 +0000] "POST /extras/dynamic-groups/5d43763c-94d8-4ec6-9766-9fddb26ccb80/edit/ HTTP/1.1" 502 559 "http://localhost:8081/extras/dynamic-groups/5d43763c-94d8-4ec6-9766-9fddb26ccb80/edit/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
DAMN ! worker 4 (pid: 118) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 4 (new pid: 278)
00:01:13.106 INFO    nautobot :
  Nautobot 2.3.7b1 initialized!
```

**Comment by Mesona** [comment]
Ah, I forgot to try your branch without my plugins, and was even actively working on upgrading one from 1.X to 2.X that I suspect may have interfered. I will give it a try tomorrow without any plugins, totally slipped my mind. Here's hoping it works!
