### ISSUE TITLE
Overlapping/Multiple NAT Support

### ISSUE THREAD

**Issue by achard** [nautobot/nautobot#630]
### Environment
* Python version: 3.6
* Nautobot version: 1.0.3

### Proposed Functionality
Currently, Nautobot only allows a 1:1 mapping of inside IPs to outside IPs. If an inside IP is homed to several ISPs each with their own address space, we cannot accurately represent the NAT configuration in Nautobot :
IP address with this NAT IP (inside) already exists.

### Use Case
AWS Elastic IPs used as the NAT outside address - there can be multiple EIPs attached to a single Inside IP, and they need to be represented in Nautobot

### Database Changes
Update the OnetoOneField to a normal ForeignKey. Associated UI changes to support multiple values.

### External Dependencies
None that I know of.

### Comments:
Issue shamelessly stolen from Netbox - Jeremy doesn't seem to see the value in this.

**Comment by glennmatthews** [comment]
Thank you for the feature request!

**Comment by achard** [comment]
Super excited to see this tagged for the 1.3 release!

**Comment by bryanculver** [comment]
Closed with #1420.
