### ISSUE TITLE
User Timezone Preference

### ISSUE THREAD

**Issue by jpedersen01** [nautobot/nautobot#6343]
### As ...

Ozzie - Operator

### I want ...

Present any times from a field or job in the user's preferred time zone.

### So that ...

Makes scheduling jobs and working with logs much easier when working in the operators time zone

### I know this is done when...

Users can set a preference of time zone and the time displayed back at the bottom of the screen and jobs is adjusted from UTC to the preference.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Apps (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by glennmatthews** [comment]
This is implemented already by #6156, coming in the 2.4 release later this year. :-) Please try it out on next.demo.nautobot.com.

**Comment by jpedersen01** [comment]
Perfect, thank you!
