### ISSUE TITLE
Add device search box to "Connect to Interface" page

### ISSUE THREAD

**Issue by waydh** [nautobot/nautobot#638]
### Environment
* Python version: 3.6.8
* Nautobot version: 1.0.3

### Proposed Functionality
Add a device search box to the "Connect to Interface" page on the B Side box.

### Use Case
When cabling it is hard to remember what rack the B side terminating device is in. The current system works very well, but some times the B side terminating device is not in adjacent racks. In our situation we have hundreds of nodes and we find we need to open up a separate device page and search for the device to find what rack it is in first. Having a device search box in the B Side terminating box on the "Connect to Interface" page would fix this.

### Database Changes
None.

### External Dependencies
None.

**Comment by jathanism** [comment]
Just so we're clear, you're talking about the interface connection view that results in creating a new cable, is that right? For example:

![Cursor_and_Connect_to_Interface_-_Nautobot](https://user-images.githubusercontent.com/138052/124642554-d35a8780-de44-11eb-8ca8-7a6fe14b6b9d.png)

If this is correct, the "Device" selection box in the "B Side" pane already supports searching for devices by hostname. If not, I'd like to ask you to be a lot more specific in exactly what you mean. Screenshots and sample data would be incredibly helpful. Thank you! :)

**Comment by waydh** [comment]
Hello,

Thank you for taking the time to look at this. I am sorry for being so blind - I never saw that search box on the drop down. 

I'll close this out. Sorry again!
