### ISSUE TITLE
GitSync with problematic repo content can result in destructive operations

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#6386]
### Environment
* Nautobot version (Docker tag too if applicable): v2.3.7
* Python version: 3.11
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Setup a GitRepository with a branch reference
2. Push invalid content to the branch, e.g. Jobs that contain bad imports
3. Sync the GitRepository in Nautobot

### Expected Behavior
The Sync should safely fail and no changes should be made within Nautobot and the user should be alerted. The repo within Nautobot should continue to normally operate against the commit from the most recent successful sync.

### Observed Behavior
The Sync fails and destructive actions are taken by Nautobot, such as disabling all Jobs that were previously registered by the repo. Other data like config context may also be removed/updated in an unexpected way.

---

Only upon a successful sync of the repo, should Nautobot make all the necessary updates resulting from the sync, and update the commit id to the current valid commit.

**Comment by rifen** [comment]
**My team wants this very badly :)** 
Today we have to go through extra testing and can't sync jobs automatically into prod because of the risk of them getting blown away.
