### ISSUE TITLE
Colored Job Log Results

### ISSUE THREAD

**Issue by rifen** [nautobot/nautobot#6387]
### As ...

Austin - Network Automation Engineer

### I want ...

To be able to color the background of my info log messages any color. Implementation could be: `self.logger.info("Repository successfully refreshed", extras={"color": "green"})` It would be nice if it would support Hex etc. Might need to include `color-hover` as well.

Bonus point: If I could change the "level" as well but that's nit-picking. It's fine that it says info. The bigger human eye catcher is the color.

### So that ...

If I have a successful log then I can indicate the log by color.
![image](https://github.com/user-attachments/assets/7487cfb0-2700-4dc3-a88c-bf912c22d6b0)

### I know this is done when...

I create a job that uses the built-in logger.

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Apps (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

I am not sure - probably add a column for color to JobResult 🤷🏻

**Comment by smk4664** [comment]
While this is not recommended by the Logging standard library, adding a `success` log level may accomplish what is asked here, by both coloring the row green (as we already have a css for `success`) and changing the "level".  But, that does not allow changing the color to any hex code they want.

**Comment by smk4664** [comment]
This has been implemented in `next` and will be available for jobs starting in Nautobot 2.4.
