### ISSUE TITLE
Fix absolute link to wrong version

### ISSUE THREAD

**Issue by scetron** [nautobot/nautobot#64]
### Change Type
- [ X] Correction

### Area
- [ X] Administration/development

### Proposed Changes
Fix link from https://nautobot.readthedocs.io/en/stable/development/getting-started/ to 

/development/getting-started/

**Comment by jathanism** [comment]
Where did you find this link to stable docs? I thought we got rid of all of those! Thanks.

**Comment by scetron** [comment]
This is in the introduction page of the Developer section. 

https://nautobot.readthedocs.io/en/latest/development/

There's a link to the getting started guide that points to stable. I've opened a PR with the fix :)
