### ISSUE TITLE
UI: Interface role is not color-coded in device interfaces table

### ISSUE THREAD

**Issue by nrnvgh** [nautobot/nautobot#6425]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3.8, 2.4.0a1
* Python version: 
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Create a role of content-type `dcim.interface` using some color
2. Assign an interface on any device to the interface role
3. Look at the `Interfaces` tab for that device in the UI

### Expected Behavior
If assigned, the `Role` column in the `Interfaces` table should be color-coded styled using the assigned color, similar to to the `Status` column

### Observed Behavior
The `Role` column has no color applied.

**Comment by nrnvgh** [comment]
The attached PR fixes the issue...however. I placed `RoleTableMixin` on `InterfaceTable` because that's where `StatusTableMixin` was. When I took a closer look at things after submitting this, I saw that `RoleTableMixin` is also missing on `VMInterfaceTable` and that `InterfaceTable` and `VMInterfaceTable` are currently the only things inheriting from `BaseInterfaceTable`. Should I add `RoleTableMixin` to `VMInterfaceTable` or move things back to `BaseInterfaceTable` ?

**Comment by glennmatthews** [comment]
Thanks for the report and the PR! Since `role` (and `status`) is an attribute of `BaseInterface`, I think you're right that it would make sense to move both `RoleTableMixin` and `StatusTableMixin` to `BaseInterfaceTable` if that works.
