### ISSUE TITLE
Docs - Error in NGINX reading content

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#6437]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3.9
* Python version: 3.11
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Follow the install docs
2. Try loading page
3. Get error loading static content

### Expected Behavior

Loaded content

### Observed Behavior

Error in reading static content. It looks like someone changed the chmod 0755 to chmod 0750 and that errored out.

**Comment by glennmatthews** [comment]
What OS are you attempting this on? I suspect this is a direct result of #6436 rather than a separate issue.

**Comment by jvanderaa** [comment]
These are on Ubuntu 24.04 that I have been going down. `0755` was what I recall from some previous versions of the install Ubuntu 22.04 as well..
