### ISSUE TITLE
Table_config always NULL in New Saved View

### ISSUE THREAD

**Issue by ynicoletti** [nautobot/nautobot#6466]
Nautobot version: 2.3.10 Ubuntu
Django version: 4.2.16
Configuration file: /opt/nautobot/nautobot_config.py
* Database platform, version: mysql
* Middleware(s):

Save view is not saving the columns i set in table view configure

### Steps to Reproduce
1. Press configure on any table view
2. Change columns in view
3. Press save as view
4. See that table_config is null

### Expected Behavior
Table_config is filled and save to a view

### Observed Behavior
table_view is allways NULL

**Comment by HanlinMiao** [comment]
Hi @ynicoletti, thank you for submitting the issue. I followed the steps as described and did not see any issues on my end. See screenshot below and see `table_config` filled out. Would you mind testing it again and maybe present a screenshot or two?
![Screenshot 2024-11-08 at 11 45 28 AM](https://github.com/user-attachments/assets/51d08d70-f627-442f-aad7-2cfc817a4129)

**Comment by MeganerdDev** [comment]
@HanlinMiao I am seeing this issue on the table_config on the current Nautobot [Demo](demo.nautobot.com) on v2.3.11

![image](https://github.com/user-attachments/assets/c70ce14e-d3f3-4043-89d1-244b1c89c6fd)

![image](https://github.com/user-attachments/assets/3a136343-2f1d-491d-abf4-4af767278d79)

**Comment by mzbroch** [comment]
@HanlinMiao I am seeing the same issue - it depends on the actual object type - for example it is not possible to save view with configuration of the table for Prefix objects.

**Comment by HanlinMiao** [comment]
Closed by https://github.com/nautobot/nautobot/pull/6595
