### ISSUE TITLE
Untagged VLAN drop-down widget for Bulk Interface Edit populates different than available_on_device from Interface Edit

### ISSUE THREAD

**Issue by MeganerdDev** [nautobot/nautobot#6470]
### Environment
* Nautobot version (Docker tag too if applicable): v2.3.10, v2.3.11b
* Python version: 3.11
* Database platform, version: PG13
* Middleware(s): N/A

### Issue
I am seeing unexpected differences between populated results for the `Untagged VLAN` drop-down widget between `Bulk Interface Edit` vs `Interface Edit `. The drop-down is populating on Interface Edit, but on Bulk Interface Edit it is empty. Even if I am only doing a "bulk edit" of a single interface, which I would expect to populate the same data as `Interface Edit`?

It appears to be related to inhereted VLAN, or is my suspicion (see digging notes)

### Steps to Reproduce
1. 
2.
3.

### Expected Behavior
The same options should populate under `Untagged VLAN` between the 2-forms

### Observed Behavior
The drop-down populates differently for the same interface between the 2-forms

### Digging
The drop-downs populate based on response from 2-different queries to /api/ipam/vlans endpoint
 - Bulk Interface Edit HTTP GET -> locations=null&locations={uuid}
 - Interface Edit HTTP GET -> available_on_device={uuid}

Looking in to available_on_device, led me to the following candidate I was considering:

> I suspect the difference of not using available_on_device on the Bulk Interface Edit API query is going to be the issue
>
> I found public issue (#5050) and patch (#6091) which indicated to me that available_on_device was created to address a possible scenario
>
> PR Notes: updated the available_on_device/get_for_device filter in the VLANFilterSet to include not just the device(s)' locations, but also those location(s)' ancestors

#### showing the widgets in question, but not showing data to demo the issue
![image](https://github.com/user-attachments/assets/36621d8b-8220-4a71-aad5-22cf22834501)
![image](https://github.com/user-attachments/assets/62bf0b5a-614c-45b2-83d1-c71caa3c5a32)

**Comment by MeganerdDev** [comment]
There will be testing tomorrow around this, and I will have more to provide

**Comment by glennmatthews** [comment]
IIRC part of the complexity here is in that bulk-edit can theoretically include interfaces from multiple distinct devices simultaneously, so that has to be factored in to any logic. For example, it should probably only show VLANs that are applicable to *all* specified devices, not *any* specified device.

**Comment by emdeefive** [comment]
Hi @glennmatthews One possible solution we were bouncing around for a quick win might be that if all of the interfaces in the bulk edit are the same devices then use `available_on_device` filter and then move to the other method if different devices. Or perhaps one step further (not sure if this is operationally effective) if all devices are in the same location then aggregate the VLANs from all of the devices using the `available_on_device` filter.
