### ISSUE TITLE
Misleading error message when csv importing cables and one end of the cable is a virtual port

### ISSUE THREAD

**Issue by sirtux** [nautobot/nautobot#648]
### Environment
* Python version: 3.9.1
* Nautobot version: 1.0.3

### Steps to Reproduce
1. Try to import a cable between a physical port and a virtual port

### Expected Behavior
A error message is displayed which informs the user of the type of error

### Observed Behavior
Error message:
`CableCSVForm' has no field named 'termination_b_id`.

### Better behaving - the API
I only found the culprit as I tried to do the same via API,
which rendered the following error:
`pynautobot.core.query.RequestError: The request failed with code 400 Bad Request: {'status': ['This field cannot be blank.'], 'termination_b_id': ['Cables cannot be terminated to Virtual interfaces']}`

I would like to see the same error message as the API reports in the CSV import.

**Comment by jathanism** [comment]
This looks like you ran into a very fun side effect of the differing code paths between UI form validation and API serializer validation. Thanks for the report!

**Comment by glennmatthews** [comment]
Possibly related closely to #371?

**Comment by sirtux** [comment]
Hmm, checked that, since #371 is also reported by me - but it seems that it might be related, but I guess had a different root cause.

However, I guess that @jathanism is right that different code paths for validation exists, and this is not optimal, maybe they can be merged?

**Comment by gsnider2195** [comment]
The error message appears to be correct in v1.4.3.

![Image](https://user-images.githubusercontent.com/75227981/192803114-574ba8b7-4c6c-4388-8e30-18ad9b47ca29.png)

Was the plan to change the csv form field names in the UI to match the API? There is in fact no `termination_b_id` form field for the `CableCSVForm` so the error reported was correct. The field names are `side_b_device`, `side_b_type` and `side_b_name`.



![Image](https://user-images.githubusercontent.com/75227981/192804001-b185809b-cf8d-484e-86e3-8f8580c000fd.png)

**Comment by glennmatthews** [comment]
Tested with the reworked CSV import in #3722 and the error appears correct here as well:

![image](https://github.com/nautobot/nautobot/assets/5603551/289ca31a-6e48-4221-a50c-053c93d4703c)
