### ISSUE TITLE
/ipam/prefixes/UUID/available-ips endpoint doesn't consider IPs in child prefixes

### ISSUE THREAD

**Issue by nrnvgh** [nautobot/nautobot#6496]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3.10
* Python version: 3.11
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Create a prefix (e.g. 6.0.0.0/28)
2. Create a child prefix under the created prefix (e.g. 6.0.0.0/29)
3.  Create an IP in the child prefix (e.g. 6.0.0.1)
4. Make an API call for /ipam/prefixes/UUID_OF_PARENT_PREFIX/available-ips; note the IP created in step 3 is included in the response
5. Make an API call for /ipam/prefixes/UUID_OF_CHILD_PREFIX/available-ips; note that the IP created in step 3 is not included in the response

### Expected Behavior
"available" to me implies a set of IPs in a prefix which minus the IPs in that prefix which exist in Nautobot. In other words, "available" means "available to created", not "all the possible IPs in a given prefix".

### Observed Behavior
Observed behavior is documented in the "step to reproduce".

**Comment by nrnvgh** [comment]
I'm thinking this isn't news to you, but just so it's documented here: This appears to be change in behavior compared to 1.6.

**Comment by lampwins** [comment]
This is very likely related to #6170 which resulted in us adding a new method that get IPs that does account for child prefixes. We should just need to change these endpoints to use that method.
