### ISSUE TITLE
IPAddressTable Missing default_columns

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot#6498]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3.9
* Python version: 3.9
* Database platform, version: Postgres
* Middleware(s): N/A

### Steps to Reproduce
1. Install Nautobot.
2. Create App with TableExtension for IPAddressTable
3. Attempt to run Nautobot and review logs.

### Expected Behavior
Expect to be able to customize the IPAddressTable.

### Observed Behavior

Receive error:

```
File "/opt/nautobot/lib64/python3.9/site-packages/nautobot/extras/plugins/__init__.py", line 643, in _modify_default_table_columns
2024-11-11 08:58:33     if column_name in table.Meta.default_columns:
2024-11-11 08:58:33 AttributeError: type object 'Meta' has no attribute 'default_columns'
```

**Comment by glennmatthews** [comment]
To be clear - we should fix the logic in `extras/plugins/__init__.py` rather than requiring all tables to define this optional parameter.

**Comment by smk4664** [comment]
A note on this, the IPAddressListView does not use the same model that would be discovered through `get_related_class_for_model` since the `IPAddressListView` uses the table name `IPAddressDetailTable` instead of `IPAddressTable`
.
