### ISSUE TITLE
Job Results UI should render log messages immediately

### ISSUE THREAD

**Issue by retnuh** [nautobot/nautobot#650]
### Environment
* Python version: 3.7
* Nautobot version: 1.0.3

### Steps to Reproduce
1.  Run any job that has time consuming steps

### Expected Behavior
Log statements in the job should be rendered when they've been logged.  Jobs can be complex and have several steps; it would be nice if the statements appeared while the user is waiting for the job to complete.

### Observed Behavior
All log statements appear all at once, after the job completes.

**Comment by itdependsnetworks** [comment]
@Joezeppe You helped with a similar process before, perhaps you could look at this as well? 

pinging @lampwins for visibility.

**Comment by glennmatthews** [comment]
A few code references that should be useful:

> https://github.com/nautobot/nautobot/blob/develop/nautobot/extras/templates/extras/inc/jobresult.html#L34
> https://github.com/nautobot/nautobot/blob/develop/nautobot/extras/templates/extras/inc/jobresult.html#L59

We only attempt to render the job logs if the jobresult is completed - removing these checks should be part of the fix.

> https://github.com/nautobot/nautobot/blob/develop/nautobot/project-static/js/job_result.js#L35

We only call `jobTerminatedAction` (which is what reloads the entire page, giving the option to re-render the page template with the latest job logs) if the jobresult is completed.

A simple fix would possibly be to allow the page template to render logs from non-completed JobResults and also to refresh the page every N seconds until a terminal state is reached; a more ideal fix might be to move the job log rendering out of the page template and into the page JS to dynamically re-render the logs as the jobresult data is refreshed via AJAX.

**Comment by Joezeppe** [comment]
I will look into possible solutions to dynamically render the job logs while it's running.

**Comment by jedelman8** [comment]
@Joezeppe hey Sammy, are you going to be able to look into this?

**Comment by jvanderaa** [comment]
@jedelman8 this could be included on the Jobs epic.

**Comment by glennmatthews** [comment]
As I understand it, the data model changes in #1030 make this much more feasible to implement.

**Comment by jedelman8** [comment]
Should includes API for job log entry too

**Comment by glennmatthews** [comment]
#1152 is probably a pre-requisite for this.

**Comment by jathanism** [comment]
> A simple fix would possibly be to allow the page template to render logs from non-completed JobResults and also to refresh the page every N seconds until a terminal state is reached; a more ideal fix might be to move the job log rendering out of the page template and into the page JS to dynamically re-render the logs as the jobresult data is refreshed via AJAX.

The simple fix is easily attainable. Unfortunately since we're using `django-tables2` to render the tables, there isn't really an easy way to use something like DataTables or an AJAX call without totally refactoring this view.
