### ISSUE TITLE
Wireless & Controller Models UI Tweaks

### ISSUE THREAD

**Issue by cmsirbu** [nautobot/nautobot#6503]
1. Add missing `+` button for `Controller Managed Device Groups` in the sidebar for consistency. Rename nav entry to just `Device Groups`.
![image](https://github.com/user-attachments/assets/0eb814a9-e2a8-4f01-9939-402e70f3ca6e)

2. Under `Radio Profile` make the help text for channels more explicit `Comma-separated list of allowed channel numbers for this radio profile.`
![image](https://github.com/user-attachments/assets/6841f057-9eb3-4a5c-9db7-76c306570c99)

3. Add `Regulatory Domain` to the list view for Radio Profiles.

4. In the detailed view for Controllers the column heading for the "Controller managed device groups" should be summarized to just `Device Group`.
![image](https://github.com/user-attachments/assets/170e68ff-ff9c-4242-b057-f7e0a6d3d310)

5. `Wireless Networks` tab in Controller detail view - table has some extra half row at the bottom and an extra header:
![image](https://github.com/user-attachments/assets/5276925e-2b1f-4519-bade-e4f31ad78a8f)

**Comment by bryanculver** [comment]
@lampwins Are we renaming "Access Point Groups" to "Device Groups" in the Nav under Wireless?

<img width="289" alt="image" src="https://github.com/user-attachments/assets/839f8aff-4549-48bb-85cd-d3a5edcdf0da">
