### ISSUE TITLE
Add VRFs column for IPAM Child Prefixes (Tab)

### ISSUE THREAD

**Issue by MeganerdDev** [nautobot/nautobot#6518]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3.11
* Python version: 3.11
* Database platform, version: PG13
* Middleware(s): N/A

VRFs column for IPAM Child Prefixes (Tab) to be displayed, similar to Prefixes implementation on #6494

![image](https://github.com/user-attachments/assets/6a90628d-cdf9-459f-ade0-3acc6561208f)
eg: https://demo.nautobot.com/ipam/prefixes/0f41685c-8efc-40b9-93b8-fe8e90694429/prefixes/

### Steps to Reproduce
1. Browse Prefixes in UI
2. Open Prefix object with Child Prefixes
3. Open 'Child Prefixes' tab

### Expected Behavior
VRFs column can be added, or visible as default

### Observed Behavior
There is no VRFs column, and there is no modification for the view.
So that may present an additional blocker/change on this if its not default.

### Notes:
- Similar to issue #6490 for VRF column on Prefix table view, and subsequent PR #6494
- Created this issue as bug, since #6490 was tagged with bug, but may be apt as feature request

**Comment by joaopsys** [comment]
I would also like to add that not only the VRF is missing, but the "Locations" as you can see is showing "1" instead of showing the Location itself - as discussed in https://github.com/nautobot/nautobot/issues/6231
