### ISSUE TITLE
The Jobs REST API feature should auto-retrieve objects defined as ObjectVar fields

### ISSUE THREAD

**Issue by jmcgill298** [nautobot/nautobot#652]
### Environment
* Python version: 3.8
* Nautobot version: 1.0.2

### Steps to Reproduce
1. Create a Job with a field defined as ObjectVar
2. Take necessary steps to have job available to Web and Worker instances
3. Use the REST API to start a job (It is unclear how the ObjectVar field should be represented, but I would expect a dict with key/value pairs matching the Related Object's field/value pairs, such that calling the ORM's `RelatedObjectModel.objects.get()` with the data would return the single matching record (or else raise an exception).

### Expected Behavior
I expected the field to automatically look up the Record in the ORM as defined in the payload, and the variable in the job to be a ModelBase instance.

### Observed Behavior
The field is not looked up and is whatever data is sent via the payload. For instance, if I pass a string, say the UUID of the Related Object, it will be the string passed in via the payload. If is a dict, say something like {"id": uuid_of_related_object}, it is a dictionary with the key value pair(s) passed in via the payload. This results in later code calling attributes on the expected ModelBase instance to raise errors, since these attributes are not defined for str or dict objects.

**Comment by jmcgill298** [comment]
This is related to #651 but is a distinct side effect of that behavior, and fixing that behavior will need to address how to validate ObjectVar fields, as these cannot be passed via REST.

**Comment by jmcgill298** [comment]
For anyone looking for a workaround, you can use try/except or isinstance in the job to catch this before executing code, and normalize the field data in the job before executing any code using the field.

```
from nautobot.dcim.models.sites import Region
from nautobot.extras.jobs import Job, ObjectVar


class CustomJob(Job):
    region = ObjectVar(
        model=Region
    )

    def run(self, data, commit):
        region = data["region"]
        if isinstance(region, dict):
            region = Region.objects.get(**region)
        elif isinstance(region, str):
            region = Region.objects.get(id=region)
```

**Comment by glennmatthews** [comment]
Thanks for the report!
