### ISSUE TITLE
Notes Form Entry

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#6532]
### As ...

Ozzie - Operator

### I want ...

to have the Notes form entry accept the key combination of CMD + Enter to hit the submit button.

### So that ...

The app performs like many form entry systems on the web.

### I know this is done when...

- I type in a new note
- Hit CMD + Enter that the "Create" Button gets selected.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Apps (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

None

**Comment by HanlinMiao** [comment]
Thanks for the submission @jvanderaa. I have a PR attached to this issue please pull my branch down and see if the feature is working as you expected.
