### ISSUE TITLE
Adding an Interface component to a Device fails

### ISSUE THREAD

**Issue by mzbroch** [nautobot/nautobot#6537]
### Environment
* Nautobot version (Docker tag too if applicable): `next` branch - as of 2024-Nov-13
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Create a Device instance in UI
2. Attempt to add Interface component through Device detail view (GUI)
3.

### Observed Behavior

Error is returned during validation:
```
Virtual Device Contexts
Ethernet1: "" is not a valid UUID.
```

This might potentially be related, but as a part of testing tried attaching an Interface to a VDC and this resulted in a different error message:
```
ValidationError at /dcim/interfaces/add/
{'virtual_device_contexts': ["Virtual Device Context with names ['test'] must all belong to the same device as the interface's device."]}
```

**Comment by HanlinMiao** [comment]
Closed by https://github.com/nautobot/nautobot/pull/6545
