### ISSUE TITLE
Incorrect VRF filter used when clicking the VRFs column in a Prefix table (also in the Prefix Bulk Edit table)

### ISSUE THREAD

**Issue by joaopsys** [nautobot/nautobot#6547]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3.11
* Python version: 3.11
* Database platform, version: PG13
* Middleware(s): N/A

### Steps to Reproduce
1. Create a new Prefix and assign 3 VRFs to it (for example)
2. Go to the Prefix table and add the VRF Column
3. Locate your new Prefix
4. Click the number '3' in the VRFs column to get redirected to the VRFs page

### Expected Behavior

I expected to be redirected to the VRFs page correctly showing the 3 VRFs assigned to my Prefix

### Observed Behavior

I get redirected to the VRFs page with an incorrect filter being used - `prefixes=` instead of `prefix=`

![image](https://github.com/user-attachments/assets/1a3a2cbb-642b-4dad-941c-d0c69bec575e)

![image](https://github.com/user-attachments/assets/8fbe130b-d5ff-46da-a57e-c6221a648f73)

**Comment by HanlinMiao** [comment]
Thanks for submitting the issue! Seems like `VRFFilterSet` does not have a `prefixes` filter, instead it has a `prefix` filter.
