### ISSUE TITLE
`.parent` is not accessible for a Prefix object during custom validation, but `.ancestors()` is

### ISSUE THREAD

**Issue by joaopsys** [nautobot/nautobot#6548]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3.11
* Python version: 3.11
* Database platform, version: PG13
* Middleware(s): N/A

### Steps to Reproduce
1. Add a custom validator to a Prefix and just raise a validation error with `f"Parent is {self.context['object'].parent} and Ancestors is {self.context['object'].ancestors()} and Descendants is {self.context['object'].descendants()}"`
2. Verify that `.parent` is always `None`
3. Verify that `.ancestors()` and `.descendants()` work as expected

### Expected Behavior
I expected `.parent` to resolve to the closest ancestor. This works if we build a custom validator for `IPAddress`, it will return the parent prefix correctly

### Observed Behavior
`.parent` is always `None`, while `.ancestors()` and `.descendants()` work as expected

![image](https://github.com/user-attachments/assets/d980b26a-3633-4ba7-a3d6-ddd267534cfc)

**Comment by glennmatthews** [comment]
Issue is likely because we currently don't populate `parent` until `save()` - might need to move that logic to `clean()`.
