### ISSUE TITLE
Add OSFP1600 and OSFP-XD interface types

### ISSUE THREAD

**Issue by austind** [nautobot/nautobot#6550]
### As ...

Austin - Network Automation Engineer

### I want ...

Add the [OSFP1600 and OSFP-XD](https://osfpmsa.org/assets/pdf/OSFP1600_and_OSFP-XD.pdf) interface types.

### So that ...

So I can properly model devices that use these interface types.

### I know this is done when...

I can select OSFP1600 and OSFP-XD as interface type options.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [X] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Apps (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

Unsure

### External Dependencies

None

**Comment by austind** [comment]
I can handle this if approved.

**Comment by glennmatthews** [comment]
No objection here - go right ahead!
