### ISSUE TITLE
Allow REST API exclude M2M fields

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#6556]
To support cases where many to many fields degrade performance of API responses (even in depth 0 cases), introduce support to ignore/exclude M2M fields in the API response.

So an API consumer can specify `?exclude_m2m=true` and not get any M2M fields at all in the response. This is particularly needed in problem areas like VRF where there are several M2M relationships and frequent opportunity for data scale. The API select2 widget will generally benefit from this across the board.

**Comment by Mesona** [comment]
This has been declared a blocker to our efforts to migrate to v2, as we have a few large resources (namespaces, VRFs) that run a risk of causing OOM nautobot crashes when queried.
