### ISSUE TITLE
Prefix permission constraints are bypassed when using the `available-prefixes` API

### ISSUE THREAD

**Issue by joaopsys** [nautobot/nautobot#6583]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3.12
* Python version: 3.11
* Database platform, version: PG16
* Middleware(s):

### Steps to Reproduce
1. Create a Prefix, e.g `10.10.0.0/24` with description `ThisDescriptionIsMandatory`.
2. Create a new user and set his permissions to view all prefixes
3. Create a custom add/edit/delete Prefix permissions for this user with the constraint `{"description": "ThisDescriptionIsMandatory"}`
4. As this new user, query the `available-prefixes` API endpoint on the newly created prefix `10.10.0.0/24` and request a new child prefix with any random description, e.g. `test` (e. John: need to verify that this exists on both GET and write versions of this endpoint)
5. Verify the Prefix is created successfully

### Expected Behavior

The new user should have gotten an object-level permission error, since the newly created prefix (child of `10.10.0.0/24`) does not respect the Prefix add/edit/delete permission constraint assigned to the user - i.e. the description of the newly created prefix is NOT `ThisDescriptionIsMandatory`.

### Observed Behavior

The new child prefix was created not respecting the permission constraints.

This same user is NOT allowed to create that same prefix in the GUI, but the `available-prefixes` endpoint allows it.

Besides, by browsing this new child prefix in the GUI, the user can't delete or edit it - which is expected since the description doesn't match the constraints. But if this is the case, the user shouldn't have been able to create it.

**Comment by glennmatthews** [comment]
Same issue likely applies to `available-ips` and `available-vlans` endpoints.
