### ISSUE TITLE
Unable to install Jobs on 1.1.0b running the RQ worker

### ISSUE THREAD

**Issue by tim-fiola** [nautobot/nautobot#659]
### Environment
* Python version: 3.8.10
* Nautobot version: 1.1.0b

### Steps to Reproduce
1.  This may be related to #656 
2. This is a fresh install on Ubuntu 20.04.2, running the RQ worker instead of Celery due to #653 
3. Installed a known, working job (`Hostname` job from demo.nautobot.com) into `$NAUTOBOT_ROOT/jobs` folder by pasting that working code into a .py file in that directory
4. Accessing Extensibility-->Jobs in the UI

### Expected Behavior
Taken to Jobs page

### Observed Behavior
The https://192.168.18.19/extras/jobs/ page shows this:

===============
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

```
<class 'django.core.signing.BadSignature'>

Signature "b'0IhZ5BiOe6jzKYqmAYR3qgAyrqkMH+jz/ijItUT5GfI=\n'" does not match

Python version: 3.8.10
Nautobot version: 1.1.0b1
```
=============

This state persists even when I remove the .py file from `$NAUTOBOT_ROOT/jobs`

**Comment by glennmatthews** [comment]
As you noted, this is almost certainly the same root cause as #654 and #656.

**Comment by tim-fiola** [comment]
Per @jathanism this won't work with RQ worker as it's deprecated. The signature problem itself is addressed in the other tickets
