### ISSUE TITLE
kombu.exceptions.EncodeError when trying to execute Job

### ISSUE THREAD

**Issue by tim-fiola** [nautobot/nautobot#663]
### Environment
* Python version: 3.8.10
* Nautobot version: 1.1.0b1

### Steps to Reproduce
1.  Copy [Planned Site Job](https://nautobot.readthedocs.io/en/latest/additional-features/jobs/#creating-objects-for-a-planned-site) from Nautobot docs to  a `.py` file `$NAUTOBOT_ROOT/jobs/` 
2. In Web UI, Extensibility-->Jobs
3. Run the `New Branch` job

### Expected Behavior
Job to execute

### Observed Behavior
Got the following message in the UI:

 **Server Error**
**There was a problem with your request. Please contact an administrator.**

**The complete exception is provided below:**

```
<class 'kombu.exceptions.EncodeError'>

Object of type DeviceType is not JSON serializable

Python version: 3.8.10
Nautobot version: 1.1.0b1
```

**Comment by jathanism** [comment]
Oof this one is ugly. I am able to reliably reproduce it and attempts to get nested serialization of model objects using JSON and the `NautobotKomboJsonDecoder` class will alleviate issues with *our* objects such as `DeviceType`, but ultimately results the same erro but with `ModelState`:

```
Object of type ModelState is not JSON serializable
```

This is `django.db.models.base.ModelState` which is the internally cached state of the model. I've never seen this leak before. 

I can completely obviate this error entirely by hard-coding these settings in `nautobot_config.py`:

```python
CELERY_ACCEPT_CONTENT = {"pickle"}
CELERY_RESULT_ACCEPT_CONTENT = CELERY_ACCEPT_CONTENT
CELERY_TASK_SERIALIZER = "pickle"
CELERY_RESULT_SERIALIZER = "pickle"
```

This forces Celery to use Pickle. This isn't necessarily desirable, but I think we have two options:

1. Go with Pickle for now while we sort it out
2. Try to get to the bottom of how to do nested JSON serialize/deserialize for messaging in Celery

**Comment by lampwins** [comment]
Given the current feature set in 1.1, pickle would work fine. However the switch to json is driven by the scheduler because args and kwargs have to be stored in the DB. So in a pinch, to get 1.1 we could switch it back to pickle and then figure out what the issue is.
