### ISSUE TITLE
"Unable to load documentation" (in Docker installation ?)

### ISSUE THREAD

**Issue by u1735067** [nautobot/nautobot#665]
### Environment
* Python version: 3.6
* Nautobot version: 1.0.2 (but 1.0.3 too on demo instance), deployed using the Docker image

### Steps to Reproduce
1. Login, add device
2. Click the "❔" button (top right)

### Expected Behavior
See the documentation related to the form

### Observed Behavior
`Unable to load documentation, file not found: /usr/local/lib/python3.6/site-packages/docs/models/dcim/device.md `

### Note
This was already an old issue with Netbox (https://github.com/netbox-community/netbox-docker/issues/253) if it can help.

**Comment by jvanderaa** [comment]
This is also an issue within a non-docker install.

**Comment by jathanism** [comment]
Hmmm I thought we had fixed this by moving `docs` to `nautobot/docs` so they get included in package builds. We might have missed a reference?

**Comment by jathanism** [comment]
Confirmed. Thanks for the report @u1735067

**Comment by jathanism** [comment]
The template code has a check for `settings.DOCS_ROOT` which we must have overlooked when we were doing all the other `*_ROOT` settings, because it's defaulting to this:

```python
>>> from django.conf import settings
>>> settings.DOCS_ROOT
'/opt/nautobot/lib/python3.8/site-packages/docs'
```
