### ISSUE TITLE
Cannot View Contact / Team Tags through Api

### ISSUE THREAD

**Issue by Mesona** [nautobot/nautobot#6662]
### Environment
* Nautobot version (Docker tag too if applicable): Demo Nautobot
* Python version: Demo Nautobot
* Database platform, version: Demo Nautobot
* Middleware(s):

### Steps to Reproduce
1. Create contact (or team)
2. Assign a tag
3. Open api view of contact

### Expected Behavior
I expected to see the assigned "tags", as I do with other resources

### Observed Behavior
"tags" are missing.
[Example contact](https://demo.nautobot.com/extras/contacts/d17d56d7-cf14-4361-9583-ff5a586c0acb/?tab=main) (I think it's part of the standard demo data and might not get deleted at end of day)
[API browser](https://demo.nautobot.com/api/extras/contacts/d17d56d7-cf14-4361-9583-ff5a586c0acb/) where "tags" are missing

I am not sure if this is a bug or should be along feature request lines, but figured I would put it here.

**Comment by glennmatthews** [comment]
Thanks for the report! This was fixed in `next` as a part of #6556 feature work (PR #6581) and will be included in the upcoming 2.4.0 release.
