### ISSUE TITLE
Providers Circuits Table missed type column

### ISSUE THREAD

**Issue by Rul-Moy** [nautobot/nautobot#6664]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3.X
* Python version: 3.11.9
* Database platform, version:
* Middleware(s):

The circuit_type column was not renamed in default_columns in CircuitTable, causing this column to be hidden in the Providers view, for example

### Steps to Reproduce
1. Open Providers view
2. Check Circuits columns
3. Circuit_type is missed

**Comment by glennmatthews** [comment]
Thanks for the report! You're absolutely right about the issue and about its root cause.

**Comment by Rul-Moy** [comment]
I'm interested in having it solved starting from version 2.3.0, which is the version we are currently using. Thanks
