### ISSUE TITLE
Copy on Hover Button in Search Results Does Not Update Clipboard

### ISSUE THREAD

**Issue by kacem-expereo** [nautobot/nautobot#6678]
### Environment
* Nautobot version : v2.3.0
* Python version: 3.11
* Database platform, version: PostgreSQL 14
* Middleware(s):

### Steps to Reproduce
1.Perform a search that yields results (the /search/ endpoint is in the URL).
2.Click the “Copy on Hover” button on any search result.
3.The clipboard is not updated as expected.

### Expectation
Clicking the “Copy on Hover” button should overwrite the clipboard with the content intended for copying.

### What happened
Clicking the “Copy on Hover” button does nothing, and the clipboard remains unchanged.

### What did I check
- An element with the exact id (copy_3d0ddb05-f9b1-4e75-b5ec-1df0ef926cce) exists
- I have the issue only under the search view, the button works fine anywhere else.
- The issue can be reproduced on the demo website : https://demo.nautobot.com/search/?q=+10.0.0.0%2F32
- I tried to compare the code with pages where the feature works, not sure to find any difference(clipboard mini js file is present.. html is very similar..)

**Comment by HanlinMiao** [comment]
Issue is confirmed locally and adding the following code block to `search.html` seems to fix it.
```
{% block javascript %}
    {{ block.super }}
    <script>
        var clipboard = new ClipboardJS('.btn');
    </script>
{% endblock %}
```

**Comment by kacem-expereo** [comment]
Thank you so much !
