### ISSUE TITLE
Documentation problem about ldaps

### ISSUE THREAD

**Issue by itheodoridis** [nautobot/nautobot#677]
### Environment
* Python version: 3.8.10
* Nautobot version: 1.0.3
### Steps to Reproduce
1. Do a clean install of Ubuntu 20.04
2. Follow installation guide up to the optional ldap section
3. Follow ldap installation guide and use Ldaps with port 636 to talk to an MS-AD Ldap server.

### Expected Behavior
Successful communication with Ldap server, successful login for AD user.

### Observed Behavior
Could not communicate with Ldap server, could not login. The problem has to do with the option 
`LDAP_IGNORE_CERT_ERRORS = True`
which does nothing for nautobot. It works when replaced by
`ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_NEVER) `
which is mentioned in parenthesis

All this has been discussed in the Nautobot slack channel

**Comment by jathanism** [comment]
Thank you @itheodoridis for the bug report! :)
