### ISSUE TITLE
Syncing Git repositories reports RQ workers are no longer supported

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#680]
### Environment
* Python version: 3.6.14
* Nautobot version: 1.1.0b2

When syncing a git repository in the demo environment while the repository is syncing I briefly see this warning message:

![Screen Shot 2021-07-13 at 7 08 33 AM](https://user-images.githubusercontent.com/14947575/125457248-5ef6b245-1114-4400-9013-b6a405453d65.png)

It looks like the job did indeed execute in Celery however.

### Steps to Reproduce
1.  Sync a git repo

### Expected Behavior

Repo syncs without warning.

### Observed Behavior

Warning about RQ displayed.

**Comment by glennmatthews** [comment]
Thanks for the report! I agree, we should not complain if RQ is still running, so long as Celery is running as well.

https://github.com/nautobot/nautobot/blob/develop/nautobot/extras/utils.py#L115
