### ISSUE TITLE
Tags menu item greyed out for users with limited permissions

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#686]
### Environment
* Python version: 3.6.14
* Nautobot version: 1.1.0b2

Take a look at the 1.1.0b2 sandbox at [https://develop.demo.nautobot.com/](https://develop.demo.nautobot.com/) log in as demo.  The `Tags` menu item is greyed out.

### Steps to Reproduce
1.  Create a user with limited permissions NOT super user
2.  Make sure the user has full permissions on extras/tags
3.  log in as user look at the menu item, it's greyed out

### Expected Behavior

Menu available

### Observed Behavior

Menu greyed out

**Comment by jathanism** [comment]
Confirmed! This is a quick fix. Thanks.
