### ISSUE TITLE
Clone a computed field and carry over select fields

### ISSUE THREAD

**Issue by FragmentedPacket** [nautobot/nautobot#698]
### Environment
* Python version: 3.6
* Nautobot version: 1.1.0b2

### Proposed Functionality
When I click **Clone** on an existing **Computed Field**, I'd like for some of the fields to be carried over to the new form.

### Use Case
Don't want to have to repopulate all fields again when cloning a computed field.
![image](https://user-images.githubusercontent.com/29315002/125703224-301fd3ba-e2fc-47f9-bc48-8ac6cdd0cc56.png)

Now if I click **Clone**. It brings up the new form, but it's blank.
![image](https://user-images.githubusercontent.com/29315002/125703285-45b8e6ac-1204-4fa1-ad03-11a613e4e4d7.png)

I would say we should probably carry over the following:
- Content Type
- Description
- Template
- Fallback Value
- Weight

I don't feel passionate about all the fields, but do what y'all think is best.

### Database Changes
None

### External Dependencies
None

**Comment by FragmentedPacket** [comment]
I can implement whichever way y'all want to go with this. Let me know.

**Comment by glennmatthews** [comment]
Thank you! Your proposed list of carry-over attributes looks good to me. Go for it!
