### ISSUE TITLE
Computed Fields, detailed view is not rendering correctly with a long template

### ISSUE THREAD

**Issue by dgarros** [nautobot/nautobot#718]
### Environment
* Python version: 3.6
* Nautobot version: 1.1.0b2

### Steps to Reproduce
1. Create a computed field with a long template on a single line

### Expected Behavior
The detailed view for all computed field should render properly.

### Observed Behavior
The detailed view for a computed field with a long template is not rendering correctly

![image](https://user-images.githubusercontent.com/304126/126376119-7724edaa-f208-4f0c-a0c9-df29b5906344.png)

**Comment by FragmentedPacket** [comment]
This appears it may be more or less related to tables and the `<pre>` tag that we use in other areas as well.

I believe I have a fix for this by adding the `table-layout: fixed` to some CSS.

**Comment by jathanism** [comment]
IMO we should move the template over to its own panel, like on the right side, similarly to Config Contexts/Export Templates?

Right page:
![Cursor_and_Connection_Description_-_Nautobot](https://user-images.githubusercontent.com/138052/127222033-656c92fe-2594-4183-b669-6236d25ab155.png)

Full width:
![Cursor_and_Connection_Description_-_Nautobot](https://user-images.githubusercontent.com/138052/127222107-30d46d5a-ec2e-42dd-b504-ca1a750fe70d.png)

Comparing them side-by-side, I'm partial to the latter.

**Comment by glennmatthews** [comment]
+1 for moving them to the full-width content, though this may still be an issue with a long-enough template string, in which case I think @FragmentedPacket 's proposed CSS fix may also be necessary.

**Comment by jathanism** [comment]
> +1 for moving them to the full-width content, though this may still be an issue with a long-enough template string, in which case I think @FragmentedPacket 's proposed CSS fix may also be necessary.

If we moved to full-width, since the full-width content panel is not a table, it will overflow and present a scroll bar (see the right panel screenshot for what that looks like).

**Comment by jathanism** [comment]
FYI in #737 I updated the detail view template to show the **Template** in the right page panel:
> Right page:
> ![Cursor_and_Connection_Description_-_Nautobot](https://user-images.githubusercontent.com/138052/127222033-656c92fe-2594-4183-b669-6236d25ab155.png)

And here's full:
> Full width:
> ![Cursor_and_Connection_Description_-_Nautobot](https://user-images.githubusercontent.com/138052/127222107-30d46d5a-ec2e-42dd-b504-ca1a750fe70d.png)

Let's make a final decision on which one we prefer and call this done.

**Comment by itdependsnetworks** [comment]
My preference is right page :)
