### ISSUE TITLE
Power Draw Does Not Provide a UtilizationData type for Graphing

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#723]
### Environment
* Python version: n/a
* Nautobot version: 1.1.0b2 (still present)

_Reported on Slack originally, documenting the issue - https://networktocode.slack.com/archives/C01NWPK6WHL/p1626817947139500_

### Steps to Reproduce
1. Create racks
2. Add power allocation
3. Get error when going to the rack

### Expected Behavior

Rack page to render

### Observed Behavior

Receives an error:

```
<class 'AttributeError'>
'dict' object has no attribute 'numerator'
Python version: 3.8.6
Nautobot version: 1.0.3
```

**Comment by glennmatthews** [comment]
@jvanderaa Can you give any status update on this? Thanks!

**Comment by jvanderaa** [comment]
@glennmatthews deprioritized through the week. I can prioritize it for today yet, depending on when the next release is planned.
