### ISSUE TITLE
SSO Custom Auth Backend Support

### ISSUE THREAD

**Issue by FragmentedPacket** [nautobot/nautobot#728]
### Environment
* Python version: 3.6
* Nautobot version: 1.0.3

### Proposed Functionality
Currently, only `social_core.backends` are supported within Nautobot to properly redirect to an external login source due to the following code.

https://github.com/nautobot/nautobot/blob/dd731f302f363268201b9aec1095e74230156f6b/nautobot/core/settings_funcs.py#L28-L33

https://github.com/nautobot/nautobot/blob/dd731f302f363268201b9aec1095e74230156f6b/nautobot/core/templates/inc/nav_menu.html#L823-L827

If would be great if this can potentially be overridden within `nautobot_config.py` via a setting of some sort or just be more relaxed in general. A few potential ideas.

```
from django.conf import settings

@lru_cache(maxsize=5)
def _sso_auth_enabled(auth_backends):
    for backend in auth_backends:
        if backend.startswith(settings["SOCIAL_AUTH_BACKEND_PREFIX"]):
            return True
    return False
```

or

```
@lru_cache(maxsize=5)
def _sso_auth_enabled(auth_backends):
    if len(auth_backends) > 1:
        return True
    return False
```

> This is due to only one **AUTHENTICATION_BACKEND** being defined by default, but not sure it's safe to assume that if it's greater than one, the login redirect should be enabled.

I'm sure there are other ways as well. I'd be willing to implement this once a decision has been made.

### Use Case
We're building a custom authentication backend (that may eventually get ported into Social Auth Core,  but at this point that is too much overhead and I assume that others may need to develop their own custom auth backends that can't be open sourced.

### Database Changes
N/A

### External Dependencies
N/A

**Comment by jathanism** [comment]
Seems like a hybrid of your suggestion and an explicit `ENABLE_SSO = True` setting might be the winning combination here. Thanks @FragmentedPacket!
