### ISSUE TITLE
Dark mode theme

### ISSUE THREAD

**Issue by UnityDG** [nautobot/nautobot#729]
### Environment
* Python version: N/A 
* Nautobot version: N/A

### Proposed Functionality
Dark mode theme for Nautobot

### Use Case
Configurable option per user to enable a dark mode theme
Possibly by matching the system theme to light/dark mode

### Database Changes
Storage option per user to hold theme value

### External Dependencies
N/A

**Comment by itdependsnetworks** [comment]
I know @tbotnz started this at some point

**Comment by jathanism** [comment]
> I know @tbotnz started this at some point

They did! But it wasn't quite complete and we still need some other UI elements to toggle between them and save them in preferences. Need to dig that back up!

@UnityDG Thanks for putting this on the backlog. :)

**Comment by tbotnz** [comment]
@UnityDG you could try this for now https://github.com/tbotnz/nautobot-dark-css Personally i think itd be cool to focus efforts on  reworking the UI into something completley different & modern(er) looking

**Comment by bryanculver** [comment]
Closed via #1554.
