### ISSUE TITLE
JSON Schema "format" property not enforced

### ISSUE THREAD

**Issue by u1735067** [nautobot/nautobot#731]
### Environment
* Python version: 3.9
* Nautobot version: 1.1.0

### Steps to Reproduce
1. Create & save the following config context schema
```json
{
    "additionalProperties": false,
    "properties": {
        "ntp-servers": {
            "items": {
                "format": "ipv4",
                "type": "string"
            },
            "type": "array"
        }
    },
    "type": "object"
}
```
2. Create the following config context, assign the previous schema:
```json
{"ntp-servers": ["hi"]}
```
3. Click save

### Expected Behavior
As per the documentation https://nautobot.readthedocs.io/en/stable/additional-features/config-contexts/#config-context-schemas, the specified `format` should be validated and the save refused

### Observed Behavior
Save is accepted

### Additional informations
https://python-jsonschema.readthedocs.io/en/stable/validate/#validating-formats indicates that by default there's no `format` validation, you can use : 
```py
jsonschema.Draft7Validator(config_context_schema.data_schema, format_checker=jsonschema.draft7_format_checker)
```

**Comment by jathanism** [comment]
Thanks @u1735067 for the report! Apparently we had this one line in there and it dropped out somehow.
