### ISSUE TITLE
Job API returns HTML 404 page instead of JSON error when class_path contains extra slash

### ISSUE THREAD

**Issue by u1735067** [nautobot/nautobot#734]
### Environment
* Python version: 3.9
* Nautobot version: 1.1.0

### Steps to Reproduce
1. Call a Job with class_path `test/test/test/test`, like: 
```
curl -X POST "https://demo.nautobot.com/api/extras/jobs/test%2Ftest%2Ftest%2Ftest/run/" -H  "accept: application/json" -H  "Content-Type: application/json" -H  "X-CSRFToken: 9WLK8XvUr36KSOZw6wNAzkpGCGMSSjN94usPfuYtTvyycWaw4ZldbiPUUZB9bHMx" -d "{}"
```

### Expected Behavior
Nautobot return json:
```json
{
  "detail": "Not found."
}
```

### Observed Behavior
Nautobot return html:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Page Not Found - Nautobot</title>
[..]
```

### Additional informations

Not sure this is really a bug (unmatched route), but shouldn't all `/api/` prefixed paths, existing or not, return response according to the requested content-type?

**Comment by jathanism** [comment]
Ultimately this is a `POST` to what is an invalid API endpoint. We suspect that attempting arbitrary URLs might result in the same error case. Thanks @u1735067!

**Comment by glennmatthews** [comment]
Might be doable by defining a custom `handler404` function in `nautobot/core/urls.py` and/or `nautobot/core/api/urls.py`?
