### ISSUE TITLE
Implement a way to deterministically lookup all secondary class objects for a model

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#747]
### User Story

As P.D. the Plugin Developer…,

I want a way to easily look up tables, filters, and other secondary classes for a model object required for developing Nautobot applications in a declarative and deterministic way,

So that I may develop plugin and customize object views without needing to rely on precise naming standards or tightly coupling extensions to the Nautobot core data models.

I will know this is done when I may easily retrieve all necessary related object classes without having to jump all over the code base or import multiple "magical" helper functions to import objects I need to develop my plugins.

 
### Database Changes (Optional)

None expected.

### External Dependencies (Optional)

Unknown. Not likely.

### Background and Context

For context, I would like to see patterns that are similar to what happens within `nautobot.utilities.util.get_filterset_for_model()` to retrieve filtersets, or `nautobot.utilities.api.get_serializer_for_model()` ultimately be replaced. Each of these performs some dynamic generation of class paths, imports them, and returns the class object to the caller.

A pattern such defining them as class variables as is done on DRF viewsets, would be desirable, for example consider "what if" we were to define these on the model class objects like so (simplified model code for example):

```python
class Device:
    # field definitions

    class Meta:
        serializer_class = DeviceSerializer
        nested_serializer_class = NestedDeviceSerializer
        table_class = DeviceTable
        filterset_class = DeviceFilterSet
        # etc...
```

**Comment by glennmatthews** [comment]
The likely challenge here as I see it is going to be avoiding circular imports and reference loops - if DeviceSerializer references Device, but Device references DeviceSerializer...

**Comment by glennmatthews** [comment]
Some of this is being done as part of #896.

**Comment by glennmatthews** [comment]
Related: #2659.
