### ISSUE TITLE
Make it possible to specify REGION for VLAN_Group scope.

### ISSUE THREAD

**Issue by ksaegusa** [nautobot/nautobot#752]
### User Story
Nelly is using Nautobot in his company which operates multiple DCs.
Vlan100 is used in the L2 networks of SiteA and SiteB.
SiteA has an identical Vlan100 with different roles.
Therefore, we would like to manage the VlanGroups separately, but currently the only way to do this is to create VlanGroups in Site and Global.

I would be happy if I could create a VlanGroup in the range of RegionA, which includes SiteA and SiteB.

### External Dependencies (Optional)
I was inspired by the following Issue.
https://github.com/netbox-community/netbox/issues/5284

In NetBox 2.11.
The scope of a Vlan_group can be [ location,rack,region,site,site group,cluster,cluster group ].

This is very useful and can meet the requirements of customers with multiple sites.

**Comment by glennmatthews** [comment]
Thanks for the request! Just adding a note that this request potentially ties in to some of the more general rework of the location/organizational model that we've been discussing for a while under #230.

**Comment by lampwins** [comment]
Since migrating Regions and Sites to Locations in 2.0, this should now be satisfied.
