### ISSUE TITLE
Nautobot Job Output always begin with \n

### ISSUE THREAD

**Issue by sirtux** [nautobot/nautobot#754]
### Environment
* Python version: 3.9
* Nautobot version: 1.1.0

### Steps to Reproduce
1. Define a job which produces an output, eg. "foo"
2. Run that job
3. Request the job result via API

### Expected Behavior
The data["output"] field contains "foo"

### Observed Behavior
The data["output"] field contains "\nfoo"

### Root cause
https://github.com/nautobot/nautobot/blob/20a93c8337271d287196deb6a8e1882f48ad3044/nautobot/extras/jobs.py#L1008

I have no idea why this is designed this way, but this makes parsing the output of a job complicated. I would like to see this removed, until there is a strong reason for that, or as alternative an option to have Job Outputs unaltered...

**Comment by glennmatthews** [comment]
Thanks for the report! Related to #765, though this is probably addressable in the short term as a bug fix as well.

**Comment by bryanculver** [comment]
Thanks for submitting this @sirtux. This has been captured as a refinement on the Jobs Improvement roadmap (#765).
