### ISSUE TITLE
Log user with django errors

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#755]
### Environment
* Python version: 3.6
* Nautobot version: v1.1.0

### Proposed Functionality
I would like to see which user triggered error in `django` logger.

### Use Case
We have Nautobot running in docker with nginx. Logging is set up to log `django`, `nautobot`, `rq.worker` and `django_auth_ldap` loggers to files. So is nginx. When there are some requests causing errors, I have to go through logs in `django`, find the same request in nginx logs and based on the IP figure out who did it. Today we had 8183 bad requests in `django` logs over 40 minutes, all looking like this:
```
[2021-07-30 00:40:33,956] Bad Request: /api/ipam/ip-addresses/63b38cc7-979d-52c4-b26f-e44dd5f390ca/
```
I got the IP from nginx logs (censored):
```
10.*.*.* - - [30/Jul/2021:00:40:33 +0000] "PATCH /api/ipam/ip-addresses/63b38cc7-979d-52c4-b26f-e44dd5f390ca/ HTTP/1.1" 400 49 "-" "python-requests/2.6.0 CPython/2.7.5 Linux/3.10.0-1160.31.1.el7.x86_64" "10.*.*.*"
```
But the IP is of server which runs multiple scripts. I alerted the team and they called owner of the biggest one (who was on vacation) and we figured out it was different script with different token owner but another person. Than I proceeded to the correct person to solve it.

So if I knew user right away from the `django` log, I would not need to go to nginx and back to Nautobot to figure out the IP and I would not have to disturb a guy on vacation.

Note: I am able to roughly guess user from ldap config (comparing the IP of the login request to the one caused the error), but there does not seem to be anything like that for API usage with tokens. And I don't want to log the token header in nginx for security reasons.

### Database Changes
None

### External Dependencies
hopefully None

**Comment by smk4664** [comment]
@Thetacz I would look into Sentry, they have builtin django support.  Sentry adds details to exceptions that are raised such as the request which I believe contains the user.

**Comment by Thetacz** [comment]
> @Thetacz I would look into Sentry, they have builtin django support. Sentry adds details to exceptions that are raised such as the request which I believe contains the user.

This looks interesting, thanks. I went though their docs and you need to supply a public DNS of sentry.io to submit all the events to, where it gets showed similar to Kibana. This comes with few issues:
1. I'm not comfortable with sending company data to public space, they even discourage sending user names in their own docs ( see [https://docs.sentry.io/platforms/python/guides/django/data-management/sensitive-data/](https://docs.sentry.io/platforms/python/guides/django/data-management/sensitive-data/)) 
2. I don't want to have another service somewhere, we already have private Kibana.
3. I just want to enhance the django logfile with username :)

**Comment by Thetacz** [comment]
Note: It would be nice to log not only errors but any access (INFO) too. This way we would have nice overview who is using API and how often, in which way and what kind of load he creates.

**Comment by itdependsnetworks** [comment]
@jathanism, internally you mentioned that you may be able to `subclass the nautobot.core.api.authentication.TokenAuthentication class that is providing the API token authentication and add logging there. You could then replace the backend w/ your own in settings.REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"]`, could you provide any more insight to the feasibility to that?

**Comment by nniehoff** [comment]
@Thetacz I built a configuration which would add the user to the 4xx and 5xx level requests as you originally reported, check it out in my PR https://github.com/nniehoff/nautobot/blob/nn_logging_example/examples/logging/advanced_requests.md as you mentioned we don't log any 2xx level requests.  This is by design of the [django.requests](https://docs.djangoproject.com/en/3.2/topics/logging/#django-request) logging.  At least this gets us part of the way there.

**Comment by jathanism** [comment]
> > @Thetacz I would look into Sentry, they have builtin django support. Sentry adds details to exceptions that are raised such as the request which I believe contains the user.
> 
> This looks interesting, thanks. I went though their docs and you need to supply a public DNS of sentry.io to submit all the events to, where it gets showed similar to Kibana. This comes with few issues:
> 
> 1. I'm not comfortable with sending company data to public space, they even discourage sending user names in their own docs ( see https://docs.sentry.io/platforms/python/guides/django/data-management/sensitive-data/)
> 2. I don't want to have another service somewhere, we already have private Kibana.
> 3. I just want to enhance the django logfile with username :)

Sentry is actually a great suggestion. They also have an on-premise offering that you can self-host, but not without its operational overhead.

**Comment by jathanism** [comment]
> @jathanism, internally you mentioned that you may be able to `subclass the nautobot.core.api.authentication.TokenAuthentication class that is providing the API token authentication and add logging there. You could then replace the backend w/ your own in settings.REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"]`, could you provide any more insight to the feasibility to that?

I suppose I should have asked about the context! While this would afford logging of every user who is authenticating, it might be decoupled from the requests. I think the logging example provided by @nniehoff [that adds an optional `username` field that can be used in log formatters](https://github.com/nautobot/nautobot/pull/771/files#diff-4d9157df0189fb13782ddbd6455f016325358df5af57dec8957b2410aa870097) may actually be the best case here.
