### ISSUE TITLE
Feature Request: Support MSSQL Backend

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#796]
### Environment
* Python version: 3.x
* Nautobot version: 1.1.x

### Proposed Functionality

Would like to see Nautobot support a MSSQL back end for a database technology

### Use Case

Enterprise wide database storage technology is MSSQL. This would allow organizations that have a MSSQL backend enterprise offering to use this database rather than an application specific DB.

### Database Changes

DB Backend

### External Dependencies

Python library to support MSSQL. In brief research there have been at least 3 different libraries that line up with Django MSSQL backends. Each time a new fork from the previous defacto library.

**Comment by jathanism** [comment]
Good news, there is an officially MSSQL backend plugin for Django! See: https://github.com/microsoft/mssql-django

Bad news: It's still not going to be that simple. I'll detail my analysis on this below.

## Limitations 
> These were copied from the README on `mssql-django`

The following features are currently not fully supported:
- Altering a model field from or to `AutoField` at migration
- Django annotate functions have floating point arithmetic problems in some cases
- Annotate function with `exists`
- Exists function in `order_by`
- Righthand power and arithmetic with datatimes
- Timezones, timedeltas not fully supported
- `bulk_update` multiple field to null
- Rename field/model with foreign key constraint
- Database level constraints
- Math degrees power or radians
- Bit-shift operators
- Filtered index
- Date extract function
- Hashing functions
- JSONField lookups have limitations, more details here (see below)

### JSONField limitations
> Also copied from the README

JSON Example:

```python
# NullableJSONModel
        values = [
            {'a': 'b', 'c': 14},
            {
                'a': 'b',
                'c': 14,
                'd': None,
                'e': '"quoted"',
            },
            {'x': 'y'},
        ]
```

- Quoted strings are NOT supported, like `{'e': '"quoted"'}`. The value will be saved, but lookups may not work as expected.
- `isnull` lookup, if set to `True`, it will return a QuerySet for keys that are not exist and keys that have value `None(null)`.
- `has_key` lookup check the existence of a specific key. If the value of this key is null it will return an empty QuerySet.
- `exact` lookup does NOT support `value = None`, `NullableJSONModel.objects.filter(value__d=None)` will return an empty `QuerySet`.

```python
>>> NullableJSONModel.objects.filter(value__a__isnull=True).values()
<QuerySet [{'id': 3, 'value': {'x': 'y'}, 'value_custom': None}]>

>>> NullableJSONModel.objects.filter(value__a__isnull=False).values()
<QuerySet [{'id': 1, 'value': {'a': 'b', 'c': 14}, 'value_custom': None}, {'id': 2, 'value': {'a': 'b', 'c': 14, 'd': None, 'e': '"quoted"'}, 'value_custom': None}]>

>>> NullableJSONModel.objects.filter(value__d__isnull=False).values()
<QuerySet []>

>>> NullableJSONModel.objects.filter(value__d__isnull=True).values()
<QuerySet [{'id': 1, 'value': {'a': 'b', 'c': 14}, 'value_custom': None}, {'id': 2, 'value': {'a': 'b', 'c': 14, 'd': None, 'e': '"quoted"'}, 'value_custom': None}, {'id': 3, 'value': {'x': 'y'}, 'value_custom': None}]>

>>> NullableJSONModel.objects.filter(value__has_key='d')
<QuerySet []>
```

## Concerns

I expect that these two query functions will need to be accounted for explicitly:

- [`CollateAsChar`](https://github.com/nautobot/nautobot/blob/develop/nautobot/utilities/query_functions.py#L8-L29)
- [`JSONBAgg`](https://github.com/nautobot/nautobot/blob/develop/nautobot/utilities/query_functions.py#L32-L55)

The only other area of concern is making sure that the IPAM network object fields (on `Aggregate`, `IPAddress`, and `Prefix` objects), is making sure that `VARBINARY` field type works as expected in MSSQL, and also that the custom annotation we have on `Prefix`  (specifically `Prefix.objects.annotate_tree` is a complicated query using nested annotations and sub-queries.) We can likely trust the unit tests on these objects, but some extra attention to making sure the objects work in all user-facing web UI views, especially on `Prefix` objects would be wise.

## Assessment

Let's give it a proper spike to scope it out and see if we could get it working with minimal effort. I'd say no more than 1 day of work for that.

If it were me:

- I'd fire up an MSSQL server, point Nautobot to it, 
- Run the test suite just to see what works and what doesn't.
- And then put emphasis on the level of effort based on test results and how easily the primary concerns above can be addressed 

It could take days to weeks based on that output. If I were forced to guess I'd say a **minimum of one sprint for one person, which is about two engineering weeks (or 80 engineering hours) on the low side.** 

This isn't counting the complexity for bringing this home, such as other things such as documentation, spinning up a server running MSSQL that can be used for testing, CI/CD integration of MSSQL testing, and anything else I haven't covered.

**Comment by jvanderaa** [comment]
From the assessment done:

```
Update pyproject.toml with new dependencies: 

Mssql-django backend, supported by Microsoft

OBCD Driver to use?

 By default is “ODBC Driver 17 for SQL Server”, install it

Variables

ACCEPT_EULA

MSSQL_SA_PASSWORD

MSSQL_PID: $$$$$$$$$$$$$$ or “Developer”

MSSQL_TCP_PORT: default is 1433

Update Django settings

MSSQL Django limitations: 

JSONField lookups limitations

Update custom customization maps:

Class CollateAsChar.as_sql()

"postgresql": '"C"',

"mysql": "utf8mb4_bin",

“Mssql”: choose the appropriate collation

class JSONBAgg.as_sql()

"postgresql": "JSONB_AGG"

"mysql": "JSON_ARRAYAGG",

“Mssql”: there are no functions like JSON_ARRAYAGG, so this would have to be overcome so find a custom alternative

TestVarbinaryIPField

"postgresql": "bytea",

"mysql": "varbinary(16)",

“Mssql”: I believe that it supports the varbinary, but not sure if there is something to do on the code to use it, here it is only testing.
```

**Comment by jathanism** [comment]
As a follow-up, for reference here are the documented JSON functions for MSSQL: https://docs.microsoft.com/en-us/sql/relational-databases/json/validate-query-and-change-json-data-with-built-in-functions-sql-server?view=sql-server-ver15

**Comment by glennmatthews** [comment]
The core team discussed this and we'll take this on for at least some initial investigation in the near future in order to make a decision about its feasibility.
