### ISSUE TITLE
Device Rackposition not changeable

### ISSUE THREAD

**Issue by mkrsn** [nautobot/nautobot#81]
### Environment
* Python version: Python 3.8.5
* Nautobot version: v1.0.0b1

### Steps to Reproduce
1. Go to Devices and click on a existing Device
2. Click Edit Button
3. Scroll Down to "Location" and Open "Position"

### Expected Behavior
When opening the List it should display the Units of the assigned Rack.

### Observed Behavior
It just shows: "The results could not be loaded"

![Screenshot_20210303_092251](https://user-images.githubusercontent.com/10330231/109775682-1cce6800-7c02-11eb-8b61-d9113d2ce20e.png)

It is only possible to assigne a Device to a Rack position while creating it. After the Device was created it's not possible to edit the position anymore. I've cross checked it with https://demo.nautobot.com/ - same Behavior.

**Comment by jathanism** [comment]
Confirmed! Thanks for the bug report.

**Comment by glennmatthews** [comment]
https://github.com/nautobot/nautobot/blob/develop/nautobot/dcim/api/serializers.py#L346

`exclude` is an IntegerField but needs to be changed to a UUIDField now that we have UUID PKs instead of integer PKs.

**Comment by jathanism** [comment]
We should also add a regression test for this. Seems to me more detailed filter testing should have caught this.

**Comment by jathanism** [comment]
Turns out it's not a filter but a query serializer that is being used as if it were a filter by `drf-yasg`.

**Comment by jathanism** [comment]
Thanks @mkrsn ! :)

**Comment by mkrsn** [comment]
Thanks for fixing / Nautobot! :)
