### ISSUE TITLE
Extend required settings documentation for configuring Celery to use Redis Sentinel

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#814]
### Proposed Changes

We need to add a section to the **Required Settings > Redis Settings** section of the documentation to instruct the reader how to configure Celery to use Redis Sentinel.

It appears that you can easily use it [per the Celery docs](https://docs.celeryproject.org/en/stable/getting-started/backends-and-brokers/redis.html?highlight=redis#configuration), e.g. adding this to `nautobot_config.py:

```python
CELERY_BROKER_URL = 'sentinel://localhost:26379;sentinel://localhost:26380;sentinel://localhost:26381'
CELERY_BROKER_TRANSPORT_OPTIONS = { 'master_name': "cluster1" }
```

We'll need to test this setup in a sandbox to assert the recommened patterns.

### Justification

There is already a section on [configuring RQ to use Redis Sentinel](https://nautobot.readthedocs.io/en/stable/configuration/required-settings/#using-redis-sentinel), so we just need to give the same treatment to Celery.

### Acceptance Criteria

- [x] Task Queuing under "Required Settings > Redis Settings" needs to be updated to mention the configurations needed for Celery
- [ ] Caching docs updated to link to required celery settings (caching doesn't require celery but requires it to be configured)

**Comment by bryanculver** [comment]
Closed with #1532
