### ISSUE TITLE
Remove celery worker "-B" option from development/docker-compose.yml

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#825]
### Proposed Changes

Remove the celery worker "-B" option from `development/docker-compose.yml`:

```diff
  celery_worker:
    image: "networktocode/nautobot-dev-py${PYTHON_VER}:local"
-   entrypoint: "nautobot-server celery worker -B -l INFO"
+   entrypoint: "nautobot-server celery worker -l INFO"
```

### Justification

The `-B` option enables a worker to run its own Celery Beat integration. This is unneeded and unused in Nautobot 1.1.x, and is [not generally recommended](https://docs.celeryproject.org/en/stable/userguide/periodic-tasks.html#starting-the-scheduler) in any case. (It is already being changed for Nautobot 1.2.x as part of #805.)

**Comment by RhnSharma** [comment]
I would like to take this one.
