### ISSUE TITLE
Using OrganizationalModel or PrimaryModel shouldn't require also specifying @extras_features(custom_fields, relationships)

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#826]
### Proposed Changes

We should investigate the feasibility and desirability of removing the use of and need for `@extras_features("custom_fields", "relationships")` on models derived from `OrganizationalModel` or `PrimaryModel` (or more precisely, all models using the `CustomFieldModel` and/or `RelationshipModel` mixins).

- Models inheriting from `CustomFieldModel` should automatically support all custom-field-related functionality without requiring an additional decorator
- Models inheriting from `RelationshipModel` should automatically support all relationship-related functionality without requiring an additional decorator

This won't forbid the use of `@extra_features` for custom fields and relationships, but just not depend on them to advertise support for these features. Instead inspect inheritance or properties to determine functionality

### Justification

Code simplification, removing "gotchas".

**Comment by bryanculver** [comment]
Related: #1505

**Comment by bryanculver** [comment]
Closed via #3360
