### ISSUE TITLE
nautobot-server post_upgrade Support Loading of EnvironmentFile

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#829]
### Environment
* Python version: 3.9
* Nautobot version: 1.1.2

### Proposed Functionality

When executing `nautobot-server post_upgrade` where the database connections are all controlled by vars in an .env file, get the error unable to connect to the DB due to `no password supplied`. This makes sense. The work around is to have to load the environment files when doing an upgrade. I believe Python has a method to load env files that could be used. It would be nice to have an option to load the env file added to the nautobot-server command.

### Use Case

This is currently done by a script as you cannot source .env files (as I understand). 

```
if [ -f .env ]; then export $(cat .env | sed 's/#.*//g' | xargs); fi
```

### Database Changes

None

### External Dependencies

Python dotenv package

**Comment by bryanculver** [comment]
@jvanderaa Do you recall the reason behind using the `.env`?

**Comment by jvanderaa** [comment]
Part of the best practices for deploying apps. @bryanculver 

The .env file is defined in the service definition. But that is not loaded when just running `nautobot-server post_upgrade` as the user.

**Comment by lampwins** [comment]
Sorry, not clear what the specific ask to core is here?

**Comment by jvanderaa** [comment]
I'd like to be able to run `nautobot-server post_upgrade --env_file .env` to be able to access the database passwords and such that are in the environment.

The work around at the moment is to have to first go into the Nautobot user, then use a bash command line to load all of the data from the .env file.

**Comment by jvanderaa** [comment]
I think we can close this out if we would like. This is a method to have the user account load the environment variables itself. https://josh-v.com/nautobot-environment-file/#loading-the-environment-variables-on-login-of-nautobot
