### ISSUE TITLE
Plugins should use Post Upgrade

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot#832]
### Proposed Functionality

Plugins should use `nautobot-server post_upgrade` after installing plugins instead of `nautobot-server migrate` and `nautobot-server collectstatic`.

### Use Case

Ease of installing plugins, and also covers bases of clearing cache, running migrations whether they think database changes have happened or not.

### Database Changes

N/A

### External Dependencies

N/A

**Comment by jmcgill298** [comment]
Does this command accept an App to limit the scope of what gets executed?

**Comment by smk4664** [comment]
Not currently, it targets all.  But you can turn off some of the commands.

https://nautobot.readthedocs.io/en/stable/administration/nautobot-server/#post_upgrade

**Comment by jmcgill298** [comment]
I fear that this can cause unexpected and irreversible side effects, especially with how Poetry handles dependencies. I know that I have accidently caused Nautobot to upgrade by installing/upgrading Plugins. If it automatically ran migrations, then it would have been very difficult to rollback to the desired Nautobot version.

**Comment by smk4664** [comment]
Our existing guide just says to run `nautobot-server migrate`.  Migrations are reversible (or should be).  I will put in a PR for adding an app input to post_upgrade.
