### ISSUE TITLE
Job logs are lost in post_run when an Exception is raised

### ISSUE THREAD

**Issue by jmcgill298** [nautobot/nautobot#835]
### Environment
* Python version: 3.8
* Nautobot version: 1.1.2

### Steps to Reproduce
1. Create a Job with a post_run() method that uses log_info() and then raises an Exception
2. Execute Job and view results

### Expected Behavior
I expected log messages to persist

### Observed Behavior
log messages do not persist if an unexpected Exception is raised

**Comment by bryanculver** [comment]
Closing as unreproducible at the moment.

**Comment by jmcgill298** [comment]
@bryanculver was it reproduced in 1.1.2 and not in a newer version?

**Comment by timizuoebideri1** [comment]
@jmcgill298 Yes, I was able to reproduce the error in v1.1.2 but not in newer version
