### ISSUE TITLE
Autonomous System Number management

### ISSUE THREAD

**Issue by achard** [nautobot/nautobot#849]
### Environment
* Python version: 3.8
* Nautobot version: 1.1.2

### Proposed Functionality
Ability to manage an inventory of AS Numbers as part of the IPAM module. These could be either public or private ASN's.
They could be either 16 or 32 bit ASN's. And they could be expressed as either a single number or in asdot (eg 46073.5000) form.

### Use Case
Enhanced management of BGP configuration. Currently an AS number can be assigned to a site, but there is no central view of what AS numbers have been assigned and which ones are available to be assigned. This could be extended to having RIRs responsible for ranges of AS numbers such that ranges can be delegated to third parties. For public AS numbers, which RIR is responsible can be looked up ( https://www.iana.org/assignments/as-numbers/as-numbers.xhtml )

Having a 'Give me an available private AS number' type button on the site creation/edit page would be great too.

### Database Changes
I imagine AS Numbers would become their own model and the site ASN field would become a foreign key.
Fields:
Allocating RIR (Foreign Key to RIR or a property inferred from ranges the RIR is responsible for)
Description/comment (Free text)
AS Value (32bit integer)

Maybe it doesn't need its own model though, just some sort of interface to see used and available AS Numbers from the existing site field? If you go this way the Allocating RIR can be inferred from the AS range that each RIR is responsible for. For public ASN's a reference to the actual public record (APNIC/ARIN/RIPE etc) would be good too. Or maybe having them associated to a RIR makes this all too complex :)

I'm open to suggestions/discussion on this point, I do think a separate model is a cleaner solution despite the additional work it requires.

### External Dependencies
None

**Comment by achard** [comment]
Having read the contribution guidelines, I see this might be more suited to a discussion than a feature request.. let me know if I should move it there!

**Comment by glennmatthews** [comment]
Thank you for the feature request, and for the detailed use cases and requirements!

**Comment by glennmatthews** [comment]
We actually have a BGP data models plugin targeted for open-source release in the near future, and at this time I believe the BGP ASN model as implemented in that plugin is the best way to move forward with this feature. Once that plugin is released, please give it a try and if it doesn't meet all your requirements, we can decide at that time whether to make enhancements to the plugin or whether to revisit the possibility of moving the ASN model into core.
