### ISSUE TITLE
Allow Import/Export of CircuitTerminations

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#851]
### User Story

As Austin the Network Automation Engineer,

I regularly take partial exports from our production Nautobot instance to import them in a separate local development instance.  There are reasons for which I can't take a full database dump from production at this time, for example, I'm working on integrating a new feature in testing and I have quite a bit of data which is new and doesn't exist in production yet.  I need to be able to export/import CircuitTermination data somehow into Nautobot.  A better approach than providing list views for the CircuitTermination model might be to have a writeable graphql endpoint to which I can export/import any data I would like ;).  

I know this is done when:

* I can export CircuitTermination data (any format is acceptable, even if the export is json from a GraphQL query)
* I can import the exported data from above into Nautobot somehow

 
### Database Changes (Optional)

None

### External Dependencies (Optional)

None

### Requires

- [x] #2276

**Comment by glennmatthews** [comment]
Implemented for 2.0.
