### ISSUE TITLE
Custom branding

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#859]
### Environment
* Python version: 3.9
* Nautobot version: 1.1.2

### Proposed Functionality
As Patti the Platform Admin, I want to be able to brand Nautobot with a custom logo and name so that it is more familiar and approachable inside my large organization.

### Use Case
In a large organization that has entrenched automation efforts, I want to introduce Nautobot as a key component of my strategy, but because of the landscape of the environment, Nautobot must "fit in" with my existing platform which has internal branding and marketing. I want as a minimum, to be able to change the nautobot logo but it would be awesome to be able to replace all references to the name "Nautobot" with my own name. I would be fine with even "<My Name> powered by Nautobot."

This is not about trying to rebrand Nautobot and call it my own, it is more about ensuring Nautobot is well received and accepted by my organization by having it fit into an existing ecosystem.

### Database Changes
Likely none, but it may relate to the ability to store certain application settings in the DB.

### External Dependencies
N/A, should be solvable internally.

**Comment by glennmatthews** [comment]
>  it would be awesome to be able to replace all references to the name "Nautobot" with my own name

So this would include things like the title of browser tabs and such.

**Comment by glennmatthews** [comment]
As mentioned above, this may have some interdependency with #370 if configuring this dynamically via the UI is a hard requirement.

**Comment by lampwins** [comment]
While #370 would be cool, it is not a requirement for me here. I was planning on just a setting that points to a file in `MEDIA_ROOT`

**Comment by jedelman8** [comment]
@lampwins since you self-assigned this one, we can target this for 1.3, but if you happen to get it done in the next few weeks, we can pull it in 1.2.

**Comment by lampwins** [comment]
Closed in #924
