### ISSUE TITLE
Document that adding device component to device type does not modify existing device instances

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#860]
### Environment
* Python version: 3.6.9
* Nautobot version: v1.1.1

When I add new component to existing device type, this is not applied to the existing instances (devices) of this device type.

Since device represent different models and devices of this type are always same, it does not make sense to me for this change to not propagate even though docs say otherwise. So from my point it is a bug, but you can treat is as feature request if you have different opinion on the subject. Usage for this is when user creates new type and does not have complete information of it and creates devices from that type (lots of them), adding more components to the existing device is long manual labor, which could be removed by this change. Creating this now because we plan to import over 5k devices and we don't have complete information of the types, so the ability to specify this later would be much helpful.

### Steps to Reproduce
1. Create device type
2. Create device instance of this type
3. Add component to the device type
4. Check created device instance

### Expected Behavior
New component present

### Observed Behavior
Component not present

**Comment by jathanism** [comment]
During review, we agree with @lampwins that this predominantly already solved with existing functionality and could be solved with better documentation, guides, and examples. 

For example: "I've made changes to my device type definitions, how do I bulk update my devices to match it?"

**Comment by smk4664** [comment]
Someone pointed me to a plugin that identifies drift between templates and interfaces. This might be a good candidate for a plugin in Nautobot, but perhaps one that checks everything from the Device Type.

**Comment by glennmatthews** [comment]
Could potentially draw some inspiration from https://github.com/netbox-community/netbox/wiki/Frequently-Asked-Questions#why-arent-device-type-component-modifications-retroactive
