### ISSUE TITLE
Mass edit of device site and rack

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#861]
### Environment
* Python version: 3.6.8
* Nautobot version: v1.1.1

### Proposed Functionality
Allow changing site and rack when mass editing devices.

### Use Case
We quite often move more devices (example: 20 at once) between sites/racks and doing these changes one-by-one is tedious. Having the ability to just select them all and do this change in UI at once would be very helpful since people doing these migrations are not really capable of using API at all.

### Database Changes
None

### External Dependencies
None

**Comment by jvanderaa** [comment]
Can assign to myself and Josh S

**Comment by jedelman8** [comment]
what's your timing on this?  If it is in the next 2-3 weeks, it'll make 1.2, otherwise, 1.3.  Can you let us know? :)

**Comment by jvanderaa** [comment]
@jedelman8 today. I have the PR in. I may just need to do a small working session on the tests.
