### ISSUE TITLE
Ability to hide a job in the UI

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#863]
### Environment
* Python version: 3.9
* Nautobot version: 1.1.2

### Proposed Functionality
As Austin the Network Automation Engineer, I want to hide a special system integration or JobHook job from the web UI so that the UI is not cluttered by jobs no human should ever execute manually.

### Use Case
Since Nautobot offers a generic network automation jobs execution framework, I have defined several technical jobs which interact with and are invoked by external systems. Such jobs are not meant to be executed by a human. Additionally, with the advent of JobHooks in #862, these jobs likely do not make sense to expose to end users for execution, and thus having them exposed in the UI at all is extraneous. It might also make sense for SSoT jobs to not show up in the UI alongside regular jobs. I imagine that pattern will continue to show up over time.

The point is, the jobs framework is generic in nature, but certain types of jobs do not make sense to view and execute within the web UI, and thus we should have the ability to hide them.

### Database Changes
Not likely. I see this being implemented as a meta attribute on the Job class.

### External Dependencies
There should be no external dependencies here.

**Comment by glennmatthews** [comment]
@jvanderaa I think that falls within the general requirements listed in #765, specifically:

-  Permission to run job based either on "`run_job`" or "`run_job_<group>`" or "`run_job_<name>`"

So I'd rather keep it as distinct from this narrower feature request.

**Comment by bryanculver** [comment]
Merged into `next`.
