### ISSUE TITLE
Inconsistent job result webpage

### ISSUE THREAD

**Issue by FloLaco** [nautobot/nautobot#864]
### Environment
* Python version: 3.6.14
* Nautobot version: 1.1.3b1

### Steps to Reproduce
1. Launch a job, and wait the automatic redirection when the job is finished
2. You can see multiples tabs : `Log`, `Output`, `Source`. Note the uri : `/extras/jobs/results/c7ad04f1-abcc-400a-abe8-e05eebe3188e/`
3.  Now, go in the `Job Results` menu, and select any job (by clicking on the date). You don't have the tabs anymore, so you can't access to the job output. Note the uri : `/extras/job-results/c7ad04f1-abcc-400a-abe8-e05eebe3188e/`

### Expected Behavior
![image](https://user-images.githubusercontent.com/1486562/131125278-9c5b4f8a-5d63-4b46-9df8-1f201826531a.png)

### Observed Behavior
![image](https://user-images.githubusercontent.com/1486562/131125214-5bb67286-99bd-410a-8803-909bf4e5f462.png)

**Comment by glennmatthews** [comment]
Fixed by #1030.
