### ISSUE TITLE
Possible bug in ipam_prefixes_available-ips_create

### ISSUE THREAD

**Issue by retnuh** [nautobot/nautobot#867]
### Environment
* Python version: Irrelevant
* Nautobot version: 1.1.2

### Observed Behavior
In `nautobot/ipam/api/views.py`, line 245, the IP address is given the prefix length of the parent prefix.  This seems odd to me, shouldn't it just be a `/32`?

**Comment by achard** [comment]
Consider it like the address you assign to an interface.. you assign both an IP address and a subnet mask.
You are right that you're only assigning a /32, but the prefix mask length is significant as well so I think the existing behaviour is correct.

In terms of consuming the data, it saves you from doing an additional lookup on the prefix to find the mask length as well.

**Comment by jvanderaa** [comment]
It should be whatever is being configured on a device. When a server or network is given an IP address it includes the mask as well. So that mask should match, which should be the prefix.

**Comment by retnuh** [comment]
Okay thanks for the clarification!
