### ISSUE TITLE
Scope tags to content types

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#872]
### Environment
* Python version: 3.9
* Nautobot version: 1.1.2

### Proposed Functionality
As Austin the Network Automation Engineer, I want to be able to scope a tag to a specific content type or set of content types, so that the given tag can only be used for the assigned content type(s), which will allow me to better namespace the use of my tags for various needs.

### Use Case
Today the namespace for tags is global to all content types (models) which means any tag that is created can be assigned to any object across any model that supports tags. At scale, this is burdensome as one typically has clusters of tags related to different use cases, like tags that are relevant to network devices, tags for servers, tags for subnets, tags for sites, etc. Often there is little overlap in use case between these clusters which in the best case means it is annoying to have to sift through a ton of unrelated tags when trying to find the one I need in a given instance. In the worst case, I might have a naming collision between tag use cases which can result in users assigning the incorrect tags for a given use case. For example, I might have a tag "provisioning" that is meant for devices that are being deployed and I might have a tag "allocating" that is meant for use with IPAM resources. Semantically a user could easily be confused by these two use cases and pick the wrong tag. This could be solved if tags can be scoped to content types in much the same way that statuses are today.

### Database Changes
This will require new associations to content types in the same way statuses are today. It should be noted though that while we use the taggit library under the hood, we already implement a custom tag model. With this change, it might be worth ditching taggit altogether as with such a substantial change there might no longer be any benefit to taggit. We should explore this further.

### External Dependencies
None, but as noted, we might be able to drop the use of taggit.

### Acceptance Criteria

- [ ] Similar to the `status` pattern already implemented, a tag constrained to a particular content type cannot be applied to other content types
- [ ] Similar to the `status` pattern, a tag could be constrained to multiple content types
- [ ] For migration, tags would by default be available to all content types
- [ ] Enforcement should be done both in the UI & API
- [ ] Should be able to filter tags by content types

**Comment by glennmatthews** [comment]
So, regarding tags versus custom fields:

| Tag | Custom Field |
| --- | --- |
| ✅ Tags have associated colors for easier recognition | :x: No associated color (but see #858 for select/multiselect fields) |
| ✅ Boolean value (associated with a given object, or not) | ✅ Various value types, including boolean and select/multiselect |
| ✅ Applies to PrimaryModel classes | ✅ Applies to PrimaryModel classes |
| :x: Does NOT apply to OrganizationalModel classes | ✅ Applies to OrganizationalModel classes |
| :x: Not currently scopable to specific content-types (this issue) | ✅ Scopable to specific content-types |
| :x: Not currently scopable to a subset of a content-type¹ | :x: Not currently scopable to a subset of a content-type (but see #889)¹ |
| ✅ Any number of tags can be applied to an object | ✅ Any number of custom fields can be applied to an object, and for multi-select fields any number of selections can be made |
| ✅ Creation/deletion is atomic, only touching Tag and TaggedItem tables | :x: Creation/deletion requires a background task to update all impacted objects |
| ✅ Creation is near-instantaneous | :x: Creation time scales with number of affected objects |
| ✅ Deletion performance scales with number of objects tagged | :x: Deletion performance scales with number of affected objects, whether having a value for that field or not |
| ✅ Can be used to filter list views | ✅ Can be used to filter list views |
| ✅ Can be used to filter REST API | ✅ Can be used to filter REST API |
| ✅ Can be used as a GraphQL filter | ✅ Can be used as a GraphQL filter |
| ✅ Various UI components allow the user to quickly see how many objects are tagged with a given tag | :x: No corresponding UI |
| :x: Not included in global search | :x: Not included in global search |

¹ Scoping to subsets of content-types would likely be best accomplished via #896.

From a user standpoint, there's not a lot of difference between Tags and a dedicated "tags" multi-select custom field with options corresponding to all available tags. If we decided to get rid of Tags as a separate field and data model, a migration to custom fields would be quite straightforward to write. The biggest concern I have about such a proposal is the performance/background-task aspect of Custom Fields.

**Comment by lampwins** [comment]
Thanks, Glenn for the analysis. I think one major thing which still stands out to me is that tags and statuses themselves can have custom fields (and other features), which means they have much more data dimensionality than simply a text label which is gained through the sole use of a (multi)select custom field on an object.

To me, this alone is compelling enough to _not_ collapse down to one feature.

**Comment by bryanculver** [comment]
Closed with #1505
