### ISSUE TITLE
Make a relationship required

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#873]
### Environment
* Python version: 3.9
* Nautobot version: 1.1.2

### Proposed Functionality
As Austin the Network Automation Engineer, I want to specify that a relationship is required so that my users are forced to provide a value for the relationship when creating or modifying data.

### Use Case
In many use cases where I am extending the data model with relationships, I need to enforce the integrity of my data by ensuring that a relationship is actually formed between objects. For instance, I might have a relationship defined between racks and vlans to designate the management vlan for that rack. I want to enforce that a rack _always_ has a management vlan and thus I want to ensure that users are required to always provide a value for this relationship when creating or modifying a rack.

This is straightforward for 1-1 and 1-many relationships and implies the constraint should be directional. Many-many is more interesting and my thought is that marking a many-many relationship as required would force the user to provide at least one value for the relationship. That is debatable I suppose though.

### Database Changes
Relationships will need the ability to mark a relation as required.

### External Dependencies
None

### TODO

- Require (being defined as "Not NULL or empty"):
    - Neither side required
    - Source side required
    - Destination side required

### Out of Scope

- Bi-directional requirement
- Non-Deletion Enforcement

**Comment by glennmatthews** [comment]
Points to clarify:

- How to handle "many" relationship side in general
- How to handle existing data when creating a required relationship (or changing a previously non-required relationship to be required henceforth)

**Comment by jedelman8** [comment]
@lampwins can you provide a little more feedback with what you were thinking?

**Comment by lampwins** [comment]
> How to handle "many" relationship side in general

I invasion being able to mark either side (or both) as required. This helps with the common case in which one side is hidden. This means I could mark the many side as not required. In the case where I do mark the many side as required, I would infer that mean I must specify at least one object for the relationship.

> How to handle existing data when creating a required relationship (or changing a previously non-required relationship to be required henceforth)

This should be handled the same way custom fields are today. The "required" constraint is only enforced on object creation/edit. There is a UI tip on objects that have a null value to say that a required value is missing.

**Comment by jathanism** [comment]
The use-cases and implementation for 1-to-1/many is pretty straightforward.

It would be good to have more concrete use-case examples for required many-to-many relationships before we try to tackle that.

**Comment by bryanculver** [comment]
> The use-cases and implementation for 1-to-1/many is pretty straightforward.
> 
> It would be good to have more concrete use-case examples for required many-to-many relationships before we try to tackle that.

@lampwins Can we get this use case example or constrain to just supporting 1-to-1 and 1-to-many relationships for now?

**Comment by lampwins** [comment]
It can be as simple as "1 or more, but never zero." For example, I have a many-to-many relationship from device to a classification model, which tells me what services or functions the device services. It must have at least one classification but could have many.

**Comment by bryanculver** [comment]
Symmetric relationships nor bi-direction requirements can be supported because of the "The Chicken and the Egg Problem" -@gsnider2195

Therefor I think the way we implement this is you have the choice of either:
- Neither side required
- Source side required
- Destination side required

"Required" being defined as "Not NULL or empty"

Should this enforce non-deletion (Ala models.protect)?

**Comment by lampwins** [comment]
That's all fine by me. In most cases, I see only one side being made required.

> Should this enforce non-deletion (Ala models.protect)?

I say no, not at this time. Sounds complicated and non-performant.

**Comment by bryanculver** [comment]
Core functionality implemented via #2612. Bulk being addressed via #2744
