### ISSUE TITLE
Replace Gunicorn w/ uWSGI

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#88]
### Proposed Changes

Self-explanatory

### Justification

uWSGI is better for the common case and more stable. Our recommendation is to use uWSGi over Gunicorn in production, so we want to revise the requirements and the documentation to support this.

**Comment by glennmatthews** [comment]
Note that `pyproject.toml` currently lists `gunicorn` as a hard dependency, so we'd want to remove that as well.

**Comment by jathanism** [comment]
Yes, thanks. We should decide as to whether we want to include uWSGI as a hard dependency (I would argue not) or whether to include it as another extras (`pip3 install nautobot[wsgi]` or something).

**Comment by itdependsnetworks** [comment]
This is one area where I like supporting optional dependencies. There are many different patterns to install, doesn't make sense to force that on the users.
