### ISSUE TITLE
move Jobs to be top-level item in navbar

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#880]
### Overview

From this epic in  #765 

There continues to be more menu items being created for Jobs and we now have Jobs, Jobs Results, Scheduling, and Approvals.  There may be more in the future as the Jobs feature set continues to expand.  We should take incremental steps in improving the UX of Jobs.

### User Story

As Ozzie the Operator, 
I want to see "Jobs" as a top-level navigation item,
So that I know exactly where I need to go to see all-things Jobs related.

As Mary the Manager,
I want to see "Jobs" as a top-level navigation item,
So that I know my team can more easily understand and view Jobs in a central location that is extremely visible.  This will help the Operators that has a core focus of executing Jobs within the NOC.

I will know this is done when:
* Jobs is top-level item in the navbar

**Comment by glennmatthews** [comment]
Fixed in `next` (1.3.0) by #1191.
