### ISSUE TITLE
improve UX of the main Jobs by adding accordion style interface

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#881]
### Overview

From the epic in #765 and a focus to improve the UI-UX of Jobs, this item is focused on improving the general UI-UX of the main Jobs page.  Once there is 20+ Jobs on a single page, it becomes hard to visualize and digest.  This proposal is to add an "accordion" style interface to view Jobs.  

An example of that can be found here: https://www.networktocode.com/training/private/

I've also seen an implementation that could possibly be used for this from @jvanderaa and @josh5276

### User Story

As Ozzie the Operator, who views and executes A LOT of Jobs, 

I want to streamline the Job experience for myself and my other team members,

So that we can focus and view only the Jobs of a given "category" or "type" (not to be confused with a new feature that allows user-defined categories; this is analogous to the current "sections" that exist on the Jobs page).

I will know this is done when ...

- Each Jobs section can be rolled-up/down using an accordion-like view using an arrow or plus sign
- There is an "easy" button at the top that allows a user to expand all or hide all Jobs 
- There is a setting defined in settings.py?? that allows me to state a default of hide all or show all Jobs.

**Comment by glennmatthews** [comment]
Implemented in `next` (v1.3.0) by #1232.
