### ISSUE TITLE
add Jobs category to more easily visualize Jobs in the UI

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#882]
### Overview

From the epic in #765.

Add a new attribute within `Meta` in a Job definition to allow users to create a Job **category**.

Currently the "section" in the Jobs page is a path/filename.  Here is one example:

![image](https://user-images.githubusercontent.com/6332586/132009528-d13b207f-833b-4d18-9b52-a9a6fd9408bc.png)

It should be permitted to use a user-defined category to better group Jobs together independent of where they are coming from, e.g. local on the filesystem or from different plugins. 

This screenshot shows a Jobs page with a focus on the breadcrumbs:

![image](https://user-images.githubusercontent.com/6332586/132009477-26dde402-aa30-4d15-b298-eb82bb38b761.png)

Instead of 

```
Jobs / Local / devices / Hostname
```

```
Jobs / Plugins / nautobot_circuit_maintenance.handle_notifications.handler / Update Circuit Maintenances`
```

This would allow a user define a category called "circuits" and we could then have the following:

```
Jobs / Circuits / Hostname
```

```
Jobs / Circuits / Update Circuit Maintenances`
```

In order to support backwards compatibility, we could maintain what we currently have when a category isn't defined, or have a "Other" category.

Open question: if there is general thought to maintain the path somewhere in the per-Job view, we can probably still add that under the description. 

### User Story

As Ozzie the Operator, 
I want to more easily find the jobs I need to execute,
So that I can better support my network.

I know this is done when:
- When there is a category attribute I can use in `Meta` that corresponds to a "section" in the UI
- When Jobs from multiple sources can be grouped in a single section, i.e. what we are saying is a new category
- When there is no category defined, it defaults to an "other" group or maintain what we currently have )

**Comment by jathanism** [comment]
Similarly to #883, this may need to rely upon a `Job` model and assignment of categories (e.g. `JobCategory` or something) within the UI. More requirements/discussion needed.

**Comment by jedelman8** [comment]
Why would this need a model?  It's currently automatically creating "sections" based on a path.  Is this possible by parsing `category` instead of a path?

**Comment by jedelman8** [comment]
@glennmatthews @jathanism can we have some discussion on this one? Would love to get this one ready!

**Comment by glennmatthews** [comment]
IIRC one of our initial concerns was whether it makes sense for the job "grouping" to be defined by the job author, or whether it's more logical to allow the groupings to be managed via the Nautobot UI (which would push us more in the direction of having a proper database model representing Jobs). Also whether it's really necessary to have this feature when it's perfectly possible to group multiple jobs into a "grouping" by simply defining them all in a single source file?

I do also think that in the absence of defined "categories" it makes sense to continue to group jobs as they are presently (by source file or module) - but then the question becomes how we integrate things when some (even just one) job(s) define a category but the majority of jobs do not - does adding a category to a single job mean that all the other jobs get automatically re-sorted into an "other" category, losing their previous structure/sorting?

**Comment by racsoce** [comment]
Hello, I came across one way to do this as follows:

background:
by the nautobot docs you can define a `name` in the Module and in the Class of your Job:

![image](https://user-images.githubusercontent.com/24923565/136040878-f66b4590-0af2-44e3-8662-87eb4071c647.png)

A tip from @dgarros is to setup the `__init__.py` as is done for Job Plugins like:
```
"""List all jobs defined in his plugin."""
from .create_pop import CreatePop
from .import_device_type import ImportDeviceType

jobs = (
    CreatePop,
    ImportDeviceType,
 )

__all__ = ("jobs",)
```

### The solution for my Job Groups:
1.- Folder structure in my `local` Jobs:
```
root@xx:/opt/nautobot/jobs# tree NetEng\ compliance/
NetEng\ compliance/
|-- __init__.py
|-- access_list_header.py
`-- object_group.py

0 directories, 3 files
```
2.- My `__init__.py`
```
"""List my jobs in this folder category"""
from .access_list_header import AccessListJob
from .object_group import ObjectGroupJob

jobs = (AccessListJob,
        ObjectGroupJob)

__all__ = ("jobs",)
```
3.- Use the same `name` variable in your Jobs Module, my 2 files for my 2 jobs, just after the imports:

![image](https://user-images.githubusercontent.com/24923565/136043526-0c75f1f5-3f85-4be8-92f6-756133839a05.png)

And that will group the 2 files on same Category defined by your "Folder" name:

![image](https://user-images.githubusercontent.com/24923565/136043810-bff2efc1-ba43-464c-bb32-88733d88a989.png)

Hope this helps.
