### ISSUE TITLE
add filter search and labels to Jobs

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#883]
### Overview

From the epic in #765.

Add a new attribute within Meta in a Job definition to allow users to create a Job labels category and add search filter to Jobs.  One or more labels could be applied to a Job to allow easy navigation of all Jobs using a search filter on the right-hand side of the page.  This feature request is to add the search filter to support searching by category, label, last status, and last run (date/range??) and to add `labels` to `Meta`.

While #882 adds categories to streamline the Jobs UX, users may still want to label jobs across categories.  This will allow the flexibility to narrow the focus of Jobs to a combination of categories and labels.

### User Story

As Ozzie the Operator,
I want to more easily find the jobs I need to execute by searching all Jobs based on one or more labels,
So that I can better support my network.

I know this is done when:

- Multiple labels can be added to a Job
- There is a search filter capability added to the Jobs page
- The category search is a multi-select option to search based on multiple labels

**Comment by jathanism** [comment]
This appears to point us back to the need for a first-class `Job` model as adding more searching/filtering/grouping features without database relationships will be ... clunky. More requirements needed.

**Comment by jedelman8** [comment]
I know we've talked about this without a new model.  What could be done without introducing a new Job model?
