### ISSUE TITLE
add ability to terminate Job early

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#884]
### Overview

From the epic in #765.

The proposal is to add the ability to terminate a Job early from the UI.  For a long-running Job or a Job that needs to be aborted for any reason, there needs to be a way to terminate the Job from the UI.

### User Story

As Ozzie the Operator,
I want the ability to terminate a Job early,
So that should there be any issues rooted from a Job, I know I can immediately stop that Job.

I will know this is done when:

- When users can stop a Job from the UI
- Have a status of "Terminated" in the Job results page to see all terminated Jobs?

**Comment by jathanism** [comment]
Under initial review we determined that while Celery does provide a mechanism to *revoke* a task, the cleanup of any transactional state, asserting logging and any other error-handling needs to be accounted for. Further requirements needed.

**Comment by jedelman8** [comment]
I know this was discussed a few backs ago, so I will rely on the greater community to drive this.  However, it sounds like you're aware of what needs to be done to "terminate" a job.  I'm not sure we need more user-facing requirements?  Thoughts?

**Comment by jedelman8** [comment]
Bump here too @jathanism and @glennmatthews .  Can you clarify what isn't clear about the requirements?

**Comment by jathanism** [comment]
Now that we're in the midst of moving to a database backend, state cleanup should be much, much easier and almost automatic. So we really just need think about the mechanism to enable the ability to send a revoke action to the control plane for workers. 

See: https://docs.celeryq.dev/en/stable/userguide/workers.html#revoke-revoking-tasks

**Comment by lampwins** [comment]
dup of #2088
