### ISSUE TITLE
Location Groups

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#892]
### Environment
* Python version: 3.9
* Nautobot version: 1.1.2

### Proposed Functionality
As Nelly the Network Engineer, I want to be able to group sites or locations in a generic way so I can model specific networking use cases, like multicast groups, DHCP or DNS regions.

### Use Case
#774 offers a solution for user-defined location hierarchies, but there is still a need for non-hierarchical groupings of locations to service a variety of real-world networking use cases. For example, I might need to model my NYC multicast metro area, which contains all my NYC sites, but also my data center which happens to reside in NJ. In another case, I might distribute my DHCP helper addresses geographically, but not necessarily in a way that fits within the hierarchical nature of the location mechanism. E.g. I might have defined a "North East US" region just for DHCP. Meanwhile, my DNS team might define the "North East US" to be a different grouping of states.

Assuming I am using config contexts to model the actual data today, I can address this by listing the grouping of the sites separately in the various config context objects. This is suboptimal because the grouping of sites is tightly coupled to and hidden within the config context and thus not easy to manage and reuse.

### Database Changes
I see this being implemented as a part of #774 however it could be implemented today as it is entirely new functionality. Ultimately we need a new model Group model with a many-to-many relationship to location/site and then to make the group usable in things like config contexts.

### External Dependencies
#774 unless we decide to implement prior.

**Comment by glennmatthews** [comment]
Seems closely related to the "dynamic groups" concept described in #768.

**Comment by jedelman8** [comment]
> Seems closely related to the "dynamic groups" concept described in #768.

Which we now have #896 for.  @lampwins can you confirm that matches what you're thinking here?

**Comment by lampwins** [comment]
It could cover this use case certainly but I have some general concerns over the UX for #896. In my location groups use case, I need Nelly the Network Engineer to be able to easily administer the groups and not require the assistance of Austin the Network Automation Engineer because of the likely complexity involved in the filtering/inclusion logic for dynamic groups.

**Comment by jedelman8** [comment]
What about if we have "Groups" with a type of _static_ and _dynamic_.  Does that go more in the direction you're thinking?

**Comment by lampwins** [comment]
Closing this in favor of simplified UX in #896
