### ISSUE TITLE
Add JSON type for custom fields

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#897]
### Overview

Users often need to support more advanced data structures as a custom field.  This would add support for a JSON type to this list of available options when creating a CF.

![image](https://user-images.githubusercontent.com/6332586/132504395-c59a3ccb-891c-4957-825e-e2c977704314.png)

### User Story 

As Austin a Network Automation Engineer,
I want to be able to create custom fields that can store JSON data,
so that I am not required to use config contexts.  This will allow me to ensure these fields are "required" when adding/editing objects.

### Acceptance Criteria

- [ ] Allows a CF to be of "JSON" data type
- [ ] Validates submitted data is valid JSON
- [ ] To view CF data of JSON type, a "View Value" link should be presented to see the full payload. This keeps the UI clean for large JSON values.
- [ ] Basic searching (`icontains`) of JSON custom fields in UI and API

### Out of Scope

- Is it NOT expected to be able to search into the field value

**Comment by sirtux** [comment]
I think this is a very desirable feature, right now I misuse the comment field for that, as a custom text field cannot be long enough...

**Comment by glennmatthews** [comment]
Would the idea here be to use JSON custom fields to store "large"/"complex" data that isn't more suitably represented as a collection of individual value custom fields (text/integer/boolean)?

It seems like if we go this direction we'd also want to link JSON custom fields with the JSON schema feature for format validation/enforcement - does this make sense as an additional requirement?

**Comment by jedelman8** [comment]
> Would the idea here be to use JSON custom fields to store "large"/"complex" data that isn't more suitably represented as a collection of individual value custom fields (text/integer/boolean)?

Yes, and data that inherently has some relationship and hierarchy to it. 

> It seems like if we go this direction we'd also want to link JSON custom fields with the JSON schema feature for format validation/enforcement - does this make sense as an additional requirement?

I didn't mention that as I thought we would have that as a separate issue and possibly not in the initial implementation. Thoughts?  Is it possible to use the implementation of the Context Schemas?

**Comment by sirtux** [comment]
> Would the idea here be to use JSON custom fields to store "large"/"complex" data that isn't more suitably represented as a collection of individual value custom fields (text/integer/boolean)?

Yes, for example I have VMs which have multiple assigned SSH Keys, and I don't know how many beforehand. So I have a JSON dict, which has this information. As well the storage information for a VM. 

The "right" way would be to extend all the models with the relevant stuff, but I'd like to stay with the default nautobot installation, as everything else will cause problems in the future (with updates) etc...

> It seems like if we go this direction we'd also want to link JSON custom fields with the JSON schema feature for format validation/enforcement - does this make sense as an additional requirement?

That would be cool - but I think a little bit grander: Why not having the relevant information from the schema available as direct fields, instead as one large JSON blob? I could then define my further required options without "coding", and maybe directly access and search for items in this json?

This, however, is a much larger scope then just adding the fields..

**Comment by jedelman8** [comment]
> That would be cool - but I think a little bit grander: Why not having the relevant information from the schema available as direct fields, instead as one large JSON blob? I could then define my further required options without "coding", and maybe directly access and search for items in this json? This, however, is a much larger scope then just adding the fields..

Yes, 100%.  From a practical perspective, we can build out the feature in 3 steps:  1) add JSON support (no schema) 2) add JSON schema support 3) look to auto-generate forms based on the schema.  For this FR, it is just 1.

**Comment by jedelman8** [comment]
Initially taking on the JSON support (no schema) per #1 above.

**Comment by sirtux** [comment]
Does this also need support in pynautobot as well?

**Comment by bryanculver** [comment]
Implemented with #1075.
