### ISSUE TITLE
Computed Fields - Include Options for Trim and Strip

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#902]
### User Story

As Nick the Nautobot Computed Field Creator,

I want to add white space into my Computed Field Jinja code while not having white space on the resulting computed field.

So that the API and visualization of computed fields are in a good state

I will know this is done when the Computed Field on the demo instance of

```
{% if obj.slug == 'arista_eos' %}
arista.eos.eos
{% elif obj.slug == 'cisco_asa' %}
cisco.asa.asa
{% elif obj.slug == 'cisco_ios' %}
cisco.ios.ios
{% elif obj.slug == 'cisco_xr' %}
cisco.iosxr.iosxr
{% elif obj.slug == 'cisco_xe' %}
cisco.ios.ios
{% elif obj.slug == 'cisco_nxos' %}
cisco.nxos.nxos
{% elif obj.slug == 'juniper_junos' %}
junipernetworks.junos.junos
{% else %}
{% endif %}
```
this will generate no white space, no `/n` on the result.

### Additional Info

Jinja typically has a few additional settings such as trim and lstrip/rstrip on it. These common flags should be exposed for the computed field so users can control what is done.

 
### Database Changes (Optional)

None

### External Dependencies (Optional)

Nine

**Comment by glennmatthews** [comment]
How much is this doable with Jinja's built-in whitespace control, a la:

```jinja2
{% for item in seq -%}
    {{ item }}
{%- endfor %}
```

? Are there specific cases where this is not sufficient and we need the global configuration flags instead?

**Comment by jvanderaa** [comment]
It's completely doable with the Jinja whitespace control, but is more of a user enhancement. With using things such as Ansible's automatic trim and stripping the JInja output is just easier.

To do what was necessary as part of a workaround provided we had to put the whitespace controls on both sides.

**Comment by bryanculver** [comment]
While a simple checkbox would be nice it can introduce its own edge cases or "it doesn't go far enough in X direction, therefor I just resorted to using native Jinja whitespace controls."

Until a clear enough reason why Jinja controls are insufficient, we will close this issue.
