### ISSUE TITLE
Add Computed Fields for Relevant Filters (Device, IPAM, etc) on Views

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#903]
### User Story

As Nick the Nautobot User

I want to filter devices, IP addresses, and other UI views by computed fields that are created,

So that I can use this to further filter down my list of devices or IP addresses that are viewed.

I will know this is done when:

* On device view, IP address view, prefix view, that the right hand filter options in the UI that the computed fields are there
* That the API can negate and search on computed fields as parameters

 
### Database Changes (Optional)

None that I am aware of

### External Dependencies (Optional)
None

**Comment by glennmatthews** [comment]
Related to (but not a duplicate of) #894.
