### ISSUE TITLE
Consolidate (simplify) UI for computed fields

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#905]
# Overview

Today, there are computed fields and custom fields.  Computed types are basically a _type_ of a custom field.  That can be seen if you look at the inputs required to create a custom field. The distinct inputs for computed fields are "template", "fallback value", and "slug" (need to consider #824?)  Taking this into consideration, it should be possible to simplify the UI and consolidate/collapse the computed field UI into the custom field view.  If this updates the API for custom fields, that is okay, but not required.  The existing API for computed fields should not break.

# User Story

As Austin the Network Automation Engineer, I find it quite confusing to navigate custom and computed fields in the UI.
I want to be able to more simply view all computed+custom fields in a single view,
So I can easily filter/see all computed+custom fields based on content type.

**Comment by glennmatthews** [comment]
To clarify the requirements, is this talking about:

1. The object detail view UI presentation of custom fields and computed fields applicable to the given object (currently two separate sections, possibly merging them together into a single section)?
2. The list UIs for displaying a summary of all currently defined custom or computed fields (currently two separate UIs, consolidating them into a single combined UI)?
3. The detail view UIs for inspecting the definition of a single custom or computed field (currently two separate UIs, consolidating them into a single combined UI)?
4. The form UIs for creating/updating custom fields and computed fields (consolidating them into a single combined UI)?
5. All of the above?

Thanks. :-)

**Comment by jedelman8** [comment]
All of the above, but it's always open for discussion.  

Maybe the "Template" goes into a tab in the object detailed view.  Would need some thought in the UI to finalize what the implementation would look like, but short answer is "yes" and "all of the above."

**Comment by glennmatthews** [comment]
While I can understand the desire for a simplified UI and feature set, this is non-trivial from both a design and implementation standpoint. Some thoughts as to the challenges involved:

- Fundamentally, computed field values are dynamic in value and are not present in the database, while custom field values are stored statically in the database. This poses any number of distinctions, such as querying/sorting/filtering (database operation for custom fields, not available for computed fields), performance implications (low for custom fields, potentially high for computed fields), editability (a computed field can be renamed after creation; a custom field may not), etc.
- Non-overlapping model fields - custom fields have (required, default, validation constraints, etc.) and computed fields have (template, fallback_value). If we really want to go this route it might be that the best option could be to combine the two data models into a single consolidated model, but this would definitely require a fair amount of additional validation/cleaning logic, not to mention the UI aspects of this.

**Comment by lampwins** [comment]
Given the multiple code paths in the existing implementation for custom fields, computed fields, and relationships, this is very non-trivial. Perhaps we defer this to a breaking change and look at a refactor of these three features at that time.

**Comment by dgarros** [comment]
As far as I understand, 2/ 3/ & 4/ represent a large among of work and might not provide a lot of value 
but 1/ should be fairly easy to implement without breaking anything and significantly improve the user experience. 

Would it be possible to focus on 1/ first : merging Custom and computed field in the object detail view UI ? without touching the API or the models ?

**Comment by lampwins** [comment]
Closing as we can revisit under larger UI refresh umbrella later.
