### ISSUE TITLE
Bless and support ability to create computed fields, custom fields, and relationships from plugins

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#906]
### Overview

While it possible to create custom fields, computed fields, and relationships from plugins, it is not well-documented or tested.  

### User Story

As P.D. a plugin developer,
I want to create computed fields, custom fields, and relationships from plugins following well-documented and tested good practices from the Nautobot core team,
So I can have greater confidence I'm doing things the _right_ way.

**Comment by glennmatthews** [comment]
This may already be covered by #820.
