### ISSUE TITLE
Allow serial number to be more than 50 characters

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#909]
### Environment
* Python version: 3.9
* Nautobot version: 1.1.2

### Proposed Functionality
As Dan the Data Owner, I want to be able to track devices with serial numbers greater than 50 characters in length.

### Use Case
Nautobot currently has a field length of 50 set on the dcim.device serial field. While this probably covers a large portion of the market, there do exist valid cases where serial numbers are longer than 50 chars. In a common case, I might track virtual networking gear as regular devices. In such a case I might track the VM's ID as its serial number, in which this VMware pattern is very common:
```
VMWARE-XX XX XX XX XX XX XX XX-XX XX XX XX XX XX XX XX
```
Which is 54 chars.

In particular, this comes up a lot when nautobot is being synced from another CMDB.

### Database Changes
Expand the length of the serial field to say 255

### External Dependencies
None

**Comment by glennmatthews** [comment]
For consistency we'd probably want to do the same for InventoryItem.serial and Rack.serial as well.

**Comment by glennmatthews** [comment]
Fixed in `next` (1.3.0) by #1197.
