### ISSUE TITLE
Job descriptions should support either markdown or raw html

### ISSUE THREAD

**Issue by retnuh** [nautobot/nautobot#916]
When rendering the description for a job, it would be nice if we could use either markdown or raw HTML.  As it is, for anything more complex than a single sentence, it's impossible to format correctly.

This is in Nautobot 1.1.2.

**Comment by lampwins** [comment]
The existing pattern would be to support markdown. We were thinking in the Job list page we would show the description up to the first line break and then in the Job detail page it would render the full description.

**Comment by glennmatthews** [comment]
Implemented in `next` (1.3.0) by #1202.
