### ISSUE TITLE
Allow global search by UUID

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#923]
### User Story

As Ozzie the Operator,

I want to be able to easily look up an object based only on its UUID, without needing to know the URL pattern required for a specific model class,

So that when I have only a UUID, such as I might get from a Change Log view:

![image](https://user-images.githubusercontent.com/5603551/133835001-6428266d-7d62-4493-903f-bf6c9256a273.png)

...I can easily look up any of the referenced objects based on the given UUID.

I will know this is done when I'm able to use the Nautobot home page's global search bar to locate an object based on its UUID alone.

![image](https://user-images.githubusercontent.com/5603551/133835221-9dd5c884-6bfe-4387-986c-ee744aba401d.png)

### Database Changes (Optional)

None

### External Dependencies (Optional)

None

**Comment by glennmatthews** [comment]
Should be doable by adding an `id__iexact` filter to the `search` method for all models. A bit tedious to implement, but not technically difficult.

**Comment by Thetacz** [comment]
> Should be doable by adding an `id__iexact` filter to the `search` method for all models. A bit tedious to implement, but not technically difficult.

I think this would be very easy and not tedious at all. Just need to add the filter to some common class all filters inherit from. Probably directly `nautobot.utilities.filters.BaseFilterSet` since AFAIK all object in Nautobot should have UUID.

**Comment by zackt25** [comment]
@glennmatthews can you please assign this to me. I've got it completed and ready for a pull request.

**Comment by bryanculver** [comment]
This was resolved by #1765 (via #1752)
