### ISSUE TITLE
Celery Not releasing threads

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot#934]
### Environment
* Python version: 3.7
* Nautobot version: 1.1.3

### Steps to Reproduce
1. Install Golden Config
2. Run backup

### Expected Behavior

When running a nornir task, to clear out sessions. My current understanding is this is what happens when the thread/process (not sure what the actual correct terminology is, and it may matter, so trying to be clear) dies.

### Observed Behavior
* Celery masks everything as a single thread
* Nornir connection doesn’t disconnect until the parent thread dies
* Celery never dies
* The connection never dies, and the ssh session is there until celery is restarted

This is likely operating as expected, hopefully there is guidance in how to avoid or settings to work around.

**Comment by jathanism** [comment]
Hmmm... Thanks for pointing this out. By default Celery workers use subprocesses. This concurrency can be controlled at the command-line, so it might be something we need to experiment with, or dig into some knobs with how the workers and their subprocesses behave.

See: https://docs.celeryproject.org/en/stable/userguide/workers.html#concurrency

Are there any specific conditions or device drivers being used by Nornir that we could focus on to reproduce this? For example, is it Nornir w/ Napalm? And if so, which platform? That will help narrow down and isolate if it's a threading vs. sub processing issue, especially if the SSH connection thread is blocking and preventing normal process cleanup from happening. Distributed computing is hard.

Thanks for any further detail you can provide!

**Comment by itdependsnetworks** [comment]
Here is a workaround on golden config https://github.com/nautobot/nautobot-plugin-golden-config/pull/128. For the other details, best to speak.

**Comment by jathanism** [comment]
To follow-up, there are a few important next steps here:

- Revise documentation on creating jobs that perform remote connections to always use context processors or explicitly close connections when complete
- Revise documentation on best practices for doing long-running and/or blocking tasks to avoid resource contention in workers
- Try to reproduce this to assert why without explicit connection closes that the thread persisted even after the job was completed and/or subprocess closed by the worker (e.g. why were soft/hard task timeouts ineffective?) and take it from there.

**Comment by itdependsnetworks** [comment]
To the first 3 points I agree, to the last one, I am not sure

**Comment by lampwins** [comment]
Do we still need to act on this? I think we were just going to address this via docs.

**Comment by itdependsnetworks** [comment]
It would be great to go through some documentation. I think ultimately this was a red-herring, but the following was not clear:

* when/how does a job/celery connect to the db? does it create a new session?
* what happens with long running tasks? 
* Can we kill current tasks?
