### ISSUE TITLE
Scheduled Jobs screen has checkbox for items but no actions to take on checked items

### ISSUE THREAD

**Issue by tim-fiola** [nautobot/nautobot#937]
### Environment
* Python version: 3.8
* Nautobot version: 1.2.0a1 (next branch)

### Steps to Reproduce
1. Schedule some jobs
2. Go to Scheduled Jobs screen
3. There is a checkbox by each scheduled job, but no action to take on checked items appears on this screen

![image](https://user-images.githubusercontent.com/13647153/134408805-540bab0b-61ba-4c52-86b8-fa6d6398c30b.png)

### Expected Behavior
There would be actions/buttons on the Scheduled Jobs page to act on the checked item(s).  I'd expect that the `Delete` button would be available on this page

### Observed Behavior

No actions can be taken on checked items on this screen.  For example, to delete this job, I had to click on the job and then on the screen for the specific job, I could delete it.

![image](https://user-images.githubusercontent.com/13647153/134409069-fa707f64-2b67-460e-9831-70542f65087c.png)

**Comment by glennmatthews** [comment]
Addressed in `next` by #942.
