### ISSUE TITLE
Rack elevation renderings not shown when X-Frame-Options is set to DENY

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#939]
### Environment
* Python version: 3.6.8
* Nautobot version: 1.1.3

Checking button to show images does not do anything.
![image](https://user-images.githubusercontent.com/26114847/134506213-6d195923-9f07-4261-9118-41127837180a.png)
![image](https://user-images.githubusercontent.com/26114847/134506238-295bf5c7-e9ad-462f-b48d-b7c1d4fe4fb4.png)
To be able to see organization of devices in rack I have to click on `Save SVG` on both front and rear.
Note: `Save SVG` does not clearly describe what is shown - it is SVG with interactable overlay. It does not trigger "save file" dialog.
### Steps to Reproduce
1. open `/dcim/racks/:uuid`
2. click `Show Images` button
3. expect images shown

### Expected Behavior
No change at all

### Observed Behavior
Images shown

Note:
Not sure if the button ever worked, in old Netbox 2.5.13 there is no button and the images are shown directly:
![image](https://user-images.githubusercontent.com/26114847/134506800-878e848a-232e-400b-bf15-933b5f10ef6d.png)

**Comment by glennmatthews** [comment]
The "Show Images" toggle is supposed to switch between whether device-type images are shown in the rack elevation or whether the simpler colored-boxes rendering is shown  - a rack elevation image should be visible regardless in either case. Can you check your browser console to see if any errors are being reported?

**Comment by Thetacz** [comment]
Glen, thanks for the quick answer. I found I cannot see any images due to `X-FRAME-OPTIONS` set to `DENY` for security reasons. I set it to `SAMEORIGIN` for now and discuss with InfoSec the implications.
Adding any image to the corresponding device type correctly shows

**Comment by Thetacz** [comment]
Note: Setting the value to anything but `DENY`will cause security warning on Nautobot startup:
![image](https://user-images.githubusercontent.com/26114847/134520207-a43aef78-f11d-42be-b96a-a35b363220cd.png)

**Comment by glennmatthews** [comment]
A few options offhand:

- Per https://docs.djangoproject.com/en/3.2/ref/clickjacking/, it looks like we could possibly add the `@xframe_options_sameorigin` specifically to the `nautobot.dcim.api.views.RackViewSet.elevation` view function so that it sets SAMEORIGIN even if we're set to DENY globally - this might be the best option
- [Silence the warning](https://docs.djangoproject.com/en/3.2/ref/settings/#std:setting-SILENCED_SYSTEM_CHECKS) by setting `SILENCED_SYSTEM_CHECKS=["security.W019"] - not always a desirable option, obviously, but I present it for sake of completeness :-)

**Comment by glennmatthews** [comment]
Reopening this for visibility to the team. :-)

**Comment by glennmatthews** [comment]
Based on some initial testing, using the `@xframe_options_sameorigin` decorator on the elevation view, in combination with setting the global default to `DENY`, appears to address this issue. I should have a PR open soon.

**Comment by Thetacz** [comment]
Thank you Glen, nice work.
