### ISSUE TITLE
Implement user guide for using git as a data source

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#97]
### Proposed Changes

Add user guide for using Git repos as data sources.  

### Justification

As a new feature, there aren't many examples on this.  The guide should highlight the different use cases using the `https://github.com/nautobot/demo-git-datasource` repo.  Create new branches in there as needed to showcase different examples in the user guide.

**Comment by jeffkala** [comment]
@glennmatthews I'll take this one.  If you want to assign it to me.

**Comment by jeffkala** [comment]
Or maybe I should ask is this already done, appears to be: https://nautobot.readthedocs.io/en/latest/models/extras/gitrepository/

**Comment by glennmatthews** [comment]
That's more of a technical reference to how the feature works. It would still be great to create a separate (though perhaps heavily cross-referenced) user guide - less focused on "how does this work?" and more focused on "how can I use this to solve my real-world challenges?" - think fully worked examples (using data added to the demo-git-datasource repo) with screenshots, etc.

**Comment by jeffkala** [comment]
Great, I can handle that @glennmatthews , Is there a specific documentation style we're following for user-guides?  Or just a md file?

**Comment by jedelman8** [comment]
We don't have a style yet per se, but to re-iterate what @glennmatthews, it should very much be focused on _using_ the feature.  Common examples and scenarios should drive it.  The first PR for a user guide should add a section "User Guides" to the RTD outline too.

@jeffkala what's your timing on this? We are looking to come out of beta this month and need to see what user guides will make it for 1.0.0 and which ones we should move to 1.1.0.  L

**Comment by jeffkala** [comment]
@jedelman8 Great, I'm working on it now.  Hopefully I'll have a nice initial draft for review in the next day or so.  I've used the git piece quite a bit when working with Ken on the golden config plugin.  I just need to get some examples for export templates and jobs.

**Comment by jeffkala** [comment]
@jedelman8 @glennmatthews , initial draft is up in a PR 184.  Hopefully this is what we're looking for.
