### ISSUE TITLE
Simplify MultipleContentTypeField boilerplate

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#98]
### Proposed Changes

Followup to #92 - Provide a custom `__init__` method for the MultipleContentTypeField class, so that we can more simply instantiate it, along the lines of:

```python
source_type = MultipleContentTypeField(feature="relationships", required=False, label="Source Type")
```

Possibly something similar should also be implemented for `CSVMultipleContentTypeField`?

### Justification

Currently there's a lot of boilerplate in instantiating a MultipleContentTypeField, particularly in constructing and ordering the queryset correctly.

```python
    source_type = MultipleContentTypeField(
        queryset=ContentType.objects.filter(FeatureQuery("relationships").get_query()).order_by("app_label", "model"),
        required=False,
        label="Source Type",
        widget=StaticSelect2Multiple(),
    )

    destination_type = MultipleContentTypeField(
        queryset=ContentType.objects.filter(FeatureQuery("relationships").get_query()).order_by("app_label", "model"),
        required=False,
        label="Destination Type",
        widget=StaticSelect2Multiple(),
    )
```

It would be nice if we could instantiate it with a simple `feature="relationships"` and have the appropriate queryset get automatically constructed and ordered. It also probably makes sense for this field to default to using a `StaticSelect2Multiple` widget instead of requiring that to be manually specified each time.

**Comment by jedelman8** [comment]
@glennmatthews can you take this for 1.0.0 ?
