### ISSUE TITLE
Add support for additional arguments in NavMenuItem 

### ISSUE THREAD

**Issue by dgarros** [nautobot/nautobot#983]
### Environment
* Python version: 3.7
* Nautobot version: 1.1.4

### Proposed Functionality
Add support for additional arguments in NavMenuItem 
Today it's possible to add a link or a button anywhere in the menu as part of a plugin but the link must be a valid django url name and it's not possible to define additional parameters

> As far as i understand the link in the NavMenuItem are being resolved with [resolve()](https://docs.djangoproject.com/en/3.2/ref/urlresolvers/) from django and this function supports `args` and `kwargs`

### Use Case
I would like to add a link in the menu that is pointing at a specific Object view or a specific Job and not a list view
Also for some links I would like to add some additional parameters to the URL to auto-populate some fields in a form

### Database Changes
No

### External Dependencies
No

**Comment by jrpell** [comment]
Just leaving a comment to say this is something I'm definitely wanting too. Was directed here to leave a comment so maybe it'll get some more attention. :)  Specifically the ability to link a Nav item directly to a job. Thanks!

**Comment by glennmatthews** [comment]
Relatedly, it would also be useful if the `PluginConfig` `home_view_name` and `config_view_name` attributes could also be extended to support inclusion of parameters - say if I want the "home view" for a given plugin to be the Job submission page for a specific job provided by the plugin.
