### ISSUE TITLE
Add status field to Interface model

### ISSUE THREAD

**Issue by dgarros** [nautobot/nautobot#984]
### Environment
* Python version: 3.7
* Nautobot version: 1.1.4

### Proposed Functionality
Extend the Interface model as part of the DCIM app with a proper Status field based on the existing Statuses.
Of course, it's possible to create a custom field for it but having a primary field that is mandatory would improve the user experience and ensure that a status is always define. Also the way the rendering of this field in the UI will be improved with the color etc ..

### Use Case
As Nelly the network engineer I need to drain the traffic on a specify interface without shutting it down completely, for that I would like to apply the status `Drained` to `Maintenance` on each interface individually.

### Database Changes
Extend the interface model with FK relationship to the Statuses model

### External Dependencies
No

### Requirements
- `status` is a new mandatory field on `Interface`
- REST API would need to be versioned
- This does not replace `enabled` field
- Default statuses are: Active, Planned, Maintenance, Failed and Decommissioned
- Default value for migration, legacy API would be "Active"
- "Active" becomes a another status that is unsafe to delete (see: #1169, not requirement for this issue)

**Comment by lampwins** [comment]
What set of default statuses should we ship with and what should the default value be applied to all existing interfaces, provided the requirement is to make this a mandatory field?

**Comment by sirtux** [comment]
I’d vote for the existing stati, no new ones, and default state “Active”.
