### ISSUE TITLE
JobResult Page Slow Loading

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#992]
### Environment
* Python version: 3.8.10
* Nautobot version: 1.1.4

### Steps to Reproduce
1. Execute Jobs via Golden Config Plugin, or self written
2. Navigate to primary JobResult page (Extensibility -> Job Results)
3. Page takes a long time to load compared to other pages (43 results)

### Expected Behavior

Expected the page to load with relative expedience. 

### Observed Behavior

At least 45 seconds to load, the timer executed was at 50 seconds

**Comment by glennmatthews** [comment]
Fixed by #1030.
